### ISSUE TITLE
SSH server documentation improvement needed

### ISSUE THREAD

**Issue by lhanson** [home-assistant/addons#1388]
I'm trying to get external SSH access to my new Home Assistant instance. After discovering that I need to install the "SSH server" add-on, I do that via the Supervisor. [README.md](https://github.com/home-assistant/hassio-addons/blob/master/ssh/README.md) doesn't actually provide any useful information, and by chance I happen to browse the repository and discover [DOCS.md](https://github.com/home-assistant/hassio-addons/blob/master/ssh/DOCS.md). Why is this a separate document from the readme, and as such is *not* actually displayed in the Supervisor web UI? Wouldn't it be infinitely more useful to display usage documentation right in Home Assistant?

Now referencing DOCS.md, the **How to use** section looks promising, but begins "_You need enable the port for external access. You can just enter 22 as value or any other value like you want. This recommend to add login credentials._" Enable the port for external access *how*, and enter the port number *where*? The add-on install process doesn't prompt for any values.

Then, in the **Configuration** section, I see a snippet of what is apparently YAML for configuring an authorized key. Okay, great; but where does this configuration live, and how do I access it?

**Comment by ekendra-nz** [comment]
:(
