### ISSUE TITLE
letsencrypt: propagation_seconds setting is not honored

### ISSUE THREAD

**Issue by Twanislas** [home-assistant/addons#1424]
Hi !

It looks like the DNS propagation seconds setting of letsencrypt is not honored :
```
[18:37:42] INFO: Selected DNS Provider: dns-ovh
[18:37:42] INFO: Use propagation seconds: 120
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator dns-ovh, Installer None
Obtaining a new certificate
Performing the following challenges:
dns-01 challenge for <REDACTED>
Waiting 30 seconds for DNS changes to propagate
Waiting for verification...
Challenge failed for domain <REDACTED>
dns-01 challenge for <REDACTED>
Cleaning up challenges
Some challenges have failed.
IMPORTANT NOTES:
 - The following errors were reported by the server:
   Domain: <REDACTED>
   Type:   dns
   Detail: DNS problem: NXDOMAIN looking up TXT for
   _acme-challenge.<REDACTED> - check that a DNS record exists
   for this domain
```

Thanks for your consideration :)

**Comment by Twanislas** [comment]
Still an issue, thanks StaleBot.

**Comment by Twanislas** [comment]
Still an issue, thanks StaleBot.

**Comment by samuelalexmclean** [comment]
I'm seeing this too. It's gross, but you can manually tweak dns_common.py to work around it (I hard coded 600 and it worked).

I'll see if I can work out where in all the plumbing the number falls out, just reading it everything looks like it should work... but it clearly doesn't. I tried to fix it in a few places upstream and it didn't take, so I think dns_common is a good place to start the investigation.

**Comment by baizej** [comment]
I was just looking at this myself and I think I see it, but don't know nearly enough Docker to do testing.  I notice on many DNS providers that the PROVIDER_ARGUMENTS has the propagation seconds at the end, but nothing exists for the "else" catch all.

Example for Cloud Flare:
```
PROVIDER_ARGUMENTS+=("--${DNS_PROVIDER}" "--${DNS_PROVIDER}-credentials" /data/dnsapikey "--dns-cloudflare-propagation-seconds" "${PROPAGATION_SECONDS}")
```
And the last else statement:
```
#All others
else
    PROVIDER_ARGUMENTS+=("--${DNS_PROVIDER}" "--${DNS_PROVIDER}-credentials" /data/dnsapikey)
fi
```

My guess, since I can't test in the Docker image, is we need a RFC2136 section with the following line:
```
    PROVIDER_ARGUMENTS+=("--${DNS_PROVIDER}" "--${DNS_PROVIDER}-credentials" /data/dnsapikey "--dns-rfc2136-propagation-seconds" "${PROPAGATION_SECONDS}" )
```

**Comment by samuelalexmclean** [comment]
Cool, I'll see if I can try this out! There are probably better ways to test, but I've had success with "sudo find / -name dns_common.py". The path will be really messy but if you open it up in pico etc your changes will be reflected next time you restart the addon.

**Comment by baizej** [comment]
Still an issue.  Guess incentive to learn git. :)

**Comment by chriscpritchard** [comment]
Still an issue

**Comment by jorisdobbelsteen** [comment]
and there is a PR with patch ...

**Comment by igogold** [comment]
I'm also have the same issue. Value of dns.propagation_seconds just ignored when used with dns-rfc2136 provider. I set 120 seconds but certbot runs with default value (60s) and renew fails after such time delay.

Is it possible to run docker container and stay it running? It finishes after (successful or unsuccessful) certbot run so I'm unable to run certbot manually with modified command line. I'm in risk to expire my TLS cert and get DoS for HA.

**Comment by GraithTiger** [comment]
Still an issue here with linode.

**Comment by mateuszdrab** [comment]
Still an issue, a year and no fix 😒
