### ISSUE TITLE
OZW Addon does not persist application preferences

### ISSUE THREAD

**Issue by davidkaplan** [home-assistant/addons#1552]
## The problem

User modified application preferences do not seem to persist between sessions.  I'm using the WebUI ozw-daemon and attempting to manually change File->Preferences->Network->Network Object Cache.  Whenever the container is restarted, it reverts back to its default value of 1000, no matter what I had it set to in the previous session.

## Environment

- Add-on with the issue: OpenZWave
- Add-on release with the issue: 0.5.2
- Last working add-on release (if known): 
- Operating environment (OS/Supervised): Supervisor 235, HA Core 0.114.0, Host HassOS 4.12

## Problem-relevant configuration

```
device: /dev/serial/by-id/usb-0658_0200-if00
network_key: ''
```

**Comment by kpine** [comment]
Also https://github.com/OpenZWave/qt-openzwave/issues/111.

**Comment by crkochan** [comment]
This should probably be re-opened as this is still an issue.

Not only that, if I forget to adjust this prior to connecting, ozw-admin throws an error and crashes which causes the entire container to exit.

**Comment by johnboiles** [comment]
RIP OpenZWave anyways
