### ISSUE TITLE
When requesting certificates for multiple domains, only the certificate for the last domain is accessible

### ISSUE THREAD

**Issue by arnoo** [home-assistant/addons#1555]
## The problem
When requesting certificates for multiple domains, only the certificate for the last domain is accessible

## Additional information
I see in the code that this is by design, but don't see the point. I use two domains on my ha instance, one for HA and one for the Matrix addon, and think it would make sense to copy all the certificates certbot acquires to the /ssl share so that they can all be used.

**Comment by MizterB** [comment]
I just set up this add-on and discovered the same issue.  The logic of only copying the "last" updated certificate to the default location doesn't make any sense when intentionally requesting multiple domain certificates.  I would expect that all domains in Let's Encrypt's "live" directory are copied over to the SSL share.  I understand that most add-ons expect HA's certificate files to be in the root of the SSL share, and they would need to be accommodated.  Maybe the config needs to differentiate between the HA domain and additional ones.  

If that cannot be resolved, we should not be allowing the user to request certificates for multiple domains that are just going to remain stuck in a data directory that is not user accessible.

I have traced "last domain" change back to [Pull Request #1166 ](https://github.com/home-assistant/hassio-addons/pull/1166/files), which was created by @pvizeli. 

Pascal, do you have any thoughts on the concerns raised above?  Thank you!

**Comment by arnoo** [comment]
Backwards compatibility would be pretty easy to maintain by copying all certificate folders, and adding a symlink to the certificate for the first or last listed domain in the current place (i.e. where other addons currently look for a certificate by default).

I'd offer a pull request, but I'm afraid setting up the dev environment will take me much longer than writing the patch.
