### ISSUE TITLE
Deconz phoscon interface keeps asking for password

### ISSUE THREAD

**Issue by domoritz** [home-assistant/addons#1556]
## The problem
Every time I want to open the phoscon interface, I get asked for the password. It is very cumbersome. I would expect the home assistant configuration to automatically put in the password. 

## Environment

- Add-on with the issue: Deconz
- Add-on release with the issue: 6.2.3
- Last working add-on release (if known): na
- Operating environment (OS/Supervised): Supervised

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```txt

```

**Comment by Mimiix** [comment]
As far as i know, that won't be possible. This is due to the fact Phoscon doesn't have a option to save a session / password.

I think you need to open a feature request [here](https://github.com/dresden-elektronik/phoscon-app-beta)

**Comment by domoritz** [comment]
Thanks for the insight. I filed https://github.com/dresden-elektronik/phoscon-app-beta/issues/189.

**Comment by domoritz** [comment]
https://github.com/dresden-elektronik/phoscon-app-beta/issues/189 has been closed but is actually not fixed yet.
