### ISSUE TITLE
Snapshot of MariaDB Add-on likely corrupt

### ISSUE THREAD

**Issue by stewartsmith** [home-assistant/addons#1575]
## The problem

When creating a Snapshot to download from the HA Web UI, the MariaDB portion is just a copy of the data directory. Seeing as this is not done with `mysqldump` or 'xtrabackup`, it means that writes may be ongoing as the files are copied, which render the copy corrupt.

i.e. by default, the 'snapshot' cannot be consistent for the MariaDB database.

## Environment

Applies to all environments.

- Add-on with the issue: MariaDB
- Add-on release with the issue: All
- Last working add-on release (if known): Never
- Operating environment (OS/Supervised): All

## Problem-relevant configuration

```yaml
recorder:
  db_url: mysql://homeassistant:XXXXXXX@core-mariadb/homeassistant?charset=utf8
  
```

## Traceback/Error logs

```txt

```

## Additional information
The correct behaviour should be that when you create a Snapshot of the MariaDB database, it either uses `mysqldump` or `xtrabackup` to create a consistent copy of the data. Anyone currently successfully using the snapshot to restore a MariaDB database is getting a non-corrupt database purely by accident.

**Comment by jrial** [comment]
Does this still happen?

**Comment by oncleben31** [comment]
It happened to me yesterday

**Comment by svh1985** [comment]
One option would be to quickly stop MariaDB before the backup or restore. I used that trick when a restore did not work due to corrupt data.

**Comment by stewartsmith** [comment]
Stopping/Starting MariaDB before/after backup is more of a workaround, and does cause an outage. The `mysqldump` utility that ships with it can get a logical (SQL) backup that's consistent without a problem and not have downtime.

**Comment by oncleben31** [comment]
@stewartsmith Have you an example of implementation of this ?

**Comment by jrial** [comment]
Unstale.

**Comment by xzwr** [comment]
Still not solved.

**Comment by Delta1977** [comment]
Still open. At Moment Mariadb-Addon Snapshots / Backup is unusable.
This should be resolved as other Addons like "Home Assistant Community Add-on: Nginx Proxy Manager" depends on mariadb

**Comment by stewartsmith** [comment]
It doesn't look like anything has changed. The backup tarballs still contain a copy of the MariaDB data directory, and unless there's extra XtraBackup steps being performed behind the scenes, then this is still basically just a corrupt copy of the database as part of the "backup"

**Comment by ludeeus** [comment]
There is, it was implemented in <https://github.com/home-assistant/addons/pull/2063>
