### ISSUE TITLE
OpenZWave 0.6.0 not starting due to missing vnc_lite.html

### ISSUE THREAD

**Issue by GeertvanHorrik** [home-assistant/addons#1582]
## The problem

Just upgraded to 0.6.0. The previous version was working fine. Now getting this output:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] auth.sh: executing... 
[23:19:55] INFO: Auth database exists
[cont-init.d] auth.sh: exited 0.
[cont-init.d] mqtt.sh: executing... 
[23:19:56] INFO: Connected to internal MQTT service
[cont-init.d] mqtt.sh: exited 0.
[cont-init.d] network_key.sh: executing... 
[cont-init.d] network_key.sh: exited 0.
[cont-init.d] novnc.sh: executing... 
sed: /usr/share/novnc/vnc_lite.html: No such file or directory
[cont-init.d] novnc.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] mqtt.sh: executing... 
[23:19:57] INFO: Ensure upstream MQTT server has the correct OZW status
[cont-finish.d] mqtt.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

## Environment

- Add-on with the issue: OpenZWave
- Add-on release with the issue: 0.6.0
- Last working add-on release (if known): 0.5.4
- Operating environment (OS/Supervised): HassOS 4.13

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```txt

```

**Comment by Veldkornet** [comment]
I have the problem as well after updating to 0.6.0.

**Comment by miouzikal** [comment]
Same here. :(
Addon was working fine before

**Comment by dfortescue** [comment]
Same issue for me. Just updated this morning.

**Comment by Veuchez** [comment]
Same problem with update 0.6.0

**Comment by SimonG-GH** [comment]
Same here

**Comment by schildgenb** [comment]
same problem here

**Comment by callahan17** [comment]
Same here, couldn't update to 0.5.3 issue #1572, but now 0.6.0 has installed but does not start,  logs as above. No Zwave.

**Comment by t3miLo** [comment]
experience the same when upgrading to `0.6.0` had to revert to ` 0.5.2` to get my zwave back up.

**Comment by gcorgnet-vista** [comment]
what's the best way to revert to `0.5.2`, please?

**Comment by t3miLo** [comment]
> what's the best way to revert to `0.5.2`, please?

I was able to use one of my previous snapshot and just reverted ozwave

**Comment by Madelaide** [comment]
same, awesome...

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] auth.sh: executing... 
[10:40:07] INFO: Auth database exists
[cont-init.d] auth.sh: exited 0.
[cont-init.d] mqtt.sh: executing... 
[10:40:10] INFO: Connected to internal MQTT service
[cont-init.d] mqtt.sh: exited 0.
[cont-init.d] network_key.sh: executing... 
[cont-init.d] network_key.sh: exited 0.
[cont-init.d] novnc.sh: executing... 
sed: /usr/share/novnc/vnc_lite.html: No such file or directory
[cont-init.d] novnc.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] mqtt.sh: executing... 
[10:40:10] INFO: Ensure upstream MQTT server has the correct OZW status
[cont-finish.d] mqtt.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

**Comment by GeertvanHorrik** [comment]
One of the things I am thinking about is to create my own add-on "repository". Then you can choose what versions are actually available and install the "latest" stable from there. Will let you know how it goes.

**Comment by sanderlv** [comment]
> 
> 
> One of the things I am thinking about is to create my own add-on "repository". Then you can choose what versions are actually available and install the "latest" stable from there. Will let you know how it goes.

Yes! The dock "drop-down-select-whatversion-you-want-or-latest" a-like :-)

**Comment by GeertvanHorrik** [comment]
**!!! WORKAROUND ONLY - AT YOUR OWN RISK !!!**

1. Copy the current config and store it so you have easy access to it
2. Remove the old integration
3. Add this custom addon repository: https://github.com/GeertvanHorrik/hassio-addons-repo
4. Install openzwave
5. Paste your config
6. Start the extension

Note that this is a workaround and will not support auto updates. You will have to redo the revert, but at least this should unblock for everyone.

I tested this, so far so good. But again, **use at your own risk**. The "only" thing I noticed is that you need to await the refresh of the devices since the zwave config seems gone (but not your devices, that's stored in the controller).

**Comment by Ascariota** [comment]
Same error, I restore my snapshot with old version.

**Comment by foxy82** [comment]
Is it possible to revert to 0.5.2 using a Docker command?
Or is it possible to upgrade from 0.4.X to 0.5.2 as my snapshot has a really old version.

**Comment by neildownie** [comment]
Same problem here. No Z-Wave :-(

**Comment by bruxy70** [comment]
Me Too

**Comment by hmorkemo** [comment]
And me. An immediate official fix will be very much appreciated!

**Comment by hmorkemo** [comment]
The workaround mentioned above installs and starts, but now all my z-wave device names are gone, and the HA integration seems to be messy. So I'm still waiting for the official fix...

**Comment by GeertvanHorrik** [comment]
> The workaround mentioned above installs and starts, but now all my z-wave device names are gone, and the HA integration seems to be messy. So I'm still waiting for the official fix...

Only in the admin tool. The mappings in home assistant are done via node ids so everything should keep working?

**Comment by hmorkemo** [comment]
> > The workaround mentioned above installs and starts, but now all my z-wave device names are gone, and the HA integration seems to be messy. So I'm still waiting for the official fix...
> 
> Only in the admin tool. The mappings in home assistant are done via node ids so everything should keep working?

Works now! After I restarted HA it's ok. Thanks!

**Comment by Quart666** [comment]
Same problem

**Comment by MartinHjelmare** [comment]
We decided to roll back the add-on to the 0.5.2 image.

https://github.com/home-assistant/hassio-addons/pull/1583

This should show up as an update in the Supervisor dashboard.

**Comment by ThePirat91** [comment]
> 
> 
> We decided to roll back the add-on to the 0.5.2 image.
> 
> #1583
> 
> This should show up as an update in the add-on panel.

When will this 'update' be rolled out?
I cannot see it yet on my instances and I have 45+ devices offline since this morning....
Thanks!

**Comment by lukewaite** [comment]
> When will this 'update' be rolled out?
> I cannot see it yet on my instances and I have 45+ devices offline since this morning....
> Thanks!

If you run `ha addons reload` on the CLI it should be available in the UI as an update after that. 

You can use the core ssh add on web terminal if you don’t have handy access to the cli already.

**Comment by MartinHjelmare** [comment]
You can also try to reload the add-on store in the GUI.

**Comment by ThePirat91** [comment]
> 
> 
> You can also try to reload the add-on store in the GUI.

Ok, reloading the store just worked and all my devices are newly alive.
Thanks guys!

**Comment by ngergely** [comment]
I know it can be frustrating having something break with an update, but I've got to commend the folks working in this project.  The speedy response and roll-back resolution is commendable.  I for one am loving seeing the evolution of this project.  Thanks

**Comment by hmorkemo** [comment]
We must all remember that this is a community project with limited development resources available.
Having something like this happen once in a while is to be expected (but hopefully not too often...).
For important add-ons like this one, I have the automatic upgrade option turned off, so I have a chance to make a backup/snapshot before I upgrade.
Your response to this problem was impressive. So keep up the good work, guys!

**Comment by Veldkornet** [comment]
We're there problems in 0.5.3 that it was rolled back to 0.5.2?

**Comment by MartinHjelmare** [comment]
- 0.5.3: failed to build on all architectures.
- 0.5.4: ozw-admin didn't work in all architectures.
- 0.6.0: failed to run successfully.

**Comment by moto3001** [comment]
Running HassOS VM on a NUC 64-bit w/ a Zwave USB stick.  OZW 0.5.3 and 0.5.4 worked fine but 0.6.0 broke it.  Reverted back to 0.5.2 via snapshot, since that was the latest one backed up.

**Comment by neildownie** [comment]
![Screenshot 2020-09-17 at 19 02 51](https://user-images.githubusercontent.com/23356892/93510728-9951e080-f919-11ea-9d27-7a123248e9ef.png)
So this helps.....

**Comment by chaddy1701** [comment]
Processed the 'update available' and reinstalled 0.5.2 but the add on wouldn't restart. Had to restore a snap shot.

**Comment by randybnl** [comment]
The downgrade to 0.5.2 did work, but are there plans on fixing this issue and updating the OpenZWave version to 0.6.0?

**Comment by MartinHjelmare** [comment]
Yes, but we have no ETA.
