### ISSUE TITLE
OZW no mouse cursor in WebUI

### ISSUE THREAD

**Issue by ve6rah** [home-assistant/addons#1584]
## The problem
When using the webui for the openzwave add-on, I have no mouse cursor in the embedded VNC client. If I move the mouse into the VNC window and click, it does work, I just can't see where it is and have to guess.

## Environment

- Add-on with the issue: openzwave
- Add-on release with the issue: 0.5.2
- Last working add-on release (if known): unknown, suspect never
- Operating environment (OS/Supervised): HassOS 4.13

## Traceback/Error logs

```txt

```

## Additional information
using this in chrome 86.0.4240.27

**Comment by GeertvanHorrik** [comment]
I have this on my *laptop* (trackpad) as well. But whenever I use my other computer (desktop), it shows a mouse cursor.

**Comment by soleen** [comment]
The same on my laptop with trackpad.

**Comment by boehmap** [comment]
Same, no mouse in openzwave

**Comment by munklinde** [comment]
I see the same in the WebUI for OZW.

The OZW Admin application runs well with remote connection to your HomeAssistant server.
https://github.com/OpenZWave/ozw-admin
I use it from Ubuntu workstation

**Comment by ve6rah** [comment]
This issue still persists, however as it appears ozw is being depreciated, I've switched to zwave-js which does not have this problem.
I'm suspecting this bug falls into the "won't fix" category for this reason.
