### ISSUE TITLE
Devices cannot connect to mqtt (Connect failed to X.X.X.X:1883, rc -2. Retry in 10 sec) 

### ISSUE THREAD

**Issue by stranim** [home-assistant/addons#1595]
## The problem

Today with no apparent reason all my sonoff devices (running Tasmota), but two, cannot connect to MQTT receiving the message:
   Connect failed to X.X.X.X:1883, rc -2. Retry in 10 sec 

The problem raised also in the past randomly limited to one or two devices each time. It usually solves autonomously after some time

## Environment

Hassio 0.115.2
Mosquitto broker
Current version: 5.1
Tasmota versions: 8.2.0, 8.3.1
Devices: Sonoff Basic R2 - V1.0, Sonoff RF R2 POWER - V1.0, Sonoff Mini, Sonoff Dual R2, BlitzWolf BW-SHP6, Shelly 1

- Add-on with the issue: Mosquitto broker
- Add-on release with the issue: 5.1
- Last working add-on release (if known): 5.1
- Operating environment (OS/Supervised): Supervised

## Problem-relevant configuration

```yaml
logins:
  - username: *****
    password: *****
anonymous: false
customize:
  active: false
  folder: mosquitto
certfile: fullchain.pem
keyfile: privkey.pem
require_certificate: false
```

## Traceback/Error logs

```txt
log from tasmota console:

19:09:12 MQT: Connect failed to X.X.X.X:1883, rc -2. Retry in 10 sec
19:09:23 MQT: Attempting connection...
19:09:28 MQT: Connect failed to X.X.X.X:1883, rc -2. Retry in 10 sec
19:09:39 MQT: Attempting connection...
19:09:44 MQT: Connect failed to X.X.X.X:1883, rc -2. Retry in 10 sec
19:09:55 MQT: Attempting connection...
19:10:00 MQT: Connect failed to X.X.X.X:1883, rc -2. Retry in 10 sec

```

**Comment by rexsububi** [comment]
Same issue here:
Attempting MQTT connection...failed, rc=-2 try again in 5 seconds
Attempting MQTT connection...failed, rc=-2 try again in 5 seconds
Attempting MQTT connection...failed, rc=-2 try again in 5 seconds
Attempting MQTT connection...failed, rc=-2 try again in 5 seconds

**Comment by tech-freak** [comment]
i have to restart my esp or "Mosquitto broker" add on to get it working again but ESP stops subscribing again after random interval , publishing works fine though

**Comment by rexsububi** [comment]
> i have to restart my esp or "Mosquitto broker" add on to get it working again but ESP stops subscribing again after random interval , publishing works fine though
> 
> ps : using pubsubclient library

Was able to resolve my issue with a restart. Pubsubclient library helped, thanks.

**Comment by tech-freak** [comment]
> Was able to resolve my issue with a restart. Pubsubclient library helped, thanks.

welcome buddy but that's the temporary solution , it will stop subscribing randomly after few hours

**Comment by ludeeus** [comment]
What did the add-on log show?
From what I read here, it's the clients that have issues, not the broker (add-on)

**Comment by vanarebane** [comment]
same problem here, been over configuration and tried many way's to configure (ip, ports, users, etc)

**Comment by stranim** [comment]
I solved the problem by upgrading my modem, the old one was suffering the number of connected devices with memory and cpu often 100%. I also reinstalled HASSIO and Mosquitto on a larger SD
