### ISSUE TITLE
Polling Interval

### ISSUE THREAD

**Issue by broyuken** [home-assistant/addons#1597]
## The problem

No way to set polling interval with open zwave beta

## Environment

HA Core 0.115.2

- Add-on with the issue: Open Zwave Beta
- Add-on release with the issue: current
- Last working add-on release (if known): never
- Operating environment (OS/Supervised): Supervised

## Problem-relevant configuration

I enabled polling on my switch, it works but it takes 15 seconds or longer to actually update in HA with the new value. In zwave2mqtt I was able to set the polling interval, is it possible to do the same in this addon?

```yaml

```

## Traceback/Error logs

```txt

```

**Comment by LunkwillAndFook** [comment]
+1. This is an ongoing issue and should not be closed.

**Comment by frenck** [comment]
It is likely the development on open zwave will come to a halt an never leave beta.

If an upstream implementation is made, we can update the addon.

However, we strongly advise to switch to using zwave JS instead.

**Comment by broyuken** [comment]
Has polling been added to zwave js yet? Last I looked it hadn’t.
