### ISSUE TITLE
NGINX proxy add-on: give ability to change location of Nginx configuration files

### ISSUE THREAD

**Issue by andreypolyak** [home-assistant/addons#1603]
## The problem
As stated in the documentation Nginx configuration files can only be located in the ```/share``` directory:
```
Option customize.default (required)
The filename of the NGINX configuration for the default server, found in the /share directory.

Option customize.servers (required)
The filename(s) of the NGINX configuration for the additional servers, found in the /share directory.
```
I have all other configuration in the ```/config``` directory and it will make sense to have Nginx configuration files there as well. Please consider giving the ability to change the location of these files.

## Environment

- Add-on with the issue: Home Assistant Add-on: NGINX Home Assistant SSL proxy
- Add-on release with the issue: 3.0.1
- Last working add-on release (if known): 
- Operating environment (OS/Supervised): HassOS

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```txt

```

**Comment by ludeeus** [comment]
It will not move to `/config`, see <https://github.com/home-assistant/supervisor/issues/1842>.
Until that is implemented, it will not change.

If a feature request for this does not exist on the forum, feel free to open one there <https://community.home-assistant.io/c/feature-requests> :+1: 
Closing this as it's not an issue, but more a feature request :+1:
