### ISSUE TITLE
Duplicated VNC view

### ISSUE THREAD

**Issue by VivantSenior** [home-assistant/addons#1644]
## The problem

Hi,

when I open deCONZ app via VNC I can see duplicated view:
![image](https://user-images.githubusercontent.com/49829548/97100987-bc4e7d80-1699-11eb-9f92-4cacd1d0dc0b.png)

## Environment

- Add-on with the issue: 6.4.0 (?)
- Add-on release with the issue: 6.4.1
- Last working add-on release (if known): ?
- Operating environment (OS/Supervised):
Home Assistant 0.116.4
Supervisor 249
ConBee II stick
deCONZ Version 2.05.84 / 14.09.2020
ConBee II Firmware 26580700 (unable to upgrade from add-on to new firmware, [issue](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3385#issuecomment-713885670))

## Problem-relevant configuration

```yaml
N/A
```

## Traceback/Error logs

```txt
127.0.0.1: new handler Process
localhost - - [25/Oct/2020 08:08:14] "GET //websockify HTTP/1.1" 101 -
localhost - - [25/Oct/2020 08:08:14] 127.0.0.1: Plain non-SSL (ws://) WebSocket connection
localhost - - [25/Oct/2020 08:08:14] 127.0.0.1: Version hybi-13, base64: 'False'
localhost - - [25/Oct/2020 08:08:14] 127.0.0.1: Path: '//websockify'
localhost - - [25/Oct/2020 08:08:14] connecting to: 127.0.0.1:5900
127.0.0.1: new handler Process
localhost - - [25/Oct/2020 08:08:15] "GET //websockify HTTP/1.1" 101 -
localhost - - [25/Oct/2020 08:08:15] 127.0.0.1: Plain non-SSL (ws://) WebSocket connection
localhost - - [25/Oct/2020 08:08:15] 127.0.0.1: Version hybi-13, base64: 'False'
localhost - - [25/Oct/2020 08:08:15] 127.0.0.1: Path: '//websockify'
localhost - - [25/Oct/2020 08:08:15] connecting to: 127.0.0.1:5900
```

## Additional information
![image](https://user-images.githubusercontent.com/49829548/97100968-8610fe00-1699-11eb-8709-fd860797dac1.png)
I think (1) should be removed and (2) changed to `width: 100%; height: 100%`.

**Comment by pvizeli** [comment]
@bramkragten what do you think?

**Comment by bramkragten** [comment]
This seems to be the addons iframe that adds the canvas twice? A bug in noVNC?

**Comment by VivantSenior** [comment]
I've checked and the issue is still persistent.
