### ISSUE TITLE
Failed to install addon: Let's Encrypt

### ISSUE THREAD

**Issue by aquatic7** [home-assistant/addons#1653]
## The problem

```
Failed to install addon
404 Client Error: Not Found ("no such image: homeassistant/amd64-addon-letsencrypt:4.11.0: No such image: homeassistant/amd64-addon-letsencrypt:4.11.0")
```

-->
## Environment

arch | x86_64
-- | --
chassis | vm
dev | false
docker | true
docker_version | 19.03.11
hassio | true
host_os | HassOS 4.15
installation_type | Home Assistant OS
os_name | Linux
os_version | 5.4.72
python_version | 3.8.6
supervisor | 2020.10.0
timezone | UTC
version | 0.117.0
virtualenv | false

| Description                | Value |
| -------------------------- | ----- |
| Installation method for HA | Virtualbox
Guest: https://github.com/home-assistant/operating-system/releases/download/4.13/hassos_ova-4.13.vdi.gz | Language: Danish
Host: Manjaro 20.1.1 | KDE Plasma 5.19.5

- Add-on with the issue: Let's Encrypt
- Add-on release with the issue: 4.11.0 
- Last working add-on release (if known): 
- Operating environment (OS/Supervised): 

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```txt

```

## Additional information
Further investigation shows that the hassos_ova-4.13.vdi is on 6,00 GB
Used: 5,55 GB

So can it be because be because of this?
The log says: 

```
Error writing config for auth: [Errno 28] No space left on device
9:51:55 PM – helpers/storage.py (ERROR)
```

Can I make the storage bigger? Why is the downloaded .vdi only on 6,00 GB?
What can I do about this?

**Comment by ludeeus** [comment]
You need to adjust the size in your hypervisor, you should try reaching out on the
[forums](https://community.home-assistant.io/) or [discord](https://discord.gg/c5DvZ4e) 👍 
Closing this as this is not an issue with the add-on.
