### ISSUE TITLE
Add 4096 bit support

### ISSUE THREAD

**Issue by damousys** [home-assistant/addons#1665]
## The problem
I am trying to generate a 4096bit certificate with certbot you can do that with --rsa-key-size 4096
Is there a way to provide Key length ?

## Environment
- Add-on with the issue: Let's Encrypt
- Add-on release with the issue: 4.11.0 
- Last working add-on release (if known): 
- Operating environment (OS/Supervised):  Debian Supervised (0.117.1)

**Comment by ludeeus** [comment]
Currently, this is not possible, feel free to raise a feature request on the forums 👍 
https://community.home-assistant.io/
