### ISSUE TITLE
Cant' update to samba 9.3 from 9.2

### ISSUE THREAD

**Issue by joecas65** [home-assistant/addons#1671]
Hi,
i'm on version 9.2 and i can't see any advice of updating to 9.3
How can i solve ?
Thanks

**Comment by frenck** [comment]
It should be available.

If you reload the add-on store, does it pop up? If not, anything visible in the logs after reloading?

**Comment by joecas65** [comment]
If i delete the addon and next try to reinstall, the add-on store show me always version 9.2

**Comment by frenck** [comment]
That was not what I asked. Could you please try what I suggested in the question and share the logs that go with that?

Thanks 👍

**Comment by joecas65** [comment]
Do you mean addon log or system log ?

**Comment by frenck** [comment]
Both :)

**Comment by joecas65** [comment]
Ok i think (hope) i have found the problem In the system log:
`ERROR (MainThread) [supervisor.store.git] Can't update https://github.com/home-assistant/hassio-addons repo: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch --depth=1 --update-shallow -v origin
  stderr: 'error: object file .git/objects/00/843bb4078ee618605da27b8b69c2d68d6d0cea is empty
fatal: loose object 00843bb4078ee618605da27b8b69c2d68d6d0cea (stored in .git/objects/00/843bb4078ee618605da27b8b69c2d68d6d0cea) is corrupt'.`
