### ISSUE TITLE
Deconz OTA directory not being excluded from snapshots

### ISSUE THREAD

**Issue by CristianHenzel** [home-assistant/addons#1680]
## The problem

Not sure if I'm misunderstanding something, but according to https://github.com/home-assistant/hassio-addons/blob/11dbfb55b5b0503bf2f61b9cba3c518e222cb00a/deconz/config.json#L33 shouldn't the /data/otau directory of the deconz add-on be excluded from snapshots?
Or is any additional configuration needed for this setting to take effect?
I'm asking because for me, this directory is not being excluded, making the snapshots fairly large.

## Environment

- Add-on with the issue: deconz
- Add-on release with the issue: 6.5.0
- Last working add-on release (if known): Not sure if it ever excluded those items, I don't think it ever did for me.
- Operating environment (OS/Supervised): HassOS 4.16, Supervisor version: 2020.11.0

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```txt

```

**Comment by pfrenssen** [comment]
Not stale.
