### ISSUE TITLE
After FULL reboot of HassOS, i always need to restart HA & Deconz add-on to make it functional

### ISSUE THREAD

**Issue by pergolafabio** [home-assistant/addons#1685]
## The problem
Since i think last update of deconz 6.5.0 , when i do a full **reboot** of HassOS, when everythings comes back, i always need to restart the deconz add-on AND HA also afterwards to regain functionality, allthough everything is started...
Hassio is started without any errors in log, the add-on is started like it should...
Also if i look in VNC, everything is connected on zigbee gateway.... , even all my identies are visible in HA , 

## Environment
HassOS 4.16 + 4.17 tested
Deconz 6.5.0
Hassio 117.6

## Problem-relevant configuration
n/a

## Traceback/Error logs
There are no error logs

## Additional information

when i press for an example , an ikea remote button, i see this in deconz addon log : 
19:12:58:844 [INFO] - Button 1002 On TRADFRI on/off switch
but it only starts working after a restart of de deconz addon AND HA restart

**Comment by pergolafabio** [comment]
still an issue, did some updates
HassOS 4.17 , HA 118.5 , deconz bump 6.6.6

after a full reboot, i alwas need to restart HA and deconz addon

**Comment by pergolafabio** [comment]
Still an issue after Hassos 5.8, and 2020.12

None to help me out?

**Comment by docholiday** [comment]
> 
> 
> Still an issue after Hassos 5.8, and 2020.12
> 
> None to help me out?

I can confirm this behaviour with RaspBee 1 after upgrade to said versions (and deconz 6.6.1).

**Comment by rattatosk** [comment]
Hi
I have the same issue after full rebooot of my PI, although there is a 20% chance the issue does not manifests itself.
Problem also came after upgrade deconz 6.5.0.

To fix it, I open de deconzweb gui in HA, go to the phoscon web app gui, and trigger a remote light switch.
After that, all devices can be triggered again through HA en HA automisations.
But this of course breaks my automations.

Anyon can tell me how I can downgrade the deconz plugin to earlier version (pre 6.5.0) until this is fixed ?

Setup :  
- deconz 6.6.0
- HA 0.118.0

Greets

**Comment by pergolafabio** [comment]
is this under investigation? i stil have the issue :(

**Comment by pergolafabio** [comment]
can someone help me? its still happening regarding all updates recently on hassos/ha/deconz

**Comment by pergolafabio** [comment]
i think i have found the issue finally, seems HassOS was fixed setup with google timezone servers, i changed those
so i think now HassOS startsup with correct timezone, seems fixed now
maybe a time issue between HassOS and deconz websockets?
