### ISSUE TITLE
Problem upgrading OpenZWave from 0.7 to 0.7.1 

### ISSUE THREAD

**Issue by oz9els** [home-assistant/addons#1693]
## The problem

After upgrading OpenZWave from 0.7 to 0.7.1 
When trying to start the add-on, I get a pup-up:

404 Client Error: Not Found ("No such image: homeassistant/amd64-addon-zwave:0.7.1") 

The status In the Configuration -> Integration -> OpenZWave (beta) is:

Network Offline
OZWDaemon offline
OpenZWave Instance 1 • 27 nodes
Controller:
OZWDaemon (OpenZWave )

..and (surprise surprise) no Z-Wave devices are working.
## Environment

- Add-on with the issue: OpenZWave 
- Add-on release with the issue: 0.7.1
- Last working add-on release (if known): 0.7.0
- Operating environment (OS/Supervised): HassOS 4.17

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```txt
System-log:
ERROR (SyncWorker_1) [supervisor.docker] Image homeassistant/amd64-addon-zwave not exists for addon_core_zwave
```

## Additional information
Tried rebooting, without any luck.

Do I lose my config if I uninstall and install again ?
Does my old version 0.7 still exist ?

**Comment by frenck** [comment]
I'm running the same architecture on my production system, and have upgraded that one (and others) to 0.7.1. The 0.7.1 builds look good and DockerHub lists the version.

Maybe the 404 is a result of not having enough disk space left?

Uninstalling the add-on will cause the loss of data. Creating a Snapshot can, of course, help in those cases.

**Comment by oz9els** [comment]
Got 10Gb free - That ought be enough..

Have a snapshot from yesterday, so I'll try that ;-) Thanks Frenck

(Will return with result..)

**Comment by oz9els** [comment]
Uninstall, Restore Snapshot, Update - worked, Now I'm running 0.7.1
Wird ;-) 

Think this issue can be closed..

**Comment by frenck** [comment]
Well, at least happy you got it working again! 👍
