### ISSUE TITLE
Motioneye can't upload videos or images into Cloud Services

### ISSUE THREAD

**Issue by marcgarciamarti** [home-assistant/addons#1704]
## 
I'm trying to upload the footage recorded by my home cameras to one (any) of a the available cloud services featured by Motioneye: Google Drive, Google Photos or Dropbox. I manage to create my own token but when I try to test it, the system enters in loop and won't confirm whether the dry-run has been successful or not. 

## 
Home Assistant Supervised running on a fresh Debian install
Operating System
Debian GNU/Linux 10 (buster)
Docker version
19.03.14

Supervisor
Version
2020.12.6
Newest Version
2020.12.6
Channel
stable

- Add-on with the issue: Motioneye
- Add-on release with the issue:  0.10.2
- Last working add-on release (if known): never tested this before 
- Operating environment (OS/Supervised): Supervised

## Problem-relevant configuration
See attached snapshots
![Screen Shot 2020-12-08 at 10 58 16](https://user-images.githubusercontent.com/12695572/101468943-59acfa80-3944-11eb-884e-05b1ebbaf6a4.png)
![Screen Shot 2020-12-08 at 10 58 25](https://user-images.githubusercontent.com/12695572/101468951-5ca7eb00-3944-11eb-80d6-a13c0c128383.png)

```yaml

```

## Traceback/Error logs

```txt

```

**Comment by ludeeus** [comment]
You want this repository <https://github.com/hassio-addons/addon-motioneye>

**Comment by marcgarciamarti** [comment]
@ludeeus sure, that's exactly the repo I got mine from. The snapshots I attached were taken from my system already running that latest version.
