### ISSUE TITLE
Suggestion for addon OpenZwave to use external MQTT Server for more flexible deployment

### ISSUE THREAD

**Issue by munklinde** [home-assistant/addons#1714]
## The problem

Suggestion for addon OpenZwave to use external MQTT Server for more flexible deployment
Not easily possible to use Zwave devices with external tools, like Node Red as mqttserver is not exposed outside the container. 

## Environment

![image](https://user-images.githubusercontent.com/1448145/102285034-a8a2f300-3f35-11eb-856e-1c1395275d97.png)

- Add-on with the issue: OpenZwave
- Add-on release with the issue: homeassistant/aarch64-addon-zwave:0.7.1
- Last working add-on release (if known): none
- Operating environment (OS/Supervised): 
![image](https://user-images.githubusercontent.com/1448145/102285137-e7d14400-3f35-11eb-813f-0a9d222fc3d0.png)

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```txt

```

## Additional information
Maybe look to Zigbee2Mqtt addon for inspiration.

**Comment by MartinHjelmare** [comment]
If running the mosquitto add-on, the OpenZWave add-on will bridge its broker with the broker in the mosquitto add-on.

**Comment by munklinde** [comment]
I'm running mosquitto add-on 5.1.
Is there some configuration required to get the bridging going ?

**Comment by MartinHjelmare** [comment]
No, you should be able to connect to the host of the computer where the add-on is running and the mqtt port that the mosquitto add-on has configured.

**Comment by munklinde** [comment]
My Mosquitto Addon works fine, Zigbee2mqtt works fine, Hass connects fine, automatomations via Node-Red works fine ... nothing from Zwave

![image](https://user-images.githubusercontent.com/1448145/102362848-21955f80-3fb5-11eb-829d-757ff02eb9c0.png)

I actually last week migrated my system from a Linux-server to a RPi4 setup, to be compliant with the guidelines because I had the same problem before.
On the Linux system I uninstalled the Addon and ran the docker image ozwdaemon manually, pointing it to use the Mosquitto server. That worked...

**Comment by kaskader13** [comment]
> If running the mosquitto add-on, the OpenZWave add-on will bridge its broker with the broker in the mosquitto add-on.
In my experience it only works if the mosquitto add-on configured without authentication...

**Comment by MartinHjelmare** [comment]
I've tested it successfully with the default authentication.

**Comment by kaskader13** [comment]
@MartinHjelmare , could you plz share how the OpenZwave configuration with auth should look like? 
What's the format? I tried "mqtt_user: ... " and "mqtt_password: ..." . It didn't work for me.
The docs at https://github.com/home-assistant/addons/blob/master/zwave/DOCS.md do not have auth parameters.

**Comment by MartinHjelmare** [comment]
There's no special config needed in the OpenZWave add-on.

When connecting with the MQTT integration in Home Assistant to the Mosquitto add-on broker you need to use the correct credentials set by the Mosquitto add-on. The default credentials is the same as your Home Assistant user account.

**Comment by kaskader13** [comment]
My HA can connect to the Mosquitto add-on without a problem. I have 20+ devices there. But the bridge from OZW's mqtt to the main mqtt does not work. If I disable logins - all works fine. Somehow OZW in my case fails to find correct credentials.

**Comment by MartinHjelmare** [comment]
Does the default credentials work?

**Comment by kaskader13** [comment]
I have mine set explicitly in Mosquitto brokeradd-on like :
`logins:
  - username: my_username
    password: my_password
anonymous: false
`
Not sure what is the default, sorry ...

**Comment by MartinHjelmare** [comment]
Remove the auth config and you'll get the default.

**Comment by MartinHjelmare** [comment]
This is my (default) Mosquitto add-on config:
```yaml
logins: []
anonymous: false
customize:
  active: false
  folder: mosquitto
certfile: fullchain.pem
keyfile: privkey.pem
require_certificate: false
```

I'm connecting from the MQTT integration from my dev computer to another host that runs this add-on with the credentials of my user account of the Home Assistant instance on the same host that runs the Mosquitto add-on.

**Comment by kaskader13** [comment]
@MartinHjelmare , thank you!  Got it working with a user created using HA GUI and with "require_certificate: false". So there were 2 cases it didn't work:

1. A user set explicitly in Mosquitto brokeradd-on.
2. "require_certificate: true" set in  in Mosquitto brokeradd-on.

All look good now. I appreciate you pointing me in the right direction.

**Comment by MartinHjelmare** [comment]
Thanks for the feedback. I'll bring this to our add-on developers.

**Comment by munklinde** [comment]
Thanks for the help. I now have OpenZWave in the Mosquitto broker .. 
![image](https://user-images.githubusercontent.com/1448145/102411718-a9e62580-3ff2-11eb-8814-1a50947b3abb.png)
