### ISSUE TITLE
Samba Share Addon insists on being the Master Browser of my network

### ISSUE THREAD

**Issue by mkanet** [home-assistant/addons#1716]
## The problem

The Samba Share Addon insists on being the Master Browser of my network… even though my Asus router already is.  I can't find any way to disable this addon's Master Browser.  Currently, there are two Master Browsers on my network:

```
-ASUS-RT-AC5300
   ☺☻__MSBROWSE__☻<01>  GROUP       Registered
-HASSIO
   ☺☻__MSBROWSE__☻<01>  GROUP       Registered

```
## Environment

- Add-on with the issue:  Samba Share
- Add-on release with the issue:  9.3.0
- Last working add-on release (if known): N/A
- Operating environment (OS/Supervised): Home Assistant running in a **VirtualBox VM on Windows 10 Version 2004**

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```txt

```

**Comment by GirzzlyAK** [comment]
Having the same issue and it is very frustrating. Whenever I reboot my Windows machine, which needs to be my MB, Samba apparently takes over. However it isn't a very good one, since my Windows machine can't seem to get the database from Samba. Can we please get a way to disable this feature?

**Comment by mkanet** [comment]
@GirzzlyAK it looks like there's a developer looking into this issue now.

**Comment by GirzzlyAK** [comment]
Not stale unless it has been resolved. Please look into this or report on any progress toward a solution.

**Comment by mkanet** [comment]
I agree.  This should get fixed.

**Comment by GirzzlyAK** [comment]
Would love to see this resolved if possible. Would hate for it to get lost.

**Comment by mkanet** [comment]
Me too.

**Comment by ludeeus** [comment]
This is not a bug. This is using default values for all master settings <https://www.samba.org/samba/docs/current/man-html/smb.conf.5.html>
Please open a [feature request on the forums](https://community.home-assistant.io/c/feature-requests/13) to have more settings exposed. Thanks :+1:

**Comment by ellisjm74** [comment]
@GrizzlyAK @mkanet it looks like someone created the feature request as suggested by @ludeeus :
https://community.home-assistant.io/t/samba-smb-disable-master-browser/722039

**Comment by GrizzlyAK** [comment]
@ellisjm74, thanks for letting me know. This is great. Hopefully this gets resolved. I voted for it.

**Comment by lmagyar** [comment]
See PR #3950

**Comment by GrizzlyAK** [comment]
Fantastic!! Thanks so much to everyone who made this happen! 👍🙌

**Comment by lmagyar** [comment]
You're welcome. It was on my wishlist also, and took only a few minutes.
