### ISSUE TITLE
Rpc_shutdown documentation is not completed

### ISSUE THREAD

**Issue by WhietStar360** [home-assistant/addons#1721]
## The problem
I think that the RPC_Shutdown plug-in is incomplete...

I made a Windows Local account, afterwards I've logged in with an Microsoft account and set a pin for login

Now... wich username and password i should use in core_rpc_shutdown?

## Environment
Home Assistant OS 5.8, Raspberry Pi 3B

- Add-on with the issue:
- Add-on release with the issue: 
- Last working add-on release (if known): 
- Operating environment (OS/Supervised): 

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```txt

```

## Additional information
The issue is solved, you need to enable Network discovery in Windows and add to regedit a Dword 32-bit value with hex value=1 in \HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System

**Comment by NeariX67** [comment]
You missed noting what to name the newly created DWORD entry. (AllowDomainPINLogon)

Found documentation here: https://admx.help/?Category=Windows_8.1_2012R2&Policy=Microsoft.Policies.CredentialProviders::AllowDomainPINLogon
