### ISSUE TITLE
Installing Duck DNS with Let's encrypt breaks deCONZ

### ISSUE THREAD

**Issue by yoheines** [home-assistant/addons#1722]
## The problem

Installing and setting up the official Duck DNS addon with the official deCONZ addon already installed and configured breaks deCONZ: Devices will show up as "not available" in the Home Assistant UI  and the Phoscon frontend will report that it can not connect to the gateway.

## Environment
Home Assistant 2020.12.1 (2020.12 when the problem was initially caused) with Home Assistant OS on a Raspberry Pi 4B (4 GB)
ConBee II USB stick installed directly at Raspberry Pi USB
DSL connectivity (IPv4 only) with a FRITZ!Box 7530 router 

- Add-on with the issue: deCONZ / Duck DNS
- Add-on release with the issue: deCONZ 6.6.1 (6.6.0 when the problem was initially caused) / Duck DNS 1.12.4
- Last working add-on release (if known): 
- Operating environment (OS/Supervised): Home Assistant OS

## Problem-relevant configuration

I configured Duck DNS as instructed in the documentation by adding the following lines to the end of configuration.yaml:

```yaml
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
```
I also added a port forward to port 8123 in  my router.
SSL access through the Duck DNS subdomain worked fine after this with no browser warnings.

## Traceback/Error logs
Relevant logs have already been discarded by the system, so unfortunately I can not provide them.

## Additional information

I was able to resolve the problem by uninstalling the deCONZ addon and reinstalling it, which was a pretty big hassle because I had to redo all the device/entity configurations and automations. Just reinstalling Duck DNS did not fix the problem. My first try to fix the problem was to only uninstall Duck DNS, which led to all addon web UIs breaking (clicking on the link just leads to a plain "401 unauthorized" error message).

**Comment by frenck** [comment]
To me, this sounds like the initial set up of the integration hasn't been done properly (in the past). With the current state of the add-on/integration, it should be impossible for them to collide (as Home Assistant now communicates directly with the add-on in an internal network).
