### ISSUE TITLE
Deconz stops responding, fixed after restart

### ISSUE THREAD

**Issue by undulattice** [home-assistant/addons#1727]
Hey.

I've moved my Philips Hue setup over to my Home Assistant box a few months back (Raspberry Pi 3+, Conbee II). It's been great until a recent update and now the lights randomly stop responding to button presses in Lovelace.

Restarting deCONZ fixes the issue.
Latest versions of everything installed.

Logs below.

Anyone experienced this, know how to fix it?

Thanks. :-)

Logger: homeassistant.util.logging
Source: util/logging.py:108
First occurred: 0:09:49 (10 occurrences)
Last logged: 22:54:29

Exception in async_update_callback when dispatching 'deconz-reachable-00212E065CCD': (True,) Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/deconz/deconz_device.py", line 93, in async_update_callback self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 296, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 322, in _async_write_ha_state attr.update(self.state_attributes or {}) File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 438, in state_attributes if supported_features & SUPPORT_COLOR and self.hs_color: File "/usr/src/homeassistant/homeassistant/components/deconz/light.py", line 149, in hs_color return (self._device.hue / 65535 * 360, self._device.sat / 255 * 100) TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'

Logger: pydeconz.websocket
Source: /usr/local/lib/python3.8/site-packages/pydeconz/websocket.py:86
First occurred: 0:09:09 (8 occurrences)
Last logged: 22:54:14

Unexpected error unsupported operand type(s) for /: 'NoneType' and 'int'

Logger: pydeconz.websocket
Source: /usr/local/lib/python3.8/site-packages/pydeconz/websocket.py:81
First occurred: 0:10:13 (8 occurrences)
Last logged: 22:53:21

Client connection error

**Comment by frenck** [comment]
Hi there @undulattice!

Thanks for opening an issue. However, the error logs/stack traces you are posting, are from the Home Assistant Core.

Please report issues with Home Assistant Core integrations here:

<https://github.com/home-assistant/core/issues>

Thanks already 👍 

Happy Holidays 🎄

**Comment by undulattice** [comment]
Apologies.

**Comment by frenck** [comment]
Don't worry! 👍
