### ISSUE TITLE
Unable to do Copy/paste in Home Assistant Companion (mobile app)

### ISSUE THREAD

**Issue by antoweb** [home-assistant/addons#1745]
## The problem

In Xiaomi MIUI 12 was unable ti do Copy/paste in file editor and the scroll bar left/tight wont work correctly

## Environment

- Add-on with the issue:
- Add-on release with the issue: 
- Last working add-on release (if known): 
- Operating environment (OS/Supervised): 

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```txt

```

**Comment by antoweb** [comment]
To be more clear this issue still remain, in home assistant companion in file editor is impossibile to copy and paste

**Comment by frenck** [comment]
Hi there @antoweb!

Thanks for reporting an issue, however, this is the issue tracker for the add-ons, but it seems like you want to report an issue with one of our mobile companion apps.

Could you please raise an issue in the issue tracker of the app you are using instead?

Thanks! 👍

**Comment by antoweb** [comment]
Using The add on Home Assistant Add-on: File editor in Home Assistant companion is imposibile to do copy/paste

**Comment by frenck** [comment]
Aah in that case, add-ons wrap existing applications, in this case: hass-configurator.

Please report issue with that application here: <https://github.com/danielperna84/hass-configurator>

If the upstream fixes the problem, we'll update the add-on.

Thanks!

../Frenck
