### ISSUE TITLE
File Editor needs internet to work

### ISSUE THREAD

**Issue by osctobe** [home-assistant/addons#1755]
## The problem

The File Editor plugin does not work on isolated network (no internet access). It is due to links to external JS files, like [1].

[1] https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.8/ace.js

## Environment

- Add-on with the issue: File Editor
- Add-on release with the issue: 5.2.0
- Last working add-on release (if known): 
- Operating environment (OS/Supervised): Supervised (hassos in a VM)

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```txt

```

**Comment by frenck** [comment]
Thanks for opening an issue @osctobe!

However, this is not an add-on issue. Add-ons wrap existing applications, in this case, the `hass-configurator`. That has that online depdency.

If you want to request a feature for this application, please report an feature request/issues up stream:

https://github.com/danielperna84/hass-configurator


Thanks!
