### ISSUE TITLE
deCONZ: cannot use VNC (ingress) in mobile view (iOS) - "Loading"

### ISSUE THREAD

**Issue by ottelo9** [home-assistant/addons#1761]
## The problem

I cannot use the deconz VNC view if I access my HA via mobile view on my iPhone or iPad. Dont matter if I use safari (even in desktop view) or the HA app. I click on the right button and get the VNC view but the page dont load (see picture). If I remember correctly this problem occurs after updating to 6.4.1 "Enable autoscale for ingress noVNC". I already cleared my cache but this not help.

![8d3ee8f30b4d9f0e9d57ed8f42a405dea9e06c64](https://user-images.githubusercontent.com/33122175/104430666-45819c00-5587-11eb-8006-f5c1b89f72b4.jpeg)

## Environment

- Add-on with the issue: deCONZ 6.6.2
- Add-on release with the issue: 6.4.1
- Last working add-on release (if known): 6.4.0
- Operating environment (OS/Supervised): Home Assistant 2020.12.1, Home Assistant OS 5.9, Raspberry Pi 3B

## Problem-relevant configuration

none

## Traceback/Error logs

none

**Comment by ottelo9** [comment]
@wovka88
Could you check this?

**Comment by wovka88** [comment]
Hi, i testet it on iPhone with Safari and the HA App, it works without problems.

Do you use any Proxy in your installation?

**Comment by ottelo9** [comment]
@wovka88 No I access the HA directly in my LAN with my iPhone/iPad. Maybe a config/settings/cache problem in (my) deconz vnc? Could I clear some cache inside the deconz addon?

**Comment by ottelo9** [comment]
Now it works, I dont know why. Maybe an iOS or Home Assistant Update.
