### ISSUE TITLE
Mosquitto Broker: 500 Server Error

### ISSUE THREAD

**Issue by portbusy** [home-assistant/addons#1767]
## The problem

After the last update of home assistant I can't start the mosquitto broker. I tried to uninstall the addon but now I can't install it anymore.
I haven't modified any configuration file, so I don't know what to insert in the section 'Problem-relevant configuration'
## Environment

- Add-on with the issue: Mosquitto Broker
- Add-on release with the issue: 5.1
- Last working add-on release (if known): 
- Operating environment (OS/Supervised): Home Assistant 2021.1.4 

## Traceback/Error logs

```
500 Server Error for http+docker://localhost/v1.40/images/homeassistant/aarch64-addon-mosquitto:5.1/json: 
Internal Server Error ("layer does not exist")

```

## System Health

version | 2021.1.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 5.4.79-v8
arch | aarch64

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4727
Installed Version | 1.10.0
Stage | running
Available Repositories | 710
Installed Repositories | 12

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Hass.io</summary>

host_os | Home Assistant OS 5.10
-- | --
update_channel | stable
supervisor_version | 2021.01.5
docker_version | 19.03.13
disk_total | 28.6 GB
disk_used | 8.9 GB
healthy | true
supported | true
board | rpi3-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.3.0), Node-RED (7.2.11), File editor (5.2.0), Visual Studio Code (2.8.2), Duck DNS (1.12.4), InfluxDB (3.7.9), Grafana (5.3.4), Terminal & SSH (8.10.0), AppDaemon 4 (0.3.2), Portainer (1.3.0), Let's Encrypt (4.11.0), AdGuard Home (2.6.1), ADB - Android Debug Bridge (0.6.3), motionEye (0.10.2), MQTT Server & Web client (1.2.0), NGINX Home Assistant SSL proxy (3.0.1)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
mode | yaml
views | 4
resources | 4

</details>

**Comment by frenck** [comment]
This can be a problem with the overlay storage. 

Try running `ha supervisor repair` from the terminal. Please note, this command can take a bit to run.

**Comment by portbusy** [comment]
The command ended successfully but unfortunately the problem I encountered remains.

I also tried to execute the command `ha core check`  that returned this ```Error: 404 Client Error for http+docker://localhost/v1.40/images/homeassistant/raspberrypi3-64-homeassistant:latest/json: Not Found ("no such image: homeassistant/raspberrypi3-64-homeassistant:latest: No such image: homeassistant/raspberrypi3-64-homeassistant:latest)```

Does this error related to my issue?

Thanks for the support

**Comment by frenck** [comment]
No, that error is a similar error. Which version of HassOS are you on? Please make sure you run the latest version of that.

**Comment by portbusy** [comment]
I'm on 5.10 which should be the latest stable

**Comment by SebastianKurp** [comment]
Running into the same error when trying to install. 
My install is a fresh install from the Home assistant site.

**Comment by SebastianKurp** [comment]
@portbusy did you figure out a fix for this?

**Comment by portbusy** [comment]
@SebastianKurp I’ve just tried to reinstall the add-on after leaving my raspberry off for some time and the installation was successful. I do not know why or if this is going to help you...
