### ISSUE TITLE
letsencrypt: Add custom ACME server option does not work if challenge is DNS

### ISSUE THREAD

**Issue by jingsno** [home-assistant/addons#1769]
## The problem

Add custom ACME server option does not work if the challenge is "dns"
"${ACME_CUSTOM_SERVER_ARGUMENTS[@]}" needs to be added to the "dns" challenge parameters aswell

## Environment

- Add-on with the issue: LetsEncrypt
- Add-on release with the issue: 
- Last working add-on release (if known): 
- Operating environment (OS/Supervised): 

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```txt

```

## Additional information
From letsencrypt/rootfs/etc/services.d/lets-encrypt/run

if bashio::config.has_value 'acme_server' ; then
    ACME_CUSTOM_SERVER_ARGUMENTS+=("--server" "${ACME_SERVER}")

SNIP

if [ "$CHALLENGE" == "dns" ]; then
    certbot certonly --non-interactive --keep-until-expiring --expand \
        --email "$EMAIL" --agree-tos \
        --config-dir "$CERT_DIR" --work-dir "$WORK_DIR" \
        --preferred-challenges "$CHALLENGE" "${DOMAIN_ARR[@]}" "${PROVIDER_ARGUMENTS[@]}"
else
    certbot certonly --non-interactive --keep-until-expiring --expand \
        --email "$EMAIL" --agree-tos \
        --config-dir "$CERT_DIR" --work-dir "$WORK_DIR" \
        --preferred-challenges "$CHALLENGE" "${DOMAIN_ARR[@]}" "${ACME_CUSTOM_SERVER_ARGUMENTS[@]}" --standalone
fi

**Comment by jingsno** [comment]
Still a problem

**Comment by imgrant** [comment]
Still exists and a PR submitted in #2362 with the fix, but closed as stale. 🤷‍♂️
