### ISSUE TITLE
 'model_id': None,

### ISSUE THREAD

**Issue by jwilleke** [home-assistant/addons#1770]
Not enough details in how to setup the project within https://console.actions.google.com/

Appears you must click the "Device registration" box at the beginning of the setup.
This was discovered ONLY when trying to setup device and am told I need a model_id which I was not provided.

## Environment

- Add-on with the issue: Home Assistant Add-on: Google Assistant SDK
- Add-on release with the issue: 2.5.0
- Last working add-on release (if known): 
- Operating environment (OS/Supervised):  Version core-2021.1.4/Home Assistant OS 5.10

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```txt
Failed to save addon configuration, not a valid value for dictionary value @ data['options']. Got {'client_secrets': '8838b30c819c.json', 'project_id': 'example-com', 'model_id': None, 'feedback': {'enable': False, 'volume': 80}}
```

**Comment by sriharshaguthikonda** [comment]
![image](https://github.com/user-attachments/assets/d5b0523c-cc89-4810-a6e5-4932b77dfa44)


any solution for this?
