### ISSUE TITLE
[CEC Scanner] 'Failed to open vchiq instance' message in HA Blue

### ISSUE THREAD

**Issue by DCSBL** [home-assistant/addons#1771]
## The problem

After installing the add-on and pressing start, the add-on prints the following in the log:
```
[12:41:49] INFO: Starting CEC client scan...
* failed to open vchiq instance
```
After that, the add-on stops.

## Environment

- Add-on with the issue: CEC Scanner
- Add-on release with the issue: 2.4
- Last working add-on release (if known): Unknown
- Operating environment (OS/Supervised): OS on preinstalled Home Assistant Blue. HA 2021.1.5. Supervisor 2021.01.7.

## Problem-relevant configuration

```yaml
Issue occurred with 'default configuration'
```
- Tried with and without HDMI cable connected
- Tried different cables
- When HDMI cable is connected, TV displays OS messages
- Disconnected deCONZ stick to be sure there is no interference
- Removed ('official HA Blue') case to make sure cable is connected properly

## Traceback/Error logs

```txt
[12:41:49] INFO: Starting CEC client scan...
* failed to open vchiq instance
```

## Additional information
This issue is shortly discussed on the Community Forum. See [here](https://community.home-assistant.io/t/home-assistant-blue-purchase/255079/79).

**Comment by TheDK** [comment]
I can confirm this - same setup, tried most of the same things.

I also noticed that regardless of the hdmi_cec device config HA creates ~15 switch.hdmi entities (numbered 1-9 then a-f), all are ´on‘, none are working, no services are working.

I only find solutions like granting permission by adding ha to group video - which is not possible on the HA Blue supervised setup.

Thanks for looking into it!

**Comment by DCSBL** [comment]
Opened [issue at home-assistant/operating-system](https://github.com/home-assistant/operating-system/issues/1216), because I suspect it maybe has to do with the OS. I just tried the [HDMI-CEC](https://www.home-assistant.io/integrations/hdmi_cec/) integration and is is also not functioning.

**Comment by oramirite** [comment]
Actually I think this is just a problem with the Docker container - if I manually spin up a second version of the CEC extension's container in Privileged mode, a scan works without issue. Some additional investigation into the privileges and device paths needed for CEC to function in a container should be all that's needed here.

**Comment by boszme** [comment]
I've made some research and I believe the current docker image is built only for RPI based devices: _/dev/vchiq_ is very specific for RPI:
https://github.com/raspberrypi/linux/blob/rpi-4.4.y/drivers/misc/vc04_services/Kconfig
https://raspberrypi.stackexchange.com/a/54590

I think this should be blocked from installing on non-RPI based installations and create a separate docker image for Odroid based devices:
https://github.com/Pulse-Eight/libcec/blob/master/docs/README.linux.md

**Comment by DCSBL** [comment]
I think we should move the discussion to the (already open) issue for the OS itself -> https://github.com/home-assistant/addons/issues/1771

@boszme, can you add your findings there?
