### ISSUE TITLE
Check Configuration fails with pip dependencies

### ISSUE THREAD

**Issue by excalbian** [home-assistant/addons#1773]
## The problem

When running, the "Check Home Assistant configuration" Addon, it fails with what appears to be a pip dependency issue. I've already upgraded to the latest version and can confirm my config is working, but the check is still failing.

## Environment

- Add-on with the issue: Check Home Assistant configuration
- Add-on release with the issue: 3.6.0
- Last working add-on release (if known): 
- Operating environment (OS/Supervised): Supervised (2021.01.5) 

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```txt
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
starting version 3.2.9
[11:02:30] INFO: Update udev information
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[11:02:30] INFO: Setup udev devices
[11:02:31] INFO: Don't worry, this temporary installation is not overwriting your current one.
[11:02:31] INFO: Installing Home Assistant: latest...
[11:02:31] INFO: Please be patient, this might take a few minutes...
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.
We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.
requests 2.25.0 requires idna<3,>=2.5, but you'll have idna 3.1 which is incompatible.
[11:03:48] INFO: Installed Home Assistant 2021.1.5
[11:03:48] INFO: Making a copy of your configuration for checking...
[11:03:50] INFO: Checking your configuration against this version...
[11:04:52] ERROR: The configuration check did not pass!
[11:04:52] ERROR: See the output below for more details.
Testing configuration at /tmp/config
Fatal error while loading config: (idna 3.1 (/usr/local/lib/python3.8/site-packages), Requirement.parse('idna<3,>=2.5'), {'requests'})
Failed config
  General Errors: 
    - (idna 3.1 (/usr/local/lib/python3.8/site-packages), Requirement.parse('idna<3,>=2.5'), {'requests'})

Successful config (partial)
[11:04:52] INFO: The full output has been written to /share/check_config.txt
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

## Additional information
While looking for a fix to this issue, I found [this thread](https://community.home-assistant.io/t/bug-with-the-config-checker-add-on/269484) on the community forum and [this issue](https://github.com/home-assistant/core/issues/42834) which has a different message (about the dependencies) and mentions that was intermittent.

**Comment by m90att** [comment]
I have run this today with the 2021.3.1 release and in the log I'm seeing the following, I think (I'm no expert) that it relates to pip dependencies too?

`ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.
We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.
requests 2.25.1 requires idna<3,>=2.5, but you'll have idna 3.1 which is incompatible.`
