### ISSUE TITLE
Reopen Issue #1329

### ISSUE THREAD

**Issue by fti7** [home-assistant/addons#1774]
## The problem

Stale Bot closes the issue #1329
There are still multiple Users with this issue!

Please open it again

## Environment
Mosquitto Addon

## Problem-relevant configuration
See #1329

## Traceback/Error logs
See #1329

**Comment by frenck** [comment]
Hi there,

Thanks for opening up an issue. When creating an issue, an issue template is presented. It looks like you've (partly) removed it. This causes your issue report to be incomplete.

Please edit your issue to have the full issue template back again and provide as much of the requested data as possible. Without it, we won't be able to help you.

Thanks already! 👍

**Comment by fti7** [comment]
Template updated

**Comment by fti7** [comment]
bump
