### ISSUE TITLE
Wrong colour and hue ikea trådfri

### ISSUE THREAD

**Issue by Vendelator** [home-assistant/addons#1779]
## The problem

Changing colour in Deconz works, setting one slider at a time in the integration seems to give correct colour and hue. But using the home assistant frontend give very incorrect colours with weird saturations. And I know they work with both ZHA, Tradfri Gateway and Deconz own phoscon frontend.

Other than this everything is working perfectly. Responsive, reliable and easy to manage.

I read about changing the rest api, changing rgb and hue values seem to have helped some people? But I wouldnt know where to start.

## Environment

- Add-on with the issue: Deconz Conbee 2
- Add-on release with the issue: 6.6.2 and prior.
- Last working add-on release (if known): None
- Operating environment (OS/Supervised): HassOS 5.8

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```txt

```

**Comment by frenck** [comment]
This sounds like an issue with the deCONZ integration in that case, not the add-on.

Issues for integrations need to be raised at the Home Assistant Core project:

https://github.com/home-assistant/core/issues

Thanks! 👍
