### ISSUE TITLE
Mosquitto Broker Error 404, cannot find docker image

### ISSUE THREAD

**Issue by SebastianKurp** [home-assistant/addons#1790]
## The problem
Cannot install Mosquitto broker
## Environment
Add-on with the issue: Mosquitto Broker
Add-on release with the issue: 5.1
Last working add-on release (if known):
Operating environment (OS/Supervised): Home Assistant 2021.1.5

## Problem-relevant configuration

Nothing, have not changed anything yet.

## Traceback/Error logs

![image](https://user-images.githubusercontent.com/16307737/106367525-e18e0000-6308-11eb-84a9-200c207eccad.png)

**Comment by SebastianKurpSyn** [comment]
Issue was with corrupt Home assistant install, you may close this issue.
