### ISSUE TITLE
duckdns doesn't work with cellular router

### ISSUE THREAD

**Issue by ibrahim405** [home-assistant/addons#1792]
## Environment

- Add-on with the issue:
- Add-on release with the issue: 
- Last working add-on release (if known): 
- Operating environment (OS/Supervised): 

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```txt

```

**Comment by ibrahim405** [comment]
![image](https://user-images.githubusercontent.com/76870757/106372211-3ae04880-6376-11eb-95ef-a8868a63f5d7.png)

**Comment by ibrahim405** [comment]
![Uploading image.png…]()

**Comment by ibrahim405** [comment]
![image](https://user-images.githubusercontent.com/76870757/106372228-63684280-6376-11eb-9523-19798f1e6ef7.png)

**Comment by ibrahim405** [comment]
what should i do

**Comment by jbacker** [comment]
There's quite a chance that your cellular connection doesn't have an externally reachable IP address (and uses NAT/CGNAT). If that's the case, no way this can work.
