### ISSUE TITLE
Homematic Addon doesn´t work correctly

### ISSUE THREAD

**Issue by sven25** [home-assistant/addons#1796]
## The problem
I´ve setup the Homematic Addon with the configuration from the documentation, so i´m assuming that the configuration is correct so far. I started the Addon and looked into the Addon Log, some errors and fatal errors. Opened up the UI from the Addon, i can´t connect devices and when i change settings, it won´t save them. After, maybe 2 minutes, i get an message which says "BidCos-RF. An component of the Homematic CCU doesn´t react anymore" (roughly translated from german).

## Environment

- Add-on with the issue: Homematic CCU Addon
- Add-on release with the issue: 11.0.6
- Last working add-on release (if known): 
- Operating environment (OS/Supervised): HomeAssistantOS 5.10 (64bit)

## Problem-relevant configuration

The Addon Configuration looks like this:
```
rf_enable: true
wired_enable: false
hmip_enable: false
rf:
  - type: CCU2
    device: /dev/ttyAMA0
wired:
  - serial: xy
    key: abc
    ip: 192.168.0.0
hmip:
  - type: HMIP_CCU2
    device: /dev/ttyUSB0
regahss_reset: false

```

The Home Assistant configuration.yaml looks like this:
```

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml


homematic:
  interfaces:
    rf:
      host: core-homematic
      port: 2001
    wired:
      host: core-homematic
      port: 2000
    hmip:
      host: core-homematic
      port: 2010
    group:
      host: core-homematic
      port: 9292
      path: /groups
```

## Traceback/Error logs

The full Log of the Homematic Addon with some Errors and Fatal Errors:
```
2021/02/01 18:52:28.999 <Debug> () CCU2CommController::waitForCoProcessorResponse(): Timeout while waiting for response.
2021/02/01 18:52:30.999  CCU2CommController::startCoprocessorAppThreadFunction(): Retrying to send start command
2021/02/01 18:52:30.999  CCU2CommController::startCoprocessorAppThreadFunction(): Send start command
2021/02/01 18:52:30.999  CCU2CommController::SendSystemCommdand()
2021/02/01 18:52:30.999  CCU2CommController::SendSystemCommdand() sending: fd 00 03 00 01 03 9e 09 
2021/02/01 18:52:32.000 <Debug> () CCU2CommController::waitForCoProcessorResponse(): Timeout while waiting for response.
2021/02/01 18:52:32.499 <Fatal error> CCU2CommController::init(): Init failed. Cannot start coprocessor application.
2021/02/01 18:52:32.499  CCU2CommController::SendSystemCommdand()
2021/02/01 18:52:32.499  CCU2CommController::SendSystemCommdand() sending: fd 00 04 00 02 0a 00 3d 10 
2021/02/01 18:52:33.500 <Debug> () CCU2CommController::waitForCoProcessorResponse(): Timeout while waiting for response.
2021/02/01 18:52:33.500 <Error> () CCU2CommController::setCSMACAEnabled(): Error disabling CSMA/CA.
2021/02/01 18:52:33.501 <Error> No BidCoS-Interface available
2021/02/01 18:52:33.502 <Warning> Error initializing interfaces
2021-02-01 18:52:33,504 [ERROR] BidCosRpcDispatcher - Could not register BidCos-RF_java
2021-02-01 18:52:33,513 [ERROR] BidCosRpcDispatcher - Could not register BidCos-RF_java
[18:52:33] INFO: Starting rfd...
2021/02/01 18:52:33.876 <Info> BidCoS-Service started
2021/02/01 18:52:33.877 <Info> XmlRpc Server is listening on TCP port 2001
2021/02/01 18:52:33.879 <Debug> CCU2CommController::init() - Legacy initialization.
2021/02/01 18:52:38.880 <Debug> () CCU2CommController::startCoprocessorApp(): Trying to start coprocessor application
2021/02/01 18:52:39.381  CCU2CommController::startCoprocessorAppThreadFunction(): Send start command
2021/02/01 18:52:39.382  CCU2CommController::SendSystemCommdand()
2021/02/01 18:52:39.382  CCU2CommController::SendSystemCommdand() sending: fd 00 03 00 00 03 18 0a 
2021/02/01 18:52:40.383 <Debug> () CCU2CommController::waitForCoProcessorResponse(): Timeout while waiting for response.
2021/02/01 18:52:42.383  CCU2CommController::startCoprocessorAppThreadFunction(): Retrying to send start command
2021/02/01 18:52:42.383  CCU2CommController::startCoprocessorAppThreadFunction(): Send start command
2021/02/01 18:52:42.383  CCU2CommController::SendSystemCommdand()
2021/02/01 18:52:42.383  CCU2CommController::SendSystemCommdand() sending: fd 00 03 00 01 03 9e 09 
2021/02/01 18:52:43.384 <Debug> () CCU2CommController::waitForCoProcessorResponse(): Timeout while waiting for response.
2021/02/01 18:52:43.882 <Fatal error> CCU2CommController::init(): Init failed. Cannot start coprocessor application.
2021/02/01 18:52:43.882  CCU2CommController::SendSystemCommdand()
2021/02/01 18:52:43.883  CCU2CommController::SendSystemCommdand() sending: fd 00 04 00 02 0a 00 3d 10 
2021/02/01 18:52:44.884 <Debug> () CCU2CommController::waitForCoProcessorResponse(): Timeout while waiting for response.
2021/02/01 18:52:44.884 <Error> () CCU2CommController::setCSMACAEnabled(): Error disabling CSMA/CA.
2021/02/01 18:52:44.887 <Error> No BidCoS-Interface available
2021/02/01 18:52:44.887 <Warning> Error initializing interfaces
2021-02-01 18:52:44,889 [ERROR] BidCosRpcDispatcher - Could not register BidCos-RF_java
2021-02-01 18:52:44,895 [ERROR] BidCosRpcDispatcher - Could not register BidCos-RF_java
[18:52:45] INFO: Starting rfd...
2021/02/01 18:52:45.261 <Info> BidCoS-Service started
2021/02/01 18:52:45.262 <Info> XmlRpc Server is listening on TCP port 2001
2021/02/01 18:52:45.264 <Debug> CCU2CommController::init() - Legacy initialization.
2021/02/01 18:52:50.265 <Debug> () CCU2CommController::startCoprocessorApp(): Trying to start coprocessor application
2021/02/01 18:52:50.766  CCU2CommController::startCoprocessorAppThreadFunction(): Send start command
2021/02/01 18:52:50.766  CCU2CommController::SendSystemCommdand()
2021/02/01 18:52:50.767  CCU2CommController::SendSystemCommdand() sending: fd 00 03 00 00 03 18 0a 
2021/02/01 18:52:51.767 <Debug> () CCU2CommController::waitForCoProcessorResponse(): Timeout while waiting for response.
2021/02/01 18:52:53.767  CCU2CommController::startCoprocessorAppThreadFunction(): Retrying to send start command
2021/02/01 18:52:53.767  CCU2CommController::startCoprocessorAppThreadFunction(): Send start command
2021/02/01 18:52:53.767  CCU2CommController::SendSystemCommdand()
2021/02/01 18:52:53.767  CCU2CommController::SendSystemCommdand() sending: fd 00 03 00 01 03 9e 09 
2021/02/01 18:52:54.768 <Debug> () CCU2CommController::waitForCoProcessorResponse(): Timeout while waiting for response.
2021/02/01 18:52:55.267 <Fatal error> CCU2CommController::init(): Init failed. Cannot start coprocessor application.
2021/02/01 18:52:55.267  CCU2CommController::SendSystemCommdand()
2021/02/01 18:52:55.267  CCU2CommController::SendSystemCommdand() sending: fd 00 04 00 02 0a 00 3d 10 
2021/02/01 18:52:56.268 <Debug> () CCU2CommController::waitForCoProcessorResponse(): Timeout while waiting for response.
2021/02/01 18:52:56.268 <Error> () CCU2CommController::setCSMACAEnabled(): Error disabling CSMA/CA.
2021/02/01 18:52:56.272 <Error> No BidCoS-Interface available
2021/02/01 18:52:56.273 <Warning> Error initializing interfaces
2021-02-01 18:52:56,275 [ERROR] BidCosRpcDispatcher - Could not register BidCos-RF_java
2021-02-01 18:52:56,281 [ERROR] BidCosRpcDispatcher - Could not register BidCos-RF_java
[18:52:56] INFO: Starting rfd...
2021/02/01 18:52:56.688 <Info> BidCoS-Service started
2021/02/01 18:52:56.689 <Info> XmlRpc Server is listening on TCP port 2001
2021/02/01 18:52:56.691 <Debug> CCU2CommController::init() - Legacy initialization.
2021/02/01 18:53:01.692 <Debug> () CCU2CommController::startCoprocessorApp(): Trying to start coprocessor application
2021/02/01 18:53:02.193  CCU2CommController::startCoprocessorAppThreadFunction(): Send start command
2021/02/01 18:53:02.194  CCU2CommController::SendSystemCommdand()
2021/02/01 18:53:02.194  CCU2CommController::SendSystemCommdand() sending: fd 00 03 00 00 03 18 0a 
2021/02/01 18:53:03.195 <Debug> () CCU2CommController::waitForCoProcessorResponse(): Timeout while waiting for response.
2021/02/01 18:53:05.195  CCU2CommController::startCoprocessorAppThreadFunction(): Retrying to send start command
2021/02/01 18:53:05.195  CCU2CommController::startCoprocessorAppThreadFunction(): Send start command
2021/02/01 18:53:05.195  CCU2CommController::SendSystemCommdand()
2021/02/01 18:53:05.195  CCU2CommController::SendSystemCommdand() sending: fd 00 03 00 01 03 9e 09 
2021/02/01 18:53:06.196 <Debug> () CCU2CommController::waitForCoProcessorResponse(): Timeout while waiting for response.
2021/02/01 18:53:06.694 <Fatal error> CCU2CommController::init(): Init failed. Cannot start coprocessor application.
2021/02/01 18:53:06.694  CCU2CommController::SendSystemCommdand()
2021/02/01 18:53:06.695  CCU2CommController::SendSystemCommdand() sending: fd 00 04 00 02 0a 00 3d 10 
2021/02/01 18:53:07.695 <Debug> () CCU2CommController::waitForCoProcessorResponse(): Timeout while waiting for response.
2021/02/01 18:53:07.695 <Error> () CCU2CommController::setCSMACAEnabled(): Error disabling CSMA/CA.
2021/02/01 18:53:07.700 <Error> No BidCoS-Interface available
2021/02/01 18:53:07.704 <Warning> Error initializing interfaces
2021-02-01 18:53:07,707 [ERROR] BidCosRpcDispatcher - Could not register BidCos-RF_java
2021-02-01 18:53:07,713 [ERROR] BidCosRpcDispatcher - Could not register BidCos-RF_java
[18:53:08] INFO: Starting rfd...
2021/02/01 18:53:08.080 <Info> BidCoS-Service started
2021/02/01 18:53:08.081 <Info> XmlRpc Server is listening on TCP port 2001
2021/02/01 18:53:08.083 <Debug> CCU2CommController::init() - Legacy initialization.
```

## Additional information
Hardware:
Raspberry Pi 3B+ with original Raspberry Power Supply and HM-MOD-RPI-PCB Module (newest Firmware installed)

I´ve tested the Hardware with RaspberryMatic and everything works fine. So there is no issue with the Hardware i guess.

Would be nice if someone can support me, i don´t have any idea what is causing those problems

**Comment by pvizeli** [comment]
RaspberryMatic using a own firmware:
https://github.com/home-assistant/addons/pull/1726

**Comment by sven25** [comment]
> RaspberryMatic using a own firmware:
> #1726

So i need to update the firmware from your mentioned link and then everything works fine?

**Comment by jens-maus** [comment]
@pvizeli 
> RaspberryMatic using a own firmware:
> #1726

As mentioned here (https://github.com/home-assistant/addons/pull/1726#discussion_r574434105), this is not entirely correct or the root-cause of the issue mentioned here. RaspberryMatic as well as piVCCU use the latest official firmware version (2.8.6) for the `HM-MOD-RPI-PCB` which is not only the only version that provides HomeMatic+homematicIP functionality in a so-called "dual co-processor" type of firmware. It is also currently the most stable version directly released by eQ3.

The above errors derive from the fact, that the current shape of the homematic add-on is far from being complete, e.g. not capable of running such a dual-copro firmware because mandatory system components (e.g. `multimacd`, no special `generic_raw_uart` kernel modules, etc.) are not working correctly or are not available in the underlying operating system (HAos). 

As you might have noticed, I am about to release a first beta version of an own "Home Assistant RaspberryMatic add-on" during the next days. This will hopefully be one step in a direction where in future we could have a more smooth and streamed-lined HomeMatic integration in Home Assistant. And I do hope core HA developers like you will appreciate and support this new upcoming HomeMatic HA Add-on - also potentially accepting PRs I would have to send over to the HAos project for getting necessary OS components integrated to get HomeMatic+homematicIP support fully integrated in Home Assistant.

**Comment by svisso** [comment]
Jens-Maus, IWould be veeeery keen on getting hands on your new homematic-homeassistant add-on. What is the news?

**Comment by jens-maus** [comment]
> Jens-Maus, IWould be veeeery keen on getting hands on your new homematic-homeassistant add-on. What is the news?

Well, the current state of affairs regarding the RaspberryMatic add-on can be seen here:
https://github.com/jens-maus/RaspberryMatic/issues/1087#issuecomment-788913737

**Comment by feutl** [comment]
For everyone who is watching this, should also have a look at https://github.com/home-assistant/operating-system/pull/1266 and support this endeavor

**Comment by cablesky** [comment]
i have always problems with the HM-MOD-RPI-PCB and HASSIO. Despite all the tips and tricks, I get the error message. Updating the firmware does not help either. I give up... FHEM works fine. Would like to switch from FHEM to home assistant - at FHEM there are no problems with the HM-MOD-RPI-PCB..

**Comment by jens-maus** [comment]
@cablesky Then wait until Home Assistant OS 6.0 is released, because it will come with direct support for the HM-MOD-RPI-PCB as well as for the RPI-RF-MOD (see https://github.com/home-assistant/operating-system/pull/1266 as well as https://github.com/jens-maus/RaspberryMatic/issues/1087)

**Comment by sven25** [comment]
Hello. 

So is Home Assistant 2021.4.6 now the version with Support for the hm-mod-rpi-pcb or is this feature still in development?

**Comment by jens-maus** [comment]
> So is Home Assistant 2021.4.6 now the version with Support for the hm-mod-rpi-pcb or is this feature still in development?

Don't mix up "Home Assistant" with "Home Assistant OS". For the hm-mod-rpi-pcb to work you need to have a Home Assistant OS version >= 6.0 (which is not yet released!)

**Comment by sven25** [comment]
Ah ok, i understand! Thanks for the explanation!

**Comment by JakobTewes** [comment]
Found this, as I´ve tried switching over from haos_rpi4-6.2.img to haos_rpi4-64-6.2.img.
Meaning that I got a SD card with a 32Bit HassOS instance and another one with 64Bit HassOS.
With the old 32 bit instance the HM AddOn works fine, while I´m running in the originally stated errors with the 64bit version, that I´ve wanted to cut over to. Switching back to 32bit for now.

**Comment by JakobTewes** [comment]
Still unfixed. 64bit not working

**Comment by cablesky** [comment]
Ok you convinced me. I have now attached a rpi-rf-uart with an FTDI to the USB socket. With the repository with you (Jens Maus) the error message "No BidCos device found" is displayed. The rpi-rf-uart is recognized with the standard Homematic add-on, but I cannot teach in a Homematic device. (See the following log).
I have installed the latest HASS.IO (Release 7).
What am I doing wrong??


`2021/11/13 15:37:47.671 <Debug> HSSXmlRpcEventDispatcher::Handle send 1 events
2021/11/13 15:37:47.686 <Debug> HSSXmlRpcEventDispatcher::Handle send completed
172.30.32.2 - - [13/Nov/2021:15:37:49 +0100] "POST /config/cp_add_device.cgi?sid=@1zWVfJnRqE@ HTTP/1.1" 200 45 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"
172.30.32.2 - - [13/Nov/2021:15:37:50 +0100] "POST /esp/system.htm?sid=@1zWVfJnRqE@&action=UpdateUI HTTP/1.1" 200 428 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"
2021/11/13 15:37:51.288  RX SERIAL: fd 00 20 01 2e 05 00 00 3b 24 84 00 28 67 1f 00 00 00 16 00 ac 4c 45 51 30 32 37 33 38 31 36 51 3f 01 00 6e b7 
2021/11/13 15:37:51.288  RX FRAME: 01 2e 05 00 00 3b 24 84 00 28 67 1f 00 00 00 16 00 ac 4c 45 51 30 32 37 33 38 31 36 51 3f 01 00 
2021/11/13 15:37:51.289  (NEQ0204528) CCU2CommController::handleIncomingSerialFrame(): Handling event telegram as event.
2021/11/13 15:37:51.440 <Debug> LEQ0273816's type is HM-ES-PMSw1-Pl
2021/11/13 15:37:51.440  CCU2BidcosRemoteInterface::AddDevice()
2021/11/13 15:37:51.448  RX SERIAL: fd 00 10 01 80 04 07 01 01 00 01 ff ff ff ff ff ff ff ff 41 9f 
2021/11/13 15:37:51.448  RX FRAME: 01 80 04 07 01 01 00 01 ff ff ff ff ff ff ff ff 
2021/11/13 15:37:51.449 <Debug> (NEQ0204528) Response status: OK, Data.
2021/11/13 15:37:51.449  (NEQ0204528) CCU2CommController::handleIncomingSerialFrame(): Got an bidcos msg. Response waiting --> Handling as response...
2021/11/13 15:37:51.450  (NEQ0204528) CCU2CommController::handleIncomingSerialFrame(): Response ok
2021/11/13 15:37:51.452  BidcosRemoteInterface::AddDevice(): Added device remotely: 28 67 1f 00 00 00 .
172.30.32.2 - - [13/Nov/2021:15:37:51 +0100] "POST /api/homematic.cgi HTTP/1.1" 200 61 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"
2021/11/13 15:37:51.464  RX SERIAL: fd 00 10 01 81 04 07 01 01 00 01 ff ff ff ff ff ff ff ff 40 99 
2021/11/13 15:37:51.465  RX FRAME: 01 81 04 07 01 01 00 01 ff ff ff ff ff ff ff ff 
2021/11/13 15:37:51.465 <Debug> (NEQ0204528) Response status: OK, Data.
2021/11/13 15:37:51.465  (NEQ0204528) CCU2CommController::handleIncomingSerialFrame(): Got an bidcos msg. Response waiting --> Handling as response...
2021/11/13 15:37:51.465  (NEQ0204528) CCU2CommController::handleIncomingSerialFrame(): Response ok
2021/11/13 15:37:51.465  BidcosRemoteInterface::AddDevice(): Added device remotely: 28 67 1f 00 00 00 .
2021/11/13 15:37:51.465  CCU2BidcosRemoteInterface::SetDeviceAesPolicy(): dev aes_channels: -1
2021/11/13 15:37:51.481  RX SERIAL: fd 00 10 01 82 04 07 01 01 00 01 ff ff ff ff ff ff ff ff 43 93 
2021/11/13 15:37:51.481  RX FRAME: 01 82 04 07 01 01 00 01 ff ff ff ff ff ff ff ff 
2021/11/13 15:37:51.481 <Debug> (NEQ0204528) Response status: OK, Data.
2021/11/13 15:37:51.481  (NEQ0204528) CCU2CommController::handleIncomingSerialFrame(): Got an bidcos msg. Response waiting --> Handling as response...
2021/11/13 15:37:51.481  (NEQ0204528) CCU2CommController::handleIncomingSerialFrame(): Response ok
2021/11/13 15:37:51.482  BidcosRemoteInterface::AddDevice(): Added device remotely: 28 67 1f 00 00 00 .
2021/11/13 15:37:51.496  RX SERIAL: fd 00 08 01 83 04 07 01 01 00 00 d3 af 
2021/11/13 15:37:51.496  RX FRAME: 01 83 04 07 01 01 00 00 
2021/11/13 15:37:51.496 <Debug> (NEQ0204528) Response status: OK, Data.
2021/11/13 15:37:51.496  (NEQ0204528) CCU2CommController::handleIncomingSerialFrame(): Got an bidcos msg. Response waiting --> Handling as response...
2021/11/13 15:37:51.496  (NEQ0204528) CCU2CommController::handleIncomingSerialFrame(): Response ok
2021/11/13 15:37:51.497  CCU2BidcosRemoteInterface::AddDevice()
2021/11/13 15:37:51.512  RX SERIAL: fd 00 10 01 84 04 07 01 01 00 01 ff ff ff ff ff ff ff ff 45 87 
2021/11/13 15:37:51.512  RX FRAME: 01 84 04 07 01 01 00 01 ff ff ff ff ff ff ff ff 
2021/11/13 15:37:51.513 <Debug> (NEQ0204528) Response status: OK, Data.
2021/11/13 15:37:51.513  (NEQ0204528) CCU2CommController::handleIncomingSerialFrame(): Got an bidcos msg. Response waiting --> Handling as response...
2021/11/13 15:37:51.513  (NEQ0204528) CCU2CommController::handleIncomingSerialFrame(): Response ok
2021/11/13 15:37:51.513  BidcosRemoteInterface::AddDevice(): Added device remotely: 28 67 1f 00 00 00 .
2021/11/13 15:37:51.529  RX SERIAL: fd 00 10 01 85 04 07 01 01 00 01 ff ff ff ff ff ff ff ff 44 81 
2021/11/13 15:37:51.529  RX FRAME: 01 85 04 07 01 01 00 01 ff ff ff ff ff ff ff ff 
2021/11/13 15:37:51.529 <Debug> (NEQ0204528) Response status: OK, Data.
2021/11/13 15:37:51.529  (NEQ0204528) CCU2CommController::handleIncomingSerialFrame(): Got an bidcos msg. Response waiting --> Handling as response...
2021/11/13 15:37:51.529  (NEQ0204528) CCU2CommController::handleIncomingSerialFrame(): Response ok
2021/11/13 15:37:51.530  BidcosRemoteInterface::AddDevice(): Added device remotely: 28 67 1f 00 00 00 .
2021/11/13 15:37:51.530  CCU2BidcosRemoteInterface::SetDeviceAesPolicy(): dev aes_channels: -1
2021/11/13 15:37:51.544  RX SERIAL: fd 00 10 01 86 04 07 01 01 00 01 ff ff ff ff ff ff ff ff 47 8b 
2021/11/13 15:37:51.544  RX FRAME: 01 86 04 07 01 01 00 01 ff ff ff ff ff ff ff ff 
2021/11/13 15:37:51.544 <Debug> (NEQ0204528) Response status: OK, Data.
2021/11/13 15:37:51.544  (NEQ0204528) CCU2CommController::handleIncomingSerialFrame(): Got an bidcos msg. Response waiting --> Handling as response...
2021/11/13 15:37:51.544  (NEQ0204528) CCU2CommController::handleIncomingSerialFrame(): Response ok
2021/11/13 15:37:51.544  BidcosRemoteInterface::AddDevice(): Added device remotely: 28 67 1f 00 00 00 .
2021/11/13 15:37:51.560  RX SERIAL: fd 00 10 01 87 04 07 01 01 00 01 ff ff ff ff ff ff ff ff 46 8d 
2021/11/13 15:37:51.561  RX FRAME: 01 87 04 07 01 01 00 01 ff ff ff ff ff ff ff ff 
2021/11/13 15:37:51.561 <Debug> (NEQ0204528) Response status: OK, Data.
2021/11/13 15:37:51.561  (NEQ0204528) CCU2CommController::handleIncomingSerialFrame(): Got an bidcos msg. Response waiting --> Handling as response...
2021/11/13 15:37:51.561  (NEQ0204528) CCU2CommController::handleIncomingSerialFrame(): Response ok
2021/11/13 15:37:51.561  BidcosRemoteInterface::AddDevice(): Added device remotely: 28 67 1f 00 00 00 .
2021/11/13 15:37:51.561  CCU2BidcosRemoteInterface::SetDeviceAesPolicy(): dev aes_channels: -1
2021/11/13 15:37:51.562 <Debug> Device firmware version is 1.6
2021/11/13 15:37:51.562 <Debug> TX:  @431731786 0x49A67B -> 0x28671F CONFIG_START [NEQ0204528]:
  CNT=1,RPTEN=1,RPTED=0,BIDI=1,BURST=0,WAKEUP=0,WAKEMEUP=0,BCAST=0,TYPE=0x01
  CONFIG_CHANNEL = 0
  CONFIG_PEER_ADDRESS = 0x000000
  CONFIG_PEER_CHANNEL = 0
  CONFIG_PARAM_LIST = 0
2021/11/13 15:37:51.562  CCU2CommController::sendBidcosMessage(): Using burstMode=0
2021/11/13 15:37:52.440  RX SERIAL: fd 00 04 01 88 04 04 07 80 
2021/11/13 15:37:52.440  RX FRAME: 01 88 04 04 
2021/11/13 15:37:52.440 <Debug> (NEQ0204528) Response status: Send failed.
2021/11/13 15:37:52.440  (NEQ0204528) CCU2CommController::handleIncomingSerialFrame(): Got an bidcos msg. Response waiting --> Handling as response...
2021/11/13 15:37:52.440  (NEQ0204528) CCU2CommController::handleIncomingSerialFrame(): Response not ok
2021/11/13 15:37:52.441 <Debug> Event: LEQ0273816:0.UNREACH=true
2021/11/13 15:37:52.441 <Debug> HSSXmlRpcEventDispatcher::Handle send 1 events
2021/11/13 15:37:52.442 <Debug> HSSXmlRpcEventDispatcher::Handle send 1 events
2021/11/13 15:37:52.443 <Debug> Event: LEQ0273816:0.STICKY_UNREACH=true
2021/11/13 15:37:52.444 <Debug> HSSXmlRpcEventDispatcher::Handle send completed
2021/11/13 15:37:52.444 <Debug> HSSXmlRpcEventDispatcher::Handle send 1 events
2021/11/13 15:37:52.445 <Debug> HSSXmlRpcEventDispatcher::Handle send completed
2021/11/13 15:37:52.445 <Debug> SendFrame failed 1 times:  @431731786 0x49A67B -> 0x28671F CONFIG_START [NEQ0204528]:
  CNT=1,RPTEN=1,RPTED=0,BIDI=1,BURST=0,WAKEUP=0,WAKEMEUP=0,BCAST=0,TYPE=0x01
  CONFIG_CHANNEL = 0
  CONFIG_PEER_ADDRESS = 0x000000
  CONFIG_PEER_CHANNEL = 0
  CONFIG_PARAM_LIST = 0
2021/11/13 15:37:52.446 <Warning> Peering with LEQ0273816 failed
2021/11/13 15:37:52.455  RX SERIAL: fd 00 08 01 89 04 07 01 01 00 00 d9 0f 
2021/11/13 15:37:52.455  RX FRAME: 01 89 04 07 01 01 00 00 
2021/11/13 15:37:52.455 <Debug> (NEQ0204528) Response status: OK, Data.
2021/11/13 15:37:52.455  (NEQ0204528) CCU2CommController::handleIncomingSerialFrame(): Got an bidcos msg. Response waiting --> Handling as response...
2021/11/13 15:37:52.455  (NEQ0204528) CCU2CommController::handleIncomingSerialFrame(): Response ok
2021/11/13 15:37:52.455 <Debug> Deleting persistent data for device LEQ0273816
2021/11/13 15:37:52.462 <Debug> HSSXmlRpcEventDispatcher::Handle send completed
2021/11/13 15:37:52.462 <Debug> HSSXmlRpcEventDispatcher::Handle send 1 events
2021/11/13 15:37:52.476 <Debug> HSSXmlRpcEventDispatcher::Handle send completed
172.30.32.2 - - [13/Nov/2021:15:37:53 +0100] "POST /esp/system.htm?sid=@1zWVfJnRqE@&action=UpdateUI HTTP/1.1" 200 428 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"`

**Comment by jens-maus** [comment]
> I have now attached a rpi-rf-uart with an FTDI to the USB socket. 

This won't work! You need a HB-RF-USB-2 to connect a RPI-RF-MOD via USB. An ordinary FTDI Uart converter will not work and is not supported in the RaspberryMatic addon. And the same applies for the Homematic addon. The RPI-RF-MOD has a dualcoprocessor mode which requires a special kernel module which the HA Homematic addon does not support!

**Comment by cablesky** [comment]
Ok, thanks for the answer!
Would it be enough to connect the rpi-rf-uart module directly to the GPIO's? That would actually be the same as a hm-mod-rpi-pcb module ..?

**Comment by jens-maus** [comment]
Yes, connection to the GPIO will work! However take care of RF interferences coming from the USB3 ports of a RaspberryPi4, which should not be used in parallel or with great distance!

**Comment by cablesky** [comment]
Thanks very much!!!
