### ISSUE TITLE
Nginx Proxy Manager failing on creating SSL Certs with Let's Encrypt

### ISSUE THREAD

**Issue by awshirley** [home-assistant/addons#1797]
## The problem
Nginx Proxy Manager has been working as a reverse proxy for me until about a week ago.  It now fails whenever I try to setup a reverse proxy with SSL

## Environment
Nginx Proxy Manager version 0.8.2
HA 2021.1.5 Supervised install on Debian Buster (with all current updates)

## Problem-relevant configuration
log_level: debug

yaml: N/A

## Traceback/Error logs

 mydomain.duckdns.org

server {
  set $forward_scheme http;
  set $server         "192.168.0.10";
  set $port           9500;
  listen 80;
#listen [::]:80;
  server_name mydomain.duckdns.org;
  access_log /proc/1/fd/1 proxy;
  location / {
    
    
     Proxy!
    include conf.d/include/proxy.conf;
  }
   Custom
  include /data/nginx/custom/server_proxy[.]conf;
}
[2/1/2021] [8:40:36 PM] [Nginx    ] › ℹ  info      Testing Nginx configuration
[2/1/2021] [8:40:36 PM] [Nginx    ] › ℹ  info      Reloading Nginx
[2/1/2021] [8:40:36 PM] [Express  ] › ⚠  warning   Command failed: /usr/bin/certbot certonly --non-interactive --config "/etc/letsencrypt.ini" --cert-name "npm-27" --agree-tos --email "myemail@mydomain.com" --preferred-challenges "dns,http" --domains "mydomain.duckdns.org" 
Saving debug log to /data/logs/letsencrypt/letsencrypt.log
Plugins selected: Authenticator webroot, Installer None
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for mydomain.duckdns.org
Using the webroot path /data/letsencrypt-acme-challenge for all unmatched domains.
Waiting for verification...
Challenge failed for domain mydomain.duckdns.org
http-01 challenge for mydomain.duckdns.org
Cleaning up challenges
Some challenges have failed.

## Additional information
I have my firewall set to forward 80 and 443 to the server.  When testing creating the SSL on DuckDNS using Let's Encrypt, the cert gets created without any errors.  Appears Nginx Proxy Manager is failing on creating any SSL Certs.

**Comment by frenck** [comment]
>  When testing creating the SSL on DuckDNS using Let's Encrypt, the cert gets created without any errors.

That is a DNS challenge, and not how this add-on works. Therefore that test doesn't say anything.

From the logs itself, I cannot tell anything. The only thing that is visible is that the challenge failed. 9 out of 10 times, this is caused by not having ports correctly forwarded or set up.

**Comment by charettepa** [comment]
having the exact same issue
any help would be apreciated

the addon is set to use 
8888 for 80 (because 80 is already in use on my HA system by hue integration)
81 for 81
4123 for 443 (because its in use by the built in nginx homeassistant add on)

my firewall forwards 
80 >8888 on the HA ip
443 >4123 on the HA ip

the log is of no additional help
shows the same as what the last person reported  "challenge failed"
