### ISSUE TITLE
docker returns error upon RASA image installation

### ISSUE THREAD

**Issue by gribouk** [home-assistant/addons#1804]
[
## The problem

I am trying to install an image in the docker of RASA NLU according to the directions provided here:
https://rhasspy.readthedocs.io/en/latest/intent-recognition/#rasanlu

When I enter the given command, docker downloads the image files, starts execution and return error as at the picture attached (I could not have copped the text from SSH add-on though I set 'share_sessions: false' in the add-on set up)

When I look at docker through the portainer, I can see the image and container installed, but status is stopped with error code 1, no idea what it means -  'Stopped for 14 minutes with exit code 1'...

No metter what I try it does not install RASA image in the docker. Is it a BUG or I am missisng something?

My config:
Intel NC

Версия | 2021.1.5
-- | --
Тип установки | Home Assistant OS
Среда разработки | false
Supervisor | true
Docker | true
Виртуальное окружение | false
Версия Python | 3.8.7
Семейство операционных систем | Linux
Версия операционной системы | 5.4.86
Архитектура ЦП | x86_64

Операционная система хоста | Home Assistant OS 5.10
-- | --
Канал обновлений | stable
Версия Supervisor | 2021.01.7
Версия Docker | 19.03.13
Памяти доступно | 457.7 GB
Памяти использовано | 49.6 GB
Исправно | true
Поддержка | true
Плата | intel-nuc
Supervisor API | ok
Версия API | ok
Установленные дополнения | Samba share (9.3.0), Check Home Assistant configuration (3.6.0), FTP (4.0.0), File editor (5.2.0), MQTT Server & Web client (1.2.0), Mosquitto broker (5.1), Terminal & SSH (9.0.0), Visual Studio Code (3.0.1), TasmoAdmin (0.14.0), DHCP server (1.2), Log Viewer (0.9.1), SSH & Web Terminal (8.0.0), Portainer (1.4.0), Rhasspy Assistant (2.5.9)

## Environment

- Add-on with the issue:
- Add-on release with the issue: 
- Last working add-on release (if known): 
- Operating environment (OS/Supervised): 

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```txt

```

**Comment by gribouk** [comment]
![docker_error](https://user-images.githubusercontent.com/72703085/106774976-bd595880-6653-11eb-808d-c95039890590.jpg)

**Comment by frenck** [comment]
Hi there,

Sound like you have issues with RASA, please report those with rhasspy, not Home Assistant.

Thanks 👍

**Comment by gribouk** [comment]
Thanks for your reply.

Can I question one more thing - I may ask something dummy since I am not pro in this area, but do not take it too strict please. I am trying to install several other docker images from the terminal and get similar type of an error: 'cannot create directory or write to file. this is read only system' - or something like that. Is it that hassio has controll over entire file system even outside its container? Maybe this is the reason? Maybe it is just not possible to do this type of installations under hassio? This would save me some time if this knowledge would be available. Thanks!

**Comment by frenck** [comment]
Running custom additional software on a Home Assistant system with a Supervisor, is not supported by the Home Assistant project.
