### ISSUE TITLE
Check Configuration: Fatal error while loading config: [Errno 2] No such file or directory:

### ISSUE THREAD

**Issue by woodmj74** [home-assistant/addons#1808]
**Hardware Environment**

- ODROID N2(+)

**Home Assistant OS release:**
- Updated from version 5.10
- Additional information (if accessible):
- issue occurred when moving to 2020.2 (may not be an os issue, please advise and will raise in the appropriate place:-) )

## System Health

version | core-2021.2.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 5.9.16
arch | aarch64
timezone | Europe/London

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4750
Installed Version | 1.10.1
Stage | running
Available Repositories | 720
Installed Repositories | 20

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 14 February 2021, 0:00
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | false
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 5.10
-- | --
update_channel | stable
supervisor_version | supervisor-2021.01.7
docker_version | 19.03.13
disk_total | 28.0 GB
disk_used | 7.9 GB
healthy | true
supported | true
board | odroid-n2
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.2.0), Samba share (9.3.0), Terminal & SSH (9.0.0), deCONZ (6.6.4), Home Assistant Google Drive Backup (0.103.1), Check Home Assistant configuration (3.6.0), Mosquitto broker (5.1), Log Viewer (0.9.1)

</details>

<details><summary>Lovelace</summary>

dashboards | 4
-- | --
resources | 15
views | 15
mode | storage

</details>

**Supervisor logs:**

**Journal logs:**

**Kernel logs:**

**Description of problem:**
Hopefully I've put this in the correct place - if not please let me know and I'll happily raise in the appropriate location.

Prior to upgrading from 2020.1.5 to 2020.02 ran Check Home Assistant configuration which threw the following errors. Raised in OS as it seems to referencing directories on the machine and (forgive my lack of knowledge) wasn't sure is this was managed by the OS rather than Core. The following log was written:

INFO:homeassistant.util.package:Attempting install of colorlog==4.6.2
[01mTesting configuration at /tmp/config[0m
INFO:homeassistant.util.package:Attempting install of aiohttp_cors==0.7.0
INFO:homeassistant.util.package:Attempting install of zeroconf==0.28.8
INFO:homeassistant.util.package:Attempting install of mutagen==1.45.1
INFO:homeassistant.util.package:Attempting install of gTTS==2.2.1
INFO:homeassistant.util.package:Attempting install of bimmer_connected==0.7.14
[31mFatal error while loading config:[0m [Errno 2] No such file or directory: '/usr/local/lib/python3.8/site-packages/chardet-4.0.0.dist-info/METADATA'
[01;37mFailed config[0m
  [01;31mGeneral Errors:[0m [31m [31m
    - [Errno 2] No such file or directory: '/usr/local/lib/python3.8/site-packages/chardet-4.0.0.dist-info/METADATA'
[0m
[01;37mSuccessful config (partial)[0m

Thank you for your assistance and ongoing awesome work!

**Comment by codypet** [comment]
@woodmj74 I've gotten that idna update issue for the last couple of updates and 
`pip install idna--2.5`
seemed to solve the problem for the update and it didn't seem to be related to the above error.  
Even now when I've done the idna update, I'm still getting the no such file or directory error.

**Comment by TheDK** [comment]
Not stale, having the same error for quite some time now:

```
INFO:homeassistant.util.package:Attempting install of colorlog==5.0.1
[01mTesting configuration at /tmp/config[0m
INFO:homeassistant.util.package:Attempting install of pyatmo==4.2.2
INFO:homeassistant.util.package:Attempting install of hass-nabucasa==0.43.0
INFO:homeassistant.util.package:Attempting install of zeroconf==0.29.0
INFO:homeassistant.util.package:Attempting install of pyroute2==0.5.18
INFO:homeassistant.util.package:Attempting install of aiohttp_cors==0.7.0
INFO:homeassistant.util.package:Attempting install of sqlalchemy==1.4.11
INFO:homeassistant.util.package:Attempting install of unidecode
INFO:homeassistant.util.package:Attempting install of cloudscraper
INFO:homeassistant.util.package:Attempting install of ha-ffmpeg==3.0.2
INFO:homeassistant.util.package:Attempting install of home-assistant-frontend==20210504.0
INFO:homeassistant.util.package:Attempting install of pillow==8.1.2
INFO:homeassistant.util.package:Attempting install of scapy==2.4.5
INFO:homeassistant.util.package:Attempting install of aiodiscover==1.4.0
INFO:homeassistant.util.package:Attempting install of PyNaCl==1.3.0
INFO:homeassistant.util.package:Attempting install of emoji==1.2.0
INFO:homeassistant.util.package:Attempting install of defusedxml==0.6.0
INFO:homeassistant.util.package:Attempting install of netdisco==2.8.2
INFO:homeassistant.util.package:Attempting install of async-upnp-client==0.16.2
INFO:homeassistant.util.package:Attempting install of distro==1.5.0
INFO:homeassistant.util.package:Attempting install of pymodbus==2.5.1
INFO:homeassistant.util.package:Attempting install of psutil==5.8.0
INFO:homeassistant.util.package:Attempting install of jsonpath==0.82
INFO:homeassistant.util.package:Attempting install of xmltodict==0.12.0
INFO:homeassistant.util.package:Attempting install of pyworxcloud==1.2.21
INFO:homeassistant.util.package:Attempting install of mutagen==1.45.1
INFO:homeassistant.util.package:Attempting install of gTTS==2.2.2
[31mFatal error while loading config:[0m [Errno 2] No such file or directory: '/usr/local/lib/python3.8/site-packages/idna-3.1.dist-info/METADATA'
[01;37mFailed config[0m
  [01;31mGeneral Errors:[0m [31m[31m
    - [Errno 2] No such file or directory: '/usr/local/lib/python3.8/site-packages/idna-3.1.dist-info/METADATA'
[0m
[01;37mSuccessful config (partial)[0m
```

**Comment by Nenodema** [comment]
Same for me:

Current version: 3.7.1, on supervised installation.

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[16:38:17] INFO: Don't worry, this temporary installation is not overwriting your current one.
[16:38:17] INFO: Installing Home Assistant: latest...
[16:38:17] INFO: Please be patient, this might take a few minutes...
[16:41:13] INFO: Installed Home Assistant 2021.5.0
[16:41:13] INFO: Making a copy of your configuration for checking...
[16:41:38] INFO: Checking your configuration against this version...
[16:43:42] ERROR: The configuration check did not pass!
[16:43:42] ERROR: See the output below for more details.
Testing configuration at /tmp/config
Fatal error while loading config: (idna 3.1 (/usr/local/lib/python3.8/site-packages), Requirement.parse('idna<3,>=2.5'), {'requests'})
Failed config
  General Errors: 
    - (idna 3.1 (/usr/local/lib/python3.8/site-packages), Requirement.parse('idna<3,>=2.5'), {'requests'})

Successful config (partial)
[16:43:42] INFO: The full output has been written to /share/check_config.txt
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by relliky** [comment]
Seeing the same when running Check Config Addon

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[23:42:22] INFO: Don't worry, this temporary installation is not overwriting your current one.
[23:42:22] INFO: Installing Home Assistant: latest...
[23:42:22] INFO: Please be patient, this might take a few minutes...
[23:45:40] INFO: Installed Home Assistant 2021.5.5
[23:45:40] INFO: Making a copy of your configuration for checking...
[23:45:42] INFO: Checking your configuration against this version...
[23:53:17] ERROR: The configuration check did not pass!
[23:53:17] ERROR: See the output below for more details.
Testing configuration at /tmp/config
Fatal error while loading config: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/site-packages/idna-3.1.dist-info/METADATA'
Failed config
  General Errors: 
    - [Errno 2] No such file or directory: '/usr/local/lib/python3.8/site-packages/idna-3.1.dist-info/METADATA'

Successful config (partial)
[23:53:17] INFO: The full output has been written to /share/check_config.txt
s6-svscanctl: fatal: unable to control /var/run/s6/services: supervisor not listening
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.`

Let me know if any more log needed.

**Comment by derandiunddasbo** [comment]
The workaround for this error is calling `pip install idna` inside the running container to update idna to the required version 3.2:

```
root@homesweethome:~# docker exec -it addon_core_check_config bash
bash-5.0# pip install idna
Collecting idna
  Downloading idna-3.2-py3-none-any.whl (59 kB)
     |████████████████████████████████| 59 kB 2.0 MB/s
Installing collected packages: idna
Successfully installed idna-3.2
WARNING: You are using pip version 20.2.4; however, version 21.1.2 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
```

This seems to work as long as the addon isn't updated.

Is there a reason this addon doesn't get fixed with a current idna version preinstalled? Is there someone maintaining this addon?

**Comment by TheDK** [comment]
pip is not available on HA OS.

Also: Yes, it should be fixed. :)

**Comment by derandiunddasbo** [comment]
> pip is not available on HA OS.

Please note the `docker exec` command before `pip`. The pip command above is launched _inside_ the addon container, not from HA OS.

**Comment by TheDK** [comment]
I currently connect to the SSH add-on as part of HA core, which doesn't support either. How do I connect to HA OS via SSH to run docker commands? It's a HA Blue installation.

**Comment by Nenodema** [comment]
> The workaround for this error is calling `pip install idna` inside the running container to update idna to the required version 3.2:
> 
> ```
> root@homesweethome:~# docker exec -it addon_core_check_config bash
> bash-5.0# pip install idna
> Collecting idna
>   Downloading idna-3.2-py3-none-any.whl (59 kB)
>      |████████████████████████████████| 59 kB 2.0 MB/s
> Installing collected packages: idna
> Successfully installed idna-3.2
> WARNING: You are using pip version 20.2.4; however, version 21.1.2 is available.
> You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
> ```
> 
> This seems to work as long as the addon isn't updated.
> 
> Is there a reason this addon doesn't get fixed with a current idna version preinstalled? Is there someone maintaining this addon?

@frenck 

Could you please add this in the next release of the "check configuration" addon (which is btw fantastic)?

**Comment by derandiunddasbo** [comment]
Connecting through the ssh addon doesn't provide the necessary privileges to access addon docker containers.

When running a HA OS Installation you may follow this guide to get access to the host system:

https://developers.home-assistant.io/docs/operating-system/debugging/

**Comment by ludeeus** [comment]
Is this still an issue with 3.8.0?

**Comment by DarkWing982** [comment]
Looks like it (Home Assistant OS):

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[12:33:11] INFO: Don't worry, this temporary installation is not overwriting your current one.
[12:33:11] INFO: Installing Home Assistant: latest...
[12:33:11] INFO: Please be patient, this might take a few minutes...
[12:34:39] INFO: Installed Home Assistant 2021.7.0
[12:34:39] INFO: Making a copy of your configuration for checking...
[12:34:47] INFO: Checking your configuration against this version...
[12:39:20] ERROR: The configuration check did not pass!
[12:39:20] ERROR: See the output below for more details.
Testing configuration at /tmp/config
Fatal error while loading config: [Errno 2] No such file or directory: '/usr/local/lib/python3.9/site-packages/idna-3.2.dist-info/METADATA'
Failed config
  General Errors: 
    - [Errno 2] No such file or directory: '/usr/local/lib/python3.9/site-packages/idna-3.2.dist-info/METADATA'

Successful config (partial)
[12:39:20] INFO: The full output has been written to /share/check_config.txt
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

**Comment by derandiunddasbo** [comment]
> Looks like it (Home Assistant OS):

That's strange...

This noon I saw the update for the Addon together with the HA update to 2021.7.0. First of all I ran the old version of the Addon and it still threw the idna error. Then I updated the Addon to 3.8.0, ran it again and the error was gone. 

Actually I just ran it the second time against the HA 2021.7.1 bugfix and the error seems to be gone for good. Thus, I don't think the first run was a fluke.

**Comment by derandiunddasbo** [comment]
I have to add, that I really don't understand the nature of this problem. The Addon version 3.8.0 obviously includes idna 2.10:

```
bash-5.1# pip show idna
Name: idna
Version: 2.10
Summary: Internationalized Domain Names in Applications (IDNA)
Home-page: https://github.com/kjd/idna
Author: Kim Davies
Author-email: kim@cynosure.com.au
License: BSD-like
Location: /usr/local/lib/python3.9/site-packages
Requires:
Required-by: yarl, requests, anyio

```

In the error it is (or in my case: it was) complaining about idna 3.2 missing and[ updating idna to version 4](https://github.com/home-assistant/addons/issues/1808?_pjax=%23js-repo-pjax-container#issuecomment-851613378) solved the problem.

**Comment by ludeeus** [comment]
2021.7.1 contains a fix for `av` for the remaining `idna` that is tracked in #2078 so I'm closing this one so it's not multiple issues with the same issue. 👍

**Comment by TheDK** [comment]
For me all errors are gone as well with Add-on 3.8.0 checking againt 2021.7.1 - all looking good:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[08:37:37] INFO: Don't worry, this temporary installation is not overwriting your current one.
[08:37:37] INFO: Installing Home Assistant: latest...
[08:37:37] INFO: Please be patient, this might take a few minutes...
[08:38:23] INFO: Installed Home Assistant 2021.7.1
[08:38:23] INFO: Making a copy of your configuration for checking...
[08:38:24] INFO: Checking your configuration against this version...
[08:40:56] INFO: Configuration check finished - no error found! :)
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by TheDK** [comment]
Just for fun and giggles:

First run with 3.8.0 againt 2021.7.2:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[09:48:06] INFO: Don't worry, this temporary installation is not overwriting your current one.
[09:48:06] INFO: Installing Home Assistant: latest...
[09:48:06] INFO: Please be patient, this might take a few minutes...
[09:48:52] INFO: Installed Home Assistant 2021.7.2
[09:48:52] INFO: Making a copy of your configuration for checking...
[09:48:52] INFO: Checking your configuration against this version...
[09:51:00] ERROR: The configuration check did not pass!
[09:51:00] ERROR: See the output below for more details.
Testing configuration at /tmp/config
Fatal error while loading config: [Errno 2] No such file or directory: '/usr/local/lib/python3.9/site-packages/idna-3.2.dist-info/METADATA'
Failed config
  General Errors: 
    - [Errno 2] No such file or directory: '/usr/local/lib/python3.9/site-packages/idna-3.2.dist-info/METADATA'

Successful config (partial)
[09:51:00] INFO: The full output has been written to /share/check_config.txt
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```
Second run a couple of minutes later, same setup, no restart - just started the add-on again:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[10:02:22] INFO: Don't worry, this temporary installation is not overwriting your current one.
[10:02:22] INFO: Installing Home Assistant: latest...
[10:02:22] INFO: Please be patient, this might take a few minutes...
[10:03:08] INFO: Installed Home Assistant 2021.7.2
[10:03:08] INFO: Making a copy of your configuration for checking...
[10:03:08] INFO: Checking your configuration against this version...
[10:05:41] INFO: Configuration check finished - no error found! :)
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

Something still seems to trip it up from time to time... Nevertheless I trust it enough to now install the current version.
