### ISSUE TITLE
problem with mqtt

### ISSUE THREAD

**Issue by liuk84** [home-assistant/addons#1814]
hello everyone and please help, I use mqtt with zigbee but for a couple of days the platform is 'freezing' it stops working until I restart the whole platform .. I don't see any problem in the logs please help me

**Comment by frenck** [comment]
Hi,

There is not much we can do from this description. Please be sure to check all available logs, as there must be something that logs something.

Also, please be sure to add detail on your setup, versions used, and more importantly, a reproduction scenario for us to reproduce your issue at our end.

Thanks!

../Frenck
