### ISSUE TITLE
File editor not loading properly.

### ISSUE THREAD

**Issue by miteshdube** [home-assistant/addons#1829]
I'm trying to open file editor but it's showing something like in below screenshot
![Screenshot_2021-02-09-15-55-14-16_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/49096865/107350570-9c7b8200-6aef-11eb-8173-c2c88fe613ce.jpg)
I tried to restart raspberry pi and add-on but issue not solved. Also cleared browser cookies and cache.

**Comment by TobiasMie** [comment]
Related to #1820. 
Check if you block some scripts or CSS.

**Comment by frenck** [comment]
This is an upstream issue. Add-on wrap existing applications, in this case `hass-configurator`, there seems to be an upstream request already:

<https://github.com/danielperna84/hass-configurator/issues/177>

One the upstream editor gets these capabilities, we can upgrade the add-on too.
