### ISSUE TITLE
Duckdns shows error in supervisor log

### ISSUE THREAD

**Issue by dailyenergy** [home-assistant/addons#1833]
## The problem
I noticed an error after update to the latest supervisor (supervisor-2021.02.6) and core(core-2021.2.2) with the duckdns plugin

21-02-09 12:22:36 INFO (MainThread) [supervisor.hassos] Detect HassOS 5.11 / BootSlot B
21-02-09 12:22:36 ERROR (MainThread) [supervisor.utils.json] Can't read json from /data/addons/core/duckdns/config.json: Invalid \escape: line 30 column 26 (char 771)
21-02-09 12:22:36 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/core/duckdns/config.json from repository core
21-02-09 12:22:37 INFO (MainThread) [supervisor.store.git] Loading add-on /data/addons/git/cebe7a76 repository

It looks like the plugin is still working

## Environment

- Add-on with the issue: duckdns
- Add-on release with the issue: Duckdns Current version: 1.12.4 
- Last working add-on release (if known): 
- Operating environment (OS/Supervised): OS

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```txt

```

**Comment by RyanMeulenkamp** [comment]
Isn't that what #1832 fixes?

**Comment by OndraM** [comment]
I started to get this error right now, having version 1.12.5 and just updated HA. As a result, the addon cannot be started via Supervisor.

**Comment by OndraM** [comment]
Oh, the error was cause by having custom domain in the "domain" part, which is no longer allowed as per #1785. I removed it and kept only in aliases, now waiting to see if DNS challenge will keep working as it was previously.

**Comment by ludeeus** [comment]
Closing as it seems to be resolved
