### ISSUE TITLE
Z-wave JS Addon Memory Use Issues

### ISSUE THREAD

**Issue by CrackerStealth** [home-assistant/addons#1834]
## The problem

The newly created Z-wave JS addon refuses to boot in my environment as the addon keeps crashing and looping boot. Seems to slowly eat up to 26% of available memory and use constant 20%-35% CPU until a JS heap space crash on new install of the addon.

## Environment

- Add-on with the issue: Z-wave JS
- Add-on release with the issue: 0.1.5
- Last working add-on release (if known): N/A
- Operating environment (OS/Supervised): Home Assistant OS

## Problem-relevant configuration

```yaml
device: /dev/ttyACM0
network key: <copied from previous Z-Wave install, modified as needed>
```

## Traceback/Error logs

After about 15 minutes of running, the addon dumps the following in the logs and starts up again. Left this for an hour with four failures before I gave up and reverted to the backup snapshot I made and went back to the deprecated Z-Wave integration.

```txt
<--- Last few GCs --->
[306:0xb423c200]   820558 ms: Scavenge (reduce) 953.9 (955.5) -> 953.1 (956.5) MB, 5.3 / 0.0 ms  (average mu = 0.267, current mu = 0.223) task 
[306:0xb423c200]   820605 ms: Scavenge (reduce) 953.9 (955.5) -> 953.1 (956.5) MB, 5.3 / 0.0 ms  (average mu = 0.267, current mu = 0.223) task 
[306:0xb423c200]   820652 ms: Scavenge (reduce) 953.9 (955.5) -> 953.2 (956.8) MB, 6.0 / 0.0 ms  (average mu = 0.267, current mu = 0.223) task 
<--- JS stacktrace --->
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```

## Additional information
* Using a Raspbery PI 4 with 4GB of ram.
* Cannot remember if I am using 32-bit or 64-bit OS image. (Edit: Host logs report "CPU: ARMv7 Processor [410fd083] revision 3 (ARMv7)" so I suspect I am using the 32-bit image.)
* Home Assistant OS 5.11, supervisor-2021.02.6, core-2021.2.2
* Followed the instructions at "https://www.home-assistant.io/integrations/zwave_js#in-a-nutshell-this-is-what-the-migration-path-looks-like" for the upgrade path.
* Other Addons: AppDaemon 4, Check Home Assistant Configuration, ESPHome, Let's Encrypt, MariaDB, Samba Share, Terminal & SSH
* Other addons and components are barely using any RAM and CPU usage; averaging 2% and 1% respectively across them.
* Aeotec Z-stick Gen 5 USB Stick attached through USB 2.0 hub. Nothing else on hub.
* Full system reboot did not fix the issue.

I ended up reverting to the backup I made and continuing with the old deprecated Z-wave integration.

**Comment by freman** [comment]
I have very much the same problem with an Aeotec Z-Wave USB Z-Stick (ZW090) 

- Raspberry PI 4 with 8GB of ram
- Home Assistant OS 5.11, supervisor-2021.02.6, core-2021.2.2
- According to arch in terminal - aarch64
- Other Addons: File editor, Log Viewer, Mosquitto broker, Network UPS Tools, Node-Red, Portainer, SSH & Web Terminal, TasmoAdmin, chrony

I went down the route of a full reset of the stick and hasn't solved the issue

Logs:
```
2:29:48.253 DRIVER   version 6.1.3
22:29:48.254 DRIVER   
<--- Last few GCs --->
[248:0x7f828e7290]   868105 ms: Scavenge 2040.7 (2046.7) -> 2039.2 (2046.7) MB, 4.5 / 0.0 ms  (average mu = 0.279, current mu = 0.246) task 
[248:0x7f828e7290]   868137 ms: Scavenge 2040.8 (2046.7) -> 2039.3 (2046.9) MB, 4.9 / 0.0 ms  (average mu = 0.279, current mu = 0.246) task 
[248:0x7f828e7290]   868170 ms: Scavenge 2040.9 (2050.9) -> 2039.4 (2050.9) MB, 4.9 / 0.0 ms  (average mu = 0.279, current mu = 0.246) task 
<--- JS stacktrace --->
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```

**Comment by mkosmo** [comment]
Same issue, same artifacts, also with a ZW090 on a 8GB Pi4 with the latest HASS/Supervisor/core.  Fresh install and I was never able to get it working.  Had to pull an old snapshot to reinstall 0.1.4 in order to get my zwave devices back online.

**Comment by Shaft405** [comment]
I have the exact same issue too with a fresh HASS install.

- Home Assistant OS 5.11, supervisor-2021.02.6, core-2021.2.2
- Z-Wave JS 0.1.6
- Architecture: aarch64

**Comment by jjlauer** [comment]
Me too 👎 Very frustrating.  No idea what's happening.

**Comment by jjlauer** [comment]
Folks, I figured out what was happening for this scenario.  I'm using a Raspberry PI 4, along with an Aeotec Z-Stick.  The Aeotec Z-Stick does NOT work correctly plugged into the USB ports directly on the RPI4.  There are threads about how either the RPI4 or the Z-Stick do not implement the USB power pins correctly or something.  I simply plugged a USB hub into the RPI4 and then plugged the Z-Stick into that, and voila it worked.

You can confirm if this is your problem quite easily.  Install the SSH & Terminal add-on.  Unplug your z-stick.  Run dmesg.  Then plug in the stick, run dmesg again.  If you don't actually see /dev/ttyAMA0 being printed out and the stick being recognized then this is your issue too.

**Comment by CrackerStealth** [comment]
@jjlauer I am aware of USB3.0 issue with the Aoetec Z-stick. I note in my report above that my Z-stick is connected to the Pi through a USB 2.0 hub with no other devices attached to the hub. I attempted to migrate a working Z-wave network from the now deprecated Open Z-wave based integration. My Pi 4 with the Z-stick is working fine with that integration.

**Comment by mkosmo** [comment]
@jjlauer That's the original version of the stick, correct?  Aeotec claimed to have fixed that issue in a later hardware revision (which I have).  It's my understanding that the non-compliant sticks don't work at all in the Pi4.

My setup has no issue with the hardware in 0.1.4, but it does in 0.1.5.  That sounds like a software issue to me.

**Comment by jjlauer** [comment]
I bought this Z-Stick years ago, so I'm guessing I do have the older version.

The original description of the bug -- where it prints the Z-Wave JS logo, then the version, then a blank line of DRIVER.  Followed by 15 minutes later, printing out that GC dump, is exactly what I was experiencing.

I wasted hours thinking Z-Wave JS add-on had a bug.  I just wanted to share what my solution was.

For purposes of troubleshooting, have you guys really run "dmesg" using the SSH addon to confirm when you plug in your Z-Stick, its 100% recognized and loaded as the /dev/ttyAMA0 port?  I originally watched it not do that and really wasted hours thinking it was a Z-Wave JS bug, when it was really a hardware issue.

Just my 2 cents though!

**Comment by CrackerStealth** [comment]
Yes, /dev/ttyAMA0 is recognized in dmesg. That said, the fact that rather than a proper error message like "/dev/ttyAMA0 is not accessible" on startup of the addon being presented in your case got me thinking. So I switched to using the usb by id device link in the config dropdown and that appears to have solved my problem.

![image](https://user-images.githubusercontent.com/6298759/107863286-c21ec900-6e18-11eb-8246-f126392ac3d0.png)

**Comment by mkosmo** [comment]
As another datapoint to support it being software, I just removed this add-on and switched to the ZwaveJS to MQTT add-on and workflow (latest version, v0.4.1).  It is working successfully the same as using an old version of the ZwaveJS add-on.

**Comment by Se7enair** [comment]
Had the same problem

changed the path from /dev/ttyAMA0 to /dev/serial/by-id/usb-xxxx like @CrackerStealth did. Seems to be the solution.

**Comment by bkvargyas** [comment]
Same problem here as well, had to change to /dev/serial/by-id and all is fine now.   Couldn't figure out why so much CPU and RAM was being consumed in the container under HASS.IO.

**Comment by stefan-sherwood** [comment]
I have the same problem

Raspberry Pi 3B+
z-wave.me RaZberry card, 5th generation (latest)
Z-Wave JS version 0.1.10
Home Assistant OS 5.12 (fresh installation)

The RaZberry card is not identified by a by-id entry so that workaround isn't an option for me.

**Comment by Pandabeer40** [comment]
> I have the same problem
> 
> Raspberry Pi 3B+
> z-wave.me RaZberry card, 5th generation (latest)
> Z-Wave JS version 0.1.10
> Home Assistant OS 5.12 (fresh installation), core-2021.3.3, supervisor-2021.03.4
> 
> The RaZberry card is not identified by a by-id entry so that workaround isn't an option for me.

Yes - same issue for me - can anybody advice?

**Comment by trebolcinco** [comment]
Up voting, I have the same issue but on a Pi3+ with the older Aeotec stick.  After the message appears I see Zwave restart and in the logs I see:

May 12 19:51:42 96bd76e11daf[386]: FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
May 12 19:51:46 systemd[1]: Started Process Core Dump (PID 8736/UID 0).
May 12 19:51:50 systemd-coredump[8738]: Process 7457 (node) of user 0 dumped core.
May 12 19:51:52 systemd[1]: systemd-coredump@1-8736-0.service: Succeeded.

**Comment by egro** [comment]
Same issue for me.  Pi3 and older Aeotec stick.  Changed it to /dev/serial/by-id and it's working just fine now.

**Comment by RichS123** [comment]
I am having a similar issue running HA Supervised under Proxmox on an Intel NUC.  When I was running the legacy Z-Wave integration, the average CPU utilized was 1-3%.

Now that I am running the ZWave JS MQTT addon, CPU utilization averages 35-40%.

I am running the newer 5+ version  of the Aeotec Zwave stick, and I've changed the configuration to /dev/serial/by-id, but the CPU utilization is still much higher than normal.

I have had ZWave crash on me once, but I don't know if it was related.

Hopefully a fix is in the works.

**Comment by RichS123** [comment]
Disregard my previous post. I found the problem and it was not related to the Raspberry PI issues.

**Comment by blaet** [comment]
I am using the RaZberry board, and have the same / similar issue. When enabling debug logging for the addon, I am seeing the following last lines:
```
2021-06-16T14:14:18.945Z DRIVER   starting driver...
2021-06-16T14:14:18.995Z DRIVER   opening serial port /dev/ttyAMA0
2021-06-16T14:14:19.031Z DRIVER   serial port opened
2021-06-16T14:14:19.034Z SERIAL » [NAK]                                                                   (0x15)
```

Might `NAK` frame dat is sent or received (not sure which) have something to do with that?

See also the [Silicon labs Z-wave programming docs](https://www.silabs.com/documents/public/user-guides/INS12350-Serial-API-Host-Appl.-Prg.-Guide.pdf) (search for `0x15`).

**Comment by phillycheeze** [comment]
Same issue here with the new Zooz 700-series USB stick and this add-on.

**Comment by imposibrus** [comment]
Well, i had exactly the same symptoms, but with the Docker image `zwavejs/zwavejs2mqtt:5.2.0`, not with addon.
In my case, the problem was in the `mqtt/outgoing` file. I moved it and re-create the container, after that everything works fine. I have no idea why this file got so big (211Mb) and why it might affect the loading🤷‍♂️
![image](https://user-images.githubusercontent.com/3369328/124479696-31d52680-ddaf-11eb-8189-574d445c0aa7.png)

**Comment by tylerszabo** [comment]
The proposed solution of using a udev symlink seems like a red herring to me with respect to a memory issue. Especially since using `/dev/serial/by-id/usb-0658_0200-if00` in the Z-Wave JS Supervisor Add-on configuration will actually be resolved to `/dev/ttyACM0` by through the `pyudev` logic in the Supervisor hardware module.

You can verify with verify with `ps -ef | grep /dev/ttyACM` and you'll likely see something like `node /usr/src/node_modules/.bin/zwave-server /dev/ttyACM0 --config /etc/zwave_config.json`. It's also visible in `/usr/share/hassio/addons/data/core_zwave_js/options.json`.

I suspect that those that have selected a symlink like `/dev/serial/by-id/usb-0658_0200-if00` and are using Supervisor to manage Add-ons are mostly getting the benefit of restarting the container and that the actual path that Z-Wave JS sees has always been a real path to the device and not a udev symlink.

**Comment by tylerszabo** [comment]
While the root cause is not yet confirmed the fact remains that there are conditions that can cause this container to consume all available memory on the host (to the point where it's hard to restart the container). I think that this issue should remain open until a memory limit is implemented to mitigate the impact of when similar situations arise.

**Comment by wesyenyang** [comment]
Anyone ever figure this out? I'm running HA on raspberry pi 4 and when I updated the Core and ZwaveJS to the latest version this error started and I lost my Zwave network.

**Comment by mpardonhw** [comment]
Experiencing the same issue here on my Pi 4 and Aeotec USB stick (mounted onboard in USB 2 port)

**Comment by BrotherRadius** [comment]
I updated to Z-Wave JS 0.1.76 and ran into this same issue.  Everything was working well before that.

**Comment by mkosmo** [comment]
How are you addressing your z-wave hardware?  Back when this was originally reported, I resolved [my](https://github.com/home-assistant/addons/issues/1834#issuecomment-776763639) problem with the solution in comment [882821010](https://github.com/home-assistant/addons/issues/1834#issuecomment-882821010).

If that doesn't resolve it, I'd suggest a new issue since whatever is causing your issue is likely unrelated to this one from a couple of years ago.

**Comment by mpardonhw** [comment]
@mkosmo My configuration is using /dev/ttyAMA0 to address my Aeotec dongle. Are you suggesting that /dev/serial/by-id/... is the solution? I read that comment you referenced as that shouldn't matter.

**Comment by mkosmo** [comment]
Yes, changing to by-id is what solved it for me back then.  It also has meant that I've survived several hardware replacement events without having to change any config in z-wave.

**Comment by denics** [comment]
can we re open this as the issue is still there? razberry on rpi4

**Comment by Pandabeer40** [comment]
Hi Denix,

 

I’ve changed to HA on my Synology NAS with USB dongle for Zwave  / Zigbee  - so this is no issue for me anymore

 

Van: Denix ***@***.***> 
Verzonden: zaterdag 26 augustus 2023 13:32
Aan: home-assistant/addons ***@***.***>
CC: Pandabeer40 ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [home-assistant/addons] Z-wave JS Addon Memory Use Issues (#1834)

 

can we re open this as the issue is still there? razberry on rpi4

**Comment by denics** [comment]
at the end it appears to be an issue with the module that try to reach the device and so it eats all the memory. In my case, it was that I did not enable the uart so on the tty I had bluetooth :(
