### ISSUE TITLE
Serial USB Permission Error

### ISSUE THREAD

**Issue by MaxBec** [home-assistant/addons#1838]
**Describe the issue you are experiencing**

Hey guys,

with the newest Hassio version i get an error with my homegear add-on. It is not able to access the USB CUL Dongle anymore:

```02/09/21 18:06:01.416 Module HomeMatic BidCoS: CUL "CUL_868": Couldn't open CUL device "/dev/serial/by-id/usb-busware.de_CUL868-if00": Permission denied```

**What is the used version of the Supervisor?**

supervisor-2021.02.6

**What type of installation are you running?**

Home Assistant OS

**Which operating system are you running on?**

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

**What is the version of your installed operating system?**

5.11

**What version of Home Assistant Core is installed?**

core-2021.2.2

**Steps to reproduce the issue**

1. Install Add-On https://github.com/MaxBec/hassio-homegear
2. Connect USB Dongle to the Hassio Host Pi
3. Start the Add-On
...

**Anything in the Supervisor logs that might be useful for us?**

_No response_

**Comment by asifma** [comment]
Same issue here...

**Comment by asifma** [comment]
I solved it via adding these lines to config.json for the addon:

  "devices": ["/dev/bus/usb:/dev/bus/usb:rwm"],
  "usb": true,

**Comment by pvizeli** [comment]
homegear add-on is not a core add-on
