### ISSUE TITLE
Z-wave JS exits with RangeError [ERR_INVALID_BUFFER_SIZE]: Buffer size must be a multiple of 16-bits

### ISSUE THREAD

**Issue by shamimrahim** [home-assistant/addons#1840]
## Environment

- Add-on with the issue: Z-wave JS
- Add-on release with the issue: 0.1.5
- Last working add-on release (if known): N/A
- Operating environment (OS/Supervised): Home Assistant OS

## Problem-relevant configuration

```yaml
device: /dev/serial/by-id/usb-0658_0200-if00
network key: <auto generated by system>
```

## Traceback/Error logs

```txt
19:20:10.031 CNTRLR » [Node 031]   querying the CC version for Association Group Information...
19:20:10.383 CNTRLR   [Node 016]   supports CC Association Group Information (0x59) in version 1
19:20:10.384 CNTRLR » [Node 016]   querying the CC version for Association...
19:20:10.490 CNTRLR   [Node 017]   supports CC Association Group Information (0x59) in version 1
19:20:10.490 CNTRLR » [Node 017]   querying the CC version for Association...
19:20:10.616 CNTRLR   [Node 019]   supports CC Multi Channel Association (0x8e) in version 1
19:20:10.617 CNTRLR » [Node 019]   querying the CC version for Multi Channel...
19:20:10.733 CNTRLR   [Node 020]   supports CC Association Group Information (0x59) in version 1
19:20:10.733 CNTRLR » [Node 020]   querying the CC version for Association...
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
RangeError [ERR_INVALID_BUFFER_SIZE]: Buffer size must be a multiple of 16-bits
    at Buffer.swap16 (buffer.js:1127:11)
    at new NodeNamingAndLocationCCNameReport (/usr/lib/node_modules/@zwave-js/server/node_modules/zwave-js/src/lib/commandclass/NodeNamingCC.ts:280:28)
    at new CommandClass (/usr/lib/node_modules/@zwave-js/server/node_modules/zwave-js/src/lib/commandclass/CommandClass.ts:108:13)
    at new NodeNamingAndLocationCC (/usr/lib/node_modules/@zwave-js/server/node_modules/zwave-js/src/lib/commandclass/NodeNamingCC.ts:165:1)
    at Function.from (/usr/lib/node_modules/@zwave-js/server/node_modules/zwave-js/src/lib/commandclass/CommandClass.ts:331:15)
    at new ApplicationCommandRequest (/usr/lib/node_modules/@zwave-js/server/node_modules/zwave-js/src/lib/controller/ApplicationCommandRequest.ts:88:32)
    at Function.from (/usr/lib/node_modules/@zwave-js/server/node_modules/zwave-js/src/lib/message/Message.ts:222:15)
    at Driver.serialport_onData (/usr/lib/node_modules/@zwave-js/server/node_modules/zwave-js/src/lib/driver/Driver.ts:1369:18)
    at SerialAPIParser.emit (events.js:315:20)
    at SerialAPIParser.EventEmitter.emit (domain.js:467:12)
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.```

## Additional information

- Using ESXI vm with official vmdk 
- Also tried with clean install on new vm without restoring any previous settings.  Exactly the same result
- Clean install on RPI, exactly same error
- Home Assistant core-2021.2.2, supervisor-2021.02.6
- Aeotec Gen 5 USB (Z-Stick)
-

**Comment by MartinHjelmare** [comment]
I'd recommend to search the node-zwave-js repo for a similar issue and otherwise open an issue there. Since the stack trace comes from the zwave-js code it's likely that a solution has the greatest chance to be found in that project.

We can keep the issue here open mean while. Thanks!

**Comment by shamimrahim** [comment]
> I'd recommend to search the node-zwave-js repo for a similar issue and otherwise open an issue there. Since the stack trace comes from the zwave-js code it's likely that a solution has the greatest chance to be found in that project.
> 
> We can keep the issue here open mean while. Thanks!

Ok, many thanks and will do.

**Comment by shamimrahim** [comment]
I have opened an issue on the node-zwave-js repo: 

https://github.com/zwave-js/node-zwave-js/issues/1711

**Comment by shamimrahim** [comment]
> I'd recommend to search the node-zwave-js repo for a similar issue and otherwise open an issue there. Since the stack trace comes from the zwave-js code it's likely that a solution has the greatest chance to be found in that project.
> 
> We can keep the issue here open mean while. Thanks!

HI @MartinHjelmare, the developer at zwaveJS kindly resolved my issue in the latest build. He has updated the docker container at zwavejs/zwavejs2mqtt:latest. 

I tried to install the integration via the Home Assistant integrations panel but it is still pulling the old container. Any idea when it might be updated to the latest? 

Many thanks!

**Comment by MartinHjelmare** [comment]
Good!

There are breaking changes in a later Z-Wave JS release so we can't update the add-on until we release a new minor version of Home Assistant core. That will happen in the beginning of March.

**Comment by shamimrahim** [comment]
many thanks, @MartinHjelmare. Appreciate the update.
