### ISSUE TITLE
deconz addon complains about invalid USB device since 6.6.5

### ISSUE THREAD

**Issue by chbndrhnns** [home-assistant/addons#1843]
## The problem

Since this [commit](https://github.com/home-assistant/addons/commit/b8f2079607f3bff5b800fb32efbb3dc212dd11b9#diff-b03135ed8c6ba9dfd6b7740b1b6014dc5d8cfb64e97d4ecd614b4c6e3b6db693R37) which seems to be part of release 6.6.5, I cannot get the deconz plugin to start. It complains about the configuration not being compliant to the required schema for "device".

Probably I need to mention that I am running hass.io on a Synology NAS which is not supported. Still, I'd like to understand the reason for the stricter config validation.
Would it be an option to losen it?

## Environment
- Add-on with the issue: deconz
- Add-on release with the issue: 6.6.5
- Last working add-on release (if known): 6.6.4
- Operating environment (OS/Supervised): supervised

## Problem-relevant configuration

```yaml
device: /dev/ttyUSB0
vnc_password: ''
dbg_info: 1
dbg_oatu: 1
```

## Traceback/Error logs

```txt
21-02-11 09:21:01 ERROR (MainThread) [supervisor.addons.addon] Add-on core_deconz has invalid options: Device /dev/ttyUSB0 don't match the filter subsystem=tty!. Got {'device': '/dev/ttyUSB0', 'vnc_password': '', 'dbg_info': 1, 'dbg_oatu': 1}
```

**Comment by pvizeli** [comment]
Not supported system
