### ISSUE TITLE
Z-Wave JS Timeout while waiting for an ACK from the controller

### ISSUE THREAD

**Issue by bmnijhuis** [home-assistant/addons#1854]
## The problem

The add-on has an issue communication with my Razberry Zwave controller. In the log file an error appears: Timeout while waiting for an ACK from the controller.

## Environment

- Add-on with the issue: zwave_js
- Add-on release with the issue: 0.1.7
- Last working add-on release (if known): 
- Operating environment (OS/Supervised): Raspbian on a Raspberry pi, supervised Linux installation

## Problem-relevant configuration

```yaml
device: /dev/ttyAMA0
network_key: b9cf64000fa33c4df9cbcf32f1a5e86d
```

## Traceback/Error logs

```txt
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] config.sh: executing... 
[cont-init.d] config.sh: exited 0.
[cont-init.d] structure.sh: executing... 
[cont-init.d] structure.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[10:34:43] INFO: Successfully send discovery information to Home Assistant.
10:34:44.608 DRIVER   ███████╗ ██╗    ██╗  █████╗  ██╗   ██╗ ███████╗             ██╗ ███████╗
                      ╚══███╔╝ ██║    ██║ ██╔══██╗ ██║   ██║ ██╔════╝             ██║ ██╔════╝
                        ███╔╝  ██║ █╗ ██║ ███████║ ██║   ██║ █████╗   █████╗      ██║ ███████╗
                       ███╔╝   ██║███╗██║ ██╔══██║ ╚██╗ ██╔╝ ██╔══╝   ╚════╝ ██   ██║ ╚════██║
                      ███████╗ ╚███╔███╔╝ ██║  ██║  ╚████╔╝  ███████╗        ╚█████╔╝ ███████║
                      ╚══════╝  ╚══╝╚══╝  ╚═╝  ╚═╝   ╚═══╝   ╚══════╝         ╚════╝  ╚══════╝
10:34:44.625 DRIVER   version 6.2.0
10:34:44.626 DRIVER   
10:34:51.157 CNTRLR   beginning interview...
10:34:51.158 CNTRLR   querying version info...
10:34:52.410 CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                      n 100 ms.
10:34:53.515 CNTRLR   Failed to execute controller command after 2/3 attempts. Scheduling next try i
                      n 1100 ms.
10:34:55.633 DRIVER   Failed to initialize the driver: Timeout while waiting for an ACK from the con
                      troller
Error in driver ZWaveError: Failed to initialize the driver: Timeout while waiting for an ACK from the controller
    at Immediate.<anonymous> (/usr/lib/node_modules/@zwave-js/server/node_modules/zwave-js/src/lib/driver/Driver.ts:721:6) {
  code: 5,
  context: undefined,
  transactionSource: undefined
}
```

## Additional information
I can use the Z-Wave JS add-on succesfully on the same hardware using hassio on an SD-card. I now use rasbian booted from an SSD with Homeassistant installed using [this guide](https://www.home-assistant.io/installation/linux#install-home-assistant-supervised). The add-on seems to have trouble communicating with the card.

**Comment by frenck** [comment]
Raspbian is not a supported OS to run Home Assistant Supervised on.

See, the requirements as listed in the guide you linked above:

<https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md>

**Comment by chado99** [comment]
For those searching try a powered hub. This [worked for me](https://community.home-assistant.io/t/zwave-errors-after-reinstall-home-assistant-operating-system-on-ssd-updated-to-64-bit-and-restored-backup/537378)  with that error.
