### ISSUE TITLE
Repeated vnc password warning messages

### ISSUE THREAD

**Issue by fudu** [home-assistant/addons#1855]
## The problem

  Get warning messages in log, probably because I did non delete VNC Password in old Deconz configuration, and now I don't know where to delete it .....

## Environment

- Add-on with the issue: deCONZ
- Add-on release with the issue: 6.7.0 (6.6.x too)
- Last working add-on release (if known): don't know
- Operating environment (OS/Supervised): Home Assistant OS 5.11

## Problem-relevant configuration

```

```

## Traceback/Error logs

```
21-02-14 09:56:24 WARNING (MainThread) [supervisor.addons.options] Unknown options vnc_password

```

**Comment by frenck** [comment]
Go to the Supervisor panel -> Click your installed deCONZ add-on -> Configuration tab.
Remove `vnc_password` from the configuration and hit the save button. 🎉

**Comment by fudu** [comment]
VNC password option is not present....
![image](https://user-images.githubusercontent.com/6508171/107882676-12fef200-6eeb-11eb-9144-74b4f82f3922.png)

**Comment by fudu** [comment]
oooppss, sorry, I did not see Option - Edit in Yaml
It's there ...
