### ISSUE TITLE
Z-Wave JS 0.1.7  broken on Raspberry PI

### ISSUE THREAD

**Issue by pkirchner** [home-assistant/addons#1859]
After updating to 0.1.7 Z-Wave stopped working. From the Log:

standard_init_linux.go:219: exec user process caused: exec format error

The container does not start at all. with 0.1.6 it worked fine.

## Environment

- Add-on with the issue: Z-Wave JS
- Add-on release with the issue: 0.1.7
- Last working add-on release (if known):  0.1.6
- Operating environment (OS/Supervised): Supervised, Raspberry Pi 4 in 64 Bit

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```
standard_init_linux.go:219: exec user process caused: exec format error

```

**Comment by frenck** [comment]
Could you provide the output of `ha info` ?

**Comment by pkirchner** [comment]
arch: aarch64
channel: stable
docker: 20.10.3
features:
- reboot
- shutdown
- services
- network
- hostname
hassos: null
homeassistant: 2021.2.3
hostname: home
logging: info
machine: raspberrypi4-64
operating_system: Raspbian GNU/Linux 10 (buster)
state: running
supervisor: 2021.02.9
supported: false
supported_arch:
- aarch64
- armv7
- armhf
timezone: Europe/Berlin

**Comment by pkirchner** [comment]
any hints to downgrade zwave-js to 0.1.6 to get my zwave working again?

**Comment by frenck** [comment]
Downgrading is only possible using snapshots.

**Comment by frenck** [comment]
`Raspbian GNU/Linux 10 (buster)`

This is not a supported system to run Home Assistant Supervised on. Therefore issues may occur. Please make sure you run a supported system.
