### ISSUE TITLE
Barrier Operator not showing up correctly in HA

### ISSUE THREAD

**Issue by Se7enair** [home-assistant/addons#1861]
## The problem

Updated to the newest version to get support for barrier operator.
But it still shows up as a switch in HA. In the WebUI it shows up as a barrier.

## Environment

- Add-on with the issue: Z-Wave JS to MQTT
- Add-on release with the issue: 0.4.1
- Last working add-on release (if known): 
- Operating environment (OS/Supervised): Home Assistant OS 5.11, supervisor-2021.02.09, core-2021.2.2, running on  a raspi 3B+ with Aeotec Z-Wave Stick 1Gen

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```txt

```

**Comment by MartinHjelmare** [comment]
We haven't released support for this in the integration yet. It's merged in dev branch and scheduled for the next minor release.
