### ISSUE TITLE
Z-wave JS crashes

### ISSUE THREAD

**Issue by fribse** [home-assistant/addons#1866]
## The problem

The Z-Wave JS crashes spontaneusly, it shows a lot of errors in the logfile.

## Environment

- Add-on with the issue: Z-Wave JS
- Add-on release with the issue: 0.1.7
- Last working add-on release (if known): unknown, the previous version also crashed spontaneusly.
- Operating environment (OS/Supervised): Supervised on PVE

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```txt
Unfortunately I had to get it up and running fast, so no log files.
```

**Comment by MartinHjelmare** [comment]
Thanks for the report. Unfortunately we can't do anything here without logs. Please open a new issue if you can get the logs. Thanks!
