### ISSUE TITLE
LetsEncrypt: propagation_seconds doesn't work with gcloud DNS provider

### ISSUE THREAD

**Issue by oramirite** [home-assistant/addons#1872]
This is for the Let's Encrypt addon. I was trying to use it to generate SSL certs for my host using a DNS challenge, and despite seeing the TXT entries appear in my zone, kept getting errors that it didn't exist:

```
Cleaning up challenges,
[17:48:56] INFO: Selected DNS Provider: dns-google,
[17:48:57] INFO: Use propagation seconds: 120,
Saving debug log to /var/log/letsencrypt/letsencrypt.log,
Plugins selected: Authenticator dns-google, Installer None,
Obtaining a new certificate,
Performing the following challenges:,
dns-01 challenge for mydomain.zone,
Attempting refresh to obtain initial access_token,
Refreshing access_token,
Waiting 60 seconds for DNS changes to propagate,
Waiting for verification...,
Challenge failed for domain mydomain.zone,
Some challenges have failed.,
IMPORTANT NOTES:,
 - The following errors were reported by the server:,
   Type:   unauthorized,
   Domain: mydomain.zone,
   Detail: No TXT record found at _acme-challenge.mydomain.zone,
   To fix these errors, please make sure that your domain name was,
   entered correctly and the DNS A/AAAA record(s) for that domain,
   contain(s) the right IP address.,
[cont-finish.d] executing container finish scripts...,
[cont-finish.d] done.,
[s6-finish] waiting for services.,
[s6-finish] sending all processes the TERM signal.,
[s6-finish] sending all processes the KILL signal and exiting.
```

My IP address should be correct because I have another host on my network pulling Let's Encrypt certs happily. I believe changing propagation_settings would fix this. As we can see in my original log, I am setting this in my config file, since it gets picked up in the first log message. But it doesn't get applied to the command.

The lack of `"${PROPAGATION_SECONDS}"` at the following line seems to be the culprit:
https://github.com/home-assistant/addons/blob/e89403ef80770cf087358a7505e8d035f7c4c4e0/letsencrypt/rootfs/etc/services.d/lets-encrypt/run#L50

It appears to be implemented for other providers, just not gcloud.

Unfortunately this basically makes the plugin unuseable for me - and I assume others - without being able to add a slight delay to hopefully fix it.

**Comment by avocadio** [comment]
Same issue hit with wildcard verification with dns-ovh

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] file-structure.sh: executing... 
[cont-init.d] file-structure.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[11:56:47] INFO: Selected DNS Provider: dns-ovh
[11:56:47] INFO: Use propagation seconds: 60
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator dns-ovh, Installer None
Renewing an existing certificate
Performing the following challenges:
dns-01 challenge for domain.tld
Waiting 30 seconds for DNS changes to propagate
Waiting for verification...
Challenge failed for domain domain.tld
dns-01 challenge for domain.tld
Cleaning up challenges
Some challenges have failed.
IMPORTANT NOTES:
 - The following errors were reported by the server:
   Domain: domain.tld
   Type:   unauthorized
   Detail: Incorrect TXT record
   "" (and 5 more) found at
   _acme-challenge.domain.tld
   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by brunoabele** [comment]
Same problem here with netcup as dns provider. Worked well for last 2 cert updates, but this time it failes all the time.

I do not think this is a propagation time issue: It took always a few days in the past till the value became visible. But this time, after the script runs, I cannot see the "_acme-challenge.homeassistant.af3.bbkom.de" dns entry.

Is it deleted at the end of the script? It was not deleted in the past. But i am not sure, as i never checked this out in detail when it worked as expected (btw: thank you for all your work on this!)

Will not have so many users reporting this bug as certificates do not expire often and I guess dns based updates are not popular.

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] file-structure.sh: executing... 
[cont-init.d] file-structure.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[13:01:34] INFO: Selected DNS Provider: null
[13:01:34] INFO: Use propagation seconds: 60
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator certbot-dns-netcup:dns-netcup, Installer None
Cert is due for renewal, auto-renewing...
Renewing an existing certificate
Performing the following challenges:
dns-01 challenge for homeassistant.af3.bbkom.de
Waiting 60 seconds for DNS changes to propagate
Waiting for verification...
Challenge failed for domain homeassistant.af3.bbkom.de
dns-01 challenge for homeassistant.af3.bbkom.de
Cleaning up challenges
Some challenges have failed.
IMPORTANT NOTES:
 - The following errors were reported by the server:
   Domain: homeassistant.af3.bbkom.de
   Type:   dns
   Detail: DNS problem: NXDOMAIN looking up TXT for
   _acme-challenge.homeassistant.af3.bbkom.de - check that a DNS
   record exists for this domain
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

**Comment by bleakvin** [comment]
@brunoabele 
Im pretty sure the record gets removed when the script ends. I had the same issue a few times using netcup.
The txt record is visible in the netcup dns management immediately but the validity is marked as "unknown" that can take a few minutes and by then the script is timed out and removes the record.
I set the propagation time to 300 seconds and never had the proplem again.

**Comment by bleakvin** [comment]
Regarding the issue with google dns i agree that the line
https://github.com/home-assistant/addons/blob/e89403ef80770cf087358a7505e8d035f7c4c4e0/letsencrypt/rootfs/etc/services.d/lets-encrypt/run#L50

should probably read

`PROVIDER_ARGUMENTS+=("--${DNS_PROVIDER}" "--${DNS_PROVIDER}-credentials" "/data/${GOOGLE_CREDS}" "--certbot-dns-google:dns-google-propagation-seconds" "${PROPAGATION_SECONDS}")`

**Comment by brunoabele** [comment]
@bleakvin 
I tried to change the propagation time before, but it was then reset to 60 while saving. Right now: I was able to change it and the new value is used..

Even with 900sec, I still get the error. Netcup says they need up to 10min to reload the name servers: [https://www.netcup-wiki.de/wiki/DNS-Einstellungen_CCP#Zone_editieren].

Several users using different DNS services report similar problems. Maybe something changed in the letsencrypt script? 

I had 2 previous cert updates which were successful (with 60sec), but it took me several runs, some months ago. So my settings are good. Timeout was too short, of course.

Now with 900sec, I have enough time to debug. I will post it here when I know what was wrong.

Thank you for your help!

**Comment by igogold** [comment]
I have the same issue with dns-rfc2136 provider:
```[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] file-structure.sh: executing... 
[cont-init.d] file-structure.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[06:00:11] INFO: Selected DNS Provider: dns-rfc2136
[06:00:11] INFO: Use propagation seconds: 120
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator dns-rfc2136, Installer None
Cert is due for renewal, auto-renewing...
Renewing an existing certificate
Performing the following challenges:
dns-01 challenge for hass.domain.ru
Waiting 60 seconds for DNS changes to propagate
Waiting for verification...
Challenge failed for domain hass.domain.ru
dns-01 challenge for hass.domain.ru
Cleaning up challenges
Some challenges have failed.
IMPORTANT NOTES:
 - The following errors were reported by the server:
   Domain: hass.domain.ru
   Type:   dns
   Detail: During secondary validation: DNS problem: query timed out
   looking up TXT for _acme-challenge.hass.domain.ru
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.```
