### ISSUE TITLE
Auth credentials inside vlc addon nginx config

### ISSUE THREAD

**Issue by olegshilov** [home-assistant/addons#1873]
I think this is not a place to store credentials
https://github.com/home-assistant/addons/blob/9fd88b5e3535e5ca84ab60e734e61876e2550b6e/vlc/rootfs/usr/share/tempio/nginx.conf#L52

**Comment by joelmoses** [comment]
Looks like the implementer is trying to lock VLC to the NGINX HA ingress mode for the VLC WebUI. This is clumsy, especially considering they're also generating a telnet secret elsewhere and using it for configuring "cvlc". All it would take is a base64 encoding of the secret prefixed by ":" and passing that value to be written to the resulting file.

I agree that it's not good practice to hardcode this.

**Comment by joelmoses** [comment]
My stab at a fix is here: https://github.com/home-assistant/addons/pull/1878

**Comment by tofuSCHNITZEL** [comment]
I'm wondering if this even matters... Since the port of nginx used for ingress is not exposed outside the docker environment, only the HA container can access it anyway... So is there even the need of a secret? Or a generated one for that matter?

**Comment by tofuSCHNITZEL** [comment]
I'm wondering... Does this even matter? The vlc port is not exposed outside the container so the only way to access it is via the ingress port of the nginx which is "protected" behind the Home Assistant login...
