### ISSUE TITLE
Unable to install new update of Z-Wave JS 0.1.8

### ISSUE THREAD

**Issue by asnandrey** [home-assistant/addons#1880]
I see that a new update is available per alert below:

Update available! 🎉
Z-Wave JS 0.1.8 is available
You are currently running version 0.1.7
You are running Home Assistant 2021.2.3, to update to this version of the add-on you need at least version 2021.2.0b0 of Home Assistant

However, the version number above is not numeric and hence HA is not allowing to install this update.

![image](https://user-images.githubusercontent.com/28460034/109085419-3e45c600-76cf-11eb-9ab2-02f5fbaa7cdc.png)

**Comment by ludeeus** [comment]
Can you post the output of both `ha supervisor info --raw-json` and `ha addons info --raw-json` ?

**Comment by brianlaucis** [comment]
Same issue here. 
![image](https://user-images.githubusercontent.com/40279388/109095826-12800b80-76e2-11eb-9a74-95689626928c.png)

**Comment by h8pewou** [comment]
Same issue here. I've also tried updating from the command line with no luck. See corresponding supervisor log entry below:

```
21-02-25 06:11:33 ERROR (MainThread) [supervisor.addons] Add-on core_zwave_js not supported on that platform
```

**Comment by GitPetri** [comment]
> Seems to be a Typo. Should say 2021.3.0b0 I just had the update popup and it now allows we to update.

I assume you mean 2021.2.3?

**Comment by ludeeus** [comment]
no, it should be "2021.3.0b0"

**Comment by GitPetri** [comment]
> no, it should be "2021.3.0b0"

Please explain, I seem to be too stupid to understand. Latest HA available is 2021.2.3, how can Z-Wave expect 2021.3.anything?

**Comment by ludeeus** [comment]
There is a breaking change in the software in the addon, that requires logic that only exists in HA 2021.3.0, that requirement is to stop you from breaking your setup.

**Comment by gcoupe** [comment]
HA 2021.3.0b0 is the beta release, I assume. The current stable release is 2021.2.3. Presumably in a few weeks time, the stable relase will be upgraded to 2021.3.0, and then this release of ZWave JS can be installed...

**Comment by ludeeus** [comment]
Next Wednesday.

**Comment by GitPetri** [comment]
> There is a breaking change in the software in the addon, that requires logic that only exists in HA 2021.3.0, that requirement is to stop you from breaking your setup.

Thanks for the explanation, for some reason I assumed that the update notification publishing would take into account stable release version.

**Comment by MartinHjelmare** [comment]
We've reverted the Home Assistant core version requirement to 2021.2.0b0, since we're now backwards compatible in the Z-Wave JS Server.
