### ISSUE TITLE
Climate "unavailable" after ZWave JS upgrade to 0.1.10

### ISSUE THREAD

**Issue by kostas2911** [home-assistant/addons#1886]
Hello,

After ZWave JS upgrade to 0.1.10 climate is unavailable.
Although sensor for air temperature is working

**Comment by espenfjo** [comment]
core-2021.3.0b2 fixed this for me.

**Comment by MartinHjelmare** [comment]
Yes, many things will be fixed in 2021.3.0. Please test the beta or upgrade once the regular release ships next week. Please report back then if there are still issues with the climate platform. And please report issues in our Home Assistant core repo. Thanks!

**Comment by pygoubet** [comment]
core-2021.3.0b2 made my climate entities back available
