### ISSUE TITLE
Z-Wave JS addon lost climate entities since last update

### ISSUE THREAD

**Issue by netphantm** [home-assistant/addons#1890]
## The problem

Since updating to 0.1.10 (skipped version 0.1.9, couldn't update because of #1880), addon doesn't find climate entities anymore.
q.8.0 also had some issues (I couldn't set HVAC mode, but setting the temperature at least worked. I also installed ZWaveJS2MQTT now and reset the whole network, but stlil no change. I have 3 thermostatic valves that I purchased all on Amazon (same seller/same model, apparently), they say on the package Eurotronics, but one of them is detected as Aeotec:
1x https://devices.zwave-js.io/?jumpTo=0x0371:0x0002:0x0015:0.16
2x https://devices.zwave-js.io/?jumpTo=0x0148:0x0003:0x0001:0.16
I previously had OpenZWave installed as an addon, but that was also buggy, and they say I should use Z-Wave JS since OpenZWave is deprecated..
## Environment

- Add-on with the issue: Z-Wave JS
- Add-on release with the issue: 0.1.10
- Last working add-on release (if known): 0.1.8
- Operating environment (OS/Supervised): Supervised

## Problem-relevant configuration

```device: /dev/serial/by-id/usb-0658_0200-if00
network_key: >-
  0xFC, 0x3F, 0x4D...
```

## Traceback/Error logs

```

```

## System Health

version | core-2021.2.3
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 4.14.180-178
arch | armv7l
timezone | Europe/Berlin

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4908
Installed Version | 1.11.3
Stage | running
Available Repositories | 814
Installed Repositories | 7

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Hass.io</summary>

host_os | Ubuntu 18.04.5 LTS
-- | --
update_channel | stable
supervisor_version | supervisor-2021.02.11
docker_version | 20.10.3
disk_total | 28.5 GB
disk_used | 26.4 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (5.1.1), Check Home Assistant configuration (3.6.0), ESPHome (1.16.2), Node-RED (8.1.2), Signal Messenger (0.36), Z-Wave JS (0.1.10)

</details>

<details><summary>Lovelace</summary>

dashboards | 3
-- | --
resources | 4
views | 2
mode | storage

</details>

**Comment by MartinHjelmare** [comment]
Some thermostats require the next version of Home Assistant to be discovered properly with this add-on version. Please either try the beta release of Home Assistant or wait to the next release next week.

Closing here.PPlease rreport bback after trying the next release of Home Assistant core of there's still an issue. Please report all issues with Z-Wave JS in the Home Assistant core repository.
