### ISSUE TITLE
Server error 500 when trying to start ZWave JS

### ISSUE THREAD

**Issue by ogarza** [home-assistant/addons#1893]
## The problem

Installation just says it failed, then if I go to the ZWave JS supervisor, this is the error message that I get when trying to start the addon:
Failed to start addon

500 Server Error for http+docker://localhost/v1.40/containers/create?name=addon_core_zwave_js: Internal Server Error ("error creating overlay mount to /mnt/data/docker/overlay2/08de997d5896969f2c1e6f5f7160bd3fa99dbbd6e36161532c81d037472e3e05-init/merged: too many levels of symbolic links")

## Environment

Version
core-2021.2.3

Version
supervisor-2021.02.11
Newest Version
supervisor-2021.02.11
Channel
stable

Operating System
Home Assistant OS 5.12
Deployment
production

Running on a RPi 4

- Add-on with the issue: Z-Wave JS
- Add-on release with the issue: 0.1.10
- Last working add-on release (if known): none
- Operating environment (OS/Supervised): Home Assistant OS 5.12

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```txt

```

**Comment by ogarza** [comment]
![vug1](https://user-images.githubusercontent.com/2816229/109562916-0662c800-7aad-11eb-8225-8b9ab842ef41.png)
![bug2](https://user-images.githubusercontent.com/2816229/109562918-095db880-7aad-11eb-98d2-ab01268e72b5.png)

**Comment by ogarza** [comment]
Actually found another issue with a different 500 server error, but tried their attempted fix anyway and it seems to have resolved my issue.

Typed: 'ha supervisor repair'

in the terminal and just waited for the command to finish

**Comment by MartinHjelmare** [comment]
Please open a new issue if there's still a problem.
