### ISSUE TITLE
Cannot access home-assistant remotely with DuckDNS

### ISSUE THREAD

**Issue by simplenotezy** [home-assistant/addons#1894]
## The problem
I cannot access my Home Assistant remotely.

![image](https://user-images.githubusercontent.com/3786627/109706941-dba26d80-7b99-11eb-8d6c-14ec02cb4baf.png)

    $ curl https://mysecretduckdnsdomain.duckdns.org
    curl: (7) Failed to connect to mysecretduckdnsdomain.duckdns.org port 443: Connection refused

![image](https://user-images.githubusercontent.com/3786627/109707051-fecd1d00-7b99-11eb-80e7-191f87142163.png)

Things I have done:
1) I have followed the documentation under https://homeassistant.local:8123/hassio/addon/core_duckdns/documentation
2) I have set up port-forwarding (even though this is not documented and I personally believe it ought to be, to be as idiot-proof as possible)
3) I have restarted my router and home assistant
4) I have been in contact with my router provider (Jensen Scandinavia, operating under Omni WiFi)
5) I have followed several comments and suggestions from forums and YouTube videos, because this seems to be an huge issue for many home-assistant users. Including " Go to Configuration > General Input your external and internal url in the appropriate boxes: ![image](https://i.imgur.com/APHCfwc.png)

Checklist:
I can access my home assistant locally with https, although I gives a warning. I believe this is because the certificate is given to mydomain.duckdns.org, so it should be OK although it would be nice to be able to dismiss this browser warning.

![image](https://user-images.githubusercontent.com/3786627/109706161-e4467400-7b98-11eb-97a2-4d4d89a5bfc2.png)

## Environment
- Add-on with the issue: DuckDNS
- Add-on release with the issue: Latest
- Last working add-on release (if known): N/A
- Operating environment (OS/Supervised): HAASOS

## Problem-relevant configuration

**configuration.yaml**
```yaml
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

```
**addon-configuration**
```yaml
lets_encrypt:
  accept_terms: true
  certfile: fullchain.pem
  keyfile: privkey.pem
token: some-unique-token
domains:
  - mysecretdomain.duckdns.org
aliases: []
seconds: 300
```

## Traceback/Error logs

```txt
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
# INFO: Using main config file /data/workdir/config
+ Account already registered!
[19:56:37] INFO: OK
123.123.123.123
NOCHANGE
[19:56:38] INFO: Renew certificate for domains: myuniquename.duckdns.org and aliases: 
# INFO: Using main config file /data/workdir/config
Processing myuniquename.duckdns.org
 + Checking domain name(s) of existing cert... unchanged.
 + Checking expire date of existing cert...
 + Valid till May 31 10:10:45 2021 GMT Certificate will not expire
(Longer than 30 days). Skipping renew!
[20:01:48] INFO: OK
123.123.123.123
NOCHANGE
[20:06:50] INFO: OK
123.123.123.123
NOCHANGE
[20:11:52] INFO: OK
123.123.123.123
NOCHANGE
[20:16:54] INFO: OK
123.123.123.123
NOCHANGE
[20:21:55] INFO: OK
123.123.123.123
NOCHANGE
[20:26:57] INFO: OK
123.123.123.123
NOCHANGE
[20:31:58] INFO: OK
123.123.123.123
NOCHANGE
[20:37:00] INFO: OK
123.123.123.123
NOCHANGE
[20:42:01] INFO: OK
123.123.123.123
NOCHANGE
[20:47:03] INFO: OK
123.123.123.123
NOCHANGE
[20:52:04] INFO: OK
123.123.123.123
NOCHANGE
```

**Comment by workingmanrob** [comment]
Fun things to try if you have a local DNS server you can set 192.168.39.122 -> whatever.duckdns.org (or cheese it using hosts file)

Then your external and internal name is the same it's just the port that changes.

Or just forward port 8123 instead of 443 and the URLs are identical.

I mention **whatever**.duckdns.org because you have listed:

- mysecretdomain.duckdns.org
- myuniquename.duckdns.org
- mysecretduckdnsdomain.duckdns.org
- domain.duckdns.org

From the log - Processing myuniquename.duckdns.org - seems like the name you should use but your config seems to reference - mysecretdomain.duckdns.org

**Comment by simplenotezy** [comment]
Turns out my ISP was blocking port-forwarding, unless I set up specific measurements on my router to enable static-IP. A service I thought I already had enabled, but turns out I just had a dynamic IP that haven't changed for ~2 years haha.
