### ISSUE TITLE
Climate entities disappeared with latest zwave-js 0.1.10

### ISSUE THREAD

**Issue by workingmanrob** [home-assistant/addons#1895]
## The problem

Latest zwave addon all climate entries are gone.

My thermostats only have a temperature sensor now and I can no longer adjust the temperature.

## Environment

- Add-on with the issue: zwave-js
- Add-on release with the issue: 1.10
- Last working add-on release (if known): 0.1.7
- Operating environment (OS/Supervised): Raspbian buster with core-2021.2.3 and supervisor-2021.02.11

![image](https://user-images.githubusercontent.com/24377919/109721049-d97be700-7b78-11eb-8732-5721167b1d40.png)

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```txt

```

## Additional information
This is also happening on the zwave-js at another location but running on armbian running the same hass and addon versions

**Comment by workingmanrob** [comment]
Rolled back to zwave-js 0.1.6 from a snapshot and climate is back.

![image](https://user-images.githubusercontent.com/24377919/109723195-c1599700-7b7b-11eb-8269-5bce7b6f9e76.png)

**Comment by MartinHjelmare** [comment]
You need to run at least Home Assistant core 2021.3.0b2 to get the thermostats back. There was a change in Z-Wave JS that became breaking for Home Assistant and we've fixed this in the release that goes out tomorrow.

Please report back after testing 2021.3.0 if it's still an issue. Closing here. Thanks!

**Comment by workingmanrob** [comment]
I knew as soon as I opened it the problem would be fixed... :+1: 

Thanks again and I just confirmed it does work as expected. :beers: 

![image](https://user-images.githubusercontent.com/24377919/109888950-6d6db180-7c52-11eb-96fb-f656e89f107a.png)

![image](https://user-images.githubusercontent.com/24377919/109888861-49aa6b80-7c52-11eb-921a-c6813bd7644c.png)
