### ISSUE TITLE
Mosquitto Broker error on startup

### ISSUE THREAD

**Issue by alesoft73** [home-assistant/addons#1901]
## The problem

On start up the add-on receive this error

[09:18:26] ERROR: Can't setup Home Assistant service mqtt

## Environment

- Add-on with the issue: Mosquitto broker
- Add-on release with the issue:  Current version: 5.1.1
- Last working add-on release (if known):  HA previus version 2021.2
- Operating environment (OS/Supervised):  Hass OS

## Problem-relevant configuration

When add-on start expose this error
[09:18:26] ERROR: Can't setup Home Assistant service mqtt

```yaml

```

## Traceback/Error logs

Only error on mosquitto broker add-on
[09:18:26] ERROR: Can't setup Home Assistant service mqtt
```txt

```

## Additional information
Nothing

**Comment by mamos76** [comment]
i have the same kind of error.
core 2021.3.0
Supervisor 2021.03.4
Home Assistant os: 5.12

**Comment by roschi02** [comment]
I have the same error. But it is not compromising the functionality in my case

**Comment by jsb5151** [comment]
Most likely related to #1887

**Comment by cogneato** [comment]
Add-on config:
```
logins: []
anonymous: false
customize:
  active: false
  folder: mosquitto
certfile: fullchain.pem
keyfile: privkey.pem
require_certificate: false
```

Add-on logs:
```
[22:46:36] INFO: Setup mosquitto configuration
[22:46:36] INFO: Found local users inside config
[22:46:37] INFO: Initialize Home Assistant Add-on services
[22:46:37] ERROR: Can't setup Home Assistant service mqtt
[22:46:37] INFO: Initialize Home Assistant discovery
[22:46:37] INFO: Start Mosquitto daemon
```



Supervisor logs:
```
21-03-10 05:46:35 INFO (SyncWorker_9) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-mosquitto with version 5.1.1
21-03-10 05:46:37 ERROR (MainThread) [supervisor.services.modules.mqtt] There is already a MQTT service in use from core_mosquitto
21-03-10 05:46:39 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'cogneato'
```

I'm seeing this as well but the broker runs as and clients connect just fine.

**Comment by realthk** [comment]
There are serious other problems with MQTT 5.1.1, as it can be seen in #1887
5.1.0 is the last stable version.

**Comment by eole210** [comment]
I started to have the same problem, herratic broker behaviour, this week, with no apparent reason. Is there a way to downgrade to 5.1 when 5.1 was never installed?
All versions are the latest and also having:
In add-on logs: `ERROR: Can't setup Home Assistant service mqtt`
Supervisor logs: `There is already a MQTT service in use from core_mosquitto`
Also to note that basic functionnality still working but as soon as I try to use a MQTT client like MQTTexplorer, all data got scrambled and restart of mosquitto is then required.

**Comment by mumblingsages** [comment]
I'm had the same error message. I rebooted my HA server and the message went away. However, its not adding discovered devices to HA instance.

**Comment by adivinus** [comment]
Same problem! Was happen occasionly.

**Comment by alesoft73** [comment]
I have resolve to remove add-on on Home Assistant and reinstall.
Now the error is disappeared!

**Comment by raidnet-ms** [comment]
I solved this problem reinstalling the integration but it came bavk with latest hassio update (6.x).
Now i'm unable to solve this again.
