### ISSUE TITLE
Deconz add-on shows message in logfile "Option 'vnc_password' does not exist in the schema for deCONZ"

### ISSUE THREAD

**Issue by fribse** [home-assistant/addons#1903]
## The problem

Probably just a cosmetic message, dunno?

## Environment

- Add-on with the issue: deconz
- Add-on release with the issue: 6.7.2
- Last working add-on release (if known): I haven't noticed it before
- Operating environment (OS/Supervised): OS

## Problem-relevant configuration

I see the logmessage, it is true that I don't have a PW on the VNC, as I don't see anywhere to put it.
```yaml

```

## Traceback/Error logs

```txt
21-03-05 15:19:00 WARNING (MainThread) [supervisor.addons.options] Option 'vnc_password' does not exist in the schema for deCONZ (core_deconz)
```

**Comment by frenck** [comment]
It is still there probably. If you go to the deCONZ add-on page, Configuration tab, switch to YAML mode to configure it; it should show up. 

You can remove `vnc_password` from that configuration.

**Comment by fribse** [comment]
You were absolutely right! Thanks @frenck

**Comment by repiuk** [comment]
I also noticed this error. The option to switch to yaml is gone...
