### ISSUE TITLE
Request add add-ons of tinc

### ISSUE THREAD

**Issue by xinyue** [home-assistant/addons#1914]
## The problem

Tinc is a Virtual Private Network (VPN) daemon that uses tunnelling and encryption to create a secure private network between hosts on the Internet.Tinc is easily to expand VPN  network for old computers, but wireguard is difficult to install for some equipments of windows xp. So I request add tinc to home-assistant/addons. Thanks.

http://tinc-vpn.org/
## Environment

- Add-on with the issue:
- Add-on release with the issue: 
- Last working add-on release (if known): 
- Operating environment (OS/Supervised): Winddows XP, Raspbian

## Problem-relevant configuration

none
```yaml

```

## Traceback/Error logs

none
```txt

```

## Additional information
none

**Comment by mdzidic** [comment]
Hello there,

I've created Tinc VPN Client Home Assistant add-on, you can check it on [mdzidic/hassio-tinc-vpn-client](/mdzidic/hassio-tinc-vpn-client)
