### ISSUE TITLE
access to config.txt for deCONZ Add-on not possbile with MacOS

### ISSUE THREAD

**Issue by letszb** [home-assistant/addons#1915]
## The problem

It seems this part
https://github.com/home-assistant/addons/blob/master/deconz/DOCS.md#using-a-raspbee
is not possible for MacOS users. You need to put the SD-card in a Windows PC to access the partition.

## Environment

- Add-on with the issue: deCONZ
- Add-on release with the issue: 6.7.2
- Last working add-on release (if known): never
- Operating environment (OS/Supervised): MacOS for writing SD-card

## Problem-relevant configuration

not needed
```yaml

```

## Traceback/Error logs

not needed
```txt

```

**Comment by frenck** [comment]
That is correct and not a bug :)
