### ISSUE TITLE
Upgrade from HA 2021.2.2 to 2021.3.4 killed all switches and sensors

### ISSUE THREAD

**Issue by IanAdd** [home-assistant/addons#1919]
## The problem

All zigbee entities stopped working on upgrading HA from 2021.2.2 to 2021.3.3 or 3.4

All has worked fine until upgrade, reverting to backup fixes the problem, 
I have a number of xiaomi sensors and switches using the conbee ii . I updated HA deconz integration to latest software version prior to the HA upgrade .

## Environment

Deconz 6.7.2
Pi4 with HASSOS 5.2
- Add-on with the issue:
- Add-on release with the issue: 
- Last working add-on release (if known): 
- Operating environment (OS/Supervised): 

## Problem-relevant configuration

xiaomi temp/humidity sensor
xiaomi switches

```yaml

```

## Traceback/Error logs

DECONZ LOG
09:54:53:173 dev /dev/ttyAMA0
09:54:53:175 GW firmware version: 0x26490700
09:54:53:175 GW firmware version shall be updated to: 0x26660700
09:55:03:323 [INFO] - No button map for: lumi.sensor_ht, unicast to: 0x0000, endpoint: 0x01, cluster: 0x0402, command: 0x0A, payload: 0000299911, zclSeq: 215
09:55:03:324 ZCL attribute report 0x00158D0003590E26 for cluster: 0x0402, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
09:55:03:334 [INFO] - No button map for: lumi.sensor_ht, unicast to: 0x0000, endpoint: 0x01, cluster: 0x0405, command: 0x0A, payload: 000021AD07, zclSeq: 216
09:55:03:335 ZCL attribute report 0x00158D0003590E26 for cluster: 0x0405, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
09:55:23:144 Current channel 15
09:55:23:147 CTRL got nwk update id 0
09:55:23:152 Device TTL 2520 s flags: 0x7
09:55:46:233 [INFO] - No button handler for: lumi.remote.b1acn01, unicast to: 0x0000, endpoint: 0x01, cluster: BASIC (0x0000), command: 0x0A, payload: 01FF421A0121BD0B03281D0421A81305212400062402000000000A210000, zclSeq: 185
09:55:46:234 ZCL attribute report 0x00158D00044D90C4 for cluster: 0x0000, ep: 0x01, frame control: 0x1C, mfcode: 0x115F 
09:55:46:235 0x00158D00044D90C4 extract Xiaomi special attribute 0xFF01
09:55:46:235 	01 battery 3005 (0x0BBD)
09:55:46:236 	03 Device temperature 29 °C
09:55:46:237 	04 unknown 5032 (0x13A8)
09:55:46:238 	05 RSSI dB (?) 36 (0x0024)
09:55:46:238 	06 LQI (?) 8589934592 (0x0200000000)
09:55:46:239 	0a Parent NWK 0 (0x0000)
09:56:23:142 Current channel 15
09:56:23:148 CTRL got nwk update id 0
09:56:23:151 Device TTL 2460 s flags: 0x7
09:57:03:175 dev /dev/ttyAMA0
09:57:03:177 GW firmware version: 0x26490700
09:57:03:178 GW firmware version shall be updated to: 0x26660700
09:57:23:142 Current channel 15
09:57:23:147 CTRL got nwk update id 0
09:57:23:150 Device TTL 2400 s flags: 0x7
09:57:41:879 0x00158D00044A7463 error APSDE-DATA.confirm: 0xE9 on task
09:58:23:144 Current channel 15
09:58:23:148 CTRL got nwk update id 0
09:58:23:152 Device TTL 2340 s flags: 0x7
09:58:29:062 [INFO] - No button map for: lumi.sensor_ht, unicast to: 0x0000, endpoint: 0x01, cluster: 0x0402, command: 0x0A, payload: 0000296411, zclSeq: 217
09:58:29:064 ZCL attribute report 0x00158D0003590E26 for cluster: 0x0402, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
09:58:29:074 [INFO] - No button map for: lumi.sensor_ht, unicast to: 0x0000, endpoint: 0x01, cluster: 0x0405, command: 0x0A, payload: 000021C707, zclSeq: 218
09:58:29:075 ZCL attribute report 0x00158D0003590E26 for cluster: 0x0405, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
09:59:13:174 dev /dev/ttyAMA0
09:59:13:175 GW firmware version: 0x26490700
09:59:13:176 GW firmware version shall be updated to: 0x26660700
09:59:23:143 Current channel 15
09:59:23:149 CTRL got nwk update id 0
09:59:23:153 Device TTL 2280 s flags: 0x7
10:00:23:144 Current channel 15
10:00:23:148 CTRL got nwk update id 0
10:00:23:152 Device TTL 2220 s flags: 0x7
10:01:23:185 dev /dev/ttyAMA0
10:01:23:188 GW firmware version: 0x26490700
10:01:23:189 GW firmware version shall be updated to: 0x26660700
10:01:23:194 Current channel 15
10:01:23:198 CTRL got nwk update id 0
10:01:23:202 Device TTL 2160 s flags: 0x7
10:01:25:169 verified group capacity: 14 and group count: 2 of LightNode 0x00158d0004182c8b
10:01:25:170 0x00158d0004182c8b found group 0xFFF0
10:01:25:172 0x00158d0004182c8b found group 0x0005
10:01:27:424 verified group capacity: 14 and group count: 2 of LightNode 0x00158d0004182896
10:01:27:426 0x00158d0004182896 found group 0xFFF0
10:01:27:427 0x00158d0004182896 found group 0x0001
10:01:37:771 0x00158D0004182896 error APSDE-DATA.confirm: 0xE9 on task
10:01:42:395 [INFO] - No button map for: lumi.sensor_ht, unicast to: 0x0000, endpoint: 0x01, cluster: 0x0402, command: 0x0A, payload: 0000291609, zclSeq: 20
10:01:42:396 ZCL attribute report 0x00158D000393065F for cluster: 0x0402, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
10:01:42:408 [INFO] - No button map for: lumi.sensor_ht, unicast to: 0x0000, endpoint: 0x01, cluster: 0x0405, command: 0x0A, payload: 000021BC16, zclSeq: 21
10:01:42:409 ZCL attribute report 0x00158D000393065F for cluster: 0x0405, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
10:01:48:269 [INFO] - No button map for: lumi.sensor_ht, unicast to: 0x0000, endpoint: 0x01, cluster: BASIC (0x0000), command: 0x0A, payload: 01FF421F0121D10B0421A843052129000624020000000064292C0965210E1C0A21C2BB, zclSeq: 48
10:01:48:270 ZCL attribute report 0x00158D0003534BC4 for cluster: 0x0000, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
10:01:48:271 0x00158D0003534BC4 extract Xiaomi special attribute 0xFF01
10:01:48:272 	01 battery 3025 (0x0BD1)
10:01:48:272 	04 unknown 17320 (0x43A8)
10:01:48:273 	05 RSSI dB (?) 41 (0x0029)
10:01:48:274 	06 LQI (?) 8589934592 (0x0200000000)
10:01:48:274 	64 temperature 2348
10:01:48:275 	65 humidity 7182
10:01:48:276 	0a Parent NWK 48066 (0xBBC2)
10:02:01:201 verified group capacity: 14 and group count: 2 of LightNode 0x00158d00044a7463
10:02:01:203 0x00158d00044a7463 found group 0xFFF0
10:02:01:205 0x00158d00044a7463 found group 0x0005
10:02:23:145 Current channel 15
10:02:23:149 CTRL got nwk update id 0
10:02:23:153 Device TTL 2100 s flags: 0x7
10:03:23:144 Current channel 15
10:03:23:148 CTRL got nwk update id 0
10:03:23:152 Device TTL 2040 s flags: 0x7
10:03:33:176 dev /dev/ttyAMA0
10:03:33:177 GW firmware version: 0x26490700
10:03:33:178 GW firmware version shall be updated to: 0x26660700
10:03:59:715 [INFO] - No button map for: lumi.sensor_ht, unicast to: 0x0000, endpoint: 0x01, cluster: BASIC (0x0000), command: 0x0A, payload: 01FF421F0121A90B0421A81305216A000624010000000064296A096521D0140A210000, zclSeq: 85
10:03:59:717 ZCL attribute report 0x00158D0003534C88 for cluster: 0x0000, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
10:03:59:719 0x00158D0003534C88 extract Xiaomi special attribute 0xFF01
10:03:59:720 	01 battery 2985 (0x0BA9)
10:03:59:722 	04 unknown 5032 (0x13A8)
10:03:59:723 	05 RSSI dB (?) 106 (0x006A)
10:03:59:725 	06 LQI (?) 4294967296 (0x0100000000)
10:03:59:727 	64 temperature 2410
10:03:59:728 	65 humidity 5328
10:03:59:729 	0a Parent NWK 0 (0x0000)
10:04:23:145 Current channel 15
10:04:23:149 CTRL got nwk update id 0
10:04:23:153 Device TTL 1980 s flags: 0x7
10:05:23:143 Current channel 15
10:05:23:147 CTRL got nwk update id 0
10:05:23:151 Device TTL 1920 s flags: 0x7

HA LOG
Logger: homeassistant.config_entries
Source: helpers/entity_registry.py:447
First occurred: 9:30:39 AM (1 occurrences)
Last logged: 9:30:39 AM

Error setting up entry deCONZ-00212EFFFF042BB4 for deconz
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 248, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/deconz/__init__.py", line 37, in async_setup_entry
    await async_update_group_unique_id(hass, config_entry)
  File "/usr/src/homeassistant/homeassistant/components/deconz/__init__.py", line 103, in async_update_group_unique_id
    await async_migrate_entries(hass, config_entry.entry_id, update_unique_id)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 736, in async_migrate_entries
    ent_reg.async_update_entity(entry.entity_id, **updates)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 374, in async_update_entity
    return self._async_update_entity(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 447, in _async_update_entity
    raise ValueError(
ValueError: Unique id '00212E042BB4-/groups/1' is already in use by 'light.hall_3'

```txt

```

## Additional information

Same issue upgrading to 2021.3.3

I have a HUE hub which controls HUE lights, I have not migrated the lights.

**Comment by mattrude** [comment]
I'm receiving the below error:

```[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] config.sh: executing... 
[cont-init.d] config.sh: exited 0.
[cont-init.d] structure.sh: executing... 
[cont-init.d] structure.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[15:44:59] INFO: Successfully send discovery information to Home Assistant.
15:45:01.874 DRIVER   ███████╗ ██╗    ██╗  █████╗  ██╗   ██╗ ███████╗             ██╗ ███████╗
                      ╚══███╔╝ ██║    ██║ ██╔══██╗ ██║   ██║ ██╔════╝             ██║ ██╔════╝
                        ███╔╝  ██║ █╗ ██║ ███████║ ██║   ██║ █████╗   █████╗      ██║ ███████╗
                       ███╔╝   ██║███╗██║ ██╔══██║ ╚██╗ ██╔╝ ██╔══╝   ╚════╝ ██   ██║ ╚════██║
                      ███████╗ ╚███╔███╔╝ ██║  ██║  ╚████╔╝  ███████╗        ╚█████╔╝ ███████║
                      ╚══════╝  ╚══╝╚══╝  ╚═╝  ╚═╝   ╚═══╝   ╚══════╝         ╚════╝  ╚══════╝
15:45:01.885 DRIVER   version 6.5.0
15:45:01.885 DRIVER   
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
ZWaveError: The config has not been loaded yet!
    at ConfigManager.lookupMeter (/usr/lib/node_modules/zwave-js/node_modules/@zwave-js/config/src/ConfigManager.ts:326:10)
    at ConfigManager.lookupMeterScale (/usr/lib/node_modules/zwave-js/node_modules/@zwave-js/config/src/ConfigManager.ts:342:22)
    at new MeterCCReport (/usr/lib/node_modules/zwave-js/src/lib/commandclass/MeterCC.ts:559:43)
    at new CommandClass (/usr/lib/node_modules/zwave-js/src/lib/commandclass/CommandClass.ts:108:13)
    at new MeterCC (/usr/lib/node_modules/zwave-js/src/lib/commandclass/MeterCC.ts:340:1)
    at Function.from (/usr/lib/node_modules/zwave-js/src/lib/commandclass/CommandClass.ts:331:15)
    at new CRC16CCCommandEncapsulation (/usr/lib/node_modules/zwave-js/src/lib/commandclass/CRC16CC.ts:99:37)
    at new CommandClass (/usr/lib/node_modules/zwave-js/src/lib/commandclass/CommandClass.ts:108:13)
    at new CRC16CC (/usr/lib/node_modules/zwave-js/src/lib/commandclass/CRC16CC.ts:52:1)
    at Function.from (/usr/lib/node_modules/zwave-js/src/lib/commandclass/CommandClass.ts:331:15)
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

Here is my config:

## System Health

version | core-2021.3.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 5.4.83-v7l
arch | armv7l
timezone | America/Chicago

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Hass.io</summary>

host_os | Home Assistant OS 5.12
-- | --
update_channel | stable
supervisor_version | supervisor-2021.03.6
docker_version | 19.03.13
disk_total | 57.8 GB
disk_used | 7.9 GB
healthy | true
supported | true
board | rpi4
supervisor_api | ok
version_api | ok
installed_addons | Let's Encrypt (4.11.0), Mosquitto broker (5.1.1), NGINX Home Assistant SSL proxy (3.0.1), Check Home Assistant configuration (3.6.0), SSH & Web Terminal (8.0.3), Z-Wave JS (0.1.11), Z-Wave JS to MQTT (0.7.0), Node-RED (8.1.3), Dnsmasq (1.4.4)

</details>

<details><summary>Lovelace</summary>

dashboards | 3
-- | --
resources | 0
views | 4
mode | storage

</details>

**Comment by csanner** [comment]
this issue appears to be 1.10 to 1.11, not related to HA version.
