### ISSUE TITLE
DuckDns Add-ons Error Jetson Nano unauthorized: authentication required

### ISSUE THREAD

**Issue by letourng** [home-assistant/addons#1921]
## Environment

- Add-on with the issue: Duckdns
- Add-on release with the issue: 1.12.5
- Last working add-on release (if known): 
- Operating environment (OS/Supervised): Ubuntu 18.04

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```txt
docker push homeassistant/aarch64-addon-duckdns:1.12.5
The push refers to repository [docker.io/homeassistant/aarch64-addon-duckdns]
65eb71508c99: Layer already exists 
bcd8688d870b: Layer already exists 
58df3a279424: Layer already exists 
4730d345bd4f: Layer already exists 
c94e1fe6fcf0: Layer already exists 
66b385cf80cf: Layer already exists 
[DEPRECATION NOTICE] registry v2 schema1 support will be removed in an upcoming release. Please contact admins of the docker.io registry NOW to avoid future disruption. More information at https://docs.docker.com/registry/spec/deprecated-schema-v1/
errors:
denied: requested access to the resource is denied
unauthorized: authentication required
```

**Comment by frenck** [comment]
`docker push homeassistant/aarch64-addon-duckdns:1.12.5`

->

`denied: requested access to the resource is denied`

That makes sense, you don't have access to our org? What are you trying to do / report?

**Comment by letourng** [comment]
My Bad sorry I can't installed duckdns because my board has not the right version of network manager. Ubuntu 18.04.5. 
Version is 1.10.

**Comment by frenck** [comment]
> Ubuntu 18.04.5

Is not supported by the Home Assistant project.

**Comment by frenck** [comment]
We do not support Ubuntu. Please refer to our documentation for details.
