### ISSUE TITLE
Update Deconz to 2.10.01 - Fix for Sonoff zbMini

### ISSUE THREAD

**Issue by gang-himself** [home-assistant/addons#1926]
Please update Deconz to the latest Version 2.10.01, as there is a fix for the Sonoff zbMini-Device. 
Here is the issue:

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4016#issuecomment-797743430

With actual version, it‘s seeing many different errors like flickering when switching, loosing connection or simply not working. 

- Add-on with the issue: Deconz
- Add-on release with the issue: 6.7.2
- Last working add-on release (if known): None
- Operating environment (OS/Supervised): HA core-2021.2.3, Supervisor 2021.03.6
--

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```txt

```

**Comment by frenck** [comment]
Deconz v2.10 is currently in beta, we only ship stable versions. Once the beta period is over, the add-on will be udpated.

**Comment by gang-himself** [comment]
Thx for the answer and now also for the update!

**Comment by matteos1** [comment]
in deCONZ to 2.12.6 there is still the problem with the mini sonoffs
