### ISSUE TITLE
z-wave js add-on loses entities after 0.1.10

### ISSUE THREAD

**Issue by sneared** [home-assistant/addons#1933]
See the following discussion:
https://community.home-assistant.io/t/lets-start-talking-about-the-new-z-wave-js-integration/269731/927?u=sneared

z-wave js add-on loses entities when updated to 0.1.12 or 0.1.13. Log files  and dumps are posted in the discussion

**Comment by kpine** [comment]
You need to re-interview the affected nodes. There was a change in zwave-js that caused this.

**Comment by sneared** [comment]
Thanks! Was this a one time change or will it be necessary to re-interview every time there is an update? I assume there was a change in the data structure. When that occurs, perhaps a requirement to re-interview battery nodes could be communicated to users so that it is expected that some entities will become unavailable.




On Wednesday, March 24, 2021, 4:57 PM, kpine ***@***.***> wrote:




You need to re-interview the affected nodes. There was a change in zwave-js that caused this.

**Comment by kpine** [comment]
> Thanks! Was this a one time change or will it be necessary to re-interview every time there is an update? I assume there was a change in the data structure. When that occurs, perhaps a requirement to re-interview battery nodes could be communicated to users so that it is expected that some entities will become unavailable.

Yes, it seems there was a change in how the metadata was created. Sounds like there's not really any way to know when to do so, only when you think something looks wrong... In other words, you're on your own.

v7.0.0 of zwave-js removed re-interviews during restarts, so even mains-powered nodes may need re-interviews in the future for any metadata changes.

**Comment by sneared** [comment]
Thanks again for the information. I appreciate all the work going into zwave-js. But I’m sure you know re-interviewing some battery devices can be really really inconvenient. Nevertheless I’m very happy with HA and support for z-wave.




On Wednesday, March 24, 2021, 5:39 PM, kpine ***@***.***> wrote:





Thanks! Was this a one time change or will it be necessary to re-interview every time there is an update? I assume there was a change in the data structure. When that occurs, perhaps a requirement to re-interview battery nodes could be communicated to users so that it is expected that some entities will become unavailable.


Yes, it seems there was a change in how the metadata was created. Sounds like there's not really any way to know when to do so, only when you think something looks wrong... In other words, you're on your own.

v7.0.0 of zwave-js removed re-interviews during restarts, so even mains-powered nodes may need re-interviews in the future for any metadata changes.

**Comment by kpine** [comment]
Yes, re-interviewing battery devices, especially the ZCOMBO, can be painful. I don't think changes like this are a common occurrence though. Generally I'd expect something like this to be mentioned as a "breaking change" in the release notes, but maybe it was just missed.

The good news is that interviewing battery devices is much improved for versions after v6.5.0; it's much more likely to succeed the first time.

**Comment by sneared** [comment]
Not to extend the exchange I really appreciate the information. Are you on the development group? If so, I’d be happy to help test or do some coding. I’m particularly interested in the device configuration files.




On Wednesday, March 24, 2021, 5:54 PM, kpine ***@***.***> wrote:




Yes, re-interviewing battery devices, especially the ZCOMBO, can be painful. I don't think changes like this are a common occurrence though. Generally I'd expect something like this to be mentioned as a "breaking change" in the release notes, but maybe it was just missed.

The good news is that interviewing battery devices is much improved for versions after v6.5.0; it's much more likely to succeed the first time.

**Comment by kpine** [comment]
> Are you on the development group?

Nope, just another user.

**Comment by sneared** [comment]
I updated the add-on to 0.1.14. I woke up the zcombo multiple times. The log shows “node data updated” but the entities are still showing unavailable. Right now it looks like my only alternative is to exclude and re-include the node. I’ll post the network dump later. Back to 0.1.10!




On Wednesday, March 24, 2021, 6:22 PM, kpine ***@***.***> wrote:





Are you on the development group?


Nope, just another user.
