### ISSUE TITLE
Unable to start mosquitto addon

### ISSUE THREAD

**Issue by zarya** [home-assistant/addons#1934]
## The problem
[services.d] starting services
[services.d] done.
[22:18:43] ERROR: Requested resource /info was not found
[22:18:43] FATAL: Unknown log_level: 
[cmd] /run.sh exited 1

## Environment

- Add-on with the issue: mosquitto
- Add-on release with the issue: 5.1.1
- Last working add-on release (if known): 
- Operating environment (OS/Supervised): supervisor-2021.03.6

## Problem-relevant configuration

It happens also with the default configuration.

## Traceback/Error logs

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[22:18:43] ERROR: Requested resource /info was not found
[22:18:43] FATAL: Unknown log_level: 
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

**Comment by buzztiaan** [comment]
fyi, downgrading to 5.1 made the issue go away

**Comment by Bonuscoupon** [comment]
How did you downgrade? Did you use a backup?

**Comment by buzztiaan** [comment]
https://github.com/home-assistant/addons/issues/1887#issuecomment-798879366
 
 instead of forking, he did : 
`cd /usr/share/hassio/addons/
cp -R core/mosquitto local/
 `

**Comment by NetJaro** [comment]
> [#1887 (comment)](https://github.com/home-assistant/addons/issues/1887#issuecomment-798879366)
> 
> instead of forking, he did :
> 
> > cd /usr/share/hassio/addons/
> > cp -R core/mosquitto local/

Hi

I dont have hassio/addons folder :(
