### ISSUE TITLE
Public Static IP

### ISSUE THREAD

**Issue by elik745i** [home-assistant/addons#1949]
## The problem

  When I try to pull ssl certificates on HASSIO and public static IP (I entered my email and my static IP instead of domain) addon does not pull certificates into ssl folder and logs does not show anything. Port forwarding is set up 8123, 443 and 80 and access to the HA using http gained.

## Environment

Latest available version - 4.11.0

- Add-on with the issue:
- Add-on release with the issue: 
- Last working add-on release (if known): 
- Operating environment (OS/Supervised): 

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```txt

```

**Comment by cogneato** [comment]
You cannot get a certificate for an IP address. You didn't mention if you were using it, but the DuckDNS add-on is only for DuckDNS domains.
