### ISSUE TITLE
Mosquitto addon

### ISSUE THREAD

**Issue by NetJaro** [home-assistant/addons#1956]
There are unexpected disconnects from clients. After disconnect client can't reconnect after some time (10min, sometimes 2h).

Home Assistant with HASSIO on terminal HP T610, 2GB RAM, SSD disc 128GB.
Proxmox.

- Add-on with the issue: Mosquitto broker
- Add-on release with the issue: 5.1.1
- Last working add-on release (if known): don't know (i use only 5.1.1) 
- Operating environment (OS/Supervised): HomeAssistant HASSIO HP610, Proxmox

## Problem-relevant configuration

LOG with Docker connection:

> 1617054300: New client connected from 172.30.32.1 as 3JqAyLAkOcYcTP5f2sNsWu (p2, c1, k60, u'homeassistant').
> 1617054549: Socket error on client 3JqAyLAkOcYcTP5f2sNsWu, disconnecting.
> 1617054575: New connection from 172.30.32.1 on port 1883.
> 1617054575: New client connected from 172.30.32.1 as 7e2bOlP1LqPKmKaYchpVPr (p2, c1, k60, u'homeassistant').
> 1617054980: Saving in-memory database to /data/mosquitto.db.
> 1617056235: Socket error on client 7e2bOlP1LqPKmKaYchpVPr, disconnecting.

```

## Traceback/Error logs
<!--
  If you come across any trace or error logs, please provide them.
-->

```txt

```

**Comment by botts7** [comment]
Same issue for me

**Comment by botronic** [comment]
Same here

**Comment by Heox420** [comment]
Same

**Comment by dworkin74** [comment]
Same
