### ISSUE TITLE
Z-Wave JS to MQTT not working with any devices

### ISSUE THREAD

**Issue by frogbite** [home-assistant/addons#1958]
I recently went from OZW to Z Wave JS using the official Z Wave JS add-on.  Had all my devices recognized and working but saw some flaky behavior such as a Leviton switch going into a "Dead" status that I had to keep excluding and including to get working again.  

So, decided that it would be good to have more control so decided to go the route of the MS to MQTT route so I would have the dashboard.  The installation went well, I deinstalled the old add-on and removed the integration.  I then installed the Z-Wave JS to MQTT "Current version: 0.9.1" and added the integration back in.   It saw all of my devices from my Aeotec Z-Stick Gen5.  But they all showed as either dead or asleep and the manufacturer and other details were either a series of "xxxxxxxx" or blank.  

After excluding and including several devices over and over, still not able to get anything to be fully recognized.  It is like it is not able to identify devices at all.  The only things that appears healthy is the AEON Z-Stick.  

Not sure how to debug this further.  Here are the particulars about my setup:

Rasperry PI gen 3b running HASIO 5.12
Supervisor supervisor-2021.03.6
Core core-2021.3.4

After a factory reset, this is what the Z Wave JS Integration shows for a Dome Motion Sensor:

Device info
Z-Wave Info
Home ID: 3561276991
Node ID: 2
Node Status: Asleep
Node Ready: No

No matter what I do, such as trying to wake up the device or trying to add one my Leviton switches in, I never have success identifying the device other than it being on the network.  Not sure if this is an integration issue or an add-on issue, but did not have the same problem with nothing working with official add-on.

**Comment by MartinHjelmare** [comment]
What does it say for the network, ws url etc, in the Z-Wave JS config panel (click "configure" on the Z-Wave JS integration card)?

**Comment by raman325** [comment]
Also, did you configure the same network key for zwavejs2mqtt as you did for the official addon?

**Comment by frogbite** [comment]
Add-on config is:

```
Container | Host | Description
3000/tcp |   | Z-Wave JS communication
```

I am using the same network key as was used by the official add-on.  Before removing the official I copied the key off to a notepad and reused it.  The integration did not complain about it, so should be good.

**Comment by MartinHjelmare** [comment]
Please check the config panel in the integration card. What does it say under network?

**Comment by frogbite** [comment]
Well that is odd.  The card is blank.  The integration shows two devices, one being the AEON stick and the other being the included motion sensor with no entities.  I guess I should try removing the and adding the integration back in?

**Comment by MartinHjelmare** [comment]
Make sure you uncheck the check box to use the add-on when configuring the integration, if you go through the config flow again.

**Comment by frogbite** [comment]
Removed and added again:

```
Network Connected
ws://192.168.1.235:3000
Driver Version: 7.0.1
Server Version: 1.3.1
Home ID: 3561276991
Nodes ready: 1 / 2
```

Will try to do a re-interview on the motion sensor.

**Comment by frogbite** [comment]
Yay, I was able to wake it up.  The only bummer is that it does not appear to be in the ZWave JS database:

```
  "id": 2,
  "deviceId": "NaN-NaN-NaN",
  "manufacturer": "Unknown manufacturer 0xXXXX",
```

The only thing mentioned for Dome in the "Z-Wave JS Config DB Browser" is the companies range extender.  Could have sworn that I had the manufacturer there with official add-on, but maybe I am remembering wrong.  I think we can close this out unless something thinks it is important to figure out why the integration got into that bad state.

**Comment by frogbite** [comment]
Hmmm, this not seeing any entities for the motion sensor but I can drill into the values in the control panel such as sensitivity settings and such.

**Comment by raman325** [comment]
> Yay, I was able to wake it up. The only bummer is that it does not appear to be in the ZWave JS database:
> 
> ```
>   "id": 2,
>   "deviceId": "NaN-NaN-NaN",
>   "manufacturer": "Unknown manufacturer 0xXXXX",
> ```
> 
> The only thing mentioned for Dome in the "Z-Wave JS Config DB Browser" is the companies range extender. Could have sworn that I had the manufacturer there with official add-on, but maybe I am remembering wrong. I think we can close this out unless something thinks it is important to figure out why the integration got into that bad state.

I have a device that is usually known but is showing the exact same info as what you've described here. I haven't tried replacing the batteries yet but last time this came up a battery replacement squared things away.

**Comment by raman325** [comment]
> Hmmm, this not seeing any entities for the motion sensor but I can drill into the values in the control panel such as sensitivity settings and such.

What do the `Status` and `Interview Status` columns say for this device? If `Interview Status` is not `Complete` or `RestartFromCache`, then that means the node isn't considered ready which is why you may not see entities

**Comment by frogbite** [comment]
Finally, had to wake it up several more times and go through the interview.  It is happy now.  Sees it as an Elexa Motion sensor and it is working.   Now to add my Leviton switches.

**Comment by raman325** [comment]
great! Can you close this issue as well, or is there still a problem?

**Comment by frogbite** [comment]
Going to close this and open a new one on issues getting Leviton switches recognized as it seems different.
