### ISSUE TITLE
RPC Shutdown doesn't start with HA on Docker/Synology

### ISSUE THREAD

**Issue by Philou06** [home-assistant/addons#1963]
RPC freshly installed and configured but it doesn't start 

  Hass.io on Docker / NAS Synology 415D+
  Hass Core - 2021.3.4
  RPC Shutdown version 2.2

The RPC Addon doesn't even start and in the Docker log on NAS I have this error message :
_Start container addon_core_rpc_shutdown failed: {"message":"OCI runtime create failed: container_linux.go:345: starting container process caused \"exec: \\\"/dev/init\\\": stat /dev/init: no such file or directory\": unknown"}._

Any idea to solve this problem, please?

Thx

PS : I tried to intall it on another Hass installation, this time on a Raspberry with HA OS and it start and works great but I want to use it on my NAS now.

**Comment by n0dr4c** [comment]
Hi,
I have exactly the same issue since a core upgrade 2 months ago, before it it worked like a charm. I use hass.io with docker on synology NAS. The addon docker container does not start.

**Comment by cogneato** [comment]
Running HA with Supervisor (né "Hass.io") on a Synology is an installation which has been deprecated as Synology is using an old version of docker which cannot be updated.

https://community.home-assistant.io/t/home-assistant-supervised-previously-known-as-hass-io-on-synology-dsm-as-native-package-not-supported-or-working-atm/125559

Installing as a VM on Synology NAS which support it is preferred, or the single HA docker image.
