### ISSUE TITLE
Starting Home Assistant GAssisant SDK...

### ISSUE THREAD

**Issue by hoanglongutc** [home-assistant/addons#1976]
Hi, I am installing the google assistant SDK add-on.
After consulting many documents I tried many different ways, but the google assistant SDK still cannot start.
The log always displays the following:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[10:28:56] INFO: Installing/Updating service client_secrets file
[10:28:56] INFO: Starting Home Assistant GAssisant SDK..
![1](https://user-images.githubusercontent.com/35026043/114968383-6a482100-9ea0-11eb-9376-658336b2d0c0.JPG)
![2](https://user-images.githubusercontent.com/35026043/114968384-6b794e00-9ea0-11eb-8f74-c957990821a2.JPG)

**Comment by MihaiZaim** [comment]
Having the same problem. Did anyone find a fix?
