### ISSUE TITLE
File Editor renders incorrectly (missing css?)

### ISSUE THREAD

**Issue by ohhai-kthxbai** [home-assistant/addons#1977]
## The problem

Hi. 
![file-editor](https://user-images.githubusercontent.com/19961661/115051159-6df59b00-9ed4-11eb-8696-89754500f135.PNG)

File editor seems to load without css?
I've tried different browsers (FF, Chrome) including FF safe mode. 
Tried deleting all cache files.
Tried uninstalling/re-installing File Editor add-on.

Any help appreciated! Thanks.

## Environment

- Add-on with the issue: File Editor
- Add-on release with the issue: 5.2.0 
- Last working add-on release (if known): Sorry, not sure.
- Operating environment (OS/Supervised): supervisor-2021.04.0 (in a VM), core-2021.4.4

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```txt

```

**Comment by frenck** [comment]
The file editor fetched style sheets from the internet. Got something in your browser preventing those from being downloaded?

**Comment by ohhai-kthxbai** [comment]
> 
> 
> The file editor fetched style sheets from the internet. Got something in your browser preventing those from being downloaded?

Spot on. After trying different machines, and browsers and disabling all add-ons - what worked was using a different server with my VPN provider. I suspect that whoever serves the css (AWS?) were refusing connections to/from a specific VPN IP address.

Thank you @frenck. I really appreciate yor work.

**Comment by skipper22hassio** [comment]
Same problem, AddGuard addon was blocking something. Could say in the AddGuard query log which address it was. Deactivated AddGuard, opened File Editor, worked, activated AddGuard, works since then.
