### ISSUE TITLE
DeCONZ: 'auto_uart' is deprecated, use 'uart'

### ISSUE THREAD

**Issue by vlumikero** [home-assistant/addons#1981]
## The problem

Warning message in the Supervisor log:

```
WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of deCONZ.

```
## Environment

- Add-on with the issue: deCONZ
- Add-on release with the issue: 6.8.0
- Last working add-on release (if known): 
- Operating environment (OS/Supervised): core-2021.4.6, supervisor-2021.04.0

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```txt
WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of deCONZ.
```

**Comment by frenck** [comment]
This has been removed in deCONZ add-on version 6.6.5

![image](https://user-images.githubusercontent.com/195327/115456612-a6bea880-a223-11eb-9e5d-89b7dc06c489.png)


See: <https://github.com/home-assistant/addons/pull/1825>

**Comment by vlumikero** [comment]
Could it be that there’s some left over configuration somewhere in my
installation? There doesn’t seem to be a way to get rid of it.

**Comment by frenck** [comment]
That should not be possible, at least, I have not come across such cases.

**Comment by vlumikero** [comment]
Any idea why this could happen?

**Comment by ludeeus** [comment]
@vlumikero do you still see those messages?

**Comment by vlumikero** [comment]
Yes, still there.
________________________________

**Comment by ludeeus** [comment]
That should not be possible as @frenck stated...
Can you do a reboot of the host and paste the full supervisor log after the startup?

**Comment by vlumikero** [comment]
This is what it looks like:

'''
21-07-28 08:31:00 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
21-07-28 08:31:00 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
21-07-28 08:31:00 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
21-07-28 08:31:00 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
21-07-28 08:31:00 INFO (MainThread) [supervisor.resolution.check] System checks complete
21-07-28 08:31:00 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
21-07-28 08:31:01 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
21-07-28 08:31:01 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
21-07-28 08:31:01 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
21-07-28 08:33:50 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-07-28 08:37:59 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
21-07-28 08:37:59 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
21-07-28 08:38:02 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of deCONZ
21-07-28 08:38:04 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of deCONZ

**Comment by ludeeus** [comment]
Please post the details from here <https://www.home-assistant.io/more-info/system-health#github-issues>

**Comment by vlumikero** [comment]
## System Health

version | core-2021.7.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.9.5
os_name | Linux
os_version | 5.10.17-v7
arch | armv7l
timezone | Europe/Stockholm

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4808
Installed Version | 1.13.2
Stage | running
Available Repositories | 911
Installed Repositories | 31

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.1
-- | --
update_channel | stable
supervisor_version | supervisor-2021.06.8
docker_version | 20.10.6
disk_total | 28.6 GB
disk_used | 18.2 GB
healthy | true
supported | true
board | rpi3
supervisor_api | ok
version_api | ok
installed_addons | Home Assistant Google Drive Backup (0.104.3), File editor (5.3.3), RPC Shutdown (2.2), Samba share (9.5.1), Terminal & SSH (9.1.3), Duck DNS (1.13.0), deCONZ (6.9.0), Glances (0.12.3), Mosquitto broker (6.0.1), Eufy Home Assistant MQTT Bridge (1.20.0), AdGuard Home (4.1.6)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 18
views | 17
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Comment by vlumikero** [comment]
Any ideas, @ludeeus?

**Comment by ludeeus** [comment]
no
