### ISSUE TITLE
Samba Share addon config changes get reverted when trying to save

### ISSUE THREAD

**Issue by CoryAlbrecht** [home-assistant/addons#1982]
## Description

When I go to the configuration tab for the Samba Share addon and try to make changes, like change the workgroup or allowed IP addresses, when I click on teh save button the chnages are reverted back to teh default configuration

## Environment

Latest HomeAssistant Supervised in docker on virtualised Ubuntu 20.04 LTS

**Comment by cogneato** [comment]
This would be a problem with the formatting of your add-on config. Make sure you are matching the existing format as shown with the default configuration.
