### ISSUE TITLE
Unreadable terminal font

### ISSUE THREAD

**Issue by slepiavka** [home-assistant/addons#1983]
Hi,

I've always had the same issue with the terminal being completely unreadable, for which I couldn't find any archived issues:
![Example](https://user-images.githubusercontent.com/67871383/115642093-30778000-a2cf-11eb-851e-e114eda5ad88.png)

Interestingly enough, the initial ASCII art seems to render correctly: 
![image](https://user-images.githubusercontent.com/67871383/115642401-be536b00-a2cf-11eb-891b-018b8b09f59d.png)

**Terminal & SSH** 
Current version: 9.1.0 

**Environment**: 
Home Assistant OS 5.13
core-2021.4.6
supervisor-2021.04.0
Host: Raspberry Pi 4, 2gb RAM

This has persisted across restarting and re-installing T&SSH, updates, host reboots, etc, on two different Win10 machines.

Thanks

**Comment by frenck** [comment]
Are you using the Brave browser?

**Comment by slepiavka** [comment]
This happened on Firefox 88.0, x64. Private session doesn't work.
Add-ons: Bitwarden, DuckDuckGo, Facebook Containers, Firefox Milti-account Containers, Firefox Relay, uBlock Origin and Python Notebook Viewer.
Tried on my work's computer with Chrome on incognito, and that worked. So it seems it's browser-caused. Not sure if this deserves the community's attention then, but perhaps it's not just one case?

**Comment by frenck** [comment]
Up until now, I was only aware of the brave browser doing this.

**Comment by slepiavka** [comment]
@Sudo-Rob that's it! Already reported to DDG. Not sure what the root cause is,, but it's an easy fix.

**Comment by Amenobiss** [comment]
The same problem. Disable Brave Shields (address bar, on the right) and now it shows ok!

**Comment by jhogendorn** [comment]
This has started appearing even when brave shields are disabled :(

**Comment by radinsky** [comment]
Same here with shields down (latest homeassistant and brave):
![image](https://user-images.githubusercontent.com/4540268/188304992-2c7b7072-2e1f-4df3-86b2-ea2538b49a93.png)

**Comment by paulomar** [comment]
> Same here with shields down (latest homeassistant and brave): ![image](https://user-images.githubusercontent.com/4540268/188304992-2c7b7072-2e1f-4df3-86b2-ea2538b49a93.png)

I've the same problem on brave, works fine on MS Edge

**Comment by slepiavka** [comment]
Did you disable adblockers or privacy extensions?

**Comment by githubkusi** [comment]
Corrupted fonts in Brave browser with shields down, correct fonts in FF

**Comment by barry-vt** [comment]
FF works fine, Vivaldi has the font problem, same engine as Brave.  How does one correct these fonts?  Post a ticket on Vivaldi's site?

**Comment by ManOnWire** [comment]
> I have the same issue with Firefox, but disabling DuckDuckGo Privacy Essentials protection corrects the display. I haven't investigated any further.
> 
> Try adding your URL to 'unprotected sites.'

Ran into this issue as well. Can confirm that adding my HA site to the list of unprotected sites In DuckDuckGo Privacy Essentials (extension) solved the issue for me.

**Comment by radinsky** [comment]
I've tested it now, for me it started to work (with shields up, latest brave and latest HA) 
![image](https://user-images.githubusercontent.com/4540268/211198540-65b22a7b-d462-4aca-bfab-6ff4f8e98ade.png)
