### ISSUE TITLE
Request to update Mosquitto addon to use Mosquitto 1.6+ or 2.0+ to support mqtt v5

### ISSUE THREAD

**Issue by SweVictor** [home-assistant/addons#1984]
## The problem

Request to update Mosquitto addon to use Mosquitto 1.6+ or 2.0+ to support mqtt v5.

Communicating over mqtt with HA it would be nice to be able to use v5 functionality, specifically the "no local / nl" setting to avoid echoing back messages sent.

## Environment

- Add-on with the issue: Mosquitto
- Add-on release with the issue: 5.1.1
- Last working add-on release (if known): N/A
- Operating environment (OS/Supervised):  Supervised

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```txt

```

**Comment by fliphess** [comment]
I have the latest mosquitto version (2.something) working with the go-auth-plugin by [iegomez](https://github.com/iegomez/mosquitto-go-auth) 

A preview can be found here: https://github.com/fliphess/addons/blob/master/prometheus/Dockerfile

The auth plugin by jpmens does not compile on newer auth versions afaik.
Sir @pvizeli do you perhaps know the current state of the auth plugin by jpmens? The fork used for the mosquitto addon seems to be maintained by you?

If it's OK'd by the maintainers, I can create a PR updating mosquitto and replacing the jpmens auth with the newer go auth plugin.

(only if I can get it 100% compatible with the current http auth using the older plugin of course)

**Comment by frenck** [comment]
This issue is being worked on. Please don't ping maintainers @fliphess.

**Comment by fliphess** [comment]
Was that on alpine perhaps? Because there are indeed some issues using alpine (I switched to debian:buster)

**Comment by frenck** [comment]
Yes, that is Alpine, I've also got a debian buster version, but cross compiling that in our build environments with cgo is another issue right now.

Thus I'm working on a different approach for now.
