### ISSUE TITLE
RPC Shutdown not working

### ISSUE THREAD

**Issue by ck003** [home-assistant/addons#1993]
## The problem
Call service RPC Shutdown, but it does not work.

## Environment

- Add-on with the issue: RPC Shutdown
- Add-on release with the issue:  2.2
- Last working add-on release (if known):  2.2
- Operating environment (OS/Supervised):  HASSOS

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

![image](https://user-images.githubusercontent.com/19967081/116577959-86899a80-a943-11eb-8a45-90c184fca037.png)

```txt

```

**Comment by Flaxing** [comment]
Have same problem.
Add-on with the issue: RPC Shutdown
Operating environment (OS/Supervised): supervisor-2021.04.0
Home Assistant 2021.4.6

**Comment by cogneato** [comment]
@ck003 This is a configuration on the Windows side that you need to make, as provided by @Flaxing 's link
https://community.home-assistant.io/t/rpc-shutdown-working-on-windows-10-windows-remote-shutdown/257767
