### ISSUE TITLE
ring second-generation contact sensor issue on mosquitto MQTT addon

### ISSUE THREAD

**Issue by fantastxu** [home-assistant/addons#2008]
Using this awesome addon without any issue until I added two new second-generation ring contact sensors into my alarm system. I can add them to my HA through addon but their entities become unavailable after two or three days. Reboot the HA core will help to solve the problem temporarily but after two or three days, the issue returns.  All my other first-generation ring contact sensors are all fine.

**Comment by ludeeus** [comment]
Since restarting core, does not impact how an add-on works.
I'd suggest you open an issue in the core repository 👍 (and fill out the provided issue template there)
