### ISSUE TITLE
MQTT seems to have broken with latest 6.0.1 update

### ISSUE THREAD

**Issue by Rusti-gotrage** [home-assistant/addons#2020]
## The problem

Since updating the MQTT broker in Supervisor, I've noticed connection issues with multiple applications talking to MQTT, especially the PAI add-on (Paradox Alarm Interface), but that might be because it's the most 'visible' to me...

I'm not seeing the log update with the connections like I used to. Demonstrated when I connect to MQTT using MQTT-Explorer, as well as when I restart Node-Red or PAI addons in Supervisor.
When PAI finally DOES deign to connect, I'm not getting the statuses of all the devices.

## Environment

Running v.6.0.1 of MQTT on HASS core-2021.5.5 on a Raspberry Pi 4

## Traceback/Error logs

And I keep seeing this in my HomeAssistant Core logs:
2021-05-20 16:49:59 ERROR (Thread-4) [homeassistant.components.mqtt] Unable to connect to the MQTT broker: Connection Refused: not authorised.

## Additional information

Stupidly I didn't do a snapshot backup before upgrading MQTT - another user in Discord had the same issues, but he DID a snapshot and was able to rollback and get everything working again...

**Comment by frenck** [comment]
Please provide add-on configuration details, client configuration details, what versions are used and OS details.

I need a reproduction scenario in order to troubleshoot this report.

**Comment by Rusti-gotrage** [comment]
PAI 2.5.2
MQTT 6.0.1
Core:   core-2021.5.5
Supervisor:   supervisor2021.04.3  Stable
Host:   OS  Home Assistant OS 5.13 Production

Redacted configs @  https://pastebin.com/Sp7HCvYv

**Comment by ivankarpov** [comment]
Same here:
PAI 2.5.2
MQTT 6.0.1
Core: core-2021.5.5

**Comment by ivankarpov** [comment]
After enabled verbose mode of mosquito found this:

1621585592: Denied PUBLISH from paradox_mqtt/3edb0d6834396faf (d0, q0, r1, m0, 'paradox/interface/run_status', ... (7 bytes))
1621585592: Denied PUBLISH from paradox_mqtt/3edb0d6834396faf (d0, q0, r1, m0, 'paradox/interface/availability', ... (7 bytes))
1621585592: Denied PUBLISH from paradox_mqtt/3edb0d6834396faf (d0, q0, r1, m0, 'paradox/interface/run_status', ... (7 bytes))
1621585592: Denied PUBLISH from paradox_mqtt/3edb0d6834396faf (d0, q0, r1, m0, 'paradox/interface/availability', ... (7 bytes))

Please note that in the PAI configuration is set right user and password for MQTT and the PAI is successfully connected to the MQTT server

**Comment by ivankarpov** [comment]
Seems that the less-restrictive ACL files fix the problem . 

1.  Mosquitto broker configuration should like this 
```
logins[]:
customize:
  active: true
  folder: mosquitto
certfile: fullchain.pem
keyfile: privkey.pem

```
2.  The acl file ( /usr/share/hassio/share/mosquitto/accesscontrollist  or  /share/mosquitto/accesscontrollist in the mosquitto container ) has to contain 2 lines 
```
topic readwrite #
pattern readwrite # 
```

**Comment by yozik04** [comment]
@frenck Something is wrong with Mosquito in 6.x. I have created a dummy python script to test it and compare with my separate mosquito installation.

```
import logging
import random
from time import sleep

import paho.mqtt.client as paho

logging.basicConfig(level=logging.DEBUG)

logging.debug("Test")

broker = "192.168.1.5"
port = 1883

mqttc = paho.Client("control1")  # create client object
mqttc.enable_logger()

#mqttc.username_pw_set("user", 'pass')

def on_publish(client, userdata, result):  # create function for callback
    print("data published \n")
    pass

mqttc.on_publish = on_publish  # assign function to callback

def on_connect(client, userdata, flags, rc):
    print("Connection returned result: " + paho.connack_string(rc))

    rc, info = mqttc.publish("dummy/test1", random.randint(0, 255), qos=1)
    print(rc, info)

mqttc.on_connect = on_connect

mqttc.connect(broker, port)  # establish connection
mqttc.loop_start()

info = mqttc.publish("dummy/test2", random.randint(0, 255), qos=1)
print(info.rc, info)

info.wait_for_publish()
sleep(1)
```

First step:
Let's start without specifying username and password.
Run script
You will still see Connection Accepted and PUBACK received.
But there will be nothing in MQTT Explorer

Next step:
Let's uncomment
`mqttc.username_pw_set("user", 'pass')`
and change accordingly. I specify credentials in mosquitto plugin this way:
```
logins:
  - username: user
    password: pass
```
Run script
topic will appear in mqtt
then comment `mqttc.username_pw_set` again
Rerun the script. It still accepts topics
change client id, rerun
still accepts messages

Restart mosquitto plugin.
Run script
now no messages appear but paho mqtt does not know the reason it still thinks everything is fine and messages are sent.

**Comment by yozik04** [comment]
I also had a problem that every second script run was sending message but now I can not reproduce that.

**Comment by Rusti-gotrage** [comment]
> Seems that the less-restrictive ACL files fixed the problem .
> 
> 1. Mosquitto broker configuration should like this
> 
> ```
> logins[]:
> customize:
>   active: true
>   folder: mosquitto
> certfile: fullchain.pem
> keyfile: privkey.pem
> ```
> 
> 1. The acl file ( /usr/share/hassio/share/mosquitto/accesscontrollist  or  /share/mosquitto/accesscontrollist in the mosquitto container ) has to contain 2 lines
> 
> ```
> topic readwrite #
> pattern readwrite # 
> ```

All I need to do now is un-noob myself and figure out how to access the Mosquitto container to make this change...

**Comment by frenck** [comment]
@Rusti-gotrage that suggest seems really wrong. Why would setting a default permission help? All MQTT users already have a default permission...

**Comment by Rusti-gotrage** [comment]
I'm grasping at straws here.... I certainly won't pretend to be the most knowledgeable person around...!
I've not been able to get that 'fix' in so I'm still at square one right now...

My logs are still showing me:

1621591746: mosquitto version 1.6.12 running
1621591746: New connection from 127.0.0.1 on port 1883.
1621591746: Socket error on client <unknown>, disconnecting. 

Which it never used to prior to this issue rearing it's head... 

When I restarted MQTT in the past, the log in HASS/Supervisor was quickly updated, clients showed up as soon as they connected and showed as disconnected in the logs as soon as they were restarted/killed - now I'm dealing with a log file that shows me Homebridge connecting, then freezes, despite my connecting with MQTT Explorer and the PAI logs saying that IT has connected to MQTT as well...

What's REALLY interesting, is Homebrige, which is running my Rinnai integration, is connecting IMMEDIATELY when MQTT restarts, AND the connection SEEMS to be working, because I'm controlling Rinnai MQTT objects within HASS and it seems to be echoing through to the Rinnai interface via MQTT without issue.... it's just nothing else wants to work!

**Comment by ChrisPotDev** [comment]
I reverted back to 5.1.1

I could see in MQTT logs that my clients connected, but no traffic passed.
If I connected from MQTT FX on windows with the same user details, I could send messages. and HA would respond.
However my esp devices messages were not passing through. it is not purely related to user permissions.

**Comment by mmoci** [comment]
I can also observe 
1621591746: Socket error on client , disconnecting. 
trace after restart.

All topics seems to be published and subscribed by my MQTT client.
On MQTT broker add on I can see following traces:
1621509042: New client connected from 192.168.0.10 as /light/bedroom/desk/ (p2, c1, k15, u'myUserName').
But the messages seems not working in my case, nothing has been exchanged according to MQTT Explorer.

**Comment by sconkdk** [comment]
I have same problem running this code on a esp32 https://github.com/buxtronix/am43

**Comment by nardusleroux** [comment]
Seeing same issue here on:
core-2021.5.5
supervisor-2021.04.3
MQTT 6.0.1
PAI 2.5.2

When I restore MQTT 5.1.1 all ok again. No changes to any configs done between MQTT releases.

**Comment by yozik04** [comment]
@frenck I have tried to use all available parameter combinations
Protocol version 5, websockets transport all kind of QOS level still nothing is received.

**Comment by yozik04** [comment]
@frenck I found root cause of it.

Try to specify client as "client/12345" with slash and all published messages will be filtered out with no error.

I will remove slash but I've seen other projects also use it.

**Comment by Scallam** [comment]
I also noticed that all MQTT devices were working fine except for my Inverter which had the slash / in the client name

**Comment by sconkdk** [comment]
I can confirm it is a bug in the clientname including /

**Comment by ChrisPotDev** [comment]
> I can confirm it is a bug in the clientname including /

None of my usernames or clientnames contain special charachters, I would have to check the code of the integrations I use.

**Comment by bytespider** [comment]
MQTT clients that use colons in their usernames seem to also be broken in 6.0.1.
For example, I have devices that use the mac address as the username.
From logs:
```
21-05-22 14:49:36 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for '34'
21-05-22 14:49:37 WARNING (MainThread) [supervisor.auth] Unauthorized login for '34'
```

and 

```
1621694977: |-- mosquitto_auth_unpwd_check(34:xx:xx:xx:xx:xx)
1621694977: |-- ** checking backend files
1621694977: |-- ** checking backend http
1621694977: |-- url=http://127.0.0.1:80/authentication
1621694977: |-- data=username=34%3Axx%3Axx%3Axx%3Axx%3Axx&password=XYZ&topic=&acc=-1&clientid=XYZ
1621694977: |-- getuser(34:xx:xx:xx:xx:xx) AUTHENTICATED=0 by none
```

As you can see only the segment before the first colon was parsed by the API. This was working in 5.1.1.

**Comment by userMak** [comment]
any updates for the above. I have several switches that just don't work anymore. Is there a plan to be fixed? (same problem as @bytespider

**Comment by ntompson** [comment]
Same here. Updating to 6.0.1 broke a whole bunch of services I have running on other servers that communicate with my HA instance over MQTT. These are python scripts using the `paho` MQTT client library. The clients all connect successfully and without error, but receive no messages on the topics to which they are subscribed. On rollback to 5.1.1, the scripts immediately start working again.

My clients were logging in with client names that included a `/`, but changing them to an `_` character didn't help, nor did removing the `/` character entirely.

Is there any clarity as to what is happening with this? Is there a 6.0.2 update coming to fix the issue? Or is it something wrong with `paho`?

**Comment by userMak** [comment]
> Same here. Updating to 6.0.1 broke a whole bunch of services I have running on other servers that communicate with my HA instance over MQTT. These are python scripts using the `paho` MQTT client library. The clients all connect successfully and without error, but receive no messages on the topics to which they are subscribed. On rollback to 5.1.1, the scripts immediately start working again.
> 
> My clients were logging in with client names that included a `/`, but changing them to an `_` character didn't help, nor did removing the `/` character entirely.
> 
> Is there any clarity as to what is happening with this? Is there a 6.0.2 update coming to fix the issue? Or is it something wrong with `paho`?

hi can you tell me how I can roll back to 5.1.1 please?

**Comment by ntompson** [comment]
Just go to Snapshots and pick the snapshot taken when you upgraded to 6.0.1. Choose restore and you should be good.

**Comment by userMak** [comment]
> Just go to Snapshots and pick the snapshot taken when you upgraded to 6.0.1. Choose restore and you should be good.

Thanks, I am on 5.1.1 and it is working fine

**Comment by jacotec** [comment]
I also have serious issues with 6.0.1.

When I start the complete host, MQTT starts but does not work - all MQTT data points just don't work, neither for reading nor writing. When I restart just the MQTT via supervisor on the running host, I'm getting the error message:

`ERROR (MainThread) [supervisor.services.modules.mqtt] There is already a MQTT service in use from core_mosquitto
`

6.x looks pretty untested for me, 5.1.1 works like a charm. Looks like I'll wait a couple of weeks before the next attempt of 6.x

My other versions:
Supervisor: 2021.5.4
Core: 2021.6.0
Host: 5.13

**Comment by ntompson** [comment]
Any progress on this? It's been quite a while...

**Comment by PhilippeRaven** [comment]
Got the same issue here. Since last Mosquitto update, I can't get my MQTT data (from a python script) in Mosquitto even when using a user/pass. I see my client ID connected to Mosquitto, but no data is passing.
I tried to publish with MQTT Explorer, it works only with a user/pass, but it works. So I don't understand, and it's only since this update.

**Comment by erte1** [comment]
@frenck Just wondering if you're up to speed on the recent findings detailed by @bytespider 

There are many reported issues, but none seem to have an assignee.

**Comment by erte1** [comment]
@frenck @ludeeus bump

**Comment by kr0ner** [comment]
```
> 1621694977: |-- mosquitto_auth_unpwd_check(34:xx:xx:xx:xx:xx)
> 1621694977: |-- ** checking backend files
> 1621694977: |-- ** checking backend http
> 1621694977: |-- url=http://127.0.0.1:80/authentication
> 1621694977: |-- data=username=34%3Axx%3Axx%3Axx%3Axx%3Axx&password=XYZ&topic=&acc=-1&clientid=XYZ
> 1621694977: |-- getuser(34:xx:xx:xx:xx:xx) AUTHENTICATED=0 by none
> ```
From where did you get this log? 🤔 I have an idea for a possible fix, but without being able to reproduce this log it will be a walk in the dark.

**Comment by T-REX-XP** [comment]
How about preparing PR with a fix??))

**Comment by kr0ner** [comment]
I can try to do so over the weekend👍

To be able to properly test it, I need to fix another issue first : the MSS310 connects, I can see the topics sent from/to it, but the values are all zero (except timestamp). Switching it on and off surprisingly works though.

**Comment by kr0ner** [comment]
> How about preparing PR with a fix??))

@T-REX-XP Here you go ;) https://github.com/home-assistant/addons/pull/2137
Seems to work so far. At least zigbee2mqtt was able to connect.
There is still some parts that are to be checked. Would appreciate a review.
Will build the docker image and push it within the next days so that testing becomes easier.

**Comment by Keltere** [comment]
> Will build the docker image and push it within the next days so that testing becomes easier.

Hi, thanks a lot for your work.
Did you setup a repository for testing this fix?
Thanks.

**Comment by Keltere** [comment]
To anyone who wants to try it just download Kr0ner repo https://github.com/kr0ner/addons/tree/kr0ner_mosquitto_sqlite and copy the mosquitto folder inside /addons with the samba addons.

**Comment by kr0ner** [comment]
If anybody wants to try: https://github.com/kr0ner/mosquitto
I've finally managed to create a docker and push it to dockerhub. Currently there is only the amd64 one available ... got cross compilation failures for the others but will try again tomorrow. You can install the addon by adding the repo in the "Supervisor" -> "Add-on Store" tab through "..." and "Repositories". Had to completely remove the official add-on and restart the system to not have conflicting instances. Also had to delete the MQTT integration under "Settings" --> "Integrations" cause it picked up the wrong container. If it works for you maybe leave a comment here https://github.com/home-assistant/addons/pull/2137 to get this integrated.

**Comment by ntompson** [comment]
So is there a fix in the works here? I can't quite tell where this is heading. I tried to update this add on a few days ago after resolving some DNS issues I thought might be related, but my `paho` clients still get broken by this version.

**Comment by cyberplant** [comment]
> topic readwrite #
> pattern readwrite #

I was developing a new software for a Wio Terminal and lost many hours debugging the MQTT client there, until I realized the MQTT broker in home-assistant was eating all the messages! 

Is it possible to add a flag to allow all packets to go through? or enable that by default unless somebody wants to limit the access?

Oh, BTW, adding this I stopped receiving the "Socket error" each one second (issue #2097)

**Comment by mgomersbach** [comment]
No it's not stale, I have this issue, and no workaround yet.

**Comment by kr0ner** [comment]
> No it's not stale, I have this issue, and no workaround yet.

https://github.com/home-assistant/addons/issues/2020#issuecomment-900392280

There is ... they just won't accept it

**Comment by mholst87** [comment]
In case it helps anyone, I was able to get MQTT working again by removing the trailing "/" from my topics.  Anything with a trailing slash seemed to just disappear into the void.  Earlier in this thread somebody mentioned trailing slash could be a problem in client IDs or usernames as well.

**Comment by bytespider** [comment]
bump

**Comment by javierferwolf** [comment]
hi to all colleagues, I have the same problem as everyone who is writing right now in this chat!
 @kr0ner the solution about copy and paste the mosquitto folder in the addons folder  https://github.com/kr0ner/mosquitto it only works for amd64 architectures right?   I have a Raspberry Pi 2 model B I understand that it will not work right?
 
 and colleagues is there any other solution for this problem?

**Comment by kr0ner** [comment]
> hi to all colleagues, I have the same problem as everyone who is writing right now in this chat!
>  @kr0ner the solution about copy and paste the mosquitto folder in the addons folder  https://github.com/kr0ner/mosquitto it only works for amd64 architectures right?   I have a Raspberry Pi 2 model B I understand that it will not work right?
>  
>  and colleagues is there any other solution for this problem?
>  

Way easier... just go to the supervisor tab in home assistant and add https://github.com/kr0ner/mosquitto as a custom repo there. I've created docker images for all archs in the meantime

**Comment by ntompson** [comment]
Hi all - is there any way we can make progress on this with the official add-on? I don't understand why there seems to be a Mexican stand off in progressing one way or the other. I'm still stuck on `5.1.1` and becoming increasingly nervous about security vulnerabilities the older it gets. 

I appreciate the work you've done @kr0ner to set up an alternative image, but I feel that this should be dealt with in the official image. And there seems to be a fundamental problem with the approach you've taken, which leads me to wonder whether there is another / better way?

To recap my issue: I have many clients working with the official MQTT broker. If I upgrade from `5.1.1` to `6.0.1`, some clients lose the ability to publish. To be specific, any client using the Python `paho-mqtt` package. 

I have checked that there are no trailing `/`s in topic or client names. I've been over every other comment made here. I've checked that my clients are using the latest `paho-mqtt` version (they are: `1.6.1`).

I just don't understand what about `6.0.1` breaks these clients.

I'd be happy to help, but I don't know where to start.

Any thoughts how we can find a solution?

**Comment by bytespider** [comment]
@ntompson there are other solutions #2259 but again little to no response from the core team

**Comment by kr0ner** [comment]
@ntompson the docker images that I've provided are not meant to replace the official addon, but to provide an easy solution to people suffering from the breaking changes introduced by 6.x.x 

There is a PR that would fix it upstream and does not break the Home Assistant auth. However I can't get @frenck to have a look at it.

**Comment by ntompson** [comment]
OK - thanks for your comments @bytespider and @kr0ner. It's a bit surprising to me that we can't figure out a way forward. I just don't have the depth of technical understanding to figure out how to break the deadlock, but it seems strange to me that the version bump from `5.1.1` to `6.0.1` caused this issue (and possibly another in #2097) and yet it has hung around for so long unresolved.

I'd really appreciate it if the core team are able to pick this up. MQTT is a critical part of the HA infrastructure. It's incredibly useful for integrating "ad-hoc things" while minimising development effort. But right now, the latest version doesn't work with the latest Python MQTT library, leaving us all in a pickle.

**Comment by ans-gw** [comment]
Problem is still active even with Version 6.11.
Daly Log and Voltronic/homeassistant both not working anymore after update...cant get any mqqq value.
Someone can fix this plz?
Very very important....

switch back to Mosquito 5 ...and all Ok.

**Comment by marrobHD** [comment]
I also still experience this issue. Since today...

**Comment by ntompson** [comment]
TL;DR: don't use `/` or `_` in your MQTT client IDs.

For anyone still stuck on this, I finally figured out where I was going wrong (it was on me). The symptoms of my problem were that upgrading from `5.1.1` to `6.x.x` caused publishing from python scripts I use for various purposes started to fail silently. The script could connect, but all attempts to publish went into a black hole.

Put simply: the client id can't include `/` or `_` characters. This is part of the MQTT spec; it must have started getting enforced from `6.x.x` of this add-on. 

To give an example:

```py
import paho.mqtt.client as mqtt

client_bad = mqtt.Client('this_is_bad_and/so/is/this')
client_ok = mqtt.Client('this-is-fine')
```

After going through all of my python scripts and getting rid of `_` and `/` characters in the client ID, I could update to the current version (`6.2.1`) with no issues.

If you're still having issues and not using scripts like me, it could be that you have an add-on / integration / custom component / library that is using bad characters. Take a look in the MQTT add-on log for connection attempts and see whether these characters are used.

[This issue](https://github.com/ParadoxAlarmInterface/pai/issues/242#issuecomment-845927933) was what finally tipped me off.
