### ISSUE TITLE
deCONZ + Phoscon: blank page with error "Request Entity Too Large"

### ISSUE THREAD

**Issue by rafaelmaza** [home-assistant/addons#2021]
## The problem

Blank page is displayed when "Phoscon" (Web App) button is clicked in deCONZ add-on.

Also, an error message appears in the browser console:

```
GET https://my-domain:8123/api/hassio_ingress/.../pwa/index.html 413 (Request Entity Too Large)
```

## Environment

- Add-on with the issue: deCONZ
- Add-on release with the issue:  6.9.0 (also happened with 6.8.0)
- Last working add-on release (if known): 6.8.0 worked at some point
- Operating environment (OS/Supervised): Ubuntu 20.04.2 LTS / supervisor-2021.04.3 / HA core-2021.5.4

## Problem-relevant configuration

No configuration required. Steps to reproduce are simply:
1. Go to add-on page (https://my-domain:8123/core_deconz)
2. Click "Phoscon" blue button
3. Blank page gets displayed with the error below in the console.

## Traceback/Error logs

From browser's console:

```txt
GET https://my-domain:8123/api/hassio_ingress/.../pwa/index.html 413 (Request Entity Too Large)
```

## Additional information

None at this stage.

**Comment by jankryh** [comment]
Hi, I have a same issue error 413  with addon deCONZ version 6.9.0 
Previous deCONZ version 6.8.0 works well  
OS Debian GNU/Linux 10 (buster), supervisor-2021.04.3, core-2021.5.5

**Comment by ferigan** [comment]
Same  issue here since upgrading to 6.9.0. Running Hass on Home Assistant Blue.

Problem seems to manifest itself on Chrome (Version 90.0.4430.212 (Official Build) (64-bit))

If I use MS Edge Phoscon works just fine.

**Comment by jankryh** [comment]
I can confirm that it works with MS Edge .. issue is only with Chrome Version 90.0.4430.212

**Comment by Perlnx** [comment]
Same problem too, Unbelievable this is a bug since there are no message about Phoscon in changelog.
I mess up my server again to reinstall HAS & Flash FW for Conbee ii since I though these system is broken.

I will never update deCONZ add-on anymore, Sigh.

* My browser is Firefox

**Comment by maxmeyer** [comment]
I had the same problem. Restarting the browser - chromium - didn't help. I deleted the whole cache of the browser. After that, it works again like a charme. @Perlnx Can you try that?

**Comment by Perlnx** [comment]
Yest, tried that but still doesn't work. I've to use Edge chromium to access Phoscon.
However after update HA core to 2021.6, Phoscon back to normal and able to access via Firefox.

This made me confuse. Problem occur after update deCONz but fixed by update HA :S
