### ISSUE TITLE
Mosquitto add-on verbose logging 

### ISSUE THREAD

**Issue by b3nj1** [home-assistant/addons#2022]
Hi,
The mosquitto logging level has been increased (again). Back in PR https://github.com/home-assistant/addons/pull/1708, we used the system logging level into the mosquitto logging level, but this has been removed in https://github.com/home-assistant/addons/pull/2007.

I'd like to submit a PR to address this, but first, @frenck, was the unconfigurable logging level change intentional for some reason. If it was intentional, is there a preferred way to make it configurable over the way we had it below?

New template log level:  
https://github.com/home-assistant/addons/blob/54ce6a192283fa6b5e0e84b741930c6b9ca64053/mosquitto/rootfs/usr/share/tempio/mosquitto.gtpl#L7

Old code to set logging level based on configured level:
https://github.com/home-assistant/addons/blob/107585db0ce949b46270644a580f090331a02a21/mosquitto/data/run.sh#L92-L101

Thanks,

- Benjamin

**Comment by frenck** [comment]
There is not need to do that or add such logic. If you want to override settings on that level, the customization feature is available. That would allow you to write about any option to mosquitto.
