### ISSUE TITLE
‘AddonManager.install’ blocked from execution, no host internet connection

### ISSUE THREAD

**Issue by jeanbart82** [home-assistant/addons#2024]
‘AddonManager.install’ blocked from execution, no host internet connection

Can't get arround this.

core-2021.5.5 on HA blue

Was trying to update Adguard from version 4.1.2 to 4.1.6, Got this error. tried to delete adguard and install again... same error.
tried to reboot host. still same error. changed dns on router to 4.4.4.4 and 8.8.8.8 rebooted host and still same error when i tried to install adguard. Also tried to update different add-on and still same error.

## Environment

- Add-on with the issue:
- Add-on release with the issue: 
- Last working add-on release (if known): 
- Operating environment (OS/Supervised): 

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```txt

```

**Comment by ludeeus** [comment]
This has nothing to with any of the add-ons in this repository
The supervisor blocks tasks that require internet if it can't verify the network connection.
Sometimes using the "Restart supervisor" button on Supervisor -> System <https://my.home-assistant.io/redirect/supervisor_info/> helps.

If that does not help, try asking for help troubleshooting your installation on [discord](https://discord.com/invite/home-assistant) 👍
