### ISSUE TITLE
frequent connection errors/socket error on client  MQTT 6.0.1

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/addons#2025]
## The problem

frequent connection errors, which also have very cryptical references to the clients

## Environment

- Add-on with the issue: MQTT
- Add-on release with the issue: 6.0.1
- Last working add-on release (if known): 5.1
- Operating environment (OS/Supervised): OS

## Problem-relevant configuration

```yaml
logins:
  - username: redacted
    password: redacted
customize:
  active: false
  folder: mosquitto
certfile: fullchain.pem
keyfile: privkey.pem
require_certificate: false
```

## Traceback/Error logs

```txt
1621584385: New connection from 127.0.0.1 on port 1883.
1621584385: Socket error on client <unknown>, disconnecting.
1621584385: New connection from 192.168.1.27 on port 1883.
1621584385: New client connected from 192.168.1.27 as 70:B3:D5:6F:31:F2 (p1, c0, k60, u'redacted').
1621584389: New connection from 192.168.1.165 on port 1883.
1621584389: New client connected from 192.168.1.165 as 2Yjhzyh2B7yCsu4pW2Nteo (p2, c1, k60, u'redacted').
1621584389: New connection from 192.168.1.71 on port 1883.
1621584389: New client connected from 192.168.1.71 as 1g6JN5uQvFCWlHQiXgs7wn (p2, c1, k60, u'redacted').
1621584400: New connection from 172.30.32.2 on port 1883.
1621584400: Socket error on client <unknown>, disconnecting.
1621584520: New connection from 172.30.32.2 on port 1883.
1621584520: Socket error on client <unknown>, disconnecting.
1621584640: New connection from 172.30.32.2 on port 1883.
1621584640: Socket error on client <unknown>, disconnecting.
1621584668: Socket error on client 2Yjhzyh2B7yCsu4pW2Nteo, disconnecting.
1621584689: New connection from 192.168.1.165 on port 1883.
1621584689: New client connected from 192.168.1.165 as 4m7534z1jclkNESBEyssZ5 (p2, c1, k60, u'redacted').
1621584760: New connection from 172.30.32.2 on port 1883.
```

1.27 is doing fine
1.165 is the instance on which this broker is running
172.30.32.2 not sure which internal ip this is
1.71 is another HA instance subscribing to this instance (165)

## Additional information

also, even though the `anonymous:` option is no longer used, this is still displayed I the supervisor log:

```
21-05-21 08:03:47 WARNING (MainThread) [supervisor.addons.options] Option 'anonymous' does not exist in the schema for Mosquitto broker (core_mosquitto)
21-05-21 08:04:33 WARNING (MainThread) [supervisor.addons.options] Option 'anonymous' does not exist in the schema for Mosquitto broker (core_mosquitto)
```

so, stopping the Add-on to give it a fresh restart makes this happen:
```
21-05-21 08:25:48 INFO (SyncWorker_2) [supervisor.docker.interface] Stopping addon_core_mosquitto application
21-05-21 08:25:50 INFO (SyncWorker_2) [supervisor.docker.interface] Cleaning addon_core_mosquitto application
21-05-21 08:26:25 INFO (SyncWorker_2) [supervisor.docker.addon] Starting Docker add-on homeassistant/armv7-addon-mosquitto with version 6.0.1
21-05-21 08:26:30 ERROR (MainThread) [supervisor.services.modules.mqtt] There is already a MQTT service in use from core_mosquitto
```

seems there are more than 1 instance in the system?

**Comment by frenck** [comment]
"anonymous" has been removed, you'll have to remove it from your configuration.

The log messages are normal, it is the supervisor checking regularly if mosquito is still responding.

These are not bugs.

**Comment by Mariusthvdb** [comment]
thanks, but, as you can see, I don't have the `anonymous:` in my config. Hence this issue...

**Comment by frenck** [comment]
The socket error is normal, as it is not an MQTT client, it is the supervisor that pokes a response

**Comment by Mariusthvdb** [comment]
I don't know, but it seems even after a host reboot, and even  a power cut (needed that because the instance wouldn't come back after the update), there is still a remnant of the previous config left somewhere. 

Should I maybe delete the add-on, and re-install afresh? Right now, I updated the add-on, after which these warnings/errors started. (the socket errors weren't there before)

**Comment by tomlut** [comment]
> The socket error is normal, as it is not an MQTT client, it is the supervisor that pokes a response

So, just for clarification, a log filled with these messages (every 2 seconds) is normal?
```
2021-06-23T15:27:31: New connection from 172.30.32.2 on port 1883.
2021-06-23T15:27:31: Socket error on client <unknown>, disconnecting.
```

**Comment by GaTechThomas** [comment]
Can we not do something on the other end to make the disconnect graceful?

**Comment by apizioq4** [comment]
Hi there, 
I don't think it's spam. I think the log entry with the socket error comes from an external iot which is misconfigurated to talk to the mqtt server. 
I have set up an SBFspot to send my inverter data through the mqtt protocol to the mqtt server but in homeassistant I don't see any data. After shutting down the SBFspot, the error messages in the mqtt log are away. 
But now I'm stuck and the SBFspot will not send the data to mqtt server. ... 
Am I right?
