### ISSUE TITLE
mqtt 6.0.1 Socket errors and device disconnecting

### ISSUE THREAD

**Issue by Tomax77** [home-assistant/addons#2027]
## The problem

Newest mosquitto mqtt addon not working properly as it produces many errors when connecting to a client in log:

1621617441: New connection from 172.30.32.1 on port 1883.
1621617441: Socket error on client <unknown>, disconnecting.
1621617456: New connection from 172.30.32.1 on port 1883.
1621617456: Socket error on client <unknown>, disconnecting.
1621617471: New connection from 172.30.32.1 on port 1883.
....

HA Core messages are:
21-05-21 17:26:07 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'mqtt'
21-05-21 17:26:08 WARNING (MainThread) [supervisor.auth] Unauthorized login for 'mqtt'

## Environment

HA Supervised
core-2021.5.5
supervisor-2021.04.3
OS: Debian Buster 10
Docker: 20.10.6

- Add-on with the issue: mosquitto mqtt
- Add-on release with the issue: 6.0.1
- Last working add-on release (if known):  5.1.1
- Operating environment (OS/Supervised): Debian Buster HA Supervised

## Problem-relevant configuration

#Mosquito config:
logins:
    username: mqtt
    password: XXXXX
customize:
  active: false
  folder: mosquitto
certfile: fullchain.pem
keyfile: privkey.pem
require_certificate: false

#zigbee2mqtt config:
data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://192.168.XXX.XXX:1883'
  user: mqtt
  password: XXXXXXX
serial:
  port: >-
    /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B001938C45E-if00
advanced:

**Comment by Mariusthvdb** [comment]
duplicate? see: https://github.com/home-assistant/addons/issues/2025

**Comment by Tomax77** [comment]
Ok, didn't mention this messages in version 5.1.1. But if it is normal behaviour my issue can be closed

**Comment by Tomax77** [comment]
Repeating HA core messages are strange and consulting. Any clue to solve it?

**Comment by mhzawadi** [comment]
I found that a reconfig of the integration to use the user I setup for MQTT sorted out any issues I had
