### ISSUE TITLE
Updating Mosquitto broker to 6.0.1 stops AM43 from working

### ISSUE THREAD

**Issue by balbulator** [home-assistant/addons#2030]
The problem
After updating to version 6.0.1, the am43 integration from buxtronix stopped working
(https://github.com/buxtronix/am43/issues/28)
In version 5.1.1 everything works well

Environment
raspberry pi 4, Raspbian OS, Home Assistant 2021.5.5, Mosquitto broker version: 6.0.1, ESP32 (A-OK)

Traceback/Error logs
```
Logger: homeassistant.helpers.template
Source: helpers/template.py:1367
First occurred: 17:31:53 (107 occurrences)
Last logged: 18:23:09

Template variable warning: 'dict object' has no attribute 'tamper' when rendering '{{ value_json.tamper }}'
Template variable warning: 'dict object' has no attribute 'consumer_overload' when rendering '{{ value_json.consumer_overload }}'
Template variable warning: 'dict object' has no attribute 'led_disabled_night' when rendering '{{ value_json.led_disabled_night }}'
Template variable warning: 'dict object' has no attribute 'power_outage_memory' when rendering '{{ value_json.power_outage_memory }}'
Template variable warning: 'dict object' has no attribute 'auto_off' when rendering '{{ value_json.auto_off }}'
```
What changes have occurred in the latest release? How can you fix it? How can I roll back a version of mosquitoes to the previous one?
Thank you

**Comment by ludeeus** [comment]
That has nothing to do with the add-on.
Those errors are from how templates are used in Home Assistant, a few versions ago it started to warn about misconfigurations.
https://www.home-assistant.io/blog/2021/04/07/release-20214/#warnings-for-undefined-variables-in-templates
