### ISSUE TITLE
400 Client error

### ISSUE THREAD

**Issue by Severe1** [home-assistant/addons#2032]
I receive the following exception on booting the addon

400 Client Error for http+docker://localhost/v1.39/containers/792e88f597c388d811879a8ad75fe889f20a4fb30d631d9b54eca8a54a68e01d/start: Bad Request ("OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/dev/init\": stat /dev/init: no such file or directory": unknown")

**Comment by frenck** [comment]
This is not an add-on issue, but a system configuration issue.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
