### ISSUE TITLE
File Editor - Rename File popup doesn't start with cursor in new file input box

### ISSUE THREAD

**Issue by dagwud** [home-assistant/addons#2033]
## The problem
Really small and silly request, but in the File Editor (Configurator) addon, the "Rename" menu brings up a popup to prompt for the file name, but the caret is not placed in the input box. A small usability fix (putting the cursor in the text box to allow you to just start typing) would be nice. When doing housekeeping and renaming a bunch of files, this extra click is pesky.

## Environment
HAOS 5.13
core-2021.5.5
supervisor-2021.04.3

- Add-on with the issue: File Editor (Configurator)
- Add-on release with the issue: 5.3.0
- Last working add-on release (if known): None known
- Operating environment (OS/Supervised): OS

## Problem-relevant configuration
Steps to reproduce:
* Open File Editor
* Click the "Browse Filesystem" icon
* Click on the "..." next to any file name
* Click Rename
* Note the popup which asks "Please enter a new name for <filename>" - if you just start typing, nothing happens as the cursor is not placed in the input box
```yaml

```

## Traceback/Error logs
None relevant

```txt

```

## Additional information
I debated whether this issue should be filed here or in 'frontend', but my logic says the frontend issue tracker is more for central UI, not plugin-specific UI, which I would guess this is. If this is incorrectly logged, apologies - please refer me appropriately.

**Comment by dagwud** [comment]
Just confirmed, to be sure - still a problem in File Editor 5.3.1, which I hadn't yet noticed was available

**Comment by frenck** [comment]
Hi there @dagwud 👋 

Add-ons wrap existing application, and thus the applications themselves are not developed here.
Changes like these need to be suggested upstream, once it has been fixed/added, we can update the application running in the add-on.

Please report your suggestion here:

<https://github.com/danielperna84/hass-configurator>

Thanks!

../Frenck

**Comment by dagwud** [comment]
Thanks Frenck! TIL. I was puzzled at not being able to see the addon code itself in the repo; now I understand a bit better.

Logger request at https://github.com/danielperna84/hass-configurator/issues/215
