### ISSUE TITLE
Devcontainer no longer works when starting supervisor.sh in the container

### ISSUE THREAD

**Issue by KJonline** [home-assistant/addons#2056]
## The problem

When running the dev container for home assistant adding and trying to start home assistant which uses the supervisor.sh script. An error is being thrown in the console and home assistant doesn't start stopping adding from being tested locally.

## Environment

- Add-on with the issue:
- Add-on release with the issue: 
- Last working add-on release (if known): 
- Operating environment (OS/Supervised): Mac OSX

## Problem-relevant configuration

{
	"name": "Home Assistant Add-Ons",
	"context": "..",
	"dockerFile": "Dockerfile",
	"appPort": ["7123:8123", "7357:4357"],
    "postStartCommand": "service docker start",
	"runArgs": ["-e", "GIT_EDITOR=code --wait", "--privileged"],
	"containerEnv": {
		"WORKSPACE_DIRECTORY": "${containerWorkspaceFolder}"
	},
	"extensions": [
		"timonwong.shellcheck",
		"esbenp.prettier-vscode"
	],
	"settings": { 
		"terminal.integrated.shell.linux": "/bin/bash"
	}
}

## Traceback/Error logs

![image](https://user-images.githubusercontent.com/29937485/120681462-5037c180-c493-11eb-8d49-59b0e8ddc1af.png)

output when running dockerd

![image](https://user-images.githubusercontent.com/29937485/120681899-c89e8280-c493-11eb-9427-68c4a475fc6e.png)

**Comment by ludeeus** [comment]
It should not try to change that anymore unless you run on Alpine <https://github.com/home-assistant/addons/pull/2000>

```
    if grep -q 'Alpine' /proc/version; then
        # The docker daemon does not start when running Alpine backed WSL2 without adjusting iptables
        update-alternatives --set iptables /usr/sbin/iptables-legacy || echo "Fails adjust iptables"
        update-alternatives --set ip6tables /usr/sbin/iptables-legacy || echo "Fails adjust ip6tables"
    fi
```

Do you have a fresh copy of the `master` branch?

**Comment by KJonline** [comment]
Yes I have the latest copy from master. When you say alpine do you mean the base Docker image, it runs on, mine starts using a Debian base image. But running that command to check for alpine  manually inside the container comes back true.

**Comment by ludeeus** [comment]
What does `/proc/version` output?

**Comment by ludeeus** [comment]
Closing as stale 👍

**Comment by csacca** [comment]
I know this issues is stale/closed, but I'm just leaving this as a note in case anyone runs into this in the future. Running WSL2 on Windows 10 Build 19042, I had to change the current `master` version of `supervisor.sh` to the following to get `dockerd` to start inside the container:

```bash
if grep -q 'Alpine|standard-WSL|standard-WSL2' /proc/version; then
        # The docker daemon does not start when running WSL2 without adjusting iptables
        update-alternatives --set iptables /usr/sbin/iptables-legacy || echo "Fails adjust iptables"
        update-alternatives --set ip6tables /usr/sbin/iptables-legacy || echo "Fails adjust ip6tables"
fi
```
