### ISSUE TITLE
supervisor logs core-samba errors (Option 'interface' does not exist in the schema for Samba share) 

### ISSUE THREAD

**Issue by jprates** [home-assistant/addons#2059]
Core: 2021.6.2
Supervisor: 2021.05.4
Host: Home Assistant OS 5.13
Samba share: 9.5.0 

I just noticed a recurring error on my supervisor logs.

I'm not sure for how many versions it is there, but I'm almost sure it wasn't there some 3 core versions ago, sorry for not being that much precise and helpful regarding versions. 

An example supervisor log entry with the error:

[supervisor.txt](https://github.com/home-assistant/addons/files/6602478/supervisor.txt)

And the corresponding samba log:

[core-samba.txt](https://github.com/home-assistant/addons/files/6602635/core-samba.txt)

Let me know if you need more help for debugging my system.

Cheers,
-jprates

**Comment by martymarty004** [comment]
The interface option warning is probably due to the changes in the latest version (9.5.0):


```
9.5.0
Remove interface options in favor of network
```

I already opened an issue about the other strange logs here -> #2040

**Comment by jprates** [comment]
I've found your issue prior to posting this one, but since the messages are all quite different I can't assume the cause is the same.
This means just that, that I cannot say both issues are, or are not, related, but thanks for the input.

**Comment by martymarty004** [comment]
To remove the `Option 'interface' does not exist` warnings, you can simply remove that line from the Add-on config.

**Comment by jprates** [comment]
Boy do I feel silly now... I had not noticed this line in the config:

`interface: ''`

It seems this was the source for the error message, and for whatever reason the message was not being triggered on previous versions.

This being said, I presume it is safe to close this issue.

**Comment by jprates** [comment]
Closing.

**Comment by martymarty004** [comment]
>for whatever reason the message was not being triggered on previous versions

That is because the `interface` option was removed in the latest release, but I'm happy that I could help you.

**Comment by habitoti** [comment]
Still doesn't solve "Invalid token for access /network/interface/default/info" error. It actually only occurred after removing the interface option form config. So seems like I exchanged a harmless schema warning for a "real" error now... :-(

**Comment by antoweb** [comment]
> To remove the `Option 'interface' does not exist` warnings, you can simply remove that line from the Add-on config.
> 
> I am also experiencing the `Invalid token for access /network/interface/default/info` error.

I have 9.6.1 version and the option "interface" is not present. but warning in supervisor log still present. Why? Bug?

**Comment by antoweb** [comment]
Solved by myself, i have to click in yaml config to unhide the hiddent option interface.
removed saved and restarted addon

allow_hosts:
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.1.0/24
interface: ''
