### ISSUE TITLE
Trying to add: G125 E27 Filament Globe

### ISSUE THREAD

**Issue by JamieP83** [home-assistant/addons#2060]
## The problem
Cannot add philips Zigbee bulb: G125 E27 Filament Globe
found here: https://www.philips-hue.com/en-gb/p/hue-white-filament-1-pack-g125-e27-filament-globe/8719514279131#specifications

## Environment

- Add-on with the issue: Deconz
- Add-on release with the issue: 6.9.0 
- Last working add-on release (if known): 
- Operating environment (OS/Supervised): HassOS 

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```txt

```

**Comment by frenck** [comment]
Add-ons wrap existing software, in this case deCONZ. We don't develop that software itself. Please report this issue with deCONZ. If it get fixed and released, this add-on will be updated.
