### ISSUE TITLE
"Check Home Assistant configuration" fails on checking nodred

### ISSUE THREAD

**Issue by wessa66** [home-assistant/addons#2064]
## Environment

- Add-on with the issue: "Check Home Assistant configuration"
- Add-on release with the issue: version: 3.7.1
- Last working add-on release (if known): 
- Operating environment (OS/Supervised): Home Assistant OS 5.13

## Traceback/Error logs

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[19:13:46] INFO: Don't worry, this temporary installation is not overwriting your current one.
[19:13:46] INFO: Installing Home Assistant: latest...
[19:13:46] INFO: Please be patient, this might take a few minutes...
[19:15:19] INFO: Installed Home Assistant 2021.6.3
[19:15:19] INFO: Making a copy of your configuration for checking...
[19:15:23] INFO: Checking your configuration against this version...
[19:19:49] ERROR: The configuration check did not pass!
[19:19:49] ERROR: See the output below for more details.
Testing configuration at /tmp/config
Failed config
  General Errors: 
    - Component error: nodered - Integration 'nodered' not found.

Successful config (partial)
[19:19:49] INFO: The full output has been written to /share/check_config.txt
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

##################
Log from /share/check_config.txt

INFO:homeassistant.util.package:Attempting install of colorlog==5.0.1
�[01mTesting configuration at /tmp/config�[0m
INFO:homeassistant.util.package:Attempting install of home-assistant-frontend==20210603.0
INFO:homeassistant.util.package:Attempting install of aiohttp_cors==0.7.0
INFO:homeassistant.util.package:Attempting install of sqlalchemy==1.4.13
INFO:homeassistant.util.package:Attempting install of pillow==8.1.2
INFO:homeassistant.util.package:Attempting install of icmplib==2.1.1
INFO:homeassistant.util.package:Attempting install of python-nmap==0.6.1
INFO:homeassistant.util.package:Attempting install of getmac==0.8.2
INFO:homeassistant.util.package:Attempting install of ring_doorbell==0.6.2
INFO:homeassistant.util.package:Attempting install of ha-ffmpeg==3.0.2
INFO:homeassistant.util.package:Attempting install of scapy==2.4.5
INFO:homeassistant.util.package:Attempting install of aiodiscover==1.4.2
INFO:homeassistant.util.package:Attempting install of pyRFXtrx==0.26.1
INFO:homeassistant.util.package:Attempting install of pushbullet.py==0.11.0
INFO:homeassistant.util.package:Attempting install of netdisco==2.8.3
INFO:homeassistant.util.package:Attempting install of mutagen==1.45.1
INFO:homeassistant.util.package:Attempting install of gTTS==2.2.2
INFO:homeassistant.util.package:Attempting install of hass-nabucasa==0.43.0
INFO:homeassistant.util.package:Attempting install of PyNaCl==1.3.0
INFO:homeassistant.util.package:Attempting install of emoji==1.2.0
INFO:homeassistant.util.package:Attempting install of distro==1.5.0
INFO:homeassistant.util.package:Attempting install of homeassistant-pyozw==0.1.10
INFO:homeassistant.util.package:Attempting install of python-openzwave-mqtt[mqtt-client]==1.4.0
�[01;37mFailed config�[0m
  �[01;31mGeneral Errors:�[0m �[31m�[31m
    - Component error: nodered - Integration 'nodered' not found.
�[0m
�[01;37mSuccessful config (partial)�[0m

```

## Additional information

**Comment by frenck** [comment]
`nodered` is used by a custom integration. Please report your issue with the author of that custom integration. Custom integrations are not supported by the Home Assistant project.

Thanks! 👍 

../Frenck
