### ISSUE TITLE
SSH addon update snapshot has no description

### ISSUE THREAD

**Issue by jmartens** [home-assistant/addons#2067]
## The problem

I have updated a bunch off addons after restoring a snapshot after a fresh install. I made snapshots before every update and noticed some do have a description when created, the one created when SSH addon was updated seems not to have one, see screenshot:
![image](https://user-images.githubusercontent.com/593327/121296381-d8352580-c8f0-11eb-9f2c-d3304a216933.png)

## Environment

- Add-on with the issue: SSH add on
- Add-on release with the issue:  8.0.0
- Last working add-on release (if known): N/A
- Operating environment (OS/Supervised): Hass OS under KVM

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```txt

```

**Comment by ludeeus** [comment]
This is not an issue with the add-on.
Can you open this in <https://github.com/home-assistant/frontend/issues/new?assignees=&labels=bug,supervisor&template=bug_report.yml> and filling out that template?
Thanks 👍
