### ISSUE TITLE
Xiaomi sensor not working with decons 6.9.0

### ISSUE THREAD

**Issue by hofvanta** [home-assistant/addons#2068]
## The problem
The sensor are decovered and seen, but mentioned as not reachable after upgrade from 6.8.0 to 6.9.0. Is is the case for all sensors. Resetting the sensor (three short presses) or reconnected didnt solve the problem.
Rolling back was fixing the problem again.

## Environment
Deconz 6.9.0 and HA core 2021.6.3 and Supervisor 2021.05.4.

Last working HA core 2021.6.3 & Supervisor 2021.05.4 with Deconz 6.8.0.

**Comment by frenck** [comment]
Hi there @hofvanta 👋 

Thanks for opening an issue. The upgrade/downgrade in this version is a difference in the upstream deCONZ version that this add-on wraps. Therefore, please report your issue with deCONZ.

If they fix this issue and release a new version, we will update the add-on with it as well (addressing your issue). 

Thanks! 👍 

../Frenck
