### ISSUE TITLE
Homematic Integration - Weather Station HmIP-SWO-B, HmIP-SWO-PL, HmIP-SWO-PR

### ISSUE THREAD

**Issue by rufinus** [home-assistant/addons#2076]
## The problem
Integration only shows the total numbers, while CCU shows also "todays" and "yesterdays" values (which is way more informative)
see 
![Bildschirmfoto zu 2021-06-15 17-14-28](https://user-images.githubusercontent.com/343160/122079096-60d62900-cdfd-11eb-9462-7078d9183531.png)
![Bildschirmfoto zu 2021-06-15 17-14-02](https://user-images.githubusercontent.com/343160/122079101-616ebf80-cdfd-11eb-9e86-24ac75563807.png)

Also as you can see on the raincounter - reseting the counter in the CCU does not reset in the Integration.

## Environment
HASS core-2021.6.3
CCU 3.57.5.20210424
- Add-on with the issue: Homematic
- Add-on release with the issue: (should not matter)

- Operating environment (OS/Supervised): HASS on VM

**Comment by rufinus** [comment]
anti-close comment. does no-one care or is interested?

**Comment by ludeeus** [comment]
The first part of this is a feature request to add more things to the integration. (You should open a feature request on the forum)
The second part, is a bug with the integration which should be opened here <https://github.com/home-assistant/core/issues>

Closing as this is not related to the addon :+1:
