### ISSUE TITLE
Check HA config fails with installation of idna

### ISSUE THREAD

**Issue by pattyland** [home-assistant/addons#2078]
## The problem
I’m trying to use the track configuration add-on but it crashes

## Environment

- Add-on with the issue: Check configuration 
- Add-on release with the issue: 3.7.1
- Last working add-on release (if known): 3.6.0 (?)
- Operating environment (OS/Supervised): OS

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[22:26:48] INFO: Don't worry, this temporary installation is not overwriting your current one.
[22:26:48] INFO: Installing Home Assistant: latest...
[22:26:48] INFO: Please be patient, this might take a few minutes...
[22:27:56] INFO: Installed Home Assistant 2021.6.5
[22:27:56] INFO: Making a copy of your configuration for checking...
[22:27:56] INFO: Checking your configuration against this version...
[22:31:22] ERROR: The configuration check did not pass!
[22:31:22] ERROR: See the output below for more details.
Testing configuration at /tmp/config
Fatal error while loading config: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/site-packages/idna-3.2.dist-info/METADATA'
Failed config
  General Errors: 
    - [Errno 2] No such file or directory: '/usr/local/lib/python3.8/site-packages/idna-3.2.dist-info/METADATA'

Successful config (partial)
[22:31:22] INFO: The full output has been written to /share/check_config.txt
s6-svscanctl: fatal: unable to control /var/run/s6/services: supervisor not listening
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

```

## Additional information
This looks like a strange mix of #1978 and #1773 but as both this bugs are fixed in 3.7.1, especially the  “hypervisor not listening stuff” I opened a new one

**Comment by ludeeus** [comment]
Is this still an issue?

**Comment by ludeeus** [comment]
Is this still an issue with 3.8.0?

**Comment by mcasper73** [comment]
Hi, i just installed version 3.8 and reboot. The problem is still present.

Check Home Assistant configuration

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[16:25:06] INFO: Don't worry, this temporary installation is not overwriting your current one.
[16:25:06] INFO: Installing Home Assistant: latest...
[16:25:06] INFO: Please be patient, this might take a few minutes...
[16:25:40] INFO: Installed Home Assistant 2021.7.0
[16:25:40] INFO: Making a copy of your configuration for checking...
[16:25:43] INFO: Checking your configuration against this version...
[16:27:41] ERROR: The configuration check did not pass!
[16:27:41] ERROR: See the output below for more details.
Testing configuration at /tmp/config
Fatal error while loading config: [Errno 2] No such file or directory: '/usr/local/lib/python3.9/site-packages/idna-3.2.dist-info/METADATA'
Failed config
  General Errors: 
    - [Errno 2] No such file or directory: '/usr/local/lib/python3.9/site-packages/idna-3.2.dist-info/METADATA'

Successful config (partial)
[16:27:41] INFO: The full output has been written to /share/check_config.txt
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

**Comment by ludeeus** [comment]
What integrations do you use?

**Comment by mcasper73** [comment]
I'm using :
Check Home Assistant configuration
Current version: 3.8.0 

With:
Core Version   core-2021.6.6
supervisor-2021.06.8
Home Assistant OS 6.1

Thanks

**Comment by ludeeus** [comment]
Those are not integrations, you can see a list of your integrations here <https://my.home-assistant.io/redirect/info/>

**Comment by derandiunddasbo** [comment]
From #1808 :
> 2021.7.1 contains a fix for `av`. For the remaining `idna` that is tracked in #2078 so I'm closing this one so it's not multiple issues with the same issue. 👍

Yes, I know. When I wrote about errors in my today's replies, I meant the idna error, not the 'av' error from the actual config check.

The first run with v3.7.2 already failed with the idna error before running the config check. 

Only after updating the addon to 3.8.0 and running it against HA 2021.7.0 the config check was actually executed and threw the av error.

Now, with the fixed HA 2021.7.1, the addon is running successfully for me, i.e. neither with the idna error, nor with errors from the config check itself:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[17:58:27] INFO: Don't worry, this temporary installation is not overwriting your current one.
[17:58:27] INFO: Installing Home Assistant: latest...
[17:58:27] INFO: Please be patient, this might take a few minutes...
[17:58:52] INFO: Installed Home Assistant 2021.7.1
[17:58:52] INFO: Making a copy of your configuration for checking...
[17:58:52] INFO: Checking your configuration against this version...
[18:00:54] INFO: Configuration check finished - no error found! :)
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by mcasper73** [comment]
Thank you very much @derandiunddasbo , i wait notification of new version 2021.7.1

**Comment by ludeeus** [comment]
Oh, my bad!
But nice!
Can you try specifying 2021.7.0 as well?

**Comment by derandiunddasbo** [comment]
> Can you try specifying 2021.7.0 as well?

No, unfortunately the logs of the last run with Addon version 3.7.2 against HA 2021.7.0 are gone after updating the addon. I don't know, if HA or the supervisor is storing old addon logs somewhere, but I don't think so. I think they are deleted together with the old docker container when updating an addon.

**Comment by ludeeus** [comment]
You can specify a version on the config tab og the addon

**Comment by pattyland** [comment]
I'm still getting nearly the exact error without the supervisor part in 3.8.0:

```txt
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[14:16:59] INFO: Don't worry, this temporary installation is not overwriting your current one.
[14:16:59] INFO: Installing Home Assistant: latest...
[14:16:59] INFO: Please be patient, this might take a few minutes...
[14:17:58] INFO: Installed Home Assistant 2021.7.1
[14:17:58] INFO: Making a copy of your configuration for checking...
[14:17:59] INFO: Checking your configuration against this version...
[14:18:15] ERROR: The configuration check did not pass!
[14:18:15] ERROR: See the output below for more details.
Testing configuration at /tmp/config
Fatal error while loading config: [Errno 2] No such file or directory: '/usr/local/lib/python3.9/site-packages/idna-3.2.dist-info/METADATA'
Failed config
  General Errors: 
    - [Errno 2] No such file or directory: '/usr/local/lib/python3.9/site-packages/idna-3.2.dist-info/METADATA'

Successful config (partial)
[14:18:15] INFO: The full output has been written to /share/check_config.txt
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by derandiunddasbo** [comment]
Today I tested the latest addon version 3.8.0 against HA 2021.7.0 as suggested by @ludeeus and indeed, the error returned:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[18:11:46] INFO: Don't worry, this temporary installation is not overwriting your current one.
[18:11:46] INFO: Installing Home Assistant: 2021.7.0...
[18:11:46] INFO: Please be patient, this might take a few minutes...
[18:12:09] INFO: Installed Home Assistant 2021.7.0
[18:12:09] INFO: Making a copy of your configuration for checking...
[18:12:09] INFO: Checking your configuration against this version...
[18:13:43] ERROR: The configuration check did not pass!
[18:13:43] ERROR: See the output below for more details.
Testing configuration at /tmp/config
Fatal error while loading config: (idna 3.2 (/usr/local/lib/python3.9/site-packages), Requirement.parse('idna<3,>=2.5'), {'requests'})
Failed config
  General Errors: 
    - (idna 3.2 (/usr/local/lib/python3.9/site-packages), Requirement.parse('idna<3,>=2.5'), {'requests'})

Successful config (partial)
[18:13:43] INFO: The full output has been written to /share/check_config.txt
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

```

... and it even stayed when reverting to "latest", a.k.a. HA 2021.7.1 in the addon config, which seems a bit odd to me, but as said, I still don't understand the nature of this problem:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[19:00:24] INFO: Don't worry, this temporary installation is not overwriting your current one.
[19:00:24] INFO: Installing Home Assistant: latest...
[19:00:24] INFO: Please be patient, this might take a few minutes...
[19:00:57] INFO: Installed Home Assistant 2021.7.1
[19:00:57] INFO: Making a copy of your configuration for checking...
[19:00:57] INFO: Checking your configuration against this version...
[19:02:48] ERROR: The configuration check did not pass!
[19:02:48] ERROR: See the output below for more details.
Testing configuration at /tmp/config
Fatal error while loading config: (idna 3.2 (/usr/local/lib/python3.9/site-packages), Requirement.parse('idna<3,>=2.5'), {'requests'})
Failed config
  General Errors: 
    - (idna 3.2 (/usr/local/lib/python3.9/site-packages), Requirement.parse('idna<3,>=2.5'), {'requests'})

Successful config (partial)
[19:02:48] INFO: The full output has been written to /share/check_config.txt
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

At least, pip installing the current idna version into the container still seems to fix that problem:

```
root@homesweethome:~# docker exec -it addon_core_check_config bash
bash-5.1# pip install idna
Collecting idna
Using cached idna-3.2-py3-none-any.whl (59 kB)
Installing collected packages: idna
Successfully installed idna-3.2
WARNING: You are using pip version 20.2.4; however, version 21.1.3 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
bash-5.1#
```

Now it's working again:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[19:12:36] INFO: Don't worry, this temporary installation is not overwriting your current one.
[19:12:36] INFO: Installing Home Assistant: latest...
[19:12:36] INFO: Please be patient, this might take a few minutes...
[19:12:59] INFO: Installed Home Assistant 2021.7.1
[19:12:59] INFO: Making a copy of your configuration for checking...
[19:12:59] INFO: Checking your configuration against this version...
[19:15:01] INFO: Configuration check finished - no error found! :)
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by ludeeus** [comment]
List all integrations you use if you see this with 3.8.0 and latest/stable/2021.7.1 as the version

**Comment by TheDK** [comment]
Same here:

First run with 3.8.0 againt 2021.7.2:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[09:48:06] INFO: Don't worry, this temporary installation is not overwriting your current one.
[09:48:06] INFO: Installing Home Assistant: latest...
[09:48:06] INFO: Please be patient, this might take a few minutes...
[09:48:52] INFO: Installed Home Assistant 2021.7.2
[09:48:52] INFO: Making a copy of your configuration for checking...
[09:48:52] INFO: Checking your configuration against this version...
[09:51:00] ERROR: The configuration check did not pass!
[09:51:00] ERROR: See the output below for more details.
Testing configuration at /tmp/config
Fatal error while loading config: [Errno 2] No such file or directory: '/usr/local/lib/python3.9/site-packages/idna-3.2.dist-info/METADATA'
Failed config
  General Errors: 
    - [Errno 2] No such file or directory: '/usr/local/lib/python3.9/site-packages/idna-3.2.dist-info/METADATA'

Successful config (partial)
[09:51:00] INFO: The full output has been written to /share/check_config.txt
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```
Second run a couple of minutes later, same setup, no restart - just started the add-on again:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[10:02:22] INFO: Don't worry, this temporary installation is not overwriting your current one.
[10:02:22] INFO: Installing Home Assistant: latest...
[10:02:22] INFO: Please be patient, this might take a few minutes...
[10:03:08] INFO: Installed Home Assistant 2021.7.2
[10:03:08] INFO: Making a copy of your configuration for checking...
[10:03:08] INFO: Checking your configuration against this version...
[10:05:41] INFO: Configuration check finished - no error found! :)
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```
## System Health

version | core-2021.6.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.9
os_name | Linux
os_version | 5.9.16
arch | aarch64
timezone | Europe/Berlin

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 5000
Installed Version | 1.13.2
Stage | running
Available Repositories | 847
Installed Repositories | 12

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 12. August 2021, 02:00
relayer_connected | true
remote_enabled | false
remote_connected | false
alexa_enabled | true
google_enabled | false
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 5.13
-- | --
update_channel | stable
supervisor_version | supervisor-2021.06.8
docker_version | 19.03.15
disk_total | 113.9 GB
disk_used | 8.7 GB
healthy | true
supported | true
board | odroid-n2
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.3.1), Check Home Assistant configuration (3.8.0), FTP (4.2.0), Terminal & SSH (9.1.3), Duck DNS (1.12.5), Log Viewer (0.11.0), Samba share (9.5.1), Node-RED (9.1.3), ESPHome (1.19.4)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 4
views | 14
mode | storage

</details>

Is there a way / Template to copy all integrations listed?

**Comment by ludeeus** [comment]
> Is there a way / Template to copy all integrations listed?

No, not really.
If you know your way around the browser console you can access it with `window.document.querySelector("home-assistant").hass.config.components`

**Comment by pattyland** [comment]
<details><summary>My integrations:</summary>
    <pre>
0: "media_player.apple_tv"
1: "hacs"
2: "binary_sensor.template"
3: "hpprinter"
4: "cover"
5: "device_tracker.bluetooth_tracker"
6: "analytics"
7: "onboarding"
8: "light.hyperion"
9: "lock.volkswagencarnet"
10: "sensor.hpprinter"
11: "trace"
12: "device_tracker"
13: "input_datetime"
14: "device_automation"
15: "telegram_bot"
16: "switch.wemo"
17: "sensor.snmp"
18: "kodi"
19: "recorder"
20: "rest"
21: "blueprint"
22: "auth"
23: "lock"
24: "notify.html5"
25: "homekit"
26: "switch.broadlink"
27: "ssdp"
28: "binary_sensor.esphome"
29: "scene.deconz"
30: "config"
31: "binary_sensor.hpprinter"
32: "fan"
33: "sensor.hassio"
34: "default_config"
35: "hassio"
36: "shelly"
37: "notify.mobile_app"
38: "script"
39: "alarm_control_panel.alexa_media"
40: "alarm_control_panel"
41: "light.alexa_media"
42: "switch.adguard"
43: "binary_sensor.mqtt"
44: "sensor.adguard"
45: "switch.alexa_media"
46: "zeroconf"
47: "sensor.template"
48: "camera.hyperion"
49: "template"
50: "scene"
51: "cloud"
52: "sun"
53: "mobile_app"
54: "sensor.shelly"
55: "notify.llamalab_automate"
56: "counter"
57: "climate"
58: "tplink"
59: "cast"
60: "conversation"
61: "media_player.androidtv"
62: "network"
63: "alarm_control_panel.template"
64: "synology_dsm"
65: "media_source"
66: "binary_sensor.deconz"
67: "calendar"
68: "sensor.synology_dsm"
69: "switch.flux"
70: "binary_sensor.updater"
71: "media_player.kodi"
72: "switch.shelly"
73: "almond"
74: "persistent_notification"
75: "apple_tv"
76: "group"
77: "discovery"
78: "tag"
79: "switch.deconz"
80: "remote.apple_tv"
81: "logbook"
82: "switch.command_line"
83: "switch.tplink"
84: "light.yeelight"
85: "sensor.foldingathomecontrol"
86: "python_script"
87: "binary_sensor.hassio"
88: "vacuum.xiaomi_miio"
89: "binary_sensor.yeelight"
90: "binary_sensor.shelly"
91: "switch.template"
92: "remote.broadlink"
93: "deconz"
94: "sensor.mobile_app"
95: "shell_command"
96: "stream"
97: "sensor.mqtt"
98: "http"
99: "broadlink"
100: "climate.deconz"
101: "binary_sensor.fritz"
102: "light.deconz"
103: "switch.rest"
104: "switch.fritz"
105: "notify.nfandroidtv"
106: "light.mqtt"
107: "volkswagencarnet"
108: "cover.shelly"
109: "weather"
110: "foldingathomecontrol"
111: "image_processing"
112: "alarm_control_panel.deconz"
113: "binary_sensor.ping"
114: "binary_sensor.volkswagencarnet"
115: "media_player.alexa_media"
116: "sensor.fritz"
117: "light"
118: "yeelight"
119: "light.shelly"
120: "notify"
121: "tts.google_translate"
122: "calendar.google"
123: "weather.darksky"
124: "system_log"
125: "input_number"
126: "climate.generic_thermostat"
127: "input_select"
128: "lock.nello"
129: "hyperion"
130: "sensor.miflora"
131: "zone"
132: "switch.synology_dsm"
133: "image_processing.facebox"
134: "webhook"
135: "timer"
136: "sensor.command_line"
137: "remote"
138: "mqtt"
139: "api"
140: "image"
141: "ping"
142: "wemo"
143: "sensor.mitemp_bt"
144: "sensor.esphome"
145: "sensor.systemmonitor"
146: "sensor.time_date"
147: "media_player.cast"
148: "binary_sensor.command_line"
149: "sensor.wled"
150: "select.wled"
151: "lock.deconz"
152: "person"
153: "binary_sensor"
154: "notify.group"
155: "media_player.spotify"
156: "lovelace"
157: "sensor.deconz"
158: "fan.xiaomi_miio_fan"
159: "fastdotcom"
160: "notify.telegram"
161: "spotify"
162: "homeassistant"
163: "fritz"
164: "camera"
165: "emulated_hue"
166: "switch.wled"
167: "notify.alexa_media"
168: "my"
169: "light.wled"
170: "wled"
171: "websocket_api"
172: "switch.mqtt"
173: "binary_sensor.synology_dsm"
174: "switch"
175: "google"
176: "switch.hyperion"
177: "sensor"
178: "scene.homeassistant"
179: "camera.synology_dsm"
180: "plant"
181: "input_boolean"
182: "automation"
183: "influxdb"
184: "sensor.alexa_media"
185: "system_health"
186: "history"
187: "dhcp"
188: "sensor.fastdotcom"
189: "vacuum"
190: "alexa_media"
191: "sensor.broadlink"
192: "device_tracker.mobile_app"
193: "updater"
194: "panel_iframe"
195: "input_text"
196: "select"
197: "tts"
198: "frontend"
199: "map"
200: "sensor.hacs"
201: "xiaomi_miio"
202: "adguard"
203: "esphome"
204: "media_player"
205: "fan.deconz"
206: "cover.deconz"
207: "light.esphome"
208: "device_tracker.fritz"
209: "search"
210: "ffmpeg"
211: "sensor.volkswagencarnet"
212: "binary_sensor.mobile_app"
    </pre>
   </details>

**Comment by nathang21** [comment]
Also happening for me. 

## System Health

version | core-2021.7.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.9.5
os_name | Linux
os_version | 5.9.16
arch | aarch64
timezone | America/Los_Angeles

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.1
-- | --
update_channel | stable
supervisor_version | supervisor-2021.06.8
docker_version | 20.10.6
disk_total | 113.9 GB
disk_used | 6.5 GB
healthy | true
supported | true
board | odroid-n2
supervisor_api | ok
version_api | ok
installed_addons | Home Assistant Google Drive Backup (0.102.0), AirCast (3.0.0), Check Home Assistant configuration (3.6.0), Samba share (9.3.0), WireGuard (0.5.0), Git pull (7.12), File editor (5.2.0), Log Viewer (0.9.1), Terminal & SSH (9.0.2), Portainer (1.4.0), Duck DNS (1.13.0), AirSonos (3.0.0), CEC Scanner (2.4)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 0
mode | auto-gen

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Comment by viktak** [comment]
Same here on 2021.9.3
