### ISSUE TITLE
Mosquitto - "Failed to save add-on configuration, Unknown error, see supervisor logs" since 5.1.1

### ISSUE THREAD

**Issue by NobleKangaroo** [home-assistant/addons#2079]
## The problem

When trying to save Mosquitto configuration, I am presented with an "Failed to save add-on configuration, Unknown error, see supervisor logs" error. Checking Home Assistant logs, I see these two lines:
```txt
2021-06-16 12:00:14 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /addons/core_mosquitto/options/validate request
2021-06-16 12:00:14 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /addons/core_mosquitto/options/validate - 
```
Until this week, I hadn't touched my Mosquitto configuration and everything was working without issue. Upon adding a few new Tasmota devices in my home and thus needing to add new usernames and passwords into Mosquitto, I encountered this error. Apparently after months of not touching my configuration, this issue went unnoticed. Having saved snapshots back to 2020, I was able to isolate the specific update that introduced this problem in my environment. Rolling back to 5.1.1, the issue is present. Rolling back to 5.1.0, the issue is not. Error appears to be present in 5.1.1 but not in 5.1.0 - would suspect one or more changes between these two versions to be the cause. It would seem that there's something happening with the validation code but without any more helpful error message than the one I posted, and without knowing how to get more information/verbose logging, I'm not sure what to check next.

## Environment

- Add-on with the issue: Mosquitto
- Add-on release with the issue: 5.1.1 and up
- Last working add-on release (if known): 5.1.0
- Operating environment (OS/Supervised): Intel NUC, Debian 10.9, Home Assistant Supervised install

## Problem-relevant configuration

```yaml
logins:
  - username: xxx
    password: yyy
anonymous: false
customize:
  active: false
  folder: mosquitto
certfile: fullchain.pem
keyfile: privkey.pem
require_certificate: true
```

## Traceback/Error logs

```txt
2021-06-16 12:00:14 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /addons/core_mosquitto/options/validate request
2021-06-16 12:00:14 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /addons/core_mosquitto/options/validate - 
```

## Additional information
Video showing the difference between 5.1.0 and 5.1.1 with nothing else changing:
https://www.youtube.com/watch?v=OcWZJlDB5_8

**Comment by ludeeus** [comment]
`anonymous` is not a valid option, remove that.

**Comment by NobleKangaroo** [comment]
Appreciate the eagle eye, however the behavior is the same with the anonymous option removed. I had just left it in there as I was going back and forth between addon versions.

On July 8, 2021 6:41:16 AM EDT, "Joakim Sørensen" ***@***.***> wrote:
>`anonymous` is not a valid option, remove that.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/home-assistant/addons/issues/2079#issuecomment-876331767

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ludeeus** [comment]
Meaning you still get timeout?
Can you paste the details from your system health section?

**Comment by NobleKangaroo** [comment]
> Meaning you still get timeout?
Oh yes, that's what I meant. Sorry for not making that clear.

> Can you paste the details from your system health section?

I just updated to 2021.7 today; here's the current output:
```
version: core-2021.7.1
installation_type: Home Assistant Supervised
dev: false
hassio: true
docker: true
virtualenv: false
python_version: 3.9.5
os_name: Linux
os_version: 4.19.0-16-amd64
arch: x86_64
timezone: America/New_York
```

I tried a Docker wipe (removed all containers and images, re-installed Home Assistant, restored from backup). I'm half tempted to completely reinstall Home Assistant from scratch and just import my configuration.yaml and see if that works. It may be something weird with my own instance if others aren't reporting this.

**Comment by ludeeus** [comment]
Can you copy everything from system health? It has an easy way to get the correct format for GitHub with the 3 dots in the top right of that card

**Comment by ovizii** [comment]
Seems to be the problem described here: https://community.home-assistant.io/t/problems-with-samba-share-addon-cannot-change-configuration/462880/3

> This error was caused by the checking logic of the config page - it checks that the password is not in the pwned database. I block lots of outbound traffic - including this!

**Comment by artreaktor** [comment]
I had a similar problem: my password has special chars, so putting it in quotes solved my issue.

**Comment by echuraev** [comment]
Hello! Have the same problem. Here is my configuration:
```
logins:
  - username: mqtt
    password: mqtt
require_certificate: false
certfile: fullchain.pem
keyfile: privkey.pem
customize:
  active: false
  folder: mosquitto

```
HA is installed under Proxmox on x86 server. How I can fix this issue?

**Comment by jekeam** [comment]
Hello! Have the same problem.

**Comment by echuraev** [comment]
I found that this issue occurs when using the Home Assistant add-on. If the Mosquitto Broker is running on an external server, the problem does not appear. As far as I understand, the Home Assistant add-on manages the MQTT connection parameters automatically. Therefore, when using the add-on, you can simply omit the login parameters—Home Assistant will add them and substitute the correct values.

This worked for me: I stopped setting the login parameters manually and let Home Assistant handle them.

**Comment by maxotkin** [comment]
> Я обнаружил, что эта проблема возникает при использовании надстройки Home Assistant. Если Mosquitto Broker работает на внешнем сервере, проблема не возникает. Насколько я понимаю, надстройка Home Assistant автоматически управляет параметрами подключения по протоколу MQTT. Поэтому при использовании надстройки можно просто не указывать параметры входа — Home Assistant добавит их и подставит правильные значения.
> 
> У меня это сработало: я перестал вручную задавать параметры входа и позволил Home Assistant сделать это за меня.
проблема с проверкой паролей (Have I Been Pwned) 

Проверку паролей через сервис Have I Been Pwned (HIBP) в Home Assistant можно отключить через командную строку (CLI). Это часто решает проблему таймаутов при сохранении настроек аддонов, если сервер имеет ограниченный доступ к интернету или сервис HIBP недоступен. 
Как отключить проверку
Для выполнения команд вам понадобится доступ к терминалу (аддон Terminal & SSH или SSH & Web Terminal).
Откройте терминал в интерфейсе Home Assistant.
Введите команду для отключения проверки:

ha security options --pwned=False

мне помогло. пароли сохранились
