### ISSUE TITLE
ESPHome 1.19 log window buttons doesn't work in Firefox

### ISSUE THREAD

**Issue by fribse** [home-assistant/addons#2080]
## The problem

After pressing 'Install' (update) over 'wireless' (OTA) it shows the logwindow in firefox (in chrome it asks for install methods)
At the bottom there are a few buttons, questionmark, EDIT STOP 'three dots'.
After doing the update, and you want to close the window, nothing happens in firefox, it works in chrome

## Environment

- Add-on with the issue: ESPHome
- Add-on release with the issue: 1.19
- Last working add-on release (if known):  1.18
- Operating environment (OS/Supervised): Supervised

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```txt

```

## Additional information
![image](https://user-images.githubusercontent.com/13660621/122304138-0627f480-cf05-11eb-94ed-a88bd684c218.png)

**Comment by ludeeus** [comment]
That add-on is not provided by this repository, please open an issue in the ESPHome issue tracker <https://github.com/esphome/issues> 👍
