### ISSUE TITLE
Mosquitto Addon - client id not accepting '/' 

### ISSUE THREAD

**Issue by PePeLLee** [home-assistant/addons#2082]
## The problem

With latest Mosquitto broker upgrade some of my devices stopped communicating with HA. After some investigation it turned out that with addon '/' in client id is not allowed.  It works fine with standalone mosquitto broker.

## Environment

Mosquitto broker
Current version: 6.0.1

- Add-on with the issue: Mosquitto broker
- Add-on release with the issue: Current version: 6.0.1
- Last working add-on release (if known): 
- Operating environment (OS/Supervised):  ubuntu

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```txt

```

## Additional information
To reproduce I use mosquitto_pub:
WORKING:
mosquitto_pub -h 192.168.7.249 -t "dzialka/bt_bridge/19/a4:c1:38:fb:65:222/tmp" -u XXX -P XXX -m "qeqwe" -i "dzialkaaaaaadasdasdasdasdasdasdasdadsadasdasdadas"
NOT WORKING:
mosquitto_pub -h 192.168.7.249 -t "dzialka/bt_bridge/19/a4:c1:38:fb:65:222/tmp" -u XXX -P XXX -m "qeqwe" -i "dzialkaaaaaadasdasd**/**asdasdasdasdasdadsadasdasdadas"

**Comment by ludeeus** [comment]
standalone broker is also running mosquitto 1.6.12?
What does the add-on log tell you?
