### ISSUE TITLE
core_deconz missing API permission

### ISSUE THREAD

**Issue by baunan** [home-assistant/addons#2092]
## Problem

My Supervisor log has resently being hammerer (once a second) with these messages related to deconz

21-06-27 11:28:39 WARNING (MainThread) [supervisor.api.middleware.security] core_deconz missing API permission for /hardware/trigger
21-06-27 11:28:39 ERROR (MainThread) [supervisor.api.middleware.security] Invalid token for access /hardware/trigger

And I am not sure if it is related, but in the deconz log I also now see this error message repeatedly

[09:47:45] INFO: Starting udevd...
parse error: Expected string key before ':' at line 1, column 4
[11:47:46] ERROR: Unknown HTTP error occured

Not sure when this occured, but I would guess it started sometime this month.

Except for the error messages, the deconz looks to work OK.

## Environment
Running Home Assistant on a VM using Proxmox
Proxmox is running on a NUC i3

core-2021.5.4
OS 4.7
supervisor-2021.06.6

Deconz add-on: 6.3.0

**Comment by ludeeus** [comment]
Update the add-on, the trigger usage was removed in 6.6.5
