### ISSUE TITLE
Mosquitto Broker Socket Error

### ISSUE THREAD

**Issue by gogreenpower** [home-assistant/addons#2097]
## The problem

Unsure what I done but it was working last week, but this week i'm not getting the published messages into HA, they are being sent from my devices as I have subscribed to the topics on other brokers and I am receiving them. 

I have done full reboots, uninstalls and the problem remains.

## Environment

- Add-on with the issue: Mosquitto broker
- Add-on release with the issue: 6.0.1
- Last working add-on release (if known): 
- Operating environment (OS/Supervised): Supervised

## Problem-relevant configuration

```yaml
logins: []
customize:
  active: false
  folder: mosquitto
certfile: fullchain.pem
keyfile: privkey.pem
require_certificate: false
```

## Traceback/Error logs

```txt
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] mosquitto.sh: executing... 
[08:20:15] INFO: Certificates found: SSL is available
[cont-init.d] mosquitto.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[08:20:15] INFO: Starting NGINX for authentication handling...
[08:20:16] INFO: Starting mosquitto MQTT broker...
1624926016: mosquitto version 1.6.12 starting
1624926016: |-- *** auth-plug: startup
[08:20:16] INFO: Successfully send discovery information to Home Assistant.
[08:20:17] INFO: Successfully send service information to the Supervisor.
1624926016: Config loaded from /etc/mosquitto/mosquitto.conf.
1624926016: Loading plugin: /usr/share/mosquitto/auth-plug.so
1624926016:  ├── Username/password checking enabled.
1624926016:  ├── TLS-PSK checking enabled.
1624926016:  └── Extended authentication not enabled.
1624926016: Opening ipv4 listen socket on port 1883.
1624926016: Opening ipv6 listen socket on port 1883.
1624926016: Opening websockets listen socket on port 1884.
1624926016: Opening ipv4 listen socket on port 8883.
1624926016: Opening ipv6 listen socket on port 8883.
1624926016: Opening websockets listen socket on port 8884.
1624926016: Warning: Mosquitto should not be run as root/administrator.
1624926016: mosquitto version 1.6.12 running
1624926016: New connection from 127.0.0.1 on port 1883.
1624926016: Socket error on client <unknown>, disconnecting.
1624926016: New connection from 172.30.32.1 on port 1883.
1624926016: New client connected from 172.30.32.1 as mqttjs_dec8d72b (p2, c1, k60, u'addons').
1624926017: New connection from 192.168.1.4 on port 1883.
1624926017: New client connected from 192.168.1.4 as mqtt-explorer-0cd99e23 (p2, c1, k60).
1624926017: New connection from 172.30.32.1 on port 1883.
1624926017: New client connected from 172.30.32.1 as 64fpGnTXcGnpKwRBx48aPL (p2, c1, k60, u'homeassistant').
1624926018: New connection from 192.168.1.34 on port 1883.
1624926018: New client connected from 192.168.1.34 as auto-9F3815E0-18E0-88AF-6E09-5DCCDF3850A9 (p2, c1, k60).
1624926018: New connection from 192.168.1.23 on port 1883.
{"result": "ok", "data": {}}1624926018: New client connected from 192.168.1.23 as DVES_4A98B7 (p2, c1, k30, u'kane').
1624926019: New connection from 192.168.1.50 on port 1883.
1624926019: New client connected from 192.168.1.50 as DVES_58883C (p2, c1, k30, u'kane').
1624926019: New connection from 192.168.1.55 on port 1883.
1624926019: New client connected from 192.168.1.55 as DVES_3330FD (p2, c1, k30, u'kane').
1624926039: New connection from 192.168.1.22 on port 1883.
1624926039: New client connected from 192.168.1.22 as DVES_4AA443 (p2, c1, k30, u'kane').
1624926061: New connection from 172.30.32.2 on port 1883.
1624926061: Socket error on client <unknown>, disconnecting.
1624926181: New connection from 172.30.32.2 on port 1883.
1624926181: Socket error on client <unknown>, disconnecting.
1624926301: New connection from 172.30.32.2 on port 1883.
1624926301: Socket error on client <unknown>, disconnecting.
1624926421: New connection from 172.30.32.2 on port 1883.
1624926421: Socket error on client <unknown>, disconnecting.
1624926541: New connection from 172.30.32.2 on port 1883.
1624926541: Socket error on client <unknown>, disconnecting.
1624926661: New connection from 172.30.32.2 on port 1883.
1624926661: Socket error on client <unknown>, disconnecting.
1624926781: New connection from 172.30.32.2 on port 1883.
1624926781: Socket error on client <unknown>, disconnecting.
1624926901: New connection from 172.30.32.2 on port 1883.
1624926901: Socket error on client <unknown>, disconnecting.
1624927021: New connection from 172.30.32.2 on port 1883.
1624927021: Socket error on client <unknown>, disconnecting.
1624927141: New connection from 172.30.32.2 on port 1883.
1624927141: Socket error on client <unknown>, disconnecting.
1624927261: New connection from 172.30.32.2 on port 1883.
1624927261: Socket error on client <unknown>, disconnecting.
1624927288: Client mqtt-explorer-0cd99e23 disconnected.
1624927290: New connection from 192.168.1.4 on port 1883.
1624927290: New client connected from 192.168.1.4 as mqtt-explorer-0cd99e23 (p2, c1, k60).
1624927381: New connection from 172.30.32.2 on port 1883.
1624927381: Socket error on client <unknown>, disconnecting.
1624927392: Client mqtt-explorer-0cd99e23 disconnected.
1624927501: New connection from 172.30.32.2 on port 1883.
1624927501: Socket error on client <unknown>, disconnecting.
1624927621: New connection from 172.30.32.2 on port 1883.
1624927621: Socket error on client <unknown>, disconnecting.
1624927741: New connection from 172.30.32.2 on port 1883.
1624927741: Socket error on client <unknown>, disconnecting.
```

## Additional information

HA Log:

Logger: homeassistant.components.mqtt
Source: components/mqtt/__init__.py:913
Integration: MQTT (documentation, issues)
First occurred: 3:53:50 PM (1 occurrences)
Last logged: 3:53:50 PM

Disconnected from MQTT server core-mosquitto:1883 (1)

**Comment by hightempo-nsy** [comment]
I have the same problem. Even if I delete and reinstall the mosquito broker and z2m, the same problem continues to occur. What the hell is that "unknown"?

**Comment by gogreenpower** [comment]
I managed to fix by by adding username and password details to all clients, seems to have fixed it. Strange that with out those details it has been working for over 12 months.

**Comment by Zorgino** [comment]
> I managed to fix by by adding username and password details to all clients, seems to have fixed it. Strange that with out those details it has been working for over 12 months.

all my clients have usernames and passwords. the problem is identical

**Comment by kolucciy** [comment]
same problem after upgrade.

**Comment by gogreenpower** [comment]
Well its still happening, just less often with the username/password set. 

Mosquitto Logs:
`1625538333: mosquitto version 1.6.12 running
1625538333: New connection from 127.0.0.1 on port 1883.
1625538333: Socket error on client <unknown>, disconnecting.
1625538334: New connection from 172.30.32.1 on port 1883.
1625538334: New client connected from 172.30.32.1 as 3tNNHmUfIqwRpaBIVVvLN0 (p2, c1, k60, u'homeassistant').`

HA logs:
`Logger: homeassistant.components.mqtt
Source: components/mqtt/__init__.py:913
Integration: MQTT (documentation, issues)
First occurred: 10:25:26 AM (1 occurrences)
Last logged: 10:25:26 AM

Disconnected from MQTT server core-mosquitto:1883 (1`

Supervisor Logs:
`21-07-06 10:24:39 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'kane'
21-07-06 10:24:40 INFO (MainThread) [supervisor.auth] Successful login for 'kane'
21-07-06 10:25:25 INFO (SyncWorker_4) [supervisor.docker.interface] Stopping addon_core_mosquitto application
21-07-06 10:25:27 INFO (SyncWorker_4) [supervisor.docker.interface] Cleaning addon_core_mosquitto application
21-07-06 10:25:31 INFO (SyncWorker_1) [supervisor.docker.addon] Starting Docker add-on homeassistant/armv7-addon-mosquitto with version 6.0.1
21-07-06 10:25:33 ERROR (MainThread) [supervisor.services.modules.mqtt] There is already a MQTT service in use from core_mosquitto
21-07-06 10:25:37 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'kane'
21-07-06 10:25:38 INFO (MainThread) [supervisor.auth] Successful login for 'kane'`


This error seesm to be the culprit:
`21-07-06 10:25:33 ERROR (MainThread) [supervisor.services.modules.mqtt] There is already a MQTT service in use from core_mosquitto`

**Comment by gogreenpower** [comment]
After search GitHub for similar errors, I found a suggestion to move the broker off HA and run separately on your host machine.  Up and running in 5 minutes and no errors as of yet.

**Comment by gogreenpower** [comment]
Saying that, during my research I discovered Mosquitto V2 made some major changes like by default it requires authentication and doesn’t listen on a network address. To make it behave like the previous version, you need to add to your configuration:

```
listener 1883
allow_anonymous true
```

**Comment by mhzawadi** [comment]
I found that a reconfig of the integration to use the user I setup for MQTT sorted out any issues I had

**Comment by mmoci** [comment]
Non of this works for me. I don't have MQTT for a months and seeing same Socket Error issue. I have configured user and password and I also try add
```
listener 1883
allow_anonymous true
```
Reinstallation was attempted once I noticed this problem, back in spring this year when new version of MQTT Broker was published.

**Comment by mycanaletto** [comment]
Same problem, only solution, restore a 5.1.1

**Comment by Korte68** [comment]
Same problem....switched back to external MQTT server

**Comment by SgtBatten** [comment]
just noticed im getting this also. MQTT was a new install for me for the purpose of using frigate. Just did default config, not really sure what else i can do.

**Comment by Korte68** [comment]
I think the problem was the authentication. Earlier it was optional, but now the clients must use mqtt username and password to connect to the MQTT server.

**Comment by Calimerorulez** [comment]
Same problem here still...

```
1637603465: New connection from 172.30.32.2 on port 1883.
1637603465: Socket error on client <unknown>, disconnecting.
```

**Comment by christianonpele** [comment]
1638688814: New connection from 127.0.0.1 on port 1883.
1638688814: Socket error on client <unknown>, disconnecting.

**Comment by Jaywhy661** [comment]
Same problem for me ![image](https://user-images.githubusercontent.com/95554141/146995434-a2b2693a-75fd-44af-ba92-d4eca58737cc.png)

**Comment by leviatan6** [comment]
Same problem for me...

**Comment by shymchenko** [comment]
And same problem for me!!!

**Comment by Korte68** [comment]
As I know anonymous login  is not accepted anymore. Configure the username and password  in all client.

**Comment by shymchenko** [comment]
"Configure the username and password in all client." 
The password is specified in Zigbee2Mqtt
Please tell me where else I need to specify the username and password? 

```
data_path: /config/zigbee2mqtt
external_converters:
  - data/avatto_me81h.js
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://core-mosquitto
  user: ****
  password: ****
```

**Comment by Korte68** [comment]
if only z2mqtt is used, no other config needed.

shymchenko ***@***.***> ezt írta (időpont: 2022. jan. 12.,
Sze, 9:48):

**Comment by Korte68** [comment]
If you have a problem, You can check the mosquitto broker log, and the
Zigbee2mqtt log.

shymchenko ***@***.***> ezt írta (időpont: 2022. jan. 12.,
Sze, 10:18):

**Comment by shymchenko** [comment]
```
1642016447: mosquitto version 1.6.12 running
1642016447: New connection from 127.0.0.1 on port 1883.
1642016447: Socket error on client <unknown>, disconnecting.
1642016475: New connection from 172.30.32.1 on port 1883.
1642016475: New client connected from 172.30.32.1 as 2cR5R8I1h0ZSu25kITX2cc (p2, c1, k60, u'homeassistant').
1642016589: New connection from 172.30.32.2 on port 1883.
1642016589: Socket error on client <unknown>, disconnecting.
1642016594: New connection from 172.30.33.3 on port 1883.
1642016594: New client connected from 172.30.33.3 as mqttjs_819ac1aa (p2, c1, k60, u'mqtt').
1642016709: New connection from 172.30.32.2 on port 1883.
1642016709: Socket error on client <unknown>, disconnecting.
1642017309: New connection from 172.30.32.2 on port 1883.
1642017309: Socket error on client <unknown>, disconnecting.
1642017420: Client mqttjs_819ac1aa has exceeded timeout, disconnecting.
1642017429: New connection from 172.30.32.2 on port 1883.
1642017429: Socket error on client <unknown>, disconnecting.
1642017462: New connection from 172.30.33.3 on port 1883.
1642017462: New client connected from 172.30.33.3 as mqttjs_819ac1aa (p2, c1, k60, u'mqtt').
1642017549: New connection from 172.30.32.2 on port 1883.
1642017549: Socket error on client <unknown>, disconnecting.
1642017669: New connection from 172.30.32.2 on port 1883.
```
Looks like  172.30.32.1 is Homeassistant core client and  172.30.33.3 is Zigbee2Mqtt client.
But I have no idea what is a 172.30.33.2!!!
How can I know what is a client of 172.30.33.2?

**Comment by shymchenko** [comment]
The flow of connection requests does not come from Zigbee2Mqtt!!!
I stopped Zigbee2Mqtt but attempts to connect anonymously from the address 172.30.32.2 did not stop!
Any ideas about how to find out who is try to connect to Mosquito?

**Comment by Korte68** [comment]
> The flow of connection requests does not come from Zigbee2Mqtt!!!
> I stopped Zigbee2Mqtt but attempts to connect anonymously from the address 172.30.32.2 did not stop!
> Any ideas about how to find out who is try to connect to Mosquito?

That is the supervisor checking if the add-on is still responding as part of a health check. This is expected, not a bug and actually good.

**Comment by mdegat01** [comment]
Yea its coming from supervisor if you have "watchdog" enabled. You can tell by the timestamps. When you enable watchdog it checks if the addon is still alive every 120 seconds and those connections are all 120 seconds apart. This addon in particular also tells supervisor to check if its alive by hitting port `1883` which is exactly what's happening.

I agree with @Korte68 that the feature is good but the log spam is an issue. It's not malicious or harmful traffic so you don't have to worry about that. And if the log spam really bothers you in the meantime then you can disable watchdog on the addon to make it go away.

**Comment by shymchenko** [comment]
Thank you!

**Comment by dima-zhemkov** [comment]
Still not resolved

**Comment by mycanaletto** [comment]
+1

**Comment by Paxy** [comment]
Ok, as there is no official help for anonymous use, here is a hack solution:

- First gain SSH access to HAOS (SSH port 22222)
- Stop Mosquitto broker
- Connect over SSH to HAOS shell
- Find all instances of mosquitto.gtpl file
`find / -name mosquitto.gtpl`
- Edit all files by removing auth configs lines
- Start Mosquitto broker

**Comment by SharkyRawr** [comment]
I made my own Mosquitto addon for hassio that allows anonymous logins (`allow_anonymous true`) and completely removed authentication. Just add https://github.com/SharkyRawr/hass-mqtt-fix to your addon store repositories, click check for updates and install `Mosquitto broker (fix)`.

Since anyone can connect and publish any topic, it's not recommended to run this on public networks -- but this works for me.

**Comment by emersonsc** [comment]
Any chance of this getting fixed...?

**Comment by andersongulao** [comment]
> I made my own Mosquitto addon for hassio that allows anonymous logins (`allow_anonymous true`) and completely removed authentication. Just add https://github.com/SharkyRawr/hass-mqtt-fix to your addon store repositories, click check for updates and install `Mosquitto broker (fix)`.
> 
> Since anyone can connect and publish any topic, it's not recommended to run this on public networks -- but this works for me.

thank you, this worked for me.

**Comment by b3nj1** [comment]
> I made my own Mosquitto addon for hassio that allows anonymous logins (`allow_anonymous true`)


You should be able to do this with the existing addon. It seems some platforms have anonymous default to true and others default to false. HA addon doesn’t specify nor give the option to set this directly , so you end up with folks who want the opposite behavior to what their platform defaults to. 

The following post says how to set allow_anonymous to false using customized settings (what I wanted), but  it should work for you all if you follow the steps and change the setting to allow_anonymous true. 

https://github.com/home-assistant/addons/issues/2091#issuecomment-1011809944

**Comment by jamesanf** [comment]
I followed the steps listed there:

> In the add-on, add/edit "active: true".
> 
> customize:
>   active: true
>   folder: mosquitto
> Create a file called /share/mosquitto/auth.conf, which has:
> 
> allow_anonymous false

But sadly I still get:

```
1650885206: New connection from 127.0.0.1 on port 1883.
1650885206: Socket error on client <unknown>, disconnecting.
```

I'm running out of ideas now, is there anything else I can try? For me, there's just one device not playing ball and everything else is just fine.  Plus, the device was communicating fine with the server without fail for 6 months until just two days ago. Any and all help would be appreciated.

**Comment by Korte68** [comment]
I think it is normal behavior. It is a kind of watchdog, just checking the
MQTT server is answering.

jamesanf ***@***.***> ezt írta (időpont: 2022. ápr. 25., H,
13:19):

**Comment by b3nj1** [comment]
@jamesanf ,  Your comment has:
> > allow_anonymous false

But, I believe your situation requires it to be set to `true`.

- Benjamin

**Comment by jamesanf** [comment]
Thanks Benjamin, but I actually tried it both ways, none of which seem to make much difference. I've also included the error on the ESP:
```
22:13:35 | [W] | [mqtt:264] | MQTT Disconnected: TCP disconnected.
22:13:35 | [I] | [mqtt:176] |  Connecting to MQTT...
```
I'm perplexed by this one. Mostly that in my experience, things don't tend to stop working for no reason whatsoever, when they've been working fine for months. That suggests to me that something has changed, but I really can't think what. I have updated everything on HA, but only after this problem appeared.

Interestingly, I can still access the webserver on the ESP just fine. So it can't be a network issue surely.

Once again any and all help would be gladly appreciated.

**Comment by Korte68** [comment]
Hi, deep sleep component not used in ESP?

jamesanf ***@***.***> ezt írta (időpont: 2022. ápr. 25., H,
23:17):

**Comment by dima-zhemkov** [comment]
Still reproduce if watchdog is enabled

**Comment by mdegat01** [comment]
So I have an idea for a fix but it will take me a bit to put it together. The problem is that watchdog right now really has no way to check if this addon is functioning without tripping this log. Since it doesn't understand mqtt or mosquitto it just knows how to ping URLs and check if ports are open. I'm going to look into getting it to understand [docker healthchecks](https://docs.docker.com/engine/reference/builder/#healthcheck) to give more flexibility around what can be used as a healthcheck.

In the meantime what you can do is turn off watchdog in the addon and instead use HA to monitor the addon and restart if necessary. Here's a package for doing something like this:
```yaml
mqtt:
  sensor:
    # MQTT broker version. More importantly, unavailable if broker is offline
    - name: MQTT Broker version
      unique_id: 552a7f812f2a49ac8b802ba29d118c99_mqtt_broker_version
      icon: mdi:router-wireless
      availability_topic: "$SYS/broker/version"
      availability_template: "{{ 'online' if value is search('^mosquitto version ') else 'offline' }}"
      state_topic: "$SYS/broker/version"
      value_template: "{{ value | replace('mosquitto version ', '') }}"
      entity_category: diagnostic
automation:
- id: 1add8cff167543daaa7cc89108a98f15_automation_broker_offline
  alias: Watchdog for mosquitto
  trigger:
    - platform: template
      value_template: >-
        {{ now().minute is even and is_state('sensor.mqtt_broker_version', 'unavailable') and
          states.sensor.mqtt_broker_version.last_changed < now() - timedelta(minutes=1) }}
  action:
    alias: Restart addon
    service: hassio.addon_restart
    data:
      addon: core_mosquitto
```
Can also add an extra action to send yourself a notification when this occurs if you want.

**Comment by robertjan** [comment]
also here i have the same issues

**Comment by Korte68** [comment]
Try to play on the mqtt server with the valoe of:

max_keepalive *value*

For MQTT v5 clients, it is possible to have the server send a "server
keepalive" value that will override the keepalive value set by the client.
This is intended to be used as a mechanism to say that the server will
disconnect the client earlier than it anticipated, and that the client
should use the new keepalive value. The max_keepalive option allows you to
specify that clients may only connect with keepalive less than or equal to
this value, otherwise they will be sent a server keepalive telling them to
use max_keepalive. This only applies to MQTT v5 clients. The maximum value
allowable, and default value, is 65535.

Set to 0 to allow clients to set keepalive = 0, which means no keepalive
checks are made and the client will never be disconnected by the broker if
no messages are received. You should be very sure this is the behaviour
that you want.

For MQTT v3.1.1 and v3.1 clients, there is no mechanism to tell the client
what keepalive value they should use. If an MQTT v3.1.1 or v3.1 client
specifies a keepalive time greater than max_keepalive they will be sent a
CONNACK message with the "identifier rejected" reason code, and
disconnected.

This option applies globally.




Kertvéllesy László ***@***.***> ezt írta (időpont: 2022. ápr. 25.,
H, 23:29):

**Comment by black-jmyntrn** [comment]
still happening for me

**Comment by VASTechAD** [comment]
happening for me aswell MB ver 6.1.3

**Comment by macminoz** [comment]
facing the same issue here with ncarlier/mqtt on Synology NAS (builtin docker)...tried both password and passless nothing changed

**Comment by mat100** [comment]
Same issue on 6.1.3

**Comment by mortenx** [comment]
> I made my own Mosquitto addon for hassio that allows anonymous logins (`allow_anonymous true`) and completely removed authentication. Just add https://github.com/SharkyRawr/hass-mqtt-fix to your addon store repositories, click check for updates and install `Mosquitto broker (fix)`.
> 
> Since anyone can connect and publish any topic, it's not recommended to run this on public networks -- but this works for me.

It Works :)

**Comment by mremedi2023** [comment]
Same problem here

**Comment by LeandroLimaPRO** [comment]
Same problem here
