### ISSUE TITLE
ZWave JS does not auto-update

### ISSUE THREAD

**Issue by deftdawg** [home-assistant/addons#2101]
## The problem

On my Raspberry Pi 4, ZWave JS never auto-updates despite the "auto-update" option being turned on, I'm not sure if this effects other plug-ins ZWave JS seems to release very often compared to the others, so it's the one I notice as never being up-to-date.

## System Health

version | core-2021.6.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.9
os_name | Linux
os_version | 5.10.17-v8
arch | aarch64
timezone | America/Toronto

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4956
Installed Version | 1.13.2
Stage | running
Available Repositories | 851
Installed Repositories | 4

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.1
-- | --
update_channel | stable
supervisor_version | supervisor-2021.06.6
docker_version | 20.10.6
disk_total | 28.3 GB
disk_used | 12.6 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Duck DNS (1.12.5), Check Home Assistant configuration (3.7.1), Visual Studio Code (3.5.0), Terminal & SSH (9.1.3), ESPHome (1.19.4), Mosquitto broker (6.0.1), Portainer (1.5.1), Snapdrop (0.1-alpha), Z-Wave JS (0.1.27)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 0
views | 10
mode | storage

</details>

- Add-on with the issue: ZWave-js
- Add-on release with the issue:  All of them
- Last working add-on release (if known):  none
- Operating environment (OS/Supervised):  HASS OS 6.1

**Comment by ludeeus** [comment]
Add-ons do not handle this, this is something the Supervisor does.
The current version of this add-on is 0.1.28.

Auto-update of add-ons run every 16 hours, if that is not working for you , please open an issue here <https://github.com/home-assistant/supervisor/issues/new?assignees=&labels=bug&template=bug_report.yml>

**Comment by deftdawg** [comment]
Will do, thanks.
