### ISSUE TITLE
No module named 'av'

### ISSUE THREAD

**Issue by cvwillegen** [home-assistant/addons#2105]
### The problem

I want to update to 2021.7.0, but checking my config fails.

```
[23:02:29] ERROR: See the output below for more details.
Testing configuration at /tmp/config
Failed config
  General Errors: 
    - Component error: camera - No module named 'av'

Successful config (partial)
[23:02:29] INFO: The full output has been written to /share/check_config.txt
```

### What is version of Home Assistant Core has the issue?

core-2021.7.0

### What was the last working version of Home Assistant Core?

core-2021.6.6

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Camera

**Comment by ludeeus** [comment]
Fixed in https://github.com/home-assistant/core/pull/52682
