### ISSUE TITLE
File Editor formatting issues caused by a binary sensor (state attributes)

### ISSUE THREAD

**Issue by jirimissbach** [home-assistant/addons#2114]
## The problem
FileEditor display gets broken by a HACS plugin. I have installed https://github.com/slesinger/HomeAssistant-PREdistribuce and added a basic configuration as follows:

binary_sensor:
  - platform: predistribuce
    receiver_command_id: 262
    periods:
    - name: hdoprepinac
      minutes: 10

This is scaping of the local electricity provider website, somehow the received result breaks the File Editor (tested in Chrome and Brave browser). Commenting out/disabling the plugin, removes the issue

A sample of the problem is shown on the attached picture, the oddly displayed text is actually state attribute of the newly created sensor "binary_sensor.hdo_aktualne"

## Environment

- Add-on with the issue: FileEditor
- Add-on release with the issue:  5.3.2
- Last working add-on release (if known): the problem was also in previous few releases
- Operating environment (OS/Supervised): supervised core-2021.7.1, supervisor-2021.06.8

## Problem-relevant configuration

 https://github.com/slesinger/HomeAssistant-PREdistribuce and added a basic configuration as follows:

binary_sensor:
  - platform: predistribuce
    receiver_command_id: 262
    periods:
    - name: hdoprepinac
      minutes: 10
```

## Traceback/Error logs
<!--
  If you come across any trace or error logs, please provide them.
-->

```txt

```

## Additional information
![image](https://user-images.githubusercontent.com/50277417/125137671-747b6380-e10d-11eb-9072-94e579d3376c.png)

I do understand that the plugin may be the cause of the issue but assuming FileEditor should not be broken by a content of a sensor. I can attach the particular full state attributes as well

**Comment by ludeeus** [comment]
Please report that to the maintainer of the software inside the add-on <https://github.com/danielperna84/hass-configurator>. Thanks :+1:

**Comment by jirimissbach** [comment]
thank you, raised as https://github.com/danielperna84/hass-configurator/issues/217#issue-1006338056
