### ISSUE TITLE
Nginx: Doesn't work with non-default HA port

### ISSUE THREAD

**Issue by jbraceg** [home-assistant/addons#2125]
## The problem

I run Home Assistant on a non-default port. The Nginx addon returns 502 Bad Gateway to every request. Looking at nginx_proxy/data/nginx.conf it appears the port is hardcoded as 8123. Please could we make it configurable? Bonus if it automatically picks up from the outer HA configuration.

## Environment

- Add-on with the issue: Nginx
- Add-on release with the issue: 3.0.2
- Last working add-on release (if known): 
- Operating environment (OS/Supervised): HAOS

## Problem-relevant configuration

```yaml
http:
  server_port: 7594
```

## Traceback/Error logs

```txt

```

**Comment by SilentT19** [comment]
If you can test ?
https://github.com/SilentT19/addons/tree/fix-2125
https://github.com/SilentT19/addons/commit/4d3d20a471401564417eeb2e3a2b5653458f5ac8

**Comment by ludeeus** [comment]
This is documented under "How to use" (2)
For feature requests please raise those on the forums. THanks :+1:
