### ISSUE TITLE
Terminal font unreadable from firefox

### ISSUE THREAD

**Issue by whit2333** [home-assistant/addons#2141]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The font in the terminal is unreadable in firefox. See the image below. It can be solved by making the web browser's window font bigger (ctrl +). This does not occur in chromium browser.

### Describe the behavior you expected

Able to read the font.
![Screenshot_2021-08-08_23-13-07](https://user-images.githubusercontent.com/2065918/128659778-129faec1-da03-4736-a54b-4e15ea6a2d32.png)

### Steps to reproduce the issue

1.Use firefox on ubuntu
2.Look at Terminal via shell integration

### What version of Home Assistant Core has the issue?

core-2021.8.3

### In which browser are you experiencing the issue with?

firefox 90.0.2 (64-bit)

### Which operating system are you using to run this browser?

Ubuntu 18.04

### Additional information

![Screenshot_2021-08-08_23-13-07](https://user-images.githubusercontent.com/2065918/128659778-129faec1-da03-4736-a54b-4e15ea6a2d32.png)

**Comment by Sudo-Rob** [comment]
Should the label be `add-on: Terminal`?

**Comment by ludeeus** [comment]
no

**Comment by Sudo-Rob** [comment]
Sorry.  Fair enough.

**Comment by eddriesen** [comment]
> Identical to #1983
> 
> It's the Duck Duck Go Privacy Essentials. Disable it for your local URL.

Thanks!

**Comment by matthiashh** [comment]
Not exactly the same problem, but my search ended up here.
If the terminal for either or both ssh and vscode looks like this in Firefox:

![Screenshot_20220123_160032](https://user-images.githubusercontent.com/5744579/150684734-da788633-504d-4bd0-866f-37ac4fd057d6.png)

It helped for me to go to `about:config` and turn off
```
privacy.resistFingerprinting
```

**Comment by paulomar** [comment]
> Not exactly the same problem, but my search ended up here. If the terminal for either or both ssh and vscode looks like this in Firefox:
> 
> ![Screenshot_20220123_160032](https://user-images.githubusercontent.com/5744579/150684734-da788633-504d-4bd0-866f-37ac4fd057d6.png)
> 
> It helped for me to go to `about:config` and turn off
> 
> ```
> privacy.resistFingerprinting
> ```

What it means 'go to about: config'??? Where is this?

**Comment by Sudo-Rob** [comment]
Populate the URL; it'll take you to a configuration page.  Then search for `privacy.resistFingerprinting` and make sure it's `false`.

![image](https://user-images.githubusercontent.com/56487711/194767510-9b514ed5-6e30-4a47-a352-aa38d7b7ceae.png)
