### ISSUE TITLE
Browser File Editor depends on 3rd party scripts hosted on the internet.

### ISSUE THREAD

**Issue by fake-name** [home-assistant/addons#2142]
## The problem

The browser-based file editor plugin does not work without loading external scripts from cloudflare.

## Environment

- Add-on with the issue:

File editor

- Add-on release with the issue: 

Current version: 5.3.3 (Changelog)
(latest, as far as I can tell)

- Last working add-on release (if known): 

Unknown

- Operating environment (OS/Supervised): 

Not relevant

## Problem-relevant configuration

Not applicable.

## Traceback/Error logs

![image](https://user-images.githubusercontent.com/1401239/128688596-327cd5b8-c003-49a3-b25a-5fb81b511ba4.png)

```text
GET https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.8/ace.js net::ERR_BLOCKED_BY_CLIENT
hasstaint.fake-url.com/:12 
GET https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.8/ext-modelist.js net::ERR_BLOCKED_BY_CLIENT
hasstaint.fake-url.com/:13 
GET https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.8/ext-language_tools.js net::ERR_BLOCKED_BY_CLIENT
```

## Additional information

I use home assistant because it *doesn't* require cloud functionality.

If a plugin does not have the explicit purpose of interoperating with an externally hosted service, it should work in the complete absence of internet availability.

In this case, the failure is due to the fact that my browser blocks 3rd party scripts by default, but this shouldn't have occurred in the first place.

**Comment by frenck** [comment]
Yup, @ChlorideCull is right, please report this issue/request upstream, thanks! 👍

**Comment by fake-name** [comment]
Whoops, sorry, I just saw it was a "first party" plugin. Derp.
