### ISSUE TITLE
Deconz Addons Sending Duplicate Events with IKEA Sound Control

### ISSUE THREAD

**Issue by haglen** [home-assistant/addons#2146]
## The problem

IKEA Sound Controls were working for some time, then several months ago duplicate events started occurring. For example, single clicking the sound control sends the same event "1002" within milli-seconds of each other. I know I'm not pressing the button twice quickly because a double click event "1004" is being sent for this control, and also is sending duplicate events. See attached screenshots showing duplicate events from the event listener in HA.
![2021-08-15 17_34_19-Developer Tools - Home Assistant](https://user-images.githubusercontent.com/71560093/129471166-5d0837dc-f949-4006-a70c-f52490d095b6.png)
![2021-08-15 17_36_06-Developer Tools - Home Assistant](https://user-images.githubusercontent.com/71560093/129471170-5637d37f-9084-448b-8e2b-e0263d188868.png)

## Environment

- Add-on with the issue: Deconz
- Add-on release with the issue: 6.9.0
- Last working add-on release (if known): 
- Operating environment (OS/Supervised):  Supervised

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```txt

```

**Comment by ludeeus** [comment]
This is out of control for the add-on.
