### ISSUE TITLE
Deconz sending random events with Samsung SmartThings Button IM6001-BTP18

### ISSUE THREAD

**Issue by haglen** [home-assistant/addons#2147]
## The problem

I've been using Samsung SmartThings buttons with Deconz for some time and a few months ago the buttons started sending random press events without the button being pressed. For example, I had a button in my bedroom to turn on the bedside light, and found the light turning on overnight while I was sleeping. I replaced the button with another brand of Zigbee button and the problem went away. I tried resetting the button and replacing the battery and had the same problem afterwards.

## Environment

- Add-on with the issue: Deconz
- Add-on release with the issue: 6.9.0
- Last working add-on release (if known): 
- Operating environment (OS/Supervised): Supervised

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```txt

```

**Comment by ludeeus** [comment]
This is out of control for the add-on.
