### ISSUE TITLE
deCONZ updating firmware inconsistencies

### ISSUE THREAD

**Issue by drthanwho** [home-assistant/addons#2151]
## The problem

How can people that use the addon version of deCONZ update the Conbee's/Raspee's firmware? According to the addon's documentation you get a button inside Phoscon telling you to update. However, for months all I see is the following:

![image](https://user-images.githubusercontent.com/22405505/130234708-c75994c2-5e25-4b82-b2f2-1b03a433d253.png)

Based on their firmware changelog 0x26660700 is from 2020-11-18

Then according to Dresden `The firmware update button doesn't work properly in the HA addon or docker installations. Nor does it work fine in Virtual machines. On this page you can find out how to update. Please use a native installation to update.` 

Alternative's would be as suggested [here ](https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Update-deCONZ-manually) where also mention not possible for the HA addon.

If only way to update is through spinning up a [different ](https://github.com/marthoc/docker-deconz#updating-conbeeraspbee-firmware )container or the other methods listed from Dresden and 
`Go to "Settings -> Gateway" and click the upgrade button` is not longer possible (not even showing up anymore) then maybe we should update this on the addon's README.

## Environment

- Add-on with the issue: deCONZ
- Add-on release with the issue: uncertain since which release this started happening (pretty sure the button was there in the past)
- Last working add-on release (if known): 
- Operating environment (OS/Supervised): OS

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```txt

```

**Comment by wiiNinja** [comment]
I'm with you. I've been upgrading by unplugging from my Raspberry Pi, plug it in my Windows machine and upgrade the firmware from there. Would be nice to be able to just upgrade from Home Assistant.

**Comment by timk75** [comment]
It seems the most recent firmware is just not included in the addon:

```
12:28:40:954 GW update firmware found: /usr/share/deCONZ/firmware/deCONZ_ConBeeII_0x26660700.bin.GCF
12:28:40:955 GW firmware version: 0x26720700
12:28:40:955 GW firmware version is up to date: 0x26720700
```

**Comment by Luke15153** [comment]
You have to update the firmware as described here: https://github.com/marthoc/docker-deconz#updating-conbeeraspbee-firmware

When I tried to update some minutes ago, the marthoc docker image does not contain the new firmware. So I performed these steps:

1. get ssh access to ha using the addon or the developer ssh access

2. Run bash in marthoc container

`docker run -it --rm --entrypoint /bin/bash --privileged --cap-add=ALL -v /dev:/dev -v /lib/modules:/lib/modules -v /sys:/sys marthoc/deconz`

This command will download the latest version of the image.

3. Download firmware

```
cd /usr/share/deCONZ/firmware 
curl https://deconz.dresden-elektronik.de/deconz-firmware/deCONZ_XXX.bin.GCF --output deCONZ_XXX.bin.GCF
```
Choose the matching firmware for your device. 

4. Stop deconz addon

5. Update Firmware

```
cd /
./firmware-update.sh
```

6. Remove marthoc image (optional)

`docker rmi marthoc/deconz`

7. Start deconz addon

in the addon's log you will see the new version. In my case

```
15:52:14:837 GW firmware version: 0x26400500
15:52:14:838 GW firmware version is up to date: 0x26400500
```

**Comment by drthanwho** [comment]
> You have to update the firmware as described here: https://github.com/marthoc/docker-deconz#updating-conbeeraspbee-firmware

That is however not the HA addon and would require you to manually run a docker image within HA


> When I tried to update some minutes ago, the marthoc docker image does not contain the new firmware. So I performed these steps:

If you are using his image the firmware-update.sh script tell you if you don't want to use local firmwares to provide it with a url link to download the required firmware for you (saves you a few steps).

You can also do this by getting in the normal HA addon container and wget to download the firmware. Then deconz includes `GCFFlasher_internal` which you can use to update the firmware.

e.g. `GCFFlasher_internal -d /dev/ttyACM1 -x 3 -f deCONZ_ConBeeII_0x266b0700.bin.GCF`

There are solutions yes. There just should be a solution or at least a documented fail proof way for the addon.

**Comment by spudje** [comment]
I'll wait and hope the newest firmware will be included in a future version of the addon :)

**Comment by malgoe** [comment]
Same problem here - still on 26390500 for my Conbee 1.

**Comment by cokeman0** [comment]
Yes, a idiot's guide to upgrading conbee firmware, would be nice.
step by step, for the really stupid. If I can do it, then everyone can :-)
