### ISSUE TITLE
internal documentation for NGINX Home Assistant SSL proxy add-on is unclear or incorrect?

### ISSUE THREAD

**Issue by phreich9** [home-assistant/addons#2152]
## The problem

In the documentation section of the NGINX Home Assistant SSL proxy add-on, there are a number of issues that need to be addressed:
The documentation currently states:
"1. And you need to add the trusted_proxies section (requests from reverse proxies will be blocked if these options are not set)."
Fallowing this statement is a text box of yaml code to put in the configuration.yaml file (the quotation marks I added):
"http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24".  
1. That code text box contains a specific IP address range (172.30.33.0/24), but does not state WHAT that IP address range is for, or WHETHER it is just an example.  If it is intended to be an example -- it should clearly specify what it is an example of.  Is the intention that the IP address range should be considered a pattern that should be replaced with some other value?  If it is to be considered as a pattern, it should be shown as such, for instance "xxx.xxx.xxx.0/24".  If it meant to be the ip address range of the internal network, then it should be clearly stated that is what is needed there, and possibly some examples shown as is done in other add-on's documentation.  Those examples, however, should be included as COMMENTS, not actual yaml lines, so that they don't accidentally get copied by an unaware user. 
Note, further research into this range IP addresses determined that this is actually a small subset of the largest of the 3 reserved blocks of "private" IP addresses reserved to be used inside internal networks.  However, it is NOT one of the commonly used ranges used inside most home networks.  Most home networks use the default private IP addresses specified in the home routers provided by their ISP, typically in the 192.168.0..0/24 or 192.168.1.0/24 ranges  Less often used is the 10.0.0.0/24 range.  However, the private block of addresses spanning from 172.16.0.0 to 172.31.255.255 are seldom encountered in the home networking environment.  These private addresses are most often used by large corporations for their massive internal networks, usually split into multiple sub-domains.  Since this is the case, I recommend that this should either be changed to a more commonly used private network range, or the reason for using the less common range should be documented.
2.  In this YAML code block there is no explanation of what the line "use_x_forwarded_for:true" does, and why it is needed.  This should be documented.
3.  It seems the intent is to show that this yaml code block should be appended to the existing http: yaml section, instead of including a section header of "http::", it should clearly state that the user should "locate the existing http: section, and then add the following lines to the end of that section:"  Again, new users would likely just copy the entire text from the text box and add it to the configuration.yaml file, likely causing issues because 2 different html: sections would then exist. 
4.   The parenthetical phrase "(requests from reverse proxies will be blocked if these options are not set) is unclear.  NGINX is a reverse proxy.  Is this phrase indicating that requests from OTHER reverse proxies will fail?  Why is that a consideration, in the context of this add-on?  How does the IP address range that is shown solve this issue?  Further, the word "options" is plural here -- if there is more than one option being described, it is not clearly shown as such.  If multiple options are being specified EACH should be clearly documented.
5. Can more than one IP address range be specified in the "trusted_proxies:" section?  Are only IP address ranges allowed, or can individual IP addresses be specified?  If the intention is that this section can contain multiple addresses, then the example should be shown this way.  If the intention is that a mixture of IP ranges and full IP addresses can be added, then the example should be shown this way.  Again, if this is intended to be an EXAMPLE, then it should be included as a comment, not actual YAML code.
6. If the unusual private address range is being used as a "place-holder" to make this section of the configuration.yaml file function in the NGINX  add-on, consideration should probably be given to modifing the add-on to not require a "place-holder", and to recognize that the lack of a specified IP range is valid.  Should a user accidentally use internal private IP addresses in this range, it could cause a lot of headaches for the typical homeassistant user.
7. The NGINX documentation section currently shown in GITHUB does not match what is currently being shown in the actual add-on's internal documentation.  They should match once these deficiencies have been corrected.

## Environment

- Add-on with the issue: NGINX
- Add-on release with the issue: Current version: 3.0.2
- Last working add-on release (if known): n/a
- Operating environment (OS/Supervised): OS

## Problem-relevant configuration
 N/A

```yaml

```

## Traceback/Error logs
 N/A

```txt

```

## Additional information
See above.

**Comment by SilentT19** [comment]
172.30.33.0/24 is the subnet of docker addons
