### ISSUE TITLE
HA Mosquitto doesn't seem to support tls-psk

### ISSUE THREAD

**Issue by csiki2** [home-assistant/addons#2153]
I tried to use psk_hint and psk_file in Mosquitto broker's configuration file at the Supervisor menu, but it doesn't seem to work.

1629499763: Config loaded from /etc/mosquitto/mosquitto.conf.
1629499763: Loading plugin: /usr/share/mosquitto/auth-plug.so
1629499763:  ├── Username/password checking enabled.
1629499763:  ├── TLS-PSK checking enabled.
1629499763:  └── Extended authentication not enabled.
1629499763: Opening ipv4 listen socket on port 1883.
1629499763: Opening ipv6 listen socket on port 1883.
1629499763: Opening websockets listen socket on port 1884.

As far as I can understand from the above the 8883 ports are not opened.
I don't understand what "TLS-PSK checking enabled" exactly means (it is in the log regardless of any psk_hint line in the configuration file).

## Environment

- Add-on with the issue:
Mosquitto broker version: 6.0.1
- Add-on release with the issue: 
- Last working add-on release (if known): 
- Operating environment (OS/Supervised): 
core-2021.8.6
supervisor-2021.06.8
Ubuntu 20.04.2 LTS

## Problem-relevant configuration

```yaml
logins: []
customize:
  active: false
  folder: mosquitto
certfile: fullchain.pem
keyfile: privkey.pem
require_certificate: false
anonymous: false
psk_hint: mqtt
psk_file: psk_file.txt
```

## Traceback/Error logs

```txt
1629499972: Config loaded from /etc/mosquitto/mosquitto.conf.
1629499972: Loading plugin: /usr/share/mosquitto/auth-plug.so
1629499972:  ├── Username/password checking enabled.
1629499972:  ├── TLS-PSK checking enabled.
1629499972:  └── Extended authentication not enabled.
1629499972: Opening ipv4 listen socket on port 1883.
1629499972: Opening ipv6 listen socket on port 1883.
1629499972: Opening websockets listen socket on port 1884.
```

## Additional information
It would be nice to have a simple secure solution for MQTT without the cert setup issues/difficulties.

**Comment by ludeeus** [comment]
It does not work, because it's not valid options.
If you need more control, you need to use the customize option.
