### ISSUE TITLE
DeConz Addon v6.10.0 won't start

### ISSUE THREAD

**Issue by wiiNinja** [home-assistant/addons#2155]
## The problem

I updated the DeConz addon from 6.9.0 to the latest 6.10.0 and the addon terminates upon starting up with these suspicious messages in the log: 
curl: (7) Failed to connect to 127.0.0.1 port 40850: Connection refused
[22:38:25] FATAL: Can't get data from deCONZ gateway

## Environment

- Add-on with the issue: DeConz
- Add-on release with the issue: 6.10.0
- Last working add-on release (if known):  6.9.0
- Operating environment (OS/Supervised): Supervised

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```txt
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] novnc.sh: executing... 
[cont-init.d] novnc.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[22:38:10] INFO: Websockify waiting for VNC to start
[22:38:10] INFO: Running the deCONZ OTA updater...
[22:38:10] INFO: Running the OSRAM LEdvance OTA updater...
[22:38:10] INFO: Running the IKEA OTA updater...
[22:38:10] INFO: Starting VNC server (local/yes)...
[22:38:10] INFO: Starting websockify...
WebSocket server settings:
  - Listen on 127.0.0.1:5901
  - Flash security policy server
  - Web server. Web root: /usr/share/novnc
  - No SSL/TLS support (no cert file)
  - proxying from 127.0.0.1:5901 to 127.0.0.1:5900
[22:38:13] INFO: deCONZ waiting for VNC to start
[22:38:14] INFO: Starting the deCONZ gateway...
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
[22:38:16] INFO: Starting Nginx...
2021/08/21 22:38:16 [notice] 316#316: using the "epoll" event method
2021/08/21 22:38:16 [notice] 316#316: nginx/1.14.2
2021/08/21 22:38:16 [notice] 316#316: OS: Linux 5.10.52-v8+
2021/08/21 22:38:16 [notice] 316#316: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2021/08/21 22:38:16 [notice] 316#316: start worker processes
2021/08/21 22:38:16 [notice] 316#316: start worker process 1362
22:38:15:671 HTTP Server listen on address 0.0.0.0, port: 40850, root: /usr/share/deCONZ/webapp/
22:38:15:729 COM: use stable device path /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2420364-if00
22:38:15:768 COM: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2420364-if00 / serialno: DE2420364, ConBee II
22:38:15:768 ZCLDB init file /data/.local/share/dresden-elektronik/deCONZ/zcldb.txt
22:38:15:882 parent process s6-supervise
22:38:15:882 gw run mode: docker/hassio
22:38:15:882 GW sd-card image version file does not exist: /data/.local/share/dresden-elektronik/deCONZ/gw-version
22:38:15:883 DB sqlite version 3.27.2
22:38:15:884 DB PRAGMA page_count: 45
22:38:15:884 DB PRAGMA page_size: 4096
22:38:15:884 DB PRAGMA freelist_count: 2
22:38:15:884 DB file size 184320 bytes, free pages 2
22:38:15:884 DB PRAGMA user_version: 7
22:38:15:884 DB upgrade to user_version 8
22:38:15:896 DB write sqlite user_version 8
22:38:15:901 DB PRAGMA user_version: 8
22:38:15:901 DB cleanup
22:38:15:901 DB create temporary views
22:38:15:971 started websocket server at port 8081
22:38:15:973 [INFO] - Found file containing button maps. Parsing data...
22:38:15:983 [INFO] - Button maps loaded.
22:38:15:985 dlg action: Read binding table
22:38:15:985 found node plugin: libde_rest_plugin.so - REST API Plugin
22:38:15:988 found node plugin: libde_signal_plugin.so - Signal Monitor Plugin
22:38:22:070 found node plugin: libstd_otau_plugin.so - STD OTAU Plugin
22:38:22:228 LightNode 1: Configuration tool 1 added
22:38:22:244 SensorNode 35 set node 0x00158d0006e486c8
22:38:22:245 DB UPDATE device_descriptors SET data = x'010401015f01030000030006000200000400', timestamp = 1629599902 WHERE device_id = (SELECT id FROM devices WHERE mac = '00:15:8d:00:06:e4:86:c8') AND endpoint = 1 AND type = 4
22:38:22:250 SensorNode 36 set node 0x00158d0006897117
22:38:22:251 DB UPDATE device_descriptors SET data = x'010401015f01030000030006000200000400', timestamp = 1629599902 WHERE device_id = (SELECT id FROM devices WHERE mac = '00:15:8d:00:06:89:71:17') AND endpoint = 1 AND type = 4
22:38:22:258 LightNode 7: Ikea-Air-Filter added
22:38:22:263 SensorNode 41 set node 0x00158d0007058417
22:38:22:264 DB UPDATE device_descriptors SET data = x'010401015f01030000030006000200000400', timestamp = 1629599902 WHERE device_id = (SELECT id FROM devices WHERE mac = '00:15:8d:00:07:05:84:17') AND endpoint = 1 AND type = 4
22:38:22:270 SensorNode 9 set node 0x804b50fffe437c68
22:38:22:271 SensorNode 43 set node 0x00158d0006e40b48
22:38:22:273 LightNode 3: Ikea-Spark-Amp added
22:38:22:275 SensorNode 33 set node 0x00158d0006b78903
22:38:22:275 SensorNode 34 set node 0x00158d0006b78903
22:38:22:276 DB UPDATE device_descriptors SET data = x'010401070101060000060400040005010003000200001900', timestamp = 1629599902 WHERE device_id = (SELECT id FROM devices WHERE mac = '00:15:8d:00:06:b7:89:03') AND endpoint = 1 AND type = 4
22:38:22:283 LightNode 9: Ikea-Katana-Amp added
22:38:22:284 SensorNode 12 set node 0x804b50fffeefac8e
22:38:22:285 SensorNode 13 set node 0x5c0272fffe947b44
22:38:22:286 SensorNode 10 set node 0x847127fffe5a7c25
22:38:22:288 SensorNode 2 set node 0x00158d00067c2f9b
22:38:22:288 SensorNode 3 set node 0x00158d00067c2f9b
22:38:22:289 DB UPDATE device_descriptors SET data = x'010401070101060000060400040005010003000200001900', timestamp = 1629599902 WHERE device_id = (SELECT id FROM devices WHERE mac = '00:15:8d:00:06:7c:2f:9b') AND endpoint = 1 AND type = 4
22:38:22:294 SensorNode 37 set node 0x00158d0006ea34b0
22:38:22:296 LightNode 2: Ikea-Japanese-Lantern added
22:38:22:297 SensorNode 42 set node 0x00158d0006f816c8
22:38:22:299 SensorNode 11 set node 0x847127fffe59325f
22:38:22:300 SensorNode 7 set node 0x00158d000544a73d
22:38:22:300 SensorNode 4 set node 0x00158d000544a73d
22:38:22:302 SensorNode 18 set node 0x00158d00067c5231
22:38:22:302 SensorNode 19 set node 0x00158d00067c5231
curl: (7) Failed to connect to 127.0.0.1 port 40850: Connection refused
[22:38:25] FATAL: Can't get data from deCONZ gateway
[22:38:25] INFO: Starting VNC server (local/yes)...
In exit
Closing socket listening at 127.0.0.1:5901
22:38:22:303 DB UPDATE device_descriptors SET data = x'010401070101060000060400040005010003000200001900', timestamp = 1629599902 2021/08/21 22:38:26 [notice] 316#316: signal 15 (SIGTERM) received from 312, exiting
2021/08/21 22:38:26 [notice] 1362#1362: exiting
2021/08/21 22:38:26 [notice] 1362#1362: exit
2021/08/21 22:38:26 [notice] 316#316: signal 17 (SIGCHLD) received from 1362
2021/08/21 22:38:26 [notice] 316#316: worker process 1362 exited with code 0
2021/08/21 22:38:26 [notice] 316#316: exit
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

## Additional information

Reverting back to 6.9.0 works again.

**Comment by floriant29** [comment]
Hello,

I've thé same issue :

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] firmware.sh: executing... 
[07:26:12] INFO: GCFFlasher V3_17 (c) dresden elektronik ingenieurtechnik gmbh
Path             | Vendor | Product | Serial     | Type
-----------------+--------+---------+------------+-------
/dev/ttyACM0     | 0x1CF1 | 0x0030  | DE2403099  | ConBee II 
/dev/ttyAMA0     | 0x0000 | 0x0000  |            | RaspBee 
[cont-init.d] firmware.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] novnc.sh: executing... 
[cont-init.d] novnc.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[07:26:12] INFO: Websockify waiting for VNC to start
[07:26:12] INFO: Running the deCONZ OTA updater...
[07:26:12] INFO: Running the IKEA OTA updater...
[07:26:12] INFO: Running the OSRAM LEdvance OTA updater...
[07:26:12] INFO: Starting VNC server (local/yes)...
[07:26:13] INFO: Starting websockify...
WebSocket server settings:
  - Listen on 127.0.0.1:5901
  - Flash security policy server
  - Web server. Web root: /usr/share/novnc
  - No SSL/TLS support (no cert file)
  - proxying from 127.0.0.1:5901 to 127.0.0.1:5900
[07:26:16] INFO: deCONZ waiting for VNC to start
[07:26:16] INFO: Starting the deCONZ gateway...
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
[07:26:20] INFO: Starting Nginx...
2021/08/24 07:26:20 [notice] 315#315: using the "epoll" event method
2021/08/24 07:26:20 [notice] 315#315: nginx/1.14.2
2021/08/24 07:26:20 [notice] 315#315: OS: Linux 4.19.0-17-arm64
2021/08/24 07:26:20 [notice] 315#315: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2021/08/24 07:26:20 [notice] 315#315: start worker processes
2021/08/24 07:26:20 [notice] 315#315: start worker process 1367
[07:26:31] INFO: Successfully send discovery information to Home Assistant.
[07:26:32] INFO: Starting VNC server (local/yes)...
2021/08/24 07:26:32 [notice] 315#315: signal 15 (SIGTERM) received from 311, exiting
2021/08/24 07:26:32 [notice] 1367#1367: exiting
2021/08/24 07:26:32 [notice] 1367#1367: exit
2021/08/24 07:26:32 [notice] 315#315: signal 17 (SIGCHLD) received from 1367
2021/08/24 07:26:32 [notice] 315#315: worker process 1367 exited with code 0
2021/08/24 07:26:32 [notice] 315#315: exit
In exit
Closing socket listening at 127.0.0.1:5901
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

**Comment by SiliconAvatar** [comment]
My deCONZ container (version 6.10.0) has just crashed won't start again, same issue as OP.

Logs indicate that it's starting correctly, but then the logs show that it received a sigterm signal and it shuts down.  


```
16:12:55:480 COM: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE1964773-if00 / serialno: DE1964773, ConBee II
16:12:56:442 Skip idle timer callback, too early: elapsed 160 msec
16:12:56:512 New websocket 172.30.32.1:33376 (state: 3) 
[16:12:57] INFO: Starting VNC server (local/yes)...
2021/09/13 16:12:57 [notice] 317#317: signal 15 (SIGTERM) received from 308, exiting
In exit
2021/09/13 16:12:57 [notice] 1350#1350: exiting
2021/09/13 16:12:57 [notice] 1350#1350: exit
Closing socket listening at 127.0.0.1:5901
2021/09/13 16:12:57 [notice] 317#317: signal 17 (SIGCHLD) received from 1350
2021/09/13 16:12:57 [notice] 317#317: worker process 1350 exited with code 0
2021/09/13 16:12:57 [notice] 317#317: exit
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by nomad-cyanide** [comment]
after upgrading to 6.10, everything stopped working on a RasPi 4b with the RaspBee II module installed. 
I could uninstall and install again and get some functionality running, but a after reboot of the Pi, nothing worked again. 
I downgraded to 6.9 via backups and got this in the logs:
17:36:08:236 start reconnect to network
17:36:09:301 dev /dev/ttyAMA0
17:36:13:235 failed to reconnect to network try=1
17:36:18:236 failed to reconnect to network try=2
17:36:23:236 failed to reconnect to network try=3
17:36:28:235 failed to reconnect to network try=4
17:36:33:235 failed to reconnect to network try=5
17:36:38:235 failed to reconnect to network try=6
17:36:43:235 failed to reconnect to network try=7
17:36:48:235 failed to reconnect to network try=8
17:36:53:235 failed to reconnect to network try=9
17:36:58:235 failed to reconnect to network try=10
17:37:03:235 reconnect network failed, try later

Had to change settings for deconz to point to /dev/ttyS0, even though Raspbee II is installed on /dev/ttyAMA0. 
This made the setup work again.
I am not upgrading to 6.10 again!
