### ISSUE TITLE
Problem with File editor

### ISSUE THREAD

**Issue by rto54** [home-assistant/addons#2162]
## The problem

Hello,
For the past few days, i have a problem with file editor, when i want to go it, this what it shows me.
And ha freeze

![image](https://user-images.githubusercontent.com/20343636/131122547-b0166631-60ea-498c-a6ad-d458a15f8ac8.png)

## System Health

version | core-2021.8.8
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.6
os_name | Linux
os_version | 5.10.53
arch | x86_64
timezone | Europe/Paris

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4531
Installed Version | 1.14.1
Stage | running
Available Repositories | 936
Installed Repositories | 35

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.2
-- | --
update_channel | stable
supervisor_version | supervisor-2021.06.8
docker_version | 20.10.6
disk_total | 292.7 GB
disk_used | 67.8 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.5.1), Check Home Assistant configuration (3.8.0), Terminal & SSH (9.1.3), Samba Backup (4.5.0), MariaDB (2.4.0), phpMyAdmin (0.5.0), Zigbee2mqtt (1.21.0-4), Mosquitto broker (6.0.1), Glances (0.13.0), InfluxDB (4.2.1), Nginx Proxy Manager (0.11.0), Duck DNS (1.13.0), Home Assistant Google Drive Backup (0.104.3), Network UPS Tools (0.8.0), File editor (5.3.3)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 19
views | 14
mode | storage

</details>

- Add-on with the issue: File editor
- Add-on release with the issue:  5.3.3
- Last working add-on release (if known):  18/08/2021
- Operating environment (OS/Supervised):  supervisor-2021.06.8

``
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

#======================#
#  Home assistant      #
#======================# 
homeassistant:
  # Name of the location where Home Assistant is running
  name: Home assitant Maison
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: !secret elevation_home
  # 'metric' for Metric, 'imperial' for Imperial
  unit_system: metric
  external_url : !secret homeassistant_url_externe
  internal_url:  !secret homeassistant_url_interne
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Paris
  customize: !include customize.yaml
  # pour TTS
  whitelist_external_dirs:
    - /config/tts

# Text to speech
tts:
  - platform: google_translate
    language: fr-fr  
    base_url: https://XXXX.ui.nabu.casa/
    cache: true
    cache_dir: /config/tts
    time_memory: 300

#======================#
#  Recorder MariaDb    #
#======================# 
recorder:
  db_url: !secret db_mysql
  auto_purge: true
  commit_interval: 15
  include:
    domains:
      - binary_sensor
      - input_boolean
      - input_datetime
      - input_number
      - input_select
      - input_text
      - sensor
      - switch
      - person
      - device_tracker
      - light
      - cover
  exclude:
    domains:
      - camera
      - zone
      - automation
      - sun
      - weather
      - cover
      - group
      - script
      - pool_pump
    event_types:
      - automation_triggered
      - script_started
      - service_registered
      - home_assistant_start
      - home_assistant_stop
      - home_assistant_stop
    entities:
      - sun.sun
      - sensor.last_boot
      - sensor.date
      - sensor.time
    
##########################
# ALEXA                  #
##########################
alexa_media:
  accounts:
    - email: !secret amazon_user
      password: !secret amazon_password
      url: amazon.fr
#api:

#alexa:
#  smart_home:
#   locale: fr-FR
#   endpoint: https://api.eu.amazonalexa.com/v3/events
#   client_id: XX
#   client_secret: XX
   
##########################

group: !include groups.yaml
automation: !include_dir_merge_list automation/
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensor.yaml
device_tracker: !include device_tracker.yaml
switch: !include switch.yaml
input_select: !include input_select.yaml
input_number: !include input_number.yaml
input_boolean: !include input_boolean.yaml

frontend:
  themes: !include_dir_merge_named themes

http:
  base_url: XXXX.duckdns.org:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

#======================#
#  Vanderbilt SPC      #
#======================#    
spc:
  api_url: !secret spc_api
  ws_url: !secret spc_url

#======================#
#  Somfy Connexoon     #
#======================#   
somfy:
#client_id: !secret somfy_id
#client_secret: !secret somfy_secret

#======================#
#  Ikea Tradfri        #
#======================#  

#======================#
#  Google NEST         #
#======================#    

#======================#
#  Jeedom              #
#======================# 
rest_command:
  volet_terrasse_up:
    url: "http://XX.fr/core/api/jeeApi.php?apikey=Q1I6mgWJpKMKYqLGZpLypw4HSu3V8dKJ&type=cmd&id=608"
  volet_terrasse_down:
    url: "http://.fr/core/api/jeeApi.php?apikey=Q1I6mgWJpKMKYqLGZpLypw4HSu3V8dKJ&type=cmd&id=609"
  volet_terrasse_stop:
    url: "http://XX.fr/core/api/jeeApi.php?apikey=Q1I6mgWJpKMKYqLGZpLypw4HSu3V8dKJ&type=cmd&id=615"
  volet_terrasse_etat:
    url: "https://XX.fr/core/api/jeeApi.php?apikey=Q1I6mgWJpKMKYqLGZpLypw4HSu3V8dKJ&type=cmd&id=610"
## Shelly ##
  volet_salon_down:
    url: "https://XX.fr/core/api/jeeApi.php?apikey=Q1I6mgWJpKMKYqLGZpLypw4HSu3V8dKJ&type=cmd&id=7536"
  volet_salon_etat:
    url: "https://XX.fr/core/api/jeeApi.php?apikey=Q1I6mgWJpKMKYqLGZpLypw4HSu3V8dKJ&type=cmd&id=7542"
#======================#
#  Telegram            #
#======================# 

telegram_bot:
  - platform: polling
    api_key: !secret telegram_token
    allowed_chat_ids:
      - !secret id_telegram_rodolphe ## Rodolphe
      - !secret id_telegram_maison ##groupe

#======================#
#  Notification        #
#======================#    
notify:
#======================#
#  WhatsApp            #
#======================#  
  - name: WhatsApp
    platform: rest
    resource: https://api.callmebot.com/whatsapp.php
    data:
      source: HA
      phone: !secret whatsapp_rodolphe
      apikey: !secret whatsapp_rodolpheapikey
#======================#
#  Free                #
#======================# 
  - name: notif_free_vero
    platform: free_mobile
    username: XXX
    access_token: XXX
#======================#
#  Telegram            #
#======================#     
  - platform: telegram    
    name: Telegram Maison
    chat_id: !secret id_telegram_maison ## Groupe
    
  - platform: telegram
    name: telegram rodolphe
    chat_id: !secret id_telegram_rodolphe ## Rodolphe  
 
#======================#
#  Fibaro HC3 Lite     #
#======================#    
fibaro:
  gateways:
    - url: !secret fibaro_url
      username: !secret fibaro_username
      password: !secret fibaro_password

#======================#
#  Mi Air Purifier 3H  #
#======================#    
fan:
  - platform: xiaomi_miio_airpurifier
    name: "Mi Air Purifier 3H"
    host: !secret 3H_host
    token: !secret 3H_token
    model: zhimi.airpurifier.mb3
    
#======================#
#  Glouk               #
#======================# 
vacuum:
  - platform: xiaomi_miio
    name: Glouk
    host: !secret Glouk_host
    token: !secret Glouk_token

camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret Glouk_maphost
    token: !secret Glouk_maptoken
    username: !secret mi_username
    password: !secret mi_password
    name: "Glouk"
    draw: ['all']
    map_transformation: 
      scale: 2
      rotate: 0
      trim: 
        top: 10
        bottom: 20
        left: 30
        right: 40
    sizes:
      charger_radius: 3
      vacuum_radius: 4
    attributes:
      - calibration_points
      - charger
      - goto
      - goto_path
      - goto_predicted_path
      - image
      - is_empty
      - map_name
      - no_go_areas
      - no_mopping_areas
      - obstacles
      - path
      - room_numbers
      - rooms
      - vacuum_position
      - vacuum_room
      - walls
      - zones
    auto_update: true

#======================#
#  Proxmox             #
#======================#        
proxmoxve:
  - host: 192.168.XXX
    username: XXX
    password: XXX
    verify_ssl: false
    nodes:
      - node: pve
        vms:
          - 100

utility_meter:
  energy_jour_hp:
    source: sensor.teleinfo_energyhp
    cycle: daily
  energy_jour_hc:
    source: sensor.teleinfo_energyhc
    cycle: daily

```
Thanks

**Comment by ludeeus** [comment]
Please report that to the maintainer of the software inside the add-on <https://github.com/danielperna84/hass-configurator>. Thanks :+1:
