### ISSUE TITLE
Terminal & SSH: keyboard layout

### ISSUE THREAD

**Issue by ebaschiera** [home-assistant/addons#2165]
## The problem
Hi, the web terminal uses a different keyboard layout from my system's and I could not find a way to set it.
I would like to have the keyboard working with my system's layout.
There's not much more to say... In the past it worked correctly. Last time I used it, maybe one month ago, it worked as expected.
Thanks!

## Environment

- Add-on with the issue: Terminal & SSH
- Add-on release with the issue: 9.1.3
- Last working add-on release (if known): don't know, but it worked correctly in the past
- Operating environment (OS/Supervised): Home Assistant OS 6.2 on a Raspi 4

## Problem-relevant configuration

```yaml
authorized_keys: []
apks: []
password: ''
server:
  tcp_forwarding: false

```

## Traceback/Error logs

```txt

```

**Comment by ludeeus** [comment]
Is that working in the emulator here <https://xtermjs.org/>?

**Comment by ebaschiera** [comment]
Same issue there. It looks like a matter of browser (Chrome) configuration.
On Firefox I am not having the same issue.
Have you got ant hint for that please? Chrome configuration doesn't look wrong... it's set in my language and locale, apparently.

Thanks for pointing me into the right direction to investigate further!

**Comment by ludeeus** [comment]
Disable all content/ad blockers
