### ISSUE TITLE
AEOTEC Nano Dimmer (ZW111) - Incorrect association with Switch 2 

### ISSUE THREAD

**Issue by rjblake** [home-assistant/addons#2166]
## The problem

I think either the text is incorrect, or configuration for Parameter 124 (https://devices.zwave-js.io/?jumpTo=0x0312:0xa000:0xaa02:0.0#) - Options shown are as follows:

Value | Label
-- | --
1 | Load
2 | Association group 4
3 | Load and association group 3

I believe Value 3 should be for "Load and association group 4", as this is for Switch 2, and as per Aeotec Specification controls Group 4. I have not been able to test it yet to see if it actually tries to control Group 3 (instead of Group 4), or is simply the text that needs correcting.

## Environment

- Add-on with the issue: Z-Wave JS 
- Add-on release with the issue: 0.1.37
- Last working add-on release (if known): 
- Operating environment (OS/Supervised):  OS

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```txt

```

**Comment by MartinHjelmare** [comment]
Your link to the Z-Wave JS Config DB Browser seems to target another device than ZW111?

Regardless, please report problems with the Z-Wave JS Config DB Browser to the Z-Wave JS project. The Home Assistant Z-Wave JS add-on is not the same project and not responsible for the Z-Wave JS Config DB Browser.

Thanks!

**Comment by rjblake** [comment]
Thanks - have corrected the link (despite copying it, seems to have referred to another device). I'm not sure if it is just test in the DB Browser, or with the configuration, as when including device, seems that this is also reflected in the configuration. Will know more once I can test on another dimmer (moving over to HA from another controller)
