### ISSUE TITLE
Not bug but feature request

### ISSUE THREAD

**Issue by terenceng81** [home-assistant/addons#2167]
## The problem
No problem but feature request, instead of shutdown the pc, can we add configuration to sleep or hibernate the pc? thanks.

## Environment

- Add-on with the issue:
- Add-on release with the issue: 
- Last working add-on release (if known): 
- Operating environment (OS/Supervised): 

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```txt

```

**Comment by ludeeus** [comment]
For feature requests, please use the forums :+1: 
https://community.home-assistant.io/c/feature-requests/13

For an alternative that support that and more have a look at <https://gitlab.com/iotlink/iotlink>
