### ISSUE TITLE
deCONZ: Phoscon Web App Login only visible when using IP-Addr as an URL via Ingress

### ISSUE THREAD

**Issue by kappuchino** [home-assistant/addons#2172]
## The problem

My vanilla hass.io instance ran smothly from 192.168.2.10:8123 (your address my vary). 
To make it it nicer, I set up a dns entry that would link ha.mydomain.tld to the address and then use http://ha.mydomain.tld:8123 just because.

Now when I use the domain url (does NOT matter if http or https), the login field of deCONZ does NOT show up / you can't choose the stick.

Since I would enforce SSL and the domain in the next step, deCONZ can't be configured any more properly.

## Environment
- Raspberry PIE 4 / 8GB / 64 Bit Image
- Home Assistant 2021.8.8 , but Problem exists at least since 2021.6 or 5 (not tried that before)
- ConBeeUSB II Stick
- Fresh Install is the same

## Problem-relevant configuration
There is no config that causes that except when I use a domain name instead of an IP Address

## Traceback/Error logs
I can't find log errors on the server. It might fail in the browser but looking at the Web-Console reveals nothing to my knowledge (so no error in the JS-Console for Example)

## Additional information
Don't know anything else.
I've included a screenshot side by side of the Browser display with IP-Address and with Domain-Name. 
![Screenshot - no Login Side by Side](https://user-images.githubusercontent.com/2975047/131921071-2eb485e6-43e8-4669-8361-f2affadc56c6.png)

**Comment by stepman0** [comment]
Same issue here, since about a year.

**Comment by kappuchino** [comment]
Here too.

**Comment by trunneml** [comment]
Same here

**Comment by trunneml** [comment]
Don't close. Problem still exist.

**Comment by kappuchino** [comment]
Yes, it still persists in the current version. Anyone any idea how much we would need to collect in "bribes" to buy a fix? And is it an Issue coming from the original phoscon or does it only occur with ingress?

**Comment by tannyl** [comment]
I have made a fix for the problem and got an PR #2325 open about it. But nothing is happening yet.

Anyway, the problem behind this, is a mix of how the whole ingress solution is made and the fact that the Phoscon's JavaScript is a bit wonky and poorly coded in some places (my opinion).

**Comment by kappuchino** [comment]
Still not working, hoping for the next release.

**Comment by tannyl** [comment]
Still not fixed

**Comment by unix0r** [comment]
still not fixed.

**Comment by herveaurel** [comment]
still not fixed !

**Comment by tannyl** [comment]
@herveaurel what versions of HA and the addon are you using?

**Comment by herveaurel** [comment]
> @herveaurel what versions of HA and the addon are you using?

hello.  my HA is up to date:

Home Assistant Core 2022.6.7

Home Assistant Supervisor 2022.05.3

Home Assistant OS 8.2

Addon : deCONZ 6.14.2

I had CONZ.  I deleted it to test something else.  I installed it again and now I have this problem.

**Comment by tannyl** [comment]
> The main page is sometimes empty, but not all the time. I have to click anywhere to get the menu. And the lights page was blank, now it shows 4 out of 30 lights, and I can't click on them to delete them.

The main page, is that the login page? And do these problems occur when using IP and/or domain name to access the page?
