### ISSUE TITLE
MariaDB example DB_URL contains @  - docs state this should not work (although it does)

### ISSUE THREAD

**Issue by SamJongenelen** [home-assistant/addons#2173]
## The Problem

The MariaDB contains an example configuration for the recorder:

>recorder:
  db_url: mysql://homeassistant:password@core-mariadb/homeassistant?charset=utf8mb4

However, as stated in the breaking changes a while ago the `db_url` shouldnt not contain `@`.
https://www.home-assistant.io/blog/2021/07/07/release-20217/#breaking-changes  (under Recorder).

## Environment

- Add-on with the issue:
MariaDB
- Add-on release with the issue: 
- Last working add-on release (if known): 
- Operating environment (OS/Supervised): 

- Problem configuration:
```yaml
recorder:
  db_url: mysql://homeassistant:password@core-mariadb/homeassistant?charset=utf8mb4
```

## Additional information

MariaDB integration worked with `@`  in my db_url, on latest HA (2021.9.3)

**Comment by ludeeus** [comment]
It both works and is needed where it's used in that example.
However, using it in the username and/or password is not working, and that is what that notice is talking about.

**Comment by SamJongenelen** [comment]
OK. Well, personally I prefer the @ sign for readability for sure. Perhaps best would be to split the `db_url` into mutliple properties?

**Comment by ludeeus** [comment]
it's a connection string, that is how it's supposed to look, and the `@` should be between the password and the hostname

**Comment by SamJongenelen** [comment]
Yeah, is a very minor thing: its not an uri its a connectionstring
