### ISSUE TITLE
problem with Energy panel and MariaDB

### ISSUE THREAD

**Issue by Whastie** [home-assistant/addons#2180]
When I installed MariaDB, the Energy panel and everything related to graphing sensors stopped working.
I have commented the line:
recorder:
# db_url: mysql: // homeassistant: pasword @ core-mariadb / homeassistant? charset = utf8mb4

and everything has worked for me again.
Can you help me configure MariaDB and keep everything working?

**Comment by ludeeus** [comment]
Please use the [forums](https://community.home-assistant.io/) or [discord](https://discord.gg/c5DvZ4e) server for configuration help. THanks :+1:
