### ISSUE TITLE
Z-Wave JS addon uses legacy configuration option "networkKey"

### ISSUE THREAD

**Issue by Doridian** [home-assistant/addons#2182]
## The problem

The Z-Wave JS addon uses the legacy configuration option `networkKey`. According to their documentation this should not be used and instead the new options should be used.
Those are described here: https://zwave-js.github.io/node-zwave-js/#/api/driver?id=zwaveoptions (See the `securityKeys` object)

This causes the following log entries to be printed upon add-on start. As I don't have any S2 accessories at the moment, I cannot verify they are indeed broken with the legacy option.

```
The `networkKey` option is deprecated in favor of `securityKeys` option. To eliminate this warning, move your networkKey into the securityKeys.S0_Legacy option. Refer to the Z-Wave JS docs for more information
[...]
2021-09-13T14:22:56.745Z DRIVER   No network key for S2 configured, communication with secure (S2) devices won't
                                   work!
```

## Environment

- Add-on with the issue: zwave_js
- Add-on release with the issue: latest
- Last working add-on release (if known): N/A 
- Operating environment (OS/Supervised): OS

**Comment by MartinHjelmare** [comment]
See https://github.com/home-assistant/addons/pull/2157.

**Comment by Doridian** [comment]
@MartinHjelmare
Thanks for the link. :)
I searched for a related PR or issue, but GitHub turned up nothing for "networkKey".
