### ISSUE TITLE
No energy measurement for Plugwise plug EU via Deconz

### ISSUE THREAD

**Issue by xylone** [home-assistant/addons#2185]
## The problem
Plugwise plugs do not expose energy measurement. Aqara plug do. See image (Circulatie pomp = Aqara, wasmachine = plug wise plug).
I used to have these integrated in Homey and there was measurement visible. So the hardware supports it.

## System Health

version | core-2021.9.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.6
os_name | Linux
os_version | 5.10.17-v8
arch | aarch64
timezone | Europe/Amsterdam

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 5000
Installed Version | 1.15.2
Stage | running
Available Repositories | 880
Installed Repositories | 4

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.4
-- | --
update_channel | stable
supervisor_version | supervisor-2021.09.0
docker_version | 20.10.7
disk_total | 360.4 GB
disk_used | 19.9 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | deCONZ (6.10.0), ESPHome (2021.8.2), Duck DNS (1.13.0), Visual Studio Code (3.6.2), Home Assistant Google Drive Backup (0.104.3), SSH & Web Terminal (9.0.1), InfluxDB (4.2.1), Grafana (7.2.0), AdGuard Home (4.1.9), ZeroTier One (0.11.1), Portainer (2.0.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 3
-- | --
resources | 2
views | 7
mode | storage

</details>

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```txt

```

## Additional information
<img width="526" alt="Schermafbeelding 2021-09-17 om 10 00 42" src="https://user-images.githubusercontent.com/2749350/133747495-ca8db6f0-fe71-450d-bc3c-696a9ee99788.png">

**Comment by ludeeus** [comment]
Please open an issue in the core repo against the integration that provides that data. Thanks :+1:
