### ISSUE TITLE
Terminal&SSH addon unreadble CLI in Safari

### ISSUE THREAD

**Issue by Stooovie** [home-assistant/addons#2186]
## The problem

Text can't be read at all in the Terminal addon in Safari.

## Environment
Terminal&SSH addon v9.1.3, HA 2021.9.6, Safari on MacOS Monterey beta, also happens in Safari on Big Sur 11.6.

- Add-on with the issue: Terminal&SSH
- Add-on release with the issue: 9.1.3
- Last working add-on release (if known): 
- Operating environment (OS/Supervised): HAOS 6.3 on Rpi4

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```txt

```

## Additional information

This only happens in Safari, Edge on the same machine is perfectly fine
<img width="1428" alt="Screenshot 2021-09-19 at 10 02 43" src="https://user-images.githubusercontent.com/10572373/133920102-b47d3847-cc99-419a-b072-c9f327ecf0ad.png">
.

**Comment by shodanx2** [comment]
There is also a font issue in Firefox, see below

![image](https://user-images.githubusercontent.com/10621885/133956682-f25f50b9-d553-4c61-9fa5-c39ea2bfa0b5.png)

**Comment by netweaver1970** [comment]
same issue as https://github.com/home-assistant/addons/issues/2141
and as https://github.com/home-assistant/addons/issues/1983

Did you look at those already?

**Comment by Stooovie** [comment]
#2141 and #1983 are different issues. I just see empty screen in Safari.

**Comment by ludeeus** [comment]
Disable all browser plugins.
See <https://github.com/tsl0922/ttyd/issues/685>

**Comment by fmeus** [comment]
Not using any browser plugins but I am having the same issue

**Comment by ludeeus** [comment]
Is the emulator here showing? https://xtermjs.org/

**Comment by fmeus** [comment]
No it is not showing either

**Comment by ludeeus** [comment]
Then that is the issue, that is the software running inside the add-on.
It seems you need to disable WebGL2 <https://github.com/xtermjs/xterm.js/issues/3357> (last comment)

**Comment by fmeus** [comment]
> Then that is the issue, that is the software running inside the add-on.
> It seems you need to disable WebGL2 [xtermjs/xterm.js#3357](https://github.com/xtermjs/xterm.js/issues/3357) (last comment)

Just checked on macOS and this workaround seems to work. It does require your to turn on the Develop Menu to be able to get to the Experimental Features...

**Comment by Stooovie** [comment]
xtermjs.org: **working** on Safari Mac, **not working** on Safari iOS. There must've been a change because the addon DID work on Safari iPhone just fine, I have used it to issue "ha core restart" command from my phone countless times.

**Comment by ludeeus** [comment]
Disable WebGL2 and it should start working again

**Comment by Stooovie** [comment]
Yes, after disabling WebGL2 in iPhone Safari Experimental features, Terminal does work. It does not, however, work in the official iOS HA app - no way to disable it there.

**Comment by Lemonadel** [comment]
Will someone fix this finally? Same problem on apps for iPad and iPhonez.

**Comment by apbarratt** [comment]
Getting this issue on Safari on my Mac.

**Comment by ludeeus** [comment]
It has been fixed in `ttyd`, but until release it there is nothing that can't be done in the add-on.

**Comment by dsegantx** [comment]
What is the status of releasing the fix?  It’s quite a long running issue considering it’s solved. Trying to understand the remaining gates to getting this released…?

**Comment by ludeeus** [comment]
Still waiting for upstream release.

**Comment by DevilTears** [comment]
I get same problem, waiting resolve

**Comment by dsegantx** [comment]
Terminal 9.2.2 was just released and I’ve installed it.  It says it fixed escape color codes.
I still don’t see different behavior on iPad/Safari.  Wondering if the fix was for something else and we’re still awaiting this fix?

**Comment by ludeeus** [comment]
This issue is still open (not fixed), still waiting for a release..

**Comment by xxpas02** [comment]
Issue still present on T&SSH 9.2.2 on HA OS 7.1 2021.12.7 on MacOS 10.15.7 with Safari 15.3 and on Home Assistant iOS app 2021.12.1 on iOS 15.2. Terminal is a grey screen with no prompt, no proper cursor and no text when typing.
