### ISSUE TITLE
SambaShare check ntlm password error

### ISSUE THREAD

**Issue by digitalMedic** [home-assistant/addons#2196]
## The problem

 Unable to connect to homeassistant using SambaShare unless I put my Windows login credentials into the SambaShare config.   As soon as I added my Windows login credentials, I was able to access the homeassistant files using SambaShare.  SambaShare worked before using generic credentials.  I have not had this problem until the last couple months.

## Environment

  I am using version 9.5.1 of SambaShare, Core Version core-2021.9.7, Supervisor Version supervisor-2021.09.0

- Add-on with the issue: SambaShare
- Add-on release with the issue: 9.5.1
- Last working add-on release (if known): 
- Operating environment (OS/Supervised): Windows 10 Pro

## Problem-relevant configuration

Config that did not work:

workgroup: WORKGROUP
username: HAsamba
password: test
allow_hosts:
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.1.0/16
  - fe80::/10
veto_files:
  - ._*
  - .DS_Store
  - Thumbs.db
  - icon?
  - .Trashes
compatibility_mode: false

Config that worked: 

workgroup: WORKGROUP
username: Rick
password: *********** [my WIndows 10 login password]
allow_hosts:
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.1.0/16
  - fe80::/10
veto_files:
  - ._*
  - .DS_Store
  - Thumbs.db
  - icon?
  - .Trashes
compatibility_mode: false

```yaml

```

## Traceback/Error logs

I was getting the following error until I added my Windows login credentials into the SambaShare config.

 check_ntlm_password: authentication for user [rick] -> [rick] failed with error nt_status_no_such_user, authoritative=1

```txt

```

**Comment by poundy** [comment]
who is managing the lifecycle of the Samba HA add-on? I note that the add-on currently uses 4.13.8, and from the SAMBA planning wiki page https://wiki.samba.org/index.php/Samba_Release_Planning that the current version (4.13.13) is only getting security updates for the next 4 months, and we therefore need to move over to a newer branch

**Comment by martymarty004** [comment]
You are not the only ones experiencing this issue, there is a quite old [topic](https://community.home-assistant.io/t/another-samba-share-problem-with-windows-10/140377) about this on the Home Assistant Community forum.
I have found a [workaround](https://community.home-assistant.io/t/another-samba-share-problem-with-windows-10/140377/30?u=martymarty004), and it seems to be working.

I'm listing the steps here aswell:

> If you open the Credential Manager in Windows, you can add a new Windows Credential with the IP of your HA instance and the credentials you configured in the Samba Add-on.
> If you try to access \\192.168.X.Y Windows will use the credentials you created and access will be granted.
> 

![image](https://user-images.githubusercontent.com/61474670/141353123-2a2a5c40-8702-4f67-af46-e58a4813c36b.png)

Of course, the add-on working out of the box would still be nice.

**Comment by poundy** [comment]
> You are not the only ones experiencing this issue

thanks for coming along and confirming. In my mind, it's a clear bug / change in behaviour - prior to around 30th May 2021, Windows users would be prompted when the logged-in user and the SAMBA add-on predefined user did not match; from that point on the SAMBA server never caused the Windows client to prompt for a password.  The pity is that there's no logs in any of those threads you pointed out, as that would tell us if the crash we observe now has been going on since that point.  

The real pity however is no engagement from anyone who is in a position to help.

**Comment by Bakkoda** [comment]
I have been experiencing problems from day 1 of 9.5.1. My Samba credentials are my windows credentials and prior to the upgrade everything worked flawlessly. Now that I am on 9.5.1 I can connect, browse, edit single files but nothing more than that. Any attempts to use git to push/pull/stage/commit fail and I lose access for 15-30 seconds then everything resumes as normal.

`check_ntlm_password:  Authentication for user [GREYSKULL$] -> [GREYSKULL$] FAILED with error NT_STATUS_NO_SUCH_USER, authoritative=1`

I do not know who is responsible at this point, Windows 10 or Samba Share but for some reason the computer name is being sent in the handshake. ALl major Win10 updates happened prior to 9.5.1 and again it all worked flawlessly. 

```
===============================================================
PANIC (pid 525): Signal 11: Segmentation fault in 4.13.8
unable to produce a stack trace on this platform
coredump is handled by helper binary specified at /proc/sys/kernel/core_pattern
Registered MSG_REQ_POOL_USAGE
check_ntlm_password:  Authentication for user [GREYSKULL$] -> [GREYSKULL$] FAILED with error NT_STATUS_NO_SUCH_USER, authoritative=1
===============================================================
INTERNAL ERROR: Signal 11: Segmentation fault in pid 526 (4.13.8)
If you are running a recent Samba version, and if you think this problem is not yet fixed in the latest versions, please consider reporting this bug, see https://wiki.samba.org/index.php/Bug_Reporting
===============================================================
PANIC (pid 526): Signal 11: Segmentation fault in 4.13.8
unable to produce a stack trace on this platform
coredump is handled by helper binary specified at /proc/sys/kernel/core_pattern
Registered MSG_REQ_POOL_USAGE
check_ntlm_password:  Authentication for user [GREYSKULL$] -> [GREYSKULL$] FAILED with error NT_STATUS_NO_SUCH_USER, authoritative=1
===============================================================
INTERNAL ERROR: Signal 11: Segmentation fault in pid 527 (4.13.8)
If you are running a recent Samba version, and if you think this problem is not yet fixed in the latest versions, please consider reporting this bug, see https://wiki.samba.org/index.php/Bug_Reporting
===============================================================
PANIC (pid 527): Signal 11: Segmentation fault in 4.13.8
unable to produce a stack trace on this platform
coredump is handled by helper binary specified at /proc/sys/kernel/core_pattern
greyskull (ipv4:192.168.2.100:57733) closed connection to service config
```

The log file is just this repeated over and over again. Sometimes I get a JSON looking breakdown but its too large for the log window to display all of it. This computer IS part of a domain as I have an AD running and its the only thing I havent seen brought up, my workgroup is the same as the domain. Again it all worked prior to 9.5.1.
