### ISSUE TITLE
Let's Encrypt acme-challenge time out

### ISSUE THREAD

**Issue by PeterBenicky** [home-assistant/addons#2197]
## The problem
  I have Home Assistant 2021.9.6 running on my Raspberry pi 4. I installed MariaDb and Let's Encrypt.  However when starting Let's Encrypt add-on, i get error:
```
http://test.benicky.info/.well-known/acme-challenge/wL-mUSA6vJ89iYUdBd5wsaHth_Kl4YeTQB4jRIEplec:
   Timeout during connect
```
Please note that i have checked my DNS record and my router, i have static public ip.
DNS: test.benicky.info -> 109.230.20.56
ma router port forward: 
80 tcp --> local ha port 80
443 tcp --> local ha port 443
8123 tcp --> local ha port 8123

I made below tests:
being able to connect from public:
test.benicky.info:8123.  During Let's Encrypt start up procedure i was able to see for 2 seconds in the browser 'ACME client standalone challenge solver' when refreshing page test.benicky.info:80. 

## Environment

Raspberry pi 4.

Home Assistant 2021.9.6 
### System Health

version | core-2021.9.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.6
os_name | Linux
os_version | 5.10.17-v8
arch | aarch64
timezone | Europe/Bratislava

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | failed to load: timeout

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.3
-- | --
update_channel | stable
supervisor_version | supervisor-2021.09.0
docker_version | 20.10.7
disk_total | 57.8 GB
disk_used | 5.4 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | eWeLink Smart Home (1.2.0), RPC Shutdown (2.2), Hey Ada! (1.1.1), Visual Studio Code (3.6.2), Mosquitto broker (6.0.1), Nginx Proxy Manager (0.11.0), MariaDB (2.4.0), SSH & Web Terminal (9.0.1), Let's Encrypt (4.11.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 0
views | 1
mode | storage

</details>

- Add-on with the issue:
- Add-on release with the issue: 
- Last working add-on release (if known): 
- Operating environment (OS/Supervised): 

Let's Encrypt
Current version: 4.11.0

## Problem-relevant configuration
Let's Encrypt config file:

```
email: peter@benicky.info
domains:
  - test.benicky.info
certfile: fullchain.pem
keyfile: privkey.pem
challenge: http
dns: {}
```
Let's Encrypt Network settings: using default, meaning host = 80 

## Traceback/Error logs
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] file-structure.sh: executing... 
[cont-init.d] file-structure.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[19:41:31] INFO: Selected http verification
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for test.benicky.info
Waiting for verification...
Challenge failed for domain test.benicky.info
http-01 challenge for test.benicky.info
Cleaning up challenges
Some challenges have failed.
IMPORTANT NOTES:
 - The following errors were reported by the server:
   Domain: test.benicky.info
   Type:   connection
   Detail: Fetching
   http://test.benicky.info/.well-known/acme-challenge/wL-mUSA6vJ89iYUdBd5wsaHth_Kl4YeTQB4jRIEplec:
   Timeout during connect (likely firewall problem)
   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address. Additionally, please check that
   your computer has a publicly routable IP address and that no
   firewalls are preventing the server from communicating with the
   client. If you're using the webroot plugin, you should also verify
   that you are serving files from the webroot path you provided.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by iball** [comment]
I'm seeing the same thing on my end with this in the logs:

21-09-30 17:00:14 WARNING (MainThread) [supervisor.addons.options] Unknown option 'yZ500JCTf1gbiXN6NScA0cVuXPmpSPPqWDz-ZqGHPVc' for Let's Encrypt (core_letsencrypt)

**Comment by bachelddd** [comment]
Hello.
I have a problem.
either in the add-on nginx or in let's, they do not generate the certificates in the ssl folder.

Log:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[09:38:25] INFO: Running nginx...
nginx: [emerg] cannot load certificate "/ssl/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/ssl/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
