### ISSUE TITLE
duckdns: algo option required but cannot set

### ISSUE THREAD

**Issue by thomasdg** [home-assistant/addons#2201]
## The problem
Just updated the duckdns addon to the latest version (1.14). It doesn't start anymore and wants to have an algo option (as also mentioned in changelog). This option seems to be required rather than optional.
I tried to add the option to the configuration, as an extra line 'algo: secp384r1', but when I try to save the configuration I get a complaint about algo missing in the configuration and not wanting to save it...

## Environment
Hass OS 6.1
Home Assistant Core core-2021.9.6

- Add-on with the issue: duckdns
- Add-on release with the issue: 1.14.0
- Last working add-on release (if known):  1.13.0
- Operating environment (OS/Supervised): 6.1 on RPi

## Traceback/Error logs
```
Missing option 'algo' in lets_encrypt in Duck DNS (core_duckdns).
```

**Comment by ripburger** [comment]
I am having the exact same issue.

**Comment by ludeeus** [comment]
The `algo` key goes under the  `lets_encrypt` key

**Comment by danuals** [comment]
![Uploading 81629AF4-84F1-4593-A10A-3AE97B7ED8FF.jpeg…]()

**Comment by thomasdg** [comment]
Thanks! Added the "algo: secp384r1" in the lets_encrypt part and works now.

lets_encrypt:
  accept_terms: true
  certfile: fullchain.pem
  keyfile: privkey.pem
  algo: secp384r1
token: ***************
domains:
  - **********.duckdns.org
aliases: []
seconds: 300

**Comment by danuals** [comment]
![A95A1381-C80A-44C2-ABCC-5E5720FD8FB5](https://user-images.githubusercontent.com/63956367/134911277-73719fe4-036a-415b-ad0d-fb357ea29887.jpeg)
