### ISSUE TITLE
Addon: DuckDNS - Algo Option

### ISSUE THREAD

**Issue by mcfly2283-ai** [home-assistant/addons#2202]
After Updating to 1.14.0 i noticed that the new optional Option "lets_encrypt.algo" is not correctly documented.
The Documentaiton say that this is optional, but after updating i can`t start the Addon till i add the line "algo: secp384r1" to my DuckDNS (Lets Encrypt) configuration.

Maybe someone can add this additional Line to the Documentaion-examples for other users, so they dont need to try and search for a working config and check if its really an optional Setting.

DuckDNS 1.14.0
OS core-2021.9.7

- Add-on with the issue: DuckDNS
- Add-on release with the issue: 1.14.0
- Last working add-on release (if known): <
- Operating environment (OS/Supervised): OS core-2021.9.7

Error after updating: "[supervisor.addons.addon] Add-on core_duckdns has invalid options: Missing option 'algo' in lets_encrypt in Duck DNS (core_duckdns). Got {'lets_encrypt': {'accept_terms': True, 'certfile': 'XXXXXX', 'keyfile': 'XXXXXXX'}, 'token': 'XXXXXXXXXXXX', 'domains': ['XXXXXXXXXXX'], 'aliases': [], 'seconds': 300}"

**Comment by ocso** [comment]
I fixed the problem by adding this line to the DuckDNS addon configuration:

**algo: secp384r1**

```
lets_encrypt:
  accept_terms: true
  certfile: fullchain.pem
  keyfile: privkey.pem
  algo: secp384r1
```

Looks like it is not optional.

**Comment by mcfly2283-ai** [comment]
> I fixed the problem by adding this line to the DuckDNS addon configuration:
> 
> **algo: secp384r1**
> 
> ```
> lets_encrypt:
>   accept_terms: true
>   certfile: fullchain.pem
>   keyfile: privkey.pem
>   algo: secp384r1
> ```
> 
> Looks like it is not optional.

Yeah. Spent me half an hour to to figure it out :)

**Comment by teknomar7** [comment]
Same issue and solution.  Either someone forgot to set a default in the code (effectively making this optional), or it was listed as optional in the documentation when it's not optional.

**Comment by dnedeltchev** [comment]
Fixed quickly but yeah, algo is not optional it seems. Does anyone know what algo to use? What's the difference? I put the default one for now but also tried rsa and that also works.

**Comment by teknomar7** [comment]
That's probably subjective.  You should probably just go with the default value unless you have specific problems with a client device not supporting that algo.  RSA would probably work with the most devices but would perform worse due to the key size (if you even would notice this).  But If you really want to learn more, probably google ECC vs RSA.

**Comment by dnedeltchev** [comment]
> That's probably subjective. You should probably just go with the default value unless you have specific problems with a client device not supporting that algo. RSA would probably work with the most devices but would perform worse due to the key size (if you even would notice this). But If you really want to learn more, probably google ECC vs RSA.

My concern was whether some functionality of let's encrypt or home assistant was altered depending on the algorithm selected. I will read up on that! Many thanks!

**Comment by bkbartk** [comment]
I have the same issue,
fixed it by changing the config
`lets_encrypt:
  accept_terms: true
  algo: secp384r1
  certfile: fullchain.pem
  keyfile: privkey.pem`
the documentation says it's optional, but it's now.

**Comment by Kars-de-Jong** [comment]
Isn’t it a better fix to actually make it optional? I’m sure most users would prefer a sensible default here.

**Comment by Kars-de-Jong** [comment]
> A sensible default would be the best approach IMO. If it's not optional then it should be seen as a breaking change given that the add-on fails to start without manual intervention.

Exactly, that's how I came here: I tried to upgrade the add-on, which failed because of this missing setting. Hence breaking change.

**Comment by Kars-de-Jong** [comment]
I'd still like to see this fixed. I'd be happy to provide a fix myself, just haven't got around to it yet.

**Comment by lmagyar** [comment]
Currently it is still mandatory and has default value, documentation says optional and has default value.

After 2 months somebody should decide whether it is optional or mandatory and modify the code or the documentation accordingly.

The new supervisor (https://github.com/home-assistant/supervisor/pull/3162) merges the default value into the config during update, so it starts, but this has nothing to do with the fact, that it is mandatory and the doc says optional.

**Comment by lmagyar** [comment]
Documentation and code is still contradictory, [docs.md](https://github.com/home-assistant/addons/blob/master/duckdns/DOCS.md#option-lets_encryptalgo-optional) says optional, [config.yaml](https://github.com/home-assistant/addons/blob/master/duckdns/config.yaml#L36) says mandatory.
