### ISSUE TITLE
Duckdns letsencrypt expired CA broke DoH

### ISSUE THREAD

**Issue by SamJongenelen** [home-assistant/addons#2211]
## The problem

Android private dns DoH using Adguard Home broke;
LetsEncrypt certificate from certbot uses expired CA (X3 expired 30sept2021) chain. Its a widespread issue, however, only seems to affect old clients, and surprisingly,  android feature 'private dns' (on updated android clients). 
This feature doesnt auto recognize the certificate path solution and was not expected to break.

Ive read workarounds by adjusting certbot parameters. 

`certbot renew --preferred-chain "ISRG Root X1" --force-renewal`

The addon appears to use Dehydrated and it does have the arg  ' --preferred-chain' as well - could we add this?
https://github.com/home-assistant/addons/blob/c1bc77b9ae87f56bb6a142eabe7294499ab72ec9/duckdns/data/run.sh#L40

Edit: acme issue here 
https://github.com/acmesh-official/acme.sh/issues/3723#issuecomment-932143360

## Environment

- Add-on with the issue: duckdns
- Add-on release with the issue: na
- Last working add-on release (if known): na
- Operating environment (OS/Supervised): 

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```txt

```

**Comment by SamJongenelen** [comment]
Goed news, thank you for the link

**Comment by SamJongenelen** [comment]
@chocomega did you try using the algo rsa option in the duckdns addon? My android is connected now!

**Comment by SamJongenelen** [comment]
Not stale

**Comment by jormercury** [comment]
Could you please apply the same fix as for the let's Encrypt addon?

**Comment by SamJongenelen** [comment]
Not stale

**Comment by SamJongenelen** [comment]
Not stale

**Comment by SamJongenelen** [comment]
Not stale

**Comment by frostworx** [comment]
thanks for the issue, @SamJongenelen :)

**Comment by chriss158** [comment]
Thought i'm affected by this "bug", so i've updated the duckdns addon to support the preferred chain option and also additionally support the generation of ZeroSSL/Buypass certificates as an altanative to let's encrypt.

Now it turns out, i'm not affected by this "bug". I've just misconfigured my router 🤦‍♂️

But now i have the enhanced duckdns addon ready. Maybe someone can test the let's encrypt certificate generation. Right now i cannot test this, because i'm rate limited by let's encrypt.

Here is the link to the repository: https://github.com/chriss158/home-assistant-addons
Please pay attention to the documentation, as a few options have changed

**Comment by PremiumUsername** [comment]
> You are right, but for me this works (I switched to LE addon hoping for this PR fix)

I can'r see duckdns in the list of supported providers for the LE addon. How did you make it work? How does your LE yaml config look like?

**Comment by PremiumUsername** [comment]
> i cannot test this, because i'm rate limited by let's encrypt

I'm rate limited as well, please report back if you still need help testing anything after the 168h time-out.

**Comment by SamJongenelen** [comment]
I use the duckdns addon, without cert gen, and then schedule the LE addon to start every day and generate it in the default folder /ssl/

**Comment by PremiumUsername** [comment]
> then schedule the LE addon to start every day and generate cert

This is the part I don't get. I installed the LE add-on and there is a list of Supported DNS providers in the docs for the add-on, but duckdns is not in that list. Are you using the LE add-on from the offical repo? What am I missing? Are there undocumented config options?

**Comment by PremiumUsername** [comment]
> Thought i'm affected by this "bug", so i've updated the duckdns addon to support the preferred chain option and also additionally support the generation of ZeroSSL/Buypass certificates as an altanative to let's encrypt.

The ZeroSSL functionality works like a charm. Thank you! Please consider making a pull request.

**Comment by chriss158** [comment]
> > then schedule the LE addon to start every day and generate cert
> 
> This is the part I don't get. I installed the LE add-on and there is a list of Supported DNS providers in the docs for the add-on, but duckdns is not in that list. Are you using the LE add-on from the offical repo? What am I missing? Are there undocumented config options?

As far as I know, you can only use the LE addon together with duckdns with the HTTP challenge. I.e. you have to open port 80 to renew the certificate.
With the DuckDNS addon this is not necessary. Here the certificate is renewed via the DNS challenge.

**Comment by PremiumUsername** [comment]
> LE addon together with duckdns with the HTTP challenge

Ah, mystery solved. Thanks for taking the time to clear up my confusion.

**Comment by SamJongenelen** [comment]
Yes, good point! I have an HA switch attached to the port 80 forwarding for maximum protection

**Comment by SamJongenelen** [comment]
Well i am no longer using duckdns addon tor my asl certificate, so cannot really say. Letsencrypt addon works good now though

**Comment by mdegat01** [comment]
Ok will close then 👍
