### ISSUE TITLE
Adguard takes sometimes too much time to resolve IP addresses

### ISSUE THREAD

**Issue by nicolasvila** [home-assistant/addons#2216]
## The problem

AdGuard is my home DNS server and use it on every devices on the LAN. After fresh start, it works pretty well and response time is <5ms 'I suppose when the address is in Adguard cache)
Problem is that after a few hours, days,... (it depends) Adguard response time increases dramatically and DNS solving does not work as expected anymore. Service is too slow (>4-5sec)
After restart of the addon, service is back to normal, with correct response times.

## Environment

- Add-on with the issue: Adguard
- Add-on release with the issue: 4.1.9
- Last working add-on release (if known): unknown: since problem is present since months
- Operating environment (OS/Supervised): Home Assistant Operating System (core-2021.9.7, supervisor-2021.09.6)

## Problem-relevant configuration

```yaml
ssl: false
certfile: fullchain.pem
keyfile: privkey.pem
log_level: debug
```

## Traceback/Error logs

```txt
No error in logs
```

**Comment by ludeeus** [comment]
That add-on is not provided by this repository, please open an issue with the author of it.
