### ISSUE TITLE
File Editor not starting - Internal Server Error (500) / No such file or directory

### ISSUE THREAD

**Issue by stm2roi3** [home-assistant/addons#2219]
## The problem

Unable to start File Editor core addon as the following error message is shown after trying to start the add-on:
"500 Server Error for http+docker://localhost/v1.41/containers/addon_core_configurator/json: Internal Server Error ("readlink /mnt/data/docker/overlay2/{ "version": no such file or directory")"

## Environment

- Add-on with the issue: File Editor
- Add-on release with the issue: 5.3.3
- Last working add-on release (if known): n.a.
- Operating environment (OS/Supervised): core-2021.9.7, supervisor-2021.09.6, Home Assistant OS 6.4

## Problem-relevant configuration

```yaml
```

## Traceback/Error logs

```txt
Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:109
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 22:39:23 (4 occurrences)
Last logged: 22:53:36
Failed to to call /addons/core_configurator/start - 500 Server Error for http+docker://localhost/v1.41/containers/addon_core_configurator/json: Internal Server Error ("readlink /mnt/data/docker/overlay2/{ "version": no such file or directory
```

## Additional information
I am also working with a RPi 4 at another location with the same OS, Supervisor and Core version and File Editor is working fine. 
The only differences are:
- This setup is using a RPi 3B
- This setup is on the versions from the beginning (RPi 4 was setup 2020 and upgraded to the mentioned versions)

**Comment by ludeeus** [comment]
Your docker overlay is corrupted, this is not an add-on issue.
Running `ha su repair` and doing a reboot should clear that up.

**Comment by stm2roi3** [comment]
@ludeeus thank you so much, Command and reboot solved it.  Really appreciate your support!
