### ISSUE TITLE
Can't install Mosquitto broker addOn on fresh home assistant OS installation (raspberry pi 4)

### ISSUE THREAD

**Issue by orienter112** [home-assistant/addons#2224]
## The problem
I get latest Home assistant OS 6.4 on SD card on raspberry pi 4. After first startup I set timezone and go to install Official add-on Mosquitto broker

and get error:

Can't install homeassistant/aarch64-addon-mosquitto:6.0.1: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=6.0.1&fromImage=homeassistant%2Faarch64-addon-mosquitto: Internal Server Error ("Get "https://registry-1.docker.io/v2/homeassistant/aarch64-addon-mosquitto/manifests/sha256:b392785a43c6ea5a36628fa1c165cc3ecc5df160700cafcbc6f343effaffc1d5": net/http: TLS handshake timeout")

## Environment

Home Assistant OS 6.4

- Add-on with the issue: Mosquitto broker
- Add-on release with the issue:  6.0.1
- Last working add-on release (if known): 
- Operating environment (OS/Supervised): supervisor-2021.09.6
- core-2021.9.7

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```txt

```

**Comment by MatTurac** [comment]
I have this issue too
