### ISSUE TITLE
The CEC Scanner Add-on doesn't seem to work anymore

### ISSUE THREAD

**Issue by solarmill** [home-assistant/addons#2225]
I cannot get the system to access the device.  I am using the Pulse Eight USB CEC adaptor plugged directly into a RPi4. I am in the standard Hassio environment (easy install).  Everything is up to date. 

I would really like to be able to monitor the CEC bus at all times, use Node-RED to parse the information flow, and trigger specific events.

- Add-on with the issue: CEC Scanner
- Add-on release with the issue:  2.4
- Operating environment (OS/Supervised):  OS

## Traceback/Error logs

[12:07:19] INFO: Starting CEC client scan...
opening a connection to the CEC adapter...
ERROR:   [            3567]	error opening serial port '/dev/ttyACM2': Operation not permitted
ERROR:   [            3567]	could not open a connection (try 1)
ERROR:   [            6403]	error opening serial port '/dev/ttyACM2': Operation not permitted
ERROR:   [            6403]	could not open a connection (try 2)
ERROR:   [            8293]	error opening serial port '/dev/ttyACM2': Operation not permitted
ERROR:   [            8293]	could not open a connection (try 3)
ERROR:   [            9553]	error opening serial port '/dev/ttyACM2': Operation not permitted
ERROR:   [            9553]	could not open a connection (try 4)
ERROR:   [           10558]	could not start CEC communications
unable to open the device on port /dev/ttyACM2

**Comment by kalebwd** [comment]
Same problem here.

**Comment by ms30250** [comment]
I have this issue as well.
