### ISSUE TITLE
Non-authoritative answer:

### ISSUE THREAD

**Issue by mutthunaveen** [home-assistant/addons#2229]
Hello board. 

im using dnsmasq for the first time, 
Using duck DNS i was able to successfully access my HA UI through internet (outside my network). 
Now inorder to get my single url for inside and outside my network im trying to configure dnsmasq. 

here is my config file from dnsmasq
defaults:
  - 8.8.8.8
  - 8.8.4.4
forwards: []
hosts:
  - host: myhostname.duckdns.org
    ip: 192.168.1.4
services: []

and Here is what im getting from cmd
C:\WINDOWS\system32>nslookup myhostname.duckdns.org 192.168.1.4
Server:  UnKnown
Address:  192.168.1.4

Non-authoritative answer:
Name:    org.domain.name
Address:  78.47.226.171
Aliases:  myhostname.duckdns.org.domain.name

and here is the LOG from dnsmasq
dnsmasq[210]: query[PTR] 4.1.168.192.in-addr.arpa from 192.168.1.7
dnsmasq[210]: forwarded 4.1.168.192.in-addr.arpa to 8.8.4.4
dnsmasq[210]: forwarded 4.1.168.192.in-addr.arpa to 8.8.8.8
dnsmasq[210]: query[A] myhostname.duckdns.org.domain.name from 192.168.1.7
dnsmasq[210]: cached myhostname.duckdns.org.domain.name is <CNAME>
dnsmasq[210]: cached org.domain.name is 78.47.226.171
dnsmasq[210]: query[AAAA] myhostname.duckdns.org.domain.name from 192.168.1.7
dnsmasq[210]: cached myhostname.duckdns.org.domain.name is <CNAME>
dnsmasq[210]: cached org.domain.name is NODATA-IPv6 

------ what i knew is in nslookup -> i need to get same IP as my local IP in both IP address places ------

can you please help me how to get it?

Thank you

**Comment by ludeeus** [comment]
Hi there :wave: 
This is the issue tracker to track bugs in add-ons, but this is not a bug, but rather using the software inside the add-on.
Try asking for help with that on the [forums](https://community.home-assistant.io/) or [discord](https://discord.gg/c5DvZ4e) server :+1:
