### ISSUE TITLE
Samba should use mdns for discovery

### ISSUE THREAD

**Issue by ishioni** [home-assistant/addons#2236]
## The problem

I run home-assistant in a separate vlan than most of my client devices. Because of this, it doesn't show up in Finder. The best way to fix it is to advertise samba with mdns (avahi-daemon). Some addons already do this, and samba does this natively if given the relevant config

## Environment

- Add-on with the issue: samba
- Add-on release with the issue: 9.5.1
- Last working add-on release (if known): 
- Operating environment (OS/Supervised): Home Assistant OS 6.5

## Problem-relevant configuration

No relevance

## Traceback/Error logs

None

## Additional information

The relevant option for samba is
```
multicast dns register = yes 
```
which seems to be the default. However, taking a look at the [APKBUILD for samba](https://git.alpinelinux.org/aports/tree/main/samba/APKBUILD?h=3.13-stable), it seems they're building it without avahi libs

**Comment by ananthb** [comment]
I second this feature. Would like discovery to work too.

**Comment by ludeeus** [comment]
We use issues to track issues, for feature requests please raise it on [the forums](https://community.home-assistant.io/c/feature-requests/13), thanks :+1:
