### ISSUE TITLE
deconz adding Aqara devices

### ISSUE THREAD

**Issue by mserrar** [home-assistant/addons#2237]
## The problem

Trying to add Aqara devices is not working. It seems that it's not detecting anything. The Conbee II is working fine, when plugged to my computer and used deConz app on windows, it's able to pair the Aqara devices, but not through the addon in Home Assistant.

## Environment

- Add-on with the issue:
- Add-on release with the issue: 
- Last working add-on release (if known): 
- Operating environment (OS/Supervised): 

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```txt

```

**Comment by lastdeadmouse** [comment]
Same issue with newer mccgq14lm door sensors. Looks to be patched in deconz beta, but not in latest stable yet.

**Comment by Pirol62** [comment]
I'M facing the same issue. One of my aquara motion sensors lost contact. Repairing didn't work. Tried to delet in phoscon and then pair - no success. Removed the battery and then restart deconz no success.
Then I bought a hue motion sensor - pairing doesn't work
HA 2021.10.6 - deConz 6.10.0

**Comment by Pirol62** [comment]
Hi, it is still not possible, to add a motion sensor, neither Aquara/Xiaomi nor Hue. Will there be some activity on that or do we have to wait for a deConz update?

**Comment by Je-sse** [comment]
We have to wait until the stable version 2.13.x is released.


**Release Schedule**
deCONZ beta releases are scheduled roughly once per week. After 2–3 betas a stable version is released and a new beta cycle begins. The stable release is usually published between 1st — 15th of the month.

Current Beta: v2.13.2-beta
Current Stable: v2.12.6

Next Beta: v2.13.3-beta
Next Stable: v2.13.x expected in November.
[Source](https://github.com/dresden-elektronik/deconz-rest-plugin)

**Comment by oywino** [comment]
How can I tell if what I have is the beta or the stable ?

**Comment by Pirol62** [comment]
> How can I tell if what I have is the beta or the stable ?

click into the supervisor panel and open your deConz addon. You will find it here:
![image](https://user-images.githubusercontent.com/48820003/146649342-66d344da-7cef-45d9-addb-2acae02eea94.png)

**Comment by oywino** [comment]
I'm not running Hass.io so there's no "Supervisor Panel" anywhere in my HA instance.
I run the docker version of HA.

**Comment by frenck** [comment]
> How can I tell if what I have is the beta or the stable ?

We only ship stable in the core add-ons, so that is easily answered :)


Anyways, this is not specifically an add-on issue, but an issue with the upstream software running inside the add-on. Please reports such issue with the upstream project @ dresden/deconz/phoscon. Once fixed and released stable, the add-on will update as well.

**Comment by Pirol62** [comment]
Just in order to complete this information: Flashing the firmware of the conbee2 to the latest version solves this issue.

**Comment by oywino** [comment]
And what - in your opinion - is the "latest" version?

**Comment by oywino** [comment]
Ok, thanks 👍
