### ISSUE TITLE
Tic is missing in ssh add-on

### ISSUE THREAD

**Issue by kmplngj** [home-assistant/addons#2245]
## The problem
I use Kitty as my terminal. For Kitty to work correctly on all hosts Kitty have to set his terminal info file.

I use a fish alias for this.

`kitty +kitten ssh $argv`

This opens the ssh connects and try to use tic to find the needed terminal informations and python to set it correctly. Would be great if the ssh add-on could also do this.

## Traceback/Error logs

```txt
❯ ssh homeassistant
sh: tic: not found
Connection to homeassistant closed.
```

**Comment by ludeeus** [comment]
We use issues to track issues, for feature requests please raise it on [the forums](https://community.home-assistant.io/c/feature-requests/13), thanks :+1:

**Comment by nschloe** [comment]
I have exactly the same issue. Is there a feature request for this yet?

**Comment by nschloe** [comment]
Well, [it is now](https://community.home-assistant.io/t/sh-tic-not-found/502279).
