### ISSUE TITLE
Check Home Assistant configuration - checking new version on reverse proxy

### ISSUE THREAD

**Issue by cableghost** [home-assistant/addons#2256]
This is regarding the plugin... Check Home Assistant configuration

Not sure about this... It's been awhile since I last updated HA, and since then, HA has made it a requirement to use the 'use_x_forwarded_for' option if using a reverse proxy. Well, I know my existing version of HA has a reverse proxy, and it does not have this option enabled/added, however, this plugin indicated my system was configured properly for upgrade.

I realize this may be beyond the scope of the plugin, however, I've already discovered... If you don't have this option enabled/added, you lose access to HA. I literally had to use my disk backup and replace my HA VM.

**Comment by ludeeus** [comment]
This is not something the add-on would be capable of catching.
