### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by TimyIsCool** [home-assistant/addons#2265]
### Describe the issue you are experiencing

Im not 100% sure if this is a bug or not

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] file-structure.sh: executing... 
[cont-init.d] file-structure.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[21:58:41] INFO: Selected DNS Provider: dns-cloudflare
[21:58:41] INFO: Use propagation seconds: 60
[21:58:42] WARNING: Use CloudFlare global key (not recommended!)
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator dns-cloudflare, Installer None
Cert not yet due for renewal
Keeping the existing certificate
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Certificate not yet due for renewal; no action taken.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### Which add-on are you reporting an issue with?

Let's Encrypt

### What is the version of the add-on?

4.11.0

### Steps to reproduce the issue

Fill out all fields

In the lets encrypt config

email: *Redacted*
domains:
  - timyg.org
certfile: fullchain.pem
keyfile: privkey.pem
challenge: dns
dns:
  provider: dns-cloudflare
  cloudflare_email: *Redacted*
  cloudflare_api_key: *Redacted*

In the home assistant config file

cloudflare:
  email: *Redacted*
  api_key: *Redacted*
  zone: timyg.org
  records:
    - *Redacted*

### Anything in the Supervisor logs that might be useful for us?

```txt
Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:109
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 22:09:41 (1 occurrences)
Last logged: 22:09:41

Failed to to call /addons/core_letsencrypt/stats - Container addon_core_letsencrypt is not running


Logger: aiohttp.server
Source: /usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py:393
First occurred: 22:09:44 (1 occurrences)
Last logged: 22:09:44

Unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1183, in _sendfile_fallback
    read = await self.run_in_executor(None, file.readinto, view)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 485, in start
    resp, reset = await task
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 440, in _handle_request
    reset = await self.finish_response(request, resp, start_time)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 591, in finish_response
    await prepare_meth(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_fileresponse.py", line 241, in prepare
    return await self._sendfile(request, fobj, offset, count)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_fileresponse.py", line 96, in _sendfile
    await loop.sendfile(transport, fobj, offset, count)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1162, in sendfile
    return await self._sendfile_fallback(transport, file,
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1192, in _sendfile_fallback
    await proto.restore()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 263, in restore
    self._transport.resume_reading()
  File "/usr/local/lib/python3.9/asyncio/sslproto.py", line 343, in resume_reading
    self._ssl_protocol._transport.resume_reading()
AttributeError: 'NoneType' object has no attribute 'resume_reading'
```

**Comment by ludeeus** [comment]
> Im not 100% sure if this is a bug or not

It's not :)

"Certificate not yet due for renewal; no action taken." this means there is nothing to do at this point, your cert is still valid.

**Comment by TimyIsCool** [comment]
> > Im not 100% sure if this is a bug or not
> 
> It's not :)
> 
> "Certificate not yet due for renewal; no action taken." this means there is nothing to do at this point, your cert is still valid.

how would i fix it?

**Comment by ludeeus** [comment]
There is nothing to fix.
Give your certificate time to near it's expiration and then run the add-on again
