### ISSUE TITLE
Update Let's Encrypt not working

### ISSUE THREAD

**Issue by mathiaslehmann** [home-assistant/addons#2286]
### Describe the issue you are experiencing

When updating Let's Encrypt, I get the following error.

![image](https://user-images.githubusercontent.com/16978467/143246280-0c55a435-50fe-4624-b51c-2b14011fad01.png)

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Let's Encrypt

### What is the version of the add-on?

4.12.0

**Comment by randarth** [comment]
Got same issue trying to update 4.11 to 4.12 on latest HA.

![image](https://user-images.githubusercontent.com/54189925/143259745-b7168a80-28a7-401f-b10c-fd1e0b5ecb62.png)

**Comment by pickonedev** [comment]
Same problem

**Comment by mydevice** [comment]
Same issue 👍 


Failed to install add-on
Can't install homeassistant/aarch64-addon-letsencrypt:4.12.0: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=4.12.0&fromImage=homeassistant%2Faarch64-addon-letsencrypt: Not Found ("manifest for homeassistant/aarch64-addon-letsencrypt:4.12.0 not found: manifest unknown: manifest unknown")

**Comment by serlinGi** [comment]
update of my situation:
I started the update excluding the backup option of the add-on and this time it seems to have gone through without problems.
not tried to start add-on it because now my certificates have a long expiration date.

**Comment by RiderCrazy** [comment]
> update of my situation: I started the update excluding the backup option of the add-on and this time it seems to have gone through without problems. not tried to start add-on it because now my certificates have a long expiration date.

Same here, works after backup option is disabled.

FYI, when I've searched for this error, I saw there's the same problem for Z-Wave JS.

**Comment by pickonedev** [comment]
I have disabled the backup option, but I still have the same error...

**Comment by mathiaslehmann** [comment]
Hello
The update worked later. So it's all good.

**Comment by pickonedev** [comment]
Yes, they solved the problem without announcing :-)
