### ISSUE TITLE
BlitzWolf SHP15 devices no energy with Deconz addon

### ISSUE THREAD

**Issue by QuadNL** [home-assistant/addons#2293]
### Describe the issue you are experiencing

With the Deconz addon in HA the Blitzwolf SHP15 devices are currently not able to being monitored with energy and consumption.
While the support currently has been build in with the Deconz by dresden image. 
https://github.com/dresden-elektronik/deconz-rest-plugin/releases
https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/v2.13.1-beta

![image](https://user-images.githubusercontent.com/66387274/144407761-0bd2cea2-9baf-4769-9024-741d79b40403.png)

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

deCONZ

### What is the version of the add-on?

6.10.0

### Steps to reproduce the issue

Adding the plug to Phoscon but no energy available in HA.

**Comment by JCSCatena** [comment]
Same problem. 

Please, update the deconz addon. I read the problem solved in 2.13.1 deconz version. 

Actually the deconz 6.10.0 addon version incorporate the deconz 2.12.6.  

A greeting.

**Comment by bcutter** [comment]
> Same problem. 
> 
> 
> 
> Please, update the deconz addon. I read the problem solved in 2.13.1 deconz version. 
> 
> 
> 
> Actually the deconz 6.10.0 addon version incorporate the deconz 2.12.6.  
> 
> 
> 
> A greeting.

Anybody knows the process of deCONZ addon being updated to latest deCONZ stable version?

Because my monitoring just told me there's finally a new stable out there (containing important fixes I wait for months):

![image](https://user-images.githubusercontent.com/13799156/146657258-7e548408-fe93-4150-adf2-984272ee7d7d.jpeg)

**Comment by frenck** [comment]
This is not an issue specific to the add-on. If fixed upstream, it will be part of the upcoming add-on release.
