### ISSUE TITLE
Allow update of deCONZ to install pre-release versions 

### ISSUE THREAD

**Issue by mforrester1975** [home-assistant/addons#2296]
### Describe the issue you are experiencing

I have new devices which can not be installed but are supported by the new pre-release version of the product.

There should be an option to install stable or beta channels so that newer devices can be integrated before the new device method is implemented.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

deCONZ

### What is the version of the add-on?

6.10.0

### Steps to reproduce the issue

1 - Add new Zigbee item
2 - Appears with no vendor in map but not added correctly in Phoscon
3 - Device is unknown in HA

### Additional information

The ability to update to beta would help as the release times are lengthy.

**Comment by frenck** [comment]
This cannot be offered as an option, as add-ons are pre-build. We are not planning on releasing unstable versions. 

Nevertheless, thank you for your suggestion 👍
