### ISSUE TITLE
Can't connect to HA Samba service

### ISSUE THREAD

**Issue by aglproyectos** [home-assistant/addons#2299]
### Describe the issue you are experiencing

Following a HA system update, the samba service becomes unreachable from a remote client. Log follows 👍 
....
Added user antonio.
[cont-init.d] samba.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
nmbd version 4.13.8 started.
Copyright Andrew Tridgell and the Samba Team 1992-2020
Registered MSG_REQ_POOL_USAGE
Registered MSG_REQ_DMALLOC_MARK and LOG_CHANGED
Registered MSG_REQ_POOL_USAGE
added interface eth0 ip=192.168.1.71 bcast=192.168.1.255 netmask=255.255.255.0
making subnet name:192.168.1.71 Broadcast address:192.168.1.255 Subnet mask:255.255.255.0
making subnet name:UNICAST_SUBNET Broadcast address:0.0.0.0 Subnet mask:0.0.0.0
making subnet name:REMOTE_BROADCAST_SUBNET Broadcast address:0.0.0.0 Subnet mask:0.0.0.0
daemon_ready: daemon 'nmbd' finished starting up and ready to serve connections
smbd version 4.13.8 started.
Copyright Andrew Tridgell and the Samba Team 1992-2020
Registered MSG_REQ_POOL_USAGE
Registered MSG_REQ_DMALLOC_MARK and LOG_CHANGED
Processing section "[config]"
Processing section "[addons]"
Processing section "[ssl]"
Processing section "[share]"
Processing section "[backup]"
Processing section "[media]"
added interface eth0 ip=192.168.1.71 bcast=192.168.1.255 netmask=255.255.255.0
INFO: Profiling support unavailable in this build.
Registered MSG_REQ_POOL_USAGE
No builtin backend found, trying to load plugin
Registered MSG_REQ_POOL_USAGE
Registered MSG_REQ_POOL_USAGE
daemon_ready: daemon 'smbd' finished starting up and ready to serve connections
waiting for connections
Registered MSG_REQ_POOL_USAGE
netbios connect: name1=GARGUEHOME     0x20 name2=GARGUE-HP      0x0
netbios connect: local=garguehome remote=gargue-hp, name type = 0
Registered MSG_REQ_POOL_USAGE
check_ntlm_password:  Authentication for user [antonio.garzonlopez@outlook.es] -> [antonio.garzonlopez@outlook.es] FAILED with error NT_STATUS_NO_SUCH_USER, authoritative=1
===============================================================
INTERNAL ERROR: Signal 11: Segmentation fault in pid 290 (4.13.8)
If you are running a recent Samba version, and if you think this problem is not yet fixed in the latest versions, please consider reporting this bug, see https://wiki.samba.org/index.php/Bug_Reporting
===============================================================
PANIC (pid 290): Signal 11: Segmentation fault in 4.13.8
unable to produce a stack trace on this platform
coredump is handled by helper binary specified at /proc/sys/kernel/core_pattern
Registered MSG_REQ_POOL_USAGE
check_ntlm_password:  Authentication for user [antonio.garzonlopez@outlook.es] -> [antonio.garzonlopez@outlook.es] FAILED with error NT_STATUS_NO_SUCH_USER, authoritative=1
===============================================================
INTERNAL ERROR: Signal 11: Segmentation fault in pid 291 (4.13.8)
If you are running a recent Samba version, and if you think this problem is not yet fixed in the latest versions, please consider reporting this bug, see https://wiki.samba.org/index.php/Bug_Reporting
===============================================================
PANIC (pid 291): Signal 11: Segmentation fault in 4.13.8
unable to produce a stack trace on this platform
coredump is handled by helper binary specified at /proc/sys/kernel/core_pattern
.
.
--- Keeps repeating the error trace

It can be noted that the first log states: Added user antonio while in the connection attempts it checks for another username (antonio.garzonlopez@outlook.es) that is actually one of my mailboxes but it is not used at all in my Home Assistant installation.

Whatever the name is the result keeps always the same. Exception made whe I try to use antonio.garzonlopez@outlook.es ...
In such case the log is:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] samba.sh: executing... 
[21:55:39] INFO: Using hostname=GarGueHome interface=eth0
addgroup: illegal character with code 64 at position 19
[cont-init.d] samba.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

...
And nothing happens.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Samba share

### What is the version of the add-on?

9.5.1

### Steps to reproduce the issue

1.Install
2.Add user whatever the name
3.
...

### Anything in the add-on logs that might be useful for us?

```txt
Already included in the description
```

**Comment by aglproyectos** [comment]
Sorry for the big characters in the description I should be using paste not formatted text so the result...

**Comment by mondrasar** [comment]
i had the same problem. Seems to be a problem caused by win11.

In your log is the message:

> check_ntlm_password: Authentication for user [antonio.garzonlopez@outlook.es] -> [antonio.garzonlopez@outlook.es] FAILED with error NT_STATUS_NO_SUCH_USER, authoritative=1

Could it be, that the email-adress is your windows-email?

I tried to add a new network drive to win11 and choose other login details (using the user and passwort from the samba-configuration). Then the samba log says:

> check_ntlm_password:  authentication for user [username] -> [username] -> [username] succeeded

*username* replaces my used Username.

in Windows i get an error message, thats not possible to connect to the network drive, but after that I'm able to connect with the explorer using \\\\ip-adress with the samba-share.

**Comment by alorle** [comment]
> i had the same problem. Seems to be a problem caused by win11.
> 
> In your log is the message:
> 
> > check_ntlm_password: Authentication for user [[antonio.garzonlopez@outlook.es](mailto:antonio.garzonlopez@outlook.es)] -> [[antonio.garzonlopez@outlook.es](mailto:antonio.garzonlopez@outlook.es)] FAILED with error NT_STATUS_NO_SUCH_USER, authoritative=1
> 
> Could it be, that the email-adress is your windows-email?
> 
> I tried to add a new network drive to win11 and choose other login details (using the user and passwort from the samba-configuration). Then the samba log says:
> 
> > check_ntlm_password:  authentication for user [username] -> [username] -> [username] succeeded
> 
> _username_ replaces my used Username.
> 
> in Windows i get an error message, thats not possible to connect to the network drive, but after that I'm able to connect with the explorer using \\ip-adress with the samba-share.

Setting a custom username/password worked for me. Thanks!!!

**Comment by magiva** [comment]
this is still an issue in 9.5.1

**Comment by EstebanDugueperoux2** [comment]
Hello,

I have had the same issue, it seems '@' character is not supported, then it miss a validation of username supported characters.
