### ISSUE TITLE
file editor add-on doesn't start

### ISSUE THREAD

**Issue by rayxxxxx** [home-assistant/addons#2304]
### Describe the issue you are experiencing

When I try to run File Editor add-on I've got this message:Image homeassistant/armv7-addon-configurator:5.3.3 does not exist for addon_core_configurator
The File Editor add-on doesn't start.
My home assistant runs on raspberry pi 2 model b.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

File editor

### What is the version of the add-on?

5.3.3

### Steps to reproduce the issue

1.install file editor add-on 
2.run file editor

**Comment by Hartsord** [comment]
I'm also having this issue, running on RPi 2 B, with HASSIO in a Docker container. Tried updating to 5.3.3, still having the issue. No info in log:

> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
> [s6-init] ensuring user provided files have correct perms...exited 0.
> [fix-attrs.d] applying ownership & permissions fixes...
> [fix-attrs.d] done.
> [cont-init.d] executing container initialization scripts...
> [cont-init.d] done.
> [services.d] starting services
> [services.d] done.
> INFO:2021-12-16 20:41:51,829:hass_configurator.configurator:Starting server
> INFO:2021-12-16 20:41:51,832:hass_configurator.configurator:Listening on: http://0.0.0.0:8099
> [cont-finish.d] executing container finish scripts...
> [cont-finish.d] done.
> [s6-finish] waiting for services.
> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
> [s6-init] ensuring user provided files have correct perms...exited 0.
> [fix-attrs.d] applying ownership & permissions fixes...
> [fix-attrs.d] done.
> [cont-init.d] executing container initialization scripts...
> [cont-init.d] done.
> [services.d] starting services
> [services.d] done.
> INFO:2021-12-20 11:32:36,158:hass_configurator.configurator:Starting server
> INFO:2021-12-20 11:32:36,195:hass_configurator.configurator:Listening on: http://0.0.0.0:8099
