### ISSUE TITLE
deconz_event is not triggered in Home assistant anymore

### ISSUE THREAD

**Issue by joggs** [home-assistant/addons#2311]
### Describe the issue you are experiencing

the deconz_event is not triggeded in home assistant anymore.
The buttons, triggers and dimmers in deconz are healthy and works find in the deconz ui and in phoscon, but no events are triggered when listening for deconz_event.
I am not sure for how long the problem has existed as existing buttons seems to work fine

There are more people with the problem here : https://community.home-assistant.io/t/everything-works-but-cant-see-any-deconz-event/207031/21

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### Which add-on are you reporting an issue with?

deCONZ

### What is the version of the add-on?

the desc of where to find it is outdated and cannot find it. i have the current stable version as of 21-12-18

### Steps to reproduce the issue

1. run home assistant 2021.12.3 (could be for other versions as well)
2. listen for events, for example by going to developer tools -> listen to events and listen to deconz_event
3. The expected behavior is that events should start popping up on the webpage when you push a working button etc, but nothing happens and no trigger is triggered 
...

### Anything in the Supervisor logs that might be useful for us?

```txt
No errors in the system log, even in verbose/debug logging for deconz. No signs of the button events in the log
```

### Anything in the add-on logs that might be useful for us?

```txt
No errors in the deconz log, even in verbose/debug logging for deconz. No signs of the button events in the log
```

### Additional information

You can see a bit down in the following thread of people that have the same problem and what they have tried
https://community.home-assistant.io/t/everything-works-but-cant-see-any-deconz-event/207031/9

**Comment by joggs** [comment]
Deleting the devices and adding them again to deconz gives the same problem. re-installing the deconz addon gives the same problem

**Comment by bcutter** [comment]
When did this issue start to appear for you?

Was it introduced with updating to a specific HA version?

**Comment by joggs** [comment]
Unfortunately I do not know as everything that has already been configured in my deconz environment since long ago has been working very well.
Today I wanted to add another switch to deconz and also add some automations to it in home assistant, I noticed this problem, so it is possible that this problem has existed for a while, as I haven't added or modified any deconz devices for months.
Very strange that existing buttons still work, but are not triggering any "deconz_event"-events.
Hopefully it is repoducable for someone else which hopefully gives us more info about the problem

**Comment by fi-sch** [comment]
It is working properly on my side. Tested a minute ago in Dev Tools, but I have a few automations based on deconz_event running multiple times a day, and they are working properly each time they should.

HA Core 2021.12.3

**Comment by jeffphilly** [comment]
Can i also confirm, tested on my end and it is working properly. I re-added an old device and it worked in addition to the existing 

core-2021.12.3

**Comment by joggs** [comment]
when listening for deconz_event on the developer page, no events show up at all, no matter old or newly added devices, but the existing event listeners seems to trigger anyway, thats why I havent noticed this earlier. So the problem appears when adding new devices now, as they does not seem to trigger any events.
Strange indeed. I was hoping the other guys from the forum I posted could assist with more info. I'll bump that forum and hope for some more feedback.

**Comment by Hrupeksc** [comment]
Hi,

have the same issue but I just add the first scene button which is working on events. All other zigbee devices are working fine. I trying to add lonsonho scene switch. Will buy IKEA trådfri remote control to check if the mentioned scene switch is not faulty.

**Comment by fi-sch** [comment]
@joggs Isn't it this issue: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5585 ? What kind of Zigbee device are you adding?

**Comment by joggs** [comment]
I had problems with both ikea symfoni and a classic ikea dimmer. I am suspecting something could be wrong with my conbee II. I actually get deconz_events for a couple of buttons when going through them all, so I think I have to take a closer look at the deconz core. So with that said, it looks like my problems lies elsewhere

**Comment by j0dan** [comment]
Same problem here. Tried running deconz on a raspberry PI and Windows. The DeConz app shows the button press, but HA has never had a deconz_event for any zigbee item including switches or outlets.

My Aqara Wireless Mini Switch seems to have an entity (random name), but with no entities (it may not support battery level).

**Comment by Mimiix** [comment]
I've just updated to the latest deconz version and HA version. I've noticed the same. I've checked the websocket and that seems to provide events:
![image](https://user-images.githubusercontent.com/43333120/146897338-8e2dd056-7799-4b9b-94d6-d634a46ed1d6.png)


I've checked HA, but HA does receive events in terms of Curtain position and data from power measurement sockets. The events just don't show up on the event listener but it does update the valeus on the devices. Not sure what's going on there. 

I'm updating from 12.2 to 12.4 now and see if that makes any changes.

**Comment by Hrupek** [comment]
Hi,
Can you tell me if the HA plugin configuration is proper on below screen?

![image](https://user-images.githubusercontent.com/54175343/146902953-dc94ffb6-be6a-48cc-acbb-3874b7f9fdcc.png)
Is it required to put the port numbers in Column "Host"


I also see the switch event in websocet API:

![image](https://user-images.githubusercontent.com/54175343/146905956-83abae48-dd70-481d-99e8-efe5a7f250b6.png)

Not sure if this is something wrong as this is my first switch added to deconz, but I am not able to link switch in deconz it is not available:
![image](https://user-images.githubusercontent.com/54175343/146906574-291f9143-2cee-4c4e-b8ad-8ea5baa13ba8.png)
Even if I clinck on Link switch I got:
![image](https://user-images.githubusercontent.com/54175343/146906665-ebe91ac9-6b8a-4f7d-a8f6-0a72a1e4d509.png)

The switch is connected to deconz:
![image](https://user-images.githubusercontent.com/54175343/146906770-468a1ef2-6422-41b6-a3eb-81c37ed90003.png)

Last thing I have plenty of active listeners in Develiper tools but there is no deconz_event on it, only if I start it manually then it show up on the list is it normal?

![image](https://user-images.githubusercontent.com/54175343/146909116-f182313b-e48f-40b7-b298-63172d25f4ef.png)

**Comment by Mimiix** [comment]
> Hi, Can you tell me if the HA plugin configuration is proper on below screen?
> 
> ![image](https://user-images.githubusercontent.com/54175343/146902953-dc94ffb6-be6a-48cc-acbb-3874b7f9fdcc.png) Is it required to put the port numbers in Column "Host"
> 
> I also see the switch event in websocet API:
> 
> ![image](https://user-images.githubusercontent.com/54175343/146905956-83abae48-dd70-481d-99e8-efe5a7f250b6.png)
> 
> Not sure if this is something wrong as this is my first switch added to deconz, but I am not able to link switch in deconz it is not available: ![image](https://user-images.githubusercontent.com/54175343/146906574-291f9143-2cee-4c4e-b8ad-8ea5baa13ba8.png) Even if I clinck on Link switch I got: ![image](https://user-images.githubusercontent.com/54175343/146906665-ebe91ac9-6b8a-4f7d-a8f6-0a72a1e4d509.png)
> 
> The switch is connected to deconz: ![image](https://user-images.githubusercontent.com/54175343/146906770-468a1ef2-6422-41b6-a3eb-81c37ed90003.png)
> 
> Last thing I have plenty of active listeners in Develiper tools but there is no deconz_event on it, only if I start it manually then it show up on the list is it normal?
> 
> ![image](https://user-images.githubusercontent.com/54175343/146909116-f182313b-e48f-40b7-b298-63172d25f4ef.png)

seems to be fine. What i did notice, is that if i listen to ALL events (putting * in the listener) they do show up.

Haven't tested behaviour yet.

**Comment by Hrupek** [comment]
In my case even if I listening all (*) events I do not see the Switch events.

**Comment by Hrupek** [comment]
I just realize that I have in home xiaomi wireless switch, I connect it to deconz and I can see the events in HA. So in my case the switch itself was the problem. I would like to make it work anyway. Can anybody tell me how I can ask to add support for my Lonsonho Switch?

**Comment by Mimiix** [comment]
Just came home to test. I do receive deconz_event for buttons:
![image](https://user-images.githubusercontent.com/43333120/146923708-4af7a38a-60bd-458c-9649-8d0483b1f205.png)


I am running deCONZ on a native raspbian installation.

**Comment by eddomak** [comment]
I just so happened to try my first integration of the Ikea Tradfri on/off this week as it was the first time I had tried to use Node Red to detect events as a trigger I didn't even know which topic to listen to. After 2hrs I gave up and used the Phoscon automation instead.

Now that I have found this thread, I am 100% sure I had no typos in the event topic "deconz event" when I first tried and it was not showing the events on button press. Then I tried "*" as per above and could see the events. Then I typed in "deconz_event" again and now the events are showing. I still cannot see any "deconz_event" when using MQTT explorer...

**Comment by eddomak** [comment]
Update from me. I gave up on DeConz, took the plunge and and went to Zigbee2MQTT. I am not trying to troll here, but must say that Zigbee2MQTT was a lot easier to setup and configure than DeConz, and works with MQTT a lot easier too.

**Comment by Grynneman** [comment]
Hi, new to this topic, but I'm having the same issue with deconz events not appearing in the dev listener.
Things to note : 
I've been running HA on an Intel NUC for a couple of years.  Swapped to a Conbee II running Deconz approximately 18 months ago with no issue.
Sequence of events to troubleshoot issue.

A couple of days ago I added an Aqara vibration sensor to the network.  Developer Tools > States showed Battery and Binary Sensor for vibration detected were created.  Attributes around tilt/orientation/etc were also created and showing data.

I wanted to see the data being produced by in Developer Tools > Events by listening to deconz_event*, but no events were appearing. 

To double check, I used node-red with deconz palette added to attach to the deconz gateway, and then listened for all events.
These were all appearing successfully, for lights, switches and the newly installed vibration sensor.

Going back to HA, I enabled logging debug logging for deconz in configuration.yaml.  Again, nothing was appearing.

Now, to be clear, all deconz devices are working in HA, it is just that deconz_event is not displaying the details on the Developer Tools>Events page.  Whether the issue goes deeper than that I don't know (I suspect it may, as nothing is appearing in the logs either)

**Comment by Grynneman** [comment]
> Hi, new to this topic, but I'm having the same issue with deconz events not appearing in the dev listener. Things to note : I've been running HA on an Intel NUC for a couple of years. Swapped to a Conbee II running Deconz approximately 18 months ago with no issue. Sequence of events to troubleshoot issue.
> 
> A couple of days ago I added an Aqara vibration sensor to the network. Developer Tools > States showed Battery and Binary Sensor for vibration detected were created. Attributes around tilt/orientation/etc were also created and showing data.
> 
> I wanted to see the data being produced by in Developer Tools > Events by listening to deconz_event*, but no events were appearing.
> 
> To double check, I used node-red with deconz palette added to attach to the deconz gateway, and then listened for all events. These were all appearing successfully, for lights, switches and the newly installed vibration sensor.
> 
> Going back to HA, I enabled logging debug logging for deconz in configuration.yaml. Again, nothing was appearing.
> 
> Now, to be clear, all deconz devices are working in HA, it is just that deconz_event is not displaying the details on the Developer Tools>Events page. Whether the issue goes deeper than that I don't know (I suspect it may, as nothing is appearing in the logs either)

Addendum to this.  I've just tried to fire a deconz_event using the Developer Tools>Events Page, it did not appear in the listener.

**Comment by leolobato** [comment]
FYI, this seems to still be an issue. Did a fresh Home Assistant install using RaspBee, added one Tradfri Switch and `deconz_event` is not showing on The Developer Tools event listener.

**Comment by joggs** [comment]
Yep. The problem has appeared for me again

**Comment by oywino** [comment]
I am currently on HA Core 2022.12.8 and there are no events coming from deConz. But the REST-API shows significant activity.

**Comment by Kallb123** [comment]
Apologies if this is slightly different. But my switches have stopped working today. I can see the events coming through to Home Assistant, but the automation just aren't triggered. Home assistant shows a press as a "short press", I wonder if that has changed? I'm just using the default switch automation UI but the triggers don't fire.

**Comment by oywino** [comment]
> I can see the events coming through to Home Assistant, but the automation just aren't triggered. 
Are you saying that enabling the event listener in the Developer Page for `deconz_event` is actually working for you ?

**Comment by Kallb123** [comment]
> Are you saying that enabling the event listener in the Developer Page for deconz_event is actually working for you ?

That is working as well. I can see my events coming through in the developer event page. I can also see the device firing events in the logbook... But then those same events are not triggering the automations that they should. They were working until this morning. Same automations, same buttons. The only thing that may have changed are software updates, maybe deconz updated?

**Comment by Mimiix** [comment]
I have the same after a reboot of home assistant.

Try disabling and re enabling the automation again , see if they work again.

**Comment by oywino** [comment]
Strange! So @Kallb123 problem is the opposite of my problem!  My deConz event triggered automations work perfect, but I cannot see any events when listening for `deconz_event` in the developer page. It would be nice to know if these issues are being investigated or not. Just talking about it isn't bringing us forward, it seems.

**Comment by aquadrat2217** [comment]
I have the same problem, deConz works fine, but i can't see any events when listening for deconz_event. What can I do?

**Comment by gromitn** [comment]
> > Are you saying that enabling the event listener in the Developer Page for deconz_event is actually working for you ?
> 
> That is working as well. I can see my events coming through in the developer event page. I can also see the device firing events in the logbook... But then those same events are not triggering the automations that they should. They were working until this morning. Same automations, same buttons. The only thing that may have changed are software updates, maybe deconz updated?

Hi, I have the exact same problem - did you find a solution? 
Thanks!

**Comment by Kallb123** [comment]
A good old turn it off and on again seemed to work, or in combination with software updates.

**Comment by michelcve** [comment]
I had the same problem after moving my docker container to a different host. I could turn off a light, but the updated status was not updated in home assistant.

Turns out that deconz uses a websocket for that (you can even configure what port number that is), and I was not exposing that port.

As soon as I did, homeassistant worked as before, and the status of the lights etc were updated in homeassistant as well.

Hopefully this might help someone in the future :-).
