### ISSUE TITLE
Update to deCONZ 2.13.4 in order to make IKEA updated firmware work again

### ISSUE THREAD

**Issue by pfefferCode** [home-assistant/addons#2313]
### Describe the issue you are experiencing

Please Update the add-on to deCONZ 2.13.4 in order to make IKEA updated firmware work again

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

deCONZ

### What is the version of the add-on?

 6.10.0

### Steps to reproduce the issue

1.
2.
3.
...

**Comment by justindekeizer** [comment]
I updated 5 of my 69 GU10's last weekend and now they keep going off and on again whenever they are ON at interval of about 5min. Could this be related? They keep rejoining the Zigbee network at those moments;

`23:48:30:953 DeviceAnnce of LightNode: 0xec1bbdfffe2111fe Permit Join: 0
23:48:31:237 ZCL got data for node=0xCBC6, cl=0x0006, at=0x0000, status=0x00, type=0x10
23:48:31:390 ZCL attribute report 0xEC1BBDFFFE2111FE for cluster: 0x0300, ep: 0x01, frame control: 0x08, mfcode: 0x0000`

**Comment by MiguelCosta** [comment]
I think after this change, deConz doesn't work.

Issue: https://github.com/home-assistant/core/issues/62388

**Comment by MiguelCosta** [comment]
hi @pfefferCode 

maybe we should revert this change beauce if we read the official documentation from dersden-elektronik, I think HA doesn't support the new deConz versions 

https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Update-deCONZ-manually

>This method cannot be used for the Home-Assistant add-on and no current workaround is known. This also includes the button in Phoscon within the addon. 

Issue: https://github.com/home-assistant/addons/issues/2317

**Comment by vbaros** [comment]
I can confirm. I had to go back to previous backup. Nothing worked. Phoscon button was read only.
