### ISSUE TITLE
SSH access not possible anymore

### ISSUE THREAD

**Issue by alve89** [home-assistant/addons#2314]
### Describe the issue you are experiencing

This issue is about the SSH-Addon.

I'm trying to SSH into my RPi4 with HassOS, authentication method is `public key`. 

This is my configuration:
```
init_commands: []
packages: []
share_sessions: false
ssh:
  allow_agent_forwarding: false
  allow_remote_port_forwarding: false
  allow_tcp_forwarding: false
  authorized_keys:
    - >-
    ssh-rsa
    AAAAB3NzaC1yc...Q==
    rsa-key007-210719-homeassistant_arbeitslaptop
    - >-
    ssh-rsa
    AAAAB3NzaC1yc...w==
    rsa-key006-211118-homeassistant_shelly_iphone_ipad
    - >-
    ssh-rsa
    AAAAB3NzaC1yc...w8=
    rsa-key014-211205-homeassistant_macbookair
  compatibility_mode: false
  password: ''
  sftp: false
  username: myloginname
zsh: true
log_level: info
```

It worked properly until:
1. Either one of the (core) updates 2021.12.x
2. or segregating my LANs and removing public accessibilty and added VPN access.

But about 2.:
- I kept everything HA-related as it was: HA is still on 192.168.1.2
- My VPN points also to 192.168.1.1 and gets an IP by DHCP so I'm in the same network (and I can properly use the HA frontend).
- Even tests with re-enabling the public access from internet via DDNS on port 42xxx which is forwared to HA port 22 failed
- So: Since everything still is as it was before my network change, I think it could be related to the updates.

Next weird thing: It still works properly with the "default" SSH add-on (https://github.com/home-assistant/addons/tree/master/ssh)! Both from public and with VPN - one more point that my network changes shouldn't be the cause. The keys are identical (in the used app it's the same key file, in the configuration I copied the `ssh-rsa` key today to make sure it's the same as in the working add-on).

This is the **output from this add-on**:
![image](https://user-images.githubusercontent.com/11487054/146736313-c8e3d846-36ec-4c09-bf08-d82d03977385.png)

with the logs:
![image](https://user-images.githubusercontent.com/11487054/146736411-18bfec4a-1869-41ae-a63e-f9e29028c163.png)

And this is the **output from the working add-on**:
![image](https://user-images.githubusercontent.com/11487054/146736452-a83a92e4-64ef-42b4-b946-fc1a54c0ffa9.png)

with the logs:
![image](https://user-images.githubusercontent.com/11487054/146736481-e9935536-044e-477d-ae13-0aad48924d2d.png)

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Terminal & SSH

### What is the version of the add-on?

10.0.0

### Steps to reproduce the issue

Actually I use it as I did before.

1. Add `ssh-rsa` key to `authorized_keys` in add-on's configuration
2. Select key file to authenticate with (in Putty (on Windows) or in Shelly on iOS
3. Start SSH connection to DDNS (ha.mydomain.tld) 
4. Confirm fingerprint and enter login-name
5. Usually enter the password for the keyfile then, but now I don't reach this point 

### Anything in the Supervisor logs that might be useful for us?

```txt
Nothing
```

### Anything in the add-on logs that might be useful for us?

```txt
See screensho
```

### Additional information

Re-installing the add-on didn't bring back the success.

**Comment by jhmoon2000** [comment]
Somehow, the updated version 10.0.0 does not accept 'ssh-rsa' method.  Other public key algorithms like ecdsa-sha2-nistp256 works fine. 'RSA SHA256' which was generated from Mac also works fine. I had to change my key pair. 
Maybe, you can regenerate your auth keys with other algorithm then SSH will work again.

**Comment by frenck** [comment]
You are posting an issue report in an incorrect issue tracker.
The add-on you are reporting for, is the Community version of the SSH add-on, however, this is the issue tracker of the Core version.

Please check the add-on documentation of your add-on for information on where to report issues.

Thanks 👍
