### ISSUE TITLE
Updated IKEA firmware blinks lights

### ISSUE THREAD

**Issue by justindekeizer** [home-assistant/addons#2315]
### Describe the issue you are experiencing

Issue: whenever the lights with the new firmware are ON they switch OFF for about 5 sec and ON again after that period every 5-6 min approx. 
The Deconz logs shows them as rejoining the network at that moment.

Restarted everything (including the powercyling the bulbs).
Rejoined the bulbs manually in the Deconz network.

Issue persist. Haven't updated the other 64 lights pending resolution.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

deCONZ

### What is the version of the add-on?

6.10.0

### Steps to reproduce the issue

1. Updated 5 of my 69 GU10 IKEA bulbs to the latest firmware by just enabling Deconz OTA
2. Switch on the lights (or groups that contain them)

### Anything in the Supervisor logs that might be useful for us?

```txt
Nothing in HA triggers the actions of the bubls, 0 changes and/or logs in HA itself about the state of the lights. Deconz log shows the rejoin of the lights.
```

### Anything in the add-on logs that might be useful for us?

```txt
23:48:30:953 DeviceAnnce of LightNode: 0xec1bbdfffe2111fe Permit Join: 0 
23:48:31:237 ZCL got data for node=0xCBC6, cl=0x0006, at=0x0000, status=0x00, type=0x10 
23:48:31:390 ZCL attribute report 0xEC1BBDFFFE2111FE for cluster: 0x0300, ep: 0x01, frame control: 0x08, mfcode: 0x0000
```

**Comment by justindekeizer** [comment]
Might this be related? : [https://github.com/home-assistant/addons/issues/2313](Issue 2313)

**Comment by justindekeizer** [comment]
Deconz was updated to **version 6.11.1.**

Issue still here but the logs show new information, might this be an bulb internal isssue after the firmware updates? Note all 5 bulbs show the same logs.

`08:40:45:623 Turn on light 0xEC1BBDFFFE6CA093 on again with former brightness after powercycle
08:40:45:623 DeviceAnnce of LightNode: 0xec1bbdfffe6ca093 Permit Join: 0
08:40:45:723 ZCL got data for node=0x6A58, cl=0x0006, at=0x0000, status=0x00, type=0x10
08:40:46:023 ZCL attribute report 0xEC1BBDFFFE6CA093 for cluster: 0x0300, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
08:40:46:700 0xEC1BBDFFFE6CA093 error APSDE-DATA.confirm: 0xE9 on task
08:40:46:712 	0xEC1BBDFFFE6CA093 force poll (2)`

**Comment by frenck** [comment]
The log you are pasting @justindekeizer; is a log from deCONZ itself. Please report those with dresden/deconz/phoscon; as this is not something the add-on can do anything about.

Add-on wrap existing software, in this case; deCONZ. If the issue gets fixed upstream, it will be included in the next release after that.
