### ISSUE TITLE
Deconz Issue on 6.11.1 No Motion detection

### ISSUE THREAD

**Issue by rnagler01** [home-assistant/addons#2323]
### Describe the issue you are experiencing

I have several motion Sensors
Osram Smart +
Sonoff Motion
and the only states i get are battery and temperature.
I already repaired all sensors, same issue.

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### Which add-on are you reporting an issue with?

deCONZ

### What is the version of the add-on?

6.11.1

### Steps to reproduce the issue

1.Pair Osram oder Sonoff motion sensors
2. sucessfully paired 
3.No motion detection
...

### Additional information

In Deconz i see both sensor types got the same vendor ID 0x104e

**Comment by frenck** [comment]
Hi there @rnagler01 👋 

Thanks for your report, unfortunately, that is not related to the add-on, but to the software running inside the add-on. Please report your issue with deCONZ/dresden/Phoscon. Once they fix and address the issue in a new release, the add-on will upgrade to it as well.

Thanks! 👍 

../Frenck
