### ISSUE TITLE
 STYRBAR Events 1002 and 2002 are missing with all others being registered

### ISSUE THREAD

**Issue by Kugelfang666** [home-assistant/addons#2332]
### Describe the issue you are experiencing

Event 1002 and 2002 are missing using a IKEA STYRBAR. All other events are showing as expected

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

deCONZ

### What is the version of the add-on?

6.11.1

### Steps to reproduce the issue

Connect a IKEA  STYRBAR to the Zigbee network
listen to deconz_events

### Anything in the Supervisor logs that might be useful for us?

```txt
no
```

### Anything in the add-on logs that might be useful for us?

```txt
no
```

### Additional information

the up and down buttons show up registering short press, long press and long press release events.
the dim+ and dim- buttons only show long press and long press release events. The shot press events 1002 and 2002 are missing

**Comment by thecinnis** [comment]
I have the same problem, when I pair the device the events are sent to deconz but after a few minutes it stops sending events 1002 and 2002 while sending 1001 + 1003 and 2001 + 2003.
I tried to pair the STYRBAR also choosing OTHER as venor but nothing has changed
