### ISSUE TITLE
Please delete

### ISSUE THREAD

**Issue by heffneil** [home-assistant/addons#2334]

**Comment by frenck** [comment]
You could also say you've found a solution (and maybe even share that for a possible future reader) and close the issue instead...

**Comment by heffneil** [comment]
No solution found, letsencrypt challenges http vis port 80 only they say on their site I discovered.

**Comment by frenck** [comment]
Sure, but still you could just say that and close the issue yourself, instead of editing it as you did.

**Comment by heffneil** [comment]
got it
