### ISSUE TITLE
Clients can connect to Mosquitto broker with no username or password.

### ISSUE THREAD

**Issue by jef-pearlman** [home-assistant/addons#2337]
### Describe the issue you are experiencing

I recently discovered that (it appears) I can log into Mosquitto broker on port 1883 with no username or password and it will grant full access.  I've searched around and asked on Discord and I don't _think_ this is the expected behavior, but my apologies if I just missed something.

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### Which add-on are you reporting an issue with?

Mosquitto broker

### What is the version of the add-on?

6.0.1

### Steps to reproduce the issue

Short version here; more detail below:
1. Set mqtt client to IP address of home assistant server and port 1883.  Do not enter a username or password.
2. Connect and subscribe to or publish topics.
3. If no data is received, disconnect and go to 2.

I have been using Mosquitto broker for quite a while for a few things--mostly Tasmota devices right now.  I recently was testing IOT Link and watching in MQTT Explorer to see what data came through when data started appearing even though I had only entered an IP address--not a username or password--into the IOT Link configuration.  My usual MQTT Explorer profile has a username/password, but I created a new profile with no username/password and it succesfully connected and showed me the entire retained topic tree.

It will reject an attempt to log in with a bad username or a bad password with a "Not authorized" error. But a correct username/password or _no_ username/password will let me in.

It is inconsistent whether I data when I connect with no username/password.  If I repeatedly disconnect and connect, it will always connect successfully, but only about half the time will it get the retained topics.  If it does, it will keep updating them as new ones get published.  If it does not, the tree will stay empty forever.

I uninstalled and reinstalled the Mosquitto broker addon and left the default configuration and the issue immediately returned.

### Anything in the Supervisor logs that might be useful for us?

```txt
22-01-03 20:55:29 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
22-01-03 21:23:59 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'FAKE'
22-01-03 21:24:00 WARNING (MainThread) [supervisor.auth] Unauthorized login for 'FAKE'
22-01-03 21:24:06 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'REAL'
22-01-03 21:24:06 WARNING (MainThread) [supervisor.auth] Unauthorized login for 'REAL'
22-01-03 21:25:31 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token

That was me testing logins with a FAKE username and a REAL username but bad passwords.  Nothing appears in the log for successful logins with either a real username/password or no username/password.
```

### Anything in the add-on logs that might be useful for us?

```txt
The logs show different things; first with username/password, second without:

1641270003: New connection from xxx.xxx.xxx.xxx on port 1883.
{"result": "ok", "data": {}}1641270003: New client connected from xxx.xxx.xxx.xxx as mqtt-explorer-58f6fbef (p2, c1, k60, u'USERNAME').
1641270005: Client mqtt-explorer-58f6fbef disconnected.
1641270009: New connection from xxx.xxx.xxx.xxx on port 1883.
1641270009: New client connected from xxx.xxx.xxx.xxx as mqtt-explorer-75402a08 (p2, c1, k60).
1641270014: Client mqtt-explorer-75402a08 disconnected.
1641270016: New connection from xxx.xxx.xxx.xxx on port 1883.
```

### Additional information

Please let me know if there's addition information I can provide, or if this is normal and I've just missed something.  Thanks!

**Comment by jef-pearlman** [comment]
I foolishly only searched for open issues, and just came across #2091, which seems like it might be the same issue.  Apologies for creating a duplicate.  But it seems like people were still experiencing it as of three months ago in that issue, and I still am today.  Is it possible to reopen one?  I'll leave this open but feel free to close it if that's what makes sense.  Thanks!

**Comment by grimmaldus** [comment]
I can only join to this I'm experiencing same issue and I've found it out the same way as you did @jef-pearlman. It's good to see that pull request is on the way.

**Comment by b3nj1** [comment]
I'm not sure if the PR will be merged or not before going stale. I posted a way to disable anonymous logins via config overrides with the current add-on version here: https://github.com/home-assistant/addons/issues/2091#issuecomment-1011809944
