### ISSUE TITLE
File Editor loads very slowly and no longer shows tree directory

### ISSUE THREAD

**Issue by gvssr** [home-assistant/addons#2340]
### Describe the issue you are experiencing

Seemingly from one day to the other File editor takes a long time to load and no longer loads the directory tree. I've tried uninstalling, reinstalling and rebooting the host but it stays the same.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

File editor

### What is the version of the add-on?

5.3.3

### Steps to reproduce the issue

1. Open File Editor
2. Wait for it to load (takes a few seconds)
3. Open the directory tree

### Anything in the Supervisor logs that might be useful for us?

```txt
22-01-06 10:12:59 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Server disconnected
22-01-06 11:03:24 WARNING (SyncWorker_3) [supervisor.docker.interface] Can't grep logs from homeassistant/aarch64-addon-configurator: 404 Client Error for http+docker://localhost/v1.41/containers/ed2e32cc73ec9117ad5aa6a5af97147879fe5b7021d66fad3ed41dd343a2df65/json: Not Found ("No such container: ed2e32cc73ec9117ad5aa6a5af97147879fe5b7021d66fad3ed41dd343a2df65")
```

### Anything in the add-on logs that might be useful for us?

```
WARNING:2022-01-06 11:05:24,088:hass_configurator.configurator:Exception getting release
WARNING:2022-01-06 11:05:24,090:hass_configurator.configurator:<urlopen error [Errno -3] Try again>
```

### Additional information

Screen when loading File Editor:
![image](https://user-images.githubusercontent.com/61377476/148368225-53112782-67be-4a28-a96d-8e943ef1b561.png)

Directory tree:
![image](https://user-images.githubusercontent.com/61377476/148368284-aefaaec0-193d-4f69-b2e4-ee086eb080e2.png)

**Comment by gvssr** [comment]
Turns out this was because git was enabled

**Comment by Jychek** [comment]
Mr. dieugab, how did u disabled git?
