### ISSUE TITLE
File Editor/Configurator SSH Keys

### ISSUE THREAD

**Issue by dunxd** [home-assistant/addons#2346]
### Describe the issue you are experiencing

I am unable to git push from the File Editor.  git push when ssh into the hassio box works fine.

The docs for file editor say:

> Option: ssh_keys (required)
> A list of filenames containing SSH private keys. These can be used to allow for access to remote git repositories.

I specified this, but get an error that the SSH key is not found. I'm using an SSH key stored under /root/.ssh which I guess the addon cannot access.

**Is this a bug in the code, or the documentation not being clear where to store SSH keys so the addon can access them?**

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

File editor

### What is the version of the add-on?

5.3.3

### Steps to reproduce the issue

1. Add path to ssh file on the ssh_keys line
2. Save and restart addon
3. Still unable to git push
...

### Anything in the add-on logs that might be useful for us?

```txt
[14:14:31] INFO: Starting SSH agent
Agent pid 213
[14:14:31] ERROR: SSH key file "/root/.ssh/id_rsa" not found
```

**Comment by frederico-betting** [comment]
I think a found a possible solution for this issue.
I copied the SSH keys to the path `/config/.ssh/` and it seems it worked fine.

So, the steps:

1. Created the directory `.ssh` under `/config`
2. Changed the permission of this folder `.ssh` (`chmod 700 .ssh`)
3. Copied the files `id_rsa` and `id_rsa.pub` to `/config/.ssh/`
4. Updated the File Editor/Configurator configuration with the following:
   ```yaml
     ssh_keys:
       - /config/.ssh/id_rsa
   ```
5. Restarted the service

From the logs:
```shell
[16:51:06] INFO: Starting SSH agent
Agent pid 215
[16:51:06] INFO: Adding SSH private key file "/config/.ssh/id_rsa"
```

**Note: Just don't forget to ignore the folder `.ssh` in your `.gitignore` file.**

**Comment by dunxd** [comment]
Tried that - still get the same error. 

I also set the permissions for the id_rsa file to 600. The id_rsa.pub file shouldn't be needed but I copied it anyway and set its permissions to 655.

Anyway to make the logging more verbose?

**Comment by dunxd** [comment]
Yes - git push origin to github works fine with no errors from command line on the home assistant box - just not from the git push menu item in file editor.

**Comment by frederico-betting** [comment]
What's the message you've got?

**Comment by dunxd** [comment]
`WARNING:2022-01-18 14:40:49,961:hass_configurator.configurator:{'error': True, 'message': "Cmd('git') failed due to: exit code(128)\n  cmdline: git push --porcelain origin\n  stderr: 'fatal: Could not read from remote repository.'", 'path': '/config'}`

**Comment by dunxd** [comment]
Fixed it - I had set the path to `/root/.ssh/id_rsa` file in the git config in an attempt to get this working.  Now I have removed that line from the git config file, it works as it should  :-)

Thanks for assistance.

**Comment by frederico-betting** [comment]
That's nice. Good to know that it's working for you. :) You're welcome.

>Yes - it would be nice if git add * was an option for the entire folder, rather than needing to do it per file. And for this addon's documentation to include full details about how to configure the ssh file would be really helpful.

Agreed!!!
