### ISSUE TITLE
Deconz not showing all attributes

### ISSUE THREAD

**Issue by criscaru** [home-assistant/addons#2349]
### Describe the issue you are experiencing

Hi,
not sure I'm opening this in thre right place, apologies if i'm wrong.

I added a develco AirQuality to Conbee II. Home assistant is showing three measures: temp, hum, airquality.

AirQuality seems to be a text measure only (excellent, good,moderate, poor) but if I call the api there seems to be also an airquality numeric measure (airqualityppm):
{
    "config": {
        "battery": 100,
        "on": true,
        "reachable": true
    },
    "ep": 38,
    "etag": "<redacted>",
    "lastannounced": "2022-01-14T15:59:39Z",
    "lastseen": "2022-01-15T08:01Z",
    "manufacturername": "Develco Products A/S",
    "modelid": "AQSZB-110",
    "name": "AirQuality 28",
    "state": {
        "airquality": "excellent",
        "airqualityppb": 45,
        "lastupdated": "2022-01-15T07:59:49.000"
    },
    "swversion": "20211025 10:59",
    "type": "ZHAAirQuality",
    "uniqueid": "00:15:bc:00:36:00:11:1c-26-fc03"
} 

Is it right that measure does not appear in HA ? Is there a way to export this also? It could be usefult to show air quality graphs.

Thanks,
C!

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

deCONZ

### What is the version of the add-on?

6.11.1

### Steps to reproduce the issue

Compare data shown by HA UI with REST API answer

**Comment by banditdk** [comment]
Same for aqara Air Quality sensor, "airqualityppb" is not exposed in HA :
"ep": 1,
        "etag": "336e44a6d22e3b0ec19a87cd558786eb",
        "lastannounced": "2021-12-29T16:53:42Z",
        "lastseen": "2022-01-02T16:52Z",
        "manufacturername": "LUMI",
        "modelid": "lumi.airmonitor.acn01",
        "name": "AirQuality 68",
        "state": {
            "airquality": "good",
            "airqualityppb": 76,
            "lastupdated": "2022-01-02T16:52:33.431"
        },
        "swversion": "2020",
        "type": "ZHAAirQuality",
        "uniqueid": "54:ef:44:10:00:10:65:46-01-000c"

**Comment by frenck** [comment]
Thank you for reaching out. This is not an add-on related issue, but a feature request to show additional sensors/attributes in the Home Assistant integration.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

**Comment by criscaru** [comment]
Sure Franck, I'll do, thanks.

C!
