### ISSUE TITLE
Changing user's name is not reflected in add on

### ISSUE THREAD

**Issue by JeffreyFalgout** [home-assistant/addons#2356]
### Describe the issue you are experiencing

I created a Home Assistant user to authorize calls to the mosquitto broker. I expected that changing the user's name would force me to change the username in the MQTT client code that publishes/subscribes to the broker. I've observed that the username doesn't need to be updated. In fact, the mosquitto broker doesn't recognize the new username at all.

I guess the silver lining here is that I've observed that if you change the password in the Home Assistant UI, you do indeed need to change the password in the MQTT client code as well, even though you don't have to change the username.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### Which add-on are you reporting an issue with?

Mosquitto broker

### What is the version of the add-on?

6.0.1

### Steps to reproduce the issue

1. Install mosquitto broker
2. Create a new user in the Home Assistant UI so that you can authorize connections to the mosquitto broker
3. Change that user's name in Home Assistant UI
4. Attempt to publish MQTT messages with the new username and observe authorization errors.

### Anything in the Supervisor logs that might be useful for us?

```txt
22-01-24 22:39:13 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for '<new username, new password>'
22-01-24 22:39:13 WARNING (MainThread) [supervisor.auth] Unauthorized login for '<new username, new password>'
22-01-24 22:39:26 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for '<old username, old password>'
22-01-24 22:39:27 WARNING (MainThread) [supervisor.auth] Unauthorized login for '<old username, old password>'
22-01-24 22:39:33 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for '<old username, new password>'
22-01-24 22:39:34 INFO (MainThread) [supervisor.auth] Successful login for '<old username, new password>'
```

### Anything in the add-on logs that might be useful for us?

```txt
Not really, more of the same:

1643089153: New connection from 192.168.3.228 on port 8883.
401: Unauthorized1643089154: Socket error on client <unknown>, disconnecting.
1643089154: New connection from 192.168.3.228 on port 8883.
1643089154: Socket error on client <unknown>, disconnecting.
1643089166: New connection from 192.168.3.228 on port 8883.
401: Unauthorized1643089166: Socket error on client <unknown>, disconnecting.
1643089166: New connection from 192.168.3.228 on port 8883.
1643089167: Socket error on client <unknown>, disconnecting.
1643089173: New connection from 192.168.3.228 on port 8883.
{"result": "ok", "data": {}}1643089173: New client connected from 192.168.3.228 as <old username> (p2, c1, k30, u'<old username>').
```

**Comment by ludeeus** [comment]
You can not change a user's username, only the name.
If you want a different username, you need to delete the previous user and create a new one with the desired username.
