### ISSUE TITLE
Problem with 2 domains (duck-dns + custom) certificate generation

### ISSUE THREAD

**Issue by cedsib** [home-assistant/addons#2365]
### Describe the issue you are experiencing

Hello !

I have a strange problem with DuckDNS :
- when I run with the config below I have an error (the MY-CUSTOM-DOMAIN challenge fails).
- when I run it in two times : first only the subdomain (that works), then MY-CUSTOM-DOMAINn it works.

Here is my config :

<img width="395" alt="Capture d’écran 2022-01-27 à 21 38 27" src="https://user-images.githubusercontent.com/55406881/151439833-50cbb528-3419-485d-a5f1-7ab818c0ef53.png">
 
It's boring because when I forget to renew it, all my certificates finally expire :-(

Anyone of you already had this issue ? And you know how to solve it ?

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Duck DNS

### What is the version of the add-on?

1.14.0

### Steps to reproduce the issue

1. Renew 2 certificates (fails)
2. Renew subdomain certificate (success)
3. Renew custom domain certificate (success)
...

### Anything in the Supervisor logs that might be useful for us?

```txt
nope :-(
```

**Comment by aejay-rs** [comment]
So, I'm also having issues today, due to my cert expiring. I was going to open a separate issue, but I also have a custom domain configured alongside my main one, so I'm worried it might be related. Here's a sanitized version of what I have in my logs:
```
 + Checking domain name(s) of existing cert... unchanged.
 + Checking expire date of existing cert...
 + Valid till Jan 27 17:45:18 2022 GMT (Less than 30 days). Renewing!
 + Signing domains...
 + Generating private key...
 + Generating signing request...
 + Requesting new certificate order from CA...
 + Received 2 authorizations URLs from the CA
 + Handling authorization for MY-SUBDOMAIN.duckdns.org
 + Handling authorization for MY-CUSTOM-DOMAIN
 + 2 pending challenge(s)
 + Deploying challenge tokens...
OKOK + Responding to challenge for MY-SUBDOMAIN.duckdns.org authorization...
 + Cleaning challenge tokens...
OKOK + Challenge validation has failed :(
ERROR: Challenge is invalid! (returned: invalid) (result: 
  ["type"]	"dns-01"
  ["status"]	"invalid"
  ["error","type"]	"urn:ietf:params:acme:error:unauthorized"
  ["error","detail"]	"Incorrect TXT record \"GENERATED-VERIFY-VALUE\" found at _acme-challenge.MY-SUBDOMAIN.duckdns.org"
  ["error","status"]	403
  ["error"]	{"type":"urn:ietf:params:acme:error:unauthorized","detail":"Incorrect TXT record \"GENERATED-VERIFY-VALUE\" found at _acme-challenge.MY-SUBDOMAIN.duckdns.org","status":403}
  ["url"]	"https://acme-v02.api.letsencrypt.org/acme/chall-v3/MY-SPECIFIC-INSTANCE-ERROR"
  ["token"]	"A_TOKEN_WAS_HERE"
  ["validated"]	"2022-01-27T21:00:45Z"
)
```

Where `GENERATED-VERIFY-VALUE` is the same TXT record value in both places mentioned.

I haven't changed my configuration since the last time I renewed my certs, and it seemed to work fine before. Then again... maybe I've done an addon update since then that could have introduced an issue?

**Comment by shadsnz** [comment]
I also had exactly this same issue today.

**Comment by aejay-rs** [comment]
> I also had exactly this same issue today.  Did anyone find it stopped you being able to log into HA via web browser? I kept getting "Unable to connect to Home Assistant." after entering my username/password/2fa.  I found I could only access it using Firefox.
> 

Yeah, that's how I discovered my issue, too. The issue stems from the web UI being a progressive web app. The HTML required to pull up the page is cached in your regular browser, but when it goes to actually try to hit the API it refuses to negotiate TLS because of the expired cert.

You might be able to get your normal browser to start displaying (but with security warnings) if you clear cache for the site before reloading it.

Still not sure what to do to get this resolved, though.

**Comment by aejay-rs** [comment]
I notice that the addons are using dehydrated to negotiate certs with letsencrypt... could [this troubleshooting guideline](https://github.com/dehydrated-io/dehydrated/blob/master/docs/troubleshooting.md#dns-invalid-challenge-since-dehydrated-060--why-are-dns-challenges-deployed-first-and-verified-later) be relevant to the issue we're seeing?

LetsEncrypt and ACME clients are all new concepts to me, so I hope I'm not introducing red herrings. Just trying to do what I can to help diagnose.

**Comment by aejay-rs** [comment]
Not sure how I managed to overlook it when searching through issues yesterday, but I believe this is a duplicate of #1869. Going to try to use some of the workaround steps mentioned there for my setup

**Comment by cwbeta** [comment]
Nope Mr Bot, it's still buggered.

**Comment by cedsib** [comment]
yes I can confirm that it's still bugged.

Here are the logs for the problem (now that my certificate is now soon expiring).

As I said earlier :
- if I run the certificate generation with this config file, **I get an error** `OKOK + Challenge validation has failed :(`
- if I run it in 2 steps (first the `MY-DUCK-SUBDOMAIN.duckdns.org`, then `MY-ALIAS-DOMAIN` ), it **runs perfectly.**

The trouble it, I can't automate the 2 steps generation :(


### CONFIGURATION FILE

```
lets_encrypt:
  accept_terms: true
  certfile: fullchain.pem
  keyfile: privkey.pem
  algo: secp384r1
token: MY-TOKEN
domains:
  - MY-DUCK-SUBDOMAIN.duckdns.org
aliases:
  - domain: MY-ALIAS-DOMAIN
    alias: MY-DUCK-SUBDOMAIN.duckdns.org
seconds: 300
```


### EXECUTION LOGS

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
# INFO: Using main config file /data/workdir/config
+ Account already registered!
[08:19:09] INFO: OK
MY-IP
NOCHANGE
[08:19:10] INFO: Renew certificate for domains: MY-DUCK-SUBDOMAIN.duckdns.org and aliases: 
MY-ALIAS-DOMAIN
# INFO: Using main config file /data/workdir/config
Processing MY-ALIAS-DOMAIN with alternative names: MY-DUCK-SUBDOMAIN.duckdns.org
 + Checking domain name(s) of existing cert... unchanged.
 + Checking expire date of existing cert...
 + Valid till Apr 26 20:45:47 2022 GMT (Less than 30 days). Renewing!
 + Signing domains...
 + Generating private key...
 + Generating signing request...
 + Requesting new certificate order from CA...
 + Received 2 authorizations URLs from the CA
 + Handling authorization for MY-DUCK-SUBDOMAIN.duckdns.org
 + Handling authorization for MY-ALIAS-DOMAIN
 + 2 pending challenge(s)
 + Deploying challenge tokens...
OKOK + Responding to challenge for MY-DUCK-SUBDOMAIN.duckdns.org authorization...
 + Cleaning challenge tokens...
OKOK + Challenge validation has failed :(
ERROR: Challenge is invalid! (returned: invalid) (result: ["type"]	"dns-01"
["status"]	"invalid"
["error","type"]	"urn:ietf:params:acme:error:unauthorized"
["error","detail"]	"Incorrect TXT record \"l85ABxSY9hYxErA51rQkRztfCHVk3R6zMc8sGpTEWeQ\" found at _acme-challenge.MY-DUCK-SUBDOMAIN.duckdns.org"
["error","status"]	403
["error"]	{"type":"urn:ietf:params:acme:error:unauthorized","detail":"Incorrect TXT record \"l85ABxSY9hYxErA51rQkRztfCHVk3R6zMc8sGpTEWeQ\" found at _acme-challenge.MY-DUCK-SUBDOMAIN.duckdns.org","status":403}
["url"]	"https://acme-v02.api.letsencrypt.org/acme/chall-v3/92196492480/t4hUOg"
["token"]	"P4xOxZnHYC6i7PAWnT9YQ9WRROsjxGS3srikPRF8rZU"
["validated"]	"2022-03-28T06:19:25Z")
```
