### ISSUE TITLE
Cannot upgrade to Z-Wave JS 0.1.52

### ISSUE THREAD

**Issue by shauntarves** [home-assistant/addons#2370]
### Describe the issue you are experiencing

After upgrading Z-Wave JS to 0.1.52, the add-on cannot be started. HA error log shows:
```
Failed to start the Z-Wave JS add-on: Image homeassistant/armv7-addon-zwave_js:0.1.52 does not exist for addon_core_zwave_js
```

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Z-Wave JS

### What is the version of the add-on?

0.1.52

### Steps to reproduce the issue

1. Update Z-Wave JS to 0.1.52 and you will see a message like `Retrying setup None` in the UI
2. Looking at HA logs shows more descriptive `Failed to to call /addons/core_zwave_js/start - Image homeassistant/armv7-addon-zwave_js:0.1.52 does not exist for addon_core_zwave_js`

### Anything in the Supervisor logs that might be useful for us?

```txt
Failed to to call /addons/core_zwave_js/start - Image homeassistant/armv7-addon-zwave_js:0.1.52 does not exist for addon_core_zwave_js
3:57:44 PM – (ERROR) Home Assistant Supervisor
Failed to start the Z-Wave JS add-on: Image homeassistant/armv7-addon-zwave_js:0.1.52 does not exist for addon_core_zwave_js
3:37:43 PM – (ERROR) Z-Wave JS - message first occurred at 3:37:03 PM and shows up 2 times
```
```


### Anything in the add-on logs that might be useful for us?

```txt
Add-on log is empty.
```

**Comment by MartinHjelmare** [comment]
Can you try with the Home Assistant CLI to run:
```
ha supervisor repair
```

**Comment by WesCossick** [comment]
In case anyone else experiences this same issue, running `ha supervisor repair` followed by a Home Assistant reboot fixed the issue in my case.
