### ISSUE TITLE
Can't install File Editor add on

### ISSUE THREAD

**Issue by blacknell** [home-assistant/addons#2375]
### The problem

In 2021.12.1, this add on worked fine.

After upgrading to 2022.2.0, i was repeatedly getting a Gateway 502 error when opening the UI. Eventually, I uninstalled it.

Today I tried to reinstall and got this error during installation
```
Can't install homeassistant/aarch64-addon-configurator:5.3.3: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=5.3.3&fromImage=homeassistant%2Faarch64-addon-configurator: Internal Server Error ("Get "https://registry-1.docker.io/v2/": net/http: TLS handshake timeout")
```

**It's worth noting** that I had a horrendous time upgrading to 2022.2 - the UI hour glass went on forever. I was very patient (IMHO) but it failed. I couldn't do an `ha host shutdown` either so ended on cutting the power (which I hate)

### What version of Home Assistant Core has the issue?

2022.2.0

### What was the last working version of Home Assistant Core?

2021.12.1

### What type of installation are you running?

Home Assistant OS

### Anything in the logs that might be useful for us?

```txt
2022-02-04 12:16:36 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /addons/core_configurator/install - Can't install homeassistant/aarch64-addon-configurator:5.3.3: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=5.3.3&fromImage=homeassistant%2Faarch64-addon-configurator: Internal Server Error ("Get "https://registry-1.docker.io/v2/": net/http: TLS handshake timeout")
```

**Comment by blacknell** [comment]
Relates [home-assistant/core #65658](https://github.com/home-assistant/core/issues/65658)

**Comment by jphansendk** [comment]
I'm having the same issue.. anyone found a solution?

Core 2024.12.4
Supervisor 2024.12.0
Operating System 14.1
Frontend 20241127.8

Raspberry Pi 5
