### ISSUE TITLE
check-config can't find Pyhton 3.9.

### ISSUE THREAD

**Issue by KentGitIvar** [home-assistant/addons#2377]
### Describe the issue you are experiencing

From check-config logfile:
[13:22:26] ERROR: See the output below for more details.
Testing configuration at /tmp/config
Fatal error while loading config: [Errno 2] No such file or directory: '/usr/local/lib/python3.9/site-packages/multidict-6.0.2.dist-info/METADATA'
Failed config
  General Errors: 
    - [Errno 2] No such file or directory: '/usr/local/lib/python3.9/site-packages/multidict-6.0.2.dist-info/METADATA'

Successful config (partial)
[13:22:26] INFO: The full output has been written to /share/check_config.txt
[cont-finish.d] executing container finish scripts..

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Check Home Assistant configuration

### What is the version of the add-on?

 3.9.0

### Steps to reproduce the issue

1. Start Check Home Assistant configuration and look in log.
2.
3.
...

**Comment by Kisty** [comment]
Closing since this is a core issue https://github.com/home-assistant/core/issues/66904
