### ISSUE TITLE
Security settings for Home Assistant Add-on: NGINX Home Assistant SSL proxy

### ISSUE THREAD

**Issue by JohnnyM84** [home-assistant/addons#2379]
### Describe the issue you are experiencing

Hello, 

I was checking the nginx proxy for some security settings and saw that this can maybe better, i tested it with a test site (https://internet.nl).
If i look for recomended settings i came accross these settings:

add_header Strict-Transport-Security 'max-age=31536000; includeSubDomains; preload';
add_header X-Frame-Options "SAMEORIGIN";
add_header X-Content-Type-Options nosniff;
add_header Content-Security-Policy "default-src 'self';";
add_header Referrer-Policy "strict-origin";

ssl_protocols TLSv1.2 TLSv1.3;
ssl_ciphers TLS13-CHACHA20-POLY1305-SHA256:TLS13-AES-256-GCM-SHA384:TLS13-AES-128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-RSA-AES128-GCM-SHA256; 
ssl_prefer_server_ciphers on;

Maybe this can be added?

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### Which add-on are you reporting an issue with?

NGINX Home Assistant SSL proxy

### What is the version of the add-on?

3.1.1

### Steps to reproduce the issue

-

**Comment by JohnnyM84** [comment]
@frenck what do you think about these settings?

**Comment by Tallyrald** [comment]
I'd like to have security headers on NGINX as well. Personally I like to use the [Snyk tool](https://snyk.io/website-scanner/) to check whether a website is secure or not. Adding the basic security headers is a must nowadays, it would be nice to have them on HA too.
Here are some settings I've used before and worked well for me:
```conf
http {
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header Strict-Transport-Security "max-age=31536000" always;
    map $sent_http_content_type $content_security_policy {
        ~*text/(html|javascript)|application/pdf|xml "default-src 'self'; base-uri 'none'; form-action 'self'; frame-ancestors 'none'; object-src 'none'; upgrade-insecure-requests";
    }
    add_header X-Content-Type-Options nosniff;
}
```

The Content Security Policy is a bit tricky, because it needs to be custom-tailored to the specific needs to the site, so I'm not sure if this exact statement would work with HA, but I feel it would be quite important to set up.

**Comment by ljurk** [comment]
Hi guys, I also think this is very important and found the solution. You can create custom headers via the customize feature:
I change custmize.active to `true` and created a file `/share/nginx_proxy_default.conf` with the following format:
```
add_header my-header "just checking" always;
```
Now its just a matter to find the right headers to set, the headers @JohnnyM84 mentioned are to strict and home-assistant isn't working anymore. I'll be back if i find the right headers to set:)

**Comment by ljurk** [comment]
A little addition: for grafana to work `'unsafe-eval'` have to be added to `script-src` like this: `script-src 'self' 'unsafe-inline' 'unsafe-eval'`

If something is not working, it's a good idea to check the Console-Tab under Developer-Tools in your Browser(`F12`). Often you can find an error message, telling you which header is blocking the current site.

**Comment by JohnnyM84** [comment]
Thanks for finding this i also added the ssl part to it because the order of the chipers is not good in the original configuration.
I have now this:
`
ssl_protocols TLSv1.2 TLSv1.3;
ssl_ciphers TLS13-CHACHA20-POLY1305-SHA256:TLS13-AES-256-GCM-SHA384:TLS13-AES-128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-RSA-AES128-GCM-SHA256;
ssl_prefer_server_ciphers on;
add_header X-Frame-Options "SAMEORIGIN";
add_header X-Content-Type-Options nosniff;
add_header X-XSS-Protection "1; mode=block";
add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; connect-src 'self' wss://YOUR_DOMAIN/;" always;
add_header Referrer-Policy "strict-origin";
`

**Comment by JohnnyM84** [comment]
After a while Some plug-ins and icons are not loading because of the Content-Security-Policy (CSP) in the IOS app :(

**Comment by ksga** [comment]
> Here is my `/share/nginx_proxy_default.conf`:
> 
> ```
> add_header X-Frame-Options "SAMEORIGIN";
> add_header X-Content-Type-Options nosniff;
> add_header X-XSS-Protection "1; mode=block";
> add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; connect-src 'self' wss://YOURHOSTNAME.duckdns.org/;" always;
> add_header Referrer-Policy "strict-origin";
> ```
> 
> homeassistant is working and I got a B+ at the [observatory](https://observatory.mozilla.org). It's not getting better, since `unsafe-inline` is a necessary `style-src` and `script-src`. I stumbled across the `connect-src` part here: [home-assistant/iOS#106 (comment)](https://github.com/home-assistant/iOS/issues/106#issuecomment-401988573) and it's necessary for the app to work, you have to change your hostname.

Actually you can get an A+ at the observatory by moving 'unsafe-inline' from script-src to script-src-elem. I added a few extras to sort maps and getting the Lovalece font as well:
```
add_header X-Frame-Options "SAMEORIGIN";
add_header X-Content-Type-Options nosniff;
add_header X-XSS-Protection "1; mode=block";
add_header Content-Security-Policy "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; connect-src 'self' wss://ha.kennethandersen.com/; font-src 'self' data:; img-src 'self' data: https://basemaps.cartocdn.com/ https://brands.home-assistant.io/; script-src-elem 'self' 'unsafe-inline';" always;
add_header Referrer-Policy "strict-origin";
```

**Comment by merquel** [comment]
> > Here is my `/share/nginx_proxy_default.conf`:
> > ```
> > add_header X-Frame-Options "SAMEORIGIN";
> > add_header X-Content-Type-Options nosniff;
> > add_header X-XSS-Protection "1; mode=block";
> > add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; connect-src 'self' wss://YOURHOSTNAME.duckdns.org/;" always;
> > add_header Referrer-Policy "strict-origin";
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > homeassistant is working and I got a B+ at the [observatory](https://observatory.mozilla.org). It's not getting better, since `unsafe-inline` is a necessary `style-src` and `script-src`. I stumbled across the `connect-src` part here: [home-assistant/iOS#106 (comment)](https://github.com/home-assistant/iOS/issues/106#issuecomment-401988573) and it's necessary for the app to work, you have to change your hostname.
> 
> Actually you can get an A+ at the observatory by moving 'unsafe-inline' from script-src to script-src-elem. I added a few extras to sort maps and getting the Lovalece font as well:
> 
> ```
> add_header X-Frame-Options "SAMEORIGIN";
> add_header X-Content-Type-Options nosniff;
> add_header X-XSS-Protection "1; mode=block";
> add_header Content-Security-Policy "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; connect-src 'self' wss://ha.kennethandersen.com/; font-src 'self' data:; img-src 'self' data: https://basemaps.cartocdn.com/ https://brands.home-assistant.io/; script-src-elem 'self' 'unsafe-inline';" always;
> add_header Referrer-Policy "strict-origin";
> ```

Just wanted to give you a heads up that you wrote out your domain name in plain text in case you weren't aware :)

**Comment by tannisroot** [comment]
> After a while Some plug-ins and icons are not loading because of the Content-Security-Policy (CSP) in the IOS app :(

Yeah I've tried both yours and ksga 's CSP header and unfortunately, in the Android app, integration icons stop loading after some time.

**Comment by BlastyCZ** [comment]
Unfortunately, I have the same experience as @tannisroot 
Icons do not work.

**Comment by tannisroot** [comment]
> Unfortunately, I have the same experience as [@tannisroot](https://github.com/tannisroot) Icons do not work.

Try this one (replace mydomain.com with yours):
```
default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; connect-src 'self' wss://homeassistant.mydomain.com/ https://brands.home-assistant.io/ https://github.com/ https://demo.home-assistant.io/ https://raw.githubusercontent.com/ https://my.home-assistant.io/; font-src 'self'; img-src 'self' https://basemaps.cartocdn.com/ https://brands.home-assistant.io/ https://github.com/ https://demo.home-assistant.io/ https://raw.githubusercontent.com/ https://my.home-assistant.io/; script-src-elem 'self' 'unsafe-inline'; object-src 'none'
```

**Comment by BlastyCZ** [comment]
> > Unfortunately, I have the same experience as [@tannisroot](https://github.com/tannisroot) Icons do not work.
> 
> Try this one (replace mydomain.com with yours):
> 
> ```
> default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; connect-src 'self' wss://homeassistant.mydomain.com/ https://brands.home-assistant.io/ https://github.com/ https://demo.home-assistant.io/ https://raw.githubusercontent.com/ https://my.home-assistant.io/; font-src 'self'; img-src 'self' https://basemaps.cartocdn.com/ https://brands.home-assistant.io/ https://github.com/ https://demo.home-assistant.io/ https://raw.githubusercontent.com/ https://my.home-assistant.io/; script-src-elem 'self' 'unsafe-inline'; object-src 'none'
> ```

Testing from yesterday - it seems that it is working! thanks!
