### ISSUE TITLE
HA won't start after change to Mosquitto add-on configuration

### ISSUE THREAD

**Issue by blacknell** [home-assistant/addons#2380]
### Describe the issue you are experiencing

After changing the Mosquitto add-on configuration to allow a custom configuration file (and then undoing that) the system now won't start. 

I changed the Mosquitto config section here to change active from false to true

```
customize:
  active: true
  folder: mosquitto
```
After saving, the system prompted me to reload the add-on.
The log then showed various errors and my mqtt clients started complaining too.
So, I reset active back to false. This time the save refused due to an invalid setting. After reloading the supervisor, then restarting the supervisor and finally a host reboot, I have no access to HA at all. No access to ssh and no web front end.

I had a 2022.2.0 install

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Mosquitto broker

### What is the version of the add-on?

Latest

### Steps to reproduce the issue

I haven't been able to reproduce as I have no test environment
1. Go to Mosquitto add-on configuration screen
2. Change `active: false` to `active: true` - and save
3. Change it back to `true` again
...

### Anything in the Supervisor logs that might be useful for us?

```txt
No access
```

### Anything in the add-on logs that might be useful for us?

```txt
No access
```

**Comment by blacknell** [comment]
I managed to reproduce part of the problem.

After a fresh install and a working mosquitto add-on, I again changed `active: false` to `active: true` - and saved. I received the errors logged below and then switch back to `active: false`. This time the system did not hang or crash violently as before. Nor did the UI complain and refuse to save due to an invalid setting.

It seems mosquitto is not finding the custom folder (which was the default value) and barfs.

Incidentally, all I'm trying to do is display timestamps in standard way with `log_timestamp_format %Y-%m-%d %H:%M:%S %Z`
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] mosquitto.sh: executing... 
[20:28:23] INFO: SSL is not enabled
[cont-init.d] mosquitto.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[20:28:23] INFO: Starting NGINX for authentication handling...
[20:28:23] INFO: Starting mosquitto MQTT broker...
1644352103: Error: Unable to open include_dir '/share/mosquitto'.
1644352103: Error found at /etc/mosquitto/mosquitto.conf:33.
[20:28:24] INFO: Starting mosquitto MQTT broker...
1644352104: Error: Unable to open include_dir '/share/mosquitto'.
1644352104: Error found at /etc/mosquitto/mosquitto.conf:33.
[20:28:25] INFO: Starting mosquitto MQTT broker...
1644352105: Error: Unable to open include_dir '/share/mosquitto'.
1644352105: Error found at /etc/mosquitto/mosquitto.conf:33.
[20:28:26] INFO: Starting mosquitto MQTT broker...
1644352106: Error: Unable to open include_dir '/share/mosquitto'.
1644352106: Error found at /etc/mosquitto/mosquitto.conf:33.
[20:28:27] INFO: Starting mosquitto MQTT broker...
1644352107: Error: Unable to open include_dir '/share/mosquitto'.
1644352107: Error found at /etc/mosquitto/mosquitto.conf:33.
[20:28:28] INFO: Starting mosquitto MQTT broker...
1644352108: Error: Unable to open include_dir '/share/mosquitto'.
1644352108: Error found at /etc/mosquitto/mosquitto.conf:33.
[20:28:29] INFO: Starting mosquitto MQTT broker...
1644352109: Error: Unable to open include_dir '/share/mosquitto'.
1644352109: Error found at /etc/mosquitto/mosquitto.conf:33.
[20:28:30] INFO: Starting mosquitto MQTT broker...
1644352110: Error: Unable to open include_dir '/share/mosquitto'.
1644352110: Error found at /etc/mosquitto/mosquitto.conf:33.
[20:28:31] INFO: Starting mosquitto MQTT broker...
1644352111: Error: Unable to open include_dir '/share/mosquitto'.
1644352111: Error found at /etc/mosquitto/mosquitto.conf:33.
[20:28:32] INFO: Starting mosquitto MQTT broker...
1644352112: Error: Unable to open include_dir '/share/mosquitto'.
1644352112: Error found at /etc/mosquitto/mosquitto.conf:33.
[20:28:33] INFO: Starting mosquitto MQTT broker...
1644352113: Error: Unable to open include_dir '/share/mosquitto'.
1644352113: Error found at /etc/mosquitto/mosquitto.conf:33.
```

**Comment by BusinessPerson** [comment]
After latest upgrade I am getting the same error
