### ISSUE TITLE
Error when update Z-Wave JS from 0.1.52 to 0.1.53

### ISSUE THREAD

**Issue by VasilisMavr** [home-assistant/addons#2384]
### Describe the issue you are experiencing

Can not update to the new version - error message comes up about core zwave js

Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:120
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 11:31:41 (1 occurrences)
Last logged: 11:31:41

Failed to to call /store/addons/core_zwave_js/update - 'core_zwave_js'

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Z-Wave JS

### What is the version of the add-on?

Z-Wave JS (0.1.52)

### Steps to reproduce the issue

1. Go to configuration
2. Z-Wave JS update box appears
3. Click to enter the update screen
4. Press update (create backup is ticked)
...

### Anything in the Supervisor logs that might be useful for us?

```txt
Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:120
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 11:31:41 (1 occurrences)
Last logged: 11:31:41

Failed to to call /store/addons/core_zwave_js/update - 'core_zwave_js'
```

**Comment by MartinHjelmare** [comment]
I was able to update. Maybe try again after refreshing the add-on store by clicking "Check for updates" in the three-dot-menu in the add-on store.

**Comment by VasilisMavr** [comment]
Hi 

I have managed to update it now after I did the update to the latest core 

Thanks
