### ISSUE TITLE
File editor inserts 4-space tabs when editing yaml files.

### ISSUE THREAD

**Issue by fake-name** [home-assistant/addons#2386]
### Describe the issue you are experiencing

Effectively the title.

When editing configuration yaml files, the editor is configured to insert 4-space tabs. 

All home-assistant yaml files by default use 2-space tab stops.

![image](https://user-images.githubusercontent.com/1401239/154048520-1e1d3801-f14d-4af4-a79c-8b4d8a5f089c.png)

The visible tab-stop markers in the editor are also 4 space aligned. 

Not a huge issue, but if you're tinkering with yaml a lot it does get annoying. Especially if you try to use the block indent/dedent functions (<kbd>ctrl</kbd>+<kbd>[</kbd>/<kbd>ctrl</kbd>+<kbd>]</kbd>). They're a pretty sure-file way to really mess up a yaml file by accident.

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### Which add-on are you reporting an issue with?

File editor

### What is the version of the add-on?

5.3.3 

### Steps to reproduce the issue

1. Open a yaml file
2. Hit the tab button

### Anything in the Supervisor logs that might be useful for us?

```txt
No
```

### Anything in the add-on logs that might be useful for us?

```txt
No
```

### Additional information

N/A

**Comment by Anton-Ka** [comment]
You can change it in editors Settings:
![image](https://user-images.githubusercontent.com/74901464/157642199-742780c1-e3ef-4915-aba9-a9e4ee312dfa.png)
![image](https://user-images.githubusercontent.com/74901464/157642330-c2eba672-a130-45b0-a2ff-461b0b4e41d1.png)

**Comment by frenck** [comment]
The editor used by the add-on is the HASS Configurator.

You can find the project of that editor here: <https://github.com/danielperna84/hass-configurator>

Please report feature requests and issues with the editor itself with that project. If they fix and release it, the add-on will update.
