### ISSUE TITLE
Duckdns Addon requises lowercase domain name in configuration file

### ISSUE THREAD

**Issue by RayLation** [home-assistant/addons#2387]
### Describe the issue you are experiencing

The addon was not updating my ip address at all. It took me quite a while to discover that domains need to be only lowercasethe configuration file. If you have any caps, you will get this error in the log:

[22:55:59] WARNING: KO

Fix suggestion: Simply mention this in the documentation OR allow caps in the domain names.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Duck DNS

### What is the version of the add-on?

1.14.0

### Steps to reproduce the issue

In the configuration of the addon, add a domain with any uppercase letter in the domain name.

Example:

```
domains:
  - YourDomainName.duckdns.org
```

Restart the addon and look at the log. You will get this warning. :

[22:55:59] WARNING: KO

The IP adress does not get updated on duckdns.

**Comment by loeffelpan** [comment]
I got this with only lower case letters but with a dash "-" in my domain.
Does anyone took a look into this?
