### ISSUE TITLE
Not realy a bug but better documentation

### ISSUE THREAD

**Issue by Kieros** [home-assistant/addons#2388]
### Describe the issue you are experiencing

I have been spending many hours just for this simple thing that is missing in the documentation
http:
  **base_url: https://my_domain.duckdns.org**
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

Not sure if this is the right thing to post but finally found someone on youtube explaining the whole thing and there he used teh base url and voila. Everything ok. I was searching and had everything right. Double checking port forward checking all over again.
Per haps this can be updated in the documentation that comes with the add_on and save others soem frustration.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### Which add-on are you reporting an issue with?

Duck DNS

### What is the version of the add-on?

1.14.0

### Steps to reproduce the issue

1. if the base_url is left out in the configuration.yaml I could not get it to work
2.
3.
...

**Comment by michael-gaudet** [comment]
Adding a link [from the README](https://github.com/home-assistant/addons/blob/master/duckdns/README.md) to the [Home Assistant page on this plugin](https://www.home-assistant.io/integrations/duckdns/) would also be really helpful.
