### ISSUE TITLE
ssh update and re-install problem

### ISSUE THREAD

**Issue by sandrybridge** [home-assistant/addons#2401]
hi I've installed this addon months ago and never had a problem.
Today I tried to update and I can't get my call to hassio.addon_stdin calls work anymore... 
I've tried to uninstall and re-install the addon but it won't work. I've tried to generate again new authorized keys for ssh but nothing... 
this is the log from the boot-up of the addon

>  [s6-init]_ making user provided files available at /var/run/s6/etc...exited 0.
>s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] permissions: applying... 
[fix-attrs.d] permissions: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
 Add-on: SSH & Web Terminal
 SSH & Web Terminal access to your Home Assistant instance
 Add-on version: 10.0.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 7.3  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2022.2.9
 Home Assistant Supervisor: 2022.01.1
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] docker.sh: executing... 
[16:00:43] INFO: Docker support has been enabled.
[cont-init.d] docker.sh: exited 0.
[cont-init.d] mosquitto.sh: executing... 
[cont-init.d] mosquitto.sh: exited 0.
[cont-init.d] mysql.sh: executing... 
[cont-init.d] mysql.sh: exited 0.
[cont-init.d] ssh.sh: executing... 
[16:00:46] WARNING: 
[16:00:46] WARNING: Logging in with "root" as the username,
[16:00:46] WARNING: is security wise a bad idea!
[16:00:46] WARNING: 
[16:00:46] WARNING: Most attacks against SSH are attempts to login
[16:00:46] WARNING: using the "root" username.
[16:00:46] WARNING: 
[16:00:46] WARNING: 
[16:00:46] WARNING: Logging in with a SSH password is security wise, a bad idea!
[16:00:46] WARNING: Please, consider using a public/private key pair.
[16:00:46] WARNING: What is this? https://kb.iu.edu/d/aews
[16:00:46] WARNING: 
[16:00:47] NOTICE: SFTP access is enabled
[cont-init.d] ssh.sh: exited 0.
[cont-init.d] user.sh: executing... 
[16:00:49] NOTICE: Session sharing has been disabled!
[cont-init.d] user.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[16:00:49] INFO: Starting the ttyd daemon...
[16:00:49] INFO: Starting the SSH daemon...
Server listening on 0.0.0.0 port 22.
Server listening on :: port 22.
[2022/03/09 16:00:49:9565] N:  Using foreign event loop...

from the development tools i try to execute this:
>service: hassio.addon_stdin
data:
  addon: a0d7b954_ssh
  input: bash /config/ipmi_sensors.sh

with no error displayed but the command isn't executed... 

thank you to all of you... I'm here if you need more information

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Terminal & SSH

### What is the version of the add-on?

10.0.2

**Comment by sandrybridge** [comment]
I've seen now that the addon_stdin has been removed from this addon... is there a guide to a workaround? I used to go with this service to run commands on other addons such as nut... thank you

**Comment by frenck** [comment]
> I've seen now that the addon_stdin has been removed from this addon

You are mixing up add-ons. This is the issue tracker of the core provided add-on, the service you are talking about was provided by a Community SSH add-on. Thus your report is in the wrong issue tracker.

The release of that add-on mentioned (@ removal in their release notes) it can still be done, using e.g., calling the `ssh` commandline direct (e.g., via the `command_line` integration). 

There are multiple topic on that in the community forums or you could try our Discord server. In all cases, it isn't an issue but a support question, which you probably get answered better on the community resources.

**Comment by sandrybridge** [comment]
is there any way to re-install a previous release of the addon since I got somebody to help me on a workaround?
