### ISSUE TITLE
Home Assistant Add-on: Terminal & SSH

### ISSUE THREAD

**Issue by liebenjj** [home-assistant/addons#2408]
### Describe the issue you are experiencing

Enabling watchdog in configuration results in the following errors in HA supervisor:

`ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-2835' coro=<Scheduler._run_task.<locals>._wrap_task() done, defined at /usr/src/supervisor/supervisor/misc/scheduler.py:58> exception=AttributeError("'NoneType' object has no attribute 'get'")>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/misc/scheduler.py", line 62, in _wrap_task
    await task.coro_callback()
  File "/usr/src/supervisor/supervisor/misc/tasks.py", line 417, in _watchdog_addon_application
    if addon.in_progress or await addon.watchdog_application():
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 473, in watchdog_application
    port = self.ports.get(f"{t_port}/tcp", t_port)
AttributeError: 'NoneType' object has no attribute 'get'`

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Terminal & SSH

### What is the version of the add-on?

9.3.0

### Steps to reproduce the issue

1. Enable watchdog in Terminal add-on configuration
2. Supervisor starts logging errors at 2min intervals
3. Disable watchdog in Terminal add-on configuration then errors stop
...

### Anything in the Supervisor logs that might be useful for us?

```txt
`ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-2835' coro=<Scheduler._run_task.<locals>._wrap_task() done, defined at /usr/src/supervisor/supervisor/misc/scheduler.py:58> exception=AttributeError("'NoneType' object has no attribute 'get'")>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/misc/scheduler.py", line 62, in _wrap_task
    await task.coro_callback()
  File "/usr/src/supervisor/supervisor/misc/tasks.py", line 417, in _watchdog_addon_application
    if addon.in_progress or await addon.watchdog_application():
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 473, in watchdog_application
    port = self.ports.get(f"{t_port}/tcp", t_port)
AttributeError: 'NoneType' object has no attribute 'get'`
```

### Anything in the add-on logs that might be useful for us?

```txt
None
```

### Additional information

Limited add-ons in HAOS.  Port 22 is disabled in Terminal so unsure whether the watchdog needs this to check if the service is alive.  Problem only started appearing in HAOS 2022.3.x

**Comment by TekFan** [comment]
Looks like this:
https://github.com/allenporter/stream-addons/issues/47

which means that it may be more general than the Terminal add-on and probably a Supervisor issue.
