### ISSUE TITLE
update Z-Wave not possible

### ISSUE THREAD

**Issue by CybDis** [home-assistant/addons#2412]
### Describe the issue you are experiencing

I get an error when trying to update:

0.1.54 to 0.1.55:

Bump Z-Wave JS to 8.11.9
``
Can't install homeassistant/aarch64-addon-zwave_js:0.1.55: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=0.1.55&fromImage=homeassistant%2Faarch64-addon-zwave_js&platform=linux%2Farm64: Not Found ("manifest for homeassistant/aarch64-addon-zwave_js:0.1.55 not found: manifest unknown: manifest unknown")
``

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### Which add-on are you reporting an issue with?

Z-Wave JS

### What is the version of the add-on?

0.1.55

### Steps to reproduce the issue

1. click on update button

**Comment by MartinHjelmare** [comment]
Do you still have this issue? Maybe try the checking for updates button under configuration?
