### ISSUE TITLE
Mosquitto version update to 2.0.14

### ISSUE THREAD

**Issue by SmartM-ui** [home-assistant/addons#2425]
### Describe the issue you are experiencing

Hi, 
would it be possible to update the Mosquitto version from the current 1.6.12 to 2.0.14 for full compatibility?

Thank you

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Mosquitto broker

### What is the version of the add-on?

6.0.1

### Steps to reproduce the issue

1. Update Mosquitto version to 2.0.14

**Comment by mdegat01** [comment]
Can't update to 2.0.14 right now because that's only available on alpine 3.15 and an addon base image with alpine 3.15 hasn't been released yet. But opened #2453 to update to 2.0.11 (which is what's available on alpine 3.14). It's a major update though so may take some work to get it in.

**Comment by SmartM-ui** [comment]
> Can't update to 2.0.14 right now because that's only available on alpine 3.15 and an addon base image with alpine 3.15 hasn't been released yet. But opened #2453 to update to 2.0.11 (which is what's available on alpine 3.14). It's a major update though so may take some work to get it in.

I follow the developments of your post
Thanks
