### ISSUE TITLE
File Editor (configurator) add-on needs external resources

### ISSUE THREAD

**Issue by RubenKelevra** [home-assistant/addons#2429]
### Describe the issue you are experiencing

I noticed that I can't open the File Editor if the Internet connection isn't working. I looked at the Firefox website debugging, and it lists the cdn of Cloudflare as a source.

It would be nice if those JavaScript
![Screenshot_20220407_001041](https://user-images.githubusercontent.com/614929/162081405-6d98b01d-1287-4a95-ac1b-b8a87cabaf65.png)
 files could be shipped with the add-on and served locally instead of having to fetch them over the internet.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

File editor

### What is the version of the add-on?

5.3.3

### Steps to reproduce the issue

1. Disconnect from the internet
2. Load the UI of the File Editor

**Comment by frenck** [comment]
That is correct, unfortunately, this is not a issue with the add-on, but an feature request for the application the add-on wraps.

More information can be found upstream: <https://github.com/danielperna84/hass-configurator/issues/177>

../Frenck
