### ISSUE TITLE
Home Assistant Core Pending (major?) Updates make deConz unstable (keeps crashing)

### ISSUE THREAD

**Issue by outofsight** [home-assistant/addons#2430]
### Describe the issue you are experiencing

Already described in the latest comments [here](https://github.com/home-assistant/addons/issues/1546).

**Few days** after **some** Home Assistant Core Updates (major?) are released and not installed, my deConz Addon starts crashing and being restarted by whatchdog in an endless loop. 

Lights, sensor, alarms, heating stop working except few seconds every few minutes. This run even for few days until I finnally install the update, which is something I would like to avoid (at some times, when  I'm far, when I don't have time to solve breaking changes, ...).

I notice the same pattern since many months both with Home Assistant OS in a QEMU VM under Proxmox and also with Home Assistant Supervised on a Raspberry Pi 4.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

deCONZ

### What is the version of the add-on?

all the latest

### Steps to reproduce the issue

1. Wait for an HA core (major?) update is released
2. Wait few days without installing

### Anything in the add-on logs that might be useful for us?

```txt
10:47:02:911 APS-DATA.indication srcAddr: 0xba3e, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0B04, lqi: 191, rssi: -70
10:47:02:912 ZCL attribute report 0x00158D000389312A for cluster: 0x0B04, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
10:47:03:181 APS-DATA.request id: 55, addrmode: 0x02, addr: 0xfffd, profile: 0x0000, cluster: 0x0000, ep: 0x00 -> 0x00 queue: 0 len: 11 tx.options 0x00
10:47:03:181 send NWK_addr_req to 0x00178801062D6101, last seen 0 s, last seen by neighbors 1 s
10:47:03:342 APS-DATA.indication srcAddr: 0x0da0, srcEp: 0x00 dstAddrMode: 2, profile: 0x0000, cluster: 0x8000, lqi: 255, rssi: -55
10:47:03:342 ZDP status = 0x00 -> SUCCESS
10:47:03:864 APS-DATA.confirm id: 55, status: 0x00 SUCCESS
10:47:04:993 DEV Tick.Init: booted after 8000 seconds
10:47:05:515 APS-DATA.indication srcAddr: 0xba3e, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0B04, lqi: 159, rssi: -74
10:47:05:515 ZCL attribute report 0x00158D000389312A for cluster: 0x0B04, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
10:47:05:581 Mgmt_Lqi_req zdpSeq: 19 to 0x00178801062D6101 start index 0
10:47:05:581 APS-DATA.request id: 68, addrmode: 0x03, addr: 0x00178801062d6101, profile: 0x0000, cluster: 0x0031, ep: 0x00 -> 0x00 queue: 1 len: 2 tx.options 0x00
10:47:05:591 APS-DATA.confirm id: 68, status: 0x00 SUCCESS
10:47:05:591 APS-DATA.confirm request id: 68 -> confirmed, timeout 121505589
10:47:05:617 APS-DATA.indication srcAddr: 0x0da0, srcEp: 0x00 dstAddrMode: 2, profile: 0x0000, cluster: 0x8031, lqi: 255, rssi: -55
10:47:05:617 APS-DATA.indication request id: 68 -> finished
10:47:05:618 APS-DATA.request id: 68 erase from queue
10:47:05:618 ZDP status = 0x00 -> SUCCESS
10:47:05:618 ZDP Mgmt_Lqi_rsp zdpSeq: 19 from 0x00178801062D6101 total: 16, startIndex: 0, listCount: 3
10:47:05:618     * neighbor: 0x00212EFFFF050BFE (0x0000), LQI: 184, relation: 0x02, depth: 0, rxOnWHenIdle: 1
10:47:05:618     * neighbor: 0x7CB03EAA00AE1FF4 (0x1202), LQI: 174, relation: 0x02, depth: 15, rxOnWHenIdle: 1
10:47:05:618     * neighbor: 0x680AE2FFFE7247AB (0x19C0), LQI: 239, relation: 0x02, depth: 15, rxOnWHenIdle: 1
[10:47:06] INFO: Successfully send discovery information to Home Assistant.
10:47:06:938 APS-DATA.indication srcAddr: 0xba3e, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0B04, lqi: 167, rssi: -73
10:47:06:939 ZCL attribute report 0x00158D000389312A for cluster: 0x0B04, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
10:47:08:918 APS-DATA.indication srcAddr: 0xba3e, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0B04, lqi: 191, rssi: -70
10:47:08:919 ZCL attribute report 0x00158D000389312A for cluster: 0x0B04, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
10:47:08:940 Mgmt_Lqi_req zdpSeq: 21 to 0x00178801062D6101 start index 3
10:47:08:940 APS-DATA.request id: 86, addrmode: 0x03, addr: 0x00178801062d6101, profile: 0x0000, cluster: 0x0031, ep: 0x00 -> 0x00 queue: 1 len: 2 tx.options 0x00
10:47:08:951 APS-DATA.confirm id: 86, status: 0x00 SUCCESS
10:47:08:952 APS-DATA.confirm request id: 86 -> confirmed, timeout 121508948
10:47:08:979 APS-DATA.indication srcAddr: 0x0da0, srcEp: 0x00 dstAddrMode: 2, profile: 0x0000, cluster: 0x8031, lqi: 255, rssi: -55
10:47:08:979 APS-DATA.indication request id: 86 -> finished
10:47:08:979 APS-DATA.request id: 86 erase from queue
10:47:08:979 ZDP status = 0x00 -> SUCCESS
10:47:08:979 ZDP Mgmt_Lqi_rsp zdpSeq: 21 from 0x00178801062D6101 total: 16, startIndex: 3, listCount: 3
10:47:08:979     * neighbor: 0x14B457FFFE25DD0D (0x2005), LQI: 187, relation: 0x02, depth: 15, rxOnWHenIdle: 1
10:47:08:979     * neighbor: 0x7CB03EAA0A042757 (0x2FA2), LQI: 124, relation: 0x02, depth: 15, rxOnWHenIdle: 1
10:47:08:979     * neighbor: 0x60A423FFFEFF9623 (0x4071), LQI: 86, relation: 0x02, depth: 15, rxOnWHenIdle: 1
10:47:09:915 APS-DATA.indication srcAddr: 0xba3e, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0B04, lqi: 191, rssi: -70
10:47:09:916 ZCL attribute report 0x00158D000389312A for cluster: 0x0B04, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
10:47:10:911 APS-DATA.indication srcAddr: 0xba3e, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0B04, lqi: 191, rssi: -70
10:47:10:912 ZCL attribute report 0x00158D000389312A for cluster: 0x0B04, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
10:47:12:301 Mgmt_Lqi_req zdpSeq: 22 to 0x00178801062D6101 start index 6
10:47:12:301 APS-DATA.request id: 104, addrmode: 0x03, addr: 0x00178801062d6101, profile: 0x0000, cluster: 0x0031, ep: 0x00 -> 0x00 queue: 1 len: 2 tx.options 0x00
10:47:12:387 APS-DATA.confirm id: 104, status: 0x00 SUCCESS
10:47:12:387 APS-DATA.confirm request id: 104 -> confirmed, timeout 121512308
10:47:12:389 APS-DATA.indication srcAddr: 0x0da0, srcEp: 0x00 dstAddrMode: 2, profile: 0x0000, cluster: 0x8031, lqi: 255, rssi: -55
10:47:12:390 APS-DATA.indication request id: 104 -> finished
10:47:12:390 APS-DATA.request id: 104 erase from queue
10:47:12:390 ZDP status = 0x00 -> SUCCESS
10:47:12:390 ZDP Mgmt_Lqi_rsp zdpSeq: 22 from 0x00178801062D6101 total: 15, startIndex: 6, listCount: 3
10:47:12:390     * neighbor: 0x7CB03EAA0A035A80 (0x5213), LQI: 64, relation: 0x02, depth: 15, rxOnWHenIdle: 1
10:47:12:390     * neighbor: 0x7CB03EAA0A043594 (0x554D), LQI: 113, relation: 0x02, depth: 15, rxOnWHenIdle: 1
10:47:12:390     * neighbor: 0x7CB03EAA00AE1FCD (0x613B), LQI: 157, relation: 0x02, depth: 15, rxOnWHenIdle: 1
10:47:12:919 APS-DATA.indication srcAddr: 0xba3e, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0B04, lqi: 183, rssi: -71
10:47:12:920 ZCL attribute report 0x00158D000389312A for cluster: 0x0B04, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
10:47:13:910 APS-DATA.indication srcAddr: 0xba3e, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0B04, lqi: 175, rssi: -72
10:47:13:911 ZCL attribute report 0x00158D000389312A for cluster: 0x0B04, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
10:47:14:941 APS-DATA.indication srcAddr: 0xba3e, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0B04, lqi: 175, rssi: -72
10:47:14:942 ZCL attribute report 0x00158D000389312A for cluster: 0x0B04, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
10:47:15:420 APS-DATA.request id: 121, addrmode: 0x02, addr: 0x0000, profile: 0x0000, cluster: 0x0004, ep: 0x00 -> 0x00 queue: 1 len: 4 tx.options 0x00
10:47:15:420 ZDP send request id: 0x05 to 0x00212effff050bfe
10:47:15:661 Mgmt_Lqi_req zdpSeq: 24 to 0x00178801062D6101 start index 9
10:47:15:661 APS-DATA.request id: 123, addrmode: 0x03, addr: 0x00178801062d6101, profile: 0x0000, cluster: 0x0031, ep: 0x00 -> 0x00 queue: 2 len: 2 tx.options 0x00
10:47:15:664 APS-DATA.confirm id: 121, status: 0x00 SUCCESS
10:47:15:665 APS-DATA.confirm request id: 121 -> confirmed, timeout 121515669
10:47:15:665 APS-DATA.indication srcAddr: 0x0000, srcEp: 0x00 dstAddrMode: 2, profile: 0x0000, cluster: 0x8004, lqi: 122, rssi: -63
10:47:15:666 APS-DATA.indication request id: 121 -> finished
10:47:15:666 APS-DATA.request id: 121 erase from queue
10:47:15:666 ZDP status = 0x00 -> SUCCESS
10:47:15:666 ZDP Simple_Descriptor_rsp 0x00212EFFFF050BFE - 0x0000
10:47:15:675 APS-DATA.confirm id: 123, status: 0x00 SUCCESS
10:47:15:675 APS-DATA.confirm request id: 123 -> confirmed, timeout 121515672
10:47:15:715 APS-DATA.indication srcAddr: 0x0da0, srcEp: 0x00 dstAddrMode: 2, profile: 0x0000, cluster: 0x8031, lqi: 255, rssi: -55
10:47:15:715 APS-DATA.indication request id: 123 -> finished
10:47:15:715 APS-DATA.request id: 123 erase from queue
10:47:15:715 ZDP status = 0x00 -> SUCCESS
10:47:15:715 ZDP Mgmt_Lqi_rsp zdpSeq: 24 from 0x00178801062D6101 total: 15, startIndex: 9, listCount: 3
10:47:15:715     * neighbor: 0x00178801062D609B (0x80BB), LQI: 204, relation: 0x02, depth: 15, rxOnWHenIdle: 1
10:47:15:715     * neighbor: 0x60A423FFFEF8DAE9 (0xA076), LQI: 238, relation: 0x02, depth: 15, rxOnWHenIdle: 1
10:47:15:715     * neighbor: 0x00158D000389312A (0xBA3E), LQI: 213, relation: 0x02, depth: 15, rxOnWHenIdle: 1
10:47:15:968 APS-DATA.indication srcAddr: 0xba3e, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0B04, lqi: 183, rssi: -71
10:47:15:969 ZCL attribute report 0x00158D000389312A for cluster: 0x0B04, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
10:47:16:913 APS-DATA.indication srcAddr: 0xba3e, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0B04, lqi: 191, rssi: -70
10:47:16:914 ZCL attribute report 0x00158D000389312A for cluster: 0x0B04, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
[10:47:17] INFO: Starting VNC server (local/yes)...
In exit
2022/04/09 10:47:17 [notice] 312#312: signal 15 (SIGTERM) received from 305, exiting
2022/04/09 10:47:17 [notice] 1555#1555: exiting
2022/04/09 10:47:17 [notice] 1555#1555: exit
2022/04/09 10:47:17 [notice] 312#312: signal 17 (SIGCHLD) received from 1555
Closing socket listening at 127.0.0.1:5901
2022/04/09 10:47:17 [notice] 312#312: worker process 1555 exited with code 0
2022/04/09 10:47:17 [notice] 312#312: exit
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by Tom-ahawk** [comment]
This is also the case for me, the Add-ons DeConz and for  Z-WAVE JS. In the Add-ons Configuration->devise, the normal path to the USB sticks as it were, is not there and trying all of the devises listed the Add-ons fails. Here is some lines from the Z-WAVE log:
```
2022-04-10T10:08:44.830Z DRIVER   
2022-04-10T10:08:53.883Z DRIVER   Failed to open the serial port: Error: I/O error setting custom baud rate of 1
                                  15200
Unable to start driver ZWaveError: Failed to open the serial port: Error: I/O error setting custom baud rate of 115200 (ZW0100)
    at Driver.openSerialport (/usr/src/node_modules/zwave-js/src/lib/driver/Driver.ts:913:9)
    at Immediate.<anonymous> (/usr/src/node_modules/zwave-js/src/lib/driver/Driver.ts:799:5) {
  code: 100,
  context: undefined,
  transactionSource: undefined
}
[cont-finish.d] executing container finish scripts...
```

**Comment by henriklund** [comment]
Maybe a stupid suggestion, but if you believe there is causality between a new release and your deConz starting to crash, why not test whether depriving your installation of that information has any bearing on the stability? I.e. block access to [https://version.home-assistant.io/stable.json](https://version.home-assistant.io/stable.json). A few ideas on how to achieve that could be to add a DNS record (typically possible in your router) pointing version.home-assistant.io to a nonexistent local IP, or by blocking version.home-assistant.io  using something like piHole or AdGuard.

**Comment by casperklein** [comment]
I noticed something similar, my zigbee devices went unavailable in HA 20 hours ago. While looking for the cause, I noticed that the deconz addon is not running. The log output is similar:

```
04:43:25:895 Device TTL 1258 s flags: 0x7
[04:43:29] INFO: Starting VNC server (local/yes)...
2022/04/17 04:43:29 [notice] 315#315: signal 15 (SIGTERM) received from 308, exiting
In exit
2022/04/17 04:43:29 [notice] 686#686: exiting
2022/04/17 04:43:29 [notice] 686#686: exit
Closing socket listening at 127.0.0.1:5901
2022/04/17 04:43:29 [notice] 315#315: signal 17 (SIGCHLD) received from 686
2022/04/17 04:43:29 [notice] 315#315: worker process 686 exited with code 0
2022/04/17 04:43:29 [notice] 315#315: exit
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

Without reading here, I wouldn't have assumed, that this could be related to new HA core versions available. But for the record, there is one update pending: 2022.4.4 -->2022.4.5

**Comment by Bellavista** [comment]
I had not read this problem ..... I have a virtual box installed on a windows 10 machine with home 2022.5 ...... nothing to do one day of activity and everything crashes
I read that the problem has existed for about 2 years and there is no valid solution
the only thing I can think of ...... I do not recommend buying the Combee II

**Comment by popy2k14** [comment]
Exact same issue here!

Here is the log:

´´´
...
03:01:16:346 ZCL attribute report 0x0017880104B5E7D3 for cluster: 0x0402, ep: 0x02, frame control: 0x08, mfcode: 0x0000 
03:01:17:172 ZCL attribute report 0x0017880104EFC57D for cluster: 0x0001, ep: 0x02, frame control: 0x08, mfcode: 0x0000 
03:01:19:188 ZCL attribute report 0x00178801032873E4 for cluster: 0x0406, ep: 0x02, frame control: 0x08, mfcode: 0x0000 
03:01:19:764 ZCL attribute report 0x54EF4410004D259B for cluster: 0xFCC0, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
03:01:21:051 ZCL attribute report 0x0017880104B5D1CC for cluster: 0x0400, ep: 0x02, frame control: 0x08, mfcode: 0x0000 
03:01:22:005 max transmit errors for node 0x54EF44100051803F, last seen by neighbors 202489 s
03:01:23:827 max transmit errors for node 0x54EF44100053DE83, last seen by neighbors 202491 s
03:01:24:260 Device TTL 2459 s flags: 0x7
[01:01:25] INFO: Service restart after closing
[03:01:25] INFO: Starting VNC server (local/yes)...
[01:01:26] WARNING: Halt add-on
s6-rc: info: service legacy-services: stopping
2022/08/13 03:01:26 [notice] 116#116: signal 15 (SIGTERM) received from 111, exiting
2022/08/13 03:01:26 [notice] 1295#1295: exiting
In exit
2022/08/13 03:01:26 [notice] 1295#1295: exit
2022/08/13 03:01:26 [notice] 116#116: signal 17 (SIGCHLD) received from 1295
2022/08/13 03:01:26 [notice] 116#116: worker process 1295 exited with code 0
2022/08/13 03:01:26 [notice] 116#116: exit
Closing socket listening at 127.0.0.1:5901
s6-svwait: fatal: supervisor died
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
´´´

Addon is stopped and not restarted but "Watchdog" is enabled, why!?
I can manually start the addon and it's working again.

I have found in the kernel/host log some messages that /dev/ttyACM0 is connecting/disconnecting, see here:

´´´
...
[144597.009312] usb 1-1.1: USB disconnect, device number 8
[144597.285591] usb 1-1.1: new full-speed USB device number 9 using xhci-hcd
[144597.457649] cdc_acm 1-1.1:1.0: ttyACM1: USB ACM device
[144600.849352] usb 1-1.1: USB disconnect, device number 9
[144601.129388] usb 1-1.1: new full-speed USB device number 10 using xhci-hcd
[144601.297688] cdc_acm 1-1.1:1.0: ttyACM0: USB ACM device
...
[174713.105205] usb 1-1.1: USB disconnect, device number 10
[174713.382328] usb 1-1.1: new full-speed USB device number 11 using xhci-hcd
[174713.553564] cdc_acm 1-1.1:1.0: ttyACM1: USB ACM device
[174716.945213] usb 1-1.1: USB disconnect, device number 11
[174717.222137] usb 1-1.1: new full-speed USB device number 12 using xhci-hcd
[174717.393566] cdc_acm 1-1.1:1.0: ttyACM0: USB ACM device
...
[205015.825108] usb 1-1.1: USB disconnect, device number 12
[205016.103344] usb 1-1.1: new full-speed USB device number 13 using xhci-hcd
[205016.273461] cdc_acm 1-1.1:1.0: ttyACM0: USB ACM device
[205019.409111] usb 1-1.1: USB disconnect, device number 13
[205019.723221] usb 1-1.1: new full-speed USB device number 14 using xhci-hcd
[205019.889392] cdc_acm 1-1.1:1.0: ttyACM0: USB ACM device
[205325.818795] kauditd_printk_skb: 18 callbacks suppressed
...
[208619.793115] usb 1-1.1: USB disconnect, device number 14
[208620.071210] usb 1-1.1: new full-speed USB device number 15 using xhci-hcd
[208620.241563] cdc_acm 1-1.1:1.0: ttyACM0: USB ACM device
[208623.633075] usb 1-1.1: USB disconnect, device number 15
[208623.911008] usb 1-1.1: new full-speed USB device number 16 using xhci-hcd
[208624.081438] cdc_acm 1-1.1:1.0: ttyACM0: USB ACM device
[212223.249105] usb 1-1.1: USB disconnect, device number 16
[212223.527817] usb 1-1.1: new full-speed USB device number 17 using xhci-hcd
[212223.697389] cdc_acm 1-1.1:1.0: ttyACM0: USB ACM device
[212227.089118] usb 1-1.1: USB disconnect, device number 17
[212227.367643] usb 1-1.1: new full-speed USB device number 18 using xhci-hcd
[212227.537430] cdc_acm 1-1.1:1.0: ttyACM0: USB ACM device
...
[215827.729106] usb 1-1.1: USB disconnect, device number 18
[215828.007491] usb 1-1.1: new full-speed USB device number 19 using xhci-hcd
[215828.177446] cdc_acm 1-1.1:1.0: ttyACM0: USB ACM device
[215831.569077] usb 1-1.1: USB disconnect, device number 19
[215831.847275] usb 1-1.1: new full-speed USB device number 20 using xhci-hcd
[215832.017384] cdc_acm 1-1.1:1.0: ttyACM0: USB ACM device
[219432.465115] usb 1-1.1: USB disconnect, device number 20
[219432.744969] usb 1-1.1: new full-speed USB device number 21 using xhci-hcd
[219432.913393] cdc_acm 1-1.1:1.0: ttyACM0: USB ACM device
[219436.305090] usb 1-1.1: USB disconnect, device number 21
[219436.584787] usb 1-1.1: new full-speed USB device number 22 using xhci-hcd
[219436.753403] cdc_acm 1-1.1:1.0: ttyACM0: USB ACM device
...
[223037.201039] usb 1-1.1: USB disconnect, device number 22
[223037.478913] usb 1-1.1: new full-speed USB device number 23 using xhci-hcd
[223037.649351] cdc_acm 1-1.1:1.0: ttyACM0: USB ACM device
[223041.041076] usb 1-1.1: USB disconnect, device number 23
[223041.318729] usb 1-1.1: new full-speed USB device number 24 using xhci-hcd
[223041.489353] cdc_acm 1-1.1:1.0: ttyACM0: USB ACM device
[226642.193040] usb 1-1.1: USB disconnect, device number 24
[226642.473024] usb 1-1.1: new full-speed USB device number 25 using xhci-hcd
[226642.641391] cdc_acm 1-1.1:1.0: ttyACM0: USB ACM device
[226646.033048] usb 1-1.1: USB disconnect, device number 25
[226646.312828] usb 1-1.1: new full-speed USB device number 26 using xhci-hcd
[226646.481402] cdc_acm 1-1.1:1.0: ttyACM0: USB ACM device
...
´´´

So it seems that the conbee II is connecting/disconnecting and maybe triggering this issue.
I found a therad where someone has similar issue and solved it by reflashing the firmware of the conbee II: https://community.home-assistant.io/t/troubleshooting-new-conbee-ii-usb-device-disconnecting/325853/12

Done that now  to the actuall stable: deCONZ_ConBeeII_0x26720700.bin

Will see how it goes.

And for the thread title: yes, there was an HA core update pending!!!!!
PS.: Sorry for not opening an new issue and posting while it's closed, but that's exactly my issue!

please unstale & reopen!

**Comment by ottelo9** [comment]
Never had problems with Deconz and now my addon stops with no auto restart:

`2022-08-13 02:47:29 INFO (MainThread) [pydeconz.websocket] Reconnecting to deCONZ (core-deconz)
2022-08-13 02:47:30 INFO (MainThread) [pydeconz.websocket] Reconnecting to deCONZ (core-deconz) failed, scheduling retry at an interval of 15 seconds`

After a manual START it works again. And I have also a core update pending!

**Comment by popy2k14** [comment]
Look here: https://community.home-assistant.io/t/deconz-official-thread/100504/3209?u=popy
More people's had issues in that night!?
It sounds strange but the eonly commonnwas that an HA core update was available for install.

I think watchdog feature of the addon is not working!

There was already an issue for this which got stalled: https://github.com/home-assistant/addons/issues/1546

**Comment by sagacity** [comment]
I just ran into this issue during the night, with a HA Core update becoming available. Deconz got a SIGTERM and didn't come back up.

**Comment by outofsight** [comment]
It was since long time I didn't noticed this issue but last night it happened again.

**Comment by casperklein** [comment]
After being notified by this thread, I checked the deConz addon in my setup. It has also stopped 😞
