### ISSUE TITLE
DuckDNS does not save file to /ssl/ folder

### ISSUE THREAD

**Issue by provinzio** [home-assistant/addons#2439]
### Describe the issue you are experiencing

I had a working DuckDNS/ngninx setup, but at some point it stopped working. I tested the setup and realized, that the duck dns addon does not update the certificate in the `ssl` file anymore. It's only checking and creating the ssl file in its working dir `data\core_duckdns_letsencrypt\<mydomain>\`. Isn't DuckDNS supposed to copy the current certificate to `/ssl/`?

Copying the newest `fullchain.pem` and `privkey.pem` by hand into the `/ssl/` folder solves my problem for now... So the created certificate is fine, but for some reasons it's not copied to the ssl dir. 

I don't now which informations are necessary for you, to identify the problem better. Happy to help with more information.

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### Which add-on are you reporting an issue with?

Duck DNS

### What is the version of the add-on?

core-2022.4.5

### Steps to reproduce the issue

unknown

### Anything in the add-on logs that might be useful for us?

```txt
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
# INFO: Using main config file /data/workdir/config
+ Account already registered!
[20:37:12] INFO: OK
213.168.73.226
NOCHANGE
[20:37:13] INFO: Renew certificate for domains: <mydomain> and aliases: 
# INFO: Using main config file /data/workdir/config
Processing <mydomain>
 + Checking domain name(s) of existing cert... unchanged.
 + Checking expire date of existing cert...
 + Valid till Jun 17 16:24:11 2022 GMT (Longer than 30 days). Skipping renew!
[20:42:19] INFO: OK
213.168.73.226
NOCHANGE
```

### Additional information

my Config
```
lets_encrypt:
  accept_terms: true
  certfile: fullchain.pem
  keyfile: privkey.pem
  algo: secp384r1
token: ...
domains:
  - <mydomain>
aliases: []
seconds: 300
```

**Comment by Olly667** [comment]
Same here.

Logfile says, my cert expires in June, but the cert expired (in the browser) on April 20.

` + Checking domain name(s) of existing cert... unchanged.
 + Checking expire date of existing cert...
 + Valid till Jun 19 14:58:24 2022 GMT (Longer than 30 days). Skipping renew!`

**Comment by programmdesign** [comment]
I have the same issue. A new cert is created by DuckDns, but it is stored in "/usr/share/hassio/addons/data/core_duckdns/letsencrypt/<my_url>.duckdns.org/". I can't even "cd" into this directory nor can I list its content -- not even with sudo. However, I can copy fullchain.pem and privkey.pem from there into the /usr/share/hassio/ssl. After I do so, everything works fine again.

**Comment by kennyboy55** [comment]
I suddenly have the same issue. The existing certificate was expired, and the new certificate generated by DuckDNS was not copied. I will see if the manual action that you mention works for me.

**Comment by wolsos** [comment]
Hi programmdesign,

How did you do this copy?
As a running job by HomeAssistant?
Where do you put the script/file?

**Comment by thorwaler** [comment]
Same here, no file in SSL (the folder did not even exist)

**Comment by eXcalibre** [comment]
Just to keep this updated for other people who may find this issue. I found my certs in the follwoing location.

lrwxrwxrwx  1 root root   91 Apr 27 12:01 fullchain.pem -> /var/lib/homeassistant/addons/data/core_duckdns/letsencrypt/DOMAIN.duckdns.org/fullchain.pem
lrwxrwxrwx  1 root root   89 Apr 27 12:01 privkey.pem -> /var/lib/homeassistant/addons/data/core_duckdns/letsencrypt/DOMAIN.duckdns.org/privkey.pem

As the destination directory uses backup file names etc, i created a symlink to the destination to always collect the latest pem file. (otherwise it will expire within the /ssl/ directory and need to be recopied on each renewal.

Hope it helps
