### ISSUE TITLE
Epoch time in mosquitto logs

### ISSUE THREAD

**Issue by snis** [home-assistant/addons#2440]
### Describe the issue you are experiencing

The logs from the official mosquitto addon displays logtime in Epoch and not human readable.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Mosquitto broker

### What is the version of the add-on?

6.0.1

### Steps to reproduce the issue

Show the log file.

### Anything in the add-on logs that might be useful for us?

```txt
1650450689: New connection from 172.30.32.2 on port 1883.
1650450689: Socket error on client <unknown>, disconnecting.
```

### Additional information

According to official mosquitto documentation https://mosquitto.org/man/mosquitto-conf-5.html
This can be changed by adding `log_timestamp_format` to the /etc/mosquitto/mosquitto.conf file.
```
log_timestamp_format format
   Set the format of the log timestamp. If left unset, this is the number of seconds since the Unix epoch.
   This option is a free text string which will be passed to the strftime function as the format specifier.
   To get an ISO 8601 datetime, for example:

log_timestamp_format %Y-%m-%dT%H:%M:%S
```

Would have made a pull request if I was smarter, but I'm a Swede

**Comment by fvant** [comment]
great suggestion, my logs are readable now

**Comment by snis** [comment]
@pplucky Thanks!

I wasn't aware of how to make customizations persistent in the container
