### ISSUE TITLE
Password entry field and Login button are invisible

### ISSUE THREAD

**Issue by rPonuganti** [home-assistant/addons#2464]
### Describe the issue you are experiencing

After updating to 6.13.0, Login password entry field and Login button are invisible.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

deCONZ

### What is the version of the add-on?

6.13.0

### Steps to reproduce the issue

1. Open the addon web UI.
2. Select Phoscon app.
3. As attached in the picture the password input field is invisible.
4. If I continue to type in my password, after a click of the key, Login button also goes invisible. 

![Login_Button_gone](https://user-images.githubusercontent.com/2393528/166264716-ad341acf-87b5-4d9f-a7d4-e9c02574681b.PNG)
![Password_inputField_missing](https://user-images.githubusercontent.com/2393528/166264718-bd10089b-8e79-4a5c-8bf6-dbcc6055f3ff.png)

### Anything in the Supervisor logs that might be useful for us?

```txt
nothing suspicious
```

### Anything in the add-on logs that might be useful for us?

```txt
nothing suspicious
```

### Additional information

I tried to restart Home Assisant, restart addon nothing changes.

**Comment by TobbeWendt** [comment]
I hav e the same issue.
Have latest beta versions:
Home Assistant Core 2022.5.0b5
Home Assistant Supervisor 2022.05.0
Home Assistant OS 8.0.rc3
Kernel version 5.15.32-v8
Agent version 1.2.1

Did upgrade the DeConz add-on today.

Using latest version of Chrome browser and MS Edge
Work OK with Firefox

**Comment by mdegat01** [comment]
This is a duplicate of #2454 which was just resolved for the user that reported it with [these instructions](https://github.com/home-assistant/addons/issues/2454#issuecomment-1113772118). It appears there's a bug with chrome creating this and tannyl provided workaround steps. Can you try and see if those work for you as well?

**Comment by TobbeWendt** [comment]
I have tried the work-arounds:
The recommended workarounds 1 and 3 works fine, #2 does not work.
Thanks, at least I can access my ConBee..  :-)

**Comment by rPonuganti** [comment]
I can also confirm that 1 and 3 works.
Thanks for the help.
