### ISSUE TITLE
Home Assisstant Add-on: Mosquitto 6.0.2 - can't get Bridge Mode up and running

### ISSUE THREAD

**Issue by epictechlab** [home-assistant/addons#2467]
### Describe the issue you are experiencing

I'm unable to get the Bridge mode up and running.

If im set 

```
customize:
  active: true
  folder: mosquitto
```
 I´m getting Errors in the Log File

````
Error: Unable to open include_dir '/share/mosquitto'.
Error found at line /etc/mosquitto/mosquitto.conf:33. 
[09:12:35] INFO: Successfully send discovery information to Home Assistant.
[09:12:35] INFO: Successfully send service information to the Supervisor.
````

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Mosquitto broker

### What is the version of the add-on?

6.0.2

### Steps to reproduce the issue

second mqtt config:
path: /usr/share/hassio/share/mosquitto/

```
connection hisensetv
address ***.***.***.***:36669
username hisenseservice
password  multimqttservice
clientid HomeAssistant
bridge_tls_version tlsv1.2
bridge_cafile hisense.crt
bridge_certfile rcm_certchain_pem.cer
bridge_keyfile rcm_pem_privkey.pkcs8
bridge_insecure true
start_type automatic
try_private true
topic /remoteapp/# both 0 hisense ""
```

### Anything in the add-on logs that might be useful for us?

```txt
`
Error: Unable to open include_dir '/share/mosquitto'.
Error found at line /etc/mosquitto/mosquitto.conf:33. 
[09:12:35] INFO: Successfully send discovery information to Home Assistant.
[09:12:35] INFO: Successfully send service information to the Supervisor.
````
```


### Additional information

_No response_

**Comment by mdegat01** [comment]
Sounds like `/share/mosquitto` doesn't exist. Did you make that folder and follow the documentation about how to use it?

**Comment by epictechlab** [comment]
Yeah, I duplicated the files from /usr/share/hassio/share/mosquitto/ to /usr/share/mosquitto/

The files are in both locations, so it should work one way or another.

**Comment by epictechlab** [comment]
Thanks, that's it. I placed the files in /share/mosquitto/ an the bridge is running

**Comment by Napoleon-BlownApart** [comment]
I had the same problem, but was able to fix it by using a `SSH` addon rather than the `File Editor`.
After logging in using SSH, I was able to access the `/share` folder, in which I created the `mosquitto` folder, and, using `nano`, I put my files there.
walla, MQTT started working.
