### ISSUE TITLE
Samba does not bind to Wireguard (wg0) interfaces

### ISSUE THREAD

**Issue by pashdown** [home-assistant/addons#2475]
### Describe the issue you are experiencing

I can't get the Samba add-on to recognize the wg0 interface on my HassOS install.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Samba share

### What is the version of the add-on?

9.6.1

### Steps to reproduce the issue

1. Go to YAML configuration mode.
2. Try adding either the Wireguard network or wg0 as an option to network(s) or interface(s).
3. Restart Samba.
4. Note that it doesn't recognize the Wireguard network or interface.

### Anything in the add-on logs that might be useful for us?

```txt
22-05-04 06:51:23 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)

22-05-04 06:53:43 WARNING (MainThread) [supervisor.addons.options] Option 'interfaces' does not exist in the schema for Samba share (core_samba)

22-05-04 06:55:24 WARNING (MainThread) [supervisor.addons.options] Option 'network' does not exist in the schema for Samba share (core_samba)

22-05-04 07:50:43 WARNING (MainThread) [supervisor.addons.options] Option 'networks' does not exist in the schema for Samba share (core_samba)
```

### Additional information

Not sure where or how the "network" option from the 9.5.0 change log is supposed to be placed.  

"Remove interface options in favor of network"

**Comment by mdegat01** [comment]
This isn't a bug. The samba addon now binds to all supported interfaces (i.e. managed by supervisor) and no others. The wireguard interface isn't managed by supervisor so this addon won't bind to that. If you want that capability you'll need to find/make a fork. Or if you are running HA supervised you can run your own smb daemon on the host (not sure if you are, you put HAOS and HA Supervised which isn't possible as those are two different installation methods).
