### ISSUE TITLE
Updating to deCONZ 6.13.0 results in regular climate sensor "failures"

### ISSUE THREAD

**Issue by beaulebens** [home-assistant/addons#2476]
### Describe the issue you are experiencing

After upgrading to 6.13.0, I noticed that some of my zigbee sensors are regularly "failing" and reporting strange values. Downgrading to 6.12.1 "fixes" the issue.

I have multiple zigbee climate sensors (they show as `lumi.weather` by LUMI, but they are Aqara Climate sensors) connected via a conbeeII stick, and running the deCONZ addon.

Running 6.13.0, on _some_ (not all) of the climate sensors, I see them regularly drop down to -148F, then bounce back to their actual reading. This shows up in the history of the sensors, as seen in the screenshot below;

<img width="414" alt="Screen Shot 2022-05-04 at 11 24 18 AM" src="https://user-images.githubusercontent.com/108942/166744329-6cb706a1-c1ac-4052-8216-ee18c8d4566e.png">

I haven't been able to figure out any pattern around which sensors it affects, and don't see anything in any of the logs that indicate what's going on.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

deCONZ

### What is the version of the add-on?

6.13.0

### Steps to reproduce the issue

1. Update from 6.12.1 to 6.13.0
2. Observe regular "dropping" of zigbee climate sensors/values

**Comment by mdegat01** [comment]
So I mean HA and this addon really doesn't get any say in that. The deconz debian package communicates with the device and reports the values to HA, this addon just packages it.

I went to their github repo and found this issue for the latest stable version (which 6.13.0 just updated the addon to). I think this matches what you're seeing:
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6017

**Comment by beaulebens** [comment]
Thanks @mdegat01, you're right -- I'll close this, and link it (and follow) that other issue.
