### ISSUE TITLE
Error 400: invalid_request

### ISSUE THREAD

**Issue by greghesp** [home-assistant/addons#2478]
### Describe the issue you are experiencing

Whe trying to request an auth code, the Google Auth page says

```
Error 400: invalid_request

You can't sign in to this app because it doesn't comply with Google's OAuth 2.0 policy for keeping apps secure.

You can let the app developer know that this app doesn't comply with one or more Google validation rules.
Request Details
The content in this section has been provided by the app developer. This content has not been reviewed or verified by Google.
If you’re the app developer, make sure that these request details comply with Google policies.
redirect_uri: urn:ietf:wg:oauth:2.0:oob
```

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Google Assistant SDK

### What is the version of the add-on?

2.5.0

### Steps to reproduce the issue

1. Open WebUI
2. Click Get a Code from Google

### Anything in the add-on logs that might be useful for us?

```txt
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[16:47:57] INFO: Installing/Updating service client_secrets file
[16:47:57] INFO: Starting WebUI for handling OAuth2...
[05/May/2022:16:47:57] ENGINE Listening for SIGTERM.
[05/May/2022:16:47:57] ENGINE Listening for SIGHUP.
[05/May/2022:16:47:57] ENGINE Listening for SIGUSR1.
[05/May/2022:16:47:57] ENGINE Bus STARTING
[05/May/2022:16:47:57] ENGINE Started monitor thread 'Autoreloader'.
[05/May/2022:16:47:57] ENGINE Serving on http://0.0.0.0:9324
[05/May/2022:16:47:57] ENGINE Bus STARTED
```

### Additional information

I'm loading the authorisation page up from my local HA IP address.  This isn't an authorised URL in the Google Project as you cant add local IP addresses.  I have added the Nabu Casa address in there, however I cannot access port 9324 from Nabu Casa

**Comment by maxi1134** [comment]
This problem is back! Due to this: https://developers.googleblog.com/2022/02/making-oauth-flows-safer.html?fbclid=IwAR3aK9n0TEFUH3sgktrrXK47t1CQnlpHBWa8eTksnSYMkKcEYuLeW2gLuYs

**Comment by maxi1134** [comment]
PRoblem still present

**Comment by maxi1134** [comment]
Problem still present

**Comment by tjmaru** [comment]
problem is here, can someone take care of it, please?

**Comment by amosyuen** [comment]
Also running into the problem

**Comment by Term1t3** [comment]
The problem is still unsolved

**Comment by MiskaWasTaken** [comment]
Problem still unsolved

**Comment by hanmilLee** [comment]
Problem still unsolved
