### ISSUE TITLE
duckdns addon new install error on aliases

### ISSUE THREAD

**Issue by aaamoeder** [home-assistant/addons#2479]
### Describe the issue you are experiencing

When setting up duckdns for the first time, you have to set domains and token, but the option alias gets accolades instead of brackets causing an error upon saving the options.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Duck DNS

### What is the version of the add-on?

1.14.0 

### Steps to reproduce the issue

1. set up addon from scratch
2. edit settings
3. save

### Anything in the Supervisor logs that might be useful for us?

```txt
/
```

### Anything in the add-on logs that might be useful for us?

```txt
/
```

### Additional information

It's in the add-on configuration.
![Screenshot 2022-05-05 210437](https://user-images.githubusercontent.com/20947118/167006230-2cdf4b69-8ef6-4465-b711-acb9c552c009.png)

I left the alias field empty but got an error.
By default the setting for alias inside yaml looks like "aliases: {}" but it should be "aliases: []"
It was only when I changed the accolades to brackets in the yaml configuration that it got accepted .

**Comment by enfguandi** [comment]
Same here.
Thanks for the solution @aaamoeder.
