### ISSUE TITLE
Error in the Phoscon application for ADD-ON Deconz in Chrome

### ISSUE THREAD

**Issue by vgisbert** [home-assistant/addons#2480]
### Describe the issue you are experiencing

The Phoscon application has stopped working.
The error that appears on the screen is:
“The web page http://192.168.9.10:8123/api/hassio_ingress/dY4Wak76CxIaGnp-A-lPYD9hbwLmE23TQgwG-zvdgkU/pwa/index.html may be temporarily down or may have moved permanently to another address.”

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### Which add-on are you reporting an issue with?

deCONZ

### What is the version of the add-on?

deCONZ  6.13.0 (Bump deCONZ to 2.15.3)

### Steps to reproduce the issue

As the problem appeared when updating Home Assistant to version 6.12.1, at first I thought it was a problem of HA versions. But recovering from backup, the same thing happened.

In one of the multiple Add-on installation tests, a message appeared saying:
“Unlock your Deconz gateway to register with Home Assistant.
Go to Deconz Settings -> Gateway -> Advanced
Press the "Authenticate App" button
You couldn't get an API key "

And returning to the documentation, indicates:
“Make a backup copy of your Deconz data, entering the web user interface, on the menu:
Configuration -> Gateway -> Backup option button, then create a new backup and download it on your computer. 2. Uninstall the complement. 3. In initial assistant, eliminate the current integration you have for Deconz. 4. Restart the house assistant. 5. Install the Deconz complement again and confuse it again in accordance with the instructions. 6. Restore the backup that created in the first step in the same location in the web user interface as before. 7. Restart the complement and next, restart the start assistant once more. 8. Follow the instructions on the configuration of the Deconz integration. ”

But I can't advance to point 6, because Phoscon does not start.
I no longer have ideas.
Could something be done through the VNC interface, which is the only one that works?

### Anything in the add-on logs that might be useful for us?

```txt
172.30.32.2 - - [05/May/2022:23:05:21 +0200] "GET /pwa/index.html HTTP/1.1" 413 0 "http://192.168.9.10:8123/api/hassio_ingress/dY4Wak76CxIaGnp-A-lPYD9hbwLmE23TQgwG-zvdgkU/ingress.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36"
```

**Comment by vgisbert** [comment]
![Portapapeles-1](https://user-images.githubusercontent.com/36932535/167026365-16dcb431-70f6-422a-aa0b-a7c9f52b38aa.jpg)

**Comment by vgisbert** [comment]
![Portapapeles-2](https://user-images.githubusercontent.com/36932535/167026668-92a776cc-4a6b-4b70-b25b-2e7b847ad786.jpg)
![Portapapeles-3](https://user-images.githubusercontent.com/36932535/167026686-8f296114-eea0-4284-a5b1-a91a33352f4a.jpg)

**Comment by vgisbert** [comment]
I have good and bad news.
In part, I have discovered who is the cause.
I have tried browsing with Firefox and the Fhoscon application works correctly. Thinking there was some misconfiguration in the Chrome browser, I have initialized it and cleared the entire profile. But it still gives the problem.
Chrome Versión 101.0.4951.54 (Build oficial) (64 bits)
At least I've found a way to continue working.
I modify the title of the issue with this information.
With this new news, any idea of the problem?

**Comment by vgisbert** [comment]
I have found a documentation that indicated that, once Chrome is initialized and the application is closed, the folder must be deleted:

"C:\Users\%USERNAME%\AppData\Local\Google\Chrome\User Data"

And fixed !!!!!
It's unbelievable how much time wasted on this issue due to simple browser corruption.

**Comment by Puntoboy** [comment]
I've suddenly having this issue in Edge. If I type the URL into a new browser window (http://deconzIP:APIPort) the GUI loads and works perfectly.
