### ISSUE TITLE
Update deCONZ on 2022.4.7 to 6.13.0 from 6.12.0 fails

### ISSUE THREAD

**Issue by Ronnie-J** [home-assistant/addons#2482]
### Describe the issue you are experiencing

Via Home Assistant I click the update button and receive the following message:

`Can't install homeassistant/amd64-addon-deconz:6.13.0: 500 Server Error for http+docker://localhost/v1.41/images/homeassistant/amd64-addon-deconz:6.13.0/json: Internal Server Error ("readlink /var/lib/docker/overlay2: invalid argument")`

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### Which add-on are you reporting an issue with?

deCONZ

### What is the version of the add-on?

6.12.0

### Steps to reproduce the issue

1. Access the DeCONZ Addon /hassio/addon/core_deconz/info
2. Click update
3. Get the error in an infobox

### Anything in the Supervisor logs that might be useful for us?

```txt
Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:120
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 12.54.19 (4 occurrences)
Last logged: 12.56.08

Failed to to call /store/addons/core_deconz/update - Can't install homeassistant/amd64-addon-deconz:6.13.0: 500 Server Error for http+docker://localhost/v1.41/images/homeassistant/amd64-addon-deconz:6.13.0/json: Internal Server Error ("readlink /var/lib/docker/overlay2: invalid argument")
```

### Anything in the add-on logs that might be useful for us?

```txt
No
```

**Comment by pvizeli** [comment]
`ha su repair` should fix that

**Comment by Ronnie-J** [comment]
@pvizeli that did indeed fix it. Do you now what issue was fixed by running that command?
