### ISSUE TITLE
deCONZ plugsocket bug (6.13.0)

### ISSUE THREAD

**Issue by kravalli** [home-assistant/addons#2491]
### Describe the issue you are experiencing

All my plugsockets update very rarely (every 5-7 mins) since I updated to 6.13.0. This is crutial for my automations, because I use the integrated power meter on them to check if a device is on and thus trigger the automation. I rolled back to 6.12.0.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

deCONZ

### What is the version of the add-on?

6.13.0

### Steps to reproduce the issue

1. update deCONZ to 6.13.0
2. turn on your device, so there is a load on the plugsocket with power meter
3. watch how long it takes to upadte the values current, ...

**Comment by klaasnicolaas** [comment]
Curious if you will still experience this problem when version 6.14 is available. Do you use an extension cable? Because slow response time is usually solved with a cable 🤔

**Comment by kravalli** [comment]
> Curious if you will still experience this problem when version 6.14 is available. Do you use an extension cable? Because slow response time is usually solved with a cable 🤔

I just update to 6.14.1 to try it out and I still had the same issue. So I loaded my backup again.
