### ISSUE TITLE
Z-Wave JS 0.1.59 fails to start

### ISSUE THREAD

**Issue by kpine** [home-assistant/addons#2494]
### Describe the issue you are experiencing

Z-Wave JS add-on version 0.1.59 fails to start.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Z-Wave JS

### What is the version of the add-on?

0.1.59

### Steps to reproduce the issue

1. Install add-on
2. Configure
3. Start
4. Notice errors in log

### Anything in the add-on logs that might be useful for us?

```txt
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/config.sh
/package/admin/s6-overlay-3.1.0.1/etc/s6-rc/scripts/cont-init: line 14: /etc/cont-init.d/config.sh: Permission denied
cont-init: info: /etc/cont-init.d/config.sh exited 126
cont-init: info: running /etc/cont-init.d/structure.sh
/package/admin/s6-overlay-3.1.0.1/etc/s6-rc/scripts/cont-init: line 14: /etc/cont-init.d/structure.sh: Permission denied
cont-init: info: /etc/cont-init.d/structure.sh exited 126
cont-init: warning: some scripts exited nonzero
s6-rc: warning: unable to start service legacy-cont-init: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### Additional information

Relevant issue: https://github.com/just-containers/s6-overlay/issues/376

**Comment by Nathanlclark** [comment]
I'm getting the same error, thanks for entering @kpine.

**Comment by tankdeer** [comment]
Same here

**Comment by cybergrimes** [comment]
Same, I rolled back to .58 and my network is still not working correctly. The log seems normal now, I was getting the same error as this issue when on .59, however no entities are available.

**Comment by wklink** [comment]
> I restored to .58 and my network is still not working correctly. The log seems normal now however no entities are available.

Restoring and **rebooting** the host worked for me.

**Comment by mark007** [comment]
Should 0.1.59 be removed as with haos i cant downgrade the addon and dont want a full restore

**Comment by tankdeer** [comment]
> Should 0.1.59 be removed as with haos i cant downgrade the addon and dont want a full restore

Not to get too sidetracked, but why can't you downgrade? I'm on HA OS and I was able to without issue

**Comment by mark007** [comment]
It says on the doca that ha os doesnt allow installing of specific versions, only via doing restores from backupa can you get back to those older versions.

**Comment by tankdeer** [comment]
> It says on the docs that ha os doesnt allow installing of specific versions, only via doing restores from backupa can you get back to those older versions.

I see what you're saying. Yes, I believe that is true, however, you can restore _just_ the addon from a backup, and not affect anything else. You don't need to do a full restore.

**Comment by CT-AUS** [comment]
same here, but was able to restore to 0.1.58

**Comment by joelmoses** [comment]
Same thing happened on my installation -errors above are identical. Restoration of _just_ the add-on from the backup worked well to recover.

**Comment by mark007** [comment]
> > It says on the docs that ha os doesnt allow installing of specific versions, only via doing restores from backupa can you get back to those older versions.
> 
> I see what you're saying. Yes, I believe that is true, however, you can restore _just_ the addon from a backup, and not affect anything else. You don't need to do a full restore.

Ahh i see. Thank you

**Comment by techtomydoor** [comment]
Same issue here on both my very stable HA OS and a freshly installed Supervised setup that I'm checking out. Rolling back to 0.1.58 from backups fixed both.

**Comment by BebeMischa** [comment]
HA supervised on dedicated machine, no VM’s and things.

Same problem, after update Zwave went dead and took RfxCom (which also is a USB controller) with it.

Restore of the partial backup made by the update and machine restart solved it. Nothing is lost, just back to normal.

This update needs an first responder :slight_smile:

**Comment by jsiemonski** [comment]
Same issue with my install, restoring worked for now.

**Comment by fireheadman** [comment]
more visibility on this from the community....
[https://community.home-assistant.io/t/bug-z-wave-latest-version-0-1-59-controller-no-longer-works](url)

**Comment by manurosado** [comment]
Same here, I also rolled back to 0.1.58 and all is well

**Comment by Devindra04** [comment]
Similar issue here using a Aeotech Z-Wave usb stick with Raspberry Pi 4 reverted back to 0.1.58 which is now working again

**Comment by dredjohn21** [comment]
Nasty bug 

For new folks: go to System->Backups and tap the older zwave js row.  Then tap version 58s row and you’ll have ability to check the box next to the add on on next page and click restore.  Would recommend restart thereafter and confirm everything is back to normal.
