### ISSUE TITLE
chmod +x to all executable scripts in all addon folders

### ISSUE THREAD

**Issue by raman325** [home-assistant/addons#2496]
### Describe the issue you are experiencing

It was discovered that due to this change: https://github.com/just-containers/s6-overlay/issues/376 files that get executed must have the executable flag set. It appears in a brief sweep that we don't typically set the x bit on executables, so the next time addons get updated, they will fail to run unless this is updated.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

deCONZ

### What is the version of the add-on?

the next new version

### Steps to reproduce the issue

1. Create a PR for an addon update without setting the +x flag.
2. Try building and running the addon, and see that it fails with something like the following:
```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/config.sh
/package/admin/s6-overlay-3.1.0.1/etc/s6-rc/scripts/cont-init: line 14: /etc/cont-init.d/config.sh: Permission denied
cont-init: info: /etc/cont-init.d/config.sh exited 126
cont-init: info: running /etc/cont-init.d/structure.sh
/package/admin/s6-overlay-3.1.0.1/etc/s6-rc/scripts/cont-init: line 14: /etc/cont-init.d/structure.sh: Permission denied
cont-init: info: /etc/cont-init.d/structure.sh exited 126
cont-init: warning: some scripts exited nonzero
s6-rc: warning: unable to start service legacy-cont-init: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by frenck** [comment]
As per: <https://developers.home-assistant.io/blog/2022/05/12/s6-overlay-base-images>

**Comment by frenck** [comment]
This has actually been resolved.
