### ISSUE TITLE
MQTT Self Signed Certificate error - no SSL connection possible

### ISSUE THREAD

**Issue by askmurphy** [home-assistant/addons#2501]
### Describe the issue you are experiencing

 I am trying to setup my MQTT addon, it works but when I am trying to connect via MQTT-Explorer (SSL, port 8883) the MQTT-explorer can't connect and gives an error: SELF SIGNED CERTIFICATE.
Ofcourse, I used my duckdns-domain.   If I connect locally, without SSL (port 1883) it works.

Maybe something is missing in the add-on or maybe It's my bad..  Don't know.  Tried discord already: there are a few with the same problem, but no fix..

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Mosquitto broker

### What is the version of the add-on?

6.1.2

### Steps to reproduce the issue

1. first: made my HA working with a duckdns.org domain, SSL connection works. 
2. mosquito setup done, testing with MQTT-explorer AND HELIUM Network MQTT integration
No SLL MQTT connection possible (SSL 8883 port ofcourse open and forwarded)

### Anything in the add-on logs that might be useful for us?

```txt
1653541785: New connection from 217.101.132.202:33829 on port 8883.
1653541785: OpenSSL Error[0]: error:1417C0C7:SSL routines:tls_process_client_certificate:peer did not return a certificate
1653541785: Client <unknown> disconnected: Protocol error.
1653541786: New connection from 217.101.132.202:33832 on port 8883.
1653541786: OpenSSL Error[0]: error:1417C0C7:SSL routines:tls_process_client_certificate:peer did not return a certificate
1653541786: Client <unknown> disconnected: Protocol error.
1653541788: New connection from 217.101.132.202:33837 on port 8883.
1653541788: Client <unknown> disconnected: Protocol error.
1653541788: New connection from 217.101.132.202:33840 on port 8883.
1653541788: Client <unknown> disconnected: Protocol error.
1653541797: New connection from 172.30.32.2:55790 on port 1883.
1653541797: Client <unknown> closed its connection.
1653541807: New connection from 217.101.132.202:33908 on port 8883.
1653541807: Client <unknown> disconnected: Protocol error.
```

### Additional information

Mosquito configuration:
```
logins: []
require_certificate: true
certfile: server.crt
keyfile: server.key
customize:
  active: true
  folder: mosquitto
  require_certificate: true
cafile: ca.crt
debug: false

```

**Comment by mdegat01** [comment]
It seems like you have two errors but I'm not sure:
> MQTT-explorer can't connect and gives an error: SELF SIGNED CERTIFICATE.
Sounds like you're presenting a self-signed certificate. If so you need to disable "validate certificate" in MQTT explorer. Or else upload the CA certificate you used to sign your self-signed certificate under advanced -> certificates -> server certificate.

```yaml
require_certificate: true
cafile: ca.crt
```
Did you mean to specify these two options? `require_certificate` requires that all clients which try to connect to your broker present a client certificate which is signed by the CA certificate specified in `cafile`. This is what is known as "mutual TLS".

To make this work you would need to generate a CA certificate file and provide it in `cafile`. And then generate a client certificate file signed by that CA cert and upload the cert and key in MQTT Explorer under advanced -> certificates -> Client certificate/key.

If all you want is to connect with your broker using SSL you should remove these two options. They are not required for that.

**Comment by freddylealg** [comment]
Please give one beer to this good man @mdegat01, thank you this works!!!
