### ISSUE TITLE
Conflict in WORKGROUP detection between  HA-Samba and UNRAID

### ISSUE THREAD

**Issue by d1964b** [home-assistant/addons#2502]
### Describe the issue you are experiencing

I'm getting multiple errors reported in the add-on logs for Samba reporting multiple responses for a query on the name WORKGROUP.  My setup is that HA runs as a VM ( using an ova image ) on my UNRAID server. UNRAID is my primary NAS and is a member of the workgroup called WORKGROUP as is HA. I am **guessing** these errors/warning are as a result of a master browser conflict between samba on UNRAID and HA.  Since HA cannot run unless UNRAID is first running I would like UNRAID to be the mbr. Is it possible to configure the HA-Samba add-on this way ? I've looked on the internet and the linuxtopia site gives an example of an smb.conf file to force samba not to be the master browser when it shares a subnet with an existing master browser, but I don't see any way to configure the add-on to do this , is it possible ? In the logs below 192.168.0.142 is the IP of may HA server and 192.168.0.110 is the IP of my UNRAID server, I only need samba on HA to expose the backup and config shares.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Samba share

### What is the version of the add-on?

9.6.1

### Steps to reproduce the issue

1. Install HA as VM on UNRAID and install Samba addon 
2. Both servers on same subnet and configured with the same workgroup name.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
No
```

### Anything in the add-on logs that might be useful for us?

```txt
query_name_response: Multiple (2) responses received for a query on subnet 192.168.0.142 for name WORKGROUP<1d>.
This response was from IP 192.168.0.110, reporting an IP address of 192.168.0.110.
query_name_response: Multiple (2) responses received for a query on subnet 192.168.0.142 for name WORKGROUP<1d>.
This response was from IP 192.168.0.110, reporting an IP address of 192.168.0.110.
Registered MSG_REQ_POOL_USAGE
query_name_response: Multiple (2) responses received for a query on subnet 192.168.0.142 for name WORKGROUP<1d>.
This response was from IP 192.168.0.110, reporting an IP address of 192.168.0.110.
Registered MSG_REQ_POOL_USAGE
Could not find child 2361 -- ignoring

waits a bit and repeats , 'child' count increases by 2 every time
```

### Additional information

Version 	core-2022.5.4
Installation Type 	Home Assistant OS
Development 	false
Supervisor 	true
Docker 	true
User 	root
Virtual Environment 	false
Python Version 	3.9.9
Operating System Family 	Linux
Operating System Version 	5.15.38
CPU Architecture 	x86_64
Timezone 	Europe/London

Home Assistant Supervisor
Host Operating System 	Home Assistant OS 8.0
Update Channel 	stable
Supervisor Version 	supervisor-2022.05.3
Docker Version 	20.10.14
Disk Total 	30.8 GB
Disk Used 	4.9 GB
Healthy 	true
Supported 	true
Board 	ova
Supervisor API 	ok
Version API 	ok
Installed Add-ons 	Samba share (9.6.1), Terminal & SSH (9.4.0), Check Home Assistant configuration (3.10.0), AppDaemon (0.8.2)

**Comment by mdegat01** [comment]
Could you just pick a different workgroup or is there some advantage conferred by having the same one? Also could you share the resources you found showing this issue and how to resolve it by forcing one to not be the master browser? I know addons but I'm not really a samba expert at all.

**Comment by d1964b** [comment]
Not really, the whole point of joining a shared network, like a workgroup, is that each member of the group can see the resources exposed by the other. To do that they all need to be joining the same workgroup.
The linuxtopia resource I was referring to was this [](https://www.linuxtopia.org/online_books/network_administration_guides/samba_reference_guide/17_NetworkBrowsing_11.html) ideally I'd like the addon to expose those elements that would allow the variables covered in the example "Example9.3.smb.conf for Not Being a Master Browser" , since I already have a DMB from the UNRAID SMB service and I only have one subnet. So have no need for any browser elections as a result of HA starting or stopping. I simply would like the Samba addon in HA too offer the option to join the existing workgroup. 
I could live with it forcing an election once on startup but I particularly don't need the  HA addon trying to force an election every 5 minutes to see if a new master is required ( as useful as that functionality might be in other contexts). Thanks

**Comment by d1964b** [comment]
Even if we could just specify the following in the smb.conf : 

 [global]
local master = no 

might be enough , since ( to the best of my recollection ) a DMB is usually the LMB in its subnet. So by specifying the above you could force it to be neither and just participate as a server in the workgroup whose name you have already provided.
