### ISSUE TITLE
Using NGINX Home Assistant SSL proxy with just an IP is not working.

### ISSUE THREAD

**Issue by zolan** [home-assistant/addons#2504]
### Describe the issue you are experiencing

I know I will be asked why I am doing this so I'll get that out of the way first.   Yes, my SSL cert is valid for my domain as well as internal IP addresses of my home network.  It is self signed and I have my own CA.  So everything to do with the SSL cert is fine for how I'm using it.

The reason I am using the IP only is that I don't want to have this connected to the internet at all.  I'm a paranoid bastard.  When I leave my house, my phone automatically connects to my personal home's VPN and I still have connection to my home assistant setup.  I used the IP because having a hostname in this situation would mean I needed to modify all phones to either have a static host lookup or do something funky with DNS.   I don't want to deal with that so I just use the IP.

Now that that is all over here is the problem.   If I set my 'domain' as the IP address in the config settings it builds the config file the way I would expect it to.  However, all connections to https://XXX.XXX.XXX.XXX  end up hitting the first 'default' server stanza in the config.

I've played around with it and tried using a regex of my IP, my IP and _, just _.   Nothing seems to work.  However, if I simply remove that first default server stanza, it works perfectly (obviously I had to hump nginx after each change to try it out).

Anyway, the bare minimum config change that I can make that makes this work as expected is removing 'default_server' from the listen line in the first stanza and adding it to the real ssl server stanza's listen line.    If I do only that, it works totally fine.

So either, I'm not specifying my IP address correctly so it isn't matching at all or something else weird is happening.   I realize there is an off chance that this is not a bug and may only require some unknown config change on my side but I feel like there has to be a simple change that can happen to the default config file to make this work for people like me.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### Which add-on are you reporting an issue with?

NGINX Home Assistant SSL proxy

### What is the version of the add-on?

3.1.1

### Steps to reproduce the issue

1. Set up a HA system.
2. Build a self signed SSL cert that works with a specific private IP address of your internal network (this took me days to get perfect)
3. Add the key and cert to fullchain.pem and privkey.pem.
4. Install NGINX addon.
5. Set the domain to your IP address.
6. Tell it to listen on port 443 (I think I had to do this?  I don't recall if it was already set to do so.)
7. Start the addon.
8. Try it.  It will give you a 400 Bad Request:

9. TO FIX:

10. Connect to the running docker container for the NGINX proxy.
11. Alter the config and remove 'default_server' from the first server stanza's listen line.   Add 'default_server' to the 3rd server stanza's listen line.
12. Find the main nginx process and HUP it via kill -1 <PID>.
13. Try again and it works beautifully.

### Anything in the Supervisor logs that might be useful for us?

```txt
I don't believe so.  As far as the addon is concerned it is working beautifully all the time.
```

### Anything in the add-on logs that might be useful for us?

```txt
I don't believe so.  As far as the addon is concerned it is working beautifully all the time.
```

### Additional information

I really hope I gave enough information.  I tried to be extremely detailed.

If the config helps here is the working version (you can diff it with the 3.1.1 default config file to see the moving of the 'default_server'.

```
daemon off;
error_log stderr;
pid /var/run/nginx.pid;

events {
        worker_connections 1024;
}

http {
    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }

    server_tokens off;

    server_names_hash_bucket_size 64;

    #include /data/cloudflare.conf;

    server {
        server_name _;
        listen 80;
        listen 443 ssl http2;    # <-  Removed 'default_server'.
        ssl_certificate /data/ssl-cert-snakeoil.pem;
        ssl_certificate_key /data/ssl-cert-snakeoil.key;
        return 444;
    }

    server {
        server_name  192.168.XX.XX;   # <- This is actually the full IP.  I just redacted the last two octets because... paranoia.

        # These shouldn't need to be changed
        listen 80 default_server;
        return 301 https://$host$request_uri;
    }

    server {
        server_name  192.168.XX.XX;  #< - Same.  Paranoia.

        ssl_session_timeout 1d;
        ssl_session_cache shared:MozSSL:10m;
        ssl_session_tickets off;
        ssl_certificate /ssl/fullchain.pem;
        ssl_certificate_key /ssl/privkey.pem;

        # dhparams file
        ssl_dhparam /data/dhparams.pem;

        listen 443 ssl http2 default_server;   # <- Added 'default_server'
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

        # intermediate configuration
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
        ssl_prefer_server_ciphers off;

        proxy_buffering off;

        #include /share/nginx_proxy_default*.conf;

        location / {
            proxy_pass http://homeassistant.local.hass.io:8123;
            proxy_set_header Host $host;
            proxy_redirect http:// https://;
            proxy_http_version 1.1;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
        }
    }

    #include /share/nginx_proxy/*.conf;
}

```

One final idea.  I realize I'm a way outside edge case but if this had a similar mechanism to the Terminal/SSH addon where we could specify some packages to be installed and specify some commands to run before this starts, I could take care of this myself with sed and whatnot.   Or even some string that gets ran as part of the run.sh script?

If you guys want nothing to do with any of this, I would also be willing to fork this for my own personal use and make the mods to work with my specific setup but I would really appreciate some pointers to how to do so and how to get it added to my HA install.

Anyway, thank you for the help in advance.

**Comment by mdegat01** [comment]
I think I'm missing something. Wouldn't it be easier to just ditch the reverse proxy and put your certificate [in HA](https://www.home-assistant.io/integrations/http/#ssl_certificate)? Then just change HA's default port from 8123 to 443.

Is there some reason you need HA listening on 8123? Seems like the reverse proxy is just adding overhead in this case since you just want to connect to HA by IP address anyway. If the only purpose of the proxy is to make HA listen on port 443 then you don't need a reverse proxy for that. HA can listen on whatever port you want and serve up whatever ssl certificates you tell it to.

Also just as an aside, you might find [this guide](https://github.com/dani-garcia/vaultwarden/wiki/Running-a-private-vaultwarden-instance-with-Let%27s-Encrypt-certs#cloudflare-setup) handy given your desired setup. It shows how to run a totally private vaultwarden instance that's not accessible outside your LAN with a completely valid and verifiable Let's Encrypt certificate. Basically just replace Vaultwarden with HA and you can do the same. Then you don't have to deal with self-signed cert errors and manually uploading certs to every machine.

**Comment by mdegat01** [comment]
No its not deprecated. Generally I do actually recommend a reverse proxy to people over putting the SSL certs in HA. I do this for a few reasons:
1) It allows people to communicate with HA unencrypted in their LAN and encrypted outside their LAN. Usually people prefer this. Also its required for some things like to be able to use local fulfillment with Google Assistant
2) It means external clients are actually talking to something like NGinx rather then directly to HA. This allows people to establish further controls on communication if necessary.
3) While HA is secure, very few pieces of software are battle-hardened the way Nginx is. So I would prefer external clients talk directly to it and indirectly to HA personally.

But none of those 3 actually apply to your use case. You don't want unencrypted LAN communication and HA is accessible only within your LAN. So in this case the reverse proxy seems like unnecessary overhead.

**Comment by zolan** [comment]
Totally makes sense.  I did like the idea of using NGINX but I'm fine with HA handling this since I have it so locked down anyway.

I'll go ahead and close this issue since I don't think anything will be done with it.   Thank you very much for your help.
