### ISSUE TITLE
Deconz update

### ISSUE THREAD

**Issue by matteos1** [home-assistant/addons#2506]
### Describe the issue you are experiencing

When i try to update deconz an error appear
Can't install homeassistant/aarch64-addon-deconz:6.14.0: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=6.14.0&fromImage=homeassistant%2Faarch64-addon-deconz&platform=linux%2Farm64: Not Found ("manifest for homeassistant/aarch64-addon-deconz:6.14.0 not found: manifest unknown: manifest unknown")

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

deCONZ

### What is the version of the add-on?

6.14.0

### Steps to reproduce the issue

1.update
2.error
3. Can't install homeassistant/aarch64-addon-deconz:6.14.0: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=6.14.0&fromImage=homeassistant%2Faarch64-addon-deconz&platform=linux%2Farm64: Not Found ("manifest for homeassistant/aarch64-addon-deconz:6.14.0 not found: manifest unknown: manifest unknown")

...

**Comment by ludeeus** [comment]
That happens when the image is not done building, try it again later.

**Comment by matteos1** [comment]
I just update but now:
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/firmware.sh
/package/admin/s6-overlay-3.1.0.1/etc/s6-rc/scripts/cont-init: 14: /package/admin/s6-overlay-3.1.0.1/etc/s6-rc/scripts/cont-init: /etc/cont-init.d/firmware.sh: Permission denied
cont-init: info: /etc/cont-init.d/firmware.sh exited 126
cont-init: info: running /etc/cont-init.d/nginx.sh
/package/admin/s6-overlay-3.1.0.1/etc/s6-rc/scripts/cont-init: 14: /package/admin/s6-overlay-3.1.0.1/etc/s6-rc/scripts/cont-init: /etc/cont-init.d/nginx.sh: Permission denied
cont-init: info: /etc/cont-init.d/nginx.sh exited 126
cont-init: info: running /etc/cont-init.d/novnc.sh
/package/admin/s6-overlay-3.1.0.1/etc/s6-rc/scripts/cont-init: 14: /package/admin/s6-overlay-3.1.0.1/etc/s6-rc/scripts/cont-init: /etc/cont-init.d/novnc.sh: Permission denied
cont-init: info: /etc/cont-init.d/novnc.sh exited 126
cont-init: warning: some scripts exited nonzero
s6-rc: warning: unable to start service legacy-cont-init: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by ludeeus** [comment]
Fixed by #2507
