### ISSUE TITLE
Deconz and aqara p1

### ISSUE THREAD

**Issue by matteos1** [home-assistant/addons#2508]
### Describe the issue you are experiencing

When i try to paring aqara p1 to deconz, deconz found new sensor but at the end of process, the sensor not appear in the list. 

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

deCONZ

### What is the version of the add-on?

2.16.1

### Steps to reproduce the issue

1. Opene deconz
2. Sensor
3. Found new sensor. 
Senor is found but i cannot click to add new sensor aqara p1...

**Comment by frenck** [comment]
This is not something we can fix from the add-on. Add-ons wrap existing software, in this case the deCONZ software by dresden. Once they add support for it, the add-on will gain it as well.

Please request it as a feature with them.

Thanks! 👍 

../Frenck
