### ISSUE TITLE
requests.exceptions.ConnectionError

### ISSUE THREAD

**Issue by Tntdruid** [home-assistant/addons#2515]
### Describe the issue you are experiencing

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] file-structure.sh: executing... 
[cont-init.d] file-structure.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[10:02:46] INFO: Selected DNS Provider: dns-linode
[10:02:46] INFO: Use propagation seconds: 360
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Account registered.
Requesting a certificate for *.mydomain.tld
Waiting 120 seconds for DNS changes to propagate
An unexpected error occurred:
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### Which add-on are you reporting an issue with?

Let's Encrypt

### What is the version of the add-on?

4.12.2 

### Steps to reproduce the issue

1.
2.
3.
...
Addon was working fine when i added the cert, now it wont renew.

**Comment by mdegat01** [comment]
Can you share your [system health](https://my.home-assistant.io/redirect/system_health/) information? Also could you run `ha resolution info` in the CLI and share that output as well?

**Comment by Tntdruid** [comment]
Did a reinstall of the Addon now its works.
