### ISSUE TITLE
Z-Wave JS 0.1.60 doesn't listen on 3000/tcp

### ISSUE THREAD

**Issue by AltumSE** [home-assistant/addons#2516]
### Describe the issue you are experiencing

After migration from RPi3 (SD card) to RPi4 (SSD) Zwave stopped working.
Analyzes show that Z-Wave JS add-on doesn't listen on port 3000/tcp. I connected to the container and verified as well, there where no services on the container listening on 3000/tcp.
Remove all configuration, integration and add-on. Followed by reboot and install of add-on and integration, then the integration warns that it can't connect to on 172.30.33.1 3000/tcp. Verified the IP and connected to the container to verify that the service isn't listening.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### Which add-on are you reporting an issue with?

Z-Wave JS

### What is the version of the add-on?

0.1.60

### Steps to reproduce the issue

1. Install add-on
2. Creat integration
3. Fail to connect
...

### Anything in the add-on logs that might be useful for us?

```txt
No logs of interest, even when changing log level.
Should say something about starting service on tcp/3000
```

### Additional information

On the console of the container:

bash-5.1# ps aux
PID   USER     TIME  COMMAND
    1 root      0:00 /package/admin/s6/command/s6-svscan -d4 -- /run/service
   15 root      0:00 s6-supervise s6-linux-init-shutdownd
   18 root      0:00 /package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B
   22 root      0:00 s6-supervise s6rc-oneshot-runner
   23 root      0:00 s6-supervise s6rc-fdholder
   30 root      0:00 /package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i d
  340 root      0:00 s6-supervise zwave_js
  392 root      0:00 bash
  403 root     24:30 node /usr/src/node_modules/.bin/zwave-server /dev/ttyAMA0 --config /etc/zwave_config.json --disable-dns-sd
  426 root      0:00 [bash]
  455 root      0:00 bash
  461 root      0:00 ps aux

bash-5.1# netstat -tulpan
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.11:42435        0.0.0.0:*               LISTEN      -
udp        0      0 127.0.0.11:43633        0.0.0.0:*                           -

bash-5.1# nc -nv 127.0.0.1 3000
<No connection - No response>

**Comment by MartinHjelmare** [comment]
What are you selecting in the config flow when setting up the integration?

**Comment by pnugent1980** [comment]
Bizarrely I encountered this exact same issue yesterday too, I migrated from RPi3 toRPi4. I've uninstalled and reinstalled the zwave-js add-on but it doesn't listen on port 3000. If I set a port in Settings -> Add-on -> Zwave-js -> Configuration -> Show disabled ports -> Type '3000' -> Save -> Restart I can see that port listening when I run a netstat but it doesn't help.

**Comment by AltumSE** [comment]
If I check the box "Use the Z-Wave JS Supervisor add-on" I get "Failed to connect"
If I uncheck the box "Use the Z-Wave JS Supervisor add-on" and add "ws://core-zwave-js:3000" or "ws://172.30.33.1:3000" as URL  I get "Failed to connect".
The problem isn't with the configuration, it's that the service isn't listening on port tcp/3000.

I could restart the service in the add-on container myself, but I are uncertain of the arguments and attributes.

**Comment by pnugent1980** [comment]
I solved my problem, it's a pre-existing issue with my Aeotec Z-Stick Gen5 not being compatible with the RPi4. I reconnected it using a USB hub. Once reconnected and the config back to default with the controller selected it started working for me. I had to stop the add-on and then change the config to have it work as reloading didn't appear to work. I then reloaded the integration and it detected the stick and slave devices.

**Comment by AltumSE** [comment]
That solved my issues also.
The question now is why couldn't I see this in the logs and why does that result in that the "node" process doesn't listen on port tcp/3000?

**Comment by NilsKrumrey** [comment]
I had the same issue with my Aeotec Z-Stick Gen 5. I tried following your steps but service would fail to start correctly, saying the driver was in use - my only rescue was restoring an older version of the add-on. Would you mind repeating step by step what you did to fix this? I have tried stopping the addon and trying to reset to default, but it keeps my USB stick selected and I also don’t know when to replug the stick - I am not actually running on a a PI, but in a VM on a Synology NAS with USB pass through yet still have the same issue.
