### ISSUE TITLE
Genie certificate expired

### ISSUE THREAD

**Issue by KeithSBB** [home-assistant/addons#2519]
### Describe the issue you are experiencing

Genie only responds to any request with: Sorry, I had an error processing your command: certificate has expired.
I'm not having any issues with other add-ons/integrations which use certificates (like duckdns / let's encyrpt so I can cast dashboards to chromecast devices)

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Almond

### What is the version of the add-on?

3.0.0

### Steps to reproduce the issue

1.type in a query

### Anything in the Supervisor logs that might be useful for us?

```txt
see nothing in HA logs
```

### Anything in the add-on logs that might be useful for us?

```txt
genie::conversation::Client-Message: 20:59:52.734: Received message: {"type":"command","command":"what time is it","id":7}
Saving conversation state for main (20 characters)
Received assistant command what time is it
Error processing queue item UserInput {
  command: { type: 'command', utterance: 'what time is it', platformData: {} }
}
Error: certificate has expired
    at TLSSocket.onConnectSecure (_tls_wrap.js:1502:34)
    at TLSSocket.emit (events.js:314:20)
    at TLSSocket._finishInit (_tls_wrap.js:937:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:711:12) {
  code: 'CERT_HAS_EXPIRED'
}
Genie says: Sorry, I had an error processing your command: certificate has expired.
```

### Additional information

this just started a couple of days ago and there are a few others reporting this on Chat

**Comment by Johnnii360** [comment]
Yepp, same here.

**Comment by KeithSBB** [comment]
Yes, its working for me
