### ISSUE TITLE
Samba Add-ons: No supported interfaces found to bind on.

### ISSUE THREAD

**Issue by rotrials** [home-assistant/addons#2523]
### Describe the issue you are experiencing

Hello developers, 
It seems that the samba add-on does not start anymore.

I'm running the homeassistant in a docker, on an Odroid H2 with arch linux.
core-2022.6.4
supervisor-2022.05.3

I hope you can help.
Thank you.

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### Which add-on are you reporting an issue with?

Samba share

### What is the version of the add-on?

 9.6.1

### Steps to reproduce the issue

1.
2.
3.
...

### Anything in the add-on logs that might be useful for us?

```txt
s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] samba.sh: executing... 
[22:10:54] INFO: Hostname: ladacumasline
[22:10:54] FATAL: No supported interfaces found to bind on.
[cont-init.d] samba.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by ludeeus** [comment]
Your installation is not supported.

**Comment by rotrials** [comment]
What is not supported? What do you mean? 
It worked before some core updates.

**Comment by ludeeus** [comment]
<https://github.com/home-assistant/architecture/blob/master/adr/0012-define-supported-installation-method.md>
<https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md>

"Odroid H2 with arch linux" is not supported.

Your posted logs also tell you "No **supported** interfaces found to bind on."

Use https://www.home-assistant.io/installation/ to install Home Assistant.

**Comment by rotrials** [comment]
As I said, it's running in a docker and it should not care what kind of device am I'm using, Odroid h2 it's a x64 architecture, like a NUC.
It worked before. The reason why it's not working anymore it's not the Odroid!

**Comment by kazir1** [comment]
> As I said, it's running in a docker and it should not care what kind of device am I'm using, Odroid h2 it's a x64 architecture, like a NUC. It worked before. The reason why it's not working anymore it's not the Odroid!

Hello. Did you manage to fix it? I have the same thing. After reinstalling the new system, everything broke down.

**Comment by rotrials** [comment]
> > As I said, it's running in a docker and it should not care what kind of device am I'm using, Odroid h2 it's a x64 architecture, like a NUC. It worked before. The reason why it's not working anymore it's not the Odroid!
> 
> Hello. Did you manage to fix it? I have the same thing. After reinstalling the new system, everything broke down.

No, still not working. But know I'm using https://github.com/lmagyar/homeassistant-addon-samba-interface
