### ISSUE TITLE
Xiaomi / Aqara unavailable 

### ISSUE THREAD

**Issue by herveaurel** [home-assistant/addons#2526]
### Describe the issue you are experiencing

Since the last update of deconz I very often lose motion detectors and wireless switch buttons.  Sometimes I lose them several times a day, I have to start pairing again

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### Which add-on are you reporting an issue with?

deCONZ

### What is the version of the add-on?

6.14.1

### Steps to reproduce the issue

1.
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
2022.05.3
```

**Comment by frenck** [comment]
Hi there @herveaurel 👋 

Unfortunately, this is not something we can improve from the add-on perspective.
Please report this issue with dresden, which creates the deCONZ software this add-on packages.

If they fix the issue and release it with an update; the add-on will be update to include that.


../Frenck

**Comment by herveaurel** [comment]
Ok ! Thanks !
