### ISSUE TITLE
nginx_proxy TLS 1.3

### ISSUE THREAD

**Issue by Delta1977** [home-assistant/addons#2527]
### Describe the issue you are experiencing

As TLS 1.3 is enabled via config id didn’t work. Only tls 1.2 works. This can be checked via did tools

In ngix.conf line 51 variable for hsts is used and I think the variable didn’t has the ; ad end so the config for ssl_protocols wollen be found. 

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

NGINX Home Assistant SSL proxy

### What is the version of the add-on?

Stable

**Comment by Delta1977** [comment]
https://github.com/home-assistant/addons/blob/2d2df782e6d44e141744579e8c5705721dbad87b/nginx_proxy/data/nginx.conf#L51 Missing ; at End of line

**Comment by mdegat01** [comment]
When HSTS is used the setup script replaces that placeholder with this config:
https://github.com/home-assistant/addons/blob/2d2df782e6d44e141744579e8c5705721dbad87b/nginx_proxy/data/run.sh#L59

Which has a semicolon at the end as you can see. So I don't think that's the issue? Are you seeing this in the generated config used at runtime or just looking at the template?

**Comment by Delta1977** [comment]
> When HSTS is used the setup script replaces that placeholder with this config:
> 
> https://github.com/home-assistant/addons/blob/2d2df782e6d44e141744579e8c5705721dbad87b/nginx_proxy/data/run.sh#L59
> 
> Which has a semicolon at the end as you can see. So I don't think that's the issue? Are you seeing this in the generated config used at runtime or just looking at the template?

only at template. no easy access to runtime config.
i thought that would be the problem. I connected my HA via nginx proxy. According to the config, TLS 1.3 is also active. Unfortunately, a test via Qualys SSL Labs or others shows that TLS 1.3 is not active, only TLS 1.2. Can you check that in your instance if TLS 1.3 works?

**Comment by zeehio** [comment]
I can verify that in my own home Assistant setup that Qualsys SSL Labs reports that TLS 1.3 is not supported. My browser and curl agree with Qualsys.

I was able to fix this issue by changing some SSL directives from the server block into the http block, as suggested by https://serverfault.com/questions/1097716/tls-1-3-not-working-on-nginx-1-21-with-openssl-1-1-1n

I will cleanup my changes and submit a pull request
