### ISSUE TITLE
MariaDB: user can't create new databases (MariaDB and Kodi don't cooperate)

### ISSUE THREAD

**Issue by Lukanex** [home-assistant/addons#2531]
Hi,

In short, I cannot find settings to let the DB user create new databases.
I tested the DB creation on a fresh `RPi4 with Raspbian 32 with MariaDB` - the user can create new databases there, not in the HASSIO add-on.

Similarly to https://github.com/home-assistant/addons/issues/952, neither one of my Kodi devices can create the media databases in MariaDB addon on HA RPi4 HASSIO (on USB boot SSD).
Kodi devices: 
- v19.4 on Windows 10,
- RPi4 LibreElec,
- RPi4 OSMC.

I can read and delete databases of MariaDB addon in HASSIO using the `homeassistant` user and `kodi` user, no problem (using DBeaver)

MariaDB addon rejects access if a wrong password is used, but does not log anything when Kodi cannot create a database.

I am ready to post logs from various tests, but I would like to hear whether someone could possibly spare time for helping me first please...

Some examples of the test cases:

I tested the DB creation on a fresh `RPi4 with Raspbian 32 with MariaDB` and the same settings with only the database IP changed it worked immediately. (Interestingly, Kodi created databases with trailing numbers compared to the specific names in advancedsettings.xml `<name>` e.g.: `kodi_music` -> `kodi_music82`
These numbers are (according to online sources) the database version depending on the Kodi updates.

```
2022-06-16 14:43:50.843 T:25180    INFO <general>: MYSQL: Connected to version 10.5.15-MariaDB-0+deb11u1
2022-06-16 14:43:50.868 T:25180    INFO <general>: Running database version kodi_music82
2022-06-16 14:43:50.892 T:25180    INFO <general>: Running database version kodi_video119
```

MariaDB does not seem to accept this behavior / new database creation.
(I also tested a fresh HASSIO installation on an SD card, with a fresh MariaDB, both the latest versions, no difference there.)

But even naming the database in HASSIO same as Kodi created on Raspbian does not help. The database is obviously empty and Kodi cannot create the tables either (not sure, whether it's even trying to).

```
<advancedsettings>
    <videodatabase>
        <type>mysql</type>
        <name>kodi_videos</name>
        <host>10.0.0.2</host>
        <port>3307</port>
        <user>kodi</user>
        <pass>********</pass>
    </videodatabase>
    <musicdatabase>
        <type>mysql</type>
        <name>kodi_music</name>
        <host>10.0.0.33</host>           ***** intentionally left talking to the Raspbian server
        <port>3306</port>
        <user>kodi</user>
        <pass>********</pass>
    </musicdatabase>
</advancedsettings>
```
```
2022-06-16 14:58:03.971 T:24604    INFO <general>: MYSQL: Connected to version 10.5.15-MariaDB-0+deb11u1
2022-06-16 14:58:03.994 T:24604    INFO <general>: Running database version kodi_music82
2022-06-16 14:58:06.042 T:24604   ERROR <general>: Unable to open database: kodi_videos119 [2002](Can't connect to MySQL server on '10.0.0.2' (10061))
2022-06-16 14:58:07.807 T:20236    INFO <general>: CIRServerSuite::Process: failed to connect to irss, will keep retrying every 5 seconds
2022-06-16 14:58:08.117 T:24604   ERROR <general>: Unable to open database: kodi_videos118 [2002](Can't connect to MySQL server on '10.0.0.2' (10061))
2022-06-16 14:58:10.154 T:24604   ERROR <general>: Unable to open database: kodi_videos117 [2002](Can't connect to MySQL server on '10.0.0.2' (10061))
.
.
.
2022-06-16 14:59:26.162 T:24604   ERROR <general>: Unable to open database: kodi_videos80 [2002](Can't connect to MySQL server on '10.0.0.2' (10061))
2022-06-16 14:59:28.233 T:24604   ERROR <general>: Unable to open database: kodi_videos79 [2002](Can't connect to MySQL server on '10.0.0.2' (10061))
2022-06-16 14:59:30.287 T:24604   ERROR <general>: Unable to open database: kodi_videos78 [2002](Can't connect to MySQL server on '10.0.0.2' (10061))
2022-06-16 14:59:32.344 T:24604   ERROR <general>: Unable to open database: kodi_videos77 [2002](Can't connect to MySQL server on '10.0.0.2' (10061))
2022-06-16 14:59:34.406 T:24604   ERROR <general>: Unable to open database: kodi_videos76 [2002](Can't connect to MySQL server on '10.0.0.2' (10061))
2022-06-16 14:59:36.460 T:24604   ERROR <general>: Unable to open database: kodi_videos75 [2002](Can't connect to MySQL server on '10.0.0.2' (10061))
2022-06-16 14:59:38.512 T:24604   ERROR <general>: Unable to open database: kodi_videos119 [2002](Can't connect to MySQL server on '10.0.0.2' (10061))
2022-06-16 14:59:38.512 T:24604   ERROR <general>: Unable to create new database
```

<img width="335" alt="image" src="https://user-images.githubusercontent.com/26509386/174064990-5aef67c5-5294-418e-85f0-bc51ce6d0f77.png">
<img width="539" alt="image" src="https://user-images.githubusercontent.com/26509386/174065066-05a98f1e-ebcf-4f9c-b3e2-8b810bf9e94b.png">

MadiaDB yaml:
```
databases:
  - homeassistant
  - ha-readonly
  - kodi_video
  - kodi_music82
logins:
  - password: ********
    username: homeassistant
  - username: ha-readonly
    password: ********
  - password: ********
    username: kodi
    host: '%'
    skip-netwroking: 0
    skip-bind-address: 0
rights:
  - database: homeassistant
    username: homeassistant
  - username: ha-readonly
    database: homeassistant
    privileges:
      - SELECT
  - database: kodi_video
    username: kodi
    host: '%'
  - database: kodi_music82
    username: kodi
    host: '%'
```

Kodi log after naming the empty DB on HA kodi_music82
```
2022-06-16 13:44:41.035 T:14580    INFO <general>: MYSQL: Connected to version 10.4.19-MariaDB
2022-06-16 13:44:41.058 T:14580   ERROR <general>: SQL: [kodi_music82] The table does not exist
                                                   Query: SELECT idVersion FROM version
```

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

MariaDB

### What is the version of the add-on?

2.4.0

### Steps to reproduce the issue

1. fresh installation of Kodi
2. fresh installation of MariaDB add-on
3. standard settings:

MariaDB
```
databases:
  - homeassistant
  - ha-readonly
  - kodi_video119
  - kodi_music82
logins:
  - password: homeassistant
    username: homeassistant
  - username: homeassistant
    password: ha-readonly
  - password: kodi
    username: kodi
    host: '%'
    skip-netwroking: 0
    skip-bind-address: 0
rights:
  - database: homeassistant
    username: homeassistant
  - username: ha-readonly
    database: homeassistant
    privileges:
      - SELECT
  - database: kodi_video119
    username: kodi
    host: '%'
  - database: kodi_music82
    username: kodi
    host: '%'
```

Kodi
```
<advancedsettings>
    <videodatabase>
        <type>mysql</type>
        <name>kodi_video</name>
        <host>10.0.0.2</host>
        <port>3306</port>
        <user>kodi</user>
        <pass>kodi</pass>
    </videodatabase>
    <musicdatabase>
        <type>mysql</type>
        <name>kodi_music</name>
        <host>10.0.0.2</host>
        <port>3306</port>
        <user>kodi</user>
        <pass>kodi</pass>
	</musicdatabase>
</advancedsettings>
```

...

### Anything in the Supervisor logs that might be useful for us?

```txt
No
```

### Anything in the add-on logs that might be useful for us?

```txt
Nothing additional in the log after the add-on starts
```

**Comment by Lukanex** [comment]
Wow, after even more reading and testing, I believe I found the solution:
MariaDB seems to let Kodi create a database when it does not exit - under specific condition.

1. The kodi user must exist and 
2. The kodi user must have a database right assigned, 
3. But the database must not exist.

First set MariaDB with (left the `ha-readonly` out, it's optional):
```
databases:
  - homeassistant
logins:
  - password: mypass123
    username: homeassistant
  - password: kodi
    username: kodi
    host: '%'
    skip-netwroking: 0
    skip-bind-address: 0
rights:
  - database: homeassistant
    username: homeassistant
  - database: kodi_video119
    username: kodi
    host: '%'
    grant: ALL PRIVILEGES ON
  - database: kodi_music82
    username: kodi
    host: '%'
    grant: ALL PRIVILEGES ON
```

Some parameters are still probably excessive like `grant: ALL PRIVILEGES ON`, which is the default in this add-on.

Then Kodi (`\userdata\advancedsettings.xml` must be created, does not exist after a new installation):
```
<advancedsettings>
    <videodatabase>
        <type>mysql</type>
        <name>kodi_video</name>
        <host>10.0.0.2</host>
        <port>3306</port>
        <user>kodi</user>
        <pass>kodi</pass>
    </videodatabase>
    <musicdatabase>
        <type>mysql</type>
        <name>kodi_music</name>
        <host>10.0.0.2</host>
        <port>3306</port>
        <user>kodi</user>
        <pass>kodi</pass>
	</musicdatabase>
</advancedsettings>
```

That way Kodi was able to create the database in HASSIO MariaDB add-on.

Please let me know if there is even a better way.

**Comment by mdegat01** [comment]
`host` and `grant` aren't options in the addon under `privileges`. The schema of that list is here:
https://github.com/home-assistant/addons/blob/2f2db170b3157ca8018e4a106bf97896967753da/mariadb/config.yaml#L34-L40

Same with `host`, `skip-networking` and `skip-bind-address` under `logins`, here's that schema:
https://github.com/home-assistant/addons/blob/2f2db170b3157ca8018e4a106bf97896967753da/mariadb/config.yaml#L31-L33

So you've probably got warnings in your supervisor log about unrecognized options being listed. Those just get removed when the config is validated so they aren't doing anything.

Im glad it's working for you though I guess even though I'm not totally sure what changed...
