### ISSUE TITLE
error: received null username or password for unpwd check

### ISSUE THREAD

**Issue by Tomax77** [home-assistant/addons#2535]
### Describe the issue you are experiencing

After upgrading mosquitto broker my entities cannot connect anymore and I receive many error messages. No solution postet on git or anywhere else can solve this problem.

In log I receive repeated errors like this:
```
1655652464: Client <unknown> disconnected, not authorised.
1655652479: New connection from XXXXXX:51778 on port 1883.
error: received null username or password for unpwd check
1655652479: Client <unknown> disconnected, not authorised.
1655652494: New connection from XXXXXX:51780 on port 1883.
error: received null username or password for unpwd check
1655652494: Client <unknown> disconnected, not authorised.
```

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Mosquitto broker

### What is the version of the add-on?

6.1.2

### Steps to reproduce the issue

After upgrading from 6.0.2 to 6.1.1 or 6.1.2 my entities aren't recovered any more and I receive many error messages in log.

**Comment by mdegat01** [comment]
Anonymous logins aren't supported by this addon, make sure all clients are using a username and password to connect.

Support for that was supposed to be removed in v6.0.0 but was accidently left enabled due to a bug. Support for anonymous logins was actually removed in v6.1.0. See #2483 for more info

**Comment by Yngve0** [comment]
I am using Telldus Plugin MQTT Homassistant (https://github.com/quazzie/tellstick-plugin-mqtt-hass/issues
). I have created an account in HASS which I use in the Telldus-plugin.

error: received null username or password for unpwd check

Anyone who have a clue?

**Comment by marklise** [comment]
> I am using Telldus Plugin MQTT Homassistant (https://github.com/quazzie/tellstick-plugin-mqtt-hass/issues ). I have created an account in HASS which I use in the Telldus-plugin.
> 
> error: received null username or password for unpwd check
> 
> Anyone who have a clue?

See the answer above: https://github.com/home-assistant/addons/issues/2535#issuecomment-1160641036

You need to create a username/password in the mosquitto broker plugin as anonymous is not allowed (which is what your are likely doing)

![image](https://user-images.githubusercontent.com/51633/210116626-81f41e8c-a679-4d28-ab8d-91115f10ff71.png)
