### ISSUE TITLE
ZWave JS upgrade from 1.61 to 1.62 broke my installation.

### ISSUE THREAD

**Issue by Lymkin** [home-assistant/addons#2540]
### Describe the issue you are experiencing

The upgrade broke my installation with the following errors.

```
2022-06-21 12:09:17 ERROR (MainThread) [homeassistant.components.zwave_js] Failed to connect: Cannot connect to host core-zwave-js:3000 ssl:default [Connect call failed ('172.30.33.4', 3000)]
2022-06-21 12:09:17 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Z-Wave JS' for zwave_js integration not ready yet: Cannot connect to host core-zwave-js:3000 ssl:default [Connect call failed ('172.30.33.4', 3000)]; Retrying in background
```

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### Which add-on are you reporting an issue with?

Z-Wave JS

### What is the version of the add-on?

1.62

### Steps to reproduce the issue

1. Run the ZWave JS addon upgrade process from Home Assistant
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
2022-06-21 12:09:17 ERROR (MainThread) [homeassistant.components.zwave_js] Failed to connect: Cannot connect to host core-zwave-js:3000 ssl:default [Connect call failed ('172.30.33.4', 3000)]
2022-06-21 12:09:17 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Z-Wave JS' for zwave_js integration not ready yet: Cannot connect to host core-zwave-js:3000 ssl:default [Connect call failed ('172.30.33.4', 3000)]; Retrying in background
```

**Comment by yormedia** [comment]
same here

**Comment by eremid** [comment]
Hello,

Same here. No logs. The docker container is running but 0 logs. Just rolled back with backup and it's ok.

The ps in the 0.1.62 :
```
PID   USER     TIME  COMMAND                                                                                                                                                                                                                      
    1 root      0:00 /package/admin/s6/command/s6-svscan -d4 -- /run/service                                                                                                                                                                      
   15 root      0:00 {rc.init} /bin/sh -e /run/s6/basedir/scripts/rc.init top                                                                                                                                                                     
   17 root      0:00 s6-supervise s6-linux-init-shutdownd                                                                                                                                                                                         
   19 root      0:00 /package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B                                                                                                                                
   21 root      0:00 s6-rc-init -c /run/s6/db /run/service                                                                                                                                                                                        
   22 root      3:49 /package/admin/s6/command/s6-ftrigrd                                                                                                                                                                                         
   23 root      0:00 bash                                                                                                                                                                                                                         
   31 root      0:00 ps auxwf                
```                                                                                                                                                                                                     

In 0.1.61 :
```
PID   USER     TIME  COMMAND
    1 root      0:00 /package/admin/s6/command/s6-svscan -d4 -- /run/service
   16 root      0:00 s6-supervise s6-linux-init-shutdownd
   20 root      0:00 /package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B
   23 root      0:00 s6-supervise s6rc-oneshot-runner
   24 root      0:00 s6-supervise s6rc-fdholder
   31 root      0:00 /package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /package/admin/s6-rc/command/s6-rc-oneshot-run -l ../
  182 root      0:00 s6-supervise zwave_js
  183 root      0:10 node /usr/src/node_modules/.bin/zwave-server /dev/ttyACM0 --config /etc/zwave_config.json --disable-dns-sd
  202 root      0:00 [bash]
  231 root      0:00 bash
  238 root      0:00 ps auxwf
  ```

zwave-server silent crash ? missing ?

Thanks

**Comment by MartinHjelmare** [comment]
What's your device configuration in the add-on configuration options?

**Comment by bratanon** [comment]
Same here. 

Container logs 
`No log line matching the '' filter`.

**Comment by MartinHjelmare** [comment]
If you're using a USB stick Z-Wave controller it's normally better to use the /dev/serial-by-id/ path to the device to avoid serial name problems. I don't know that this is the reason for this issue, but can be something to try.

**Comment by der71** [comment]
I am using the /dev/serial/by-id/ option and have the exact same problem after updating from 1.61 to 1.62

**Comment by bratanon** [comment]
Im also using `/dev/serial/by-id/usb-0658_200.....`

**Comment by bratanon** [comment]
Supervised installation on ubuntu 20.04.4. Not a supported installation I know, but anyway.

**Comment by der71** [comment]
I was hoping the author of the issue would be.
Time to downgrade

**Comment by redford-jones** [comment]
Same behaviour here, with some weird quirks just to really make it better. Initially I managed to downgrade to 0.161 through a partial backup. 
Then add-on then automatically updated itself moments later (auto update is **not** enabled on my supervised install). I now cannot downgrade again as all my backups are being errored as containing ‘no core data’. I also cannot stop the container - it keeps respawning by itself.

**Comment by redford-jones** [comment]
Also noticed that the container is running very hot, constant 100% cpu utilisation:

![B7079F53-C5EE-460E-A8FE-639BC087A9ED](https://user-images.githubusercontent.com/18560237/174909124-e025b0b7-4853-49e7-b7df-3496be0d950b.png)

**Comment by Spr0ckEt** [comment]
I'm having the same issue.  I cannot rollback either because I get "Unknown error. See supervisor."

WAF -10

My wife says thanks 😆

**Comment by MartinHjelmare** [comment]
I'd like to get an overview of the affected systems. If everyone that has posted in this issue so far can copy and paste their System Health information, that would be great. Thanks!

**Comment by redford-jones** [comment]
Version | core-2022.6.6
-- | --
Installation Type | Home Assistant Supervised
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.9.12
Operating System Family | Linux
Operating System Version | 5.4.0-110-generic
CPU Architecture | x86_64
Timezone | Europe/London

**Comment by MartinHjelmare** [comment]
Please copy the System Health information using the copy button in the top right of the System Health page and paste all of it.

**Comment by redford-jones** [comment]
> Please copy the System Health information using the copy button in the top right of the System Health page and paste all of it.

That is copied using the copy button. The copy button does not appear to copy everything. Here is the only other pertinent information 

Host Operating System |  
-- | --
Update Channel | stable
Supervisor Version | supervisor-2022.05.3
Agent Version |  
Docker Version | 20.10.14
Disk Total | 233.2 GB
Disk Used | 36.8 GB
Healthy | Unhealthy
Supported | Unsupported
Supervisor API | ok
Version API | ok
Installed Add-ons | Let's Encrypt (4.12.2), NGINX Home Assistant SSL proxy (3.1.1), File editor (5.3.3), Mosquitto broker (6.1.2), Zigbee2mqtt (1.18.1-1), Ring-MQTT with Video Streaming (5.0.2), Terminal & SSH (9.4.0), Studio Code Server (5.1.1), Log Viewer (0.14.0), Z-Wave JS (0.1.62), Home Assistant Google Drive Backup (0.108.2), Zigbee2mqtt Edge (edge), SQLite Web (3.6.0), Z-Wave JS to MQTT (0.43.0), JupyterLab (0.8.0), Samba share (9.7.0), GoDaddy DNS (1.0.4), AppDaemon (0.9.0), Crowdsec (1.3.4-ha2)

Yes, it shows as unsupported as it’s Ubuntu 20.04 and unhealthy as giving containers privileged root access breaks every rule of running containers.

**Comment by MartinHjelmare** [comment]
This is the output from one of my test systems when using the copy button and selecting "For GitHub".

## System Health

version | core-2022.7.0.dev20220621
-- | --
installation_type | Home Assistant OS
dev | true
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.12
os_name | Linux
os_version | 5.15.45
arch | aarch64
timezone | Europe/Stockholm

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | pending
can_reach_cloud_auth | pending
can_reach_cloud | pending

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.0.dev20220608
-- | --
update_channel | dev
supervisor_version | supervisor-2022.06.dev2101
agent_version | 1.2.1
docker_version | 20.10.14
disk_total | 13.6 GB
disk_used | 8.5 GB
healthy | true
supported | true
board | odroid-n2
supervisor_api | ok
version_api | ok
installed_addons | SSH & Web Terminal (11.0.1), File editor (5.3.3), Remote API proxy (1.2.0), Z-Wave JS (0.1.62), VLC (0.1.3), Matter Server (0.2.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
mode | auto-gen

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | June 15, 2022, 9:12 AM
-- | --
current_recorder_run | June 21, 2022, 10:49 PM
estimated_db_size | 34.43 MiB
database_engine | sqlite
database_version | 3.34.1

</details>

**Comment by bratanon** [comment]
Cant copy that. Getting this error
![image](https://user-images.githubusercontent.com/812265/174974846-8f6ba73f-c2ed-4f43-982a-24d47f4dda81.png)

**Comment by eremid** [comment]
me too...

**Comment by AvocadusRex** [comment]
I also have this issue. Updated yesterday and no Z-Wave devices are available anymore. No logs either from the Addon, I also tried to access them directly with `docker logs addon_core_zwave_js` on the host machine but also empty.
Tried to restore a backup to roll back to a previous version. This seems to work as I can see in the log that the addon is discovering the devices again but unfortunately HA updates again the Addon seconds later and I don't know how to stop that. This is the "Supervisor" log when trying to restore the addon from a previous backup and then HA updating it automatically again.

<details>
  <summary>Supervisor Log</summary>

```
22-06-22 11:24:34 INFO (MainThread) [supervisor.backups.manager] Found 8 backup files
22-06-22 11:24:34 INFO (MainThread) [supervisor.backups.manager] Found 8 backup files
22-06-22 11:24:40 INFO (MainThread) [supervisor.backups.manager] Partial-Restore f83eae43 start
22-06-22 11:24:41 INFO (MainThread) [supervisor.backups.manager] Restoring f83eae43 Docker config
22-06-22 11:24:41 INFO (MainThread) [supervisor.backups.manager] Restoring f83eae43 Repositories
22-06-22 11:24:42 INFO (MainThread) [supervisor.store] Loading add-ons from store: 28 all - 0 new - 0 remove
22-06-22 11:24:42 INFO (MainThread) [supervisor.backups.manager] Restoring f83eae43 Add-ons
22-06-22 11:24:45 INFO (MainThread) [supervisor.addons.addon] Restore config for addon core_zwave_js
22-06-22 11:24:45 INFO (MainThread) [supervisor.addons.addon] Restore/Install of image for addon core_zwave_js
22-06-22 11:24:45 INFO (SyncWorker_4) [supervisor.docker.interface] Downloading docker image homeassistant/aarch64-addon-zwave_js with tag 0.1.58.
22-06-22 11:25:04 INFO (MainThread) [supervisor.addons.addon] Restoring data for addon core_zwave_js
22-06-22 11:25:07 INFO (SyncWorker_3) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-zwave_js with version 0.1.58
22-06-22 11:25:07 INFO (MainThread) [supervisor.addons] Detect new Add-on after restore core_zwave_js
22-06-22 11:25:07 INFO (MainThread) [supervisor.backups.manager] Partial-Restore f83eae43 done
22-06-22 11:25:09 INFO (MainThread) [supervisor.api.middleware.security] /host/info access from core_zwave_js
22-06-22 11:25:10 INFO (MainThread) [supervisor.discovery] Sending discovery to Home Assistant zwave_js from core_zwave_js
22-06-22 11:25:11 INFO (MainThread) [supervisor.discovery] Discovery badeff6a114e4c1ebe93d134b19c8659 message send
22-06-22 11:26:11 INFO (MainThread) [supervisor.backups.manager] Creating new partial backup with slug 117703b9
22-06-22 11:26:11 INFO (MainThread) [supervisor.backups.manager] Backing up 117703b9 store Add-ons
22-06-22 11:26:11 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on core_zwave_js
22-06-22 11:26:14 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon core_zwave_js
22-06-22 11:26:14 INFO (MainThread) [supervisor.backups.manager] Creating partial backup with slug 117703b9 completed
22-06-22 11:26:14 INFO (SyncWorker_7) [supervisor.docker.interface] Updating image homeassistant/aarch64-addon-zwave_js:0.1.58 to homeassistant/aarch64-addon-zwave_js:0.1.62
22-06-22 11:26:14 INFO (SyncWorker_7) [supervisor.docker.interface] Downloading docker image homeassistant/aarch64-addon-zwave_js with tag 0.1.62.
22-06-22 11:26:40 INFO (SyncWorker_7) [supervisor.docker.interface] Stopping addon_core_zwave_js application
22-06-22 11:26:45 INFO (SyncWorker_7) [supervisor.docker.interface] Cleaning addon_core_zwave_js application
22-06-22 11:26:45 INFO (MainThread) [supervisor.addons] Add-on 'core_zwave_js' successfully updated
22-06-22 11:26:45 INFO (SyncWorker_5) [supervisor.docker.interface] Cleanup images: ['homeassistant/aarch64-addon-zwave_js:0.1.58']
```
</details>

This is my "System Health Information" output (I also have this JS browser error with the `Uncaught (in promise) TypeError: Cannot read properties of null (reading 'type')`, so here is my best attempt to reconstruct the output).

Version | core-2022.6.6
-- | --
Installation Type | Home Assistant Supervised
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.9.12
Operating System Family | Linux
Operating System Version | 5.4.0-1065-raspi
CPU Architecture | aarch64
Timezone | Europe/Berlin

<details>
  <summary>Home Asistant Cloud</summary>

Logged In | false
-- | --
Reach Certificate Server | ok
Reach Authentication Server | ok
Reach Home Assistant Cloud | ok
</details>

<details>
  <summary>Home Assistant Supervisor</summary>

Host Operating System | Ubuntu 20.04.4 LTS
-- | --
Update Channel | stable
Supervisor Version | supervisor-2022.05.3
Agent Version |  
Docker Version | 20.10.17
Disk Total | 109.8 GB
Disk Used | 14.9 GB
Healthy | true
Supported | Unsupported
Supervisor API | ok
Version API | ok
Installed Add-ons | Mosquitto broker (6.1.2), File editor (5.3.3), Genie (3.0.0), Check Home Assistant configuration (3.10.2), Glances (0.13.0), PSA Car Controller (v2.6.0), Z-Wave JS (0.1.62)
</details>

<details>
  <summary>Dashboards</summary>

Dashboards | 1
-- | --
Resources | 1
Views | 12
Mode | storage
</details>

<details>
  <summary>Recorder</summary>

Oldest Run Start Time | 21 June 2022, 19:40
-- | --
Current Run Start Time | 22 June 2022, 11:22
Estimated Database Size (MiB) | 474.93 MiB
Database Engine | sqlite
Database Version | 3.34.1
</details>

**Comment by flippz** [comment]
> I also have this issue. Updated yesterday and no Z-Wave devices are available anymore. No logs either from the Addon, I also tried to access them directly with `docker logs addon_core_zwave_js` on the host machine but also empty. Tried to restore a backup to roll back to a previous version. This seems to work as I can see in the log that the addon is discovering the devices again but unfortunately HA updates again the Addon seconds later and I don't know how to stop that. This is the "Supervisor" log when trying to restore the addon from a previous backup and then HA updating it automatically again.
> 
> Supervisor Log
> This is my "System Health Information" output (I also have this JS browser error with the `Uncaught (in promise) TypeError: Cannot read properties of null (reading 'type')`, so here is my best attempt to reconstruct the output).
> 
> Version	core-2022.6.6
> Installation Type	Home Assistant Supervised
> Development	false
> Supervisor	true
> Docker	true
> User	root
> Virtual Environment	false
> Python Version	3.9.12
> Operating System Family	Linux
> Operating System Version	5.4.0-1065-raspi
> CPU Architecture	aarch64
> Timezone	Europe/Berlin
> Home Asistant Cloud
> Home Assistant Supervisor
> Dashboards
> Recorder

![2022-06-22_13h02_20](https://user-images.githubusercontent.com/21279095/175013816-56c6708b-e559-46bc-b2ba-711800742833.png)

**Comment by bendikrb** [comment]
Same here (on a NUC running Ubuntu 20.04.4 LTS using docker supervised).
Got same error as [bratanon](https://github.com/home-assistant/addons/issues/2540#issuecomment-1162772564) when trying to copy system health.. The addon came back up when restoring to my last backup (0.1.55), but was automatically upgraded to 0.1.62 right away (although the "auto update" toggle is OFF).
I'm also running home assistant on a generic x86 installation (same docker supervised setup). Here, the update to 0.1.62 worked without any issues..

**Comment by bendikrb** [comment]
> How do I downgrade to 0.1.61 using ha cli?

I managed to downgrade by changing from 0.1.62 -> 0.1.61 in `/usr/share/hassio/addons/addons.json`, `/usr/share/hassio/addons/core/zwave_js/config.yaml`, and from 1.19.0 -> 1.18.0 in `/usr/share/hassio/addons/core/zwave_js/build.yaml` (not sure if this is necessary).
Then I pulled the image (`docker pull homeassistant/amd64-addon-zwave_js:0.1.61`) and rebooted.

**Comment by pvizeli** [comment]
Look like docker on Ubuntu is not working anymore with s6-overlay on our base images. I guess the supervisor will on next update also complete stop working and the system which using Ubuntu will not work anymore

**Comment by eliahru** [comment]
> Look like docker on Ubuntu is not working anymore with s6-overlay on our base images. I guess the supervisor will on the next update also completely stop working and the system which uses Ubuntu will not work anymore

That would be a disaster for us, HA owners on unsupported platforms. Can we hope that some support of unsupported can be done to try to resolve this issue with S6 and docker on Ubuntu? 
Isn't the main idea of containers is to let apps work the same way on different distros? :)

**Comment by Swinkey87** [comment]
Same problem here:

## System Health

version | core-2022.6.7
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.12
os_name | Linux
os_version | 5.15.32-v8
arch | aarch64
timezone | Europe/Amsterdam

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4969
Installed Version | 1.25.5
Stage | running
Available Repositories | 1062
Downloaded Repositories | 13

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 8.2
-- | --
update_channel | stable
supervisor_version | supervisor-2022.05.3
agent_version | 1.2.1
docker_version | 20.10.14
disk_total | 111.1 GB
disk_used | 14.2 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Node-RED (12.0.2), Samba share (9.7.0), Mosquitto broker (6.1.2), UniFi Network Application (2.3.0), File editor (5.3.3), Terminal & SSH (9.4.0), ESPHome (2022.3.1), Duck DNS (1.15.0), Home Assistant Google Drive Backup (0.108.2), Google Assistant Webserver (0.0.4), Z-Wave JS (0.1.62), Spotify Connect (0.12.1), InfluxDB (4.5.0), Z-Wave JS to MQTT (0.43.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 6
views | 12
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | June 21, 2022, 3:11 PM
-- | --
current_recorder_run | June 22, 2022, 5:01 PM
estimated_db_size | 390.10 MiB
database_engine | sqlite
database_version | 3.34.1

</details>

**Comment by ErikH2** [comment]
My Aeotec z vawe stick also broke down as above, A nuc with ubuntu server...

<html>
<body>


Version | core-2022.6.7
-- | --
Installation Type | Home Assistant Supervised
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.9.12
Operating System Family | Linux
Operating System Version | 5.4.0-120-generic
CPU Architecture | x86_64
Timezone | Europe/Stockholm


</body>
</html>
<html>
<body>
<div class="card-header" style="justify-content: space-between; display: flex; align-items: center; color: rgb(33, 33, 33); font-family: Roboto, Noto, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h3>Home Assistant Community Store</h3><a class="manage" href="http://192.168.9.144:8123/hacs" style="color: var(--primary-color); text-decoration: none;"><mwc-button style="display: inline-flex; outline: none; -webkit-tap-highlight-color: transparent; vertical-align: top;"><button id="button" class="mdc-button   " aria-label="" style="-webkit-font-smoothing: antialiased; font-family: var(--mdc-typography-button-font-family, var(--mdc-typography-font-family, Roboto, sans-serif)); font-size: var(--mdc-typography-button-font-size, 0.875rem); line-height: inherit; font-weight: var(--mdc-typography-button-font-weight, 500); letter-spacing: var(--mdc-typography-button-letter-spacing, 0.0892857em); text-decoration: var(--mdc-typography-button-text-decoration, none); text-transform: var(--mdc-typography-button-text-transform, uppercase); position: relative; display: inline-flex; align-items: center; justify-content: center; box-sizing: border-box; min-width: 64px; border: none; outline: none; user-select: none; appearance: none; overflow: hidden; vertical-align: middle; background: transparent; padding-top: 0px; padding-right: var(--mdc-button-horizontal-padding, 8px); padding-bottom: 0px; padding-left: var(--mdc-button-horizontal-padding, 8px); height: 36px; border-radius: var(--mdc-shape-small, 4px); flex: 1 1 auto; color: var(--mdc-theme-primary, #6200ee);"><span class="leading-icon"><slot name="icon"></slot></span><span class="mdc-button__label" style="position: relative;"></span><span class="slot-container   " style="display: inline-flex; align-items: center; justify-content: center;"><slot>HANTERA</slot></span><span class="trailing-icon"><slot name="trailingIcon"></slot></span></button></mwc-button></a></div>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.25.5
Stage | running
Available Repositories | 1060
Downloaded Repositories | 3


</body>
</html>
<html>
<body>
<div class="card-header" style="justify-content: space-between; display: flex; align-items: center; color: rgb(33, 33, 33); font-family: Roboto, Noto, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h3>Home Assistant Cloud</h3><a class="manage" href="http://192.168.9.144:8123/config/cloud" style="color: var(--primary-color); text-decoration: none;"><mwc-button style="display: inline-flex; outline: none; -webkit-tap-highlight-color: transparent; vertical-align: top;"><button id="button" class="mdc-button   " aria-label="" style="-webkit-font-smoothing: antialiased; font-family: var(--mdc-typography-button-font-family, var(--mdc-typography-font-family, Roboto, sans-serif)); font-size: var(--mdc-typography-button-font-size, 0.875rem); line-height: inherit; font-weight: var(--mdc-typography-button-font-weight, 500); letter-spacing: var(--mdc-typography-button-letter-spacing, 0.0892857em); text-decoration: var(--mdc-typography-button-text-decoration, none); text-transform: var(--mdc-typography-button-text-transform, uppercase); position: relative; display: inline-flex; align-items: center; justify-content: center; box-sizing: border-box; min-width: 64px; border: none; outline: none; user-select: none; appearance: none; overflow: hidden; vertical-align: middle; background: transparent; padding-top: 0px; padding-right: var(--mdc-button-horizontal-padding, 8px); padding-bottom: 0px; padding-left: var(--mdc-button-horizontal-padding, 8px); height: 36px; border-radius: var(--mdc-shape-small, 4px); flex: 1 1 auto; color: var(--mdc-theme-primary, #6200ee);"><mwc-ripple class="ripple" style="position: absolute; top: 0px; left: 0px; width: 79.3125px; height: 36px; pointer-events: none; display: block;"><div class="mdc-ripple-surface mdc-ripple-upgraded mdc-ripple-surface--primary" style="--mdc-ripple-fg-size: 0; --mdc-ripple-left: 0; --mdc-ripple-top: 0; --mdc-ripple-fg-scale: 1; --mdc-ripple-fg-translate-end: 0; --mdc-ripple-fg-translate-start: 0; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); will-change: unset; position: absolute; outline: none; overflow: hidden; --mdc-ripple-fg-opacity:var(--mdc-ripple-press-opacity, 0.12); top: 0px; left: 0px; width: 79.3125px; height: 36px; pointer-events: none;"></div></mwc-ripple><span class="leading-icon"><slot name="icon"></slot></span><span class="mdc-button__label" style="position: relative;"></span><span class="slot-container   " style="display: inline-flex; align-items: center; justify-content: center;"><slot>HANTERA</slot></span><span class="trailing-icon"><slot name="trailingIcon"></slot></span></button></mwc-button></a></div>

Logged In | false
-- | --
Reach Certificate Server | ok
Reach Authentication Server | ok
Reach Home Assistant Cloud | ok


</body>
</html>
<html>
<body>
<div class="card-header" style="justify-content: space-between; display: flex; align-items: center; color: rgb(33, 33, 33); font-family: Roboto, Noto, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h3>Home Assistant Supervisor</h3></div>

Host Operating System | Ubuntu 20.04.2 LTS
-- | --
Update Channel | stable
Supervisor Version | supervisor-2022.05.3
Agent Version |  
Docker Version | 20.10.7
Disk Total | 145.2 GB
Disk Used | 34.1 GB
Healthy | true
Supported | Unsupported
Supervisor API | ok
Version API | ok
Installed Add-ons | Check Home Assistant configuration (3.10.2), File editor (5.3.3), Terminal & SSH (9.4.0), Samba share (9.7.0), Z-Wave JS (0.1.62)


</body>
</html>
<html>
<body>
<div class="card-header" style="justify-content: space-between; display: flex; align-items: center; color: rgb(33, 33, 33); font-family: Roboto, Noto, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h3>Dashboards</h3><a class="manage" href="http://192.168.9.144:8123/config/lovelace" style="color: var(--primary-color); text-decoration: none;"><mwc-button style="display: inline-flex; outline: none; -webkit-tap-highlight-color: transparent; vertical-align: top;"><button id="button" class="mdc-button   " aria-label="" style="-webkit-font-smoothing: antialiased; font-family: var(--mdc-typography-button-font-family, var(--mdc-typography-font-family, Roboto, sans-serif)); font-size: var(--mdc-typography-button-font-size, 0.875rem); line-height: inherit; font-weight: var(--mdc-typography-button-font-weight, 500); letter-spacing: var(--mdc-typography-button-letter-spacing, 0.0892857em); text-decoration: var(--mdc-typography-button-text-decoration, none); text-transform: var(--mdc-typography-button-text-transform, uppercase); position: relative; display: inline-flex; align-items: center; justify-content: center; box-sizing: border-box; min-width: 64px; border: none; outline: none; user-select: none; appearance: none; overflow: hidden; vertical-align: middle; background: transparent; padding-top: 0px; padding-right: var(--mdc-button-horizontal-padding, 8px); padding-bottom: 0px; padding-left: var(--mdc-button-horizontal-padding, 8px); height: 36px; border-radius: var(--mdc-shape-small, 4px); flex: 1 1 auto; color: var(--mdc-theme-primary, #6200ee);"><span class="leading-icon"><slot name="icon"></slot></span><span class="mdc-button__label" style="position: relative;"></span><span class="slot-container   " style="display: inline-flex; align-items: center; justify-content: center;"><slot>HANTERA</slot></span><span class="trailing-icon"><slot name="trailingIcon"></slot></span></button></mwc-button></a></div>

Kontrollpaneler | 1
-- | --
Resources | 1
Views | 3
Mode | storage


</body>
</html>
<html>
<body>
<div class="card-header" style="justify-content: space-between; display: flex; align-items: center; color: rgb(33, 33, 33); font-family: Roboto, Noto, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h3>Recorder</h3></div>

Äldsta starttid | 16 juni 2022 20:14
-- | --
Aktuell starttid | 22 juni 2022 19:06
Estimated Database Size (MiB) | 178.61 MiB
Database Engine | sqlite
Database Version | 3.34.1


</body>
</html>

![image](https://user-images.githubusercontent.com/97853435/175116609-aceb8421-2cc0-4490-8798-54146b14c7ac.png)

**Comment by redford-jones** [comment]
> > How do I downgrade to 0.1.61 using ha cli?
> 
> I managed to downgrade by changing 0.1.62 -> 0.1.61 in `/usr/share/hassio/addons/addons.json`, `/usr/share/hassio/addons/core/zwave_js/config.yaml` and 1.19.0 -> 1.18.0 in `/usr/share/hassio/addons/core/zwave_js/build.yaml` (not sure if this is necessary). Then I pulled the image (`docker pull homeassistant/amd64-addon-zwave_js:0.1.61`) and rebooted.

Sadly that doesn't work for me either. Changed the files, rebooted HA, rebooted the entire server and it still spins up 0.1.6.2

**Comment by frenck** [comment]
> Isn't the main idea of containers is to let apps work the same way on different distros? :)

Not with our containers, as the ADRs and requirements are quite clear about this. Ubuntu is not supported, it is untested and things may break as you experience now. Use Debian instead.

The problem @ S6 has been found, and will be addressed upstream. However, it only occurs on systems with an outdated Linux kernel.

# ℹ️  We don't need more "does not work for me", logs or system reports. We are aware of the issue and the cause is a combination of running on an unsupported system with the latest S6 dependency we use. 

Be patient while things will get resolved. If you need to downgrade, you'll need to restore a backup (partially restoring just this add-on will work too).

**Comment by redford-jones** [comment]
> > Isn't the main idea of containers is to let apps work the same way on different distros? :)
> 
> Not with our containers, as the ADRs and requirements are quite clear about this. Ubuntu is not supported, it is untested and things may break as you experience now. Use Debian instead.
> 
> The problem @ S6 has been found, and will be addressed upstream. However, it only occurs on systems with an outdated Linux kernel.
> 
> > Note
> > ## We don't need more "does not work for me", logs or system reports. We are aware of the issue and the cause is a combination of running on an unsupported system with the latest S6 dependency we use.
> 
> Be patient while things will get resolved. If you need to downgrade, you'll need to restore a backup (partially restoring just this add-on will work too).

Thank you for the update @frenck 

Yes, this is the risk that we run by not running a fully supported set up. At least there looks to be a fix in the short term and and upstream fix that will carry us forward until the next LTS version of Ubuntu lands later this year.
This may be my excuse to start the move to a supported install.

**Comment by MartinHjelmare** [comment]
A new add-on version 0.1.63 has been released that should fix the problem for now.

https://github.com/home-assistant/addons/pull/2542

**Comment by Lymkin** [comment]
Thanks for the fix. 1.63 is working for me.

**Comment by nelsonblaha** [comment]
I fixed mine by updating Debian to 11. Currently running fine on 0.1.62.
