### ISSUE TITLE
check_config fails when using secrets file

### ISSUE THREAD

**Issue by ianr2** [home-assistant/addons#2543]
### Describe the issue you are experiencing

This add on always fails when using a secrets file with the error message:
Error loading /tmp/config/configuration.yaml: Secret xxxxxx not defined
This has not worked for several months. It used to work some time ago.

It fails with the first definition in the secrets file. I have moved different definitions to the start of the file and that definition is then shown in the error message.

The secrets file works as expected with Home Assistant.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Check Home Assistant configuration

### What is the version of the add-on?

3.10.2

### Steps to reproduce the issue

1. Update Pending Notification
2. Select the PRE_CHECK_LOG on the message Core 2022.6.6 -> 2022.6.7 [PRE-CHECK LOG]
3. Add on runs , error message received

If you run the add on by not going through the notification it results in the same error message
...

### Anything in the Supervisor logs that might be useful for us?

```txt
No errors reported
```

### Anything in the add-on logs that might be useful for us?

```txt
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun check-config (no readiness notification)
s6-rc: info: service legacy-services successfully started
[15:39:18] INFO: Don't worry, this temporary installation is not overwriting your current one.
[15:39:18] INFO: Installing Home Assistant: stable...
[15:39:18] INFO: Please be patient, this might take a few minutes...
[15:41:09] INFO: Installed Home Assistant 2022.6.7
[15:41:09] INFO: Making a copy of your configuration for checking...
[15:41:13] INFO: Checking your configuration against this version...
[15:41:29] ERROR: The configuration check did not pass!
[15:41:29] ERROR: See the output below for more details.
Testing configuration at /tmp/config
Failed config
  General Errors: 
    - Error loading /tmp/config/configuration.yaml: Secret XXXXXXX not defined

Successful config (partial)
[15:41:29] INFO: The full output has been written to /share/check_config.txt
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by frenck** [comment]
The configuration check add-on has been deprecated and is no longer needed.
See: #2544
