### ISSUE TITLE
s6-overlay-suexec: fatal: can only run as pid 1

### ISSUE THREAD

**Issue by gavin-lu** [home-assistant/addons#2546]
### Describe the issue you are experiencing

s6-overlay-suexec: fatal: can only run as pid 1
After updating to version 3.1.2.
Issue goes away when reverting to version 3.1.1.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

NGINX Home Assistant SSL proxy

### What is the version of the add-on?

3.1.2

### Steps to reproduce the issue

1. Update to 3.1.2
2. Start nginx add-on
3. Check log
...

### Anything in the Supervisor logs that might be useful for us?

```txt
Home Assistant Core 2022.6.7
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.2
```

### Anything in the add-on logs that might be useful for us?

```txt
s6-overlay-suexec: fatal: can only run as pid 1
```

**Comment by Delta1977** [comment]
Same here with 3.1.2

**Comment by maretodoric** [comment]
Same here with 3.1.2, as soon as i updated it

**Comment by DayRunner131** [comment]
Same issue with V3.1.3

"s6-overlay-suexec: fatal: can only run as pid 1"

**Comment by CanoHard** [comment]
Same here

**Comment by mdegat01** [comment]
Yea it's https://developers.home-assistant.io/blog/2022/05/12/s6-overlay-base-images . Will be fixed in a moment.
