### ISSUE TITLE
Nginx addon Startup error in 3.1.4

### ISSUE THREAD

**Issue by Delta1977** [home-assistant/addons#2548]
### Describe the issue you are experiencing

Perror: Expected string key before ':' at line 1, column 4
[22:19:35] ERROR: Unknown HTTP error occured
parse error: Expected string key before ':' at line 1, column 4
[22:19:35] ERROR: Unknown HTTP error occured
[22:19:35] INFO: Running nginx...
nginx: [emerg] invalid port in upstream "homeassistant.local.hass.io:" in /etc/nginx.conf:62

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

NGINX Home Assistant SSL proxy

### What is the version of the add-on?

3.1.4

### Steps to reproduce the issue

In startup

### Anything in the add-on logs that might be useful for us?

```txt
arse error: Expected string key before ':' at line 1, column 4
[22:19:35] ERROR: Unknown HTTP error occured
parse error: Expected string key before ':' at line 1, column 4
[22:19:35] ERROR: Unknown HTTP error occured
[22:19:35] INFO: Running nginx...
nginx: [emerg] invalid port in upstream "homeassistant.local.hass.io:" in /etc/nginx.conf:62
```

### Additional information

Error after upgrade from 3.1.3 and on fresh install

**Comment by DayRunner131** [comment]
Same here....

"s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
parse error: Expected string key before ':' at line 1, column 4
[22:27:46] ERROR: Unknown HTTP error occured
parse error: Expected string key before ':' at line 1, column 4
[22:27:47] ERROR: Unknown HTTP error occured
[22:27:47] INFO: Running nginx...
nginx: [emerg] invalid port in upstream "homeassistant.local.hass.io:" in /etc/nginx.conf:62
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped"

Reverting back to V3.1.1

**Comment by frenck** [comment]
Which version of the Supervisor do you have?

**Comment by bennydente** [comment]
Same here. And I have Home Assistant Supervisor 2022.05.3

thanks.

**Comment by checkerschaf** [comment]
@frenck Supervisor Version supervisor-2022.05.3

**Comment by npotgieter** [comment]
<html>
<body>
<div class="card-header" style="justify-content: space-between; display: flex; align-items: center; color: rgb(225, 225, 225); font-family: Roboto, Noto, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(28, 28, 28); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h3>Home Assistant Supervisor</h3></div>

Host Operating System | Home Assistant OS 8.2
-- | --
Update Channel | stable
Supervisor Version | supervisor-2022.05.3
Agent Version | 1.2.1
Docker Version | 20.10.14
Disk Total | 30.8 GB
Disk Used | 16.4 GB
Healthy | true
Supported | true
Board | ova
Supervisor API | ok
Version API | ok


</body>
</html>

**Comment by Delta1977** [comment]
supervisor-2022.05.3

**Comment by frenck** [comment]
Found the issue, fix inbound.

**Comment by DayRunner131** [comment]
Works great now with V3.1.5. Thanks for the quick fixes @frenck!
