### ISSUE TITLE
nginx_proxy: NEMS reports SSL error after upgrading nginx_proxy from 3.1.1 to 3.1.5

### ISSUE THREAD

**Issue by tracestep** [home-assistant/addons#2553]
### Describe the issue you are experiencing

I use Linux NEMS (Nagios Enterprise Monitoring Server - [https://nemslinux.com/](https://nemslinux.com)) to monitor my VMs and services, which include Home Assistant https access through nginx_proxy. Everything ran fine when running nginx_proxy addon version 3.1.1. After upgrading to 3.1.5, I get this error from the monitoring system: 

`1996436608:error:14094458:SSL routines:ssl3_read_bytes:tlsv1 unrecognized name:../ssl/record/rec_layer_s3.c:1544:SSL alert number 112`

That happens using TLS 1.2; if I try to use TLS 1.3 (after the upgrade, which fix that), I get:

`CRITICAL - Cannot make SSL connection.  1995932800:error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version:../ssl/record/rec_layer_s3.c:1544:SSL alert number 70`

I confirmed that by reverting the addon to 3.1.1, the error goes away; neither `curl` nor my browser return no error in either version. I tried searching NEMS for any info on this, but got nothing... I do not know the specifics of what the `check_http` Nagios plugin does; it might be it's fault, but that does not happen on earlier versions of the addon, so some change in the addon triggered it.

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### Which add-on are you reporting an issue with?

NGINX Home Assistant SSL proxy

### What is the version of the add-on?

3.1.5

### Steps to reproduce the issue

1. Install Linux NEMS [https://nemslinux.com/](https://nemslinux.com) on a Raspberry Pi (or possibly only the Nagios plugin `check_https` from [https://nagios-plugins.org/download/nagios-plugins-2.1.2.tar.gz](https://nagios-plugins.org/download/nagios-plugins-2.1.2.tar.gz))
2. Login to the NEMS instance and run `/usr/lib/nagions/plugins/check_http -p 443 -S --ssl=1.2 hahost.youtdomain.tld`
EDIT: The correct syntax is `/usr/lib/nagions/plugins/check_http -p 443 --ssl=1.2 -H hahost.youtdomain.tld`
3. Get the SSL error

### Anything in the Supervisor logs that might be useful for us?

```txt
Nothing appears on the supervisor logs.
```

### Anything in the add-on logs that might be useful for us?

```txt
Nothing appears on the addon logs.
```

### Additional information

I use my own CA, but it is correctly installed on both the server and the client and curl reports no error.

**Comment by mdegat01** [comment]
So I mean if curl and your browser work fine this definitely sounds like an issue with nems linux. And fixing that is out of scope for this project.

Although side note I did look up the documentation for [nems linux check_http](https://docs.nemslinux.com/en/latest/check_commands/check_http.html#check-http-argument-syntax). It seems to show the `-S` and `--ssl` options are synonymous and don't support providing a specific SSL/TLS version like that. Are you sure what you're doing there works? Based on this bit of the error `ssl3_read_bytes:tlsv1` it kind of seems like that part of your command is just being ignored and its trying to use an old SSL version to connect.

**Comment by tracestep** [comment]
Looking further in the `check_http` documentation, I found the `--sni` switch:

```
--sni
        Enable SSL/TLS hostname extension support (SNI)
```
And it did solve the issue. So using `/usr/lib/nagions/plugins/check_http -p 443 --ssl=1.2 --sni -H hahost.yourdomain.tld` fixes it.
So I am closing the issue, but it still might be worth looking into other possible side-effects of whatever changed between 3.1.1 and 3.1.5. Thanks, @mdegat01.

**Comment by mdegat01** [comment]
So #2558 alerted me to what's actually going on here @tracestep . It wasn't the TLS version, it was because you were reaching out to the addon at a domain other the one specified in the addon config. Which explains why adding the `sni` fixes it.

I guess I can see now how this could create some issues. But just an FYI anything reaching to the addon without using the domain specified in the config wasn't really checking anything. There was always an entirely different path through the addon for that. Here's what it was prior to #2532:
https://github.com/home-assistant/addons/blob/d37b21354316c7266a5d7616a553bfe15da5af71/nginx_proxy/data/nginx.conf#L26-L33

As you can see the addon served up a totally bogus certificate (not the one you provided in the config) and closed the connection as quickly as possible by returning a 444. It only used your certificate and did what you would expect if the domain provided in the config was used.

So I guess I'll have to help people through this now but I would argue your check wasn't really working properly before and is now.

**Comment by tracestep** [comment]
Hmmm... that makes sense. But the "Domain" specified on my nginx_proxy config was `~^(.+)$`, which I guess should match any domain name I access it through (my certificate has several SAN and IPs so I can reach the server in different ways).

**Comment by mdegat01** [comment]
Well it matches almost anything. It won't match no server name (which I assume becomes `""`). And that is possible according to [nginx docs](https://nginx.org/en/docs/http/server_names.html):
> First, a connection is created in a default server context. Then, the server name can be determined in the following request processing stages, each involved in server configuration selection:
>
> - during SSL handshake, in advance, according to [SNI](https://nginx.org/en/docs/http/configuring_https_servers.html#sni)
>
> - after processing the request line
>
> - after processing the Host header field
>
> - if the server name was not determined after processing the request line or from the Host header field, nginx will use the empty name as the server name.

So I don't really know how linux nems works. But if you use an IP address and don't set SNI does maybe it doesn't provide `host` at all and winds up in the empty server name path?
