### ISSUE TITLE
Cloudflare not working after updating to 3.1.3

### ISSUE THREAD

**Issue by RouNNdeL** [home-assistant/addons#2558]
### Describe the issue you are experiencing

Cloudflare started reporting SSL protocol errors after updating to 3.1.5. The change seems to have been introduced in 3.1.3.

This seems to be related to #2553 and how the new nginx handles SNIs (I think?). I'm getting an SSL error when trying to connect to nginx with an invalid (different to the one specified in the addon configuration) domain name.
```
* Closing connection 0
curl: (35) error:14094458:SSL routines:ssl3_read_bytes:tlsv1 unrecognized name
```

The domain set in Cloudflare is set correctly, no changes have been made to the configuration, justed updated the addon.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

NGINX Home Assistant SSL proxy

### What is the version of the add-on?

3.1.5

### Steps to reproduce the issue

Updated to 3.1.5 - no configuration change.

### Anything in the Supervisor logs that might be useful for us?

```txt
No
```

### Anything in the add-on logs that might be useful for us?

```txt
No
```

### Additional information

The addon exposes port 443, but the NATed external port is different.

**Comment by mdegat01** [comment]
So previously the addon would serve up a bogus self-signed certificate when you tried to connect to it with a domain other then what is specified in the addon. It was literally called the snakeoil certificate in the code:
https://github.com/home-assistant/addons/blob/21215aa9d0cdd1c2e322a6c8faf93ae727e3ce96/nginx_proxy/data/run.sh#L24-L26

If you actually tried to connect to it with a domain other then the one in the config it did nothing. It returned a `444` status code which is Nginx's code for "close the connection immediately and tell the client nothing, they are probably malicious":
https://github.com/home-assistant/addons/blob/d37b21354316c7266a5d7616a553bfe15da5af71/nginx_proxy/data/nginx.conf#L26-L33

#2532 speed up this process marginally by simply having the addon reject the ssl handshake if reached at a domain other then the one specified. Which I believe is what you're showing.

So I guess the question is why are you doing this?
> trying to connect to nginx with an invalid (different to the one specified in the addon configuration) domain name

That never worked. You got a bogus certificate and a quick "go away" response, now you get an error. What are you trying to achieve with this?

**Comment by RouNNdeL** [comment]
This was just to troubleshoot the issue, I do not need it to resolve with the local domain name, just remote. It works when manually specifying `--resolve` in `curl`. I was not able to troubleshoot the cloudflare issue.

**Comment by mdegat01** [comment]
When you say
> Cloudflare started reporting SSL protocol errors

What do you actually mean? Where are these errors and what specifically is reporting them?

**Comment by RouNNdeL** [comment]
HTTP 525 - SSL handshake failed when trying to access the site.

**Comment by RouNNdeL** [comment]
Let me describe the set up in a bit more detail:
HA (8123) <-> Nginx proxy (443) <- dst NAT (8443->443) -> Cloudflare (8443).
Could the different port cause this issue, I'm not an expert on how nginx matches `server_name`.

**Comment by mdegat01** [comment]
Oh you mean the cloudflare proxy option, like when you host your domain with them, that option? Sorry cloudflare is really big so I wasn't sure if you were talking about that or [the cloudflared tunnel](https://github.com/cloudflare/cloudflared) or something else.

Is there a way to specify that cloudflare should use the sni for that check? It obviously wasn't checking the certificate since it would've told you the certificate it received is invalid. The addon only served up the certificate you provided if you used the correct sni, if you used a different one you got the snakeoil one. If cloudflare was checking the certificate I assume it would've told you it got some bogus one and not origin certificate you were supposed to upload to your server.

**Comment by RouNNdeL** [comment]
Yeah, I assumed it was quite common to protect HA with a WAF when exposing it to the outside world and the proxy is also the most used feature of cloudflare I guess. The issue is between CF and Nginx Proxy and not CF and the browser so specifying what to use for the check (which I don't think is possible) would not solve the issue. Cloudflare docs as to what causes  HTTP 525:

```
Contact your hosting provider to exclude the following common causes at your origin web server:

- No valid SSL certificate installed
- Port 443 (or other custom secure port) is not open
- NoSNI support
- The cipher suites accepted by Cloudflare does not match the cipher suites supported by the origin web server 
```
Since something broke in 3.1.3 I would assume to issue is related to the SNI option.

**Comment by RouNNdeL** [comment]
Is there any way to enable more verbose logging in the addon. I could not find anything in the docs.

**Comment by mdegat01** [comment]
There's not a log level or debug option but you can use the [customize option](https://github.com/home-assistant/addons/blob/master/nginx_proxy/DOCS.md#option-customizeactive-required) to modify the config. If you add a file for `customize.default` then you can set any of the options [here](https://www.nginx.com/resources/wiki/start/topics/examples/full/) that you see under `server`. Including options around `access_log` that aren't in use by default.

**Comment by mdegat01** [comment]
Yea idk I'm at a bit of a loss tbh. The addon clearly does have SNI support, if you look at the issue you linked earlier (#2553) providing `sni` was how that author was able to resolve the problem.

I was trying to test this with my own account but I can't because I use the "Authenticated Origin Pulls" option to ensure port sniffers can't bypass my WAF. Since you use this addon I'm guessing you don't use that since the addon doesn't support that. Unfortunately that limits my ability to reproduce this on my end so you'll have to tell me what you see.

I'm just a bit stumped because while you're correct that something changed here only the error path was changed. I am not sure how this addon could've been working before if Cloudflare was reaching out without using the specified domain name. The error message changed but it was always an error.

**Comment by VNRARA** [comment]
Every single update breaks my whole setup. I'm starting to get tired of this addon..

**Comment by mag1024** [comment]
I'm hit by this issue as well.
My setup is a bastion host with nginx, connecting via NAT to the nginx addon on the HA host.

I'm guessing that despite the relevant options in the external nginx's proxy config
`proxy_set_header Host ...;
proxy_ssl_server_name on;`
There's some kind of name mismatch going on which used to get ignored, but is now causing failures.

@mdegat01, could you please a complete example of how to enable logging? I tried creating a global customizations file under share/, but I can't seem to get it to do anything other than cause the addon not to start.

Is there an easy way to downgrade the addon?

**Comment by RouNNdeL** [comment]
As far as I know the only way to downgrade is to uninstall and somehow install the old version, haven't tried it yet.

**Comment by mdegat01** [comment]
> @mdegat01, could you please a complete example of how to enable logging?

I believe you can enable the access log for the default server by adding this to the addon config:
```yaml
customize:
  active: true
  default: nginx_proxy_default*.conf
```
And then putting this in `/share/nginx_proxy_default_access_log.conf`:
```
access_log: stdout;
```
But I haven't really tried it myself and can't right now. I also have no idea if that will tell you anything, it only changes the config of the default server and it sounds like somehow you're ending up in the catch-all/error server.

> Is there an easy way to downgrade the addon?

Restore from a backup. That's the only way.

@pyos I'm thinking I might have to revert #2532. It seems to have had some unintended consequences both with this issue. I'm really at a loss how it couldve had an effect here so figured I'd ping you in case you had any ideas.

**Comment by mag1024** [comment]
Through some blind pokery, I discovered that adding `proxy_ssl_name $host;` to my external proxy config seems to resolve the issue for me.

**Comment by mdegat01** [comment]
@mag1024 you added that to the config of the nginx proxy addon via customize? Or to the config of a proxy before this addon?

**Comment by RouNNdeL** [comment]
I've managed to resolve the issue by changing Cloudflare's SSL mode to `Full`. Seems like when using `Flexible` CF does not send the SNI in the handshake message (I only noticed this with packet capture). Using anything other then `Full (strict)` meant that I didn't notice the issue until this change.

**Comment by mag1024** [comment]
Sorry, I should've been more clear. Here's my complete setup:

host1.domain.com: external nginx proxy, forwarding to host2
host2.domain.com: router, NATs some port to host3
host3.domain.com: home assistant

Basically I discovered that external proxy setup I needed is
```
        proxy_pass https://host2.domain.com:1234;
        ....
        proxy_set_header Host              host3.domain.com;
        proxy_ssl_name                     host3.domain.com;
        proxy_ssl_server_name              on;
```

In particular, previously, my external proxy was not setting the proxy_ssl_* parameters, and was thus hitting the default server on the addon. So my problem was really specific to the (mis)configuration of my external proxy.

**Comment by pyos** [comment]
Yeah, that makes sense... with SSL, nginx resolves server blocks twice and makes no effort to ensure that the results are consistent, so if you just ignore the certificate, `curl https://wrong-domain/ -H "Host: correct-domain"` used to work. nginx will happily give you a certificate for wrong-domain, then serve a page from correct-domain.

~~I wonder if this can be used as a security hole somehow...~~
