### ISSUE TITLE
IPv6 Config URL failing in DuckDNS

### ISSUE THREAD

**Issue by sbeagle25** [home-assistant/addons#2560]
### Describe the issue you are experiencing

I try to use the url to update my ipv6 address in duckdns but failing. If I set the ipv6 as default, it will get the internal ipv6 which came from my AP. I need the url function to get my public ipv6.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Duck DNS

### What is the version of the add-on?

1.15.0

### Steps to reproduce the issue

1. set ipv6: https://api.ipify.org/ 
2. start Duckdns

### Anything in the add-on logs that might be useful for us?

```txt
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
# INFO: Using main config file /data/workdir/config
+ Account already registered!
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by mdegat01** [comment]
Just to confirm, you mean `https://api6.ipify.org/` not `https://api.ipify.org/` right? That's what you had [here](https://github.com/home-assistant/addons/issues/1715#issuecomment-1145796862) so I assume that was a typo but wanted to check. `https://api.ipify.org/` doesn't make sense for `ipv6`, it returns your ipv4 address.

**Comment by sbeagle25** [comment]
Yes, my bad. Sorry for the typo. Here is my full config of duckdns.

> domains:
>   - xxxx.duckdns.org
> token: 778ef2d3-6291-40b1-a81e-xxxxxx
> aliases: []
> lets_encrypt:
>   accept_terms: true
>   algo: secp384r1
>   certfile: fullchain.pem
>   keyfile: privkey.pem
> seconds: 300
> ipv6: https://api6.ipify.org/
>

**Comment by sbyx** [comment]
If you set ipv6 to "default" it should get your public IPv6 address of home assistant this should actually come from your local router. Then in your local router make sure to just open the firewall to that internal IP for access from the internet. Port forwarding is normally not used for IPv6.

What does that "internal ipv6 address" from your AP look like?

**Comment by sbeagle25** [comment]
@sbyx I use a sim card as my network source. So I got only one public ipv6 from it which is used by the router. That's why I need to use the url to get my public ipv6.  I have already set the firewall for my homeassistant.
As for the internal ipv6, maybe it should called as local ipv6 address. It is created by the router and assign to every machine inside the router's network. If I use the default settings, it will get a ipv6 as "ddv4.db80...."  which is not a public one.

**Comment by sbeagle25** [comment]
I did use a mobile hotspot as my home internet. So i got only one ipv6 address. Now my solution just like you say, using a duckdns option on my router. But it will generate another problem. Every 3 months the SSL certificate will invalid. I have to renew it manually.

**Comment by mdegat01** [comment]
@sbeagle25 just use the let's encrypt addon, it can handle that part.

**Comment by sbeagle25** [comment]
@mdegat01 Thanks. I'll try let's encrypt addon. So my situation can't use the duckdns addon right? If it's unsolvable I'll close this issue.

**Comment by mdegat01** [comment]
Yea I'll close this one, sorry about that.
