### ISSUE TITLE
Let's Encrypt 404 code 80 port open

### ISSUE THREAD

**Issue by RayBan91** [home-assistant/addons#2561]
### Describe the issue you are experiencing

Hello,
I have issue with renewal my SSL certificate using Let's Encrypt. After 60 my cert expired and I wanted to recreate, but I'm getting this output:
(...)
[15:57:12] INFO: Selected http verification
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Renewing an existing certificate for *PUBLIC_DOMAIN_NAME*
Certbot failed to authenticate some domains (authenticator: standalone). The Certificate Authority reported these problems:
  Domain: *PUBLIC_DOMAIN_NAME*
  Type:   unauthorized
  Detail: *PUBLIC_IP*: Invalid response from http://*PUBLIC_DOMAIN_NAME*/.well-known/acme-challenge/hash: 404
Hint: The Certificate Authority failed to download the challenge files from the temporary standalone webserver started by Certbot on port 80. Ensure that the listed domains point to this machine and that it can accept inbound connections from the internet.
(...)

I have my domain managing by OVH redirect to my public IP. On edge router I have 8123 port redirect to 8123 ports to my HA Appliance VM IP and on the purpose of certification renewal I enabled 80 (public) > 8123 (local) port redirection. I can reach my HA site from browser (incognito mode) using public (mobile GSM) network on 8123 and 80 port using HTTP protocol. 

...and still I'm getting this error.

- What I'm doing wrong? I have all of my public services (containers and VMs) certified by Let's Encrypt and opened 80 port was always enough to recertificate. :)

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Let's Encrypt

### What is the version of the add-on?

4.12.5

### Steps to reproduce the issue

1. Have a SSL cert generated by Let's Encrypt
2. Try to renewal after 90 days
3. Get information about 404 code respons

### Additional information
Reachable from Internet
![image](https://user-images.githubusercontent.com/48070278/175979198-fa7e4a6f-2e31-4038-8738-cf7918ba2697.png)

When I unhash ssl_certifiacte and ssl_key rows in my configuration.yaml file :
![image](https://user-images.githubusercontent.com/48070278/175980579-c822b37d-c97c-4875-8e13-f21393f9e460.png)
I can't use HTTP protocol and 80 port, I need to use HTTPS protocol on 443 & 8123 port, and then I'm getting other message: 

Detail: *PUBLIC_IP*: Fetching http://*PUBLIC_DOMAIN_NAME*/.well-known/acme-challenge/hash: Error getting validation data
Hint: The Certificate Authority failed to download the challenge files from the temporary standalone webserver started by Certbot on port 80. Ensure that the listed domains point to this machine and that it can accept inbound connections from the internet.

**Comment by RayBan91** [comment]
I needed redirect 80 external to 80 local port, not 80 external to 8123 local.

**Comment by dan-turner** [comment]
@RayBan91 thank you sir! you just saved my butt
