### ISSUE TITLE
Missing addon-image: zwave_js from ghcr.io ?

### ISSUE THREAD

**Issue by zinefer** [home-assistant/addons#2569]
### The problem

I have been having a weird issue with zwave_js for a very long time (possibly since it came out). The image is seemingly unavailable at ghcr.io. I do seem to be able to obtain the image in very specific circumstances, something around running the latest core with the latest zwave but something is definitely wrong here.

I can run `docker pull homeassistant/amd64-addon-zwave_js:0.1.61` and the image gets downloaded and HA automatically starts it.

### What version of Home Assistant Core has the issue?

core-2022.6.7

### What type of installation are you running?

Home Assistant Supervised

### Integration causing the issue

zwave_js

### Link to integration documentation on our website

https://www.home-assistant.io/integrations/zwave_js/

### Anything in the logs that might be useful for us?

```txt
`ha supervisor logs`

22-07-03 07:24:53 ERROR (SyncWorker_3) [supervisor.docker] Image homeassistant/amd64-addon-zwave_js:0.1.61 does not exist for addon_core_z
wave_js
22-07-03 07:26:13 ERROR (SyncWorker_1) [supervisor.docker] Image homeassistant/amd64-addon-zwave_js:0.1.61 does not exist for addon_core_z
wave_js
22-07-03 07:27:33 ERROR (SyncWorker_7) [supervisor.docker] Image homeassistant/amd64-addon-zwave_js:0.1.61 does not exist for addon_core_z
wave_js
22-07-03 07:28:53 ERROR (SyncWorker_3) [supervisor.docker] Image homeassistant/amd64-addon-zwave_js:0.1.61 does not exist for addon_core_z
wave_js
```

There were some logs in `ha core logs` but it seems like those logs are cleared quickly and I've lost them. They seemed to me to be about the image not existing.
```


### Additional information

https://ghcr.io/homeassistant/amd64-addon-zwave_js also 404's for me.

**Comment by mdegat01** [comment]
Just to confirm, the config doesn't list a ghcr.io link, it lists a dockerhub one for image:
https://github.com/home-assistant/addons/blob/95f31020b7030ee34209a1b648fee3cf4e54fecc/zwave_js/config.yaml#L18

Going to close this as there's no issue here from what I can see. @zinefer if I missed something feel free to ping me or re-open.
