### ISSUE TITLE
deCONZ Gateway page empty after upgrade to 6.15.0

### ISSUE THREAD

**Issue by KoalaWerewolf** [home-assistant/addons#2575]
### Describe the issue you are experiencing

Upgraded deCONZ from 6.14.1 to 6.15.0. After upgrade the Gateway page in Phoscon does not provide any information about the Conbee-stick. The text for the navigation buttons at the bottom is not internationalized either.
deCONZ is working, I can control my Zigbee network. Running Conbee II on latest FW.
Nothing seems wrong in either the deCONZ log or the Supervisor log.
I have done a reboot of my RPi to see if that helped, the issue is still there.
![image](https://user-images.githubusercontent.com/82532385/177513724-3ab80e09-e241-4578-adab-19c32da8d13c.png)

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

deCONZ

### What is the version of the add-on?

6.15.0

### Steps to reproduce the issue

1. Would not be able to reproduce unless I downgrade and upgrade again. Steps I've taken before this:
2. Upgrade to 6.15.0
3. Navigate to Gateway page in Phoscon.
...

**Comment by madnessi** [comment]
Same issue.
In the beginning its working, It say v2.17.1 Phoscon used. But date is still from v2.16.1 (4/21/2022)
and then Gateway page is not working anymore.
Currently restored back to 6.14.1

**Comment by KoalaWerewolf** [comment]
Clearing the cache resolved the issue. Thanks!
