### ISSUE TITLE
Update from 9.4.0 to 9.5.0 fails

### ISSUE THREAD

**Issue by Sesshoumaru-sama** [home-assistant/addons#2577]
### Describe the issue you are experiencing

Trying to update to 9.5.0 from 9.4.0 fails with:
Can't install homeassistant/amd64-addon-ssh:9.5.0: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=9.5.0&fromImage=homeassistant%2Famd64-addon-ssh&platform=linux%2Famd64: Not Found ("manifest for homeassistant/amd64-addon-ssh:9.5.0 not found: manifest unknown: manifest unknown")

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Terminal & SSH

### What is the version of the add-on?

9.4.0

### Steps to reproduce the issue

1. Just try to update.

### Additional information

Home Assistant Core 2022.6.7
Home Assistant Supervisor 2022.06.2
Home Assistant OS 8.2

**Comment by canedje** [comment]
Same here

**Comment by banan77** [comment]
Same here. HA in docker, Raspberry Pi OS Lite 64-bit, all up to date

**Comment by gfn256** [comment]
Same here. RPI4 8GB SSD HASSio

**Comment by antoweb** [comment]
same here

**Comment by frenck** [comment]
## ⚠️ Please note

Don't just report "I have the same issue". It doesn't add anything to triage the issue at hand. Instead, just leave a 👍 to the top / original issue report.

That keeps everything nice and clean, while we still hear you.

Thanks! 👍 

../Frenck

**Comment by gfn256** [comment]
../Frenck noted. You're absolutely right!

**Comment by canedje** [comment]
It is updating now. But stopping the container

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
fix-attrs: info: applying /etc/fix-attrs.d/cli
fix-attrs: info: applying /etc/fix-attrs.d/profile
fix-attrs: info: applying /etc/fix-attrs.d/ssh
s6-chown: fatal: unable to chown /data/.ssh/authorized_keys: No such file or directory
fix-attrs: warning: fix-attrs is deprecated, please fix volume permissions in your container manager instead
fix-attrs: warning: some fix files failed to apply
s6-rc: warning: unable to start service fix-attrs: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by antoweb** [comment]
Now error is:
Pulled image homeassistant/aarch64-addon-ssh:9.5.0 failed on content-trust verification!

**Comment by sbeukers** [comment]
I've got the same problem. 
Update succeeded after reboot but the application crashed and doesn't start anymore
I reverted back to 9.4.0

**Comment by frli4797** [comment]
`22-07-06 14:27:14 INFO (SyncWorker_3) [supervisor.docker.interface] Updating image homeassistant/aarch64-addon-ssh:9.4.0 to homeassistant/aarch64-addon-ssh:9.5.0
22-07-06 14:27:14 INFO (SyncWorker_3) [supervisor.docker.interface] Downloading docker image homeassistant/aarch64-addon-ssh with tag 9.5.0.
22-07-06 14:28:15 CRITICAL (SyncWorker_3) [supervisor.docker.interface] Pulled image homeassistant/aarch64-addon-ssh:9.5.0 failed on content-trust verification!`

**Comment by frli4797** [comment]
> Now error is:
> Pulled image homeassistant/aarch64-addon-ssh:9.5.0 failed on content-trust verification!

`22-07-06 14:27:14 INFO (SyncWorker_3) [supervisor.docker.interface] Updating image homeassistant/aarch64-addon-ssh:9.4.0 to homeassistant/aarch64-addon-ssh:9.5.0 22-07-06 14:27:14 INFO (SyncWorker_3) [supervisor.docker.interface] Downloading docker image homeassistant/aarch64-addon-ssh with tag 9.5.0. 22-07-06 14:28:15 CRITICAL (SyncWorker_3) [supervisor.docker.interface] Pulled image homeassistant/aarch64-addon-ssh:9.5.0 failed on content-trust verification!`

**Comment by sbeukers** [comment]
> > I've got the same problem. Update succeeded after reboot but the application crashed and doesn't start anymore I reverted back to 9.4.0
> 
> how to revert to 9.4.0?

If you didn't untick backup
Settings ->System->Backup addon_core_ssh_9.4.0
Else uninstall and install 9.4.0

**Comment by antoweb** [comment]
> > > I've got the same problem. Update succeeded after reboot but the application crashed and doesn't start anymore I reverted back to 9.4.0
> > 
> > 
> > how to revert to 9.4.0?
> 
> If you didn't untick backup Settings ->System->Backup addon_core_ssh_9.4.0 Else uninstall and install 9.4.0

So the problem for me is how to install a previous version

**Comment by frenck** [comment]
Add-on version 9.5.0 has been reverted / pulled. 9.4.0 is the current stable version at this point. If you need to go back, please use a back to (partial) restore the SSH add-on.

**Comment by frenck** [comment]
Good! Closing this issue in that case. Thanks for letting us know @pyrrolizin ❤️ 

../Frenck
