### ISSUE TITLE
Building wheel for numpy (pyproject.toml) did not run successfully.

### ISSUE THREAD

**Issue by gusmori** [home-assistant/addons#2583]
### Describe the issue you are experiencing

When I run the check assistant configuration with version 2022.7.0 it gives me an error for which I cannot find a solution.
I don't know what it means either.
Thanks.

> [15:17:36] INFO: Don't worry, this temporary installation is not overwriting your current one.
[15:17:36] INFO: Installing Home Assistant: stable...
[15:17:36] INFO: Please be patient, this might take a few minutes...
[15:19:25] INFO: Installed Home Assistant 2022.7.0
[15:19:25] INFO: Making a copy of your configuration for checking...
[15:19:28] INFO: Checking your configuration against this version...
[15:35:02] ERROR: The configuration check did not pass!
[15:35:02] ERROR: See the output below for more details.
Testing configuration at /tmp/config
INFO:homeassistant.helpers.storage:Migrating core.entity_registry storage from 1.6 to 1.7
WARNING:homeassistant.components.mqtt.mixins:Manually configured MQTT sensor(s) found under platform key 'sensor', please move to the mqtt integration key, see https://www.home-assistant.io/integrations/sensor.mqtt/#new_format
  
  × Building wheel for numpy (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [258 lines of output]
      Running from numpy source directory.
      setup.py:86: DeprecationWarning:
      
        `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
        of the deprecation of `distutils` itself. It will be removed for
        Python >= 3.12. For older Python versions it will remain present.
        It is recommended to use `setuptools < 60.0` for those Python versions.
        For more details, see:
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Check Home Assistant configuration

### What is the version of the add-on?

3.11.0

### Steps to reproduce the issue

1.
2.
3.
...

**Comment by frenck** [comment]
The Configuration Check add-on has been deprecated and will be removed in the future.

It will not receive any updates or fixes anymore at this point. The reasoning is that the add-on is actually obsolete / not needed anymore today.

For more information, see the deprecation PR here: <https://github.com/home-assistant/addons/pull/2544>
