### ISSUE TITLE
DuckDNS plugin reports "wrong" IPv6 address

### ISSUE THREAD

**Issue by ast0815** [home-assistant/addons#2593]
### Describe the issue you are experiencing

I have the DuckDNS plugin set up to report only an IPv6 address. When I use the web interface of the SSH plugin, it tells me a couple of IPv6 addresses of the eth0 adapter. The DuckDNS plugin reports one of those to the DuckDNS server when I set the IPv6 config option to `default`.

The problem is, that not all of those IPv6 addresses seem to actually work. Yesterday, everything was fine with one of those addresses, but then at some point this morning DuckDNS switched to reporting a different one, and I cannot actually reach any Home Assistant services (http, https) via that one.

Using the suggested web addresses to get the IPv6 address via an online service also does not work. If I configure it like that, it does not report any IPv6 address (according to the plugin log). I suspect the problem might be that the containers the plugins run in do not actually get an IPv6 address? At least I could _not_ access any IPv6 websites using curl from the SSH container.

So I suspect the problem is one of the following:

1. The DuckDNS plugin picks the wrong IPv6 address to report.
2. Home Assistant is too picky about which IPv6 addresses it listens on for connections. I.e. all IPv6 addresses are correct, but the servers only listen for connections to one of them.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Duck DNS

### What is the version of the add-on?

1.15.0

### Steps to reproduce the issue

1. Have multiple IPv6 addresses for eth0 adapter (I think I get mine from my ISP via the cable Internet router?)
2. Try to configure DuckDNS plugin to report IPv6 addresses
3. Try to access Home Assistant (http or https) via the reported IPv6 address
4. Notice that only some of the addresses reported on SSH login actually work, and DuckDNS picks the "wrong" one sometimes.

### Anything in the Supervisor logs that might be useful for us?

```txt
Nothing I can see.
```

### Anything in the add-on logs that might be useful for us?

```txt
Nope. It happily reports an IPv6 address if configured with `default`. Does not report anything (but also does not print any error message) when configured with one of the suggested websites.
```

### Additional information

I have worked around this issue for the time being, by configuring DuckDNS to report the fixed IPv6 address that is working at the moment. I am worried that the IP might change at any moment though, since I think I got it from my ISP and I do not know how long the lease is.

**Comment by ast0815** [comment]
I managed to write a tiny script that extracts the correct IP address in the SSH server plugin. Looks like the address with the `/128` subnet is the correct one in my case:

```
ha net info | egrep [0-9:]*/128 | sed -e 's/^[ -]*\([0-9a-f:]*\).*$/\1/' >/config/www/ipv6
```

This way I can get the IPv6 address out of the container and in principle have access to it anywhere in HA with the static file provision on `http://127.0.0.1/local/ipv6`.

But it seems like the DuckDNS plugin no longer supports getting the IP address by querying a remote website? I really just need any way to set the IPv6 address automatically.  Be it via an http request or via a HA automation.

Any help is appreciated.

**Comment by Chris2834** [comment]
Also habe problems with one of the HA installations I support. One is running IPV4 and one IPV6 with similar DuckDNS configuration. The one running IPV6 seems to run sometimes for a very short while after restart via DuckDNS but then refuses. 
I need to check your workaround to validate if I face the same issue as listed here. But by first reading it matches my checks that the submitted IPV6 is not correct.
Thanks for sharing.

**Comment by Chris2834** [comment]
Problem reoccured, or still remains unstable. Any update?

**Comment by ast0815** [comment]
I mean, it looks like there has not been an update of the plugin, so I guess the same issue remains. I just changed the ipv6 config to `default` for testing, and it chose the right IP address to report to duckdns. But that might have been just pure luck. I will keep an eye on it.

**Comment by ast0815** [comment]
Ah, no. Scratch that. It chose the wrong IP address. It just worked because I tested it from within my home network, where the wrong IP address also works. The IP address it reports to DuckDNS is _not_reachable from the Internet.

**Comment by filewalker1** [comment]
having the same issues...

**Comment by ast0815** [comment]
I guess nothing has happened so the issue is still relevant?
