### ISSUE TITLE
File editor

### ISSUE THREAD

**Issue by TK960517** [home-assistant/addons#2599]
### Describe the issue you are experiencing

Image homeassistant/amd64-addon-configurator:5.3.3 does not exist for addon_core_configurator

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### Which add-on are you reporting an issue with?

File editor

### What is the version of the add-on?

5.3.3

### Steps to reproduce the issue

Just after it was installed

**Comment by mdegat01** [comment]
Try running `ha su repair` from the CLI. Or also just try reinstalling it again.

Also there is definitely something in your supervisor log related to that error, please share it. And if it still happens after the repair can you check if other addons work in the official and community repo or if it's just that one?
