### ISSUE TITLE
MariaDB not starting on 2022.8.2 , 3, & 4 betas

### ISSUE THREAD

**Issue by bschatzow** [home-assistant/addons#2607]
### Describe the issue you are experiencing

After the install the system reboots.  When it comes back on line the Maria DB is not running.  I need to manually restart MariaDB and then restart HA.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

MariaDB

### What is the version of the add-on?

2.5.1

### Steps to reproduce the issue

1. Install 2022.8 (beta 2 and beyond)
2. After restart, Mariadb is not starting.  
3. Not sure why it stopped?
4.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
Nothing in logs other than recorder related stuff.
```

### Anything in the add-on logs that might be useful for us?

```txt
Logs are empty.
```

**Comment by JoshWobbles** [comment]
Same. Mosquitoes won't start either

**Comment by mdegat01** [comment]
If you're on the beta then you're also on the beta version of supervisor (2022.07.1 right?). If so this issue was reported, where some addon appear to not be running but are actually running:
https://github.com/home-assistant/supervisor/issues/3761

I just put in a fix for it and will be putting out a new beta for supervisor momentarily. Does that describe your situation? Is MariaDB actually running just the UI shows it is not?

For reference if MariaDB was actually not running you would know immediately assuming you have set up [recorder](https://www.home-assistant.io/integrations/recorder/) to use it. Your core logs would be absolutely swamped with errors about failing to write history.

**Comment by bschatzow** [comment]
Maria was not started or running.  I think maybe it was a corruption as I had other issues and I am in the process of rebuilding my installation

**Comment by Electronlibre2012** [comment]
i have the same problem and there is an error message : ERROR: Got unexpected response from the API: There is already a MySQL service in use from core_mariadb

the addon doent start anymire automaticaly i have to manually start the addon, then restart Ha, and it work for a few hours then crash again.

my config : 

recorder:
  db_url: mysql://your_login:your_password@core-mariadb/hadb?charset=utf8mb4
  db_max_retries: 1
  include:
    domains:
      - sensor
      - binary_sensor
      - switch
      - light
      - fan
      - media_player
      - alarm_control_panel

**Comment by Wampukas** [comment]
The same issue, it stops every few hours and when you start it again it shows the error mentioned above.

**Comment by kipfel** [comment]
Here the same issue.

**Comment by Electronlibre2012** [comment]
hello, the addon crash every day at 2 am when its backing up...i use google drive backup addon

**Comment by sniner** [comment]
Seems to be a Google Drive Backup problem: https://github.com/sabeechen/hassio-google-drive-backup/issues/682

**Comment by ghost58400** [comment]
I still have this bug with the latest vestion of Google Drive Backup as mentionned above, when I reboot Home Assistant host I have to restart manually MariaDB and then restart Home Assistant

**Comment by mdegat01** [comment]
@bschatzow if the db is corrupted in the backup then restoring it isn't going to go well. But there should definitely be something in the addons logs if that's the case. If you can't see the logs in the UI then could you give this a try: https://community.home-assistant.io/t/how-to-get-to-your-log-after-restart-restore/387662 . It works for addons as well as core logs.

For those using the Google drive addon, do you tell that addon to stop the Mariadb addon before taking a backup? If so then don't do that. That is the solution on the linked bug. There's no reason to stop the addon prior to backing it up, the addon already has a freeze feature for that and it's more efficient.

**Comment by bschatzow** [comment]
@mdegat01 Thank you for responding.  I have no idea if the db was corrupt or not.  I do know that on each restart of HA after 8.2 I had to manually restart Mariadb, then restart HA and that fixed the issue.  I was not seeing errors in the Mariadb log or HA log relating to this.  The errors in HA had to do with recorder as the DB was not started.

I have started a clean install (again) (not from a backup) and I'll get back to this issue on the next update (either now working, or not working)

As to the Google drive addon, I was stopping the MariaDB addon as that was the suggestion to keep the DB from getting corrupted.  Per your suggestion I will make sure it is not stopped prior to the backup.

**Comment by ob1w4nken0b1** [comment]
Same issue here...on reboot MariaDB does not successfully start causing also Nginx, mosquitto and z2m to fail. 
The error it throws in the logs is just a generic "unknown HTTP error occured".
Manually restarting MariaDB and all the other addons afterwards is the only temporary fix i found

**Comment by DmytroKorniienko** [comment]
Same issue, moreover database purge 100% load one of cpu cores for a days!!! If I restart addon - cpu utilisation back to normal, but any next attempt of purge - same problem. Nothing critical in logs btw.

**Comment by KoleBarnes** [comment]
Having the same/similar issue. Getting crashes every so often due to MariaDB becoming unavailable. Add-on shows that MariaDB is not running and can't get it to "start" but HA IS using it. Reinstalling MariaDB doesn't work; no error logs from MariaDB either.

Same time frame. Not in beta.
Home Assistant 2022.8.7
Supervisor 2022.08.5
Operating System 8.5
Frontend 20220802.0 - latest 

MariaDB Current version: 2.5.1

**Comment by ghost58400** [comment]
I had the issue yesterday with fully up-to-date system so I think it is not fixed
