### ISSUE TITLE
500 Server error in ZWave JS

### ISSUE THREAD

**Issue by Guy-Falkes** [home-assistant/addons#2612]
### Describe the issue you are experiencing

Somehow, don't know why, my ZWave JS add-on wont start.
I tried to uninstall and reinstall but even that won't really work (even uninstall failed).
Did a backup restore of the day before and that too seems to have the same issue.

When starting I'm getting this error message but can't find any usefull intel online:
`Failed to start add-on
500 Server Error for http+docker://localhost/v1.41/containers/addon_core_zwave_js/json: Internal Server Error ("stat /mnt/data/docker/overlay2/26a241e61a74a41056d13327555222e493fd3114c9970f3645e70937cdfdc186: no such file or directory")`

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Z-Wave JS

### What is the version of the add-on?

0.1.65

### Steps to reproduce the issue

1.
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:123
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 01:16:45 (5 occurrences)
Last logged: 01:21:49

Failed to to call /addons/core_zwave_js/start - 500 Server Error for http+docker://localhost/v1.41/containers/addon_core_zwave_js/json: Internal Server Error ("stat /mnt/data/docker/overlay2/26a241e61a74a41056d13327555222e493fd3114c9970f3645e70937cdfdc186: no such file or directory")
Failed to to call /addons/core_zwave_js/info - Addon is not installed
```

### Anything in the add-on logs that might be useful for us?

```txt
Logger: homeassistant.components.zwave_js
Source: components/zwave_js/addon.py:384
Integration: Z-Wave (documentation, issues)
First occurred: 01:13:08 (11 occurrences)
Last logged: 01:23:51

Failed to start the Z-Wave JS add-on: 500 Server Error for http+docker://localhost/v1.41/containers/addon_core_zwave_js/json: Internal Server Error ("stat /mnt/data/docker/overlay2/26a241e61a74a41056d13327555222e493fd3114c9970f3645e70937cdfdc186: no such file or directory")
```

**Comment by mdegat01** [comment]
So what you're seeing is this error: https://stackoverflow.com/questions/71314384/docker-var-lib-docker-overlay2-id-merged-no-such-file-or-directory . I've seen it before occasionally too with other addons.

I don't really have a sense of why it happens sometimes but when it happens the fix is pretty straightforward. First try running `ha su repair` from the cli and then starting it again. That should clean up images and containers and try to fix it.

If it still won't start then reboot the host. That is the HAOS equivalent of restarting docker from that post I linked (since everything in HAOS is in docker containers). That has always fixed the issue for me.

**Comment by Guy-Falkes** [comment]
Thanks for trying to help out @mdegat01 .
Since I made the report i created a working workaround. It turns out the complete Z-wave network works just fine without zwave JS and only zwave js2mqtt. This has worked great form me.
On the other hand this whole 500 server error left me a bit worried. If this tends to happen to add-ons, what's the chance of it happening again to another add-on and how to fix it then.

I'm gonna close the issue for now (close as not planned/reproduces/stale) and hope that whenever this happens again someone can reopen the issue and make not of it happening again. If enough people get this issue, a solution should then be make/found/created...
