### ISSUE TITLE
Samba is not configurable, but requires configuration

### ISSUE THREAD

**Issue by Commod0re** [home-assistant/addons#2617]
### Describe the issue you are experiencing

Samba Share 10.0.0 is impossible to use as a first time user. Initial configuration is required, but it's impossible to satisfy because no configuration is allowed.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Samba share

### What is the version of the add-on?

10.0.0

### Steps to reproduce the issue

1. Install Samba Share 10.0.0
2. Click Start and see the following modal
<img width="498" alt="Screen Shot 2022-08-16 at 6 18 41 PM" src="https://user-images.githubusercontent.com/2621594/185013547-3ec3baa1-1e2f-43b9-b18e-4b132fdb725f.png">
3. click "Edit Config" or even just the "Configuration" tab and see the following
<img width="769" alt="Screen Shot 2022-08-16 at 6 19 26 PM" src="https://user-images.githubusercontent.com/2621594/185013614-a065e6e1-98af-4df8-ba87-ababe2a3fbc8.png">

**Comment by mdegat01** [comment]
There was a frontend bug for a bit with addons. It should be fixed now though. If you are somehow still seeing this then do the following:
1) clear your cache
2) go back to the list of installed addons
3) refresh the page
4) click on the samba addon and go to the configuration tab

You should now see the options as expected. And hopefully it won't happen again with the latest frontend in use.
