### ISSUE TITLE
Anonymous logins removed from Mosquitto Add-on

### ISSUE THREAD

**Issue by DCSBL** [home-assistant/addons#2623]
### Describe the issue you are experiencing

I have some wifi devices that can connect to a MQTT broker, but they do not provide a way to set an username/password nor they have one. Because of this I get this error: 
```
1661075134: Sending CONNACK to ::ffff:192.168.5.152 (0, 5)
1661075134: Client <unknown> closed its connection.
error: received null username or password for unpwd check
```
After looking around a bit, I saw that [this PR](https://github.com/home-assistant/addons/pull/2007) removed support for anonymous logins, why? 

Why can't we just add the `allow_anonymous true` config in the customise part? Or is it not as easy as it seems?

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Mosquitto broker

### What is the version of the add-on?

6.1.2

### Steps to reproduce the issue

1. Rewritten a DNS record so the device tries to make a connection to the Mosquitto add-on
2. Saw that the device was able to connect
3. Saw that the device was not able to authenticate, connection was disconnected.

```
logins: []
require_certificate: false
certfile: fullchain.pem
keyfile: privkey.pem
customize:
  active: true
  folder: mosquitto
```

```
# acl.conf
allow_anonymous true
acl_file /share/mosquitto/accesscontrollist
```

```
# accesscontrollist
topic readwrite #
```

### Anything in the add-on logs that might be useful for us?

```txt
...
1661075508: Sending CONNACK to ::ffff:192.168.5.152 (0, 5)
1661075508: Client <unknown> closed its connection.
error: received null username or password for unpwd check
1661075524: Sending CONNACK to ::ffff:192.168.5.152 (0, 5)
1661075524: Client <unknown> closed its connection.
1661075528: New connection from 172.30.32.2:39318 on port 1883.
1661075528: Client <unknown> closed its connection.
error: received null username or password for unpwd check
1661075540: Sending CONNACK to ::ffff:192.168.5.152 (0, 5)
1661075540: Client <unknown> closed its connection.
error: received null username or password for unpwd check
1661075556: Sending CONNACK to ::ffff:192.168.5.152 (0, 5)
1661075556: Client <unknown> closed its connection.
error: received null username or password for unpwd check
...
```

**Comment by DCSBL** [comment]
But why is it enforced by this add-on and not configurable?

**Comment by doug62** [comment]
Thanks for clarifying - since Anonymous is officially removed I can now stop wasting my time on this and use a different broker, very unfortunate.

**Comment by atamgp** [comment]
christ!

I spend a week trying to make this work.
@mdegat01 If you choose to do this, also state it in the addon documentation?
Now you only refer to the man page making everyone assume all features are supported....

**Comment by atamgp** [comment]
@DCSBL has a good point.... it's up to the user

**Comment by DCSBL** [comment]
@atamgp easy... you are talking to volunteers. Open a PR to change the documentation yourself if you have issues.

Anyway, I was able to fix my situation with the use the (quite new) EMQX addon. This broker is highly configurable. https://github.com/hassio-addons/addon-emqx

**Comment by atamgp** [comment]
you're right, I did not mean it offensive :)
will take a look at emqx, thanks for the suggestion.

**Comment by s0170071** [comment]
> 

has this been fixed ? I really love anonymous for my home IoT.

**Comment by nickm324** [comment]
> > 
> 
> has this been fixed ? I really love anonymous for my home IoT.

Its not broken, they removed anonymous on purpose.

**Comment by Write** [comment]
> @atamgp easy... you are talking to volunteers. Open a PR to change the documentation yourself if you have issues.
> 
> Anyway, I was able to fix my situation with the use the (quite new) EMQX addon. This broker is highly configurable. https://github.com/hassio-addons/addon-emqx

High, did you find a way to use certificate ? I need it for meross_lan support : https://github.com/bytespider/Meross/wiki/MQTT

**Comment by dturner** [comment]
There is one perfectly legitimate use case for anonymous logins: **debugging**. 

Removing it just makes it more difficult for new users to debug MQTT issues.

**Comment by DCSBL** [comment]
Use [EMQX](https://github.com/hassio-addons/addon-emqx), you can do the same and have full control over all your settings.

**Comment by mrmiles156** [comment]
How is this done in EMQX? is it something to do with the ACL file?

**Comment by dturner** [comment]
> Use [EMQX](https://github.com/hassio-addons/addon-emqx), you can do the same and have full control over all your settings.

Yeah, I actually ended up just using DietPi/Mosquitto directly. My point was that disabling anonymous logins is, in my opinion, a fairly arrogant decision which is likely to drive people away from Home Assistant. If anonymous logins were such an enormous security issue then it should be up to the Mosquitto authors to disable it, not Home Assistant.

**Comment by SomeFixItDude** [comment]
The library I use on my MCU doesn't support anything but anonymous. This should be an option, please reconsider.

**Comment by kerryland** [comment]
> > Use [EMQX](https://github.com/hassio-addons/addon-emqx), you can do the same and have full control over all your settings.
> 
> Yeah, I actually ended up just using DietPi/Mosquitto directly. My point was that disabling anonymous logins is, in my opinion, a fairly arrogant decision which is likely to drive people away from Home Assistant. If anonymous logins were such an enormous security issue then it should be up to the Mosquitto authors to disable it, not Home Assistant.

Absolutely an arrogant decision, but that's not unusual.

My favourite part is that the alternative broker, [EMQX](https://github.com/hassio-addons/addon-emqx), which _allows_ for unauthorised clients, is provided by the same developer who _removed_ unauthorised clients from the Mosquitto addon.

Fingers crossed he doesn't do the same to EMQX addon!

**Comment by kerryland** [comment]
> Guess my only alternative is to migrate to EMQX, but I hear Mosquitto is more stable, so guess I will migrate back after I am done debugging.

The switch to EMQX was utterly painless. I've had no problems at all with it.

**Comment by antst** [comment]
It is still ridiculous, from my point of view. Proper security practice would be disable anonymous by default but still provide option to enable, like mosquitto does.
Otherwise it is kind of stupid situation, where, despite the fact that mosquito fits the bill perfectly, I need to install EMQX, or installing broker somewhere else, killing whole concept of haos approach.

**Comment by DCSBL** [comment]
Can we end this discussion, please?

https://boyter.org/posts/the-three-f-s-of-open-source/

**Comment by antst** [comment]
> Can we end this discussion, please?
> 
> https://boyter.org/posts/the-three-f-s-of-open-source/

Followed your advice :)

For people who for whatever reasons also need anonymous and don't want to go EMQX way, here is my fork of official add-on, but with anonymous mode re-enabled.
https://github.com/antst/hass_addons

**Comment by bjanders** [comment]
I was struggling with this as well. I also think that it should be up to the user what is secure enough. The default settings should be secure by not allowing anonymous access, but for example, a user may have a closed secure network where only trusted devices can connect, then anonymous access could be perfectly fine for the required security level.

At the minimum, it should be clearly documented that anonymous access has been completely disabled (unlike the standard mosquitto).

EMQX solved this for me as well.

**Comment by Ylianst** [comment]
Thank you for this discussion. I have a new AFERIY P310 battery and I need to have a MQTT server anonymous access ([Details here](https://github.com/schauveau/sydpower-mqtt)). In an ideal world, I would allow anonymous access only for a specific inbound IP address. I will give EMQX a try.

**Comment by richardsg307** [comment]
I am already heavily invested in Mosquitto with Integrations/Add-ons like Zigbee2MQTT, GivTCP, Tasmota, Axle VPP, and many more.

How painless would the switch to EMQX or Anonymous Mosquitto broker be?

My use case is to connect an Aferiy P280 to HA and control when AC charging is enabled (00:00-06:00 Cheap rate).

I'm also aware there is a an ESP32/BLE way to get the connection. Maybe I'll do that.

**Comment by Ylianst** [comment]
@richardsg307 - I ended up looking at EMQX for a few minutes and deciding it's not worth it and build my own ESPhome integration, that was much better: [https://github.com/Ylianst/ESP-FBot](https://github.com/Ylianst/ESP-FBot)

**Comment by kerryland** [comment]
> How painless would the switch to EMQX or Anonymous Mosquitto broker be?

It's completely painless. Stop Mosquitto and start EMQX.

That's it.

(Well, make sure EMQX is running on port 1883, like mosquito does. I don't remember if I need to change that). 

... but maybe your use case is better handled by @Ylianst's integration. I don't know

**Comment by Ylianst** [comment]
This is a bit off topic, but using MQTT to talk to these batteries requires faking the DNS name to cause the battery to connect to your server which is a bit of a hack, but it depends on your situation. With a Bluetooth integration, you get correct connection and data flowing from the battery.

**Comment by richardsg307** [comment]
> It's completely painless. Stop Mosquitto and start EMQX.

I'm begining to see that. However, i think i will still need to add my current username/password to the EMQX setup along with an anonymous thing for the P280. Not sure how to do that!

Meanwhile, I've just got the ESP32/BLE version going and found it doesn't do the AC Charge Booking thing and you cannot use it and the BrightEMS app at the same time! So, I'm not finished yet.
