### ISSUE TITLE
DHCP Server Add-on not showing record time in logs in UI

### ISSUE THREAD

**Issue by Masterz69** [home-assistant/addons#2628]
### Describe the issue you are experiencing

DHCP Server Add-on not showing record time in logs in UI

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

DHCP Server

### What is the version of the add-on?

1.3.0

### Steps to reproduce the issue

Just install add-on and check the logs.

### Anything in the add-on logs that might be useful for us?

```txt
DHCPDISCOVER from 94:b5:55:f8:07:bc (espressif) via eth0
DHCPOFFER on 192.168.1.220 to 94:b5:55:f8:07:bc (espressif) via eth0
reuse_lease: lease age 82524 (secs) under 25% threshold, reply with unaltered, existing lease for 192.168.1.220
DHCPREQUEST for 192.168.1.220 (192.168.1.11) from 94:b5:55:f8:07:bc (espressif) via eth0
```

**Comment by mdegat01** [comment]
This addon just runs [dhcpd](https://linux.die.net/man/8/dhcpd). This software does not provide any options around changing how logs are output so there's nothing we can do here. If you are unsatisfied with the current views on logs in HA, see [here](https://community.home-assistant.io/t/how-to-get-to-your-log-after-restart-restore/387662) for how to get to the system journal and the details it provides.
