### ISSUE TITLE
DNSMasq Add-on not showing time in logs in UI

### ISSUE THREAD

**Issue by Masterz69** [home-assistant/addons#2629]
### Describe the issue you are experiencing

DNSMasq Add-on not showing time in logs in UI

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Dnsmasq

### What is the version of the add-on?

1.4.4

### Steps to reproduce the issue

Install Add-on and see the logs.

### Anything in the add-on logs that might be useful for us?

```txt
dnsmasq[210]: reply checkonline.home-assistant.io is 172.67.68.90
dnsmasq[210]: reply checkonline.home-assistant.io is 104.26.5.238
dnsmasq[210]: reply checkonline.home-assistant.io is 104.26.4.238
dnsmasq[210]: reply checkonline.home-assistant.io is 172.67.68.90
dnsmasq[210]: reply checkonline.home-assistant.io is 104.26.5.238
```

**Comment by mdegat01** [comment]
This addon just runs [dnsmasq](https://linux.die.net/man/8/dnsmasq). From what I can see there are no options provided which allow customization of those logs or addition of a timestamp. As I said on the other issue, if you are unsatisfied with the current views on logs in HA, see [here](https://community.home-assistant.io/t/how-to-get-to-your-log-after-restart-restore/387662) for how to get to the system journal and the details it provides.
