### ISSUE TITLE
Spam at log. Messages like: New connection from 172.30.32.2

### ISSUE THREAD

**Issue by KitHubek** [home-assistant/addons#2634]
### Describe the issue you are experiencing

At log many many logs ad below:

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Mosquitto broker

### What is the version of the add-on?

6.1.2

### Steps to reproduce the issue

1. Go to mosquito logs
2.
3.
...

### Anything in the add-on logs that might be useful for us?

```txt
1661770800: New connection from 172.30.32.2:54258 on port 1883.
1661770800: Client <unknown> closed its connection.
1661770920: New connection from 172.30.32.2:54260 on port 1883.
1661770920: Client <unknown> closed its connection.
1661771040: New connection from 172.30.32.2:54262 on port 1883.
1661771040: Client <unknown> closed its connection.
1661771160: New connection from 172.30.32.2:54264 on port 1883.
1661771160: Client <unknown> closed its connection.
1661771280: New connection from 172.30.32.2:54266 on port 1883.
1661771280: Client <unknown> closed its connection.
1661771400: New connection from 172.30.32.2:54268 on port 1883.
1661771400: Client <unknown> closed its connection.
1661771520: New connection from 172.30.32.2:54270 on port 1883.
1661771520: Client <unknown> closed its connection.
1661771640: New connection from 172.30.32.2:54272 on port 1883.
1661771640: Client <unknown> closed its connection.
1661771760: New connection from 172.30.32.2:54274 on port 1883.
1661771760: Client <unknown> closed its connection.
1661771880: New connection from 172.30.32.2:54276 on port 1883.
1661771880: Client <unknown> closed its connection.
1661772000: New connection from 172.30.32.2:54278 on port 1883.
1661772000: Client <unknown> closed its connection.
1661772120: New connection from 172.30.32.2:54280 on port 1883.
1661772120: Client <unknown> closed its connection.
1661772240: New connection from 172.30.32.2:54282 on port 1883.
1661772240: Client <unknown> closed its connection.
1661772360: New connection from 172.30.32.2:54284 on port 1883.
1661772360: Client <unknown> closed its connection.
1661772480: New connection from 172.30.32.2:54286 on port 1883.
1661772480: Client <unknown> closed its connection.
```

**Comment by martijntinus** [comment]
Had the same issue, devices cant connect to the mqtt server ether. After two or three restarts it fixed itself.

**Comment by mdegat01** [comment]
If you disable watchdog does it go away?

**Comment by klausdm** [comment]
Had same issue after installing 6.1.3. Rebooted twice.... came back to normal operation.

**Comment by hdprice** [comment]
I've got the same problem, ring-mqtt can't connect, it's logs say it's not authorized. Triple checked all configs, everything looks good and this wa working for over 2 years before the update last week.

**Comment by almirus** [comment]
workaround - Simply edited the file in the Mosquitto Configuration page, using the 3 dots at the top and choosing edit in yaml, delete last space and save

**Comment by madAndroid** [comment]
Experiencing the same issue - any Home Assistant restart causes the broker to fail.. restarting the broker via the add-on in supervisor, "fixes" the problem, until the next HA restart.

**Comment by jkasten80** [comment]
Same for me

**Comment by SCratORS** [comment]
Same for me

**Comment by jkasten80** [comment]
Any news here? The problem is still there

**Comment by SCratORS** [comment]
This problem is solved by disabling watchdog

**Comment by roblatour** [comment]
bad bot - this issue is not resolved - problem remains notwithstanding work arounds

**Comment by KitHubek** [comment]
problem still exsist

**Comment by ngosang** [comment]
Problem still exists in 2023.12.1

**Comment by vbueschken** [comment]
Problem still exists in 2023.12.3

**Comment by Ferrari2** [comment]
Still exist at 30.1.2024 :-)

**Comment by tokken1** [comment]
Problem besteht immer noch am 7.02.2024

**Comment by Seylox** [comment]
So apparently this is not an issue but rather an (annoying) side effect of the hass.io supervisor checking if the add-on is still responding. See also @frenck's response here: https://github.com/home-assistant/core/issues/51603#issuecomment-856523532

**Comment by starsoccer** [comment]
> So apparently this is not an issue but rather an (annoying) side effect of the hass.io supervisor checking if the add-on is still responding. See also @frenck's response here: [home-assistant/core#51603 (comment)](https://github.com/home-assistant/core/issues/51603#issuecomment-856523532)

Ive seen that thread and while I understand this is a semi intended effect, the effect is still an annoyance to many. I think there are alternative options to check for uptime that dont require a log entry.

Or alternatively just simply implementing a filter to not show these logs, or better yet not log this in the first place if its coming from the supervisor would also be a decent solution
