### ISSUE TITLE
File Editor refuses to start

### ISSUE THREAD

**Issue by thomasdexe** [home-assistant/addons#2645]
### Describe the issue you are experiencing

I just installed Home Assistant OS (2022.8.7) on a Raspberry Pi, and installed the File Editor add-on (5.3.3) and when I click Start for the File Editor, it seems like it should be starting but it does not. When I click start again it does nothing. I've tried restarting HA, uninstalling/reinstalling File Editor and nothing seems to change, each time it ends up with the exact same logs

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

File editor

### What is the version of the add-on?

5.3.3

### Steps to reproduce the issue

1. Click Install on File Editor Add-on page
2. Click Start
3. Loading spinner shows up, goes away, it is not started.

### Anything in the add-on logs that might be useful for us?

```txt
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
INFO:2022-09-01 20:48:42,687:hass_configurator.configurator:Starting server
INFO:2022-09-01 20:48:42,689:hass_configurator.configurator:Listening on: http://0.0.0.0:8099
```

**Comment by okovjogurtu** [comment]
Same problem, restore backup didn't help

**Comment by xBoNeAU** [comment]
Also having this issue. Seems to also affect samba starting, although it appears it could still be running as I can access shared folders. But file editor won't run at all

**Comment by noiwid** [comment]
Hi, same for me. 
I just had to reinstall H.A, due to corrupted drive. I've switch to H.A OS (instead of installation via docker).
I've restore my latest backup, but the file editor is now broken.

Here is the File Editor logs ;
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun configurator (no readiness notification)
s6-rc: info: service legacy-services successfully started
INFO:2022-09-12 16:51:28,529:hass_configurator.configurator:Starting server
INFO:2022-09-12 16:51:28,532:hass_configurator.configurator:Listening on: http://0.0.0.0:8099

H.A don't log anything about this...

**Comment by pur3asdf** [comment]
same problem after i changed booting from sd card to ssd on raspi 4 today

**Comment by xBoNeAU** [comment]
Also couldn't find any logs to suggest it wasn't working.
Fresh install and then restore still had the same problem.
Fresh install and then built everything from the ground back up again.
All working now, unfortunately I could not find a fix that didn't involve a rebuild.

**Comment by noiwid** [comment]
Hi, 
i found a workaround:
A - backup H.A
b - fresh install
C - partial restore of the backup, except File Editor
D - reinstall manually File Editor.

I also just realize yesterday that File Editor has its own logs! Go on System -> logs page, and check the menu in the upper right corner, it allow to switch to different logs..

**Comment by mdegat01** [comment]
Any errors related to the file editor addon in the supervisor logs? You can find those in the same place as the file editor logs:
> I also just realize yesterday that File Editor has its own logs! Go on System -> logs page, and check the menu in the upper right corner, it allow to switch to different logs..

Just switch to supervisor instead.

**Comment by GreenBlast** [comment]
I'm having the same issue, and I don't really want to do a fresh install to do a partial restore.

I assume that there is a somewhere a configuration file that doesn't get deleted when the add on is deleted?

**Comment by toniofig** [comment]
Hi, 
fyi
same issue with v5.4.2, file editor "START" won't do anything.
Using proxmox to restart the system, and the problem went away.

**Comment by fxstein** [comment]
Same problem on a brand new install with HASS OS on a NUC. File editor keeps spinning the circle and will never start.

**Comment by imilchev** [comment]
Any solution for this? I am running into the same problem and would prefer to not re-install everything. Can someone provide some info which file we need to delete to solve the problem?

**Comment by auggy** [comment]
I’m also having the same problem and my system is up to date.

**Comment by LunchboxNYC** [comment]
Having the same issue with a new home assistant yellow setup

**Comment by copadewe** [comment]
Intel Nuc, totally new setup of HA and loaded the file editor, after installing click on "start" nothing happend.
But in the left side there is "file editor" and when I click I can work with.

**Comment by DickiePhitt** [comment]
I have the same problem with File Editor initially giving a not started message then refusing to start from the Add-on. Removed and re-installed Add-On without any resolution

**Comment by Henrik1986** [comment]
I had the same problem but after a full reboot the file editor starts again. 

Go to 
1. Settings
2. System
3. Hardware
4. Push the three dots
5. Reboot system

**Comment by slouma79** [comment]
try rebooting the hardware

**Comment by ChrisFarwell** [comment]
> try rebooting the hardware not only supervisor

This worked for me. Thank you.

**Comment by AubsUK** [comment]
Restarting the whole hardware (well, VM) worked for me too.
