### ISSUE TITLE
Updates Z-Wave JS 0.1.67 and 0.1.68 turns on LED on UZB1

### ISSUE THREAD

**Issue by demey** [home-assistant/addons#2648]
### Describe the issue you are experiencing

LED turns on on both versions (0.1.67, 0.1.68) and turns off in case of returning to 0.1.65
On version 0.1.65 LED has normal behavior.
I made update to 0.1.67 and observed this issue after that restored 0.1.65 from backup.
In several days I updated add-on to 0.1.68 and faced with the same issue.
At this moment add-on restored to 0.1.65.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Z-Wave JS

### What is the version of the add-on?

0.1.67 and 0.1.68

### Steps to reproduce the issue

1. Update add-on version to 0.1.67 or 0.1.68 via GUI.

**Comment by johandijkstra** [comment]
There are more issue with > 0.1.65, I have issues with fibaro devices which do not work anymore
