### ISSUE TITLE
Git pull add-on wipes Home Assistant config (Caused by DNS failure??)

### ISSUE THREAD

**Issue by EmnaX** [home-assistant/addons#2653]
### Describe the issue you are experiencing

Hello,
I just installed the "Git pull" add-on, set it all up, clicked "start" and now my configuration directory is completely empty except for some files in a "node-red" folder.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### Which add-on are you reporting an issue with?

Git pull

### What is the version of the add-on?

7.13.1

### Steps to reproduce the issue

1. Install Git pull add-on
2. Fill out "Configuration" page for add-on
3. Run add-on

### Anything in the Supervisor logs that might be useful for us?

```txt
# Probably not but this was around the time I did the update:

22-09-06 21:45:06 INFO (SyncWorker_3) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-git_pull with version 7.13.1
22-09-06 21:45:44 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API connection is closed
22-09-06 21:45:48 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Node-RED is stopped, restarting...
22-09-06 21:45:48 INFO (SyncWorker_9) [supervisor.docker.interface] Cleaning addon_a0d7b954_nodered application
22-09-06 21:45:49 INFO (SyncWorker_2) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/node-red/amd64 with version 13.3.2
22-09-06 21:45:58 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize
22-09-06 21:45:58 INFO (MainThread) [supervisor.api.proxy] WebSocket access from a0d7b954_nodered
22-09-06 21:45:58 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running
22-09-06 21:46:04 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_ssh
22-09-06 21:46:04 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_ssh
22-09-06 21:46:04 INFO (MainThread) [supervisor.api.middleware.security] /host/info access from core_ssh
22-09-06 21:46:04 INFO (MainThread) [supervisor.api.middleware.security] /core/info access from core_ssh
```

### Anything in the add-on logs that might be useful for us?

```txt
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Check SSH connection
[Warn] No valid SSH connection for ssh
[Info] Start adding SSH key
[Info] Setup deployment_key on id_ed25519
[Warn] Git repostory doesn't exist
[Info] Backup configuration to /tmp/config-2022-09-06_21-45-09
[Info] Start git clone
Cloning into '/config'...
ssh: Could not resolve hostname git.vps.example.ca: Name does not resolve

fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
[Error] Git clone failed
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

### Additional information

I'm not sure exactly what happened but the add-on logs show that DNS resolution failed so I'm guessing that's why? It could be some other configuration error I have made in the add-on... not sure. Based on the error, let's assume DNS might have played a roll. Here is some more info:

I am running a local Gitea installation on a separate server that I was hoping to use for config versioning. The repo was already populated with a copy of Home Assistant's config directory so if anything was pulled with the add-on, it should have been fine. The FQDN for the Gitea installation is `git.vps.example.ca`. That URL will not resolve if an external DNS server is queried. I have my own internal DNS which Home Assistant is set to use. That being said, something strange is happening. If I SSH into Home Assistant, the command `dig` resolves the correct IP address fine but `ping git.vps.example.ca` says `ping: bad address git.vps.example.ca`. If I plug in the IP address for the Gitea installation and re-run `ping`, it works as expected.

One more item, the add-logs state `[Info] Backup configuration to /tmp/config-2022-09-06_21-45-09` but after SSH'ing into the system, I don't see any backup folder there.

**Comment by mdegat01** [comment]
From the docs for the addon:
https://github.com/home-assistant/addons/blob/master/git_pull/DOCS.md#warning

So yea, like it says, you need to make a backup first. It's going to wipe your config folder and try and clone. If that fails, then there's no config.

> One more item, the add-logs state [Info] Backup configuration to /tmp/config-2022-09-06_21-45-09 but after SSH'ing into the system, I don't see any backup folder there.

This is inside the git pull container. If you ssh'ed in then you're inside the SSH container. Each container has its own `/tmp` folder so you won't see it there. Not sure why it makes this backup but its not really possible to restore from it. Hence why the docs say to take a backup first.

>  If I SSH into Home Assistant, the command dig resolves the correct IP address fine but ping git.vps.example.ca says ping: bad address git.vps.example.ca. If I plug in the IP address for the Gitea installation and re-run ping, it works as expected.

If you do `dig AAAA git.vps.example.ca` aimed at your local DNS server, what happens? Specifically what is the status returned? Is it `NOERROR` or `NXDOMAIN`? If it's `NXDOMAIN` then your DNS server is not handling DNS correctly and it won't work well with HA (or any musl-based system). If you want to know why `AAAA` queries matter here, I put up a pretty good explanation [here](https://community.home-assistant.io/t/local-dns/178108/117?u=centralcommand)

**Comment by EmnaX** [comment]
Hi Mike,

Thanks for taking the time to have a look at this!

Your first two points make sense.

The last bit about the DNS is interesting. When I run `dig AAAA git.vps.example.ca` I do indeed get `nxdomain`. My local DNS server is `Unbound` running on `pfSense`. I had a look at the options on pfSense and nothing jumped out at me as to how to go about fixing the issue. I'll have to read up on Unbound to see if there is some way to fix this or maybe it's just a limitation with Unbound.

I do have IPv6 networking disabled for HA as well as on my pfSense box but I guess this has more to do with how Unbound responds as you described in your link.

Thanks for pointing me in the right direction, I'll try to figure out how to resolve the DNS issue now.

**Comment by EmnaX** [comment]
Just a quick follow up to the DNS issue if someone else stumbles across this with a similar setup. In pfSense, under `Services` --> `DNS Resolver` --> `General Settings`, changing the value of `System Domain Local Zone Type` to `Transparent` fixed the issue for me.

For some additional reading on zone types: https://man.openbsd.org/unbound.conf

I'll have to give this add-on another shot now that DNS is working better :) Thanks again Mike!
