### ISSUE TITLE
Deconz addon blocks my IP 

### ISSUE THREAD

**Issue by rubenp1986** [home-assistant/addons#2658]
### Describe the issue you are experiencing

After using the official Deconz addon for months the following problem appears on my installation. 
Every time I open the Phoscon Web App or the deConz application, I get notified that my (Local) ip was blocked. 
Only if I access my installation form an other location I can access both the web app and the deconz app. 

The error I receive is: Login attempt or request with invalid authentication from (myIP).
Login attempt or request with invalid authentication from (myIP). Requested URL: '/api/config?_=1662667'. (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36)
(WAARSCHUWING) HTTP - bericht kwam voor het eerst om 21:27:57 en verschijnt 407 keer

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

deCONZ

### What is the version of the add-on?

6.15.0 

### Steps to reproduce the issue

1. Open the DeConz addon
2. Click on deconz or phoscon
3. No access to the  app
...

**Comment by NanoWireDnB** [comment]
I had the exact problem with Google Chrome. Worked flawlessly in another browser, which made me suspicious that it might be a cookie problem. It worked in an Google Chrome Incognito Tab. I cleared all cookies and website data related to home assistant and voilà, problem solved.

**Comment by kukulich** [comment]
I have the exact problem Firefox and also in Home Assistant app on iOS.

**Comment by flatty2804** [comment]
I have the same problem, but not browser related. all entities are working, but i cannot login to Phoscon or Deconz app. any news?

**Comment by rubenp1986** [comment]
For me it is also not a browser based problem. It seems however be a IP problem. I switched to another location and that solved the problem. But after the last HA upgrade, I now have access to deconz from my own IP.  I am not sure if this was solved by the update of that it was a coincidence.

**Comment by Whippie72** [comment]
The same on me. i already thought i had done something wrong. 
All entities are there and working, but i can't login to deconz/phoscon because my IP is blocked.

Has the code owner been able to look at this? @Kane610

**Comment by Kane610** [comment]
> The same on me. i already thought i had done something wrong. All entities are there and working, but i can't login to deconz/phoscon because my IP is blocked.
> 
> Has the code owner been able to look at this? @Kane610

I have no idea, I'm not the code owner of the add-on

**Comment by rubenp1986** [comment]
can you check if you can login via another location? That worked for me. Both a different physical location and with a public (mobile phone) IP address did work for me. After one of the last updates, this problems seems to be solved for me.

**Comment by Whippie72** [comment]
> can you check if you can login via another location? That worked for me. Both a different physical location and with a public (mobile phone) IP address did work for me. After one of the last updates, this problems seems to be solved for me.

thanks for the hint, but it doenst work for me on any location. i even tried to login with cellular (mobile).


> > The same on me. i already thought i had done something wrong. All entities are there and working, but i can't login to deconz/phoscon because my IP is blocked.
> > Has the code owner been able to look at this? @Kane610
> 
> I have no idea, I'm not the code owner of the add-on

i'm sorry, but you were listed as a code owner for deconz. hopefully someone else has a look on this topic.

**Comment by Kane610** [comment]
> i'm sorry, but you were listed as a code owner for deconz. hopefully someone else has a look on this topic.

Im code owner for the integration but have nothing to do with the add-on
