### ISSUE TITLE
devices in tellstick.conf isnt read/visable

### ISSUE THREAD

**Issue by tomasenskede** [home-assistant/addons#2665]
### Describe the issue you are experiencing

I have installed the addon according to the instruction on my HA 2022.9.2 with my TellStick (1781/C31) 

I have added flowing lines in configuration.yaml ;
# TellStick add-on
tellstick:
  host: core-tellstick
  port: [50800, 50801]

light:
  - platform: tellstick
sensor:
  - platform: tellstick

and I have created an ./etc/tellstick.conf with the following sample informantion;

devices:
  id = 1
  name = "Farstu, fönster"
  protocol = "arctech"
  model = "codeswitch"
  parameters {
    house = "13463"
    unit = "1"
  }

I can not reach "Farstu, fönster" in the device list within HA... whats wrong?

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

TellStick

### What is the version of the add-on?

2.1.0

### Steps to reproduce the issue

1.
2.
3.
...

**Comment by tomasenskede** [comment]
log file;

[16:15:55] INFO: Initialize the tellstick configuration...
[16:15:58] INFO: Exposing sockets and loading service...
telldusd daemon starting up
[16:15:58] INFO: Starting event listener...
Connecting to TellStick (1781/C31) with serial A63LN6LW

**Comment by mdegat01** [comment]
> and I have created an ./etc/tellstick.conf with the following sample informantion;

Tellstick runs in a docker container. I'm not sure where exactly you're putting that file but its not in the docker container tellstick is running in. It has its own `/etc` and won't see your file.

The only options addons have are what is in the configuration tab of the addon. See [here](https://github.com/home-assistant/addons/blob/master/tellstick/DOCS.md#configuration) in the addon doc for how to configure your tellstick devices.
