### ISSUE TITLE
MariaDB doesn't use the query cache

### ISSUE THREAD

**Issue by RubenKelevra** [home-assistant/addons#2667]
### Describe the issue you are experiencing

I noticed that the mariadb addon has the query cache turned off by default. Turning it on via `query_cache_type=on` and `query_cache_size=2​097​152` gave me a significant performance improvement on my Rasberry Pi 4 when (re)loading graphs with many values.

It would be neat if the query cache size could be set via the settings options of the add-on and have a sensible default, like 10% memory of the host? :)

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

MariaDB

### What is the version of the add-on?

2.5.1

### Steps to reproduce the issue

1. Install add-on
2. Look at the value of variable `query_cache_size` and `query_cache_type` which are zero and 'OFF'

### Additional information

Documentation on these options:

https://mariadb.com/kb/en/server-system-variables/#query_cache_type

https://mariadb.com/kb/en/server-system-variables/#query_cache_size

**Comment by Xitee1** [comment]
Still an issue.
I wanted to enable caching but there is no option for it.

I don't know exactly what the caching is doing, but I mainly wanted to enable it to reduce disk writes because I have many entities which are updating like all two seconds.
