### ISSUE TITLE
DuckDNS add-on stopped updating IP addresses

### ISSUE THREAD

**Issue by tdragon** [home-assistant/addons#2668]
### Describe the issue you are experiencing

At some point the DuckDNS add-on stopped updating both IPv4 and IPv6 address. I cannot say when it happened, I didn't access my host from outside for a while.

There are warning in the add-on log, see below.

But if I run `curl -s "https://www.duckdns.org/update?domains={my domain}&token={my token}&ipv6={my ipv6}&verbose=true"` manually in the SSH add-on, I get:
```
OK

{my ipv6}
UPDATED
```
And I can see the address is updated on duckdns.org.
The same happens for the Ipv4 - no automatic updates, but manual update works fine.

Am I doing something wrong?

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Duck DNS

### What is the version of the add-on?

1.15.0

### Steps to reproduce the issue

My configuration:
```
domains:
  - "*.{my domain}.duckdns.org > {my domain}.duckdns.org"
token: {my token
aliases: []
lets_encrypt:
  accept_terms: true
  algo: secp384r1
  certfile: fullchain.pem
  keyfile: privkey.pem
seconds: 300
ipv6: default
```

### Anything in the add-on logs that might be useful for us?

```txt
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
# INFO: Using main config file /data/workdir/config
+ Account already registered!
[12:49:53] WARNING: 
[12:49:53] WARNING: 
[12:49:54] INFO: Renew certificate for domains: .....
```

The `WARNING` line is repeated continuously.
```


### Additional information

_No response_

**Comment by MagnaPilot** [comment]
Just want to add, I have one installation with the same issue.  Just a continuous WARNING message in the logs over time.  Never updates the IPv4 (I don't use v6).  Have verified the host can access the required internet sites for proper updates. 

Addon Version:  1.15
Addon Log:
`s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
# INFO: Using main config file /data/workdir/config
+ Account already registered!
[07:22:21] WARNING: 
[07:22:24] INFO: Renew certificate for domains: *.mydomain.duckdns.org > mydomain.duckdns.org and aliases: 
# INFO: Using main config file /data/workdir/config
Processing *.mydomain.duckdns.org
 + Checking domain name(s) of existing cert... unchanged.
 + Checking expire date of existing cert...
 + Valid till Dec 10 12:00:52 2022 GMT (Longer than 30 days). Skipping renew!
[07:27:39] WARNING: `

**Comment by benrafshoon** [comment]
I am seeing the same symptoms. On version 1.15, repeated "WARNING: " lines in the logs every 5 minutes. I only have ipv4 updates configured. When I ssh into my home assistant instance, I can successfully run `curl "https://www.duckdns.org/update?domains=${DOMAINS}&token=${TOKEN}&ip=${ipv4}&verbose=true"` with DOMAINS and TOKEN variables set in bash.

**Comment by tdragon** [comment]
The issue is still here. Do not close it, please! Reinstallation of the addon does not help. 
I can provide additional info if needed.

**Comment by alfarocch** [comment]
I have the same problem: last month autoupdate stop work :-(

**Comment by alfarocch** [comment]
thx, but is an complicated solution (i don't need home-assistant). There is a log od duckdns client?

**Comment by benrafshoon** [comment]
This is still reproing for me; it should be reopened.
