### ISSUE TITLE
Zigbee and Z-Wave devices not active anymore

### ISSUE THREAD

**Issue by hcpalka** [home-assistant/addons#2675]
### The problem

After updating to V9.5 and installing the latest version of Z-Wave the Zigbee devices (Deconz connected with ConbeeII-Stick) are still visible, but grey - hence no communication is happening anymore.

I have already dis-connected the USB-stick and re-connected - restarted the system - no change

Any idea how to solve this problem.

Thank you

Best regards

Christian

![deconz](https://user-images.githubusercontent.com/68823369/191454935-1a0a06e2-fd47-453a-841c-7529da9cdd68.jpg)
![hassio_version](https://user-images.githubusercontent.com/68823369/191454962-7f579529-6efd-41cb-a64c-7ed1ad3be9bc.jpg)
![devices](https://user-images.githubusercontent.com/68823369/191455011-9de72e0b-c9bc-4fd0-b665-33c63db9f844.jpg)

### What version of Home Assistant Core has the issue?

9.5

### What was the last working version of Home Assistant Core?

9.4

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Deconz

**Comment by sk1ppy81** [comment]
I Have the same thing. but I think it is related to z-waver version 1.72. I did a reinstall from home assistant to version 2022.9.0
All was working -> then I updated z-wave 1.72. Nothing was working update to the latest home assistant version 2022.9.6 but same problem. 
In logging **Failed to start the Z-Wave JS add-on: Image homeassistant/aarch64-addon-zwave_js:0.1.72 does not exist for addon_core_zwave_js**

I use the Z‐Stick Gen5 USB Controller

The integration is saying Retrying setup: None

**Comment by hcpalka** [comment]
In the meantime - with latest update - things are working better - but not perfect yet. With regards to Z-Wave things are back to "normal", but with regards to Zigbee things are far from normal, as my smart plugs are only partially usable (with ZHA) - seems deConz is better in that respect
