### ISSUE TITLE
Problem after Z-wave adapter hard reset

### ISSUE THREAD

**Issue by jstrade0** [home-assistant/addons#2677]
### Describe the issue you are experiencing

After a hard-reset of the Z-Wave adapter, the battery-powered devices stop automatically wakes up. It is a Danfoss Thermostat LC-13 device and a Danfoss Keemple smart radiator. I get messages in the log:

DRIVER Received a command that contains multiple CommandClasses. This is not supported yet! Discarding the message...
CNTRLR « [Node 002] TODO: no handler for application command

If the z-wave adapter is from the factory, everything works. If I use Hard-reset the problem start. I tried Hard reset both HA and from Z-Wave>me. With the same result. In Z-Wave>me, the battery device works, but in HA it stops. Tried on HW RAzberry 7 Pro, ZMEERAZ2, Aeotec Z-stick Gen5+, Aeotec Z-Pi 7. Only Aeotec Z-stick Gen5+ managed to help me reset the SW in Windows to a mode where it worked again in HA. With Razzbery 7 Pro, only restoring the configuration that I made from the new adapter using Z-WAVE>me (including network settings) helped. All other attempts resulted in the above-mentioned entry in the log, and after some time the device went into error E5.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Z-Wave JS

### What is the version of the add-on?

1.69-1.72

### Steps to reproduce the issue

1. Make Hard-reset of ZW adapter from Z-Wave JS to MQTT
2. Add ZW device ( Thermostat from Danfoss )
3. HA stops responding to automatic wake-up from the device. 
...

### Anything in the add-on logs that might be useful for us?

```txt
DRIVER Received a command that contains multiple CommandClasses. This is not supported yet! Discarding the message...
CNTRLR « [Node 002] TODO: no handler for application command
```

**Comment by MartinHjelmare** [comment]
How do you hard reset the Z-Wave adapter?

**Comment by jstrade0** [comment]
With Z-Wave JS to MQTT in HA 
and in Z-WAVE>ME ( expert/control .. Reset ) 
![QNRSmMuU0zsGyCfp](https://user-images.githubusercontent.com/112707521/191981336-68c58549-f73a-4436-8136-d320633c6df6.png)

**Comment by MartinHjelmare** [comment]
Please capture a driver debug log. The next step is probably to report this to the driver project at:
https://github.com/zwave-js/node-zwave-js/issues
