### ISSUE TITLE
MQTT Callback function not called

### ISSUE THREAD

**Issue by henkhoven** [home-assistant/addons#2685]
### Describe the issue you are experiencing

The rpogram uses MQTT to publish and subscribe to topics. When the MQTT broker that the client/program is connected to issues a publish to the subscribed topic  (using MQTT Explorer to publish a value to the subscribed topic global/prices/energy/frank) the call back is called and everything works as expected. When an external device, in this specific case a broker running on a different server, is pulbishing to the same topic (verified reception of the message using MQTT Explorer) the callback function is never called. 

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Debian

### Which add-on are you reporting an issue with?

Mosquitto broker

### What is the version of the add-on?

6.1.3

### Steps to reproduce the issue

Both the program and MQTT Explorer are connected to the same local MQTT broker. When publishing to global/prices/energy/frank on the local broker using MQTT Explorer the callback function is invoked.
When an external broker is publishing to the topic on the local broker the callback function is not invoked allthough I see the message arriving in MQTT Explorer connected to the local broker.

MQTT Callback function:

void mqttProtocol::mqttcallback(char* topic, byte* payload, unsigned int length) 
{
    Serial.println("Entered mqttcallback()");
    Serial.print("Passed topic contains: ");
    Serial.println(topic);
    if (strcmp(topic, "global/prices/energy/frank") == 0)
    {
      Serial.print("Message arrived [");
      Serial.print(topic);
      Serial.println("] ");
   }
}

MQTT Connect & Subscription:

int mqttProtocol::Connect(PubSubClient& mymqttClient, char* mqttconfig[])
{
  errornr = -1;
  unsigned long deltaTimer = 0;
  if(setupBroker == 0)
  { 
    begin_mqtt(mymqttClient, mqttconfig);
  }
  mymqttClient.disconnect();
  for (int i=0; i<3; i++) {
    CTOTimer = millis();
    mymqttClient.connect(mqttconfig[2], mqttconfig[3], mqttconfig[4]);
    while(millis() - CTOTimer < WTIMEOUT)
    {
      if (mymqttClient.connected() == true)
      {
        i = 3;
        CTOTimer = millis() + WTIMEOUT;        
        Serial.println("Connected to MQTT Broker");
      }
    }
    if (mymqttClient.connected() == false)
    {
      errornr = 1;
    } else {
      mymqttClient.setCallback(mqttcallback);
      mymqttClient.subscribe("global/prices/energy/frank");
    }
  }
  return errornr;
}

IIt seems to me that the actual subscription is working as when I publish locally everything works as expected. Also when I let the program connect to the remote MQTT broker everything works as expected. Only when the remote broker publishes the message to the local broker (and the program is connected to the local broker) the callback is never invoked.

### Anything in the Supervisor logs that might be useful for us?

```txt
All logs seems OK (MQTT & Supervisor), no errors displayed/listed
```

### Anything in the add-on logs that might be useful for us?

```txt
MQTT logs displays/lists no errors
```

**Comment by frenck** [comment]
What software is this about? This issue is reported against the add-on repository, but the issue report itself looks like a report for using a different program/library and not a problem for the broker itself?

**Comment by henkhoven** [comment]
I see what you mean, my appologies, it should be reported to the MQTT PubSubClient. I stand corrected!

Regards,
Henk Hoven

**Comment by frenck** [comment]
No problem, will close the issue on this end in that case 👍 

../Frenck
