### ISSUE TITLE
File editor web error

### ISSUE THREAD

**Issue by fabriziolanni** [home-assistant/addons#2686]
### Describe the issue you are experiencing

I have this issue when open web Page 
WARNING:2022-09-28 14:16:05,361:hass_configurator.configurator:Client IP banned.
INFO:2022-09-28 14:16:05,363:hass_configurator.configurator:172.30.32.1 - "GET / HTTP/1.1" 420 -

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### Which add-on are you reporting an issue with?

File editor

### What is the version of the add-on?

5.4.1 i think ultimate version

### Steps to reproduce the issue

1.
2.
3.
...

### Anything in the Supervisor logs that might be useful for us?

```txt
WARNING:2022-09-28 14:16:05,361:hass_configurator.configurator:Client IP banned.
INFO:2022-09-28 14:16:05,363:hass_configurator.configurator:172.30.32.1 - "GET / HTTP/1.1" 420 -
```

**Comment by ludeeus** [comment]
Report that to the author of hass_configurator, the add-on only wrap software, it does not control how it functions

**Comment by kolomiichenko** [comment]
i have a similar problem
