### ISSUE TITLE
Mosquitto broker Error

### ISSUE THREAD

**Issue by compoundbow83** [home-assistant/addons#2688]
### Describe the issue you are experiencing

Since the last update of the addon I get errors in the log and the addon no longer works. And as a result, the "Ring-MQTT with Video Streaming" addon no longer works either.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Mosquitto broker

### What is the version of the add-on?

6.1.3.

### Steps to reproduce the issue

1. The error passes after every restart and then persists

### Anything in the Supervisor logs that might be useful for us?

```txt
Logger: homeassistant.components.mqtt.client
Source: components/mqtt/client.py:566
Integration: MQTT (documentation, issues)
First occurred: 27. September 2022 um 20:25:09 (2220 occurrences)
Last logged: 22:12:33

Unable to connect to the MQTT broker: Connection Refused: not authorised.



Logger: homeassistant.components.mqtt.client
Source: components/mqtt/client.py:685
Integration: MQTT (documentation, issues)
First occurred: 27. September 2022 um 20:25:10 (2220 occurrences)
Last logged: 22:12:33

Disconnected from MQTT server core-mosquitto:1883 (5)
```

### Anything in the add-on logs that might be useful for us?

```txt
2022-09-30 20:58:16: New connection from 172.30.32.2:57372 on port 1883.
2022-09-30 20:58:16: Client <unknown> closed its connection.
```

**Comment by ludeeus** [comment]
"Ring-MQTT with Video Streaming" is not sending proper authentication, report the issue with the author of "Ring-MQTT with Video Streaming"
