### ISSUE TITLE
Wrong units after update to Deconz 6.16.0 (Develco ZHEMI101)

### ISSUE THREAD

**Issue by RasmusRR** [home-assistant/addons#2689]
### Describe the issue you are experiencing

After I updated to Deconz 6.16.0 the measurement units changed from kWh to mWh on my Freint Electricity Meter (Develco ZHEMI101)

Which makes it almost useless

Is there any way I know I can change it back to kWh. Unfortunately I don't have a backup

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

deCONZ

### What is the version of the add-on?

6.16.0

### Steps to reproduce the issue

1. update to deconz 6.16.0

**Comment by RasmusRR** [comment]
I managed to find a backup back from 6.14.2 which solved the problem for me. However, I still hope that the problem will be solved so that I can update in the future.

**Comment by ludeeus** [comment]
This needs to be fixed in deconz, please report the issue to them.
The addon only wrap the software
