### ISSUE TITLE
DuckDNS addon not renewing letsencrypt certificate

### ISSUE THREAD

**Issue by googanhiem** [home-assistant/addons#2690]
### Describe the issue you are experiencing

Yesterday my HA instance starting having external connection issues with DuckDNS and is having problems now renewing its certificate due to an DNS error. Not sure if the cert protocol has changed or if the service has done (no indications online is the issue).

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Duck DNS

### What is the version of the add-on?

1.15.0

### Steps to reproduce the issue

1. Certificates expire
2. restart duckdns
3. error occurs
...

### Anything in the add-on logs that might be useful for us?

```txt
ERROR: Challenge is invalid! (returned: invalid) (result: ["type"]	"dns-01"
["status"]	"invalid"
["error","type"]	"urn:ietf:params:acme:error:dns"
["error","detail"]	"DNS problem: SERVFAIL looking up TXT for _acme-challenge.XXXXXXX.duckdns.org - the domain's nameservers may be malfunctioning"
["error","status"]	400
["error"]	{"type":"urn:ietf:params:acme:error:dns","detail":"DNS problem: SERVFAIL looking up TXT for _acme-challenge.XXXXXX.duckdns.org - the domain's nameservers may be malfunctioning","status":400}
["url"]	"https://acme-v02.api.letsencrypt.org/acme/chall-v3/XXXXX/XXXXXX"
["token"]	"XXXXXXXX"
["validated"]	"2022-10-02T11:00:44Z")
```

### Additional information

I'm also not using aliases (as I'm aware of that issue).

It has worked for 2 years with no settings changes, and only yesterday started experiencing issues.

I've tried rebooting hosts, core, add-ons, deleting cert files (followed by a full reboot), changing DNS settings, taking nginx out of the equation and changing ports and forwarding rules - no change.

**Comment by ludeeus** [comment]
DuckDNS is having issues, run it again when that is resolved.
There is nothing that can be done by the add-on.

**Comment by googanhiem** [comment]
@ludeeus anywhere I can track the duckdns issue.. haven't seen a status page

**Comment by ludeeus** [comment]
You have to ask duckdns about that.

**Comment by googanhiem** [comment]
They've pointed me to this: https://intodns.com/duckdns.org
