### ISSUE TITLE
LetsEncrypt auto renew not working

### ISSUE THREAD

**Issue by appsheld** [home-assistant/addons#2693]
### Describe the issue you are experiencing

From description:

...designed to eliminate the hitherto complex process of manual creation, validation, signing, installation, and **renewal** of certificates for secure websites...

Renew is not working. Add-on stops after start.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Let's Encrypt

### What is the version of the add-on?

 4.12.7

### Steps to reproduce the issue

1. start Add-on 
2. show Log
3. See stop of Add-on
...

### Anything in the add-on logs that might be useful for us?

```txt
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/file-structure.sh
cont-init: info: /etc/cont-init.d/file-structure.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun lets-encrypt (no readiness notification)
s6-rc: info: service legacy-services successfully started
[10:11:12] INFO: Selected DNS Provider: dns-azure
[10:11:12] INFO: Use propagation seconds: 60
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Certificate not yet due for renewal
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Certificate not yet due for renewal; no action taken.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by mdegat01** [comment]
Right, renewing certificates. As in when run, if it checks if the existing certificate needs to be renewed and does so. What you're looking for is continuous monitoring of a certificate, this addon doesn't do that. You're welcome to make an automation to run it nightly though. Or submit a [feature request](https://community.home-assistant.io/c/feature-requests/13)

**Comment by felipecrs** [comment]
An automation to run the add-on nightly should be documented and even suggested in the configuration guide. Don't you think?

**Comment by paulvt** [comment]
I run it nightly, and even it is about to expire in 12 hours, when I run it manually, it still says:
```
Certificate not yet due for renewal
```
Does this mean it will only renew it only and if only if has expired already?
I would expect it to renew in the week leading up to the expiry date? 
Should I file an issue for this?

**Comment by michaelyork** [comment]
This seems like it deserves another look. It's not obvious to folks that the add-on itself doesn't auto-renew the certificate.
