### ISSUE TITLE
deconz crash (s6-svwait: fatal: supervisor died)

### ISSUE THREAD

**Issue by wifiuk** [home-assistant/addons#2696]
### Describe the issue you are experiencing

Unable to control all smart devices using DeConz plugin

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

deCONZ

### What is the version of the add-on?

deCONZ Current version: 6.16.0

### Steps to reproduce the issue

1. Try to Start Deconz Add-on
2. It will work for a second then die.

### Anything in the Supervisor logs that might be useful for us?

```txt
Logger: homeassistant.components.deconz
Source: components/deconz/gateway.py:349
Integration: deCONZ (documentation, issues)
First occurred: 07:28:24 (8 occurrences)
Last logged: 07:33:56

Error connecting to deCONZ gateway at 172.30.33.1
```

### Anything in the add-on logs that might be useful for us?

```txt
...........................
...........................
07:30:36:557 SC tick --> StateRead
07:30:36:557 SC tick --> StateRead
07:30:36:557 SC tick --> StateRead
07:30:36:558 SC tick --> StateRead
07:30:36:558 SC tick --> StateRead
07:30:36:559 SC state change failed: xx:xx:xx:xx:xx:xx:xx:31-02-0402
07:30:37:279 GW update firmware found: /usr/share/deCONZ/firmware/deCONZ_ConBeeII_0x26720700.bin.GCF
07:30:37:279 GW firmware version is up to date: 0x26720700
07:30:39:156 ZCL attribute report 0x0017880104B74981 for cluster: 0x0402, ep: 0x02, frame control: 0x08, mfcode: 0x0000 
[06:30:39] INFO: Service restart after closing
[07:30:40] INFO: Starting VNC server (local/yes)...
[06:30:40] WARNING: Halt add-on
s6-rc: info: service legacy-services: stopping
2022/10/06 07:30:40 [notice] 145#145: signal 15 (SIGTERM) received from 118, exiting
2022/10/06 07:30:40 [notice] 659#659: exiting
2022/10/06 07:30:40 [notice] 659#659: exit
In exit
Closing socket listening at 127.0.0.1:5901
2022/10/06 07:30:40 [notice] 145#145: signal 17 (SIGCHLD) received from 659
2022/10/06 07:30:40 [notice] 145#145: worker process 659 exited with code 0
2022/10/06 07:30:40 [notice] 145#145: exit
s6-svwait: fatal: supervisor died
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### Additional information

Home Assistant 2022.10.0
Supervisor 2022.09.1
Operating System 9.0
Frontend 20221005.0 - latest

**Comment by Bogstag** [comment]
I have the same issue and it started after upgrading to Home Assistant 2022.10.0.

Everything is the same as above but with the following differences:
Home Assistant 2022.10.1
Frontend-version: 20221006.0 - latest

From Home Assistant Core logs:
Logger: homeassistant.components.deconz
Source: components/deconz/gateway.py:349
Integration: deCONZ (documentation, issues)
First occurred: 08:48:24 (1 occurrences)
Last logged: 08:48:24

Error connecting to deCONZ gateway at core-deconz

**Comment by wifiuk** [comment]
i had to rollback to a month-old proxmox backup to get it all working again, not upgrading anything until I know its working again, totally killed the entire house as its all onboarded into deconz.
