### ISSUE TITLE
Home Assistant Terminal & SSH web terminal unreadable in Firefox.

### ISSUE THREAD

**Issue by bjwest** [home-assistant/addons#2699]
### Describe the issue you are experiencing

The web terminal font in the Terminal & SSH add-on is unreadable in Firefox, but looks fine in Chrome.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Terminal & SSH

### What is the version of the add-on?

9.6.1

### Steps to reproduce the issue

1. Open the Terminal & SSH terminal in Firefox
2. Notice the font is unreadable.
...

### System Health information

No copy button on bottom of pop-up, only "There are currently no repairs available" in box on top.

### Additional information

This is a fresh install of Homeassistant, and my first time using it.

First screenshot is from Firefox, second from Chrome.

![Terminal and SSH in Firefox](https://user-images.githubusercontent.com/1934590/194984629-d98f7aad-e8e9-4217-ba93-15a5b6d075d2.png)
![Terminal and SSH in Chrome](https://user-images.githubusercontent.com/1934590/194984648-99c10e68-58b6-41b3-b85b-0128b46fbff5.jpg)

**Comment by andrew-deering-informa** [comment]
I'm experiencing the same behavior. Completely unreadable in the current version of Firefox (v105.0.3)

**Comment by jamesarm97** [comment]
I have an issue with the screen going light grey like it should, but then I never get text, unless I resize my browser window, then the screen redraws correctly but doesn't update in real time. I always have to type something, then resize to force a redraw. Safari

**Comment by danys94** [comment]
I have the same problem. Started happening when I moved from FHD to QHD. Brave Browser.

**Comment by RussPitcher** [comment]
I've got the same problem in Brave 1.45.133.  Seems like it's down to the browser as I've just tried a couple of other browsers:

- Edge 107.0.1418.56 is OK
- Chrome 107.0.5304.121 is OK
- Firefox 83.0 is OK

**Comment by grehund** [comment]
I have the same problem in both Firefox 110.0 and Brave [Version 1.48.171 Chromium: 110.0.5481.177 (Official Build) (64-bit)]

**Comment by UnmitigatedAudacity** [comment]
Stale? I've had this problem for years, it hasn't gone away. Mine is exactly as described by OP, across all versions of Firefox and all versions of HA since then.

**Comment by tkroo** [comment]
What (at least temporarily) fixes this problem for me is to [start Firefox in troubleshoot mode](https://support.mozilla.org/en-US/kb/diagnose-firefox-issues-using-troubleshoot-mode), then quit, and restart Firefox.

**Comment by knnelg** [comment]
> What (at least temporarily) fixes this problem for me is to [start Firefox in troubleshoot mode](https://support.mozilla.org/en-US/kb/diagnose-firefox-issues-using-troubleshoot-mode), then quit, and restart Firefox.

As of 06/05/2025, this is still an issue, and tkroo's fix still works as a work around. Many thanks tkroo.

**Comment by davet2001** [comment]
Yes, there's clearly something wrong here. For me it's like the text is grey on grey and unreadable until I attempt to highlight it.
Firefox 145.0.2 (64-bit) 

Picture in case needed:

When I just click in the window:
<img width="846" height="349" alt="Image" src="https://github.com/user-attachments/assets/9ee79aad-1909-4228-aebb-a76693a63797" />

When imagine there is some text there and try to select it:
<img width="846" height="349" alt="Image" src="https://github.com/user-attachments/assets/5ecbf3b0-e096-44c2-bb40-38f2f3431acd" />
