### ISSUE TITLE
Sensor - state change in phoscon but no event from deconz to HA

### ISSUE THREAD

**Issue by groovy-ka** [home-assistant/addons#2700]
### Describe the issue you are experiencing

Hello,
I have created an issue on homeassistant/core,
And after some investigations, it seems to be a deconz issu.
There is my problem :
https://github.com/home-assistant/core/issues/79961

« I have a problem with my TS0203 door sensor.
Before, all was ok, but recently, i have noticed that phoscon doesn’t send state to HA.
All is ok in phoscon app, when i open, the state is on, when i close, the state is off immediately.
I also have lights that work good in HA.
It is like phoscon won’t communicate whit HA.
Sometimes, when i refresh deconz and open a door, that work on time, and stop after. »

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### Which add-on are you reporting an issue with?

deCONZ

### What is the version of the add-on?

6.16.0

### Steps to reproduce the issue

Refresh deconz
Open door > event is send to HA
After that, no more event is sended

### System Health information

No correction

**Comment by PublicCodeRobin** [comment]
Not sure if your issue is the same as mine but I also notice that events come trough very slowly. If wattage spikes on my SmartPlugs it should turn on the amps that are connected to the TV. It does this after like 10 minutes or something. It was way more quickly before.
