### ISSUE TITLE
core_letsencrypt is not using the exposed port config key when http challenge is selected

### ISSUE THREAD

**Issue by alefab** [home-assistant/addons#2702]
### Describe the issue you are experiencing

Even if the config key to change the external port is setup, the url used to validate the installation is not using it:
`  Detail: 1.2.3.4: Fetching http://foo.my.domain/.well-known/acme-challenge/xxxxx: Timeout during connect (likely firewall problem)`

full log:
```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/file-structure.sh
cont-init: info: /etc/cont-init.d/file-structure.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun lets-encrypt (no readiness notification)
s6-rc: info: service legacy-services successfully started
[22:27:12] INFO: Selected http verification
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Requesting a certificate for minus.myds.me
Certbot failed to authenticate some domains (authenticator: standalone). The Certificate Authority reported these problems:
  Domain: minus.myds.me
  Type:   connection
  Detail: 1.2.3.4: Fetching http://foo.my.domain/.well-known/acme-challenge/xxxxx: Timeout during connect (likely firewall problem)
Hint: The Certificate Authority failed to download the challenge files from the temporary standalone webserver started by Certbot on port 80. Ensure that the listed domains point to this machine and that it can accept inbound connections from the internet.
Some challenges have failed.
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
```

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Let's Encrypt

### What is the version of the add-on?

4.12.7

### Steps to reproduce the issue

1. Change the default exposed port for http challenge
2. Start the service
3. The url used to challenge the connection is not using the defined port

### System Health information

Aucune correction n'est actuellement disponible

### Anything in the Supervisor logs that might be useful for us?

```txt
none
```

**Comment by baf** [comment]
Same problem. I have port 8000 configured, but the logs report:
> Hint: The Certificate Authority failed to download the challenge files from the temporary standalone webserver started by Certbot on port 80.

**Comment by drewancil** [comment]
I did this today.  The port you configure changes what port the add-in listens on, not what port the certbot uses.  No idea if this is by design or not, but I simply worked around it by forwarding port 80 on my router to port 8000.  It worked.
