### ISSUE TITLE
Can't configure

### ISSUE THREAD

**Issue by Muppetkeeper** [home-assistant/addons#2703]
### Describe the issue you are experiencing

I enter my duckdns address, change false to true, click save, then I get

"This add-on does not expose configuration for you to mess with…"

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### Which add-on are you reporting an issue with?

NGINX Home Assistant SSL proxy

### What is the version of the add-on?

3.1.5

### Steps to reproduce the issue

1.
2.
3.
...
as above

### System Health information

Host Operating System | Home Assistant OS 8.4
-- | --
Update Channel | stable
Supervisor Version | supervisor-2022.10.0
Agent Version | 1.2.1
Docker Version | 20.10.14
Disk Total | 58.7 GB
Disk Used | 8.1 GB
Healthy | true
Supported | true
Board | rpi4-64
Supervisor API | ok
Version API | ok
Installed Add-ons | Samba share (10.0.0), File editor (5.4.1), Duck DNS (1.15.0), NGINX Home Assistant SSL proxy (3.1.5)

**Comment by brtski** [comment]
I have the same problem with the same version of the add-on running on HAOS:
Home Assistant 2022.10.3 Supervisor 2022.10.0 Operating System 9.2 Frontend-versie: 20221010.0

**Comment by Muppetkeeper** [comment]
> 

Pleased its not just me!

**Comment by honnielsen** [comment]
same here

**Comment by erahhal** [comment]
This is definitely broken for the latest version of HA+samba add-on.

**Comment by claudiobgit** [comment]
I confirm same problem here (Linux + Firefox user) and solution @erahhal above just works!
