### ISSUE TITLE
Unable to disable HSTS

### ISSUE THREAD

**Issue by Longoon12000** [home-assistant/addons#2705]
### Describe the issue you are experiencing

HSTS causes other HA add-ons, which do not use HTTPS and don't have a lovelace integration (uptime kuma for example), to be unreachable because it forces the browser to switch to HTTPS even tho other add-ons do not support it. [According to the documentation](https://github.com/home-assistant/addons/blob/master/nginx_proxy/DOCS.md#option-hsts-required), if hsts is empty in the configuration, the header should not be send. However the Strict-Transport-Security header is still sent, even when hsts is empty ("") or null.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

NGINX Home Assistant SSL proxy

### What is the version of the add-on?

3.1.5

### Steps to reproduce the issue

1. Setup NGINX Home Assistant SSL proxy
2. Add following line to nginx add-on configuration:
`hsts:`
or
`hsts: ""`
3. Restart nginx add-on, `hsts:` will automatically be changed to `hsts: null`
4. Reload HA over SSL and check response headers, the headers will contain:
`strict-transport-security: max-age=31536000; includeSubDomains`
even tho it has been disabled in the configuration.

## System Information

version | core-2022.10.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.5
os_name | Linux
os_version | 5.15.72
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | failed to load: timeout
GitHub Web | ok
GitHub API Calls Remaining | 4999
Installed Version | 1.28.0
Stage | running
Available Repositories | 1188
Downloaded Repositories | 4

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.2
-- | --
update_channel | stable
supervisor_version | supervisor-2022.10.0
agent_version | 1.4.1
docker_version | 20.10.17
disk_total | 30.8 GB
disk_used | 7.4 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | ESPHome (2022.9.4), SSH & Web Terminal (12.0.2), motionEye (0.18.0), Studio Code Server (5.4.0), RPC Shutdown (2.2), Grocy (0.18.2), Node-RED (13.4.0), Uptime Kuma (0.3.0), NGINX Home Assistant SSL proxy (3.1.5), Mosquitto broker (6.1.3)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 1
views | 4
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | October 7, 2022 at 12:55
-- | --
current_recorder_run | October 14, 2022 at 10:11
estimated_db_size | 19.99 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Additional information

The documentation also says, hsts is required, however according to #264 it should be marked as optional.

**Comment by Longoon12000** [comment]
No? This is still an issue, all information is provided. Please!

**Comment by TheHolyRoger** [comment]
Same issue here

**Comment by Longoon12000** [comment]
Very cool, thanks.

**Comment by jnawk** [comment]
what a hostile config - any issue we ignore, automatically close that.
