### ISSUE TITLE
SAMBA Share - iOS 16 Unable to Write into SMB Drive

### ISSUE THREAD

**Issue by jhemmond** [home-assistant/addons#2711]
### Describe the issue you are experiencing

When trying to transfer media from iOS to HA through Samba Share Add-On, iOS is throwing an error as shown here https://imgur.com/a/BQOIsSU

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Samba share

### What is the version of the add-on?

10.0.0

### Steps to reproduce the issue

1. Enable Samba Share Addon
2. Configure the Files app on iOS 16 to connect to Server and authenticate into Samba Share
3. Copy any media from Photos app on iPhone and save to the Samba Share drive

Error here pops up - https://imgur.com/a/BQOIsSU

### System Health information

"There are currently no repairs available"

### Anything in the Supervisor logs that might be useful for us?

```txt
no
```

### Anything in the add-on logs that might be useful for us?

```txt
root opened file USB/IMG_7469.JPG read=No write=No (numopen=4)
root closed file USB/IMG_7469.JPG (numopen=2) NT_STATUS_OK
root opened file USB/IMG_7469.JPG read=No write=Yes (numopen=4)
root closed file USB/IMG_7469.JPG (numopen=2) NT_STATUS_OK
root opened file USB/IMG_7469.JPG read=No write=Yes (numopen=4)
root closed file USB/IMG_7469.JPG (numopen=2) NT_STATUS_OK
root opened file USB/IMG_7469.JPG read=Yes write=No (numopen=5)
root opened file USB/IMG_7469.JPG read=No write=No (numopen=5)
root closed file USB/IMG_7469.JPG (numopen=3) NT_STATUS_OK
root opened file USB/IMG_7469.JPG read=No write=No (numopen=5)
root closed file USB/.nfs.20051030.0c1c (numopen=3) NT_STATUS_OK
root closed file USB/.nfs.20051030.0c1c (numopen=2) NT_STATUS_OK
root opened file USB/.nfs.20051030.0c1c read=No write=No (numopen=4)
root closed file USB/.nfs.20051030.0c1c (numopen=2) NT_STATUS_OK
root opened file USB/IMG_7469.JPG read=No write=No (numopen=4)
root closed file USB/IMG_7469.JPG (numopen=2) NT_STATUS_OK
root opened file USB/IMG_7469.JPG read=No write=Yes (numopen=4)
root closed file USB/IMG_7469.JPG (numopen=2) NT_STATUS_OK
root opened file USB/IMG_7469.JPG read=No write=Yes (numopen=4)
root closed file USB/IMG_7469.JPG (numopen=2) NT_STATUS_OK
root opened file USB/IMG_7469.JPG read=Yes write=No (numopen=5)
root opened file USB/IMG_7469.JPG read=No write=No (numopen=5)
root closed file USB/IMG_7469.JPG (numopen=3) NT_STATUS_OK
root opened file USB/IMG_7469.JPG read=No write=No (numopen=5)
```

### Additional information

none

**Comment by miktin** [comment]
I have same problem.

**Comment by AStoker** [comment]
Same problem. Finally found this issue. Any resolution?

**Comment by AStoker** [comment]
Opened follow-up issue that will hopefully get some traction #2857

**Comment by jhemmond** [comment]
For anyone interested. I upgraded iOS version to 16.3 and that resolved the issue.

**Comment by AStoker** [comment]
@jhemmond , I'm running 16.3 now and still have the issue :(
