### ISSUE TITLE
Update to use new command syntax with gandi DNS

### ISSUE THREAD

**Issue by 3v1n0** [home-assistant/addons#2715]
### Describe the issue you are experiencing

```
Plugin legacy name certbot-plugin-gandi:dns may be removed in a future version. Please use dns instead.
Certbot is moving to remove 3rd party plugins prefixes. Please use --authenticator dns-gandi --dns-gandi-credentials
```

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### Which add-on are you reporting an issue with?

Let's Encrypt

### What is the version of the add-on?

4.12.7

### Steps to reproduce the issue

1. Run it when configured to use gandi dns challenge

## System Information

version | core-2022.10.5
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.5
os_name | Linux
os_version | 5.4.0-1073-raspi
arch | aarch64
timezone | Europe/Madrid
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4935
Installed Version | 1.27.1
Stage | running
Available Repositories | 1123
Downloaded Repositories | 19

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 49

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Ubuntu 20.04.5 LTS
-- | --
update_channel | stable
supervisor_version | supervisor-2022.10.0
agent_version | null
docker_version | 20.10.17
disk_total | 58.2 GB
disk_used | 19.7 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.4.1), Let's Encrypt (4.12.7), Log Viewer (0.14.0), Studio Code Server (5.4.0), motionEye (0.18.0), Mosquitto broker (6.1.3), Zigbee2mqtt (1.22.0-2), AppDaemon (0.9.3), BorgBackup (0.60.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 10
views | 9
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 20 ottobre 2022 11:50
-- | --
current_recorder_run | 22 ottobre 2022 03:57
estimated_db_size | 527.30 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

### Anything in the add-on logs that might be useful for us?

```txt
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/file-structure.sh
cont-init: info: /etc/cont-init.d/file-structure.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun lets-encrypt (no readiness notification)
s6-rc: info: service legacy-services successfully started
[04:07:38] INFO: Selected DNS Provider: dns-gandi
[04:07:38] INFO: Use propagation seconds: 60
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugin legacy name certbot-plugin-gandi:dns may be removed in a future version. Please use dns instead.
Certbot is moving to remove 3rd party plugins prefixes. Please use --authenticator dns-gandi --dns-gandi-credentials
Certificate not yet due for renewal
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Certificate not yet due for renewal; no action taken.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```
```


### Additional information

_No response_

**Comment by d3v3l15h** [comment]
Hi,

Would it be possible to reopen this one and have Let's Encrypt addon use 3rd party plugin (gandi here) without prefix ?

See https://github.com/certbot/certbot/pull/8131

Thank you.

**Comment by Jim-Noble** [comment]
Same issue for me using the plugin for gandi. Presumably this issue will affect all 3rd party plugins though.
