### ISSUE TITLE
High CPU with Deconz AddOn

### ISSUE THREAD

**Issue by repiuk** [home-assistant/addons#2716]
### Describe the issue you are experiencing

If deconz is running the cpu usage slowly increases. After 2 or 3 days the whole system becomes slows down. Only remedy is restarting or rebooting home assistant. Only remedy I can think of is a daily reboot...

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

deCONZ

### What is the version of the add-on?

6.16.0

### Steps to reproduce the issue

1.
2.
3.
...

### System Health information

no repairs

**Comment by ottelo9** [comment]
We've had that before. I'm also currently having problems with Deconz and have just restarted. I'll check the CPU usage.

**Comment by popy2k14** [comment]
Exact same issue here! 
I have to restart the addon to get a snappy ZigBee network. After restart the CPU load of the addon is just 0,8%. After a few days it's at 16% or higher. In this state, the ZigBee network is mostly unusable.

Any hints what could be the issue?

Thx

**Comment by repiuk** [comment]
At least I'm not alone with this. It's causing troubles for the last month or so. I now restart 4 or 5 times every day, sometimes the CPU load remains stable after a restart. This only last a few days because some updated modules requires a restart and the problem surfaces again.

**Comment by popy2k14** [comment]
Yeah, we are in the same boat.
In the thread: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6445
I discussed this with the deconz main dev and he stated we should please try 2.19.1 which was just released yesterday.

There was a very similar issue with conbee I and raspbee I which LEDs to looping in deconz and is now fixed. He states that this also affects conbee II in some cases but have not such an impact as it has on the first gen devices.

Which conbee/raspbee version do you have?

Please try the new version and let us know the results.

Thx

**Comment by repiuk** [comment]
Conbee II, The addon is on 2.18.02. I could try installing deconz 2.19.1 on a ubuntu server with docker.
Never tried updating a docker manually on HAOS. Is that what you suggest to try?

**Comment by popy2k14** [comment]
Ok, so our HW and HA addon version is the same.
No, we just should wait until the addon gets updated.
Shouldn't take too long. Mostly a couple of days.

**Comment by repiuk** [comment]
Installed the addon update and deconz is now at 2.19.1. After a reboot the CPU load of the deconz container cooled down from 5-6% to 0.5%. Overall CPU load still grows in time. Another reboot resulted in the old high CPU load of deconz and overall CPU load always grows in time. 
With the previous deconz version I tried several reboots of the whole system, restarts of home assistant, restarts of the addon etc. Sometimes (if I'm lucky) the system runs stable (no growing CPU load). Tried to find the problem with Glances and the Profiler service without success. I only see deconz running at a high CPU load (5-6%) and can't find which specific python module goes through the roof.
Also tried migrating the deconz docker to another machine which is another challenge because the zigbee network doesn't restore as a working network mesh (from a backup file exported from the deconz addon in homeassistant).  

My main suspect are Nous A1Z plugs they flood the deconz log with
07:35:03:415 ZCL attribute report 0xA4C138B79BDE4D87 for cluster: 0x0B04, ep: 0x01, frame control: 0x18, mfcode: 0x0000
Probably the power consumption readings, they are updated every second or maybe faster.

**Comment by popy2k14** [comment]
I have updated deconz also and see how it goes.
Also like on your side, at start it's about 4-5% load and it settles @ ~0,5%.

Can you unplug those plugs to see if it settles?

In the thread over here: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6445
some users are reporting good news.
But i dont know if the high cpu usage issue is the same as ours.

**Comment by repiuk** [comment]
Great idea. Unplugged all of them (9) and kept one which isn't updating (0 W). CPU load has dropped to low levels.
Now I need to find which settings to change in the DDF editor...

**Comment by popy2k14** [comment]
Nice to hear you found your issue.
There is a great phoscon forum where you can ask such questions.

**Comment by repiuk** [comment]
Solved:
Open the phoscon app, select one of the Nous plugs
and right click > Edit DDF
![Screenshot 2022-10-29 082144](https://user-images.githubusercontent.com/12936788/198817217-934751da-4a52-45b7-b7aa-26f49b9db8fe.png)
Min interval was at 1, changed that to 10, Reportable change also has to increase. I changed voltage to 5 and Power to 10.
Save the new DDF in /data/.local/share/Dresden-elektronic/deCONZ/devices and reboot the whole system

**Comment by popy2k14** [comment]
As this is an deconz issue. Can you please open an GitHub issue on deconz repo?
So everyone can benefit from your DDF optimizations?

**Comment by repiuk** [comment]
Yes
https://forum.phoscon.de/t/nous-a1z-ddf-causes-high-cpu/2675

**Comment by popy2k14** [comment]
thx

**Comment by popy2k14** [comment]
Just a small update, if anyone with similar issues finds this thread.

With the upcomming fixes in deconz (better APS queue handling, new javascript engine, ...) our issues should be finally resolved.

See: https://github.com/dresden-elektronik/deconz-rest-plugin/commits/master
Commits on 10.11.2022.
Will be included in next release.

**Comment by jdeluyck** [comment]
I'm seeing the same entries with Innr power plugs - I hope they'll also be fixed with this commit?
