### ISSUE TITLE
deCONZ - Unexpected light color mode 2

### ISSUE THREAD

**Issue by GitHubxtsnl** [home-assistant/addons#2720]
### Describe the issue you are experiencing

Logger: pydeconz.models.light.light
Source: components/deconz/light.py:167
First occurred: October 23, 2022 at 5:44:03 PM (1356 occurrences)
Last logged: 7:39:38 AM

Unexpected light color mode 2

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

deCONZ

### What is the version of the add-on?

6.16.0

### Steps to reproduce the issue

no steps known, error message appears in the log very often without any known reason.

### System Health information

There are currently no repairs available

### Anything in the Supervisor logs that might be useful for us?

```txt
Only this message, but I think it is not related:
22-10-24 07:29:50 WARNING (MainThread) [supervisor.addons.options] Option 'vnc_password' does not exist in the schema for deCONZ (core_deconz)
```

### Additional information

Home Assistant 2022.10.5
deCONZ 6.16.0
ConBee II 2.18.02 / 9/19/2022 / 26720700

**Comment by stijink** [comment]
Same for me.

**Comment by nadinecross** [comment]
Me too

**Comment by Mariuss811** [comment]
Same issue

**Comment by kingpainter** [comment]
Me 2

**Comment by jreidel** [comment]
Same issue

**Comment by GitHubxtsnl** [comment]
I recently updated to Home Assistant 2022.12.1 & deCONZ 6.17.1 and this message does not appear in the log anymore.
