### ISSUE TITLE
Let's Encrypt complains about "legacy name certbot-dns-transip:dns-transip"

### ISSUE THREAD

**Issue by rigrig** [home-assistant/addons#2724]
### Describe the issue you are experiencing

Using the Let's Encrypt plugin, this shows up in the log:
`Plugin legacy name certbot-dns-transip:dns-transip may be removed in a future version. Please use dns-transip instead.`

The DNS configuration field already contains this though:
```yaml
provider: dns-transip
```

Renewing the certificate does work fine.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Let's Encrypt

### What is the version of the add-on?

4.12.7

### Steps to reproduce the issue

1. Configure the plugin for TransIP DNS challenge
2. Start the plugin (renewing the certificate works fine)
3. Look at the log file

Actual behavior:
Log contains the warning `Plugin legacy name certbot-dns-transip:dns-transip may be removed in a future version. Please use dns-transip instead.`

Expected behavior:
No warning

## System Information

version | core-2022.10.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.5
os_name | Linux
os_version | 5.15.72
arch | aarch64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4898
Installed Version | 1.28.3
Stage | running
Available Repositories | 1132
Downloaded Repositories | 16

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.2
-- | --
update_channel | stable
supervisor_version | supervisor-2022.10.0
agent_version | 1.4.1
docker_version | 20.10.17
disk_total | 13.6 GB
disk_used | 8.5 GB
healthy | true
supported | true
board | odroid-n2
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.6.1), Network UPS Tools (0.11.0), motionEye (0.18.0), Studio Code Server (5.4.0), Let's Encrypt (4.12.7), ESPHome (2022.10.0), MariaDB (2.5.1), Syncthing (1.15.1), Nextcloud Backup (0.17.6)

</details>

<details><summary>Dashboards</summary>

dashboards | 8
-- | --
resources | 9
views | 13
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | October 15, 2022 at 11:42
-- | --
current_recorder_run | October 25, 2022 at 05:10
estimated_db_size | 272.20 MiB
database_engine | mysql
database_version | 10.6.8

</details>

### Anything in the add-on logs that might be useful for us?

```txt
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/file-structure.sh
writing RSA key
cont-init: info: /etc/cont-init.d/file-structure.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun lets-encrypt (no readiness notification)
s6-rc: info: service legacy-services successfully started
[21:56:52] INFO: Selected DNS Provider: dns-transip
[21:56:53] INFO: Use propagation seconds: 60
[21:56:53] INFO: Increasing DNS propagation limit for TransIP to at least 240 seconds.
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugin legacy name certbot-dns-transip:dns-transip may be removed in a future version. Please use dns-transip instead.
Renewing an existing certificate for ****.*****.***
Waiting 240 seconds for DNS changes to propagate
Successfully received certificate.
Certificate is saved at: /data/letsencrypt/live/****.*****.***-0001/fullchain.pem
Key is saved at:         /data/letsencrypt/live/****.*****.***-0001/privkey.pem
This certificate expires on 2023-01-23.
These files will be updated when the certificate renews.
NEXT STEPS:
- The certificate will need to be renewed before it expires. Certbot can automatically renew the certificate in the background, but you may need to take steps to enable that functionality. See https://certbot.org/renewal-setup for instructions.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
If you like Certbot, please consider supporting our work by:
 * Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
 * Donating to EFF:                    https://eff.org/donate-le
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### Additional information

DNS configuration field:
```yaml
provider: dns-transip
transip_username: ******
transip_api_key: |
  -----BEGIN PRIVATE KEY-----
   ***
  -----END PRIVATE KEY-----
```

I guess this is a duplicate of #2418, but that was auto-closed by the bot.

**Comment by nl0pvm** [comment]
This issue is still relevant and actual
