### ISSUE TITLE
Add-On deCONZ: Philips Smart Button does not fire event since Version 6.17.0

### ISSUE THREAD

**Issue by marc965** [home-assistant/addons#2730]
### Describe the issue you are experiencing

With deCONZ-Addon 6.15.0 the "Philips Smart Button" fires events 1000 and 1002.
No event with v6.17.0.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

deCONZ

### What is the version of the add-on?

6.17.0 (2.19.1)

### Steps to reproduce the issue

1. Install 6.17.0
2. Smart Hue Button not working
3. Install 6.15.0 from backup
4. Smart Hue Button is working again
...

### System Health information

no repairs available

### Anything in the Supervisor logs that might be useful for us?

```txt
no errors with this add-on found
```

### Anything in the add-on logs that might be useful for us?

```txt
no errors
```

**Comment by jtotham** [comment]
I've got the same problem in 6.17, when I rolled back to 6.16 my Hue Smart buttons still don't fire, rolling back to 6.15 they work as expected and as they did previously.

**Comment by ge8020** [comment]
I have the same behavior here. 6.15 ist working, 6.16. & 6.17 are not. It's also not possible to pair a new Hue Smart Button on the later Versions.

**Comment by therealhalifax** [comment]
I can confirm that. Also unpairing and repairing of the buttons dosnt work.

**Comment by Friedi1970** [comment]
Same here. I also tried to unpair and repair. No success :(

**Comment by ekt-** [comment]
i'm having a similar issue ([reported here](https://github.com/home-assistant/addons/issues/2734)). in my case events are fired but the id changed. did you test in the 'developer tools' page to see if events are fired but with different ids?

**Comment by Friedi1970** [comment]
> i'm having a similar issue ([reported here](https://github.com/home-assistant/addons/issues/2734)). in my case events are fired but the id changed. did you test in the 'developer tools' page to see if events are fired but with different ids?

Well, I listened to deconz events and there are simply no events when using the hue smart button at all.

**Comment by therealhalifax** [comment]
I checked that and I see no events at all in the developer Tools when listen to deconz_Events

**Comment by geir55** [comment]
Still an issue with the latest update. Enyone on the case?

**Comment by Friedi1970** [comment]
Still the same problem. Even with the latest version.

**Comment by therealhalifax** [comment]
Still no update available 😒

**Comment by marc965** [comment]
6.17.1 ist not working too...🤬

**Comment by ge8020** [comment]
Should have been fixed in [deconz 2.20.1](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6461#issuecomment-1396586178) which isn´t out yet for HA as it seems. Lets wait for it...

**Comment by simonjgreen** [comment]
@beginnersguide I see you bumped the previous version. Would you mind bumping to latest again? There's a whole device from Hue waiting on it :)

**Comment by beginnersguide** [comment]
There is already a PR for the latest version.

https://github.com/home-assistant/addons/pull/2842

Am 22. Januar 2023 23:52:02 schrieb Simon Green ***@***.***>:

**Comment by mrman79** [comment]
Updated HA to deconz 2.20.1 and now I got Smart buttons working again.
