### ISSUE TITLE
Lumi.plug.mmeu01: no more power consumption after updating to 6.17.0

### ISSUE THREAD

**Issue by marc965** [home-assistant/addons#2731]
### Describe the issue you are experiencing

Installed v6.17.0:  All Lumi.plug.mmeu01 shows power and consuption not available.
![image](https://user-images.githubusercontent.com/85791333/198891258-08a63b30-50b4-4bf0-82c9-3eef83f0e996.png)

But information is still provided from deCONZ: see log:
```
15:11:20:165 ZCL attribute report 0x04CF8CDF3C8A37D6 for cluster: 0xFCC0, ep: 0x01, frame control: 0x1C, mfcode: 0x115F 
15:11:21:601 0x04CF8CDF3C8A340E extract Xiaomi special attribute 0x00F7
15:11:21:601 	64 on/off 1
15:11:21:601 	03 Device temperature 25 °C
15:11:21:602 	98 power 125.519997 (126)
15:11:21:602 	95 consumption 97.154686 (97155)
15:11:21:602 	96 voltage 2330.000000 (233)
15:11:21:602 	97 current 538.712463 (539)
15:11:21:603 	05 RSSI dB (?) 4 (0x0004)
15:11:21:603 	9a unknown 0 (0x00)
15:11:21:603 	08 unknown 278 (0x0116)
15:11:21:603 	07 unknown 0 (0x0000000000000000)
15:11:21:604 	09 unknown 3329 (0x0D01)
15:11:21:604 	0b unknown 0 (0x00)
15:11:21:604 	9b Consumer connected (yes/no) 1
```

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

deCONZ

### What is the version of the add-on?

6.17.0

### Steps to reproduce the issue

1. install 6.17.0
2. Power and Consumption not longer available
3. Reinstall 6.15.0 from backup
4. Power and Consumtion are back again
...

### System Health information

no repairs available

### Anything in the Supervisor logs that might be useful for us?

```txt
no add-on specific error log found
Home Assistant is working normally...
```

### Anything in the add-on logs that might be useful for us?

```txt
no add-on specific error log found
Home Assistant is working normally...
```

### Additional information

With deConz Version 6.15.0 all is working good...
i have only issue #2649 with 6.15.0.
with Version 6.17.0 i have one additional issue: #2730.
this issue comes with 6.16.0.
Rolled back to 6.15.0 succesfully.

**Comment by realm360** [comment]
Same problem here. 2 Aqara smart plugs not showing watt (power) info anymore after 6.15.0
