### ISSUE TITLE
Deconz VNC interface not suitable for DDF editor

### ISSUE THREAD

**Issue by Zehir** [home-assistant/addons#2733]
### Describe the issue you are experiencing

To use the DDF Editor to make binding I need to do a drag and drop between the two windows as described in the [documentation](https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet#bindings-panel). The issue is that both windows are displayed in tabs and I can open them side by side to do the drang and drop. I need to drag from the deConz combee II windows and drop it in the DDF Editor windows.
![image](https://user-images.githubusercontent.com/845225/198904655-2de9cc78-9f8d-4657-973c-e26c5dfb9ec5.png)

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

deCONZ

### What is the version of the add-on?

6.17.0

### Steps to reproduce the issue

1. Open the VNC window of the deConz Addon.
2. Open the DDF Editor from the Menu Edit->Edit DDF.
3. Try to create a binding in the binding tab like described in the [documentation](https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet#bindings-panel).

## System Information

version | core-2022.10.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.5
os_name | Linux
os_version | 5.15.61-v8
arch | aarch64
timezone | Europe/Paris
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.28.0
Stage | running
Available Repositories | 1201
Downloaded Repositories | 17

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.3
-- | --
update_channel | stable
supervisor_version | supervisor-2022.10.0
agent_version | 1.4.1
docker_version | 20.10.18
disk_total | 116.8 GB
disk_used | 22.4 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (10.0.0), File editor (5.4.1), Let's Encrypt (4.12.7), Check Home Assistant configuration (3.11.0), RPC Shutdown (2.2), deCONZ (6.17.0), Log Viewer (0.14.0), Nginx Proxy Manager (0.12.2), MariaDB (2.5.1), Grafana (8.0.2), InfluxDB (4.5.0), ADB - Android Debug Bridge (0.8.0), Vaultwarden (Bitwarden) (0.17.3), SSH & Web Terminal (12.0.2), Studio Code Server (5.4.0), Node-RED (13.5.0), Home Assistant Google Drive Backup (0.108.4), Mosquitto broker (6.1.3), Portainer (2.15.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 11
views | 2
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 2 juin 2022 à 18:13
-- | --
current_recorder_run | 30 octobre 2022 à 20:20
estimated_db_size | 540.08 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Comment by Zehir** [comment]
Did anybody read the issue here ?

**Comment by Burn-In** [comment]
This is what is needed to at least test DDFs. Because of the limitations of add-ons I didn't find a way to create our copy or edit the DDFs in the correct folder.
So, please implement the floating editor window.

**Comment by Zehir** [comment]
> 

Until there is a good way to do it you can use this solution : 
https://community.home-assistant.io/t/deconz-support-management-of-ddf-files-through-ha-config/370331/20

**Comment by Zehir** [comment]
There is a work in progress discussion about an solution for that. If anybody find this message in the future, see here :
https://github.com/dresden-elektronik/deconz-rest-plugin-v2/issues/14

**Comment by Zehir** [comment]
Fixed in #3966
