### ISSUE TITLE
Can't enter domain name during configuration

### ISSUE THREAD

**Issue by roelof-47** [home-assistant/addons#2737]
### Describe the issue you are experiencing

After install the Duckdns addon, I can't configure the domain name as required.
The appropriate line in the configuration setup is missing. See attached screenshot.
![duckdns](https://user-images.githubusercontent.com/98609074/200173515-19cab11b-946a-40c9-89a7-1009c68d470e.PNG)

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### Which add-on are you reporting an issue with?

Duck DNS

### What is the version of the add-on?

1.15.0

### Steps to reproduce the issue

1. Install Duck dns
2. open configuration tab
3. No line in top of page for entering my domain name. See screenshot. 
...

### System Health information

Er zijn momenteel geen herstelwerkzaamheden beschikbaar

(Currently no repairs available)

**Comment by mclenaghan** [comment]
Not a solution to the code, but I got round this problem by selecting the option to edit in YAML. The parameters are the same as shown in the UI.

domains:
  -xxx.duckdns.org
token: xxxxxxxx
aliases: []
lets_encrypt:
  accept_terms: true
  algo: secp384r1
  certfile: fullchain.pem
  keyfile: privkey.pem
seconds: 300

**Comment by roelof-47** [comment]
Thank you for your response. I was able to complete the configuration this way. 
So, the solution is in a small corner. I overlooked this.

It remains a mystery that the domain line does not appear in the add-on.
Anyway, life is a lot easier with a little help.
Thanks again.

**Comment by m4k5ym** [comment]
Confirmed. UI is broken according to that configuration option.

**Comment by terjew** [comment]
I just installed the add-on and experienced the same bug.

**Comment by minddigger** [comment]
I also installed DuckDNS and also have the same bug !!

**Comment by Grimgorkos** [comment]
I just received the same bug after installing DuckDNS Add-on. I cant enter my domain name (I can type it, but cant press enter to confirm it)

**Comment by minddigger** [comment]
Grimgorkos, you have to enter the text in Yaml. (See replays of mclenaghan)

**Comment by Grimgorkos** [comment]
> Grimgorkos, you have to enter the text in Yaml. (See replays of mclenaghan)

Yeah, I managed to get it working via the Yaml editor too (thanks to reading some of the previous comments in this thread). Thanks for the comment anyway!

**Comment by Splinter911** [comment]
Same issue -Same solution - UI not working.

**Comment by mgsnuno** [comment]
same issue; same workaround (YAML edit)
