### ISSUE TITLE
SAMBA SHARE: This add-on does not expose configuration for you to mess with…

### ISSUE THREAD

**Issue by codeclinic** [home-assistant/addons#2738]
### Describe the issue you are experiencing

After installing SAMBA Share add-on, if I add a password or make any changes to the config, on saving the config screen disappears and cannot be re-entered without first uninstalling / re-installing the add-on. The issue is then repeated.

Thus I cannot get SAMBA share to start up.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Samba share

### What is the version of the add-on?

10.0.0

### Steps to reproduce the issue

After installing SAMBA Share add-on, if I add a password or make any changes to the config, on saving the config screen disappears and cannot be re-entered without first uninstalling / re-installing the add-on. The issue is then repeated.

## System Information

version | core-2022.11.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.15.61-v8
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.3
-- | --
update_channel | stable
supervisor_version | supervisor-2022.10.2
agent_version | 1.4.1
docker_version | 20.10.18
disk_total | 228.5 GB
disk_used | 2.2 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | 

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
mode | auto-gen

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 7 November 2022 at 13:05
-- | --
current_recorder_run | 7 November 2022 at 16:24
estimated_db_size | 0.28 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

### Anything in the Supervisor logs that might be useful for us?

```txt
none
```

### Anything in the add-on logs that might be useful for us?

```txt
none
```

### Additional information

no

**Comment by codeclinic** [comment]
I'm getting the same scenario with all addons. This is an out of the box installation of home assistant os on an rpi4.

**Comment by codeclinic** [comment]
If I edit the add-on config via YAML it works as expected, same for all other addons.

**Comment by Timj58** [comment]
I'm getting the same thing happening when i try to set up Samba Share with installation of home assistant on an rpi4. - original instalation would let me change password ECT but could not connect from my Windows PC to Samba Sharw so tried deleting and re installing - now i have this problem - This add-on does not expose configuration for you to mess with…

**Comment by ParcelRot** [comment]
I am having the same problem.

**Comment by lhartje** [comment]
I'm having the same issue. I have installed installed the SAMBA share plugin, but when I select the configuration tab the message ' This add-on does not expose configuration for you to mess with… ' is displayed. I can't configure a password via the UI and can not start the plugin.

**Comment by Wintherman** [comment]
Same  for me. Config not possible after first Configuration
When clicking Start it does not go to the red Start   Stop.
And no access from PC.

**Comment by Bachigaloupe** [comment]
Well I have mostly the same troubles as reported but not all. Exactly what was initially posted with edits to the configuration for allowed IPs and having to uninstall but I didn't have the issue as described by Wintherman as far as not getting the stop. I was hoping someone would tell me I am doing something wrong but now I think this is part of a bigger problem

**Comment by ezande** [comment]
I'm on version 2023.2.1 now and having exactly the same issue. First config seems ok but once started not visible anymore.

**Comment by Wintherman** [comment]
Hi
I found out there is something with the web-browser cache that cause this
problem.
Re-starting the web-browser solved the issue and the configuration came up.

//Håkan

Den sön 5 mars 2023 kl 16:05 skrev github-actions[bot] <
***@***.***>:
