### ISSUE TITLE
silabs-multiprotocol: Couldn't set EzspConfigId.CONFIG_MULTICAST_TABLE_SIZE=16 configuration value: EzspStatus.ERROR_OUT_OF_MEMORY

### ISSUE THREAD

**Issue by luvienm** [home-assistant/addons#2741]
Hello,

I'm seeing this error in the Home Assistant Core log but it doesn't seem to be impacting on the functionality of my 11 zigbee devices connected via ZHA socket.

This is on a Sonoff ZBDONGLE-E (EFR32MG21A020F768IM32) with the zigbee and openthread rcp uart firmware built with gecko sdk version 4.1.3. Not sure if this matters but openthread is enabled with a network formed on the same channel as zigbee with different PANids.

silabs-multiprotocol add-on version is 0.7.0:

```
Logger:** bellows.ezsp.protocol
Source: components/zha/core/gateway.py:172
First occurred: 4:44:11 PM (1 occurrences)
Last logged: 4:44:11 PM
Couldn't set EzspConfigId.CONFIG_MULTICAST_TABLE_SIZE=16 configuration value: EzspStatus.ERROR_OUT_OF_MEMORY
```

There is also an error in the Supervisor log:

```
22-11-09 16:43:57 ERROR (SyncWorker_8) [supervisor.utils.yaml] Can't read YAML file /data/addons/git/77f1785d/silabs-multiprotocol/translations/en.yaml - mapping values are not allowed in this context
  in "/data/addons/git/77f1785d/silabs-multiprotocol/translations/en.yaml", line 16, column 94
```

Please let me know if any further information is required to make things easier. Thanks.

**Comment by agners** [comment]
> Couldn't set EzspConfigId.CONFIG_MULTICAST_TABLE_SIZE=16 configuration value: EzspStatus.ERROR_OUT_OF_MEMORY

Yeah it seems that ZHA requests a configuration `zigbeed` is not configured for. We probably can adjust that at compile time, but I'll have to check.

> 22-11-09 16:43:57 ERROR (SyncWorker_8) [supervisor.utils.yaml] Can't read YAML file /data/addons/git/77f1785d/silabs-multiprotocol/translations/en.yaml - mapping values are not allowed in this context
>   in "/data/addons/git/77f1785d/silabs-multiprotocol/translations/en.yaml", line 16, column 94

This should be addressed with the move to this repository.

**Comment by HAuser2019** [comment]
Got similar error when ugraded tot HA 2023.8.1 and Silicon Labs Multiprotocol addon 2.3.1
(don't know which upgrade caused it). Nor I understand the error in the log.

After reboot says this:

Logger: bellows.ezsp.protocol
Source: components/zha/core/gateway.py:205
First occurred: 12:10:34 (1 occurrences)
Last logged: 12:10:34

Couldn't set EzspConfigId.CONFIG_PACKET_BUFFER_COUNT=255 configuration value: EzspStatus.ERROR_INVALID_ID

**Comment by tggman** [comment]
> Got similar error when ugraded tot HA 2023.8.1 and Silicon Labs Multiprotocol addon 2.3.1 (don't know which upgrade caused it). Nor I understand the error in the log.
> 
> After reboot says this:
> 
> Logger: bellows.ezsp.protocol Source: components/zha/core/gateway.py:205 First occurred: 12:10:34 (1 occurrences) Last logged: 12:10:34
> 
> Couldn't set EzspConfigId.CONFIG_PACKET_BUFFER_COUNT=255 configuration value: EzspStatus.ERROR_INVALID_ID

I've been running HAC 2023.8.1 since it's release yesterday and did not start seeing this error until AFTER I updated the Silicon Labs Multiprotocol to version 2.3.1 today
