### ISSUE TITLE
Deprecated add-on still making problems

### ISSUE THREAD

**Issue by JGNi** [home-assistant/addons#2751]
### Describe the issue you are experiencing

I've uninstalled the old 'Check Home Assistant configuration' add-on. 
But everytime I get a notification about updates, HA still links to the old not-installed add-on. 
How can I get it to stop with that?

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Check Home Assistant configuration

### What is the version of the add-on?

Not installed

### Steps to reproduce the issue

1. Update to a part of HA is announced in notification area
2. I click 'Open'
3. I get the info 'Check Home Assistant configuration. Addon is not installed'. Which is correct. 

## System Information

version | core-2022.11.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.15.61-v8
arch | aarch64
timezone | Europe/Copenhagen
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4650
Installed Version | 1.28.3
Stage | running
Available Repositories | 1147
Downloaded Repositories | 55

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | August 2, 2023 at 02:00
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | false
remote_server | eu-west-2-5.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.3
-- | --
update_channel | stable
supervisor_version | supervisor-2022.10.2
agent_version | 1.4.1
docker_version | 20.10.18
disk_total | 457.7 GB
disk_used | 9.9 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Glances (0.17.1), Home Assistant Google Drive Backup (0.109.2), Log Viewer (0.14.0), Node-RED (13.5.3), Samba share (10.0.0), SSH & Web Terminal (12.1.3), Portainer (2.0.0), deCONZ (6.17.0), Spotify Connect (0.12.2), Mosquitto broker (6.1.3), File editor (5.4.2), SQLite Web (3.6.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 32
views | 14
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | November 14, 2022 at 22:10
-- | --
current_recorder_run | November 20, 2022 at 11:50
estimated_db_size | 150.25 MiB
database_engine | mysql
database_version | 10.6.10

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Comment by ludeeus** [comment]
It sounds like you have an automation that creates a persistent notification for you.
