### ISSUE TITLE
Deconz Addon Fails to Start - 409 Client Error

### ISSUE THREAD

**Issue by Puntoboy** [home-assistant/addons#2772]
### Describe the issue you are experiencing

I work up this morning and my Zigbee devices weren't responding. Logged into HA and went to Deconz only to see a message that the addon wasn't started. So, I went to the addon page and attempted to start it. I received this error message. 

![image](https://user-images.githubusercontent.com/11718878/205009742-8ea05537-d2c0-4836-9f82-42d40e5ff012.png)

I've tried rebooting HA, but it's still the same. I haven't tried anything else as I don't really want to repair all of my Zigbee devices so looking for advice first. 

I've performed no updates or changes in the last few days, and it was working correctly until sometime in the last 8 hours.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

deCONZ

### What is the version of the add-on?

6.17.0

### Steps to reproduce the issue

1. Go to Deconz addon page
2. Attempt to start addon
3. Receive error message
...

## System Information

version | core-2022.9.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.5
os_name | Linux
os_version | 5.15.60
arch | x86_64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4837
Installed Version | 1.27.2
Stage | running
Available Repositories | 1168
Downloaded Repositories | 24

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 30 November 2022 at 00:00
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | false
remote_server | eu-west-2-3.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 8.5
-- | --
update_channel | stable
supervisor_version | supervisor-2022.11.2
agent_version | 1.2.1
docker_version | 20.10.14
disk_total | 30.8 GB
disk_used | 21.9 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | AppDaemon (0.9.3), Broadlink bridge (0.1.6), Check Home Assistant configuration (3.11.0), ESPHome (2022.10.2), File editor (5.4.2), Home Assistant Google Drive Backup (0.109.2), Let's Encrypt (4.12.7), Log Viewer (0.14.0), Mosquitto broker (6.1.3), Node-RED (13.5.1), Samba share (10.0.0), Terminal & SSH (9.6.1), deCONZ (6.17.0), Home Panel (2.5.0), Studio Code Server (5.4.0), ESPHome (dev) (dev), Traccar (0.17.0), MariaDB (2.5.1), Portainer (1.5.1), Zigbee2MQTT (1.28.2-1), SSH & Web Terminal (12.1.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 8
views | 11
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 28 November 2022 at 18:43
-- | --
current_recorder_run | 1 December 2022 at 08:34
estimated_db_size | 822.31 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

<details><summary>Sonoff</summary>

version | 3.3.1 (b20e33c)
-- | --
cloud_online | 2 / 2
local_online | 2 / 2

</details>

### Anything in the Supervisor logs that might be useful for us?

```txt
Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:123
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 08:35:48 (2 occurrences)
Last logged: 08:44:47

Failed to to call /addons/core_deconz/start - Can't create container from addon_core_deconz: 409 Client Error for http+docker://localhost/v1.41/containers/create?name=addon_core_deconz: Conflict ("Conflict. The container name "/addon_core_deconz" is already in use by container "969ea7be19024d11280051c8d2e9ab5728b0ac01f6680bf38479a2a30e1d2659". You have to remove (or rename) that container to be able to reuse that name.")
```

### Anything in the add-on logs that might be useful for us?

```txt
Logs are empty as the addon won't start
```

**Comment by Puntoboy** [comment]
If I go to SSH and list the docker containers, Deconz isn't listed. If I try to start it, I get this error.

![image](https://user-images.githubusercontent.com/11718878/205029148-939216c0-aebb-4a2f-8179-94a0f0d73307.png)

**Comment by frenck** [comment]
Seem to be file/system corruption, try running `ha supervisor repair` from an terminal or SSH prompt.

**Comment by Puntoboy** [comment]
Running that now, thanks.

**Comment by Puntoboy** [comment]
Bingo, thanks. Rebooted the system after running the repair. 

Any idea what would cause that? What led you to that conclusion?

**Comment by frenck** [comment]
> Any idea what would cause that? What led you to that conclusion?

I have no idea. We see this behavior on rare occasions, mostly around failing SD cards (which is not the case in your system, as it seems).

**Comment by Puntoboy** [comment]
Thanks. I would be surprised if it was a failing SD card as it's running from an SSD and there are no SD Cards in the system :)

**Comment by frenck** [comment]
> I would be surprised if it was a failing SD card as it's running from an SSD and there are no SD Cards in the system :)

yeah I figured, as it said x86_64 in your issue description 😄
