### ISSUE TITLE
Error in 2.19.1, lost all connection to Zigbee devices. Need update to 2.19.3

### ISSUE THREAD

**Issue by Brian-lub** [home-assistant/addons#2783]
### Describe the issue you are experiencing

I have no connection to any of my Zigbee devices, they all droppede at after a reboot. i have tried everything i can but nothing worked. then took the mater to Discord. I have been talking to "manup" and "Mimiix" on Deconz Discord
https://discord.com/channels/494922323518947329/543511893382529064/1049323615100874843 and thay found that there is a bug in 2.19.1 and that should be fixed in 2.19.3, 
![image](https://user-images.githubusercontent.com/47833231/205736717-72a9b504-2639-4c4e-a775-7c94324794ff.png)
  

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### Which add-on are you reporting an issue with?

deCONZ

### What is the version of the add-on?

6.17.0

### Steps to reproduce the issue

1.It not working at all time
2.
3.
...

## System Information

version | core-2022.11.5
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.4.0-135-generic
arch | x86_64
timezone | Europe/Copenhagen
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.28.4
Stage | running
Available Repositories | 1156
Downloaded Repositories | 15

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | December 12, 2022 at 01:00
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | eu-west-2-4.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Ubuntu 20.04.5 LTS
-- | --
update_channel | stable
supervisor_version | supervisor-2022.11.2
agent_version | null
docker_version | 20.10.21
disk_total | 109.5 GB
disk_used | 34.0 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.4.2), Samba share (10.0.0), Node-RED (13.5.3), UniFi Network Application (2.4.1), ESPHome (2022.3.1), Z-Wave JS UI (1.3.0), AdGuard Home (4.7.4), MariaDB (2.5.1), Portainer (2.16.2), Nextcloud Backup (0.17.7), deCONZ (6.17.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 5
views | 8
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | November 29, 2022 at 09:22
-- | --
current_recorder_run | December 4, 2022 at 13:57
estimated_db_size | 530.55 MiB
database_engine | mysql
database_version | 10.6.8

</details>

### Anything in the add-on logs that might be useful for us?

```txt
https://pastebin.com/mFsmT4zg
```

**Comment by QuadNL** [comment]
Idem, all my lights and sensors are down, now. 
House is unmanageble.

**Comment by QuadNL** [comment]
@Brian-lub i did a temp fix.

If  addon verison is 6.17 then you can go trough.
Stop the addon and open the terminal:
[code]
docker pull homeassistant/amd64-addon-deconz:6.16.0[/]
Remove current image:
[code]
docker rmi homeassistant/amd64-addon-deconz:6.17.0
[/]
Tag the image 6.16 with version 6.17:
[code]
docker tag homeassistant/amd64-addon-deconz:6.16.0 homeassistant/amd64-addon-deconz:6.17.0
[/]
start the addon. You are now using Phoscon 2.18.02. 
With above commands you use deconz addon version 6.17 in HA with the image 6.16.

**Comment by Zehir** [comment]
@Brian-lub could you check with lastest version if it's fixed ?
