### ISSUE TITLE
MariaDB Duplicate/multiple records of the same entity with the same time stamp

### ISSUE THREAD

**Issue by RamiRihawi** [home-assistant/addons#2787]
### Describe the issue you are experiencing

I noticed that some sensors are being recorded multiple times under the same timestamp, which means the database will grow fast for no reason.

Recently i ran into the issue of purging the 20GB database created by HA using mariaDB which caused the system running on Raspi 4, 8GB to completely freeze until a power loop is done.
I managed to manually delete the tables using PHPmyAdmin add-on and start fresh.
I also added exclude command in the configuration file leaving only the sensors that i am interested in to keep their records.

To see an image of the issue the link is below

[https://community.home-assistant.io/t/mariadb-duplicate-multiple-records-of-the-same-entity-with-the-same-time-stamp/498694](url)

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

MariaDB

### What is the version of the add-on?

2.5.1

### Steps to reproduce the issue

1. phpMyAdmin
2. Database Name
3. States
...

## System Information

version | core-2022.11.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.15.61-v8
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4995
Installed Version | 1.28.4
Stage | running
Available Repositories | 1158
Downloaded Repositories | 42

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 16

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | October 2, 2023 at 2:00 AM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | eu-central-1-0.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.3
-- | --
update_channel | stable
supervisor_version | supervisor-2022.11.2
agent_version | 1.4.1
docker_version | 20.10.18
disk_total | 457.7 GB
disk_used | 185.6 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (10.0.0), Terminal & SSH (9.6.1), File editor (5.4.2), Studio Code Server (5.4.1), Samba NAS (10.0.0-nas3), Mosquitto broker (6.1.3), Node-RED (13.5.3), Assistant Relay (0.7.4), UniFi Network Application (2.4.1), Spotify Connect (0.12.2), MariaDB (2.5.1), ESPHome (2022.11.5), Home Assistant Google Drive Backup (0.109.2), InfluxDB (4.5.0), Grafana (8.1.0), Log Viewer (0.14.0), Frigate (Full Access) (0.11.1), Zigbee2MQTT (1.28.4-1), phpMyAdmin (0.8.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 6
-- | --
resources | 31
views | 19
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | December 4, 2022 at 11:36 AM
-- | --
current_recorder_run | December 6, 2022 at 11:55 AM
estimated_db_size | 251.53 MiB
database_engine | mysql
database_version | 10.6.8

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Comment by LustigePerson** [comment]
Did you find any solution to this? I just switched my new installation to MAriaDB and see the same problem.
