### ISSUE TITLE
File editor - git version too old for SSH commit signing

### ISSUE THREAD

**Issue by caraar12345** [home-assistant/addons#2792]
### Describe the issue you are experiencing

`File editor` is running `git version 2.32.4` which is too old to use SSH commit signing.

Would it be possible to get it updated, please?

_I'm really sorry if this doesn't count as an "issue related to one of the official add-ons"! But it technically is one I suppose? 😅_

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

File editor

### What is the version of the add-on?

5.4.2

### Steps to reproduce the issue

1. Set up SSH commit signing with `git config gpg.format ssh`
2. Use `git commit` then `git push` in `File editor`
3. Be met with an error: `error: unsupported format for gpg.format: ssh`

## System Information

version | core-2022.12.0b6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.15.72
arch | x86_64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.28.4
Stage | running
Available Repositories | 1225
Downloaded Repositories | 54

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 5 January 2023 at 00:00
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
remote_server | eu-west-2-3.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.2
-- | --
update_channel | beta
supervisor_version | supervisor-2022.11.2
agent_version | 1.4.1
docker_version | 20.10.17
disk_total | 56.6 GB
disk_used | 53.4 GB
healthy | true
supported | failed to load: Unsupported
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.1.3), Ookla Speedtest CLI (0.1.0), Home Assistant Google Drive Backup (0.109.2), SSH & Web Terminal (12.1.3), MariaDB (2.5.1), Studio Code Server (5.4.1), InfluxDB2 (1.0.2), Caddy 2 (1.2.6), Samba share (10.0.0), Ring-MQTT with Video Streaming (5.0.5), Node-RED (13.5.3), Zigbee2MQTT (1.28.4-1), fluent-bit (1.2.4), Portainer (2.16.2), Let's Encrypt (4.12.7), Assistant Relay BETA (4.0.0b2), Assistant Relay (0.7.4), AirCast (3.5.0), Shortumation (v0.7.6), Zigbee2MQTT Edge (edge), JupyterLab (0.9.2), AppDaemon (0.10.1), MQTT Explorer (browser-1.0.1), Network UPS Tools (0.11.0), Epic Games Free (bullseye-slim-2022-11-26), Tailscale (0.7.0), EMQX (0.1.3), File editor (5.4.2), diyHue (2.0.7), ESPHome (2022.11.5)

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 23
views | 7
mode | storage

</details>

<details><summary>NextDNS</summary>

can_reach_server | ok
-- | --

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 30 November 2022 at 18:33
-- | --
current_recorder_run | 7 December 2022 at 00:28
estimated_db_size | 498.24 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

**Comment by caraar12345** [comment]
Hey - not sure this is a "feature request" as much as it's a "can we bump the git version"?

**Comment by caraar12345** [comment]
Which, being as the Dockerfile doesn't specify a git version, likely just means "can it be rebuilt"

**Comment by frenck** [comment]
You want git commit signing, which it currently doesn't, thus a new feature.

> being as the Dockerfile doesn't specify a git version, likely just means "can it be rebuilt"

Nope, that will not work.

**Comment by caraar12345** [comment]
> You want git commit signing, which it currently doesn't, thus a new feature.

Fair enough - thanks for the clarification.

> Nope, that will not work.

Fair play - I didn't realise Alpine 3.14 only goes up to git 2.32.4-r0.

Would you accept a PR to raise the base image to 3.15 or 3.16? Both of which containing git >=2.34.0 😄 

I've bumped it in a fork [here](https://github.com/caraar12345/home-assistant-addons/tree/main/configurator) -- with the actual repo fork being https://github.com/caraar12345/home-assistant-addons-fork -- and it seems to work great with 3.16 😄
