### ISSUE TITLE
Domain field not available on Let'sEncrypt conf page

### ISSUE THREAD

**Issue by ruffoniluka** [home-assistant/addons#2810]
### Describe the issue you are experiencing

During the configuration of Let's Encrypte isn't possible fill the domain's field. It's possible do it only writing the configuration in YAML page. I'm using Firefox last version, 

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Hey Ada!

### What is the version of the add-on?

4.12.7

### Steps to reproduce the issue

1.install Let's Encrypt add-on
2. Going to configuration page
3. Try to fill the domain's fields
...

## System Information

version | core-2022.12.7
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.15.80
arch | x86_64
timezone | Africa/Ceuta
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4960
Installed Version | 1.28.4
Stage | running
Available Repositories | 1195
Downloaded Repositories | 3

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.4
-- | --
update_channel | stable
supervisor_version | supervisor-2022.11.2
agent_version | 1.4.1
docker_version | 20.10.19
disk_total | 30.8 GB
disk_used | 5.9 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Samba share (10.0.0), Home Assistant Google Drive Backup (0.109.2), Samba Backup (5.2.0), SSH & Web Terminal (13.0.0), File editor (5.4.2), MariaDB (2.5.1), Example (6.0.0), Studio Code Server (5.5.0), Google Assistant SDK (2.5.0), NGINX Home Assistant SSL proxy (3.2.0), Let's Encrypt (4.12.7)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 0
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 15 dicembre 2022 14:17
-- | --
current_recorder_run | 20 dicembre 2022 12:20
estimated_db_size | 11.09 MiB
database_engine | mysql
database_version | 10.6.8

</details>

### Anything in the Supervisor logs that might be useful for us?

```txt
no
```

### Anything in the add-on logs that might be useful for us?

```txt
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/file-structure.sh
cont-init: info: /etc/cont-init.d/file-structure.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun lets-encrypt (no readiness notification)
s6-rc: info: service legacy-services successfully started
[13:00:08] INFO: Selected http verification
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Account registered.
Requesting a certificate for homeassistant.lucaruffoni.it
Certbot failed to authenticate some domains (authenticator: standalone). The Certificate Authority reported these problems:
  Domain: homeassistant.lucaruffoni.it
  Type:   connection
  Detail: 93.46.126.248: Fetching http://homeassistant.lucaruffoni.it/.well-known/acme-challenge/gRpyMuOlKQnqqU9d1GXEJbTyiOUbPKo2Kc-7_cwzVZs: Timeout during connect (likely firewall problem)
Hint: The Certificate Authority failed to download the challenge files from the temporary standalone webserver started by Certbot on port 80. Ensure that the listed domains point to this machine and that it can accept inbound connections from the internet.
Some challenges have failed.
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by JigSawFr** [comment]
Same problem on my side, but works as expected by editing yaml file.

**Comment by Fastdruid** [comment]
Same issue but using Chrome ( **Version 108.0.5359.125 (Official Build) (64-bit)** ). Also got round it by editing the YAML.

**Comment by pilehave** [comment]
Same issue for me in Chrome and Firefox. Got around it by putting my domain in the brackets as [my.domain.com].
While at it, please change the e-mailfield to plain text and not hidden (***).

**Comment by swifty99** [comment]
same here, thx for the hint with the brackets

**Comment by swifty99** [comment]
not so quick stale bot!

**Comment by pilehave** [comment]
Not planned? WTF 😂
This is a Bug. Utterly ridiculous that this has not been fixed. Wasting
everybody's time.

lør. 25. mar. 2023 22.05 skrev github-actions[bot] ***@***.***
