### ISSUE TITLE
Unable to use File editor without internet connection

### ISSUE THREAD

**Issue by optimusprimespace** [home-assistant/addons#2811]
### Describe the issue you are experiencing

Is this a bug or a feature not to access basic file editing feature without an active internet connection? I had to download Studio Code Serves because when the system is offline (aka the internet is unplugged) i can't access basic functions on this addon because it wants my browser to access cloudflare for unknown reason. After a while the addon loads but cannot click on anything...

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

File editor

### What is the version of the add-on?

5.4.2

### Steps to reproduce the issue

1.Install the addon
2.Remove internet connection from the system and the browser you are trying to access HA
3.You restart the system to ensure that nothing is cached
4.When you start the addon, you can't open anything because it tries to communicate with cloudflare

## System Information

version | core-2022.12.8
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.15.80
arch | x86_64
timezone | ****
config_dir | /config

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.4
-- | --
update_channel | stable
supervisor_version | supervisor-2022.11.2
agent_version | 1.4.1
docker_version | 20.10.19
disk_total | ***
disk_used | ***
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | failed to load: unreachable
installed_addons | ESPHome (2022.12.3), Studio Code Server (5.5.0), File editor (5.4.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 2
views | 13
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 2022. december 14. 10:52
-- | --
current_recorder_run | 2022. december 22. 16:00
estimated_db_size | ***
database_engine | sqlite
database_version | 3.38.5

</details>

### Additional information

Please let us use these basic addons without internet connection. It's the main purpose of HA is that you can run everything offline in your own network.

**Comment by frenck** [comment]
This is not a limitation of the add-on itself, but an limitation of the editor the add-on wraps. Track this upstream issue: 

<https://github.com/danielperna84/hass-configurator/issues/177>

Once upstream has addressed it, we can update the add-on.

Happy Holidays! 🎄 

../Frenck
