### ISSUE TITLE
Mosquitto addon seems to use old term for Users.

### ISSUE THREAD

**Issue by martyvis** [home-assistant/addons#2820]
### Describe the issue you are experiencing

I'm trying to understand how to configure the user for the Mosquitto MQTT add on. The documentation refers to adding a local user under the main "Configurations->Users" menu but as far as I can see in the latest version of Home Assistant, supervisor
Supervisor 2022.12.1,  this might be under Settings->People - or have I totally got this confused?

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Mosquitto broker

### What is the version of the add-on?

6.1.3

### Steps to reproduce the issue

I'm just reading the documentation :- " Create a new user for MQTT via your Home Assistant's frontend Configuration -> Users " which I can't find

### System Health information

There are currently no repairs available

**Comment by ikidd** [comment]
At the top of the People page, there is a tab for Users.  Switch to that and configure users there.  People are entities for use in things like presence detection; users are the actual logins for HA.

**Comment by martyvis** [comment]
OK. I worked it out. I still couldn't see that Users tab in People. But thinking there must be something peculiar, that I found the Users tab is only visible if I turn on Advanced Mode (unlock advanced features!!) that I could see the tab. (I guess though my other point that there is no Configuration menu but a Settings one is correct. I don't how pedantic that doc needs to be about this though.

**Comment by alsternerd** [comment]
> At the top of the People page, there is a tab for Users. Switch to that and configure users there. People are entities for use in things like presence detection; users are the actual logins for HA.

The the shown path should be "Configuration -> People -> Users (Tab)" instead if "Configuration -> Users".
I did fall into that, too now and searched at least an hour, just to find this issue.
