### ISSUE TITLE
Duck DNS rejects all domain names

### ISSUE THREAD

**Issue by michaelmotzke** [home-assistant/addons#2822]
### Describe the issue you are experiencing

At configuration duck DNS rejects all domain names. Whatever I try i get this answer.

Failed to save add-on configuration, Invalid list for option ‘domains’ in Duck DNS (core_duckdns). Got {‘domains’: ‘[domainname.duckdns.org](http://domainname.duckdns.org/)’, ‘token’: ‘dhdhdhddhdhdhdh’, ‘aliases’: [], ‘lets_encrypt’: {‘accept_terms’: True, ‘algo’: ‘secp384r1’, ‘certfile’: ‘fullchain.pem’, ‘keyfile’: ‘privkey.pem’}, ‘seconds’: 300}

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Duck DNS

### What is the version of the add-on?

1.15.0

### Steps to reproduce the issue

1. After installing Duck DNS it requires input of domain.
2. The input process rejects every domain. Also on yaml
3. on yams comes this response:4. 
Failed to save add-on configuration, Invalid list for option ‘domains’ in Duck DNS (core_duckdns). Got {‘domains’: ‘[domainname.duckdns.org](http://domainname.duckdns.org/)’, ‘token’: ‘dhdhdhddhdhdhdh’, ‘aliases’: [], ‘lets_encrypt’: {‘accept_terms’: True, ‘algo’: ‘secp384r1’, ‘certfile’: ‘fullchain.pem’, ‘keyfile’: ‘privkey.pem’}, ‘seconds’: 300}...

The problems seems to be the validity check of the domain name.

### System Health information

no repairs

### Anything in the Supervisor logs that might be useful for us?

```txt
no
```

### Anything in the add-on logs that might be useful for us?

```txt
no
```

### Additional information

Logs show nothing

**Comment by kartmen10** [comment]
Hello,

I get exactly the same...

**Comment by iVolt1** [comment]
I am getting similar.  The input process rejects every domain.

Failed to save add-on configuration, Missing required option 'domains' in Duck DNS (core_duckdns). Got {'domains': [None], 'token': xxxxxxxxxxxxxxxxxxxxxxxb', 'aliases': [], 'lets_encrypt': {'accept_terms': True, 'algo': 'secp384r1', 'certfile': 'fullchain.pem', 'keyfile': 'privkey.pem'}, 'seconds': 300}

**Comment by wigster** [comment]
Same here. You can edit in YAML mode by hand as a workaround.

**Comment by michaelmotzke** [comment]
https://community.home-assistant.io/t/duckdns-addon-1-15-0-accepts-no-domain-at-installation/511715/6?u=mimo

**Comment by Muppetkeeper** [comment]
I have managed to input a domain vi the yaml, but now I can't change the port to 8126.  Has anyone got the code for this please?

**Comment by kartmen10** [comment]
hello,

still not working for me grrr :(((
Have any ideas to help me?
Thx,

Kevin

domains:
  - homekevin.ducksdns.org
token:
  - ********f4-b7ce-4e0e-88fc-*******e90f
lets_encrypt:
  accept_terms: true
  algo: secp384r1
  certfile: fullchain.pem
  keyfile: privkey.pem
seconds: 300

Échec de l'enregistrement de la configuration du module complémentaire,
does not match regular expression .+\.duckdns\.org. Got {'domains': ['
homekevin.ducksdns.org'], 'token': [ ********f4-b7ce-4e0e-88fc-*******e90f
], 'lets_encrypt': {'accept_terms': True, 'algo': 'secp384r1', 'certfile':
'fullchain.pem', 'keyfile': 'privkey.pem'}, 'seconds': 300}

Le mer. 11 janv. 2023 à 12:28, Muppetkeeper ***@***.***> a
écrit :
