### ISSUE TITLE
Google Assistant SDK

### ISSUE THREAD

**Issue by MaggiMaikel** [home-assistant/addons#2823]
### Describe the issue you are experiencing

Hello everyone, first of all I wish you a happy new year.
So now to my question, I've been trying to get the Google Assistant SDK to work for days. I have to say that the documentation is really bad and not suitable for a beginner. How to set everything on Google is described quite “well” and was also set by me, but not the rest.

The documentation says:
 
If the above My button doesn’t work, you can also perform the following steps manually:

Browse to your Home Assistant instance.
In the sidebar click on  [Settings](https://my.home-assistant.io/redirect/config).
From the configuration menu select: [Devices & Services](https://my.home-assistant.io/redirect/integrations).
In the bottom right, click on the  [Add Integration](https://my.home-assistant.io/redirect/config_flow_start?domain=google_assistant_sdk) button.
From the list, search and select “Google Assistant SDK”.
Follow the instruction on screen to complete the set up. 

The only problem is that the GA SDK can't be found there, so I checked the addons to see if I had to install something there first. That's exactly how it was. So I installed the fun and took a look at the configurations to see what else needs to be set.

GA SDK settings

I created the google_assistant.json and filled it with the Google Client Secret. (I don't even know if that's right, because that's not described anywhere either). I entered the project ID and then he also wants a model ID, again there is no description of where to find the ID... So I first entered another ID that was shown to me on Google (it can just can't find it again). It is also nowhere described how I should deal with the port. If I then want to start the addon, it shows me the following in the log:

Look add-on logs

Long story short, no sense at all. I can't even install the addon to see how good/bad the addon is for Google users. Has anyone of you perhaps already had experience with it or even got it installed and adjusted? Would appreciate any help.
Documentations:
- once the documentation of the GA SDK in HA
- https://rc.home-assistant.io/integrations/google_assistant_sdk

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Google Assistant SDK

### What is the version of the add-on?

newest

### Steps to reproduce the issue

1.
2.
3.
...

### System Health information

-

### Anything in the Supervisor logs that might be useful for us?

```txt
-
```

### Anything in the add-on logs that might be useful for us?

```txt
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[14:35:51] FATAL: You need initialize Google Assistant with a client secret JSON!
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

### Additional information

-

**Comment by alkno** [comment]
I ran into the same issue yesterday. I tried to install the Google Assistant SDK Addon. And that's the problem. 
In order to follow the installation instructions you need to install the Google Assistant SDK as an integration in the "Devices & Services" section.

**Comment by govols98** [comment]
I'm having the same issue as above but have not be able to find the fix. Has anyone found the fix for this?
