### ISSUE TITLE
Mosquitto unstable - No ACK

### ISSUE THREAD

**Issue by tim-devel** [home-assistant/addons#2826]
### Describe the issue you are experiencing

I have been using the mosquito add on for months and it has always been really stable but I have had nothing but problems over last few days.  The mosquito server will randomly crash a few times a day.  There  will be a message in the home assistant logs about no ACK error but there is also an error message every 60 seconds in the mosquito logs about contacting a web address.

I have not been able to get any further debugging this.  I would be grateful for any assistance in identifying the cause of this issue.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Mosquitto broker

### What is the version of the add-on?

6.1.3

### Steps to reproduce the issue

1. No specific steps.  Mosquito installed as standard with various devices connected to it - z2m, tasmota, ring2mqtt etc.
2.
3.
...

### System Health information

There are currently no repairs available

### Anything in the Supervisor logs that might be useful for us?

```txt
23-01-08 07:09:15 INFO (SyncWorker_0) [supervisor.docker.interface] Cleaning addon_core_mosquitto application
23-01-08 07:09:16 INFO (SyncWorker_7) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-mosquitto with version 6.1.3
23-01-08 07:09:22 ERROR (MainThread) [supervisor.services.modules.mqtt] There is already a MQTT service in use from core_mosquitto
```

### Anything in the add-on logs that might be useful for us?

```txt
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/mosquitto.sh
[07:09:18] INFO: Setting up user root
[07:09:19] INFO: Setting up user ebusd
[07:09:19] INFO: Certificates found: SSL is available
cont-init: info: /etc/cont-init.d/mosquitto.sh exited 0
cont-init: info: running /etc/cont-init.d/nginx.sh
cont-init: info: /etc/cont-init.d/nginx.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun mosquitto (no readiness notification)
services-up: info: copying legacy longrun nginx (no readiness notification)
s6-rc: info: service legacy-services successfully started
[07:09:20] INFO: Starting NGINX for authentication handling...
[07:09:20] INFO: Starting mosquitto MQTT broker...
1673161760: Loading config file /share/mosquitto/log.conf
2023-01-08 07:09:20: Warning: Mosquitto should not be run as root/administrator.
[07:09:22] INFO: Successfully send discovery information to Home Assistant.
[07:09:22] INFO: Successfully send service information to the Supervisor.
time="2023-01-08T07:09:36Z" level=error msg="POST error: Post \"http://127.0.0.1:80/superuser\": EOF"
time="2023-01-08T07:15:07Z" level=error msg="POST error: Post \"http://127.0.0.1:80/superuser\": EOF"
time="2023-01-08T07:15:22Z" level=error msg="POST error: Post \"http://127.0.0.1:80/superuser\": read tcp 127.0.0.1:47790->127.0.0.1:80: read: connection reset by peer"
time="2023-01-08T07:15:37Z" level=error msg="POST error: Post \"http://127.0.0.1:80/superuser\": EOF"
time="2023-01-08T07:16:46Z" level=error msg="POST error: Post \"http://127.0.0.1:80/superuser\": EOF"
```

**Comment by tim-devel** [comment]
#2655

**Comment by nimmerpeople** [comment]
I have the same in my logs too, now on two different Home Assistant devices/builds - both trying to use ebusd

will see if I can track down ..

time="2023-01-27T22:36:34Z" level=error msg="POST error: Post \"http://127.0.0.1:80/superuser\": EOF"
time="2023-01-27T22:48:28Z" level=error msg="POST error: Post \"http://127.0.0.1:80/superuser\": EOF"
time="2023-01-27T22:51:58Z" level=error msg="POST error: Post \"http://127.0.0.1:80/superuser\": EOF
