### ISSUE TITLE
Duck DNS does not allow custom domain names

### ISSUE THREAD

**Issue by GibsDev** [home-assistant/addons#2835]
### Describe the issue you are experiencing

When configuring Duck DNS via yaml, I am trying to add my own custom domain so that it will be registered with Let's Encrypt and not show a security warning when I use my custom domain as a CNAME for my Duck DNS domain.

The configuration throws an error because the custom domain does not match the regex pattern `.+\.duckdns\.org`

Based on posts I've seen on the internet, it looks like you used to be able to configure your own custom domains.

```
domains:
  - <custom>.duckdns.org
  - <custom domain>
token: <token>
aliases: []
lets_encrypt:
  accept_terms: true
  algo: secp384r1
  certfile: fullchain.pem
  keyfile: privkey.pem
seconds: 300

```

Is there any way to remove this regex check? I could not find the configuration file over SSH to try it that way.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Duck DNS

### What is the version of the add-on?

1.15.0

### Steps to reproduce the issue

1. Add a custom domain in the configuration yaml

## System Information

version | core-2023.1.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.15.76-v8
arch | aarch64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.4
-- | --
update_channel | stable
supervisor_version | supervisor-2022.12.1
agent_version | 1.4.1
docker_version | 20.10.19
disk_total | 56.3 GB
disk_used | 2.7 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Duck DNS (1.15.0), NGINX Home Assistant SSL proxy (3.2.0), Terminal & SSH (9.6.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | January 12, 2023 at 2:01 AM
-- | --
current_recorder_run | January 13, 2023 at 11:31 AM
estimated_db_size | 2.92 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

**Comment by ludeeus** [comment]
You want the letsencrypt addon, not duckdns.

**Comment by GibsDev** [comment]
Is it possible to have the standalone Let's Encrypt Add-on running alongside DuckDNS? I would still like DuckDNS to run so that my potentially dynamic IP will update.

**Comment by ludeeus** [comment]
yes

**Comment by GibsDev** [comment]
So for those who may stumble upon this in the future. I disabled DuckDNS Let's Encrypt by not accepting the terms in the DuckDNS config. Then I installed the Let's Encrypt Add-on and set that up using my duckdns domain and custom domain. Things seem to be working well.

As with the Duck DNS configuration I still needed to add:

```
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
```

to configuration.yaml.

---

I still would like to troubleshoot how to get localhost running over http after these changes, but that is out of the scope of this issue.

I also don't know if this issue should be closed. I guess that depends on if it should still be possible to use custom domains with the DuckDNS Let's Encrypt implementation?

**Comment by ludeeus** [comment]
My bad, it looks like it's the `alias` option you wanted.

**Comment by GibsDev** [comment]
I tried out the alias option, but I did not have any luck. But I'm thinking Let's Encrypt may not have generated a new certificate when I did. Once I finish troubleshooting the current setup, I will try to make a backup and try with alias again.

**Comment by pierslawson** [comment]
It is a long running saga with Duck DNS and custom domains. See this issue that has been closed, but the same issue still occurs:
