### ISSUE TITLE
Can´t set an Domain

### ISSUE THREAD

**Issue by Kasper027** [home-assistant/addons#2839]
### Describe the issue you are experiencing

Hello, I'm trying to enter a domain in the domain field without success. If I enter my xxx.duckdns.org address in the field and then press enter, it is not accepted. As soon as I select another field, the address in the domain field is deleted.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Duck DNS

### What is the version of the add-on?

1.15.0

### Steps to reproduce the issue

.

### System Health information

No repairs

### Anything in the add-on logs that might be useful for us?

```txt
No Logs
```

**Comment by JohnDeckers** [comment]
I have the same problem.
The logfile says:
![image](https://user-images.githubusercontent.com/122289472/212746299-0cd4e43d-d875-44dd-93a8-6570d7ade05b.png)

Who  can Help?

**Comment by WkdPaul** [comment]
Had the same issue, click on the 3 dots at the right and edit in YALM

Put the domain between the brackets, enter the token and save.

**Comment by Kasper027** [comment]
Thanks. That work fine

**Comment by sOckhamSter** [comment]
I'm also seeing this same issue - tested in Safari and Chrome, the only workaround I can find at the moment is to manually edit the YAML.
