### ISSUE TITLE
Zwave device neo coolcam not recognized

### ISSUE THREAD

**Issue by surf33** [home-assistant/addons#2843]
### Describe the issue you are experiencing

The device Zwave Neo CoolCam NAS-DS01 is not recognized. However, it is in the official zwave database https://devices.zwave-js.io/?jumpTo=0x0258:0x0003:0x0082:0.0

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### Which add-on are you reporting an issue with?

Z-Wave JS

### What is the version of the add-on?

0.1.74

### Steps to reproduce the issue

1. include in the zwave network the new device
2.go into the zwave JS UI
3. it is indicated : "Device ID undefined-undefined-undefined (0xXXXX-0xXXXX-0xXXXX)"
...

## System Information

version | core-2023.1.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.15.76-v8
arch | aarch64
timezone | Europe/Paris
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4876
Installed Version | 1.29.1
Stage | running
Available Repositories | 1197
Downloaded Repositories | 16

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.4
-- | --
update_channel | stable
supervisor_version | supervisor-2022.12.1
agent_version | 1.4.1
docker_version | 20.10.19
disk_total | 287.2 GB
disk_used | 14.4 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.5.0), Z-Wave JS UI (1.5.0), Terminal & SSH (9.6.1), SSH & Web Terminal (13.0.2), MariaDB (2.5.1), Traccar (0.17.0), UniFi Network Application (2.5.0), Z-Wave JS (0.1.74), Studio Code Server (5.5.1), Log Viewer (0.14.0), Node-RED (14.0.1), Samba share (10.0.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 9
views | 10
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 13 janvier 2023 à 12:05
-- | --
current_recorder_run | 21 janvier 2023 à 11:34
estimated_db_size | 380.66 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

**Comment by MartinHjelmare** [comment]
Side note: You're not running both the Z-Wave JS UI and the Z-Wave JS add-on at the same time, right?

**Comment by surf33** [comment]
What I have is:
- Integration : I have Z Wave JS (and all my devices)
- Addons: 
Z Wave JS : stopped
Z Wave JS UI : started

I can find the sensor in Z Wave JS with "_Device ID undefined-undefined-undefined (0xXXXX-0xXXXX-0xXXXX)" but nothing in the Z Wave JS integration

**Comment by MartinHjelmare** [comment]
If you're not using the Z-Wave JS add-on, opening an issue in the add-on repository isn't relevant. Please open an issue in the Home Assistant Core repository instead.

**Comment by surf33** [comment]
Ok, thanks!
