### ISSUE TITLE
Unable to upload files to Samba Share - iOS 16

### ISSUE THREAD

**Issue by AStoker** [home-assistant/addons#2857]
### Describe the issue you are experiencing

I am trying to upload a file to a samba share folder (media folder) using the iOS Files app.
It's worth noting that it works on Mac OS. But when trying to upload a file using iOS 16.3 (or iPadOS 16.3) I get an error 100093.
> The Operation Can't Be Completed.
> The operation can't be completed because an unexpected error occurred (error code 100093)

Related to issue #2711

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Samba share

### What is the version of the add-on?

10.0.0

### Steps to reproduce the issue

1. Install samba share addon
2. Configure samba share with username and password
3. Open Files app on iPad
4. Copy a file (a picture for example) from a folder
5. Open Samba share on Files app
6. Navigate to `media` folder
7. Paste file
8. Error occurrs

## System Information
version | core-2023.1.7
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.15.76-v7
arch | armv7l
timezone | America/New_York
config_dir | /config
<details><summary>Home Assistant Cloud</summary>
logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok
</details>
<details><summary>Home Assistant Supervisor</summary>
host_os | Home Assistant OS 9.4
-- | --
update_channel | stable
supervisor_version | supervisor-2023.01.1
agent_version | 1.4.1
docker_version | 20.10.19
disk_total | 3667.5 GB
disk_used | 33.0 GB
healthy | true
supported | true
board | rpi3
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.6.1), File editor (5.5.0), Samba share (10.0.0), SSH & Web Terminal (13.0.2), Mosquitto broker (6.1.3), Z-Wave JS (0.1.74), AirCast (3.5.1), Plex Media Server (3.2.1)
</details>
<details><summary>Dashboards</summary>
dashboards | 1
-- | --
resources | 0
mode | auto-gen
</details>
<details><summary>Recorder</summary>
oldest_recorder_run | January 17, 2023 at 6:18 PM
-- | --
current_recorder_run | January 25, 2023 at 7:31 PM
estimated_db_size | 224.27 MiB
database_engine | sqlite
database_version | 3.38.5
</details>

### Anything in the Supervisor logs that might be useful for us?

```txt
> 23-01-27 13:18:58 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
```

### Anything in the add-on logs that might be useful for us?

```txt
root opened file Not Terrible.png read=No write=No (numopen=3)
root closed file Not Terrible.png (numopen=1) NT_STATUS_OK
root opened file Not Terrible.png read=No write=Yes (numopen=3)
root closed file Not Terrible.png (numopen=1) NT_STATUS_OK
root opened file Not Terrible.png read=No write=Yes (numopen=2)
root closed file Not Terrible.png (numopen=0) NT_STATUS_OK
root opened file Not Terrible.png read=No write=Yes (numopen=3)
root closed file Not Terrible.png (numopen=1) NT_STATUS_OK
```

**Comment by AStoker** [comment]
Bump

**Comment by AStoker** [comment]
Bump. Still an issue.

**Comment by patanachai** [comment]
I have the similar problem, my error is
> "The operation couldn't be completed. Operation canceled"
This might be related to this apple discussion [here](https://discussions.apple.com/thread/252772242)

I quote the workaround from the reply here
> 1.Install samba-vfs-modules ( sudo apt install samba-vfs-modules )
2 I have added the following 3 options into the [global] section into /etc/samba/smb.conf :
       fruit:nfs_aces = no
       fruit:aapl = yes
       vfs objects = catia fruit streams_xattr
3 sudo service smbd restart (load the new config)

**Comment by patanachai** [comment]
I cloned and tested an addons on a local development setup with a vfs-modules solution above with combination of different configuration.  I got the same error

>The Operation Can't Be Completed.
The operation can't be completed because an unexpected error occurred (error code 100093)

This might be a with iOS **Files** App specific implementation and **Raspberry Pi**
Note: The tested Ipad is on IpadOS 16.4.1

**Comment by AStoker** [comment]
Bump. Still an issue ☹️

**Comment by AStoker** [comment]
To future generations who still cannot use Samba shares, I wish you well 🖖

**Comment by Feuermurmel** [comment]
Maybe it's this issue? https://apple.stackexchange.com/a/424682/25448

Adding `vfs objects = fruit streams_xattr` to `smb.conf` solved the issue with stock Samba on Debian.

**Comment by Damilare1** [comment]
> Maybe it's this issue? https://apple.stackexchange.com/a/424682/25448
> 
> Adding `vfs objects = fruit streams_xattr` to `smb.conf` solved the issue with stock Samba on Debian.

This worked for me as well, documentation for the `fruit vfs module` was quite explanatory as to how it enhances interoperability with OSX: https://www.samba.org/samba/docs/current/man-html/vfs_fruit.8.html.

**Comment by Gpzim98** [comment]
> Maybe it's this issue? https://apple.stackexchange.com/a/424682/25448
> 
> Adding `vfs objects = fruit streams_xattr` to `smb.conf` solved the issue with stock Samba on Debian.

This worked for me as well.
