### ISSUE TITLE
deconz: turn off with transition (fade out) stopped working

### ISSUE THREAD

**Issue by prof7bit** [home-assistant/addons#2859]
### Describe the issue you are experiencing

See here:
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6709
https://github.com/home-assistant/core/issues/86646

I'm not sure whether this is the rest-API or the addon or the integration, but as described in the above links: I am unable to do a fade-off transition since the latest Deconz-Addon. 

My Home Assistant version is still 2022.11.5.

I cannot find any relevant change logs that touch the topic of transitions, neither in deconz nor in Home Assistant.

Downgrading the addon to 6.17.1 fixes it.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Deconz

### What is the version of the add-on?

6.18.0

### Steps to reproduce the issue

1. turn_off with data: {transition: 10}

will turn off immediately and ignore the transition.

### System Health information

"no repairs available"

**Comment by chpego** [comment]
https://github.com/dresden-elektronik/deconz-rest-plugin/compare/v2.19.3...v2.20.1

**Comment by PolestarWx** [comment]
same with turn on here 
`https://github.com/home-assistant/core/issues/86646`

**Comment by PolestarWx** [comment]
#[86646](https://github.com/home-assistant/core/issues/86646)

**Comment by PolestarWx** [comment]
@pvizeli @frenck @kiwikern if any one you can take a look on that, this seems to affect lot of user, not sure it's really deconz rest pluginthat cause problem or HA directly since user that use other zigbee key seems affected in the other issue.

**Comment by PolestarWx** [comment]
Just checked deconz debug log and nothing appear related to a transition fail

**Comment by PolestarWx** [comment]
Please reopen

**Comment by dimitripb** [comment]
@PolestarWx This is not an HA issue. It's in Deconz:
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6709
