### ISSUE TITLE
Z-Wave JS: UI does not fulfill certification requirements for Thermostat Mode and Thermostat Setpoint CC

### ISSUE THREAD

**Issue by AlCalzone** [home-assistant/addons#2863]
### Describe the issue you are experiencing

The Z-Wave specs mandate this for the Thermostat Mode CC:
> The end user MUST be able to select between all supported modes by the supporting node, even if
the controlling node does not know what a given mode represents.

and this for the Thermostat Setpoint CC:
> The end user MUST be able to set the setpoint for any setpoint type, even if the controlling node
does not know what a given type represents.

Testing with a HELTUN HE-HT01 which supports these modes/setpoints:
```
"0": "Off",
"1": "Heat",
"8": "Dry",
"10": "Auto changeover",
"11": "Energy heat",
"13": "Away"
```

I only get the following choices in the UI:
![grafik](https://user-images.githubusercontent.com/17641229/215478249-98893c3c-84b6-469c-89e4-206201bfd818.png)
and 
![grafik](https://user-images.githubusercontent.com/17641229/215478203-1dd77527-3512-4c26-a015-b400ae3b8ce8.png)

Notice that Heat/Cool isn't supported by the device and all the other modes are missing.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Z-Wave JS

### What is the version of the add-on?

0.1.74

### Steps to reproduce the issue

Include a Z-Wave thermostat which supports other modes than Off, Heat, Heat/Cool.
Attempt to enable one of those additional modes.

## System Information

version | core-2023.1.7
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.15.84-v8
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.01.1
agent_version | 1.4.1
docker_version | 20.10.22
disk_total | 13.6 GB
disk_used | 5.3 GB
healthy | true
supported | true
board | yellow
supervisor_api | ok
version_api | ok
installed_addons | Z-Wave JS (0.1.74), Z-Wave JS UI (1.4.2), Samba share (10.0.0), Z-Wave JS (0.1.72), NGINX Home Assistant SSL proxy (3.2.0), Let's Encrypt (4.12.7)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
mode | auto-gen

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | August 29, 2022 at 7:12 PM
-- | --
current_recorder_run | January 30, 2023 at 12:37 PM
estimated_db_size | 2.96 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

**Comment by MartinHjelmare** [comment]
Please open these issues in the core repo instead. Thanks!

**Comment by MartinHjelmare** [comment]
I think heat/cool is mapped to Auto changeover.

This is our definition of these modes:

```
# The device supports heating/cooling to a range
    HEAT_COOL = "heat_cool"

    # The temperature is set based on a schedule, learned behavior, AI or some
    # other related mechanism. User is not able to adjust the temperature
    AUTO = "auto"
```
