### ISSUE TITLE
DuckDNS add-on not starting with unavailable Internet

### ISSUE THREAD

**Issue by ygorre** [home-assistant/addons#2868]
### Current state
DuckDNS add-on crashes and do not start when Internet access is unavailable.

This bug arises mostly on power outages, when my RPi3 HaOS finishes booting before my Internet modem does. After that, I need to manually start the add-on (something not really possible when abroad with dynamic IP address).

### Expected behavior
Add-on starts successfully and wait for proper network connection on such cases (e. g. by retrying after some minutes).

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Duck DNS

### What is the version of the add-on?

1.15.0

### Steps to reproduce the issue

1. Power on the OS without Internet access.
2. DuckDNS add-on do not start automatically.
...

### System Health information

No repairs available.

### Anything in the add-on logs that might be useful for us?

```txt
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
# INFO: Using main config file /data/workdir/config
ERROR: Problem connecting to server (get for https://acme-v02.api.letsencrypt.org/directory; curl returned with 6)
EXPECTED value GOT EOF
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### Additional information

Add-on info has "Start on boot" and "Watchdog" checked. A simulation of the error I just made also indicates the system attempted to restart the add-on before stopping.

**Comment by CarlosGS** [comment]
Same here, cannot access Home Assistant until manually restarting the addon

**Comment by M0uC0** [comment]
I have the same problem.

Away from home when it happens.. new ip assigned by the isp when internet is back on...
No home access till i arrive at home and press "start" on it.

**Comment by edurenye** [comment]
This issue is important, this is a big bug

**Comment by alsFC** [comment]
It also occurs when the Let's Encrypt API is just not available. IMHO the Duck DNS Add-on should just ignore this, start without certificate evaluation and log a warning.
