### ISSUE TITLE
Mosquitto: Unable to create websockets listener on port 1884

### ISSUE THREAD

**Issue by rokam** [home-assistant/addons#2904]
### Describe the issue you are experiencing

When I launch the mosquitto broker it complains about port 1884, even if I change the port in the configuration, the issue remains. So I think the port conflict should be inside the container.

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### Which add-on are you reporting an issue with?

Mosquitto broker

### What is the version of the add-on?

6.1.3

### Steps to reproduce the issue

1. Start  the addon with any configuration

## System Information

version | core-2023.3.1
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.10
os_name | Linux
os_version | 6.2.2-arch1-1
arch | x86_64
timezone | America/Sao_Paulo
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4962
Installed Version | 1.31.0
Stage | running
Available Repositories | 1242
Downloaded Repositories | 5

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Arch Linux
-- | --
update_channel | stable
supervisor_version | supervisor-2023.01.1
agent_version | 1.4.1
docker_version | 23.0.1
disk_total | 111.3 GB
disk_used | 50.5 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | Duck DNS (1.15.0), Home Assistant Google Drive Backup (0.110.1), Studio Code Server (5.5.3), Mosquitto broker (6.1.3), Terminal & SSH (9.6.1), SQLite Web (3.7.0), Zigbee2MQTT (1.30.2-1), Node-RED (14.0.3), NGINX Home Assistant SSL proxy (3.2.0), UniFi Network Application (2.5.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
views | 4
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 25 de fevereiro de 2023 às 19:43
-- | --
current_recorder_run | 6 de março de 2023 às 09:39
estimated_db_size | 356.35 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

<details><summary>Sonoff</summary>

version | 3.4.0 (5406fa7)
-- | --
cloud_online | 27 / 31
local_online | 27 / 27

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Anything in the Supervisor logs that might be useful for us?

```txt
23-03-06 09:43:13 INFO (SyncWorker_1) [supervisor.docker.interface] Cleaning addon_core_mosquitto application
23-03-06 09:43:13 INFO (SyncWorker_1) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-mosquitto with version 6.1.3
23-03-06 09:43:20 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Mosquitto broker is stopped, restarting...
23-03-06 09:43:20 INFO (SyncWorker_4) [supervisor.docker.interface] Cleaning addon_core_mosquitto application
23-03-06 09:43:21 INFO (SyncWorker_5) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-mosquitto with version 6.1.3
23-03-06 09:43:27 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Mosquitto broker is stopped, restarting...
23-03-06 09:43:27 INFO (SyncWorker_6) [supervisor.docker.interface] Cleaning addon_core_mosquitto application
23-03-06 09:43:27 INFO (SyncWorker_1) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-mosquitto with version 6.1.3
23-03-06 09:43:34 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Mosquitto broker is stopped, restarting...
23-03-06 09:43:34 INFO (SyncWorker_7) [supervisor.docker.interface] Cleaning addon_core_mosquitto application
23-03-06 09:43:34 INFO (SyncWorker_4) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-mosquitto with version 6.1.3
23-03-06 09:43:41 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Mosquitto broker is stopped, restarting...
23-03-06 09:43:41 INFO (SyncWorker_2) [supervisor.docker.interface] Cleaning addon_core_mosquitto application
23-03-06 09:43:41 INFO (SyncWorker_6) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-mosquitto with version 6.1.3
23-03-06 09:43:47 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Mosquitto broker is stopped, restarting...
23-03-06 09:43:47 INFO (SyncWorker_7) [supervisor.docker.interface] Cleaning addon_core_mosquitto application
23-03-06 09:43:48 INFO (SyncWorker_0) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-mosquitto with version 6.1.3
23-03-06 09:43:54 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Mosquitto broker is stopped, restarting...
23-03-06 09:43:54 INFO (SyncWorker_1) [supervisor.docker.interface] Cleaning addon_core_mosquitto application
23-03-06 09:43:55 INFO (SyncWorker_4) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-mosquitto with version 6.1.3
23-03-06 09:44:01 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Mosquitto broker is stopped, restarting...
23-03-06 09:44:01 INFO (SyncWorker_7) [supervisor.docker.interface] Cleaning addon_core_mosquitto application
23-03-06 09:44:01 INFO (SyncWorker_3) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-mosquitto with version 6.1.3
23-03-06 09:44:07 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Mosquitto broker is stopped, restarting...
```

### Anything in the add-on logs that might be useful for us?

```txt
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/mosquitto.sh
[09:29:48] INFO: Setting up user kodi
[09:29:48] INFO: Certificates found: SSL is available
cont-init: info: /etc/cont-init.d/mosquitto.sh exited 0
cont-init: info: running /etc/cont-init.d/nginx.sh
cont-init: info: /etc/cont-init.d/nginx.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun mosquitto (no readiness notification)
services-up: info: copying legacy longrun nginx (no readiness notification)
s6-rc: info: service legacy-services successfully started
[09:29:49] INFO: Starting NGINX for authentication handling...
[09:29:49] INFO: Starting mosquitto MQTT broker...
2023-03-06 09:29:49: Warning: Mosquitto should not be run as root/administrator.
2023-03-06 09:29:49: mosquitto version 2.0.11 starting
2023-03-06 09:29:49: Config loaded from /etc/mosquitto/mosquitto.conf.
2023-03-06 09:29:49: Loading plugin: /usr/share/mosquitto/go-auth.so
2023-03-06 09:29:49:  ├── Username/password checking enabled.
2023-03-06 09:29:49:  ├── TLS-PSK checking enabled.
2023-03-06 09:29:49:  └── Extended authentication not enabled.
2023-03-06 09:29:49: Opening ipv4 listen socket on port 1883.
2023-03-06 09:29:49: Opening ipv6 listen socket on port 1883.
2023-03-06 09:29:49: Opening websockets listen socket on port 1884.
2023-03-06 09:29:49: Error: Unable to create websockets listener on port 1884.
[12:29:49] WARNING: Halt add-on
s6-rc: info: service legacy-services: stopping
[12:29:49] INFO: Service restart after closing
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by wberrazeg** [comment]
Same issue here, on :
Home Assistant 2023.4.0.dev20230307
Supervisor 2023.03.dev0702
Operating System 10.0.dev20230306
Frontend 20230307.0.dev - latest
Mosquitto broker :  6.1.3

**Comment by freerko** [comment]
Same here, completely new setup on a Raspberry Pi 3. It is not possible to start the Mosquitto broker add-on. In the Add-On GUI there is a red dot for Mosquitto and clicking on "Start" doesn't change that.

My add-on logs:

> s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/mosquitto.sh
[11:19:15] INFO: SSL is not enabled
cont-init: info: /etc/cont-init.d/mosquitto.sh exited 0
cont-init: info: running /etc/cont-init.d/nginx.sh
cont-init: info: /etc/cont-init.d/nginx.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun mosquitto (no readiness notification)
services-up: info: copying legacy longrun nginx (no readiness notification)
s6-rc: info: service legacy-services successfully started
[11:19:17] INFO: Starting NGINX for authentication handling...
[11:19:17] INFO: Starting mosquitto MQTT broker...
2023-03-09 11:19:17: Warning: Mosquitto should not be run as root/administrator.
[11:19:20] INFO: Successfully send discovery information to Home Assistant.
[11:19:20] INFO: Successfully send service information to the Supervisor.

**Comment by eddybeegy** [comment]
Same on:
Home Assistant 2023.4.0.dev20230310
Supervisor 2023.03.dev0905
Operating System 10.0.dev20230309
Frontend 20230310.0.dev - latest
Mosquitto broker : 6.1.3

**Comment by rokam** [comment]
I don't know what is the issue because it works inside the devcontainer. But I was able to run it with debian:bookworm base image.

**Comment by spartandrew18** [comment]
Same issue here running latest dev on Homeassistant OS

**Comment by mwhdc** [comment]
Same here with Operating System 10.0 rc1.

**Comment by BenjaminPavelka** [comment]
Same issue here running Homeassistant on arch linux.

**Comment by outgeeked** [comment]
Experiencing the same issue, running the following config via Proxmox on an Intel NUC 12:

Home Assistant 2023.3.6
Supervisor 2023.03.2
Operating System 10.0.rc1
Frontend 20230309.1 - latest

**Comment by wattsie** [comment]
Agreed. Confirmed is appears to be in 10.0.rc1.
I downgraded HA Core to all version back from 2023.3.6 to 2023.2.5 and keeps failing on websockets.
I did see in passing, a post about possibly "_error comes about if libwebsockets is compiled without the LWS_WITH_EXTERNAL_POLL flag, and if only a single websockets only listener is defined_"
For now, I rolled back to 9.5 and MQTT is working again.
Thanks for all the awesome work.

**Comment by Thrasher2020** [comment]
How do I roll back please?

**Comment by wattsie** [comment]
Sorry on phone so might be rough. 

OS back to 9.5
`ha os upgrade —version 9.5`

Core downgrade
`ha core upgrade —version x.x.x`

Check GitHub for version numbers

Be sure to have backups. 

Cheers.

**Comment by dbrb2** [comment]
Thanks! Worked as suggested

**Comment by FrancoLoco** [comment]
same here

**Comment by Thrasher2020** [comment]
Back online again - thanks!!
________________________________

**Comment by Emilef22** [comment]
Hi! Witch core version I have to downgrade? Thanks!

**Comment by LeChat109** [comment]
> Hi! Witch core version I have to downgrade? Thanks!

you have to downgrade to version 9.5 with the command `ha os upgrade —version 9.5`

**Comment by LeChat109** [comment]
same problem

**Comment by outgeeked** [comment]
I receive the following error when attempting to update Mosquitto broker from 6.1.3 to 6.20; is this a known issue?

![image](https://user-images.githubusercontent.com/73629733/228015860-149b08b0-9178-4487-a251-731f35472853.png)

**Comment by rokam** [comment]
The images are being uploaded atm.
https://github.com/home-assistant/addons/actions/runs/4534642566

**Comment by dodavies** [comment]
upgrading to v 10 and this is still an issue

**Comment by Thrasher2020** [comment]
You need to update MQTT
