### ISSUE TITLE
multiprotocol high CPU use

### ISSUE THREAD

**Issue by jhbruhn** [home-assistant/addons#2910]
### Describe the issue you are experiencing

The multiprotocol add-on is using a lot of CPU resources. According to glances, it is the mdnsd process utilizing 99% after a while.

This happens with OTBR enabled and disabled. ZigBee connected to Z2M

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Silicon Labs Multiprotocol

### What is the version of the add-on?

1.0.0

### Steps to reproduce the issue

1. Leave addon running for a couple of hours with any configuration 
2.
3.
...

## System Information

version | core-2023.3.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.10
os_name | Linux
os_version | 5.15.84-v8
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.31.0
Stage | running
Available Repositories | 1320
Downloaded Repositories | 53

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.03.1
agent_version | 1.4.1
docker_version | 20.10.22
disk_total | 458.4 GB
disk_used | 41.7 GB
healthy | true
supported | true
board | yellow
supervisor_api | ok
version_api | ok
installed_addons | AdGuard Home (4.8.2), AppDaemon (0.11.0), ESPHome (2023.2.4), File editor (5.5.0), Grafana (8.2.0), MariaDB (2.5.2), Mosquitto broker (6.1.3), Node-RED (14.0.4), Samba Backup (5.2.0), Samba share (10.0.0), Studio Code Server (5.5.3), Tailscale (0.7.0), Terminal & SSH (9.6.1), TooGoodToGo Home Assistant MQTT Bridge (2.5.1.2), phpMyAdmin (0.8.3), InfluxDB (4.5.0), Zigbee2MQTT (1.30.1-1), E-Paper Screenshotter (1.0.1.35), E-Paper Station (1.0.0.48), RPC Shutdown (2.2), Silicon Labs Multiprotocol (1.0.0), Zigbee2MQTT Edge (edge), Glances (0.17.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 22
views | 19
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | March 7, 2023 at 18:02
-- | --
current_recorder_run | March 10, 2023 at 09:32
estimated_db_size | 3244.39 MiB
database_engine | mysql
database_version | 10.6.10

</details>

**Comment by MattWestb** [comment]
I have the same experiences and it normally happening after start of the system but can also happening then its up and running. Restart the addon is making the mdnsd service behaving normal and not eating one CPU. And its being better in the last version as it was for nearly one year ago.

**Comment by jhbruhn** [comment]
Is there any way to aid in fixing this? Mdnsd does not seem to output any error or warning logs, maybe those could be enabled?

If I restart the addon it is working fine for a couple of hours maybe before it starts to eat one of my CPU cores again, which is not that many on a HA Yellow :(

**Comment by networkpanic** [comment]
i face this issue too on a raspberry pi4 with a SkyConnect connected.
A restart solves the issue for some time but it always comes back

**Comment by elylv** [comment]
Having the same issue on my system, Proxmox reports >50% cpu usage constantly until I stop this addon.  Eventually comes back after a restart.  I am on version 1.1.1

**Comment by knallt** [comment]
I have the same issue. Since I have installed the ha skyconnect with ZHA the CPU usage is at 25% for the add-on on RPI 4. Any idea?

**Comment by MattWestb** [comment]
@knallt Is you running OS or normal ?
If not OS can you running `htop` and look wish process is eating CPU.

**Comment by elylv** [comment]
I am running OS, and htop doesn't report the high CPU usage (but Proxmox does)... not sure if this is a limitation of OS.  CPU usage drops immediately if I stop the multiprotocol addon.

**Comment by si458** [comment]
#2937 same issue here

**Comment by jhbruhn** [comment]
Can, for now, the mdnsd service be disabled if the OTBR is disabled? This way at least in some scenarios the load could be reduced, although it does not fix the root of the problem. Especially with whisper/piper running on the yellow, it needs all the CPU capacity it can get.

**Comment by MattWestb** [comment]
What i knowing if mDNS is not working / installed in the addon the the thread device cant communication with your network that is running the HA and the other way so you is braking the OTBR functionality completely.

**Comment by jhbruhn** [comment]
Which is why I suggested to only disable the mdnsd service if OTBR is also disable via the addon configuration.

**Comment by MattWestb** [comment]
OK so the system is still having one up and running and not multiple that is fighting and making problems like we is having if running more OTBR  with the same thread network in  the network today.

**Comment by glowtape** [comment]
Ditto. Noticed only today. Going into the Alpine OS shell and running top:

<img width="880" alt="image" src="https://user-images.githubusercontent.com/4010813/236491250-8bd8d173-97d4-4a74-8383-01baf099e86e.png">

**Comment by JC-LB** [comment]
Here it eventually ended up making everything USB related disconnect (Z-wave stick, RFXtrx, and Zigbee Sky connect....)
My PI is hot as never seen, just ordered a 20W psu to replace the 15W I have.

But something definitely needs to be done with this internal mdnsd process, by the way, i see in the container log that it cannot claim an IPv6 group address a few times after boot.

**Comment by jhbruhn** [comment]
Still relevant for people who are using OTBR, right?

**Comment by DerTanzendeNarr** [comment]
Had the issue twice this week.
RPi4 with SkyConnect.

**Comment by mikenhu** [comment]
I am facing the same issue. 

I have HA yellow and just recently have had the high processor usage on silicon labs multiprotocol add on for the past few days. Restarting the add on or the HA yellow didn't help reduce the issue at all. Today I found that only disabling the OTBR firewall option on the add on immediately fixed the high stat and reduce the processor temperature.

**Comment by prj32** [comment]
I have had the same issue on and off for a few releases. It has come back with latest release, restarting doesn't help. I tried disabling OTBR and performance returned to normal. Thank-you @mikenhu. Team can we confirm if this is a supported configuration.Happy to share logs if that would help.

**Comment by jhbruhn** [comment]
AFAIK not fixed yet.

**Comment by MattWestb** [comment]
I was having this problems more or less every restart of my hardware and was need to restart the addon one or more times for getting the system not burning one CPU all the time at the beginning this journey (from the beginning and the end of the last year) but after updating armbian with the normal Ubuntu fixes also some for the DNS i have seen it only 1 time the last 3 months on 3 systems running the addon with RCP EZSP.
One thing can being problem in the OS and need updating  it  for getting it working better. (I only have one active OTBR then its not working have more active in the network (the network is OK but HA cant handling it OK) that can also being the one thing  that making it working better.
Its only observations no real facts from my side.

**Comment by AFumi39** [comment]
I "solved" setting up an automation that notify me about high CPU usage for 30 minutes (so I can check and restart the addon). Until now restarting the addon solves the problem for some time, but it seems to occurs randomly: I can have high CPU problem 2 times in a day, or even only 1 time in a week; it seems unrelated to anything else on raspi or HAOS.

For example last weeks the problem occurred on:
04/07
05/07 (2 times)
09/07
11/07
14/07
23/07
27/07
02/08

**Comment by jcnico** [comment]
> I "solved" setting up an automation that notify me about high CPU usage for 30 minutes (so I can check and restart the addon). Until now restarting the addon solves the problem for some time, but it seems to occurs randomly: I can have high CPU problem 2 times in a day, or even only 1 time in a week; it seems unrelated to anything else on raspi or HAOS.
> 
> For example last weeks the problem occurred on: 04/07 05/07 (2 times) 09/07 11/07 14/07 23/07 27/07 02/08

You can even automate the restart using the hassio.addon_restart service.

Last occurrence for me was on 31/05, so it somehow seemed to have disappeared for me.

**Comment by AFumi39** [comment]
> You can even automate the restart using the hassio.addon_restart service.
> 
> Last occurrence for me was on 31/05, so it somehow seemed to have disappeared for me.

Yes, I can automate the restart, but for now I preferred to receive only notification and do the manual restart. If this continue, I will surely add the restart action to the automation

**Comment by agners** [comment]
This is addressed with #3169, closing.
