### ISSUE TITLE
Nginx proxy addon: No config option for `X-Forwarded-Host`

### ISSUE THREAD

**Issue by TheHolyRoger** [home-assistant/addons#2912]
### Describe the issue you are experiencing

As the title says, there's no config option for `X-Forwarded-Host` which should go just here: https://github.com/home-assistant/addons/blob/master/nginx_proxy/data/nginx.conf#L66

As noted in the vscode issue here: https://github.com/hassio-addons/addon-vscode/issues/584#issuecomment-1462976192

The latest version of vscode no longer functions without adding:
`proxy_set_header X-Forwarded-Host $http_host;`
To the nginx config

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

NGINX Home Assistant SSL proxy

### What is the version of the add-on?

3.2.0

### Steps to reproduce the issue

1. Use nginx proxy
2.  Use latest version of vscode addon

### System Health information

N/A

### Anything in the Supervisor logs that might be useful for us?

```txt
N/A
```

### Anything in the add-on logs that might be useful for us?

```txt
N/A
```

**Comment by agners** [comment]
Fixed by: #2915.
