### ISSUE TITLE
Have the option to turn soft reset back on for VM

### ISSUE THREAD

**Issue by djfjeff** [home-assistant/addons#2917]
### Describe the issue you are experiencing

With this PR merged (https://github.com/home-assistant/addons/pull/2261), there is no way to enable soft reset in a VM, even turning the Soft Reset options still give the following error when trying to do a soft reset  :

`The soft reset feature has been disabled with a config option or the ZWAVEJS_DISABLE_SOFT_RESET environment variable.`

I am aware of the issue that soft reset can do in a VM environment but I already have a script that take care of this. I need to have this option to do NVM backup for my stick.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Z-Wave JS

### What is the version of the add-on?

1.7.2

### Steps to reproduce the issue

1. Run HASS in a VM
2. Turn on Soft Reset in the ZwaveJS settings
3. Try to do a soft reset and still get the error
...

### System Health information

There are currently no repairs available

### Additional information

It was possible and was working fine before the merge of https://github.com/home-assistant/addons/pull/2261

**Comment by MartinHjelmare** [comment]
Are you using the Z-Wave JS UI add-on? The official Z-Wave JS add-on and the Z-Wave JS UI add-on don't share any code or configuration. If you're using one, it doesn't matter how the other one is coded.

**Comment by djfjeff** [comment]
I am using the Z-Wave JS UI addon. Do you know where I should fill this bug if I am not in the right place?

**Comment by djfjeff** [comment]
Ok, I found the issue and will work with the right folks on this, sorry for the noise!
