### ISSUE TITLE
Silicon Labs Multiprotocol crashes with Unknown otbr_log_level: null

### ISSUE THREAD

**Issue by mbay0r** [home-assistant/addons#2924]
### Describe the issue you are experiencing

Silicon Labs Multiprotocol Current version: 1.0.2 
Home Assistant 2023.3.5
Supervisor 2023.03.1
Operating System 9.5

ive a crash every night, which results in the following error:

```
[07:18:20] FATAL: Unknown otbr_log_level: null
[07:18:20] INFO: otbr-agent ended with exit code 1 (signal 0)...
[07:18:20] INFO: OTBR firewall teardown completed.
```

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Silicon Labs Multiprotocol

### What is the version of the add-on?

1.0.2 

### Steps to reproduce the issue

after saving the configuration again, everything is ok again. The next day the same problem again.

### System Health information

all ok.

**Comment by MattWestb** [comment]
Have you trying setting `OpenThread Border Router agent log leve` to `notice` in the addon settings ?
On the road it have being some settings that is not getting  defaults then installing the addon and its failing to start until you is setting somthing so its not being `null`.

**Comment by mbay0r** [comment]
it really sucks, every day I have to restart the addon. Is there any way to set this manually in a configuration file? Thanks

**Comment by MattWestb** [comment]
My 2 motion sensor have not leaving the network for over 4 years and only one have getting new battery under that time but it have many bad routers to jumping to if its like to do that.

**Comment by MattWestb** [comment]
Sorry wrong posting :-((

**Comment by agners** [comment]
Uninstall/reinstall or save the config should make this go away, I'd say. Are there any information in the Supervisor logs?

**Comment by mbay0r** [comment]
@agners I save the configuration every day, otherwise I can not start the addon. I have already done Uninstall/Reinstall, unfortunately that did not fix the error. :-(

Supervisor log looks good, but also starts at 11:00 am

**Comment by agners** [comment]
Can you maybe change the log level to something else and then save?

I've never had a case where configuration save didn't work. If it is a file system issue or corruption issue I'd expect something in the log files.

**Comment by mbay0r** [comment]
done. ive set it to info right now.

I have tried all log levels in the past, but the error is always the same.

supervisor log:

```
23-03-29 14:01:09 INFO (SyncWorker_7) [supervisor.docker.interface] Stopping addon_core_silabs_multiprotocol application
23-03-29 14:01:14 INFO (SyncWorker_7) [supervisor.docker.interface] Cleaning addon_core_silabs_multiprotocol application
23-03-29 14:01:15 INFO (SyncWorker_1) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-silabs-multiprotocol with version 1.0.2
23-03-29 14:01:23 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_silabs_multiprotocol

```

**Comment by mbay0r** [comment]
@agners any other ideas? thank you very much!

**Comment by agners** [comment]
What type of storage are you using? Maybe your storage is not working correctly anymore?

Can you go to the add-on change the log level, then press Save. Then go to Logs and choose "Supervisor" in the selection on the top right corner.

**Comment by mbay0r** [comment]
Im running HA OS on a QNAP NAS as a Virtual Machine using VirtualizationStation 3. VM is running on a Raid 1, Disk Health is good.

Here is the log:

```
23-04-04 21:06:14 INFO (SyncWorker_4) [supervisor.docker.interface] Stopping addon_core_silabs_multiprotocol application
23-04-04 21:06:19 INFO (SyncWorker_4) [supervisor.docker.interface] Cleaning addon_core_silabs_multiprotocol application
23-04-04 21:06:19 INFO (SyncWorker_5) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-silabs-multiprotocol with version 1.0.2
```

thank you

**Comment by agners** [comment]
@mbay0r can you enable debug logging from the Terminal (e.g. SSH & Terminal add-on):

```
ha supervisor options --logging debug
```

Then go to the add-on, change the log level, press Save, then check the Supervisor log again?

You should see something along the lines of:
```
23-04-06 16:20:12 DEBUG (MainThread) [supervisor.api.middleware.security] /addons/core_silabs_multiprotocol/options access from Home Assistant
```

**Comment by agners** [comment]
Also, can you press the tripple dot menu on the top right, and select "Edit in YAML", and share that configuration here?

**Comment by mbay0r** [comment]
23-04-06 17:57:43 DEBUG (SyncWorker_6) [supervisor.plugins.dns] Removing host entry 172.30.32.1 - ['core-silabs-multiprotocol', 'core-silabs-multiprotocol.local.hass.io']
23-04-06 17:57:43 INFO (SyncWorker_6) [supervisor.docker.interface] Stopping addon_core_silabs_multiprotocol application
23-04-06 17:57:44 DEBUG (MainThread) [supervisor.utils.dbus] Property change for org.freedesktop.NetworkManager-/org/freedesktop/NetworkManager: ['Devices'] changed & [] invalidated
23-04-06 17:57:44 DEBUG (MainThread) [supervisor.utils.dbus] Property change for org.freedesktop.NetworkManager-/org/freedesktop/NetworkManager: ['AllDevices'] changed & [] invalidated
23-04-06 17:57:48 DEBUG (MainThread) [supervisor.bus] Fire event 'BusEvent.DOCKER_CONTAINER_STATE_CHANGE' with 'DockerContainerStateEvent(name='addon_core_silabs_multiprotocol', state=<ContainerState.STOPPED: 'stopped'>, id='6d148ba3a990f68b8b15c40f43027ff118ff9ada1e62737492be005223ff10e8', time=1680796668)'
23-04-06 17:57:48 DEBUG (MainThread) [supervisor.homeassistant.websocket] Sending: {'type': <WSType.SUPERVISOR_EVENT: 'supervisor/event'>, 'data': {'event': <WSEvent.ADDON: 'addon'>, 'slug': 'core_silabs_multiprotocol', 'state': <AddonState.STOPPED: 'stopped'>}, 'id': 36}
23-04-06 17:57:48 DEBUG (MainThread) [supervisor.homeassistant.websocket] Received: WSMessage(type=<WSMsgType.TEXT: 1>, data='{"id":36,"type":"result","success":true,"result":null}', extra='')
23-04-06 17:57:48 INFO (SyncWorker_6) [supervisor.docker.interface] Cleaning addon_core_silabs_multiprotocol application
23-04-06 17:57:49 DEBUG (MainThread) [supervisor.addons.addon] Add-on core_silabs_multiprotocol write options: {'device': '/dev/ttyUSB0', 'baudrate': '460800', 'flow_control': True, 'autoflash_firmware': True, 'cpcd_trace': False, 'otbr_enable': True, 'otbr_log_level': 'notice', 'otbr_firewall': True}
23-04-06 17:57:49 DEBUG (MainThread) [supervisor.bus] Fire event 'BusEvent.DOCKER_CONTAINER_STATE_CHANGE' with 'DockerContainerStateEvent(name='addon_core_silabs_multiprotocol', state=<ContainerState.RUNNING: 'running'>, id='1e263a749e02c676ae3f7b0090bfa42b796932911896d02be9bc48e9fc3227c2', time=1680796669)'
23-04-06 17:57:49 INFO (SyncWorker_5) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-silabs-multiprotocol with version 1.1.1
23-04-06 17:57:49 DEBUG (SyncWorker_5) [supervisor.plugins.dns] Add Host entry 172.30.32.1 -> ['core-silabs-multiprotocol', 'core-silabs-multiprotocol.local.hass.io']
23-04-06 17:57:49 DEBUG (MainThread) [supervisor.homeassistant.websocket] Sending: {'type': <WSType.SUPERVISOR_EVENT: 'supervisor/event'>, 'data': {'event': <WSEvent.ADDON: 'addon'>, 'slug': 'core_silabs_multiprotocol', 'state': <AddonState.STARTED: 'started'>}, 'id': 37}
23-04-06 17:57:49 DEBUG (MainThread) [supervisor.homeassistant.websocket] Received: WSMessage(type=<WSMsgType.TEXT: 1>, data='{"id":37,"type":"result","success":true,"result":null}', extra='')
23-04-06 17:57:49 DEBUG (MainThread) [supervisor.api.middleware.security] /addons/core_silabs_multiprotocol/info access from Home Assistant
23-04-06 17:57:49 DEBUG (MainThread) [supervisor.api.middleware.security] Passthrough /app/frontend_latest/402e1dc3.js
23-04-06 17:57:50 DEBUG (MainThread) [supervisor.api.middleware.security] Passthrough /addons/self/options/config from core_silabs_multiprotocol
23-04-06 17:57:50 DEBUG (MainThread) [supervisor.api.middleware.security] Passthrough /addons/self/info from core_silabs_multiprotocol
23-04-06 17:57:51 DEBUG (MainThread) [supervisor.api.middleware.security] Passthrough /supervisor/ping
23-04-06 17:57:51 DEBUG (MainThread) [supervisor.api.middleware.security] Passthrough /info from core_silabs_multiprotocol
23-04-06 17:57:53 DEBUG (MainThread) [supervisor.api.middleware.security] /backups access from Home Assistant
23-04-06 17:57:53 DEBUG (MainThread) [supervisor.api.middleware.security] /host/info access from Home Assistant
23-04-06 17:57:54 DEBUG (MainThread) [supervisor.api.middleware.security] /addons access from Home Assistant
23-04-06 17:57:57 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_silabs_multiprotocol
23-04-06 17:57:58 DEBUG (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from Home Assistant
23-04-06 17:57:58 DEBUG (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from Home Assistant
23-04-06 17:57:59 DEBUG (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from Home Assistant
23-04-06 17:57:59 DEBUG (MainThread) [supervisor.utils.dbus] Property change for org.freedesktop.UDisks2-/org/freedesktop/UDisks2/block_devices/vda3: ['MountPoints'] changed & [] invalidated
23-04-06 17:57:59 DEBUG (MainThread) [supervisor.utils.dbus] Property change for org.freedesktop.UDisks2-/org/freedesktop/UDisks2/block_devices/vda3: ['MountPoints'] changed & [] invalidated
23-04-06 17:57:59 DEBUG (MainThread) [supervisor.bus] Fire event 'BusEvent.DOCKER_CONTAINER_STATE_CHANGE' with 'DockerContainerStateEvent(name='addon_core_silabs_multiprotocol', state=<ContainerState.HEALTHY: 'healthy'>, id='1e263a749e02c676ae3f7b0090bfa42b796932911896d02be9bc48e9fc3227c2', time=1680796679)'
23-04-06 17:58:00 DEBUG (MainThread) [supervisor.utils.dbus] Property change for org.freedesktop.NetworkManager-/org/freedesktop/NetworkManager: ['AllDevices'] changed & [] invalidated
23-04-06 17:58:00 DEBUG (MainThread) [supervisor.utils.dbus] Property change for org.freedesktop.NetworkManager-/org/freedesktop/NetworkManager: ['Devices'] changed & [] invalidated
23-04-06 17:58:00 DEBUG (MainThread) [supervisor.api.middleware.security] Passthrough /discovery from core_silabs_multiprotocol
23-04-06 17:58:00 DEBUG (MainThread) [supervisor.discovery] Duplicate discovery message from core_silabs_multiprotocol

**Comment by mbay0r** [comment]
```
device: >-
  /dev/serial/by-id/usb-Nabu_Casa_SkyConnect_v1.0_44ed41105e43ed11925747ab2a61ed69-if00-port0
baudrate: "460800"
flow_control: true
autoflash_firmware: true
cpcd_trace: false
otbr_enable: true
otbr_log_level: notice
otbr_firewall: true

```

thank you very much!

**Comment by agners** [comment]
So you've been able to resolve it by adding  `otbr_log_level` manually?

**Comment by mbay0r** [comment]
No, I did not add anything. I think it was added by saving. 

But the error is still there, every night the addon crashes and won't start. I then have to save and restart again.

**Comment by agners** [comment]
And the start fails with that same error?

```
[07:18:20] FATAL: Unknown otbr_log_level: null
[07:18:20] INFO: otbr-agent ended with exit code 1 (signal 0)...
```

**Comment by mbay0r** [comment]
yes, its always the same error. :-(

**Comment by agners** [comment]
This feels very weird. This sounds like your QNAP is restoring a old snapshot of the VM or something.

**Comment by mbay0r** [comment]
I think so too! That can not be and is unfortunately not so. Especially since then the complete virtual machine would be affected and not only this addon.

**Comment by mbay0r** [comment]
Actually, the addon should also stay off, after a crash:

![image](https://user-images.githubusercontent.com/120255277/230441519-5e3ead89-8aa3-4a95-ba6b-efe8c15b1dc1.png)

```
[core-ssh ~]$ uptime
 18:34:54 up 3 days, 20:49,  0 users,  load average: 0.02, 0.19, 0.17
```

Unfortunately, the addon hangs in a reboot loop and writes the log full non-stop, so I can't see what caused the crash.

Is there a way to expand the log buffer or save it to a file?

**Comment by mbay0r** [comment]
Thank you for all your effort. The problem is solved, I reinstalled everything yesterday. Now it seems to work. Happy Easter !
