### ISSUE TITLE
Mqtt broker does not show up in integrations as indicated in documentation

### ISSUE THREAD

**Issue by enterNameHere** [home-assistant/addons#2936]
### Describe the issue you are experiencing

Started mosquitto addon. After it ran, was instructed to add user from ha.  Did so.  Then instructed to go to settings-devices-integrations.  Mqtt will show up there as new integration.  One click install.

this does not happen.  There is nothing appearing there.

please advise?

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Mosquitto broker

### What is the version of the add-on?

6.1.3

### Steps to reproduce the issue

1.install mosquitto from addons, then start it
2.add user from ha
3.go to devices integrations - find no mqtt there
...

### System Health information

Currently no repairs

### Anything in the Supervisor logs that might be useful for us?

```txt
Home Assistant Core


Failed to to call /addons/core_mosquitto/restart - Can't create container from addon_core_mosquitto: 409 Client Error for http+docker://localhost/v1.41/containers/create?name=addon_core_mosquitto: Conflict ("Conflict. The container name "/addon_core_mosquitto" is already in use by container "bce2591f7b856e0bf27419554cc86df4334c728164be136ea00e0ae4c6ae0e5e". You have to remove (or rename) that container to be able to reuse that name.")
8:59:32 PM – (ERROR) Home Assistant Supervisor
:0:0 Script error.
8:56:53 PM – (ERROR) components/system_log/__init__.py - message first occurred at 8:42:52 PM and shows up 2 times
Error fetching yamaha_musiccast data:
8:25:32 PM – (ERROR) MusicCast
[Scrap Room speaker(10.0.0.112):8009] Failed to connect to service ServiceInfo(type='host', data=('10.0.0.112', 8009)), retrying in 5.0s
8:25:12 PM – (ERROR) /usr/local/lib/python3.10/site-packages/pychromecast/socket_client.py
[Scrap Room speaker(10.0.0.112):8009] Heartbeat timeout, resetting connection
8:24:42 PM – (WARNING) /usr/local/lib/python3.10/site-packages/pychromecast/socket_client.py
Ended unfinished session (id=5 from 2023-03-23 18:32:25.798302)
7:06:15 PM – (WARNING) Recorder
The system could not validate that the sqlite3 database at //config/home-assistant_v2.db was shutdown cleanly
7:06:15 PM – (WARNING) Recorder
 
CLEAR
```

**Comment by rokam** [comment]
https://my.home-assistant.io/redirect/server_controls/
Restart the home assistant and MQQT will appear as discovered integration.
https://my.home-assistant.io/redirect/integrations/

**Comment by enterNameHere** [comment]
> https://my.home-assistant.io/redirect/server_controls/
> Restart the home assistant and MQQT will appear as discovered integration.
> https://my.home-assistant.io/redirect/integrations/

🤦‍♂️

Thank you so much 😊

**Comment by am11r** [comment]
Hi,
sorry to come back here but I have the same problem. restart HA then Mosquitto, or only HA, I tried a lot of things, but mqtt never showing it. if I try to add manually it I don't know what to indicate in "borker*" forms:
![Capture d’écran 2023-09-04 à 19 51 10](https://github.com/home-assistant/addons/assets/72324894/fb7301e6-c280-45d6-be18-8769ded64732)
![Capture d’écran 2023-09-04 à 19 51 18](https://github.com/home-assistant/addons/assets/72324894/0e23a5d4-3a56-4f45-bc9c-cc7c568068a1)

thanks for help

**Comment by Quent2638** [comment]
> Hi, sorry to come back here but I have the same problem. restart HA then Mosquitto, or only HA, I tried a lot of things, but mqtt never showing it. if I try to add manually it I don't know what to indicate in "borker*" forms: ![Capture d’écran 2023-09-04 à 19 51 10](https://user-images.githubusercontent.com/72324894/266106549-fb7301e6-c280-45d6-be18-8769ded64732.png) ![Capture d’écran 2023-09-04 à 19 51 18](https://user-images.githubusercontent.com/72324894/266106567-0e23a5d4-3a56-4f45-bc9c-cc7c568068a1.png)
> 
> thanks for help

Hi,
I have the same problem, did you find a solution?
THANKS

**Comment by am11r** [comment]
> > Hi, sorry to come back here but I have the same problem. restart HA then Mosquitto, or only HA, I tried a lot of things, but mqtt never showing it. if I try to add manually it I don't know what to indicate in "borker*" forms: ![Capture d’écran 2023-09-04 à 19 51 10](https://user-images.githubusercontent.com/72324894/266106549-fb7301e6-c280-45d6-be18-8769ded64732.png) ![Capture d’écran 2023-09-04 à 19 51 18](https://user-images.githubusercontent.com/72324894/266106567-0e23a5d4-3a56-4f45-bc9c-cc7c568068a1.png)
> > thanks for help
> 
> Hi, I have the same problem, did you find a solution? THANKS

Hi,
In first form i wrote « homeassistant » which is the link with my HA
Second one: 1883
Third and fourth : the login/password i created in HA for mqtt
Hope it will help you

**Comment by Quent2638** [comment]
> > > Hi, sorry to come back here but I have the same problem. restart HA then Mosquitto, or only HA, I tried a lot of things, but mqtt never showing it. if I try to add manually it I don't know what to indicate in "borker*" forms: ![Capture d’écran 2023-09-04 à 19 51 10](https://user-images.githubusercontent.com/72324894/266106549-fb7301e6-c280-45d6-be18-8769ded64732.png) ![Capture d’écran 2023-09-04 à 19 51 18](https://user-images.githubusercontent.com/72324894/266106567-0e23a5d4-3a56-4f45-bc9c-cc7c568068a1.png)
> > > thanks for help
> > 
> > 
> > Hi, I have the same problem, did you find a solution? THANKS
> 
> Hi, In first form i wrote « homeassistant » which is the link with my HA Second one: 1883 Third and fourth : the login/password i created in HA for mqtt Hope it will help you

Super!
Thanks.
