### ISSUE TITLE
High CPU load

### ISSUE THREAD

**Issue by klaus1956** [home-assistant/addons#2937]
### Describe the issue you are experiencing

Since yesterday I found my NUC i5 on very high load:
CPU: 1..2%  --> ~ 13%
Temparature: 30°C --> >50°C
Consumption: 10W --> 25W

In the AddOn I found that the CPU-Load of this Addon was constantly above 10% - After stopping the AddOn all Data went back to normal

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Silicon Labs Multiprotocol

### What is the version of the add-on?

1.0.2.

### Steps to reproduce the issue

1. I am not aware of any changes
2. High load started yesterday 12:20 and ended by stopping this AddOn
3.
4.
...

### System Health information

No Repairs shown

### Anything in the Supervisor logs that might be useful for us?

```txt
"Silicon" not mentzioned in Logs
```

### Anything in the add-on logs that might be useful for us?

```txt
n/a
```

### Additional information

Intel NUC 11/i5 32GB & 1TB Samsung SSD 980

**Comment by MattWestb** [comment]
Some times mDNS is having problem and is is eating one CPU in my test systems.
Restart Silabs addon and look if the CPU is going up agen or if it sating low and if you have possibility looking what poses with htop that is doing it wold being great.

**Comment by klaus1956** [comment]
Worked for the Moment - thank you

**Comment by MattWestb** [comment]
I think its somthing bad in mDNS or in the addon. 
I was seen it many times before then i was having 3 OTBR running and they was fighting to have the normal DNS name for the OTBR but i have disabling 2 of them so only is having 1 that is doing the mesh routing and the thread network is super stable with my EVE power plugs is reporting power very nice and the Nanoleaf light is super fast reacting :-))

**Comment by un-listed** [comment]
Same Problem here. Happens every few days, resolves after a plugin restart. Any Idea how to debug this problem?

**Comment by klaus1956** [comment]
My be its paranoya, but yesterday I found again a high CPU load, but it was not the Silabs-AddOn. It was the very updated last version of the Matter update.

Is it possible that these problems are linked somehow?

**Comment by MattWestb** [comment]
Can you diving in the host system CLI and running `htop` ?
I was not getting problem then updating Matter update but both is using mDNS in the host system but is interesting what is using 100% of one CPU in the system.

**Comment by klaus1956** [comment]
I'm afraid I ned some "diving help" - my SSH-capabilities just send me to the HA-System and this does not recognize "htop".
Can you share a link how to reach the right SSH-Prompt please

**Comment by MattWestb** [comment]
Im sorry i only running container and suprevicred and can shh to the host OS and i think its not possible with HAOS and you cant getting the perhaps the device is knowing one way getting witch posses is burning one CPU.

**Comment by simoautio** [comment]
I have the same issue. When restarting the home assistant add-on, for some time it consumes ~0% cpu and after some time it jumps to around 20%. I'd like to help in debugging if I can --> @MattWestb, are you requesting to see the (h)top from the home assistant system, or should i try to log into the container and run command there?

**Comment by si458** [comment]
im having the exact same issue, Rpi 4 1GB model, after a period of time the CPU goes up to 25% (1 core)
I ended up making an automation which watches the cpu of the addon and if its above 15% for 30mins then restart the add-on and notify me
i get about 6 alerts a day,
whats even weirder, i have NOTHING connected at all! no zigbee devices, no thread devices, no z-wave devices, nothing!
i bought the skyconnect to use as my zigbee dongle but havent gotten round to buying zigbee devices yet, but its all setup and running ready to go

**Comment by mikefrantz** [comment]
> im having the exact same issue, Rpi 4 1GB model, after a period of time the CPU goes up to 25% (1 core)
> I ended up making an automation which watches the cpu of the addon and if its above 15% for 30mins then restart the add-on and notify me
> i get about 6 alerts a day,
> whats even weirder, i have NOTHING connected at all! no zigbee devices, no thread devices, no z-wave devices, nothing!
> i bought the skyconnect to use as my zigbee dongle but havent gotten round to buying zigbee devices yet, but its all setup and running ready to go

**Comment by mikefrantz** [comment]
I had the same problem with my CPU usage. Can you give me an example of your automation to turn off silicon labs and turn it back on again please?
