### ISSUE TITLE
[zwave JS] Fibaro rollershutter 3 stops working with version 0.1.77

### ISSUE THREAD

**Issue by ljsquare** [home-assistant/addons#2939]
### Describe the issue you are experiencing

After updating the add-on to version 0.1.77 the Fibaro Rollershutter 3 won't respond to any commands. According to the status it is recognised and alive.
I revert back to 0.1.76 and I don't have any issues.  

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Z-Wave JS

### What is the version of the add-on?

0.1.77

### Steps to reproduce the issue

1. update to 0.1.77
2. control cover with up/down
3. no reaction
...

### System Health information

none

### Anything in the add-on logs that might be useful for us?

```txt
2023-03-27T09:16:44.016Z CNTRLR   [Node 043] Timed out while waiting for a response from the node (ZW0201)
Z-Wave error ZWaveError: Cannot check for firmware updates for node 43: Failed to query fingerprint from the node! (ZW0260)
    at ZWaveController.getAvailableFirmwareUpdates (/usr/src/node_modules/zwave-js/src/lib/controller/Controller.ts:5742:10)
    at Function.handle (/usr/src/node_modules/@zwave-js/server/dist/lib/controller/message_handler.js:205:30)
    at Client.receiveMessage (/usr/src/node_modules/@zwave-js/server/dist/lib/server.js:106:62) {
  code: 260,
  context: undefined,
  transactionSource: undefined
}
```

**Comment by MartinHjelmare** [comment]
@raman325 any idea?

**Comment by raman325** [comment]
not sure - one thing to try would be to switch to the Z-Wave JS UI addon and to try controlling the device from the UI panel. If it works, it's an HA problem, if it doesn't, then it's a zwave-js problem

**Comment by raman325** [comment]
@AlCalzone is this something you have heard or seen in any reports?

**Comment by AlCalzone** [comment]
No. I'd start by re-interviewing the device.
