### ISSUE TITLE
Problem after upgrade  mosquito broker to  6.2.0 - bridge with Supla - no auto-updates

### ISSUE THREAD

**Issue by bdkacz** [home-assistant/addons#2945]
### Describe the issue you are experiencing

Hi. 

After upgrade of mosquitto broker to 6.2.0 the bridge with Supla (configured as describe dhere https://drive.google.com/file/d/10HTT6juRks7OcmRl10u9WWjwdMPKQwb3/view)  stop working - it get data only on start of broker and no auto update of sensor values.

Temporary solution is to set  debug: true in mosquito broker configuration - after this it work correctly

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Mosquitto broker

### What is the version of the add-on?

6.2.0

### Steps to reproduce the issue

1. Upgrade to 6.2.0
2. Start integration
3.
...

## System Information

version | core-2023.3.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.10
os_name | Linux
os_version | 5.15.90
arch | x86_64
timezone | Europe/Warsaw
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4677
Installed Version | 1.31.0
Stage | running
Available Repositories | 1250
Downloaded Repositories | 21

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.03.2
agent_version | 1.4.1
docker_version | 20.10.22
disk_total | 95.8 GB
disk_used | 16.3 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.5.0), Home Assistant Google Drive Backup (0.110.3), Samba share (10.0.0), Let's Encrypt (4.12.8), Mosquitto broker (6.2.0), Log Viewer (0.14.0), Check Home Assistant configuration (3.11.0), Node-RED (14.1.1), NGINX Home Assistant SSL proxy (3.2.0), ESPHome (2023.3.2), Samba Backup (5.2.0), Zigbee2MQTT (1.30.2-1), SSH & Web Terminal (13.1.0), Wmbusmeters (W-MBus to MQTT) (1.10.2), AdGuard Home (4.8.3)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 14
views | 10
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 28 grudnia 2022 03:45
-- | --
current_recorder_run | 28 marca 2023 10:08
estimated_db_size | 19930.66 MiB
database_engine | mysql
database_version | 10.5.18

</details>

<details><summary>Xiaomi Miot Auto</summary>

component_version | 0.7.7
-- | --
can_reach_server | pending
can_reach_spec | ok
logged_accounts | 1
total_devices | 13

</details>

**Comment by dsl10007** [comment]
After updating to 6.2.0 my integration with the "Solar Assistant" also stopped working. 

All i get now is "unknown" as the value for all sensors.

**Comment by convicte** [comment]
I believe it's a general unseen loss of communication because for me it happens both for Supla and Accurite2MQTT addon, though, it did happen for Supla twice but for A2M only once.

**Comment by MnM001** [comment]
My HiSense TV integration is also broken after upgrading to 6.2.0
TV Sensor now shows Unavailable.
It worked perfectly before the 6.2.0 upgrade.

**Comment by haarkop** [comment]
with me, after the automatic update, the connection to the Supli bridge also fails.

**Comment by PelonVela** [comment]
After updating to 6.2.0 my Sdomotica BTicino Living Now addon stopped reporting Outlet Power consumption. I can control my lights and outlets (ON/OFF) but no power consumption data is reported. I rolled back to 6.1.3 to have that data at the moment.

**Comment by Taronaga** [comment]
After updating to 6.2.0, some MQTT devices, in particular MegaD - 2561, stopped working.

**Comment by ChristoffBo** [comment]
Same for me SolarAssistant stopped working, have to restart the broker addon after rebooting HA.

**Comment by Taronaga** [comment]
It didn’t help me. I restarted the system several times, also restarted MegaD. Without result. MQTT doesn’t work. After rolling back to 6.1.3 everything becomes normal. All lighting and all sockets are tied to this device, other devices have not been checked. Builds on esp also stopped working.

**Comment by phinor** [comment]
> After updating to 6.2.0 my integration with the "Solar Assistant" also stopped working.
> 
> All i get now is "unknown" as the value for all sensors.

Experienced the same. Oddly, rebooting seems to help. However, it appears that it only works every second reboot - which sounds bizarre...

**Comment by Taronaga** [comment]
After upgrading to operating system 10.0, MQTT version 6.1.3 and even stopped working ..... and version 6.2.0 did not work for me. I do not know what to do :(

**Comment by GuGu927** [comment]
When addon prints this log
"**error: received null username, clientid or topic, or access is equal or less than 0 for acl check**"

add keepalive option when connect to broker.
connect param must contain userid, password, keepalive value.

I don't want to see that logs ... I can not handle connect option with some devices because device firmware does not support add keetalive option.

**Comment by matrixthecat** [comment]
Hi, i have same issue with espresense. It cannot connect to mosquitto (home-assistant)
I have created a local user and reconfigured esp32 to mosquitto account  and now no problem!

**Comment by jackkitley** [comment]
I have the same issue with solar assistant. @ChristoffBo @dsl10007 .

When rebooting i need to restart the mqtt add on to have solar assistant send data.

**Comment by dsl10007** [comment]
> I have the same issue with solar assistant. @ChristoffBo @dsl10007 .
> 
> When rebooting i need to restart the mqtt add on to have solar assistant send data.

Does this still work.

Mine was working like this for a while, but now it will not show any Solar Assistant data, even if i restart MQTT after a reboot ?

**Comment by jackkitley** [comment]
Still same issue. Happened after mqtt update
