### ISSUE TITLE
After upgrading to latest docker container 6.2.0 on a pi4 running aarch64, libraries libcares.so.2 and libcjson.so.1 are missing

### ISSUE THREAD

**Issue by rlehfeld** [home-assistant/addons#2948]
### Describe the issue you are experiencing

Dear all,
since my system updated to 6.2.0, some libraries, e.g. libcares.so.2 and libcjson.so.1 are missing within the mosquitto docker container. Due to that I get for example following errors:

root@core-mosquitto:/# mosquitto_sub
mosquitto_sub: error while loading shared libraries: libcjson.so.1: cannot open shared object file: No such file or directory
root@core-mosquitto:/# mosquitto_pub
mosquitto_pub: error while loading shared libraries: libcares.so.2: cannot open shared object file: No such file or directory

This makes it also impossible to run my own compiled mosquitto plugins any longer within the mosquitto container as libmosquitto.so.1 is missing libraries as well.

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### Which add-on are you reporting an issue with?

Mosquitto broker

### What is the version of the add-on?

6.2.0

### Steps to reproduce the issue

1. docker exec -it addon_core_mosquitto bash
2. mosquitto_sub
mosquitto_sub: error while loading shared libraries: **libcjson.so.1**: cannot open shared object file: No such file or directory
3. mosquitto_pub
mosquitto_pub: error while loading shared libraries: **libcares.so.2**: cannot open shared object file: No such file or directory
4. ldd /usr/local/lib/libmosquitto.so.1
        linux-vdso.so.1 (0x0000007f9b24e000)
        libssl.so.1.1 => /usr/lib/aarch64-linux-gnu/libssl.so.1.1 (0x0000007f9b157000)
        libcrypto.so.1.1 => /usr/lib/aarch64-linux-gnu/libcrypto.so.1.1 (0x0000007f9aea7000)
        **libcares.so.2 => not found**
        libpthread.so.0 => /lib/aarch64-linux-gnu/libpthread.so.0 (0x0000007f9ae76000)
        libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000007f9ad01000)
        /lib/ld-linux-aarch64.so.1 (0x0000007f9b21e000)
        libdl.so.2 => /lib/aarch64-linux-gnu/libdl.so.2 (0x0000007f9aced000)

## System Information

version | core-2023.3.6
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.10
os_name | Linux
os_version | 5.15.84-v8+
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.31.0
Stage | running
Available Repositories | 1314
Downloaded Repositories | 3

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 11 (bullseye)
-- | --
update_channel | stable
supervisor_version | supervisor-2023.03.3
agent_version | 1.4.1
docker_version | 23.0.1
disk_total | 29.1 GB
disk_used | 20.3 GB
healthy | true
supported | true
supervisor_api | ok
version_api | ok
installed_addons | ESPHome (2023.3.2), TasmoAdmin (0.24.0), Mosquitto broker (6.2.0), Nextcloud Backup (0.17.7), NGINX Home Assistant SSL proxy (3.2.0), AdGuard Home (4.8.3)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 0
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 21. März 2023 um 12:21
-- | --
current_recorder_run | 24. März 2023 um 02:56
estimated_db_size | 1466.70 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

**Comment by rlehfeld** [comment]
here now the proper system health informaion:

## System Information

version | core-2023.3.6
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.10
os_name | Linux
os_version | 5.15.84-v8+
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.31.0
Stage | running
Available Repositories | 1314
Downloaded Repositories | 3

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 11 (bullseye)
-- | --
update_channel | stable
supervisor_version | supervisor-2023.03.3
agent_version | 1.4.1
docker_version | 23.0.1
disk_total | 29.1 GB
disk_used | 20.3 GB
healthy | true
supported | true
supervisor_api | ok
version_api | ok
installed_addons | ESPHome (2023.3.2), TasmoAdmin (0.24.0), Mosquitto broker (6.2.0), Nextcloud Backup (0.17.7), NGINX Home Assistant SSL proxy (3.2.0), AdGuard Home (4.8.3)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 0
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 21. März 2023 um 12:21
-- | --
current_recorder_run | 24. März 2023 um 02:56
estimated_db_size | 1466.70 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

**Comment by agners** [comment]
Closed with #2987.
