### ISSUE TITLE
Lets encrypt fails to detect new hostnames

### ISSUE THREAD

**Issue by rbray89** [home-assistant/addons#2955]
### Describe the issue you are experiencing

The let's encrypt addon should force renewal when the list of hostnames changes, not relying just on old cert date.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Let's Encrypt

### What is the version of the add-on?

4.12.8

### Steps to reproduce the issue

Alter hostnames
Restart addon
See that new hostnames are not accounted for.
https://my.home-assistant.io/redirect/system_health/

## System Information

version | core-2023.3.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.10
os_name | Linux
os_version | 5.15.90
arch | x86_64
timezone | America/Denver
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4900
Installed Version | 1.31.0
Stage | running
Available Repositories | 1247
Downloaded Repositories | 7

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.03.3
agent_version | 1.4.1
docker_version | 20.10.22
disk_total | 30.8 GB
disk_used | 5.6 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Studio Code Server (5.5.5), ESPHome (2023.3.2), Let's Encrypt (4.12.8), NGINX Home Assistant SSL proxy (3.2.0), Mosquitto broker (6.2.0), go2rtc (1.3.1), RTSPtoWebRTC (1.0.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 4
views | 2
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | March 21, 2023 at 7:24 AM
-- | --
current_recorder_run | March 28, 2023 at 11:30 AM
estimated_db_size | 8.96 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

### Anything in the add-on logs that might be useful for us?

```txt
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/file-structure.sh
cont-init: info: /etc/cont-init.d/file-structure.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun lets-encrypt (no readiness notification)
s6-rc: info: service legacy-services successfully started
[22:55:35] INFO: Selected DNS Provider: dns-cloudflare
[22:55:35] INFO: Use propagation seconds: 60
[22:55:35] INFO: Use CloudFlare token
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Certificate not yet due for renewal
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Certificate not yet due for renewal; no action taken.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by marcelhoogantink** [comment]
This issue is still active

**Comment by marcelhoogantink** [comment]
Still not solved
