### ISSUE TITLE
Failing installing Silicon Labs Flasher Add-on ARM 32 and 64

### ISSUE THREAD

**Issue by MattWestb** [home-assistant/addons#2957]
### Describe the issue you are experiencing

A armbian 32 and one 64 but machine:
```
Failed to install add-on
Can't install homeassistant/armv7-addon-silabs-flasher:0.1.1: 404 Client Error for http+docker://localhost/v1.42/images/create?tag=0.1.1&fromImage=homeassistant%2Farmv7-addon-silabs-flasher&platform=linux%2Farm%2Fv7: Not Found ("manifest for homeassistant/armv7-addon-silabs-flasher:0.1.1 not found: manifest unknown: manifest unknown")

Failed to install add-on
Can't install homeassistant/aarch64-addon-silabs-flasher:0.1.1: 404 Client Error for http+docker://localhost/v1.42/images/create?tag=0.1.1&fromImage=homeassistant%2Faarch64-addon-silabs-flasher&platform=linux%2Farm64: Not Found ("manifest for homeassistant/aarch64-addon-silabs-flasher:0.1.1 not found: manifest unknown: manifest unknown")
``` 

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### Which add-on are you reporting an issue with?

Silicon Labs Flasher

### What is the version of the add-on?

0.1,1,

### Steps to reproduce the issue

1.
2.
3.
...

## System Information

version | core-2023.3.4
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.10
os_name | Linux
os_version | 5.15.93-sunxi
arch | armv7l
timezone | Europe/Vienna
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Armbian 23.02.2 Jammy
-- | --
update_channel | stable
supervisor_version | supervisor-2023.03.3
agent_version | 1.4.1
docker_version | 23.0.1
disk_total | 55.9 GB
disk_used | 8.6 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | Alsa & PulseAudio Fix (3.4.1), File editor (5.5.0), Silicon Labs Multiprotocol (1.0.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 1
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | March 24, 2023 at 13:33
-- | --
current_recorder_run | March 31, 2023 at 07:47
estimated_db_size | 89.20 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

## System Information

version | core-2023.3.4
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.10
os_name | Linux
os_version | 6.1.11-rk322x
arch | armv7l
timezone | Europe/Vienna
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Armbian 23.02.2 Jammy
-- | --
update_channel | stable
supervisor_version | supervisor-2023.03.3
agent_version | 1.4.1
docker_version | 23.0.1
disk_total | 7.0 GB
disk_used | 4.4 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.5.0), Alsa & PulseAudio Fix (3.4.1), Silicon Labs Multiprotocol (1.0.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 1
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | March 23, 2023 at 09:32
-- | --
current_recorder_run | March 26, 2023 at 16:05
estimated_db_size | 95.29 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

## System Information

version | core-2023.3.0
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.10
os_name | Linux
os_version | 5.15.103-rockchip64
arch | aarch64
timezone | Europe/Vienna
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Armbian 23.02.2 Jammy
-- | --
update_channel | stable
supervisor_version | supervisor-2023.03.3
agent_version | 1.4.1
docker_version | 23.0.1
disk_total | 28.2 GB
disk_used | 14.2 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.5.0), HyperHDR (19.0.0.0), Matter Server (4.2.0), Silicon Labs Multiprotocol (1.0.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 1
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | March 26, 2023 at 13:18
-- | --
current_recorder_run | March 31, 2023 at 00:14
estimated_db_size | 108.08 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

**Comment by MattWestb** [comment]
Silicon Labs Flasher is not possible selecting in the trample so i was patching it later.

**Comment by MattWestb** [comment]
10 hours later and all 3 is installing OK but have not testing flashing new RCP on the test systems then im not sure where and how putting local firmware files in the system and getting it working OK

**Comment by agners** [comment]
> 10 hours later and all 3 is installing OK

The first build somehow failed, only with the second build the add-ons got actually uploaded.

> but have not testing flashing new RCP on the test systems then im not sure where and how putting local firmware files in the system and getting it working OK

This is currently not possible. I keep it in mind for a future update.
