### ISSUE TITLE
Configuration for MariaDB add on not possible through web interface – 2023.04b5

### ISSUE THREAD

**Issue by thatslolo** [home-assistant/addons#2966]
### Describe the issue you are experiencing

When installing the MariaDB add on I'm not able to set user und password in web interface.
The result is that I'm not able to start the add on.

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### Which add-on are you reporting an issue with?

MariaDB

### What is the version of the add-on?

Current version: 2.5.2

### Steps to reproduce the issue

1. install add on 
2. try to set up user

## System Information

version | core-2023.4.0b5
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.10
os_name | Linux
os_version | 5.10.110
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.31.0
Stage | waiting
Available Repositories | 1254
Downloaded Repositories | 31

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 24 April 2023 at 02:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | false
remote_server | eu-central-1-8.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 11 (bullseye)
-- | --
update_channel | beta
supervisor_version | supervisor-2023.04.dev0101
agent_version | 1.5.1
docker_version | 23.0.2
disk_total | 457.4 GB
disk_used | 11.2 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | AirCast (3.5.2), ESPHome (2023.3.2), Grafana (8.2.1), Home Assistant Google Drive Backup (0.110.3), ICantBelieveItsNotValetudo (4.0.0), InfluxDB (4.6.0), Log Viewer (0.15.0), Matter Server (4.2.0), Mosquitto broker (6.2.0), OpenThread Border Router (1.2.0), Studio Code Server (5.5.6), Zigbee2MQTT (1.30.3-1), phpMyAdmin (0.8.5), MariaDB (2.5.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 15
views | 8
mode | storage

</details>

<details><summary>Miele</summary>

component_version | 0.1.9
-- | --
reach_miele_cloud | ok

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 3 April 2023 at 07:26
-- | --
current_recorder_run | 3 April 2023 at 10:51
estimated_db_size | 9.53 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

### Anything in the Supervisor logs that might be useful for us?

```txt
23-04-03 10:50:35 ERROR (MainThread) [supervisor.addons.addon] Add-on core_mariadb has invalid options: Missing required option 'password' in MariaDB (core_mariadb). Got {'databases': ['homeassistant'], 'logins': [{'password': None, 'username': 'homeassistant'}], 'rights': [{'database': 'homeassistant', 'username': 'homeassistant'}]}
```

**Comment by thatslolo** [comment]
![61786](https://user-images.githubusercontent.com/73950246/229461682-246dd0f8-5a3f-462e-8ccd-a23593816404.png)

**Comment by QuinnyPig** [comment]
I'm seeing the same thing in configuring LetsEncrypt; are you by any chance using Safari on an iPad as well?

**Comment by HDStremmie** [comment]
I used Safari on an iPad as well (for config MariaDB). Same thing. Changed to other OS and browser (Windows/Edge) and experienced no issues.

**Comment by thatslolo** [comment]
I'm using Safari on macOS

**Comment by thatslolo** [comment]
Can confirm that the issue doesn't happen with Brave (Chrome) on macOS

**Comment by nagashik** [comment]
I have the same problem.
Home Assistant OS
Rasberry PI5

Unable to save user. it writes to me:
Unknown error, see supervisor logs

in supervisor log I see:
Failed to to call /addons/core_mariadb/options/validate -

The password finaly just small literals. nothing more
