### ISSUE TITLE
SiLabs Multiprotocol - upgrade to version 1.1 Not coming up

### ISSUE THREAD

**Issue by tommyjlong** [home-assistant/addons#2967]
### Describe the issue you are experiencing

Upgraded to version 1.1.  Also changed the baud rate in the Add-On config to 460800
Tried shutting down the system, replugging SkyConnect, no luck. Add-On won't come up.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Silicon Labs Multiprotocol

### What is the version of the add-on?

1.1

### Steps to reproduce the issue

Upgrade to 1.1 and capture Logs.

### System Health information

```
There are currently no repairs available
```

### Anything in the Supervisor logs that might be useful for us?

```txt
23-04-04 20:03:06 WARNING (SyncWorker_3) [supervisor.addons.options] Option 'otbr_web_enable' does not exist in the schema for Silicon Labs Multiprotocol (core_silabs_multiprotocol)
23-04-04 20:03:08 INFO (SyncWorker_3) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-silabs-multiprotocol with version 1.1.0
23-04-04 20:03:08 WARNING (MainThread) [supervisor.addons.options] Option 'otbr_web_enable' does not exist in the schema for Silicon Labs Multiprotocol (core_silabs_multiprotocol)
23-04-04 20:03:09 WARNING (MainThread) [supervisor.addons.options] Option 'otbr_web_enable' does not exist in the schema for Silicon Labs Multiprotocol (core_silabs_multiprotocol)
23-04-04 20:03:28 WARNING (MainThread) [supervisor.addons.options] Option 'otbr_web_enable' does not exist in the schema for Silicon Labs Multiprotocol (core_silabs_multiprotocol)
23-04-04 20:03:28 WARNING (MainThread) [supervisor.addons.options] Option 'otbr_web_enable' does not exist in the schema for Silicon Labs Multiprotocol (core_silabs_multiprotocol)
23-04-04 20:03:28 INFO (SyncWorker_2) [supervisor.docker.interface] Cleaning addon_core_silabs_multiprotocol application
23-04-04 20:03:28 WARNING (SyncWorker_2) [supervisor.addons.options] Option 'otbr_web_enable' does not exist in the schema for Silicon Labs Multiprotocol (core_silabs_multiprotocol)
```

### Anything in the add-on logs that might be useful for us?

```txt
Here is the Log (journalctl -f | grep multipro) :

Apr 05 00:07:42 homeassistant-test addon_core_silabs_multiprotocol[356]: [20:07:42] INFO: Web UI and REST API port are exposed, starting otbr-web.
Apr 05 00:07:43 homeassistant-test addon_core_silabs_multiprotocol[356]: s6-rc: info: service mdns: starting
Apr 05 00:07:43 homeassistant-test addon_core_silabs_multiprotocol[356]: s6-rc: info: service s6rc-oneshot-runner: starting
Apr 05 00:07:43 homeassistant-test addon_core_silabs_multiprotocol[356]: s6-rc: info: service mdns successfully started
Apr 05 00:07:43 homeassistant-test addon_core_silabs_multiprotocol[356]: s6-rc: info: service s6rc-oneshot-runner successfully started
Apr 05 00:07:43 homeassistant-test addon_core_silabs_multiprotocol[356]: s6-rc: info: service fix-attrs: starting
Apr 05 00:07:43 homeassistant-test addon_core_silabs_multiprotocol[356]: s6-rc: info: service fix-attrs successfully started
Apr 05 00:07:43 homeassistant-test addon_core_silabs_multiprotocol[356]: s6-rc: info: service legacy-cont-init: starting
Apr 05 00:07:43 homeassistant-test addon_core_silabs_multiprotocol[356]: cont-init: info: running /etc/cont-init.d/check-cpcd-shm.sh
Apr 05 00:07:43 homeassistant-test addon_core_silabs_multiprotocol[356]: [20:07:43] INFO: Starting mDNS Responder...
Apr 05 00:07:43 homeassistant-test addon_core_silabs_multiprotocol[356]: Default: mDNSResponder (Engineering Build) (Apr  4 2023 22:25:27) starting
Apr 05 00:07:43 homeassistant-test addon_core_silabs_multiprotocol[356]: Default: mDNS_AddDNSServer: Lock not held! mDNS_busy (0) mDNS_reentrancy (0)
Apr 05 00:07:43 homeassistant-test addon_core_silabs_multiprotocol[356]: cont-init: info: /etc/cont-init.d/check-cpcd-shm.sh exited 0
Apr 05 00:07:43 homeassistant-test addon_core_silabs_multiprotocol[356]: s6-rc: info: service legacy-cont-init successfully started
Apr 05 00:07:43 homeassistant-test addon_core_silabs_multiprotocol[356]: s6-rc: info: service banner: starting
Apr 05 00:07:43 homeassistant-test addon_core_silabs_multiprotocol[356]: 
Apr 05 00:07:43 homeassistant-test addon_core_silabs_multiprotocol[356]: -----------------------------------------------------------
Apr 05 00:07:43 homeassistant-test addon_core_silabs_multiprotocol[356]:  Add-on: Silicon Labs Multiprotocol
Apr 05 00:07:43 homeassistant-test addon_core_silabs_multiprotocol[356]:  Zigbee and OpenThread multiprotocol add-on
Apr 05 00:07:43 homeassistant-test addon_core_silabs_multiprotocol[356]: -----------------------------------------------------------
Apr 05 00:07:43 homeassistant-test addon_core_silabs_multiprotocol[356]:  Add-on version: 1.1.0
Apr 05 00:07:43 homeassistant-test addon_core_silabs_multiprotocol[356]:  You are running the latest version of this add-on.
Apr 05 00:07:43 homeassistant-test addon_core_silabs_multiprotocol[356]:  System: Home Assistant OS 9.5  (amd64 / qemux86-64)
Apr 05 00:07:43 homeassistant-test addon_core_silabs_multiprotocol[356]:  Home Assistant Core: 2023.3.6
Apr 05 00:07:43 homeassistant-test addon_core_silabs_multiprotocol[356]:  Home Assistant Supervisor: 2023.03.3
Apr 05 00:07:43 homeassistant-test addon_core_silabs_multiprotocol[356]: -----------------------------------------------------------
Apr 05 00:07:43 homeassistant-test addon_core_silabs_multiprotocol[356]:  Please, share the above information when looking for help
Apr 05 00:07:43 homeassistant-test addon_core_silabs_multiprotocol[356]:  or support in, e.g., GitHub, forums or the Discord chat.
Apr 05 00:07:43 homeassistant-test addon_core_silabs_multiprotocol[356]: -----------------------------------------------------------
Apr 05 00:07:43 homeassistant-test addon_core_silabs_multiprotocol[356]: s6-rc: info: service banner successfully started
Apr 05 00:07:43 homeassistant-test addon_core_silabs_multiprotocol[356]: s6-rc: info: service universal-silabs-flasher: starting
Apr 05 00:07:44 homeassistant-test addon_core_silabs_multiprotocol[356]: [20:07:44] INFO: Checking /dev/ttyUSB0 identifying SkyConnect v1.0 from Nabu Casa.
Apr 05 00:07:44 homeassistant-test addon_core_silabs_multiprotocol[356]: [20:07:44] INFO: Starting universal-silabs-flasher with /dev/ttyUSB0
Apr 05 00:07:44 homeassistant-test addon_core_silabs_multiprotocol[356]: Usage: universal-silabs-flasher flash [OPTIONS]
Apr 05 00:07:44 homeassistant-test addon_core_silabs_multiprotocol[356]: Try 'universal-silabs-flasher flash --help' for help.
Apr 05 00:07:44 homeassistant-test addon_core_silabs_multiprotocol[356]: 
Apr 05 00:07:44 homeassistant-test addon_core_silabs_multiprotocol[356]: Error: No such option: --ensure-exact-version
Apr 05 00:07:44 homeassistant-test addon_core_silabs_multiprotocol[356]: s6-rc: warning: unable to start service universal-silabs-flasher: command exited 2
Apr 05 00:07:44 homeassistant-test addon_core_silabs_multiprotocol[356]: /run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
Apr 05 00:07:44 homeassistant-test addon_core_silabs_multiprotocol[356]: /run/s6/basedir/scripts/rc.init: fatal: stopping the container.
Apr 05 00:07:44 homeassistant-test addon_core_silabs_multiprotocol[356]: s6-rc: info: service mdns: stopping
Apr 05 00:07:44 homeassistant-test addon_core_silabs_multiprotocol[356]: s6-rc: info: service banner: stopping
Apr 05 00:07:44 homeassistant-test addon_core_silabs_multiprotocol[356]: Default: mDNSResponder (Engineering Build) (Apr  4 2023 22:25:27) stopping
Apr 05 00:07:44 homeassistant-test addon_core_silabs_multiprotocol[356]: s6-rc: info: service banner successfully stopped
Apr 05 00:07:44 homeassistant-test addon_core_silabs_multiprotocol[356]: s6-rc: info: service legacy-cont-init: stopping
Apr 05 00:07:44 homeassistant-test addon_core_silabs_multiprotocol[356]: s6-rc: info: service legacy-cont-init successfully stopped
Apr 05 00:07:44 homeassistant-test addon_core_silabs_multiprotocol[356]: s6-rc: info: service fix-attrs: stopping
Apr 05 00:07:44 homeassistant-test addon_core_silabs_multiprotocol[356]: s6-rc: info: service fix-attrs successfully stopped
Apr 05 00:07:44 homeassistant-test addon_core_silabs_multiprotocol[356]: [20:07:44] INFO: mDNS ended with exit code 4 (signal 0)...
Apr 05 00:07:44 homeassistant-test addon_core_silabs_multiprotocol[356]: s6-rc: info: service s6rc-oneshot-runner: stopping
Apr 05 00:07:44 homeassistant-test addon_core_silabs_multiprotocol[356]: s6-rc: info: service mdns successfully stopped
Apr 05 00:07:44 homeassistant-test addon_core_silabs_multiprotocol[356]: s6-rc: info: service s6rc-oneshot-runner successfully stopped

```
```


### Additional information

_No response_

**Comment by luisiam** [comment]
Same here. I disable `Automatically flash firmware` inside configuration and it's back online now. Something is wrong with the updated `universal-silabs-flasher`

**Comment by tommyjlong** [comment]
Seems the universal-silabs-flasher is trying to use an option not available to it `Error: No such option: --ensure-exact-version`

**Comment by luisiam** [comment]
I actually checked the source code of `universal-silabs-flasher` and the option is indeed there. Not sure what's wrong. That's beyond my knowledge

**Comment by tommyjlong** [comment]
Assuming you did a backup prior to upgrading then go to UI->System->Backups 
click on the row "addon_core_silabs_multiprotocol_1.0.2" (do not the box, but tick the row), a popup will show, then tick the box "Add-On's and click "Restore"

**Comment by luisiam** [comment]
I don’t have a backup. I think it’s good idea to always have a backup before updating lol
Disabling auto update fw works for me. I bet the devs will figure it out and push another update very soon.

**Comment by grantclem** [comment]
+1

**Comment by oekinger** [comment]
Same here -> back on 1.02 again

**Comment by SlowmoDK** [comment]
Ya im skipping this one :(

sadly untested updates seems to be happening a lot more often these days 

I really wish, we could have LTS versions ... 3-6 month STABLE releases
Yes u can test new stuff on beta versions, but i freaking hate to spend time almost daily checking every single update for breakages

**Comment by niekbruggeman** [comment]
Same here, reverted back to 1.02 this morning after waking up with the multiprotocol not starting up anymore.

With 1.1.0 im getting the error:
s6-rc: warning: unable to start service universal-silabs-flasher: command exited 1
switching "flash device" to off. 
Getting error message:  " Unable to connect to secundairy"

The release notes say: "Use default baudrate of 460800 (WARNING: You MUST update your configuration!)" 
But what to update ?

I tried all possible boudrates and restarting, with no effect.
The current config of 1.02 has no boudrate set. None of the 5 radiobuttons are checked.

**Comment by luisiam** [comment]
> Same here, reverted back to 1.02 this morning after waking up with the multiprotocol not starting up anymore.
> 
> With 1.1.0 im getting the error: s6-rc: warning: unable to start service universal-silabs-flasher: command exited 1 switching "flash device" to off. Getting error message: " Unable to connect to secundairy"
> 
> The release notes say: "Use default baudrate of 460800 (WARNING: You MUST update your configuration!)" But what to update ?
> 
> I tried all possible boudrates and restarting, with no effect. The current config of 1.02 has no boudrate set. None of the 5 radiobuttons are checked.

You will have to manually flash the 460800 baud rate firmware in order for to use the new baud rate in the configuration

**Comment by niekbruggeman** [comment]
> 

Is there an instruction online ?

**Comment by luisiam** [comment]
> > 
> 
> Thanks for your reply! Is there an instruction online ?

Follow [this guide](https://github.com/NabuCasa/silabs-firmware/wiki/Flash-Silicon-Labs-radio-firmware-manually) and use [this FW](https://github.com/NabuCasa/silabs-firmware/blob/main/RCPMultiPAN/beta/NabuCasa_SkyConnect_RCP_v4.2.2_rcp-uart-hw-802154_460800.gbl) (assumming you are using SkyConnect).

**Comment by RemCom** [comment]
@luisiam This doesnt fix the error why the addon isnt starting. The new version of the flasher isnt compatible with --ensure-exact-version flag:

[08:26:35] INFO: Checking /dev/ttyUSB1 identifying SkyConnect v1.0 from Nabu Casa.
[08:26:35] INFO: Starting universal-silabs-flasher with /dev/ttyUSB1
Usage: universal-silabs-flasher flash [OPTIONS]
Try 'universal-silabs-flasher flash --help' for help.
Error: No such option: --ensure-exact-version

**Comment by luisiam** [comment]
> Automatically flash firmware

You will also have to disable `Automatically flash firmware` in configuration

**Comment by cburghardt** [comment]
Tried:
universal-silabs-flasher --device /dev/serial/by-id/usb-Nabu_Casa_SkyConnect_v1.0_b06506090541ed1181477aa7ccf2b06c-if00-port0 flash --allow-cross-flashing --firmware silabs-firmware/RCPMultiPAN/beta/NabuCasa_SkyConnect_RCP_v4.2.2_rcp-uart-hw-802154_460800.gbl

Result:
2023-04-05 08:26:04 homeassistant universal_silabs_flasher.flash[202] INFO Extracted GBL metadata: NabuCasaMetadata(metadata_version=1, sdk_version='4.2.2', ezsp_version=None, ot_rcp_version=None, fw_type=<FirmwareImageType.RCP_UART_802154: 'rcp-uart-802154'>, baudrate=460800)
2023-04-05 08:26:04 homeassistant universal_silabs_flasher.flasher[202] INFO Probing ApplicationType.GECKO_BOOTLOADER at 115200 baud
2023-04-05 08:26:06 homeassistant universal_silabs_flasher.flasher[202] INFO Probing ApplicationType.CPC at 460800 baud
2023-04-05 08:26:10 homeassistant universal_silabs_flasher.flasher[202] INFO Probing ApplicationType.CPC at 115200 baud
2023-04-05 08:26:14 homeassistant universal_silabs_flasher.flasher[202] INFO Probing ApplicationType.CPC at 230400 baud
2023-04-05 08:26:19 homeassistant universal_silabs_flasher.flasher[202] INFO Probing ApplicationType.EZSP at 115200 baud
2023-04-05 08:26:24 homeassistant universal_silabs_flasher.flasher[202] INFO Probing ApplicationType.SPINEL at 460800 baud

**Comment by agners** [comment]
The amd64 version of the add-on accidentally installed an older version of the universal-silabs-flasher.

Fixed with #2968, add-on version 1.1.1 fixes this.

**Comment by agners** [comment]
@cburghardt hm, it seems that the flasher isn't able to talk to the SkyConnect. Can you remove and plug back in your SkyConnect?

**Comment by cburghardt** [comment]
Thanks for the hint, no idea what happened but that has solved it.

**Comment by tommyjlong** [comment]
1.1.1 is now working for me :)
For anyone else looking at this, I upgraded with the "Automatically flash firmware" enabled.  For some reason, my configuration file does not have a baud rate selected.  From the logs below, the universal_silabs_flasher will try to run at 460800, but it will discover the bootloader will run at 115200 baud and will then flash the SkyConnect.  After than it will run at 460800

```
[14:13:10] INFO: Checking /dev/ttyUSB0 identifying SkyConnect v1.0 from Nabu Casa.
[14:13:10] INFO: Starting universal-silabs-flasher with /dev/ttyUSB0
2023-04-05 14:13:11 homeassistant-test universal_silabs_flasher.flash[185] INFO Extracted GBL metadata: NabuCasaMetadata(metadata_version=1, sdk_version='4.2.2', ezsp_version=None, ot_rcp_version=None, fw_type=<FirmwareImageType.RCP_UART_802154: 'rcp-uart-802154'>, baudrate=460800)
2023-04-05 14:13:11 homeassistant-test universal_silabs_flasher.flasher[185] INFO Probing ApplicationType.GECKO_BOOTLOADER at 115200 baud
2023-04-05 14:13:13 homeassistant-test universal_silabs_flasher.flasher[185] INFO Probing ApplicationType.CPC at 460800 baud
2023-04-05 14:13:17 homeassistant-test universal_silabs_flasher.flasher[185] INFO Probing ApplicationType.CPC at 115200 baud
2023-04-05 14:13:17 homeassistant-test universal_silabs_flasher.flasher[185] INFO Detected ApplicationType.CPC, version '4.2.2' at 115200 baudrate (bootloader baudrate None)
2023-04-05 14:13:17 homeassistant-test universal_silabs_flasher.flash[185] INFO Firmware baudrate 115200 differs from expected baudrate 460800
2023-04-05 14:13:17 homeassistant-test universal_silabs_flasher.flasher[185] INFO Probing ApplicationType.GECKO_BOOTLOADER at 115200 baud
2023-04-05 14:13:17 homeassistant-test universal_silabs_flasher.flasher[185] INFO Detected bootloader version '2.1.1'
2023-04-05 14:13:17 homeassistant-test universal_silabs_flasher.flasher[185] INFO Detected ApplicationType.CPC, version '4.2.2' at 115200 baudrate (bootloader baudrate 115200)
NabuCasa_SkyConnect_RCP_v4.2.2_rcp-uart-hw-802154_460800.gbl
s6-rc: info: service universal-silabs-flasher successfully started
[14:13:40] INFO: Using known baudrate of 460800 for cpcd!
[14:13:40] INFO: Generating cpcd configuration.
 s6-rc: info: service cpcd-config successfully started
