### ISSUE TITLE
ZigBee less reliable when OTBR is enabled

### ISSUE THREAD

**Issue by jhbruhn** [home-assistant/addons#2974]
### Describe the issue you are experiencing

While using the Add-on, ZigBee messages from end devices seem to get lost if the otbr is enabled. If I disable it in the addon configuration, all messages, esp. Button presses on remotes, arrive reliably.
I have no thread or matter devices in my network.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Silicon Labs Multiprotocol

### What is the version of the add-on?

1.1.1

### Steps to reproduce the issue

1. Setup addon on HA yellow
2. Configure Zigbee2mqtt to use the zigbeed connection 
3. Make sure the OTBR is enabled
...

## System Information

version | core-2023.4.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.10
os_name | Linux
os_version | 5.15.84-v8
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.32.1
Stage | running
Available Repositories | 1337
Downloaded Repositories | 53

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.04.0
agent_version | 1.4.1
docker_version | 20.10.22
disk_total | 458.4 GB
disk_used | 41.9 GB
healthy | true
supported | true
board | yellow
supervisor_api | ok
version_api | ok
installed_addons | AdGuard Home (4.8.5), AppDaemon (0.12.0), ESPHome (2023.3.2), File editor (5.5.0), Grafana (8.2.1), MariaDB (2.5.2), Mosquitto broker (6.2.0), Node-RED (14.1.4), Samba Backup (5.2.0), Samba share (10.0.0), Studio Code Server (5.5.6), Tailscale (0.10.1), Terminal & SSH (9.6.1), TooGoodToGo Home Assistant MQTT Bridge (2.5.1.2), phpMyAdmin (0.8.5), InfluxDB (4.6.0), Zigbee2MQTT (1.30.3-1), E-Paper Screenshotter (1.0.1.35), E-Paper Station (1.0.0.48), RPC Shutdown (2.2), Silicon Labs Multiprotocol (1.1.1), Glances (0.18.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 22
views | 19
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | April 7, 2023 at 06:52
-- | --
current_recorder_run | April 13, 2023 at 06:49
estimated_db_size | 2574.84 MiB
database_engine | mysql
database_version | 10.6.10

</details>

### Additional information

Using Zigbee2mqtt

**Comment by agners** [comment]
Can you check if both, Zigbee and Thread, are running on the same channel (you can check the Zigbee channel in the ZHA integration page, and the Thread channel in the Thread page in the info menu of the network your Silicon Labs Multiprotocol border router is part of).

**Comment by jhbruhn** [comment]
Good point, the OTBR is indeed running on channel 15 while Zigbee2MQTT uses Channel 11. How can I change the channel of the OTBR? I tried forming a new network via the WebInterface of OTBR, but that didn't do the trick yet. Maybe I need to do a little reading on how Thread works :)

**Comment by agners** [comment]
@jhbruhn we just added some documentation about this, see https://yellow.home-assistant.io/multiprotocol-channel-missmatch. Since you don't have any Thread devices currently, simply resetting the Thread network is your best option.

**Comment by jhbruhn** [comment]
Thanks for the quick reply, the documentation really helped. Unfortunately just resetting the border router leads to two separate networks, which are both still on channel 15 instead of 11. Perhaps because I am not using ZHA for Zigbee and thus HA does not know which channel to pick?

This is the state after resetting the border router:
![image](https://user-images.githubusercontent.com/1036566/232076464-bc2f0f1d-b539-4a08-87b9-d1eb32881f77.png)

If I then make the one below the preferred network, it leads to this:
![image](https://user-images.githubusercontent.com/1036566/232076636-62a63ee9-7c0b-4931-a096-0b4268d7ac9b.png)

Which, after deleting the bottom network, gets to this:
![image](https://user-images.githubusercontent.com/1036566/232076707-63df4b11-884c-4a5d-8ebc-23ac5c43493e.png)

After which the loop starts at the top.

**Comment by agners** [comment]
Right, resetting the network doesn't work in your case since you are using Z2M :cold_sweat: 

We do read the channel from ZHA, and setup a Thread network with the right channel. Currently there is no built-in mechanism to change the channel.

You could do it through the REST API with some jq magic, but I am not sure what this does to the OTBR/Thread integration in HA Core.

**Comment by jhbruhn** [comment]
Before I break something, I think it would be good to be able to change the channel via the UI. Where would I open an issue for this, home-assistant/core?

**Comment by jhbruhn** [comment]
This issue probably has to be fixed in core, so it can be closed here? Or are API interfaces needed for that which are implemented in the addon?

**Comment by agners** [comment]
Yes, work is ongoing, there will be a Core PR eventually. The base support in the `python-otbr-api` library has recently been added see https://github.com/home-assistant-libs/python-otbr-api/pull/42.
