### ISSUE TITLE
RPC Shutdown update to 2.3 breaks addon

### ISSUE THREAD

**Issue by gfn256** [home-assistant/addons#2991]
### Describe the issue you are experiencing

Updating RPC Shutdown from 2.2 to 2.3 breaks the addon - and reports that it cannot log in to remote PC.
Messed trying with quotation marks around  credentials details etc. in config but it did not help.
Reverting back to 2.2 solves the issue after adding quotation marks (which then get removed after saving&restarting addon)

NOTE: I have no "%" mark of my own in the username or password, just the one between the username & password.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

RPC Shutdown

### What is the version of the add-on?

2.3

### Steps to reproduce the issue

Detailed as above

## System Information

version | core-2023.4.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.10
os_name | Linux
os_version | 6.1.24
arch | x86_64
timezone | Asia/Jerusalem
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | August 11, 2023 at 3:00 AM
relayer_connected | true
relayer_region | ap-southeast-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | eu-central-1-8.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.0
-- | --
update_channel | stable
supervisor_version | supervisor-2023.04.0
agent_version | 1.5.1
docker_version | 23.0.3
disk_total | 30.8 GB
disk_used | 8.8 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.2.0), File editor (5.5.0), Home Assistant Google Drive Backup (0.110.3), RPC Shutdown (2.2), Samba share (10.0.0), Terminal & SSH (9.6.2), eWeLink Smart Home (1.4.3)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 0
views | 13
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | April 10, 2023 at 6:47 AM
-- | --
current_recorder_run | April 19, 2023 at 4:52 PM
estimated_db_size | 157.98 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

**Comment by agners** [comment]
> Reverting back to 2.2 solves the issue after adding quotation marks (which then get removed after saving&restarting addon)

Quotation marks is a pure YAML thing, and they should not be necessary unless you have a `"` or `\` in your password string, then you should use single quotes (`'`) (see https://stackoverflow.com/a/69850618/184207).

**Comment by agners** [comment]
@gfn256 actually, I can't reproduce. The latest add-on works fine here.

Can you retest on your side? Are you sure the same configuration did it work before? Can you provide the add-on logs after a non-working attempt?

**Comment by D43DBULL** [comment]
2.4 fixed the issue for me

**Comment by gfn256** [comment]
Fixed for me too in 2.4

**Comment by gfn256** [comment]
Why did Alpine 3.17 fix the issue? I don't know!
I'm on a Proxmox VM running HAOS 10.0 latest evrything.

**Comment by agners** [comment]
Just for the records, that the image update fixes this issue doesn't make sense to me either :sweat_smile: 

Maybe the add-on restart which comes along with it or something like that fixed it, not sure :man_shrugging:
