### ISSUE TITLE
Failed to start add-on

### ISSUE THREAD

**Issue by milandzuris** [home-assistant/addons#2994]
### Describe the issue you are experiencing

![image](https://user-images.githubusercontent.com/42905545/233430664-d7e3bfb9-ff58-4b9f-9191-159c083faa04.png)

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

RPC Shutdown

### What is the version of the add-on?

2.4

### Steps to reproduce the issue

*

### System Health information

*

**Comment by agners** [comment]
Can you try to uninstall and install the add-on again?

**Comment by milandzuris** [comment]
> Can you try to uninstall and install the add-on again?

no

**Comment by DvdEnde** [comment]
I had the same issue.  uninstalling and installing the add-on again solved the issue.
