### ISSUE TITLE
Samba Share Will Not Update

### ISSUE THREAD

**Issue by RJ-Make** [home-assistant/addons#3004]
### Describe the issue you are experiencing

Samba Share will not update to 10.0.1

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Samba share

### What is the version of the add-on?

10.0.0

### Steps to reproduce the issue

1. Try to update Samba Share from 10.0.0 to 10.0.1

## System Information

version | core-2023.4.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.10
os_name | Linux
os_version | 6.1.24
arch | x86_64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.32.1
Stage | running
Available Repositories | 1269
Downloaded Repositories | 19

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | April 20, 2024 at 8:00 PM
relayer_connected | true
relayer_region | us-east-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
remote_server | us-east-1-2.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.0
-- | --
update_channel | stable
supervisor_version | supervisor-2023.04.0
agent_version | 1.5.1
docker_version | 23.0.3
disk_total | 62.3 GB
disk_used | 18.5 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Samba share (10.0.0), Studio Code Server (5.5.7), InfluxDB (4.6.0), Nextcloud Backup (0.17.7), SSH & Web Terminal (13.1.0), Samba Backup (5.0.0), Z-Wave JS UI (1.11.1), Network UPS Tools (0.11.2), Grafana (8.2.2), Glances (0.18.1), ESPHome (2023.4.1), Uptime Kuma (0.7.2), Music Assistant BETA (2.0.0b29)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 8
views | 32
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | March 25, 2023 at 6:02 PM
-- | --
current_recorder_run | April 24, 2023 at 4:43 AM
estimated_db_size | 1447.29 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

### Anything in the Supervisor logs that might be useful for us?

```txt
23-04-24 14:41:14 ERROR (SyncWorker_3) [supervisor.docker.interface] Can't install homeassistant/amd64-addon-samba:10.0.1: 500 Server Error for http+docker://localhost/v1.42/images/create?tag=10.0.1&fromImage=homeassistant%2Famd64-addon-samba&platform=linux%2Famd64: Internal Server Error ("Get "https://registry-1.docker.io/v2/": read tcp 192.168.1.132:46680->52.1.184.176:443: read: connection reset by peer")
```

### Anything in the add-on logs that might be useful for us?

```txt
Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/update.py:169
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 2:41:14 PM (1 occurrences)
Last logged: 2:41:14 PM

[140643807461488] Error updating Samba share: Can't install homeassistant/amd64-addon-samba:10.0.1: 500 Server Error for http+docker://localhost/v1.42/images/create?tag=10.0.1&fromImage=homeassistant%2Famd64-addon-samba&platform=linux%2Famd64: Internal Server Error ("Get "https://registry-1.docker.io/v2/": read tcp 192.168.1.132:46680->52.1.184.176:443: read: connection reset by peer")
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 167, in async_install
    await async_update_addon(self.hass, slug=self._addon_slug, backup=backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 51, in _wrapper
    raise HassioAPIError(data["message"])
homeassistant.components.hassio.handler.HassioAPIError: Can't install homeassistant/amd64-addon-samba:10.0.1: 500 Server Error for http+docker://localhost/v1.42/images/create?tag=10.0.1&fromImage=homeassistant%2Famd64-addon-samba&platform=linux%2Famd64: Internal Server Error ("Get "https://registry-1.docker.io/v2/": read tcp 192.168.1.132:46680->52.1.184.176:443: read: connection reset by peer")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1820, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1857, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 216, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 798, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 977, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 838, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 156, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 417, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 169, in async_install
    raise HomeAssistantError(f"Error updating {self.title}: {err}") from err
homeassistant.exceptions.HomeAssistantError: Error updating Samba share: Can't install homeassistant/amd64-addon-samba:10.0.1: 500 Server Error for http+docker://localhost/v1.42/images/create?tag=10.0.1&fromImage=homeassistant%2Famd64-addon-samba&platform=linux%2Famd64: Internal Server Error ("Get "https://registry-1.docker.io/v2/": read tcp 192.168.1.132:46680->52.1.184.176:443: read: connection reset by peer")
```

**Comment by agners** [comment]
This is unrelated to the add-on itself. Most likely a problem with the Internet connection or another issue reaching Docker Hub.

**Comment by agners** [comment]
You can try pulling the image manually in the Advanced SSH & Web Terminal:

```
docker pull homeassistant/amd64-addon-samba:10.0.1
```

**Comment by RJ-Make** [comment]
> You can try pulling the image manually in the Advanced SSH & Web Terminal:
> 
> ```
> docker pull homeassistant/amd64-addon-samba:10.0.1
> ```

When I run that command it returns an error "invalid reference format"

**Comment by RJ-Make** [comment]
Well, now that I've uninstalled the Add-on (thinking that would solve the update problem) I can't reinstall it.  

Any help here would be great.

**Comment by RJ-Make** [comment]
```
Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:125
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 5:22:48 AM (2 occurrences)
Last logged: 5:39:19 AM

Failed to to call /addons/core_samba/install - Can't install homeassistant/amd64-addon-samba:10.0.2: 500 Server Error for http+docker://localhost/v1.42/images/create?tag=10.0.2&fromImage=homeassistant%2Famd64-addon-samba&platform=linux%2Famd64: Internal Server Error ("Head "https://registry-1.docker.io/v2/homeassistant/amd64-addon-samba/manifests/10.0.2": Get "https://auth.docker.io/token?scope=repository%3Ahomeassistant%2Famd64-addon-samba%3Apull&service=registry.docker.io": read tcp 192.168.1.132:35450->34.205.13.154:443: read: connection reset by peer")
Failed to to call /addons/core_samba/install - Can't install homeassistant/amd64-addon-samba:10.0.2: 500 Server Error for http+docker://localhost/v1.42/images/create?tag=10.0.2&fromImage=homeassistant%2Famd64-addon-samba&platform=linux%2Famd64: Internal Server Error ("Get "https://registry-1.docker.io/v2/": read tcp 192.168.1.132:52152->44.205.64.79:443: read: connection reset by peer")
```

**Comment by RJ-Make** [comment]
This was a Verizon routing issues.

**Comment by RJ-Make** [comment]
> @RJ-Make I've been running into this and some other seemingly random bugs all of a sudden and I finally come across you mentioning a Verizon routing issue and I'm thinking that must also be my problem since the HAOS instance I'm troubleshooting is connected to a router using a verizon 4g sim card. Do you mind sharing what you did to fix the routing issue?

I could not fix the problem, Verizon had to fix the routing failure. If you perform a tracert on the url you can see where the failure resides and try and report it to Verizon.
