### ISSUE TITLE
VLC add on turns volume to 135% after playing audio

### ISSUE THREAD

**Issue by dbuezas** [home-assistant/addons#3007]
### Describe the issue you are experiencing

This happens when playing from the Media tab, a service (e.g tts) or even in the AddOn's web UI.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Almond

### What is the version of the add-on?

0.1.3

### Steps to reproduce the issue

1. Go to the Addon UI http://homeassistant.local:8123/hassio/ingress/local_vlc
2. Set the volume to 70%
3. Press Play
4. Wait for it to finish
5. Press Play again
6. The Volume resets back to 135% and the audio is super loud and oversaturated.

## System Information

version | core-2023.4.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.10
os_name | Linux
os_version | 6.1.24
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4760
Installed Version | 1.32.1
Stage | running
Available Repositories | 1272
Downloaded Repositories | 29

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | August 25, 2023 at 2:00 AM
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | false
remote_server | eu-central-1-1.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.0
-- | --
update_channel | stable
supervisor_version | supervisor-2023.04.1
agent_version | 1.5.1
docker_version | 23.0.3
disk_total | 468.7 GB
disk_used | 68.3 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | SSH & Web Terminal (13.1.0), File editor (5.5.0), SQLite Web (3.7.1), Mosquitto broker (6.2.0), ESPHome (2023.3.0), Studio Code Server (5.5.6), Frigate (0.12.0), Samba share (10.0.0), VLC (0.1.3)

</details>

<details><summary>Dashboards</summary>

dashboards | 7
-- | --
resources | 16
views | 66
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | April 22, 2023 at 3:22 PM
-- | --
current_recorder_run | April 25, 2023 at 2:29 PM
estimated_db_size | 38013.77 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

<details><summary>Xiaomi Gateway 3</summary>

version | 3.2.1 (ebfc175)
-- | --

</details>

<details><summary>Xiaomi Miot Auto</summary>

error | failed to load: timeout
-- | --

</details>

### Anything in the Supervisor logs that might be useful for us?

```txt
Nothing relevant
```

### Anything in the add-on logs that might be useful for us?

```txt
172.30.32.2 - - [25/Apr/2023:18:41:51 +0000] "GET /requests/status.xml HTTP/1.1" 200 761 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
```

### Additional information

I now made a local AddOn that exactly clones the original and extended this line like this: `exec cvlc .... --volume 75`. This makes it quite usable for me.

It may be worth considering making it configurable as "Default volume" as a workaround.

Thank you for the add-on, I'm quite enjoying it!

**Comment by agners** [comment]
I can't reproduce this. Is it maybe some Core automation which interferes here?

Can you recheck on 0.2.0?

**Comment by dbuezas** [comment]
I didn't realise there was a newer version. Will do.
Could it be the host device itself? it's a laptop, which I assume is not the most usual kind of server

**Comment by agners** [comment]
Yeah maybe, sound card (or rather its driver) could make a difference I guess.

**Comment by robertvorthman** [comment]
I have the same issue.  VLC add-on resets to 102% volume on my Dell Optiplex 3050.  Home Assistant version 2023.5.2.

**Comment by dbuezas** [comment]
@agners Just tried v0.2.0. Volume still resets after each audio played (this time to a different number than 135%)

**Comment by rongten** [comment]
Same issue. Intel nuc5i5, vlc-core 0.2.0, haos 10.3, supervisor 2023.07.1, HA 2023.07.1.
In the docker of vlc-core there are no binaries to control the volume, only on the os there is pa-info.

Doing pa-info on the os before and after playing a sound and having the volume change, the output stays the same (checked with pa-info | grep volume | md5sum), so the issue is maybe really in the container.

**Comment by rongten** [comment]
Ah, in my case it goes to 100%.

**Comment by trianglesis** [comment]
I have the same issue.

Using Raspberry Pi 5, installed HA, installed addon:

- "/hassio/ingress/core_vlc" - 0.3.0
- https://github.com/home-assistant/addons/tree/master/vlc

The volume always returns to 50%, even if I'm trying to change it by automation or at the WEB UI.
The volume always goes back to 50%.
