### ISSUE TITLE
Crond logs in Home Assistant CLI after nginx update

### ISSUE THREAD

**Issue by janrg** [home-assistant/addons#3013]
### Describe the issue you are experiencing

About 1-2 minutes after the “Welcome to the Home Assistant command line” message appears, the following message shows up:

`crond[58] crond (busybox 1.35.0) started, log level 8`

This is then followed on every cron execution with a message such as this one:

`crond[58] USER root pid 148 cmd run-parts /etc/periodic/15min`

A downgrade of the nginx addon to 3.2 appears to get rid of these messages. From the commit history, it also seems likely that it was introduced in 3.3.

More information here:
https://community.home-assistant.io/t/cron-logs-in-cli-after-move-to-another-computer/563355

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

NGINX Home Assistant SSL proxy

### What is the version of the add-on?

3.4

### Steps to reproduce the issue

Start homeassistant (in HAOS), wait for logs to appear.

## System Information

version | core-2023.4.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.10
os_name | Linux
os_version | 6.1.25
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4812
Installed Version | 1.32.1
Stage | running
Available Repositories | 1272
Downloaded Repositories | 29

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.1
-- | --
update_channel | stable
supervisor_version | supervisor-2023.04.1
agent_version | 1.5.1
docker_version | 23.0.3
disk_total | 62.3 GB
disk_used | 14.7 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.5.0), Studio Code Server (5.5.7), Duck DNS (1.15.0), Mosquitto broker (6.2.0), ESPHome (2023.4.0), Terminal & SSH (9.7.0), NGINX Home Assistant SSL proxy (3.4.0), MariaDB (2.5.2), Home Assistant Google Drive Backup (0.110.3), phpMyAdmin (0.8.5), Samba share (10.0.0), InfluxDB (4.6.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 19
views | 18
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 19 April 2023 at 18:03
-- | --
current_recorder_run | 27 April 2023 at 19:17
database_engine | mysql
database_version | 10.6.10

</details>

**Comment by Ndrinta** [comment]
Same "problem" here.

**Comment by kingofconven** [comment]
doing it on a fresh install with only duck dns and nginx

**Comment by n00bster-za** [comment]
downgraded to 3.2. busybox message is gone but not the. crond[60]: USER root pid 149 cmd run-parts /etc/periodic/15min

it spams the HA CLI interface. 15min then after 1 hour it says hourly. then counts in 15 min intervals again.

**Comment by moelloman** [comment]
same problem on my HA

**Comment by jazzygff** [comment]
Same here

**Comment by sbritto0228** [comment]
I can confirm after restoring to NGIX 3.2 that the messages have gone away. Apart from being unsightly my HA was running normally with no performance issues or no issues connecting internally or externally.
