### ISSUE TITLE
Mosquitto Addon does not see .conf file in /share/mosquitto since addon update to 6.2 - probably not a mosquitto problem! 

### ISSUE THREAD

**Issue by raphael303** [home-assistant/addons#3014]
### Describe the issue you are experiencing

Many users have specific configuration data for Mosquitto stored in a file mosquitto.conf which is located in /share/mosquitto.

Since the mosquitto update to 6.2 this file is not seen by mosquitto on startup of home assistant.

Restarting mosquitto after home assistant is running seems to solve the problem.

First looks at the problem pointed to a filename change from ANYTHING.conf to mosquitto.conf (in that folder) to solve the problem. But it actually doesn't. It seems the subsequent restarts of mosquitto were the actual solution.

Which is of course annoying, because it requires manual intervention after each home assistant restart.
Mosquitto bug report did not yield results, issue is being taken serious but ultimately being waved off to be a HA issue:
https://github.com/eclipse/mosquitto/issues/2776

I agree. Mosquitto runs fine, but specifically on HA startup, the file remains invisible to it.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Mosquitto broker

### What is the version of the add-on?

6.2.1

### Steps to reproduce the issue

1. Place a file called "mosquitto.conf" in the folder /shared/mosquitto - the file can have for example a bridge to another broker: 
```
connection venus-home
address 192.168.1.XXX
topic # both 0 venus-home/
```
3. Add this to "customize" in the Mosquitto configuration in the HA frontend:
```
active: true
folder: mosquitto
```
4. Restart Mosquitto - The bridge will work
5. Restart HomeAssistant - The bridge will not work
6. Restart Mosquitto - The bridge will work

## System Information

version | core-2023.4.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.10
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | Europe/Zurich
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.30.1
Stage | running
Available Repositories | 1271
Downloaded Repositories | 16

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 22. Dezember 2023 um 01:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | false
remote_server | eu-central-1-5.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.1
-- | --
update_channel | stable
supervisor_version | supervisor-2023.04.1
agent_version | 1.5.1
docker_version | 23.0.3
disk_total | 458.4 GB
disk_used | 24.7 GB
healthy | true
supported | true
board | yellow
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.2.1), Node-RED (14.1.5), Grafana (8.2.2), chrony (2.5.0), Samba share (10.0.1), Terminal & SSH (9.7.0), InfluxDB (4.6.0), UniFi Network Application (2.6.0), ESPHome (2023.4.2), File editor (5.6.0), SSH & Web Terminal (13.1.0), Zigbee2MQTT (1.30.3-1)

</details>

<details><summary>Dashboards</summary>

dashboards | 9
-- | --
resources | 14
views | 20
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 23. April 2023 um 06:12
-- | --
current_recorder_run | 27. April 2023 um 21:10
estimated_db_size | 2314.59 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

**Comment by fjarvis** [comment]
I am having exactly the same issue and can also get it to work again with a restart of the mosquitto add-on after starting HA.

**Comment by rjodwyer** [comment]
Also having same issue, using it to bridge to Chirpstack MQTT, buy yes restarting MQTT addon fixes it.

**Comment by jackkitley** [comment]
Having the same problem with solar assistant and pushing data to broken on HA restart. i need to restart the broker now in order for it to work again. very annoying.

Version 6.2.1

**Comment by jackkitley** [comment]
Same issue here. Ever since the latest mqtt add on update

**Comment by argoyle** [comment]
> Issue still persists on 10.2. Would like to have a addon-restart automation too. Ugly fix, but would work.

Thanks for the idea 😊. This works for me:
```yaml
alias: Restart Mosquitto
description: ""
trigger:
  - platform: homeassistant
    event: start
condition: []
action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  - service: hassio.addon_restart
    data:
      addon: core_mosquitto
mode: single
```

**Comment by mprajza** [comment]
Hey argoyle, nice one. Thank you for sharing Restart Mosquitto automation. It solves my issue.
Of course it world be better if the dev. team fix it withing its code.
However, I am good with this setup.
Cheers Martin
