### ISSUE TITLE
DNS challenge with netcup api

### ISSUE THREAD

**Issue by steffenweb** [home-assistant/addons#3016]
### Describe the issue you are experiencing

Hello, 
I have a problem with the DNS challenge with netcup api.

My configuration seems to work when I request the certificate for the subdomain I wanted to use the TXT record will be created, but it's wrong.
ha.xxxxxx.de is the subdomain I want to use with home assistant.
The created TXT record is "_acme-challenge.ha"

The log output:
[16:24:25] INFO: Selected DNS Provider: dns-netcup
[16:24:25] INFO: Use propagation seconds: 60
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugin legacy name certbot-dns-netcup:dns-netcup may be removed in a future version. Please use dns-netcup instead.
Account registered.
Requesting a certificate for ha.xxxxxx.de
Waiting 60 seconds for DNS changes to propagate
Certbot failed to authenticate some domains (authenticator: certbot-dns-netcup:dns-netcup). The Certificate Authority reported these problems:
  Domain: ha.xxxxxx.de
  Type:   unauthorized
  Detail: No TXT record found at _acme-challenge.ha.xxxxxx.de
Hint: The Certificate Authority failed to verify the DNS TXT records created by --certbot-dns-netcup:dns-netcup. Ensure the above domains are hosted by this DNS provider, or try increasing --certbot-dns-netcup:dns-netcup-propagation-seconds (currently 60 seconds).
Some challenges have failed.
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### Which add-on are you reporting an issue with?

Let's Encrypt

### What is the version of the add-on?

4.12.8

### Steps to reproduce the issue

Read above.

### System Health information

There are currently no repairs available

**Comment by ptc** [comment]
Change your DNS propagation timeout to something higher than 60 seconds, as this is not long enough for the DNS to update. Try 300 or even 600 seconds.

**Comment by steffenweb** [comment]
Ok, it worked with 600s on my second try. Thanks for help.
