### ISSUE TITLE
Samsung TV prompts for auth to allow HA to control it after every power cycle

### ISSUE THREAD

**Issue by namaneko** [home-assistant/addons#3021]
I'm making a new post because this is happening to me. I have to admit though I'm a little lost on where to get the logs you need. If someone would kindly point me in the right direction, I'll get whatever you need.

That said, I have a Samsung TV Q60 TV that runs on Tizen.

I have a brand new Home Assistant VM in KVM on an Ubuntu Server host.

 Home Assistant 2023.4.6 Supervisor 2023.04.1
Operating System 10.1
Frontend 20230411.1 - latest 

              I have opened a documentation PR, but as it stands nobody has provided any logs...
Please open a new issue __with logs__ if you are still affected.

_Originally posted by @epenet in https://github.com/home-assistant/core/issues/70777#issuecomment-1396589217_

**Comment by agners** [comment]
This doesn't belong to the add-on repository.
