### ISSUE TITLE
[PIPER] Integration does not allow for float config values

### ISSUE THREAD

**Issue by alessandroias** [home-assistant/addons#3023]
### Describe the issue you are experiencing

I can only set `length_scale` `noise_scale` and `noise_w` as floats using the YAML editor.
This is caused by the `<input />`'s `step` attribute which is now set to one...
I am not sure if this is an addons issue or a frontend issue. I might investigate more. 

This is especially annoying because i can't set the default value back manually.
![image](https://user-images.githubusercontent.com/46724443/236067300-c1ad49e9-cf8f-4f90-a0bf-51da5ab6850b.png)

I'm sorry for setting the wrong flag: Piper's flag does not exist at the moment.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Almond

### What is the version of the add-on?

0.1.2

### Steps to reproduce the issue

1. Open `Piper`'s config page _(I should mention I am using Chrome)_;
2. Pretend to modify either Length Scale, Noise Scale or Speaking Cadence with a float value;
3. You can now see the input flagged as invalid.

## System Information

version | core-2023.5.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.11
os_name | Linux
os_version | 5.15.61-v8
arch | aarch64
timezone | Europe/Rome
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4922
Installed Version | 1.32.1
Stage | running
Available Repositories | 1282
Downloaded Repositories | 12

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.2
-- | --
update_channel | stable
supervisor_version | supervisor-2023.04.1
agent_version | 1.4.1
docker_version | 20.10.17
disk_total | 57.8 GB
disk_used | 28.5 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Nginx Proxy Manager (0.12.3), MariaDB (2.5.2), AdGuard Home (4.8.6), Studio Code Server (5.5.2), Advanced SSH & Web Terminal (14.1.0), Samba NAS (10.0.0-nas8), ESPHome (2023.4.3), Plex Media Server (3.2.1), Piper (0.1.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 6
views | 10
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 21 aprile 2023 alle ore 10:36
-- | --
current_recorder_run | 4 maggio 2023 alle ore 00:13
estimated_db_size | 76.83 MiB
database_engine | sqlite
database_version | 3.40.1

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Comment by bramkragten** [comment]
Fixed in frontend:
https://github.com/home-assistant/frontend/pull/16478
https://github.com/home-assistant/frontend/pull/16483
