### ISSUE TITLE
duckDNS not updating IP

### ISSUE THREAD

**Issue by L0bit0** [home-assistant/addons#3027]
### The problem

Hi

I am using duckDNS on home assistant, but when my router IP changes is not reflected on duckDNS.

Details:
-	I have configured duck DNS like this:
![image](https://user-images.githubusercontent.com/10359623/233030332-eaa6d475-4394-4d2d-98f7-a3a9693c3201.png)
-	It is working for some time, but as soon router IP changes, changes is not reflected on duckDNS:
-	I can configure a new DNS and it again works for some time…
-	Log:
![image](https://user-images.githubusercontent.com/10359623/233030851-d109f5d9-eee0-4059-bae3-44c5000f8351.png)

-	I tried to:
    o	Restart duck DNS service
    o	Restart home assistant server
    o	Refresh IP form duckDNS web

Any idea?

### What version of Home Assistant Core has the issue?

2023.4.5

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

DuckDNS

**Comment by L0bit0** [comment]
Hi, i am still having issue, any idea? make sense to create on any other place more specific to duck DNS?

**Comment by ascendedguard** [comment]
I'm having the same issue on a brand new install. Guessing the plugin doesn't work?

**Comment by ascendedguard** [comment]
@L0bit0 Actually, figured it out on my end... I was getting the same blank WARNING: message, you have to switch `accept_terms: false` to true in the Let's Encrypt configuration options.

**Comment by L0bit0** [comment]
Thanks,, I have updated with your comments and it is working now. Anyway I have to monitor, as with previous configuration also works for some time (couple of hours)

Thanks
