### ISSUE TITLE
[piper] multi-line prompt causes prompts and outputs to become mis-aligned

### ISSUE THREAD

**Issue by saw2kx** [home-assistant/addons#3028]
### Describe the issue you are experiencing

If I enter a multi-line prompt in Media > TTS > piper [SIC - lower case?], only the first line is read and then the second line is read in place of whatever I enter next.  e.g.:

 <table>
  <tr>
    <th>Prompt</th>
    <th>Spoken output</th>
  </tr>
  <tr>
    <td>Apple<br>Banana</td>
    <td>Apple</td>
  </tr>
  <tr>
    <td>Peach</td>
    <td>Banana</td>
  </tr>
  <tr>
    <td>Clementine</td>
    <td>Peach</td>
  </tr>
  <tr>
    <td>Pomello</td>
    <td>Clementine</td>
  </tr>
</table>

This persists through rebooting the system (I can't find where to clear the cache and hoped a reboot would do it).

As I have done this a few times now to test and confirm the bug, the prompts and output are now further out of line.  Each multi-line prompt increases the misalignment by number of lines -1 .

This seems to affect everything.  I just changed the prompt in an automation and triggered it and I got the prompt I entered in Media several times ago.

One more thing that seems pertinant in relation to the caching: if I reenter the same prompt, it will output whatever it said the first time I entered the prompt, so "clementine" will always say "peach" for example.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Almond

### What is the version of the add-on?

0.1.2

### Steps to reproduce the issue

1. Enter a multi line prompt for Piper to speak.
2. Only the first line is read.
3. The second line replaces the first line of the next prompt.
4. the problem continues, with prompts and output getting further maligned the more multi-line prompts one enters.

## System Information

version | core-2023.5.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.11
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | America/Chicago
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.1
-- | --
update_channel | stable
supervisor_version | supervisor-2023.04.1
agent_version | 1.5.1
docker_version | 23.0.3
disk_total | 234.0 GB
disk_used | 11.2 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.6.0), Mosquitto broker (6.2.1), AdGuard Home (4.8.6), MariaDB (2.6.0), Samba share (10.0.1), phpMyAdmin (0.8.5), ESPHome (2023.4.4), Tailscale (0.11.1), Piper (0.1.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 0
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 27 April 2023 at 13:49
-- | --
current_recorder_run | 4 May 2023 at 10:20
estimated_db_size | 149.98 MiB
database_engine | mysql
database_version | 10.6.12

</details>

### Anything in the Supervisor logs that might be useful for us?

```txt
Well, this seems unrelated, but it says to report it...!  I'll go do that in the right place after this:

 Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 10:21:02 (1 occurrences)
Last logged: 10:21:02
Detected integration that calls media_source.async_resolve_media without passing an entity_id. Please report issue for media_source using this method at homeassistant/components/media_source/__init__.py, line 147: report("calls media_source.async_resolve_media without passing an entity_id")
```

### Anything in the add-on logs that might be useful for us?

```txt
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service piper: starting
s6-rc: info: service piper successfully started
s6-rc: info: service discovery: starting
INFO:__main__:Ready
[10:04:32] INFO: Successfully send discovery information to Home Assistant.
s6-rc: info: service discovery successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
```

**Comment by synesthesiam** [comment]
Thanks for the bug report! A fix will be in the next version :+1:

**Comment by saw2kx** [comment]
Thanks for the fix.

When I got stuck in this misaligned token loop or whatever it is I thought I'd try to break out of it by changing the voice, but anything previously cached still used the previous voice.  Is this because of this issue or a different bug I should report?  Cached responses should be dropped and regenerated when I change the voice, right?

**Comment by synesthesiam** [comment]
The voice name is part of the cache key, so they will remain in cache until deleted from `config/tts`. Not sure if there's a service call to purge this cache.

**Comment by saw2kx** [comment]
Interesting, thanks.  I'll poke around some with it, I'm keen to learn more.

**Comment by synesthesiam** [comment]
@agners This issue is resolved.
