### ISSUE TITLE
Piper TTS not working with DLNA connected speakers

### ISSUE THREAD

**Issue by liquidbear99** [home-assistant/addons#3030]
### Describe the issue you are experiencing

I believe Piper TTS is not working with DLNA connected speakers.

I successfully have assist tab set up to convert my verbal commands to text and it can respond to me using Piper so that part works as expected; however, I believe the automation service TTS is not working. I went into the Developer Tools in the Services Tab and set up a TTS for my media player using Piper. I tried multiple speakers and the command will send but no audio will play through the speakers. I know the speakers work because Music Assistant utilizes each one successfully. Each of my speakers is connected via piCorePlayer/Logitech Media Server and uses DLNA to communicate with Home Assistant. It seems like Piper is having trouble with DLNA speakers. I further diagnosed this since when I send the TTS command to my Denon receiver connected via DLNA an error on my receiver states “Unable to play media. Please try again later”.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Almond

### What is the version of the add-on?

0.1.2

### Steps to reproduce the issue

1. Install Piper
2. Connect a speaker through DLNA
3. Attempt to execute TTS through the DLNA speaker using Piper

## System Information

version | core-2023.5.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.11
os_name | Linux
os_version | 6.1.25
arch | x86_64
timezone | X
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4996
Installed Version | 1.32.1
Stage | running
Available Repositories | 1283
Downloaded Repositories | 28

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.1
-- | --
update_channel | stable
supervisor_version | supervisor-2023.04.1
agent_version | 1.5.1
docker_version | 23.0.3
disk_total | 1877.1 GB
disk_used | 27.7 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.6.0), Samba share (10.0.1), WireGuard (0.8.0), AdGuard Home (4.8.6), Terminal & SSH (9.7.0), Mosquitto broker (6.2.1), Z-Wave JS (0.1.80), Duck DNS (1.15.0), RTSP Simple Server Add-on (v0.17.6), Home Assistant Google Drive Backup (0.110.4), ESPHome (2023.4.4), Frigate (0.12.0), NGINX Home Assistant SSL proxy (3.4.2), Music Assistant BETA (2.0.0b29), Piper (0.1.2), Whisper (0.1.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 16
views | 37
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | April 6, 2023 at 11:35 PM
-- | --
current_recorder_run | May 3, 2023 at 4:30 PM
estimated_db_size | 639.91 MiB
database_engine | sqlite
database_version | 3.40.1

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Anything in the add-on logs that might be useful for us?

```txt
Logger: homeassistant.components.samsungtv
Source: components/samsungtv/media_player.py:455
Integration: Samsung Smart TV (documentation, issues)
First occurred: 10:11:12 AM (7 occurrences)
Last logged: 10:32:41 AM

Unsupported media type
```

### Additional information

I also attempted to use my Smart TV as an alternat speaker but also got an error that the media type was unsupported.

**Comment by liquidbear99** [comment]
I'm unsure if this should be in the Wyoming or Piper repo so I made a report in both, feel free to close the irrelevant one

https://github.com/home-assistant/core/issues/92528

**Comment by synesthesiam** [comment]
This is due to Piper outputting WAV audio instead of MP3. We plan to change this in a future version.
