### ISSUE TITLE
[piper] Can not call piper as tts service

### ISSUE THREAD

**Issue by dflvunoooooo** [home-assistant/addons#3034]
### Describe the issue you are experiencing

I am unable to call piper via a tts service. And thus it is not possible to replace picotts or anything with piper. Is this intended? I was under the impression, that piper is supposed to be a full tts alternative. It is listed under media -> tts. 

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Almond

### What is the version of the add-on?

piper not almond! 0.1.2

### Steps to reproduce the issue

1. Developer options -> Service
2. Type "tts"
3. No piper there 

### System Health information

No repairs. 

### Anything in the Supervisor logs that might be useful for us?

```txt
No.
```

**Comment by tomlut** [comment]
Use the `tts.speak` service. `tts.piper` is the target entity.

**Comment by dflvunoooooo** [comment]
This is working. Thank you very much.
