### ISSUE TITLE
Samba add-on slower on initial connect

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/addons#3043]
### Describe the issue you are experiencing

Its hard to pin down, but bottom line is, when connecting (my Mac file system Finder) to the Ha system, response takes a lot longer than before.
up to 2023.4 (ish) or maybe the add-on update to 10.x response was near immediate. Currently, it takes up to 8 seconds for the connection to be confirmed and Finder shows the contents..

No errors in the log, its merely noted, and [confirmed in the 2023.5 thread in the community](https://community.home-assistant.io/t/2023-5-lets-talk/567331/469?u=mariusthvdb).

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Samba share

### What is the version of the add-on?

10.0.1

### Steps to reproduce the issue

1. disconnect network
2. Connect network
3. select Finder Go: connect server
4.  wait 8 seconds.....
...

## System Information

version | core-2023.5.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.11
os_name | Linux
os_version | 5.15.90
arch | x86_64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.32.1
Stage | running
Available Repositories | 1297
Downloaded Repositories | 53
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 31 augustus 2023 om 02:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | eu-central-1-10.ui.nabu.casa
certificate_status | ready
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.5
-- | --
update_channel | beta
supervisor_version | supervisor-2023.04.1
agent_version | 1.4.1
docker_version | 20.10.22
disk_total | 458.4 GB
disk_used | 22.6 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | AppDaemon (0.12.2), Log Viewer (0.15.0), MariaDB (2.6.1), Samba share (10.0.1), Terminal & SSH (9.7.0), phpMyAdmin (0.8.5), Mosquitto broker (6.2.1), Z-Wave JS (0.1.80), ESPHome (2023.4.2), Matter Server (0.3.0), Studio Code Server (5.5.7), Home Assistant Google Drive Backup (0.110.4), Music Assistant (2.0.0b4), Whisper (0.2.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 10
-- | --
resources | 38
views | 85
mode | yaml

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 28 april 2023 om 08:22
-- | --
current_recorder_run | 12 mei 2023 om 11:34
estimated_db_size | 1934.89 MiB
database_engine | mysql
database_version | 10.6.12

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Comment by tomlut** [comment]
It's about 5 seconds for initial connection for me, which is a lot slower than I remember it being.

**Comment by TekFan** [comment]
For me it's between 5 and 7 seconds.
I also noticed that it sometimes creates phantom disks on the desktop that I cannot eject.
After a while, my desktop is full of those drives and a macOS reboot is the only solution to get rid of them.
But the this may be a macOS problem.

**Comment by Mariusthvdb** [comment]
if anything, this has worsened, currently taking even more than 10 secs, running HA 2022.4.5

**Comment by tomlut** [comment]
Still an issue, 2023.6.3

**Comment by g-kiss** [comment]
For me the connection is between 5 and 10 seconds from windows desktop.

**Comment by vezinpi** [comment]
I have 2 concurent systems running at home. One is a non supervised docker on a raspberry pi with ssd running raspbian and one using HASS OS (supervised) again on a raspberry pi with ssd.

When accessing using a windows computer, an average of 5 to 7 seconds is required to see the share folders from the HASS OS Rpi. Almost instantaneous on the other one

**Comment by GiZMoSK1221** [comment]
same here from windows. Issue started 2-3 samba addon versions earlier. I noticed that immediately. I have npp open with home-assistant.log and checking it regularly. When I activate npp, it used to show me immediately, that log file has changed. Now it needs 5-10 sec. it's really annoying :(
i'm running HASS OS on RPI4 with SSD

**Comment by tomlut** [comment]
Still an issue.

**Comment by Mariusthvdb** [comment]
Keep

**Comment by Mariusthvdb** [comment]
Keep

**Comment by luca-angemi** [comment]
For me seems solved now with latest relaese. Anyone still having this issue?

**Comment by frenck** [comment]
Yeah, this is solved with the lastest version (which brings in a newer samba).


../Frenck
