### ISSUE TITLE
Whisper is using a lot of RAM all of a sudden after updateing to 0.2.0

### ISSUE THREAD

**Issue by drthanwho** [home-assistant/addons#3048]
### Describe the issue you are experiencing

I don't see anything in the logs or anything. I'm just noticing my RAM being high all of  a sudden which started going down as soon as I stopped the container. And can verify it from Glances saying it's using 1GB all of a sudden.
![image](https://github.com/home-assistant/addons/assets/22405505/c97d7458-a04b-491c-bce7-bf73a1236848)
![image](https://github.com/home-assistant/addons/assets/22405505/ee26ec10-5099-4875-8787-8b696245f361)

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Whisper

### What is the version of the add-on?

0.2.0

### Steps to reproduce the issue

1. Update Whisper to 0.2.0
2.
3.
...

## System Information

version | core-2023.5.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.11
os_name | Linux
os_version | 6.1.27
arch | x86_64
timezone | Europe/Athens
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.32.1
Stage | running
Available Repositories | 1301
Downloaded Repositories | 74
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.0.dev20230501
-- | --
update_channel | dev
supervisor_version | supervisor-2023.05.dev0901
agent_version | 1.5.1
docker_version | 23.0.5
disk_total | 38.7 GB
disk_used | 30.2 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | AdGuard Home (4.8.6), DSS VoIP Notifier (4.0.0), ESPHome (2023.4.4), ESPHome (beta) (2023.4.4), ESPHome (dev) (dev), File editor (5.6.0), Firefly iii (5.7.18), Firefly iii Data Importer (version-1.2.2-3), Frigate NVR (3.1), Glances (0.18.2), Grafana (8.2.2), Hey Ada! (1.2.0), InfluxDB (4.6.0), Mosquitto broker (6.2.1), Network UPS Tools (0.11.2), RTSPtoWeb - WebRTC (1.4.0), Remote API proxy (1.2.0), Advanced SSH & Web Terminal (14.1.0), Samba share (10.0.1), Scrutiny (v0.7.1), Spotify Connect (0.12.3), Studio Code Server (5.5.7), TasmoAdmin (0.24.2), VSCode Remote (6541b8e), chrony (2.5.0), phpMyAdmin (0.8.5), Music Assistant BETA (2.0.0b30), Whisper (0.2.0), Piper (0.1.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 8
-- | --
resources | 50
views | 46
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 3 May 2023 at 20:51
-- | --
current_recorder_run | 10 May 2023 at 21:22
estimated_db_size | 1770.92 MiB
database_engine | mysql
database_version | 10.9.2

</details>

<details><summary>Sonoff</summary>

version | 3.5.1 (122751c)
-- | --
cloud_online | 1 / 2
local_online | 0 / 0

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Comment by synesthesiam** [comment]
Which Whisper model are you using?

**Comment by drthanwho** [comment]
medium-int8

**Comment by synesthesiam** [comment]
That is about what I'd expect for RAM usage from medium-int8.

**Comment by drthanwho** [comment]
24/7? I thought that would be the case only when it's in use.

**Comment by synesthesiam** [comment]
The faster-whisper library that we use keeps the whole model in RAM as far as I know. Other libraries like whisper.cpp use mmap which should behave more like you're expecting.

**Comment by drthanwho** [comment]
As long as it's expected behaviour then fair enough. I just hadn't realised that was the case
