### ISSUE TITLE
NGINX Addon -- is not usable.. 400 & 500 errors with no logging or help to try and resolve.

### ISSUE THREAD

**Issue by MiddleSiggy** [home-assistant/addons#3055]
### Describe the issue you are experiencing

I have more than 30 years and 26 IT certifications, and the HA implementation of this addon makes it practically un-usable.. 

You need to add in some logging or a hint as to why things are not working.. I have just spent the last 3 hours trying to debug my instance to try and understand why I can reach HA internally, but externally I receive nothing but errors.. 

So at this point I have uninstalled it, left my inside HA running on port 8123, and just feed my external connection through haproxy on psfense from outside port 443 to 8123.. 

I highly suggest you do something with this package...

Thank you

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

NGINX Home Assistant SSL proxy

### What is the version of the add-on?

current

### Steps to reproduce the issue

1. install Nginx, configure per documentations
2. can connect internal no problem 10.254.0.254:8123
3. can connect ha.domain.com internal with IP resolves to 10.254.0.254
4. When trying to come from outside, my edge has a pfsense firewall running haproxy it does not work.
5. The connection is Internet -> haproxy -> Nginx -> HA

Logging is needed

I have tried to use openssl to test port 443 on nginx and it does not seem to work correctly.. 

again.. no logging... 
...

### System Health information

no logging, logging needed

### Anything in the Supervisor logs that might be useful for us?

```txt
no logging, logging needed
```

### Anything in the add-on logs that might be useful for us?

```txt
no logging, logging needed
```

**Comment by 8ear** [comment]
I have the same issue.

**Comment by wawyed** [comment]
I had to add this to configuration.yaml:

```

**Comment by MiddleSiggy** [comment]
I have added every version of the trusted_proxies and more... 

The developers for this add-on needs to add an easier way to support people with useful logs.
