### ISSUE TITLE
Whisper and Piper add on not available

### ISSUE THREAD

**Issue by wolfhond** [home-assistant/addons#3059]
### Describe the issue you are experiencing

Hello

I have a RPI4 but I can't install Whisper and Piper add on.

I get te message:
This add-on is not compatible with your device's processor or the operating system you have installed on your device.

Anybody an idea?

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Whisper and Piper

## System Information

version | core-2023.5.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.11
os_name | Linux
os_version | 6.1.21-v7l
arch | armv7l
timezone | Europe/Brussels
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.32.1
Stage | running
Available Repositories | 1287
Downloaded Repositories | 24

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 7 april 2024 om 02:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | eu-central-1-5.ui.nabu.casa
certificate_status | ready
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.1
-- | --
update_channel | stable
supervisor_version | supervisor-2023.04.1
agent_version | 1.5.1
docker_version | 23.0.3
disk_total | 57.8 GB
disk_used | 14.7 GB
healthy | true
supported | true
board | rpi4
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.6.0), Samba share (10.0.1), Terminal & SSH (9.7.0), Dropbox Sync (1.3.0), Mosquitto broker (6.2.1), ESPHome (2022.3.1), eWeLink Smart Home (1.4.3), OneDrive Backup (2.1.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 18
views | 28
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 14 mei 2023 om 19:33
-- | --
current_recorder_run | 23 mei 2023 om 12:47
estimated_db_size | 222.05 MiB
database_engine | sqlite
database_version | 3.40.1

</details>

**Comment by agners** [comment]
You are running Raspberry Pi with Home Assistant OS in 32-bit variant. The add-ons require 64-bit OS. To migrate, I recommend making a full backup, downloading it and reinstall the RPi 64-bit HAOS.

**Comment by wolfhond** [comment]
thanks i was thinking buy a backup device. Thats the moment to switch to 64bit

**Comment by rheicide** [comment]
@agners Piper's recent releases provide binaries for armv7 (32-bit Raspberry Pi 3/4). Is it possible to update the add-on to support it?
