### ISSUE TITLE
Timeout running pipeline

### ISSUE THREAD

**Issue by dominikhoebert** [home-assistant/addons#3071]
### Describe the issue you are experiencing

Always getting following error when using voice assistant:

```
stage: error
run:
  pipeline: 01h0a695ejh71jhe7nf4g5ad78
  language: en
  runner_data:
    stt_binary_handler_id: 1
    timeout: 30
events:
  - type: run-start
    data:
      pipeline: 01h0a695ejh71jhe7nf4g5ad78
      language: en
      runner_data:
        stt_binary_handler_id: 1
        timeout: 30
    timestamp: "2023-05-29T11:44:46.543151+00:00"
  - type: stt-start
    data:
      engine: stt.faster_whisper
      metadata:
        language: en
        format: wav
        codec: pcm
        bit_rate: 16
        sample_rate: 16000
        channel: 1
    timestamp: "2023-05-29T11:44:46.544437+00:00"
  - type: error
    data:
      code: timeout
      message: Timeout running pipeline
    timestamp: "2023-05-29T11:45:16.543829+00:00"
stt:
  engine: stt.faster_whisper
  metadata:
    language: en
    format: wav
    codec: pcm
    bit_rate: 16
    sample_rate: 16000
    channel: 1
  done: false
error:
  code: timeout
  message: Timeout running pipeline
```

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Whisper

### What is the version of the add-on?

0.2.0

### Steps to reproduce the issue

Already tried updating, different devices, different models…

## System Information

version | core-2023.5.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.11
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | Europe/Vienna
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4998
Installed Version | 1.30.1
Stage | running
Available Repositories | 1284
Downloaded Repositories | 14

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.1
-- | --
update_channel | stable
supervisor_version | supervisor-2023.04.1
agent_version | 1.5.1
docker_version | 23.0.3
disk_total | 116.7 GB
disk_used | 75.3 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.2.1), Studio Code Server (5.6.0), Advanced SSH & Web Terminal (15.0.1), Zigbee2MQTT (1.30.4-1), Tailscale (0.11.1), Plex Media Server (3.2.4), radarr (0.11.2), Qbittorrent (4.5.2-3), Samba share (10.0.2), Home Assistant Google Drive Backup (0.110.4), VLC (0.2.0), ESPHome (2023.5.5), Duck DNS (1.15.0), AdGuard Home (4.8.7), Uptime Kuma (0.7.4), Vaultwarden (Bitwarden) (0.19.4), eWeLink Smart Home (1.4.3), Epic Games Free (c0dfe30ee94fa609a9efcb5eb2b8fd0c1dafe6e2-2023-05-03-2), Nginx Proxy Manager (0.12.3), MariaDB (2.6.1), heimdall (0.3.1), Bazarr NAS (1.2.1), Jackett NAS (0.21.42), Lidarr NAS (1.1.4.3027-ls121), Readarr (nightly-0.1.6.1865-ls178), Sonarr (3.0.10.1567-2), Bookstack (1.8.0), Crowdsec (1.4.6), Crowdsec Firewall Bouncer (v0.0.26-ha2), Firefly iii (6.0.10), Organizr (1.90-bugfix2), Cloudcommander (16.15.0), Portainer (2.18.3), Piper (0.1.3), Whisper (0.2.0), Filebrowser (2.23.0-5), EMQX (0.2.9)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 9
views | 4
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 22. Mai 2023 um 15:09
-- | --
current_recorder_run | 29. Mai 2023 um 13:41
estimated_db_size | 106.86 MiB
database_engine | sqlite
database_version | 3.40.1

</details>

**Comment by horizonchasers** [comment]
I had the same issue. I uninstalled Whisper, reloaded HA, installed again and then did a system reboot and it is working now.

**Comment by agners** [comment]
Is there anything in the logs of the Whisper add-on when this timeout occurs?

**Comment by dominikhoebert** [comment]
> I had the same issue. I uninstalled Whisper, reloaded HA, installed again and then did a system reboot and it is working now, but only in Google Chrome, not through app on macOS or iOS.

Did not work for me

**Comment by dominikhoebert** [comment]
> Is there anything in the logs of the Whisper add-on when this timeout occurs?

No errors in Home Assistant Logs or in the Add-on Logs

**Comment by horizonchasers** [comment]
In whisper I am getting this each time I try it through the app on iOS and I get time "Timeout running pipeline"

INFO:wyoming_faster_whisper.handler:
INFO:wyoming_faster_whisper.handler:
INFO:wyoming_faster_whisper.handler:

Also had this error around the same time but not sure if it is related.

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:125 
Integration: Home Assistant WebSocket API (documentation, issues) 
First occurred: 7:50:59 AM (9 occurrences) 
Last logged: 7:56:52 AM

[140651174862448] Received binary message for non-existing handler 1
[140651178190560] Received binary message for non-existing handler 1

**Comment by horizonchasers** [comment]
Then when I try it in Safari on my Mac where chrome is working I do get the following error.

ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-6932' coro=<AsyncEventHandler.run() done, defined at /usr/local/lib/python3.9/dist-packages/wyoming/server.py:26> exception=ValueError("can't extend empty axis 0 using modes other than 'constant' or 'empty'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/wyoming/server.py", line 32, in run
    if not (await self.handle_event(event)):
  File "/usr/local/lib/python3.9/dist-packages/wyoming_faster_whisper/handler.py", line 61, in handle_event
    segments, _info = self.model.transcribe(
  File "/usr/local/lib/python3.9/dist-packages/wyoming_faster_whisper/faster_whisper/transcribe.py", line 124, in transcribe
    features = self.feature_extractor(audio)
  File "/usr/local/lib/python3.9/dist-packages/wyoming_faster_whisper/faster_whisper/feature_extractor.py", line 152, in __call__
    frames = self.fram_wave(waveform)
  File "/usr/local/lib/python3.9/dist-packages/wyoming_faster_whisper/faster_whisper/feature_extractor.py", line 98, in fram_wave
    frame = np.pad(frame, pad_width=padd_width, mode="reflect")
  File "<__array_function__ internals>", line 200, in pad
  File "/usr/local/lib/python3.9/dist-packages/numpy/lib/arraypad.py", line 815, in pad
    raise ValueError(
ValueError: can't extend empty axis 0 using modes other than 'constant' or 'empty'

And see this in Debug-
stage: error
run:
  pipeline: 01h1j1nkffa472206r8efnppx5
  language: en
  runner_data:
    stt_binary_handler_id: 1
    timeout: 30
events:
  - type: run-start
    data:
      pipeline: 01h1j1nkffa472206r8efnppx5
      language: en
      runner_data:
        stt_binary_handler_id: 1
        timeout: 30
    timestamp: "2023-05-30T12:24:17.634407+00:00"
  - type: stt-start
    data:
      engine: stt.faster_whisper
      metadata:
        language: en
        format: wav
        codec: pcm
        bit_rate: 16
        sample_rate: 16000
        channel: 1
    timestamp: "2023-05-30T12:24:17.634627+00:00"
  - type: error
    data:
      code: timeout
      message: Timeout running pipeline
    timestamp: "2023-05-30T12:24:47.636304+00:00"
stt:
  engine: stt.faster_whisper
  metadata:
    language: en
    format: wav
    codec: pcm
    bit_rate: 16
    sample_rate: 16000
    channel: 1
  done: false
error:
  code: timeout
  message: Timeout running pipeline

**Comment by synesthesiam** [comment]
What hardware are you running on?

**Comment by dominikhoebert** [comment]
Raspi 4B 8GB

**Comment by horizonchasers** [comment]
Im running OVA on Synology as a Virtual Machine with ample resources

**Comment by RTS007** [comment]
I have the same, cannot run on android device
