### ISSUE TITLE
Silicon Labs Multiprotocol update to 2.0.0 need Home assistant Dev version

### ISSUE THREAD

**Issue by Cl3tus** [home-assistant/addons#3073]
### Describe the issue you are experiencing

I am running everything on stable and not on dev but i got an update for the silicon labs multiprotocol. It says i can't update due to not having the correct version of Home Assistant.

Add-on core_silabs_multiprotocol not supported on this system, requires Home Assistant version 2023.6.0.dev20230531 or greater

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Almond

### What is the version of the add-on?

You have 1.1.3 installed. Click update to update to version 2.0.0

### Steps to reproduce the issue

1. Click update in addon section of Home Assistant

## System Information

version | core-2023.5.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.11
os_name | Linux
os_version | 6.1.29
arch | x86_64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4996
Installed Version | 1.32.1
Stage | running
Available Repositories | 1296
Downloaded Repositories | 44
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 9 November 2023 at 01:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | false
remote_connected | false
alexa_enabled | false
google_enabled | true
remote_server | eu-central-1-8.ui.nabu.casa
certificate_status | ready
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.2
-- | --
update_channel | stable
supervisor_version | supervisor-2023.04.1
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 503.3 GB
disk_used | 162.4 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Samba share (10.0.2), Spotify Connect (0.12.4), Studio Code Server (5.6.1), VLC (0.2.0), ESPHome (2023.5.5), Eufy Security Add-on (1.3.0), RTSP Simple Server Add-on (v0.17.6), Home Assistant Git Exporter (1.16.0), Portainer (2.18.3), Z-Wave JS UI (1.13.2), SQLite Web (3.8.0), Rclone Backup (3.0.1), Mosquitto broker (6.2.1), Advanced SSH & Web Terminal (15.0.2), Silicon Labs Multiprotocol (1.1.3), Matter Server (4.5.0), Whatsapp (1.3.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 25
views | 27
mode | storage

</details>

<details><summary>Miele</summary>

component_version | 0.1.13
-- | --
reach_miele_cloud | ok

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 24 May 2023 at 12:58
-- | --
current_recorder_run | 30 May 2023 at 20:12
estimated_db_size | 363.23 MiB
database_engine | sqlite
database_version | 3.40.1

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Anything in the Supervisor logs that might be useful for us?

```txt
Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:125
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 13:13:17 (1 occurrences)
Last logged: 13:13:17

Failed to to call /store/addons/core_silabs_multiprotocol/update - Add-on core_silabs_multiprotocol not supported on this system, requires Home Assistant version 2023.6.0.dev20230531 or greater

23-05-31 13:11:06 ERROR (MainThread) [supervisor.addons.model] Add-on core_silabs_multiprotocol not supported on this system, requires Home Assistant version 2023.6.0.dev20230531 or greater
23-05-31 13:11:16 ERROR (MainThread) [supervisor.addons.model] Add-on core_silabs_multiprotocol not supported on this system, requires Home Assistant version 2023.6.0.dev20230531 or greater
23-05-31 13:13:17 ERROR (MainThread) [supervisor.addons.model] Add-on core_silabs_multiprotocol not supported on this system, requires Home Assistant version 2023.6.0.dev20230531 or greater
```

**Comment by agners** [comment]
With the updated REST API which comes with this new release of the add-on we need the latest Home Assistant Core release.

Unfortunately, we only have a single set of metadata, which means we only can track a single version and its minimal Home Assistant Core requirement. This is a limitation of the Supervisor/Add-on system currently.

Probably best is to wait until today's 2023.6.0b0 release on the beta channel later today or the main release 2023.6.0 next week.

Keep in mind that the Silicon Labs Multiprotocol add-on is still marked experimental at this stage.

**Comment by Cl3tus** [comment]
Thank you for the clarification @agners
