### ISSUE TITLE
Silicon lab

### ISSUE THREAD

**Issue by patrizio1968** [home-assistant/addons#3077]
### Describe the issue you are experiencing

Add-on core_silabs_multiprotocol not supported on this system, requires Home Assistant version 2023.6.0.dev20230531 or greater
/

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Almond

### What is the version of the add-on?

Current version: 1.1.1

## System Information

version | core-2023.5.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.11
os_name | Linux
os_version | 6.1.29
arch | x86_64
timezone | Europe/Rome
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4546
Installed Version | 1.32.1
Stage | running
Available Repositories | 1283
Downloaded Repositories | 69

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 20 giugno 2023 alle ore 02:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | eu-central-1-4.ui.nabu.casa
certificate_status | ready
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.2
-- | --
update_channel | stable
supervisor_version | supervisor-2023.04.1
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 219.4 GB
disk_used | 13.0 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Home Assistant Google Drive Backup (0.110.4), Samba share (10.0.2), Mosquitto broker (6.2.1), ESPHome (2023.5.5), Advanced SSH & Web Terminal (15.0.2), Node-RED (14.2.2), File editor (5.6.0), Glances (0.19.2), Network UPS Tools (0.11.2), Duck DNS (1.15.0), VLC (0.2.0), Studio Code Server (5.6.1), CEC Scanner (3.0), Hey Ada! (1.2.0), Z-Wave JS UI (1.13.2), Matter Server (4.5.1), Silicon Labs Multiprotocol (1.1.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 48
views | 14
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 31 maggio 2023 alle ore 19:45
-- | --
current_recorder_run | 1 giugno 2023 alle ore 12:54
estimated_db_size | 1803.47 MiB
database_engine | sqlite
database_version | 3.40.1

</details>

<details><summary>Sonoff</summary>

version | 3.5.1 (122751c)
-- | --
cloud_online | 11 / 11
local_online | 0 / 0

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

## System Information

version | core-2023.5.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.11
os_name | Linux
os_version | 6.1.29
arch | x86_64
timezone | Europe/Rome
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4546
Installed Version | 1.32.1
Stage | running
Available Repositories | 1283
Downloaded Repositories | 69

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 20 giugno 2023 alle ore 02:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | eu-central-1-4.ui.nabu.casa
certificate_status | ready
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.2
-- | --
update_channel | stable
supervisor_version | supervisor-2023.04.1
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 219.4 GB
disk_used | 13.0 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Home Assistant Google Drive Backup (0.110.4), Samba share (10.0.2), Mosquitto broker (6.2.1), ESPHome (2023.5.5), Advanced SSH & Web Terminal (15.0.2), Node-RED (14.2.2), File editor (5.6.0), Glances (0.19.2), Network UPS Tools (0.11.2), Duck DNS (1.15.0), VLC (0.2.0), Studio Code Server (5.6.1), CEC Scanner (3.0), Hey Ada! (1.2.0), Z-Wave JS UI (1.13.2), Matter Server (4.5.1), Silicon Labs Multiprotocol (1.1.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 48
views | 14
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 31 maggio 2023 alle ore 19:45
-- | --
current_recorder_run | 1 giugno 2023 alle ore 12:54
estimated_db_size | 1803.47 MiB
database_engine | sqlite
database_version | 3.40.1

</details>

<details><summary>Sonoff</summary>

version | 3.5.1 (122751c)
-- | --
cloud_online | 11 / 11
local_online | 0 / 0

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Anything in the Supervisor logs that might be useful for us?

```txt
Logger: frontend.js.latest.202305033
Source: components/system_log/__init__.py:257
First occurred: 13:03:12 (6 occurrences)
Last logged: 13:04:33

http://homeassistant.local:8123/config/repairs?dialog=system-health:0:0 Uncaught
http://homeassistant.local:8123/hacsfiles/lovelace-media-art-background/media-art-background.js?hacstag=20287427051370:81:147 Uncaught TypeError: Cannot read properties of null (reading 'shadowRoot')
http://homeassistant.local:8123/config/logs:0:0 Uncaught
```

**Comment by agners** [comment]
See explanation in this issue: https://github.com/home-assistant/addons/issues/3073#issuecomment-1570011338

For now, you have to use a 2023.6.0 beta release or wait until next weeks final release.
