### ISSUE TITLE
Unable to install or update the Silicon Labs Multiprotocol addon

### ISSUE THREAD

**Issue by niryeffet** [home-assistant/addons#3078]
### Describe the issue you are experiencing

On a newly installed, fully updated Home Assistant, I'm seeing the following message when clicking on the "Silicon Labs Multiprotocol" addon:

You are running Home Assistant 2023.5.4, to update to this version of the add-on you need at least version 2023.6.0.dev20230531 of Home Assistant

The same message appears for existing HA with the 1.1.3 version of the addon already installed.

Released addons should not demand a dev version on HA.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Silicon Labs Multiprotocol

### What is the version of the add-on?

2.0.0

### Steps to reproduce the issue

1. Install fresh production version of home assistant.
2. Try to install the Silicon Labs Mulltiprotocol addon.

### System Health information

There are currently no repairs available

### Anything in the Supervisor logs that might be useful for us?

```txt
Home Assistant Core
There are no new issues!
```

**Comment by MattWestb** [comment]
I agree with you and its not the first time updates is being broken in the beta period and i think its not so nice done but i think very needed then doing large APT changes.

If you can waiting 3 days shall HA 2023.6.0 being released and it shall working if all is going well.

**Comment by dotgrid** [comment]
Sounds good. No worries. 👍 

Thank you for the explanation. I was wondering about this, too.

**Comment by agners** [comment]
We are aware of that problem, unfortunately allowing for beta/dev channel for add-ons requires significant changes in how add-ons are handled currently.

See also: https://github.com/home-assistant/addons/issues/3073#issuecomment-1570011338

**Comment by bert269** [comment]
I get the same error message and I am not on the beta channel for Home Assistant.

**Comment by agners** [comment]
@bert269 did you update to Home Assistant 2023.6.0? The new add-on requires at least this version.

You can continue to run the old add-on with the old HA version, but if you want to update the add-on, you need to be using the new HA version. The API between the two changed.
