### ISSUE TITLE
Whisper causes only one language (e.g. English) is listed in the Configuration language drop-down

### ISSUE THREAD

**Issue by jaymunro** [home-assistant/addons#3085]
### Describe the issue you are experiencing

As originally reported in core under #92655, “ Initially there were multiple languages available in the first dropdown when running 2023.5.0, but now only English is available.”

https://github.com/home-assistant/core/issues/92655

<img width="614" alt="Screenshot 2023-05-06 at 10 37 34 AM" src="https://user-images.githubusercontent.com/1166024/236582260-fa302b02-543f-48a3-926c-82225bc5735c.png">

I am reporting this bug again here as #92655 it did not get any labels added

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Whisper

### What is the version of the add-on?

0.2.0

### Steps to reproduce the issue

1. Install and configure the add-ons Piper & Whisper.
2. Add Wyoming integration 
3. Add discovered Piper & Whisper to Wyoming integration
4. Navigate to Settings > Voice Assistants > Chose an Assistant > Configuration > Languages
5. Confirm only English is available in the dropdown menu

Whisper config is:
```
model: tiny-int8
language: en
beam_size: 1
```

Steps to reproduce once issue is present:

1. Settings > Add-ons > Whisper > (Stop & turn off ‘Start on boot’)
2. Dev Tools > Restart > Restart Home Assistant (OS reboot not needed)
3. Wait for reboot
4. Settings > Voice Assistants > Chose an Assistant > Configuration > Languages
5. Confirm only English available in the dropdown menu
7. Swipe down to re-load in iOS app (F5 or ‘Reload’ in browser)
8. Chose an Assistant > Configuration > Languages
9. Now all languages available in the dropdown menu
10. Settings > Add-ons > Whisper > (Start)
11. Swipe down to re-load in iOS app (F5 or ‘Reload’ in browser)
12. Settings > Voice Assistants > Chose an Assistant > Configuration > Languages
13. Confirm once again only English is available in the dropdown menu

Note that a local browser reload is essential and if not done the behaviour can be confusing.

### System Health information

There are currently no repairs available

### Anything in the Supervisor logs that might be useful for us?

```txt
23-06-07 00:35:48 INFO (SyncWorker_4) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-whisper with version 0.2.0
23-06-07 00:35:49 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session e9a2a2fdc08b292b4f21a35599586feecc2d2e6ff89fa9902148cfa7de5197fc9fce6190a6d3dcc56bfeb9179697529229a6ba26e6b41acf669d93e306106adf
23-06-07 00:36:31 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session e9a2a2fdc08b292b4f21a35599586feecc2d2e6ff89fa9902148cfa7de5197fc9fce6190a6d3dcc56bfeb9179697529229a6ba26e6b41acf669d93e306106adf
```

### Anything in the add-on logs that might be useful for us?

```txt
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service whisper: starting
s6-rc: info: service whisper successfully started
s6-rc: info: service discovery: starting
INFO:__main__:Ready
[00:35:49] INFO: Successfully send discovery information to Home Assistant.
s6-rc: info: service discovery successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
```

### Additional information

Please see https://github.com/home-assistant/core/issues/92655 for further info and reports of this from other users.

**Comment by marcelhoogantink** [comment]
And now?

**Comment by jaymunro** [comment]
2023.7.1 and still only one language available

**Comment by jaymunro** [comment]
As per https://github.com/home-assistant/core/issues/92655, this is resolved.
