### ISSUE TITLE
Silicon Labs Multiprotocol fails to start otbr-agent

### ISSUE THREAD

**Issue by ginkage** [home-assistant/addons#3088]
### Describe the issue you are experiencing

I'm getting the following error in the log:
```
[20:47:02] INFO: Setup OTBR firewall...
ip6tables v1.8.7 (nf_tables): Couldn't load match `set':No such file or directory

Try `ip6tables -h' or 'ip6tables --help' for more information.
[20:47:02] INFO: otbr-agent ended with exit code 2 (signal 0)...
OTBR_FORWARD_INGRESS  all opt    in * out wpan0  ::/0  -> ::/0  
Chain OTBR_FORWARD_INGRESS (0 references)
target     prot opt source               destination         
DROP       all      anywhere             anywhere             PKTTYPE = unicast
otbr-ingress-deny-src
otbr-ingress-deny-src-swap
otbr-ingress-allow-dst
otbr-ingress-allow-dst-swap
[20:47:02] INFO: OTBR firewall teardown completed.
```
Looks like the add-on is trying to use nftables, though it was designed for legacy iptables...

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Almond

### What is the version of the add-on?

2.1.0

### Steps to reproduce the issue

1. Flash and connect the dongle
2. Install Silicon Labs Multiprotocol add-on
3. Start the add-on

## System Information

version | core-2023.6.0
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.3
os_name | Linux
os_version | 6.1.29
arch | aarch64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4459
Installed Version | 1.32.1
Stage | running
Available Repositories | 1286
Downloaded Repositories | 16

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 17 January 2024 at 00:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
remote_server | eu-central-1-6.ui.nabu.casa
certificate_status | ready
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 11 (bullseye)
-- | --
update_channel | stable
supervisor_version | supervisor-2023.06.1
agent_version | 1.5.1
docker_version | 24.0.1
disk_total | 114.6 GB
disk_used | 56.4 GB
healthy | true
supported | true
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.2.1), Zigbee2MQTT (1.31.1-1), Advanced SSH & Web Terminal (15.0.2), File editor (5.6.0), Let's Encrypt (4.12.9), Node-RED (14.2.2), Grafana (8.3.0), InfluxDB (4.7.0), ESPHome (2023.5.5), Frigate (Full Access) (0.12.0), Matter Server (4.6.0), Silicon Labs Multiprotocol (2.1.0), Silicon Labs Flasher (0.1.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 3
views | 2
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 28 May 2023 at 19:16
-- | --
current_recorder_run | 7 June 2023 at 20:42
estimated_db_size | 1851.23 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

<details><summary>Xiaomi Miot Auto</summary>

component_version | 0.7.9
-- | --
can_reach_server | pending
can_reach_spec | ok
logged_accounts | 0
total_devices | 0

</details>

### Anything in the Supervisor logs that might be useful for us?

```txt
Log Details (ERROR)
Logger: homeassistant
Source: components/otbr/config_flow.py:36
First occurred: 20:43:08 (1 occurrences)
Last logged: 20:43:08

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1085, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1069, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 973, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 634, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 674, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('172.30.32.1', 8081)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 845, in async_init
    flow, result = await task
                   ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 873, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/otbr/config_flow.py", line 120, in async_step_hassio
    await self._connect_and_set_dataset(url)
  File "/usr/src/homeassistant/homeassistant/components/otbr/config_flow.py", line 36, in _connect_and_set_dataset
    if await api.get_active_dataset_tlvs() is None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/python_otbr_api/__init__.py", line 75, in get_active_dataset_tlvs
    response = await self._session.get(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host core-silabs-multiprotocol:8081 ssl:default [Connect call failed ('172.30.32.1', 8081)]
```

**Comment by ginkage** [comment]
Sorry, the nf/legacy tables is indeed irrelevant here (fwiw, legacy tables would print the same error).
Looks like the questionnaire wasn't handled correctly, as some of my answers got garbled... Anyway, I'm running HA Supervised (2023.6.1), not HAOS, on an Odroid N2+, with a Debian Bullseye and kernel 6.1.29.

**Comment by agners** [comment]
Hm, Debian Bullseye should be using iptables with nf_tabels by default, afaik. Can you double check with `iptables -v` on your host?

What I've had previously that incomplete/broken iptables/ipset's caused problems. Can you reproduce this after a restart?

**Comment by ginkage** [comment]
The host system seems to be using legacy tables on my machine... Should I switch to nf_tables and restart then?

So far the problem was reproduced consistently. What do you mean by incomplete iptables/ipset's though, is there any extra setup that should be performed?

**Comment by ginkage** [comment]
OK, so now the host definitely has nf_tables by default, but I'm still getting exactly the same error.

**Comment by ginkage** [comment]
Basically, yes to all of the above: rebooted the board, same problem, all requirements are met, it is a vanilla Debian Bullseye.

Ipset seems to be present: all kernel modules are loaded, ipset command works.

**Comment by agners** [comment]
I am guessing it fails on this line:

```
ip6tables -A $otbr_forward_ingress_chain -m set --match-set otbr-ingress-deny-src src -j DROP
```

The most plausible explanation is still some kernel config. Can you check if `CONFIG_NET_EMATCH_IPSET` is enabled?

What is `uname -a` saying? Where did you get the image from?

**Comment by ginkage** [comment]
In my config I have:
```
CONFIG_NET_EMATCH=y
CONFIG_NET_EMATCH_STACK=32
CONFIG_NET_EMATCH_IPSET=m
CONFIG_NET_EMATCH_IPT=m
```
`uname -a`:
```
Linux hassodroid 6.1.29 #1 SMP PREEMPT Mon Jun 12 13:55:54 BST 2023 aarch64 GNU/Linux
```
It's an image built with https://github.com/pyavitz/debian-image-builder

**Comment by ginkage** [comment]
Yay, `CONFIG_NETFILTER_XT_SET` seems to have done the trick! Thank you so much!

BTW, there's hardly such a thing as "real" Debian Bullseye, since we're talking about kernel image for a specific board (you have to make those yourself). I think in this case the source of truth is the HASSOS kernel config: https://github.com/home-assistant/operating-system/blob/dev/buildroot-external/kernel/hassos.config#L119 — I've double-checked to include that I have all other relevant modules enabled as well.

Thanks again!
