### ISSUE TITLE
Let's encrypt addon ignoring alternative port for http challenge

### ISSUE THREAD

**Issue by skirit** [home-assistant/addons#3089]
### Describe the issue you are experiencing

Certboot always try to connect to port 80 and ignore alternative setting for tcp port.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Let's Encrypt

### What is the version of the add-on?

4.12.9

### Steps to reproduce the issue

1. "Change the ports on your host that are exposed by the add-on" set to port 8888
2. Start add-on
3. get:
```
Requesting a certificate for xx.xxxx.xx
Certbot failed to authenticate some domains (authenticator: standalone). The Certificate Authority reported these problems:
  Domain: xx.xxxx.xx
  Type:   unauthorized
  Detail: y.y.y.y: Invalid response from http://xx.xxxx.xx/.well-known/acme-challenge/Xqr8SbHAi4bhQPnFDXaprKMZhMzk6PyKMGPueF2SpoY: 404
Hint: The Certificate Authority failed to download the challenge files from the temporary standalone webserver started by Certbot on port 80. Ensure that the listed domains point to this machine and that it can accept inbound connections from the internet.
Some challenges have failed.
```

### System Health information

Version | core-2023.6.0
-- | --
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.11.3
Operating System Family | Linux
Operating System Version | 6.1.29
CPU Architecture | x86_64
Timezone | Europe/Prague
Configuration Directory | /config

**Comment by edgimar** [comment]
This was also brought up in https://github.com/home-assistant/addons/issues/1742, which was closed due to inactivity.
