### ISSUE TITLE
mosquitto missing in addon store

### ISSUE THREAD

**Issue by ciclocaffe** [home-assistant/addons#3092]
### Describe the issue you are experiencing

Mosquitto is missing from the addon store. I was on 5.4 now updated to 6.1 and still missing.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### Which add-on are you reporting an issue with?

Mosquitto broker

### What is the version of the add-on?

none

### Steps to reproduce the issue

1. settings > add-ons > add-ons store
2. mosquitto broker missing from the list

## System Information

version | core-2023.6.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.3
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | Europe/Rome
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4939
Installed Version | 1.32.1
Stage | running
Available Repositories | 1283
Downloaded Repositories | 2

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.2
-- | --
update_channel | stable
supervisor_version | supervisor-2023.06.1
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 56.6 GB
disk_used | 5.4 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Advanced SSH & Web Terminal (15.0.2), Duck DNS (1.15.0), File editor (5.6.0), Home Assistant Google Drive Backup (0.110.4), Log Viewer (0.15.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
views | 2
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 1 June 2023 at 08:05
-- | --
current_recorder_run | 9 June 2023 at 20:13
estimated_db_size | 18.64 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

**Comment by agners** [comment]
Can you share the Supervisor logs? Are other add-ons available? What Home Assistant OS version are you using?

**Comment by ciclocaffe** [comment]
today I checked again...and now the whole addon store disappeared..

log:

Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:125
Integration: Home Assistant Supervisor ([documentation](https://www.home-assistant.io/integrations/hassio), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+hassio%22))
First occurred: 12 June 2023 at 11:10:01 (9 occurrences)
Last logged: 14:25:58

    Failed to to call /store/repositories - Can't add https://github.com/hassio-addons/repository, already in the store
    Failed to to call /store/repositories - Cmd('git') failed due to: exit code(128) cmdline: git clone -v --recursive --depth=1 --shallow-submodules -- http://github.com/hassio-addons/repository /data/addons/git/e399101c stderr: 'Cloning into '/data/addons/git/e399101c'... fatal: unable to access 'http://github.com/hassio-addons/repository/': Could not resolve host: github.com '
    Failed to to call /addons/reload - string index out of range
    Failed to to call /store/repositories - Cmd('git') failed due to: exit code(128) cmdline: git clone -v --recursive --depth=1 --shallow-submodules -- https://github.com/hassio-addons/repository, /data/addons/git/4573322f stderr: 'Cloning into '/data/addons/git/4573322f'... fatal: unable to access 'https://github.com/hassio-addons/repository,/': Could not resolve host: github.com '
    Failed to to call /network/interface/wlan0/update - Activating connection failed, check connection settings.

**Comment by agners** [comment]
> Could not resolve host: github.com

It seems you system has a DNS error. Can you check `ha network info`. Maybe a restart helps?

**Comment by ciclocaffe** [comment]
docker:                                                                                                                                                   
  address: 172.30.32.0/23                                                                                                                                 
  dns: 172.30.32.3                                                                                                                                        
  gateway: 172.30.32.1                                                                                                                                    
  interface: hassio                                                                                                                                       
host_internet: true                                                                                                                                       
interfaces:                                                                                                                                               
- connected: false                                                                                                                                        
  enabled: false                                                                                                                                          
  interface: eth0                                                                                                                                         
  ipv4:                                                                                                                                                   
    address: []                                                                                                                                           
    gateway: null                                                                                                                                         
    method: disabled                                                                                                                                      
    nameservers: []                                                                                                                                       
    ready: false                                                                                                                                          
ipv6:
    address: []
    gateway: null
    method: disabled
    nameservers: []
    ready: false
  primary: false
  type: ethernet
  vlan: null
  wifi: null
- connected: true
  enabled: true
  interface: wlan0
  ipv4:
    address:
    - 192.168.1.12/24
    gateway: 192.168.1.1
    method: auto
    nameservers:
    - 192.168.1.1
    ready: true
  ipv6:
    address:
    - fe80::7458:5caa:7a77:ada/64
    gateway: null
    method: auto
    nameservers: []
    ready: false
  primary: true
  type: wireless
  vlan: null
  wifi:
    auth: wpa-psk
    mode: infrastructure
    signal: 61
    ssid: D-Link-40134C
supervisor_internet: true                                                                                                                             Fri 06-16 14:12

**Comment by ciclocaffe** [comment]
ok I changed dns to 8.8.8.8 and at least I see the addons are back..except for mosquitto. Isn't there a way to manually add it from the terminal?

**Comment by comercy** [comment]
I also have this problem with Home Assistant 2023.6.2. Anyway to install it manually?

**Comment by ciclocaffe** [comment]
bump

**Comment by agners** [comment]
Can you go to Settings -> Add-ons  -> Add-on Store and click on the top right menu then "Check for updates".

Wait for a few seconds and press Ctrl+F5 to ensure a full page reload, just to be sure (this should not be necessary).

If the Mosquitto Add-on is still missing, can you share the Supervisor log?

**Comment by ciclocaffe** [comment]
Hello,
reinstalled everything from scratch, still same issue, mosquitto disappeared completely.
Supervisor log.

`[32m23-11-19 11:53:34 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information[0m
[32m23-11-19 11:53:34 INFO (MainThread) [supervisor.host.manager] Host information reload completed[0m
[32m23-11-19 11:55:22 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository[0m
[32m23-11-19 11:55:22 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/sabeechen/hassio-google-drive-backup repository[0m
[31m23-11-19 11:55:23 ERROR (MainThread) [supervisor.store.git] Can't update https://github.com/sabeechen/hassio-google-drive-backup repo: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch -v --update-shallow --depth=1 -- origin
  stderr: 'fatal: unable to access 'https://github.com/sabeechen/hassio-google-drive-backup/': Could not resolve host: github.com'.[0m
[32m23-11-19 11:55:23 INFO (MainThread) [supervisor.resolution.module] Create new suggestion execute_reset - store / cebe7a76[0m
[32m23-11-19 11:55:23 INFO (MainThread) [supervisor.resolution.module] Create new issue corrupt_repository - store / cebe7a76[0m
[31m23-11-19 11:55:23 ERROR (MainThread) [supervisor.store.git] Can't update https://github.com/hassio-addons/repository repo: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch -v --update-shallow --depth=1 -- origin
  stderr: 'fatal: unable to access 'https://github.com/hassio-addons/repository/': Could not resolve host: github.com'.[0m
[33m23-11-19 11:55:24 WARNING (MainThread) [supervisor.store.git] No valid repository for https://github.com/home-assistant/addons[0m
[32m23-11-19 11:55:24 INFO (MainThread) [supervisor.store] Loading add-ons from store: 41 all - 1 new - 0 remove[0m
[32m23-11-19 11:55:24 INFO (MainThread) [supervisor.store] Loading add-ons from store: 41 all - 0 new - 0 remove[0m
[31m23-11-19 11:55:24 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-383094' coro=<Repository.update() done, defined at /usr/src/supervisor/supervisor/store/repository.py:104> exception=StoreGitError()>[0m
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/git.py", line 136, in pull
    await self.sys_run_in_executor(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/git/remote.py", line 1014, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress, kill_after_timeout=kill_after_timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/git/remote.py", line 853, in _get_fetch_info_from_stderr
    proc.wait(stderr=stderr_text)
  File "/usr/local/lib/python3.11/site-packages/git/cmd.py", line 600, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch -v --update-shallow --depth=1 -- origin
  stderr: 'fatal: unable to access 'https://github.com/sabeechen/hassio-google-drive-backup/': Could not resolve host: github.com'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/repository.py", line 108, in update
    await self.git.pull()
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 296, in wrapper
    raise err
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 289, in wrapper
    return await self._method(obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/store/git.py", line 178, in pull
    raise StoreGitError() from err
supervisor.exceptions.StoreGitError
[31m23-11-19 11:55:24 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-383093' coro=<Repository.update() done, defined at /usr/src/supervisor/supervisor/store/repository.py:104> exception=StoreGitError()>[0m
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/git.py", line 136, in pull
    await self.sys_run_in_executor(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/git/remote.py", line 1014, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress, kill_after_timeout=kill_after_timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/git/remote.py", line 853, in _get_fetch_info_from_stderr
    proc.wait(stderr=stderr_text)
  File "/usr/local/lib/python3.11/site-packages/git/cmd.py", line 600, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch -v --update-shallow --depth=1 -- origin
  stderr: 'fatal: unable to access 'https://github.com/hassio-addons/repository/': Could not resolve host: github.com'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/repository.py", line 108, in update
    await self.git.pull()
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 296, in wrapper
    raise err
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 289, in wrapper
    return await self._method(obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/supervisor/supervisor/store/git.py", line 178, in pull
    raise StoreGitError() from err
supervisor.exceptions.StoreGitError
[33m23-11-19 11:56:34 WARNING (MainThread) [supervisor.store.git] No valid repository for https://github.com/home-assistant/addons[0m
[32m23-11-19 11:56:34 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository[0m
[32m23-11-19 11:56:34 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/sabeechen/hassio-google-drive-backup repository[0m
[32m23-11-19 11:56:35 INFO (MainThread) [supervisor.store] Loading add-ons from store: 41 all - 0 new - 0 remove[0m
[32m23-11-19 11:56:35 INFO (MainThread) [supervisor.store] Loading add-ons from store: 41 all - 0 new - 0 remove[0m
[33m23-11-19 11:57:27 WARNING (MainThread) [supervisor.store.git] No valid repository for https://github.com/home-assistant/addons[0m
[32m23-11-19 11:57:27 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository[0m
[32m23-11-19 11:57:27 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/sabeechen/hassio-google-drive-backup repository[0m
[32m23-11-19 11:57:28 INFO (MainThread) [supervisor.store] Loading add-ons from store: 41 all - 0 new - 0 remove[0m
[32m23-11-19 11:57:28 INFO (MainThread) [supervisor.store] Loading add-ons from store: 41 all - 0 new - 0 remove[0m
[33m23-11-19 12:01:06 WARNING (MainThread) [supervisor.store.git] No valid repository for https://github.com/home-assistant/addons[0m
[32m23-11-19 12:01:06 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository[0m
[32m23-11-19 12:01:06 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/sabeechen/hassio-google-drive-backup repository[0m
[32m23-11-19 12:01:08 INFO (MainThread) [supervisor.store] Loading add-ons from store: 41 all - 0 new - 0 remove[0m
[32m23-11-19 12:01:08 INFO (MainThread) [supervisor.store] Loading add-ons from store: 41 all - 0 new - 0 remove[0m
[32m23-11-19 12:01:39 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json[0m
[33m23-11-19 12:01:39 WARNING (MainThread) [supervisor.store.git] No valid repository for https://github.com/home-assistant/addons[0m
[32m23-11-19 12:01:39 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository[0m
[32m23-11-19 12:01:39 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/sabeechen/hassio-google-drive-backup repository[0m
[32m23-11-19 12:01:40 INFO (MainThread) [supervisor.store] Loading add-ons from store: 41 all - 0 new - 0 remove[0m
[32m23-11-19 12:01:40 INFO (MainThread) [supervisor.store] Loading add-ons from store: 41 all - 0 new - 0 remove[0m
`

While you investigate are there any instructions to install mosquitto manually?
