### ISSUE TITLE
OpenThread addon not starting

### ISSUE THREAD

**Issue by brugk000** [home-assistant/addons#3102]
### Describe the issue you are experiencing

Addon is not starting due rcp failure.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Almond

### What is the version of the add-on?

2.2.0

### Steps to reproduce the issue

1.
2.
3.
...

## System Information

version | core-2023.6.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.3
os_name | Linux
os_version | 6.1.28
arch | x86_64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.0.dev20230511
-- | --
update_channel | stable
supervisor_version | supervisor-2023.06.2
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 30.8 GB
disk_used | 5.6 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | ESPHome (2022.3.1), TimescaleDB (2.1.1), Terminal & SSH (9.7.1), OpenThread Border Router (2.2.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 12 juni 2023 om 18:38
-- | --
current_recorder_run | 15 juni 2023 om 11:19
estimated_db_size | 9.90 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Anything in the add-on logs that might be useful for us?

```txt
[11:29:20] INFO: Starting otbr-agent...
otbr-agent[11512]: [NOTE]-AGENT---: Running 0.3.0-f46f689-dirty
otbr-agent[11512]: [NOTE]-AGENT---: Thread version: 1.3.0
otbr-agent[11512]: [NOTE]-AGENT---: Thread interface: wpan0
otbr-agent[11512]: [NOTE]-AGENT---: Radio URL: spinel+hdlc+uart:///dev/ttyACM0?uart-baudrate=460800
otbr-agent[11512]: [NOTE]-ILS-----: Infra link selected: enp0s18
otbr-agent[11512]: [INFO]-NCP-----: OpenThread log level changed to 5
otbr-agent[11512]: 49d.17:13:53.389 [W] Platform------: Wait for response timeout
otbr-agent[11512]: 49d.17:13:53.389 [I] Platform------: Software reset RCP successfully
otbr-agent[11512]: 49d.17:13:55.391 [W] Platform------: Wait for response timeout
otbr-agent[11512]: 49d.17:13:55.392 [C] Platform------: Failed to communicate with RCP - no response from RCP during initialization
otbr-agent[11512]: 49d.17:13:55.392 [C] Platform------: This is not a bug and typically due a config error (wrong URL parameters) or bad RCP image:
otbr-agent[11512]: 49d.17:13:55.392 [C] Platform------: - Make sure RCP is running the correct firmware
otbr-agent[11512]: 49d.17:13:55.392 [C] Platform------: - Double check the config parameters passed as `RadioURL` input
otbr-agent[11512]: 49d.17:13:55.392 [C] Platform------: HandleRcpTimeout() at radio_spinel_impl.hpp:2309: RadioSpinelNoResponse
[11:29:24] INFO: otbr-agent ended with exit code 6 (signal 0)...
```

### Additional information

Running HassOS on proxmox with usb passtrough

**Comment by agners** [comment]
What type of radio are you using? If you are using Home Assistant SkyConnect or Home Assistant Yellow, do you have the "Automatically flash firmware" option set to on?

**Comment by brugk000** [comment]
I am using the ZBDongle-E dongle with the latest formware from Darkxst

**Comment by darkxst** [comment]
I'd be guessing its maybe wrong or older firmware? @brugk000 what version do you have installed?

This is the latest build that is required for 2.2.0, and seems to work fine here.
https://github.com/darkxst/silabs-firmware-builder/blob/main/firmware_builds/zbdonglee/ot-rcp-v2.3.0.0-zbdonglee-460800.gbl

**Comment by brugk000** [comment]
I have installed the latest firmware 4.3.0 this morning

**Comment by darkxst** [comment]
Did this stop working on upgrade to 2.2 or is it a new install?

**Comment by brugk000** [comment]
Its a new install with a new dongle from Sonoff

**Comment by darkxst** [comment]
This error occurs when it fails to establish the initial serial connection to dongle. I'm inclined to think its a configuration issue here.
Are you sure you have the OpenThread RCP firmware and not the Multipan RCP firmware?  Also check your baudrate matches and hardware flow control is off.

If all that is correct, then is the USB pass through working correctly?

**Comment by brugk000** [comment]
Me bad, sorry. I flashed the dongle as per these instructions: https://smarthomescene.com/guides/how-to-enable-thread-and-matter-support-on-sonoff-zbdongle-e
Try to start the openthread addon and missed the part that I had to use the silicon labs addon. Can confirm tho that this is working. Again sorry for your time wasted

**Comment by darkxst** [comment]
indeed you need to select the correct firmware in the Web Flasher
MultiPan RCP is for Silabs Multiprotocol Addon
Openthread RCP is for this Addon

**Comment by brugk000** [comment]
Changed the firmware to OpenThread and the addon is working.
Thanks again
