### ISSUE TITLE
ImportError: cannot import name 'getargspec' from 'inspect' in vlc component

### ISSUE THREAD

**Issue by samex** [home-assistant/addons#3103]
Hello Team,

I'm encountering an issue with the VLC component of Home Assistant. But it looks like VLC is not the problem, its python3.11/inspect.py.

Upon running the program, it throws an error related to the importing of the 'getargspec' module from 'inspect'. The specific error message is as follows:

```
File "/usr/src/homeassistant/homeassistant/components/vlc/media_player.py", line 7, in 
  import vlc
File "/usr/local/lib/python3.11/site-packages/vlc.py", line 49, in 
  from inspect import getargspec
ImportError: cannot import name 'getargspec' from 'inspect' (/usr/local/lib/python3.11/inspect.py)

```

This issue is observed in Python 3.11 environment.

Any help in troubleshooting this issue would be highly appreciated. Let me know if you need any additional information to better understand or replicate the problem.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

VLC

### What is the version of the add-on?

0.2.0

### Steps to reproduce the issue

1. Look in to Logviewer Addon - happens on of after boot

## System Information

version | core-2023.6.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4962
Installed Version | 1.31.0
Stage | running
Available Repositories | 1283
Downloaded Repositories | 2

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.2
-- | --
update_channel | stable
supervisor_version | supervisor-2023.06.2
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 116.8 GB
disk_used | 10.7 GB
healthy | true
supported | true
board | rpi3-64
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.7.1), ESPHome (2023.5.5), Mosquitto broker (6.2.1), Spotify Connect (0.12.4), Node-RED (14.2.2), AirCast (3.5.3), File editor (5.6.0), RPC Shutdown (2.4), Hey Ada! (1.2.0), VLC (0.2.0), CEC Scanner (3.0), ZeroTier One (0.16.3), Log Viewer (0.15.1), AdGuard Home (4.8.10)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
views | 3
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 6. Juni 2023 um 03:38
-- | --
current_recorder_run | 16. Juni 2023 um 09:40
estimated_db_size | 7.84 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Anything in the Supervisor logs that might be useful for us?

```txt
2023-06-16 09:43:00.102 ERROR (MainThread) [homeassistant.config] Platform error: media_player
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config.py", line 928, in async_process_component_config
platform = p_integration.get_platform(domain)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/loader.py", line 833, in get_platform
cache[full_name] = self._import_platform(platform_name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/loader.py", line 850, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 940, in exec_module
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "/usr/src/homeassistant/homeassistant/components/vlc/media_player.py", line 7, in <module>
import vlc
File "/usr/local/lib/python3.11/site-packages/vlc.py", line 49, in <module>
from inspect import getargspec
ImportError: cannot import name 'getargspec' from 'inspect' (/usr/local/lib/python3.11/inspect.py)
```

**Comment by MartinHjelmare** [comment]
The VLC add-on isn't meant to be used with the `vlc` integration. It's meant for the `vlc_telnet` integration.
