### ISSUE TITLE
Swedish voice missing

### ISSUE THREAD

**Issue by fredamn76** [home-assistant/addons#3105]
### Describe the issue you are experiencing

Piper has a (sv-se) voice but it is missing in the Piper addon.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Piper

### What is the version of the add-on?

0.1.3 

### Steps to reproduce the issue

1. Installed latest version 0.1.3
2. Tried to set swedish voice in addon settings but its missing
3.
4.
...

## System Information

version | core-2023.6.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.34
arch | x86_64
timezone | Europe/Stockholm
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4991
Installed Version | 1.32.1
Stage | running
Available Repositories | 1288
Downloaded Repositories | 121

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 1 januari 2018 kl. 01:00
relayer_connected | false
relayer_region | null
remote_enabled | false
remote_connected | false
alexa_enabled | false
google_enabled | true
remote_server | null
certificate_status | null
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.3
-- | --
update_channel | beta
supervisor_version | supervisor-2023.06.2
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 73.1 GB
disk_used | 36.3 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Samba share (10.0.2), Home Assistant Google Drive Backup (0.110.4), Terminal & SSH (9.7.1), Mosquitto broker (6.2.1), Matter Server (4.6.0), MariaDB (2.6.1), Zigbee2MQTT (1.31.2-1), Crowdsec Firewall Bouncer (v0.0.26-ha2), ESPHome (2023.5.5), Grocy (0.19.1), Music Assistant BETA (2.0.0b38), Piper (0.1.3), Studio Code Server (5.6.2), Whisper (0.2.0), Eufy Security Add-on (1.3.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 9
-- | --
resources | 73
views | 120
mode | storage

</details>

<details><summary>NextDNS</summary>

can_reach_server | ok
-- | --

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 15 juni 2023 kl. 04:20
-- | --
current_recorder_run | 18 juni 2023 kl. 09:10
estimated_db_size | 624.84 MiB
database_engine | mysql
database_version | 10.6.12

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

<details><summary>Xiaomi MIoT</summary>

logged_in | true
-- | --
can_reach_micloud_server | ok
accounts_count | 1
account_devices_count | 3
added_devices | 1

</details>

**Comment by albinmedoc** [comment]
Still missing. They showed Swedish as an available language in the livestream today (Year of the Voice, Chapter 3)

**Comment by Skrufen** [comment]
Still missing as of 2023.7.3

**Comment by newlund** [comment]
+1

**Comment by MHultman** [comment]
Still missing.

**Comment by albinmedoc** [comment]
@synesthesiam, is this just an error inte the select input?
Will Swedish work if it's added as an option?

**Comment by synesthesiam** [comment]
The new voices will be available with 2023.8 and a Piper add-on update.

Unfortunately, I had to break backwards compatibility with 2023.7, so I'm waiting for 2023.8 so people can keep installing the existing add-on 🫤

**Comment by tomaszpieczykolan** [comment]
Related #3126
