### ISSUE TITLE
SkyConnect not detected when using THREAD only firmware

### ISSUE THREAD

**Issue by austwhite** [home-assistant/addons#3110]
### Describe the issue you are experiencing

Not sure if this is fully implemented yet, but I noticed on the Firmware site for the SkyConnect that there is a Thread only firmware.  If this is installed, Home Assistant will not detect the SkyConnect and the OTBR is unable to utilise the SkyConnect as a Thread radio.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Almond

### What is the version of the add-on?

Current version (won't install with the fault described)

### Steps to reproduce the issue

1. Install Thread Only firmware on SkyConnect ( completes successfully)
2. Install SkyConnect via USB to Home Assistant OS device ( Yellow, Intel NUC, Raspberry Pi 4 tried)
3. Try to install Open Thread Border Router
...

## System Information

version | core-2023.6.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | Australia/Sydney
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.3
-- | --
update_channel | stable
supervisor_version | supervisor-2023.06.2
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 233.0 GB
disk_used | 5.7 GB
healthy | true
supported | true
board | yellow
supervisor_api | ok
version_api | ok
installed_addons | ESPHome (2023.6.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
mode | auto-gen

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | June 22, 2023 at 10:48 AM
-- | --
current_recorder_run | June 23, 2023 at 12:59 PM
estimated_db_size | 2.06 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Anything in the add-on logs that might be useful for us?

```txt

```

### Additional information

I am not sure if this is fully implemented as I have found little documentation on it.
Please let me know if I am just jumping the gun a bit on this one :)

**Comment by darkxst** [comment]
It is implemented but you need to install and configure this addon:
https://github.com/home-assistant/addons/blob/master/openthread_border_router/DOCS.md

Once that is running, the Openthread Border Router integration in Home Assistant should pick it up automatically.

**Comment by austwhite** [comment]
Unchecked it out.   Seems to be available on my Intel system but not on the HA Yellow.

**Comment by darkxst** [comment]
It is supported on the Yellow. Do you have advanced mode enabled in your user profile?

**Comment by austwhite** [comment]
I'll check all the setup on the yellow tonight.
Thanks for all the information and help 😊

**Comment by austwhite** [comment]
Seems it is appearing there.  I'll close this now and thank you for your help and support.
