### ISSUE TITLE
OpenThread not starting

### ISSUE THREAD

**Issue by dworkin74** [home-assistant/addons#3123]
### Describe the issue you are experiencing

Addon is not starting due rcp failure.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Almond

### What is the version of the add-on?

2.2.0

### Steps to reproduce the issue

Just trying to start

## System Information

version | core-2023.6.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.34
arch | x86_64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4614
Installed Version | 1.32.1
Stage | running
Available Repositories | 1350
Downloaded Repositories | 61

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 6 juli 2023 om 02:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | false
remote_server | eu-central-1-10.ui.nabu.casa
certificate_status | ready
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.3
-- | --
update_channel | stable
supervisor_version | supervisor-2023.06.4
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 457.7 GB
disk_used | 49.4 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (10.0.2), MariaDB (2.6.1), AirSonos (3.5.4), AppDaemon (0.13.1), Check Home Assistant configuration (3.11.0), Glances (0.19.2), Grafana (8.3.0), Nginx Proxy Manager (0.12.3), Advanced SSH & Web Terminal (15.0.2), Studio Code Server (5.8.0), WireGuard (0.8.1), phpMyAdmin (0.8.6), Samba Backup (5.0.0), InfluxDB (4.7.0), Z-Wave JS (0.1.84), Let's Encrypt with Lexicon (3.0.2), Mosquitto broker (6.2.1), Zigbee2MQTT (1.31.2-1), Node-RED (14.2.2), Z-Wave JS UI (1.13.4), Matter Server (4.8.2), ESPHome (2023.6.3), TimescaleDB (2.1.1), pgAdmin4 (2.1.1), DSMR Reader (1.10.1), DSMR Datalogger (1.1.0), OpenThread Border Router (2.2.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 48
views | 24
mode | storage

</details>

<details><summary>NextDNS</summary>

can_reach_server | ok
-- | --

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 15 juni 2023 om 10:50
-- | --
current_recorder_run | 29 juni 2023 om 12:20
database_engine | mysql
database_version | 10.6.12

</details>

### Anything in the add-on logs that might be useful for us?

```txt
s6-rc: info: service mdns: starting
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service mdns successfully started
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service banner: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
[12:35:22] INFO: Starting mDNS Responder...
Default: mDNSResponder (Engineering Build) (Jun 13 2023 13:29:39) starting
Default: mDNS_AddDNSServer: Lock not held! mDNS_busy (0) mDNS_reentrancy (0)
-----------------------------------------------------------
 Add-on: OpenThread Border Router
 OpenThread Border Router add-on
-----------------------------------------------------------
 Add-on version: 2.2.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.3  (amd64 / generic-x86-64)
 Home Assistant Core: 2023.6.3
 Home Assistant Supervisor: 2023.06.4
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service banner successfully started
s6-rc: info: service universal-silabs-flasher: starting
[12:35:22] INFO: Checking /dev/ttyUSB1 identifying SkyConnect v1.0 from Nabu Casa.
[12:35:22] INFO: Starting universal-silabs-flasher with /dev/ttyUSB1
2023-06-29 12:35:23 homeassistant universal_silabs_flasher.flash[150] INFO Extracted GBL metadata: NabuCasaMetadata(metadata_version=1, sdk_version='4.3.0', ezsp_version=None, ot_rcp_version='SL-OPENTHREAD/2.3.0.0_GitHub-dae3ff2c5' (2.3.0.0), fw_type=<FirmwareImageType.OT_RCP: 'ot-rcp'>, baudrate=460800)
2023-06-29 12:35:23 homeassistant universal_silabs_flasher.flasher[150] INFO Probing ApplicationType.GECKO_BOOTLOADER at 115200 baud
2023-06-29 12:35:25 homeassistant universal_silabs_flasher.flasher[150] INFO Probing ApplicationType.SPINEL at 460800 baud
2023-06-29 12:35:25 homeassistant universal_silabs_flasher.flasher[150] INFO Detected ApplicationType.SPINEL, version 'SL-OPENTHREAD/2.3.0.0_GitHub-dae3ff2c5' (2.3.0.0) at 460800 baudrate (bootloader baudrate None)
2023-06-29 12:35:25 homeassistant universal_silabs_flasher.flash[150] INFO Firmware version 'SL-OPENTHREAD/2.3.0.0_GitHub-dae3ff2c5' (2.3.0.0) is flashed, not re-installing
s6-rc: info: service universal-silabs-flasher successfully started
s6-rc: info: service otbr-agent: starting
[12:35:25] INFO: Starting otbr-agent...
otbr-agent[182]: [NOTE]-AGENT---: Running 0.3.0-f46f689-dirty
otbr-agent[182]: [NOTE]-AGENT---: Thread version: 1.3.0
otbr-agent[182]: [NOTE]-AGENT---: Thread interface: wpan0
otbr-agent[182]: [NOTE]-AGENT---: Radio URL: spinel+hdlc+uart:///dev/ttyUSB1?uart-baudrate=115200&uart-flow-control
otbr-agent[182]: [NOTE]-ILS-----: Infra link selected: eno1
otbr-agent[182]: 49d.17:19:32.545 [W] Platform------: Wait for response timeout
otbr-agent[182]: 49d.17:19:34.547 [W] Platform------: Wait for response timeout
otbr-agent[182]: 49d.17:19:34.548 [C] Platform------: Failed to communicate with RCP - no response from RCP during initialization
otbr-agent[182]: 49d.17:19:34.548 [C] Platform------: This is not a bug and typically due a config error (wrong URL parameters) or bad RCP image:
otbr-agent[182]: 49d.17:19:34.548 [C] Platform------: - Make sure RCP is running the correct firmware
otbr-agent[182]: 49d.17:19:34.548 [C] Platform------: - Double check the config parameters passed as `RadioURL` input
otbr-agent[182]: 49d.17:19:34.548 [C] Platform------: HandleRcpTimeout() at radio_spinel_impl.hpp:2309: RadioSpinelNoResponse
[12:35:29] INFO: otbr-agent ended with exit code 6 (signal 0)...
[12:35:29] INFO: OTBR firewall teardown completed.
```

### Additional information

I am running the OpenThread RCP built

**Comment by darkxst** [comment]
> ```
> otbr-agent[182]: [NOTE]-AGENT---: Radio URL: spinel+hdlc+uart:///dev/ttyUSB1?uart-baudrate=115200&uart-flow-control
> ```
Can you check your baudrate setting? This should be set to 460800, but appears to currently be 115200, hence why RCP connection fails.

**Comment by dworkin74** [comment]
Thank you. That fixed the issue
