### ISSUE TITLE
Add ukrainian_tts / medium voice option

### ISSUE THREAD

**Issue by KuzmaTolyanuch** [home-assistant/addons#3126]
### Describe the issue you are experiencing

There is an additional ukrainian voice available:
https://huggingface.co/rhasspy/piper-voices/tree/main/uk/uk_UK/ukrainian_tts/medium
However it is missing in the voices list in the addon configuration.
The only one which is available has a low quality.
Could you please add it? Thanks in advance.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Piper

### What is the version of the add-on?

0.1.3 

### Steps to reproduce the issue

1. Go to Piper addon config
2. Click Configuration
3. Verify that "uk_UK-ukrainian_tts-medium" is missing in voices options
...

## System Information

version | core-2023.7.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.34
arch | x86_64
timezone | Europe/Kiev
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4996
Installed Version | 1.32.1
Stage | running
Available Repositories | 1271
Downloaded Repositories | 31

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.3
-- | --
update_channel | stable
supervisor_version | supervisor-2023.07.1
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 30.8 GB
disk_used | 16.8 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | ESPHome (2023.6.4), Home Assistant Google Drive Backup (0.111.1), Studio Code Server (5.8.1), MariaDB (2.6.1), Mosquitto broker (6.2.1), Node-RED (14.3.0), Samba Backup (5.2.0), Samba share (10.0.2), Zigbee2MQTT (1.32.0-2), Piper (0.1.3)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 15
views | 28
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | June 30, 2023 at 9:21 AM
-- | --
current_recorder_run | July 5, 2023 at 11:39 PM
estimated_db_size | 852.36 MiB
database_engine | mysql
database_version | 10.6.12

</details>

**Comment by tomaszpieczykolan** [comment]
Is there a way to provide a custom voice to the add-on? I can't find it. It would be helpful if we could provide a local URL to the voice file. Then all voices would be supported.
