### ISSUE TITLE
nginx_proxy: Host header causes problems with ESPHome addon

### ISSUE THREAD

**Issue by mancontr** [home-assistant/addons#3132]
### Describe the issue you are experiencing

As discussed [here](https://community.home-assistant.io/t/esphome-web-ui-black-screen-for-validate-install-and-log/337578/16), when using the NGINX SSL Proxy addon together with the ESPHome addon, the websocket requests fail with this error:
```Cross origin websockets not allowed```

The reason is that the Origin and Host field differ, because the former includes the port, but the latter doesn't.

The fix would be very simple: on the default config, replace $host with $http_host, so it includes the port, on the `proxy_set_header Host` [rule](https://github.com/home-assistant/addons/blob/master/nginx_proxy/rootfs/etc/nginx.conf#L63C13-L63C34).

I tried this fix and worked correctly for me, and didn't seem to break any of my other addons, but further testing would be nice.

I can send a PR if this fix looks reasonable.

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### Which add-on are you reporting an issue with?

NGINX Home Assistant SSL proxy

### What is the version of the add-on?

3.5.0

### Steps to reproduce the issue

1. Configure the NGINX and ESPHome addons
2. Access the ESPHome page through ingress, and use the "validate" button
3. The screen stays black, and an error is reported in the supervisor logs

## System Information

version | core-2023.7.1
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 5.10.0-22-amd64
arch | x86_64
timezone | Europe/Madrid
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.32.1
Stage | running
Available Repositories | 1272
Downloaded Repositories | 6

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 11 (bullseye)
-- | --
update_channel | stable
supervisor_version | supervisor-2023.07.1
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 217.6 GB
disk_used | 16.2 GB
healthy | true
supported | true
supervisor_api | ok
version_api | ok
installed_addons | Advanced SSH & Web Terminal (15.0.3), Home Assistant Google Drive Backup (0.111.1), Let's Encrypt (4.12.9), Mosquitto broker (6.2.1), NGINX Home Assistant SSL proxy (3.5.0), NanoNVR (1.2.1), Network UPS Tools (0.12.0), Samba share (10.0.2), Zigbee2MQTT (1.32.1-1), Omada Controller Beta (5.9.2), Studio Code Server (5.8.1), AdGuard Home (4.8.11), ESPHome (2023.6.5)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 5
views | 8
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 9 de julio de 2023, 22:05
-- | --
current_recorder_run | 10 de julio de 2023, 00:05
estimated_db_size | 192.32 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Anything in the Supervisor logs that might be useful for us?

```txt
23-07-13 09:40:53 ERROR (MainThread) [supervisor.api.ingress] Ingress error: 403, message='Invalid response status', url=URL('http://172.30.32.1:63409/validate')
```

**Comment by mancontr** [comment]
The problem is still happening, and a fix is already known - just one line.
Any chance someone can take a look at this?

**Comment by vdemidov** [comment]
The problem is still happening

**Comment by mancontr** [comment]
I just checked and this still happens. This has been stalling for half a year, affecting multiple addons and with a simple, single-line fix already proposed. Is there anything I can do to get it through?

**Comment by mancontr** [comment]
Just checked again, and the issue keeps happening...

**Comment by agners** [comment]
I can confirm this fixes logs when connecting through the NGINX Proxy add-on with a non-default port. :tada: 

Thanks!
