### ISSUE TITLE
Lets Encript

### ISSUE THREAD

**Issue by Martynhsmith** [home-assistant/addons#3137]
### Describe the issue you are experiencing

No matter what I seem to do the lets encrypt addon always uses port 80
![letsencript](https://github.com/home-assistant/addons/assets/11158209/2cab7357-d049-4faf-985b-11f97966a600)

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Almond

### What is the version of the add-on?

4.12.9

### Steps to reproduce the issue

1. Try to change the port to eg 88 - see attachment
2.
3.
...

## System Information

version | core-2023.7.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.34
arch | x86_64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.32.1
Stage | running
Available Repositories | 1273
Downloaded Repositories | 11

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | November 16, 2023 at 12:00 AM
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | false
remote_server | eu-central-1-6.ui.nabu.casa
certificate_status | ready
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.3
-- | --
update_channel | stable
supervisor_version | supervisor-2023.07.1
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 30.8 GB
disk_used | 16.3 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.7.1), Samba share (10.0.2), Home Assistant Google Drive Backup (0.111.1), Studio Code Server (5.8.1), Mosquitto broker (6.2.1), Node-RED (14.3.0), Duck DNS (1.15.0), File editor (5.6.0), TasmoBackup (1.04.26), InfluxDB (4.7.0), Grafana (9.0.2), Zigbee2MQTT (1.32.1-1), MariaDB (2.6.1), RPC Shutdown (2.4), WireGuard (0.8.1), TasmoAdmin (0.24.4), Let's Encrypt (4.12.9)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 5
views | 14
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | July 7, 2023 at 6:23 AM
-- | --
current_recorder_run | July 15, 2023 at 3:08 PM
estimated_db_size | 512.84 MiB
database_engine | mysql
database_version | 10.6.12

</details>

### Anything in the Supervisor logs that might be useful for us?

```txt
I don't think so
```

### Anything in the add-on logs that might be useful for us?

```txt
nope
```

### Additional information

I might be doing something wrong but I can't see it

**Comment by djm228** [comment]
The greyed out "80/tcp" is just a reminder of the default port number. Your add-on is currently using port 88.
