### ISSUE TITLE
Whisper "medium" model not available anymore

### ISSUE THREAD

**Issue by taha-yassine** [home-assistant/addons#3141]
### Describe the issue you are experiencing

The "medium" model of whisper was removed from the available downloadable models according to https://github.com/rhasspy/rhasspy3/issues/16#issuecomment-1565678185, but is still mentionned in the documentation of the add-on.
A solution could be either to remove "medium" as an option, or to allow the user to provide his own model ("medium" or any custom model).

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Whisper

### What is the version of the add-on?

0.2.1

### Steps to reproduce the issue

1. Install the add-on
2. Choose "medium" as the model
3. Start the add-on

### System Health information

Not relevant

### Additional information

To be honest, I didn't test this directly on HA as I'm hosting Whisper on a separate more powerful machine, but I'm using the same docker image so the issue should be the same.
```[tasklist]
### Tasks
```

**Comment by Diondk** [comment]
I can confirm this is also not available on HA OS when installing Whisper, i was also looking on using the medium model.

**Comment by NeleB54Gold** [comment]
I've installed Whisper and Piper on a HA external docker, but whisper cannot startup if I want the medium option, I've tried tiny-int8, tiny and medium-int8 that actually works, but I cannot get the most accurate.
