### ISSUE TITLE
Piper tts cutting scentences

### ISSUE THREAD

**Issue by SiboutVanLoo** [home-assistant/addons#3145]
### Describe the issue you are experiencing

The end part is cut-off to soon. "time to go to bed." becomes "Time to g-" (in dutch :-) ). Playing the mp3 itself shows the same.
Triggering a command generates the same behaviour.
TTS: Piper (Voice nl-rdh-x-low)
Media players: MASS generated (Chromecast google home speakers, stereo pair and single ones.)
HW: RPi4 + SSD.
Tried:
Rebooting speakers, clearing ram by shutting down other addons, manually triggering, clearing playlists, pre-turn-on service call to wake speaker, inter-delaying commands, ...

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Piper

### What is the version of the add-on?

0.1.3

### Steps to reproduce the issue

1. Automation to send voice command
2. MASS media player - chromecast (Google home speaker - mini speaker - stereo pair.)
3.
...

## System Information

version | core-2023.7.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | Europe/Brussels
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.32.1
Stage | running
Available Repositories | 1278
Downloaded Repositories | 66
HACS Data | ok

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 18

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 24 oktober 2023 om 02:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | eu-central-1-5.ui.nabu.casa
certificate_status | ready
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.3
-- | --
update_channel | stable
supervisor_version | supervisor-2023.07.1
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 219.4 GB
disk_used | 50.7 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.6.0), Samba share (10.0.2), ESPHome (2023.7.0), Matter Server (4.8.3), Music Assistant BETA (2.0.0b59), Whisper (0.2.1), Piper (0.1.3), TasmoAdmin (0.25.0), Grocy (0.19.1), Studio Code Server (5.9.0), Node-RED (14.4.1), Advanced SSH & Web Terminal (15.0.5)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 49
views | 16
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 17 juli 2023 om 20:17
-- | --
current_recorder_run | 21 juli 2023 om 23:20
estimated_db_size | 691.91 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Anything in the add-on logs that might be useful for us?

```txt
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service piper: starting
s6-rc: info: service piper successfully started
s6-rc: info: service discovery: starting
WARNING:wyoming_piper.download:Voice hashes do not match
WARNING:wyoming_piper.download:Expected: {'nl-rdh-x-low.onnx': '7d60d0de9ad9ec11a1d293665743afda', 'nl-rdh-x-low.onnx.json': '189e6fd4e40bf8322800f50a743b4778'}
WARNING:wyoming_piper.download:Got: {'nl-rdh-x-low.onnx': '', 'nl-rdh-x-low.onnx.json': ''}
INFO:__main__:Downloading nl-rdh-x-low to /data
INFO:__main__:Ready
[11:08:41] INFO: Successfully send discovery information to Home Assistant.
s6-rc: info: service discovery successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
```

**Comment by SiboutVanLoo** [comment]
Well, it's still doing it. Any suggestions ?

**Comment by rojoricardo** [comment]
> Well, it's still doing it. Any suggestions ?

did you ever solved this?

**Comment by SiboutVanLoo** [comment]
Not completely, adding a delay helpen, but long scentences still cut off.
Splitring thema is a workaround, but it doesnt sound natural at all...

Op wo 8 nov 2023 20:12 schreef rojoricardo ***@***.***>:
