### ISSUE TITLE
DuckDNS addon does not actually work with URL options

### ISSUE THREAD

**Issue by ast0815** [home-assistant/addons#3146]
### Describe the issue you are experiencing

I want to use an URL to determine my IPv6 address, since duckdns cannot determine that itself. Unfortunately that does not seem to work.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Duck DNS

### What is the version of the add-on?

1.15.0

### Steps to reproduce the issue

1. Setup Duck DNS and add-on
2. Check it works with updating the IPv4 address when providing no values for "IPv4" and "IPv6" config options
3. Set "IPv6" option to `https://api6.ipify.org/`
4. It no longer updates any IP, and instead just restarts the add-on over and over again (see logs below)

## System Information

version | core-2023.7.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4999
Installed Version | 1.32.1
Stage | running
Available Repositories | 1273
Downloaded Repositories | 5

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 12 August 2023 at 02:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | false
remote_server | eu-central-1-4.ui.nabu.casa
certificate_status | ready
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.3
-- | --
update_channel | stable
supervisor_version | supervisor-2023.07.1
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 117.3 GB
disk_used | 25.2 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.7.1), Duck DNS (1.15.0), NGINX Home Assistant SSL proxy (3.5.0), AppDaemon (0.13.3), VLC (0.2.0), File editor (5.6.0), JupyterLab (0.11.1), SQLite Web (3.9.0), Nextcloud Backup (0.17.7), Bluetti to MQTT (1.4.1), ESPHome (2023.7.0), Mosquitto broker (6.2.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 4
views | 11
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 21 October 2022 at 16:29
-- | --
current_recorder_run | 22 July 2023 at 18:06
estimated_db_size | 14134.25 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Anything in the add-on logs that might be useful for us?

```txt
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
# INFO: Using main config file /data/workdir/config
+ Account already registered!
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by oguzhanogreden** [comment]
I experienced something similar using v1.15.0 of the Duck DNS add-on.

With only IPv6 option set, I got the same log output as above.

With only IPv4 configuration set, it works as expected.

With neither set, it works as expected.
