### ISSUE TITLE
File editor: resizing browser reloads file

### ISSUE THREAD

**Issue by ReenigneArcher** [home-assistant/addons#3147]
### Describe the issue you are experiencing

Resizing the browser (snapping it to a corner/edge/etc), causes the loaded file to be reloaded... thus losing any unsaved changes.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

File editor

### What is the version of the add-on?

5.6.0

### Steps to reproduce the issue

1. Open file
2. Make changes
3. Resize/snap browser to edge of screen

## System Information

version | core-2023.7.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.34
arch | x86_64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4895
Installed Version | 1.32.1
Stage | running
Available Repositories | 1261
Downloaded Repositories | 12

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.3
-- | --
update_channel | stable
supervisor_version | supervisor-2023.07.1
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 30.8 GB
disk_used | 13.9 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Samba share (10.0.2), Duck DNS (1.15.0), File editor (5.6.0), phpMyAdmin (0.8.7), MariaDB (2.6.1), Nginx Proxy Manager (0.12.3), Check Home Assistant configuration (3.11.0), ADB - Android Debug Bridge (0.8.0), AdGuard Home (4.8.12), Network UPS Tools (0.12.0), motionEye (0.19.1), AppDaemon (0.13.3), Z-Wave JS (0.1.84), Advanced SSH & Web Terminal (15.0.5)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 11
views | 23
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | July 17, 2023 at 8:48 PM
-- | --
current_recorder_run | July 24, 2023 at 2:08 PM
estimated_db_size | 190.50 MiB
database_engine | mysql
database_version | 10.6.12

</details>

**Comment by ReenigneArcher** [comment]
bump

**Comment by ReenigneArcher** [comment]
Working now 🤷‍♂️

**Comment by 0anton** [comment]
Editor discards not saved edits, when browser window is resized. Lost my work because of that. Shall be re-opened?

**Comment by ReenigneArcher** [comment]
Yes, it looks to still be an issue... but does now require going to/from a very narrow browser window, instead of just any resize.

**Comment by ReenigneArcher** [comment]
bump

**Comment by 0anton** [comment]
It's still relevant.
