### ISSUE TITLE
LQI problem with Z2M and Multipan

### ISSUE THREAD

**Issue by Drealine** [home-assistant/addons#3158]
### Describe the issue you are experiencing

Hi
Using Multipan Protocol and Z2M, LQI show max 255. Seems to be not implemented in the add-on.

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### Which add-on are you reporting an issue with?

Silicon Labs Multiprotocol

### What is the version of the add-on?

2.3.0

### Steps to reproduce the issue

Nothing, just the LQI showing max value 255.

### System Health information

NA

**Comment by Drealine** [comment]
Additionnal info. In network scan of Z2M, routes LQI are ok.

**Comment by MattWestb** [comment]
I never have any problems with LQI in ZHA and all devices is reporting it OK as the last seen for all online devices.
![Screenshot 2023-08-01 223538](https://github.com/home-assistant/addons/assets/49618193/613b063d-e43d-4306-9d3f-6eb98067b8b7)
If more Z2M user is having that problem i think its better posting it in https://github.com/Koenkk/zigbee-herdsman/issues/319 so @kirovilya can taking on look on it.

**Comment by Drealine** [comment]
> I never have any problems with LQI in ZHA and all devices is reporting it OK as the last seen for all online devices.
> ![Screenshot 2023-08-01 223538](https://github.com/home-assistant/addons/assets/49618193/613b063d-e43d-4306-9d3f-6eb98067b8b7)
> If more Z2M user is having that problem i think its better posting it in https://github.com/Koenkk/zigbee-herdsman/issues/319 so @kirovilya can taking on look on it.

With Standalone ZigBee fw of sonoff. LQI is ok.

**Comment by Drealine** [comment]
> > I never have any problems with LQI in ZHA and all devices is reporting it OK as the last seen for all online devices.
> > ![Screenshot 2023-08-01 223538](https://github.com/home-assistant/addons/assets/49618193/613b063d-e43d-4306-9d3f-6eb98067b8b7)
> > If more Z2M user is having that problem i think its better posting it in https://github.com/Koenkk/zigbee-herdsman/issues/319 so @kirovilya can taking on look on it.
> 
> With Standalone ZigBee fw of sonoff. LQI is ok.

So what do you think about this problem ?
Z2m bug or addon ?

**Comment by MattWestb** [comment]
If you is having good router near you can getting 255 but if have little distance and RF around it shall being lower for most device but EZSP is having one very good radio retriever.
Post one issue in the Z2M thread then **kirovilya** can taking on look on it then hi have also running  the addon for testing and is knowing how its coded in Z2M.

**Comment by Drealine** [comment]
Ok @MattWestb , thank you :) Yes, but devices at 10 meters show the same LQI ^^

**Comment by Drealine** [comment]
https://github.com/Koenkk/zigbee-herdsman/issues/738

**Comment by darkxst** [comment]
> I never have any problems with LQI in ZHA

Is that with RCP multipan firmware?

**Comment by Drealine** [comment]
> Is that with RCP multipan firmware?

Yes

**Comment by darkxst** [comment]
I have seen this behaviour under ZHA, with ZBDongle-E Multipan and also heard second hand report of it happening with Skyconnect. End-devices that are connect directly to coordinator falsely report 255 LQI, devices connected via a router report the correct LQI.

**Comment by MattWestb** [comment]
That can being the reason i have not seen it then i have blocking the coordinator having end device as direct children then its only making problem then restating the addon and they must rejoining the network every time.

The interesting is if getting the same LQI from the network map for end devices that is having the coordinator as its parent then its using one other method for getting the LQI (its pulled from all routers in the network and not from the message sent from the device).
