### ISSUE TITLE
Mosquito 2.0.15 has a regression bug

### ISSUE THREAD

**Issue by garethhowell** [home-assistant/addons#3164]
### Describe the issue you are experiencing

I have unreliable bridges. Sometimes they connect, but not always. And if they fail for any reason, they don't always reconnect.
This has been reported in the main mosquito issues list: [https://github.com/eclipse/mosquitto/issues/2795](https://github.com/eclipse/mosquitto/issues/2795) and appears to have been created by a regression bug: [https://github.com/eclipse/mosquitto/issues/2634](https://github.com/eclipse/mosquitto/issues/2634).

How do we downgrade the addon to use 2.0.14 as others seem to have done.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Mosquitto broker

### What is the version of the add-on?

6.2.1

### Steps to reproduce the issue

1. Nothing to do other upgrade to the latest version of the addon
2.
3.
...

## System Information

version | core-2023.7.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | Etc/GMT
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.32.1
Stage | running
Available Repositories | 1266
Downloaded Repositories | 18

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.4
-- | --
update_channel | stable
supervisor_version | supervisor-2023.07.1
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 116.7 GB
disk_used | 14.4 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.2.1), MariaDB (2.6.1), InfluxDB (4.7.0), Node-RED (14.4.3), Studio Code Server (5.10.0), ESPHome (2023.7.1), Home Assistant Google Drive Backup (0.111.1), Glances (0.19.2), Advanced SSH & Web Terminal (15.0.6), Network UPS Tools (0.12.0), ArgonOne Active Cooling (29c), RPC Shutdown (2.4), HassOS I2C Configurator (0.13a), Grafana (9.0.3), MQTT IO (0.2.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 12
views | 4
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 27 July 2023 at 15:27
-- | --
current_recorder_run | 3 August 2023 at 14:04
estimated_db_size | 152.33 MiB
database_engine | mysql
database_version | 10.6.12

</details>

**Comment by darkxst** [comment]
> How do we downgrade the addon to use 2.0.14 as others seem to have done.

The only way to downgrade addons is to restore the backup of the addon that was taken before you installed the current version.

**Comment by CJOWood** [comment]
Looks like this got fixed in https://github.com/eclipse/mosquitto/commit/6d240a9d183413fca7d2a4f42eae803ba84af97c
