### ISSUE TITLE
Couldn't set EzspConfigId.CONFIG_PACKET_BUFFER_COUNT=255 configuration value: EzspStatus.ERROR_INVALID_ID

### ISSUE THREAD

**Issue by tggman** [home-assistant/addons#3166]
### Describe the issue you are experiencing

Started getting this error in the logs right after updating to v2.3.1

```
Logger: bellows.ezsp.protocol
Source: components/zha/core/gateway.py:205
First occurred: 7:50:22 AM (1 occurrences)
Last logged: 7:50:22 AM

Couldn't set EzspConfigId.CONFIG_PACKET_BUFFER_COUNT=255 configuration value: EzspStatus.ERROR_INVALID_ID
```

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Silicon Labs Multiprotocol

### What is the version of the add-on?

2.3.1

### Steps to reproduce the issue

Error shows up in logs whenever Home Assistant is restarted

## System Information

version | core-2023.8.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.39
arch | aarch64
timezone | America/Chicago
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4987
Installed Version | 1.32.1
Stage | running
Available Repositories | 1275
Downloaded Repositories | 1

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 14

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | August 12, 2023 at 7:00 PM
relayer_connected | true
relayer_region | us-east-1
remote_enabled | false
remote_connected | false
alexa_enabled | true
google_enabled | true
remote_server | us-east-1-0.ui.nabu.casa
certificate_status | ready
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.4
-- | --
update_channel | stable
supervisor_version | supervisor-2023.07.1
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 113.9 GB
disk_used | 8.8 GB
healthy | true
supported | true
board | odroid-n2
supervisor_api | ok
version_api | ok
installed_addons | Samba share (10.0.2), Terminal & SSH (9.7.1), Let's Encrypt (4.12.9), Duck DNS (1.15.0), Z-Wave JS (0.1.85), Silicon Labs Multiprotocol (2.3.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 0
views | 17
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | July 31, 2023 at 2:31 PM
-- | --
current_recorder_run | August 5, 2023 at 7:49 AM
estimated_db_size | 577.55 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Anything in the Supervisor logs that might be useful for us?

```txt
23-08-05 06:45:59 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on core_silabs_multiprotocol
23-08-05 06:45:59 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon core_silabs_multiprotocol
23-08-05 06:45:59 INFO (MainThread) [supervisor.backups.manager] Creating partial backup with slug 76f9da73 completed
23-08-05 06:45:59 INFO (SyncWorker_3) [supervisor.docker.addon] Updating image homeassistant/aarch64-addon-silabs-multiprotocol:2.3.0 to homeassistant/aarch64-addon-silabs-multiprotocol:2.3.1
23-08-05 06:45:59 INFO (SyncWorker_3) [supervisor.docker.interface] Downloading docker image homeassistant/aarch64-addon-silabs-multiprotocol with tag 2.3.1.
23-08-05 06:46:21 INFO (SyncWorker_3) [supervisor.docker.interface] Stopping addon_core_silabs_multiprotocol application
23-08-05 06:46:26 INFO (SyncWorker_3) [supervisor.docker.interface] Cleaning addon_core_silabs_multiprotocol application
23-08-05 06:46:26 INFO (MainThread) [supervisor.addons] Add-on 'core_silabs_multiprotocol' successfully updated
23-08-05 06:46:26 INFO (SyncWorker_6) [supervisor.docker.interface] Cleanup images: ['homeassistant/aarch64-addon-silabs-multiprotocol:2.3.0']
23-08-05 06:46:28 INFO (SyncWorker_3) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-silabs-multiprotocol with version 2.3.1
23-08-05 06:46:55 INFO (MainThread) [supervisor.api.middleware.security] /network/info access from core_silabs_multiprotocol
```

**Comment by agners** [comment]
As discussed in https://github.com/zigpy/zigpy/discussions/894#discussioncomment-6569904 this is a change in the Gecko SDK v4.3.1.0:

> // The NCP no longer supports configuration of packet buffer count at runtime
> // using this parameter. Packet buffers must be configured using the
> // EMBER_PACKET_BUFFER_COUNT macro when building the NCP project.

https://github.com/SiliconLabs/gecko_sdk/blob/v4.3.1/protocol/zigbee/app/util/ezsp/ezsp-enum.h#L17-L19

The Silicon Labs Multiprotocol uses 255 as the number of buffers, which will automatically assign the maximum number. Since this is a changed behavior for Gecko SDK, we can't fix this on the add-on side.

I think this needs to be addressed in ZHA. I've opened a new issue on the Core side: https://github.com/home-assistant/core/issues/97967.

**Comment by tggman** [comment]
Thanks!
