### ISSUE TITLE
Add aarch64 to Home assistant addon : Google assistant SDK

### ISSUE THREAD

**Issue by nyok92** [home-assistant/addons#3172]
### Describe the issue you are experiencing

In Build.yaml, please add build from :
aarch64: ghcr.io/home-assistant/aarch64-base-debian:buster

https://github.com/home-assistant/addons/blob/master/google_assistant/build.yaml

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Debian

### Which add-on are you reporting an issue with?

Google Assistant SDK

### What is the version of the add-on?

2.5.0

### Steps to reproduce the issue

try to install the addon for aarch64 based system.

## System Information

version | core-2023.8.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.39
arch | aarch64
timezone | Europe/Paris
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.32.1
Stage | running
Available Repositories | 1270
Downloaded Repositories | 23

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.4
-- | --
update_channel | stable
supervisor_version | supervisor-2023.08.1
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 48.5 GB
disk_used | 25.8 GB
healthy | true
supported | true
board | generic-aarch64
supervisor_api | ok
version_api | ok
installed_addons | Home Assistant Google Drive Backup (0.111.1), File editor (5.6.0), Mosquitto broker (6.2.1), Frigate (Full Access) (0.12.1), Matter Server (4.9.0), Terminal & SSH (9.7.1), Spotify Connect (0.12.4), Piper (1.2.0), Whisper (1.0.0), Glances (0.19.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 10
views | 8
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 3 août 2023 à 16:11
-- | --
current_recorder_run | 4 août 2023 à 22:41
estimated_db_size | 299.83 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
