### ISSUE TITLE
Matter add-on Timeout error

### ISSUE THREAD

**Issue by nvenk** [home-assistant/addons#3173]
### Describe the issue you are experiencing

I'm running HA on an ODroid N2+ 64gb, with the Skyconnect dongle. Skyconnect is set up in Multiprotocol firmware, but the problem persists with the Zigbee firmware as well.

I tried installing the matter add-on & integration, and installation works fine without any errors. However, The integration is stuck at "failed, will retry".

Matter Add-on logs show the following: 
```
2023-08-09 17:45:32 core-matter-server matter_server.server.helpers.paa_certificates[126] INFO Fetching the latest PAA root certificates from DCL.
/usr/local/lib/python3.11/site-packages/matter_server/server/helpers/paa_certificates.py:46: CryptographyDeprecationWarning: The parsed certificate contains a NULL parameter value in its signature algorithm parameters. This is invalid and will be rejected in a future version of cryptography. If this certificate was created via Java, please upgrade to JDK16+ or the latest JDK11 once a fix is issued. If this certificate was created in some other fashion please report the issue to the cryptography issue tracker. See https://github.com/pyca/cryptography/issues/8996 for more details.
  pem_certificate = x509.load_pem_x509_certificate(certificate.encode())
2023-08-09 17:45:37 core-matter-server matter_server.server.helpers.paa_certificates[126] INFO Fetched 103 PAA root certificates from DCL.
2023-08-09 17:45:37 core-matter-server matter_server.server.helpers.paa_certificates[126] INFO Fetching the latest PAA root certificates from Git.
2023-08-09 17:50:38 core-matter-server asyncio[126] ERROR Task exception was never retrieved
future: <Task finished name='Task-1' coro=<run.<locals>.new_coro() done, defined at /usr/local/lib/python3.11/site-packages/aiorun.py:209> exception=TimeoutError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiorun.py", line 219, in new_coro
    await coro
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/server.py", line 94, in start
    await self.device_controller.initialize()
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 92, in initialize
    await fetch_certificates()
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/helpers/paa_certificates.py", line 153, in fetch_certificates
    fetch_count += await fetch_git_certificates()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/matter_server/server/helpers/paa_certificates.py", line 126, in fetch_git_certificates
    async with http_session.get(f"{GIT_URL}/{cert}.pem") as response:
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 467, in _request
    with timer:
  File "/usr/local/lib/python3.11/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
TimeoutError
```

and the SiliconLabs Multiprotocol add-on logs show this line over and over:
```
otbr-agent[299]: 20:24:39.561 [W] Platform------: [netif] Failed to transmit, error:Parse
```

I'd really appreciate some help in trying to get Matter running.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Matter Server

### What is the version of the add-on?

4.9.0

### Steps to reproduce the issue

1. Connect the Skyconnect dongle 
2. Install ZHA add-on
3. Update skyconnect firmware to multi-protocol
4. Install Matter integration. This triggers add-on installation.
5. Matter integration status defaults to "failed, will retry".

## System Information

version | core-2023.8.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.39
arch | aarch64
timezone | America/Los_Angeles
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | failed to load: timeout
can_reach_cloud_auth | failed to load: timeout
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.4
-- | --
update_channel | stable
supervisor_version | supervisor-2023.08.1
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 56.6 GB
disk_used | 4.5 GB
healthy | true
supported | true
board | odroid-n2
supervisor_api | ok
version_api | failed to load: timeout
installed_addons | Matter Server (4.9.0), Silicon Labs Multiprotocol (2.3.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
mode | auto-gen

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | August 9, 2023 at 10:27 PM
-- | --
current_recorder_run | August 9, 2023 at 5:19 PM
estimated_db_size | 0.62 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Anything in the Supervisor logs that might be useful for us?

```txt
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/http.py:51
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 6:58:24 AM (1 occurrences)
Last logged: 6:58:24 AM

[281472982098752] from 192.168.4.152 (Home Assistant/2023.4 (io.robbie.HomeAssistant; build:2023.460; iOS 16.6.0)): Disconnected: Did not receive auth message within 10 seconds
_________
Logger: homeassistant.config_entries
Source: config_entries.py:1290
First occurred: August 9, 2023 at 5:44:42 PM (1 occurrences)
Last logged: August 9, 2023 at 5:44:42 PM

Config entry 'Matter' for matter integration not ready yet: Failed to connect to matter server; Retrying in background
_________
Logger: bellows.ezsp.protocol
Source: components/zha/core/gateway.py:205
First occurred: August 9, 2023 at 5:19:42 PM (1 occurrences)
Last logged: August 9, 2023 at 5:19:42 PM

Couldn't set EzspConfigId.CONFIG_PACKET_BUFFER_COUNT=255 configuration value: EzspStatus.ERROR_INVALID_ID
_________
Logger: homeassistant.config_entries
Source: config_entries.py:430
First occurred: August 9, 2023 at 5:19:38 PM (1 occurrences)
Last logged: August 9, 2023 at 5:19:38 PM

Config entry 'Matter' for matter integration not ready yet: Failed to connect to matter server; Retrying in background
```

### Additional information

I've tried re-flashing HAOS and the Skyconnect firmware multiple times over the past few days and tried with single and multiprotocol firmwares.

Also maybe something of interest – Matter worked fine the first day I installed it. I was able to add my devices. We had a power cut a few days after first install, and since power came back, it hasn't been working. (This was also around the time I switched Skyconnect from Zigbee to Multi-protocol for the first time, so not sure if that is related).

**Comment by darkxst** [comment]
> "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1141, in __aenter__ self._resp = await self._coro ^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 467, in _request with timer: File "/usr/local/lib/python3.11/site-packages/aiohttp/helpers.py", line 721, in __exit__ raise asyncio.TimeoutError from None TimeoutError

Matter server is failing to download certificates from github, you will need to ensure your HA Box has IPv6 internet connectivity. See this issue for more details:
https://github.com/home-assistant/operating-system/issues/2549

I not sure about the multiprotocol error, but its not related to the Matter server not starting.

**Comment by agners** [comment]
Thanks for the update. I'll close the issue then.
