### ISSUE TITLE
LetsEncrypt add-on not starting on boot despite option being selected

### ISSUE THREAD

**Issue by baylf2000** [home-assistant/addons#3174]
### Describe the issue you are experiencing

The Lets Encrypt add-on does not run at boot despite the "start on boot" despite option being selected.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Let's Encrypt

### What is the version of the add-on?

4.12.9

### Steps to reproduce the issue

1. Set the "Start On Boot" option to true in the add-on interface.
2. Reboot the server.
3. Check the add-on log files, confirming add-on has not run.

## System Information

version | core-2023.8.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.39
arch | x86_64
timezone | Australia/Brisbane
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.32.1
Stage | running
Available Repositories | 1266
Downloaded Repositories | 2

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | August 18, 2023 at 10:00 AM
relayer_connected | true
relayer_region | ap-southeast-1
remote_enabled | false
remote_connected | false
alexa_enabled | true
google_enabled | true
remote_server | ap-southeast-1-1.ui.nabu.casa
certificate_status | ready
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.4
-- | --
update_channel | stable
supervisor_version | supervisor-2023.08.1
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 468.7 GB
disk_used | 12.9 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.2.1), Zigbee2MQTT (1.32.2-1), Matter Server (4.9.0), TasmoAdmin (0.25.0), Let's Encrypt (4.12.9), File editor (5.6.0), ESPHome (2023.7.1), Home Assistant Google Drive Backup (0.111.1), Advanced SSH & Web Terminal (15.0.6), Samba share (10.0.2), Hello world (1.0.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
views | 2
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | August 3, 2023 at 12:57 AM
-- | --
current_recorder_run | August 13, 2023 at 4:03 AM
estimated_db_size | 159.54 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

**Comment by Tomschin** [comment]
Same issue. (Runing on a PI4)

There are two errors in my log section.

===============================================
Logger: aiohttp.server
Source: /usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py:403
First occurred: 07:47:55 (12 occurrences)
Last logged: 07:52:15

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 332, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 557, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Bad status line "Invalid method encountered:\n\n  b'\\x16\\x03\\x01\\x02'\n    ^"

==============================

Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:130
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 07:55:45 (1 occurrences)
Last logged: 07:55:45

Failed to to call /addons/core_letsencrypt/stats - Container addon_core_letsencrypt is not running

**Comment by Tomschin** [comment]
In the moment I use another tool, but I am still interested in a solution for that problem.
