### ISSUE TITLE
VLC add on needs config to expose/set password to work with vlc-telnet integration in case discovery doesn't work/happen

### ISSUE THREAD

**Issue by BobC76** [home-assistant/addons#3186]
### Describe the issue you are experiencing

The add on documentation says simply:

> How to use
> Start the add-on.
> Add the VLC Telnet integration to Home Assistant, see documentation: https://www.home-assistant.io/integrations/vlc_telnet

As noted in a comment below, this brief set of instructions assumes one can set up the integration via the discovery information that the add-on sends to Home Assistant Core. But this doesn't always happen, and you can't always just confirm the discovery under Devices & Services in the GUI Settings..

As the latest vlc_telnet expects a password, and there's no way to set it on the add on, if for some reason discovery doesn't happen, it can't work as described.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

VLC

### What is the version of the add-on?

0.2.0

### Steps to reproduce the issue

1. Follow the instructions at https://github.com/home-assistant/addons/blob/master/vlc/DOCS.md - they don't work because the vlc_telnet integration requires a password, and no-where does the vlc documentation state where that can be set/seen

## System Information

version | core-2023.8.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.39
arch | x86_64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.32.1
Stage | running
Available Repositories | 1272
Downloaded Repositories | 43

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.4
-- | --
update_channel | beta
supervisor_version | supervisor-2023.08.1
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 30.8 GB
disk_used | 8.3 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Samba share (10.0.2), Terminal & SSH (9.7.1), SQLite Web (3.9.2), Cloudflared (4.2.2), Studio Code Server (5.10.0), Mosquitto broker (6.2.1), Home Assistant Google Drive Backup (0.111.1), Node-RED (14.4.4), VLC (0.2.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 31
views | 14
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 19 August 2023 at 19:31
-- | --
current_recorder_run | 19 August 2023 at 20:31
estimated_db_size | 662.00 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

<details><summary>Solcast PV Forecast</summary>

can_reach_server | ok
-- | --
remaining_requests | 3
rooftop_site_count | 1
polling_hours | 6 -> 19 and once at midnight

</details>

### Anything in the Supervisor logs that might be useful for us?

```txt
Supervisor
No errors have been reported
```

### Anything in the add-on logs that might be useful for us?

```txt
VLC
No errors have been reported
```

**Comment by MartinHjelmare** [comment]
You're expected to set up the integration via the discovery information that the add-on sends to Home Assistant Core. You just need to confirm the discovery under Devices & Services in the GUI Settings..

**Comment by BobC76** [comment]
Hi thanks for replying, and I'm sorry I don't follow or quite understand what you are suggesting. I can't set a password for the vlc_telnet integration when there is no way of knowing what was set for the vlc add-on?

**Comment by BobC76** [comment]
Ok, having removed everything and installing the add-on then vlc-telnet one by one, I can see what you mean.  My problem was having installed them both previously and not got it working due to misconfiguring my audio output, the discovery didn't just happen after I corrected the audio/vlc add on side. So I couldn't then set up vlc-telnet without uninstalling and then re-installing.

**Comment by BobC76** [comment]
I've updated the title and description to better capture what I encountered. I'm not clear in what circumstances discovery can/should happen, but in my case it hadn't. I don't know if causing a restart would have triggered something I missed.

**Comment by agners** [comment]
@BobC76 not sure if it is a good idea to show the username/password and let the user handle the configuration... How about extending the documentation to mention that automatic discovery is expected when the add-on is being installed, and if that is not the case the user should make sure to remove the Telnet integration and reinstall the add-on?

**Comment by BobC76** [comment]
Hi, that would be an improvement agreed. I'm not sure I understand why its a problem exposing a password for this when lots of other integrations also require similar credential entry to work, but at least clearer there's a sequence in which it will work otherwise it won't would have saved me some time. I've borrowed your words for https://github.com/home-assistant/addons/pull/3200 :)

**Comment by NHodgesVFX** [comment]
I tried to add the VLC addon and ran into the same issue I do get a discovery for core-vlc but not vlc_telnet. Additionally, the core-vlc integration fails to connect. I don't believe I have any stale vlc_telnet integrations. After installing VLC and failing to connect with core-vlc I tried to setup the vlc_telnet integration but couldn't because I don't know / cant setup the password.

![image](https://github.com/home-assistant/addons/assets/11403345/46c74d6e-af68-4e00-bdb4-62f446f3e481)
![image](https://github.com/home-assistant/addons/assets/11403345/e3dc3650-51b8-45fe-b289-c14248a2d8f3)

**Comment by ejohb** [comment]
I have this same problem. Why can't I just set a password in the add-on?

**Comment by upsuper** [comment]
I had the same problem, but after restarting the VLC addon, it gets auto-discovered again, and this time it works.

I think there is probably a race condition between creating `/data/secret` and reading the secret (for discovery or for starting VLC).

**Comment by pablinho1023** [comment]
Happening to me but the automatic discovery never happens. If I search for the integration, it asks for a password. Is there any workaround?

**Comment by Axsgranted** [comment]
discovery not working for me either...
