### ISSUE TITLE
Silicon Labs Multiprotocol stops working and needs restart every few hours

### ISSUE THREAD

**Issue by demono10000** [home-assistant/addons#3193]
### Describe the issue you are experiencing

Every few hours my zigbee devices stop working and I have to restart Silicon Labs Multiprotocol addon to make my devices work again. When I check logs before restarting, I see that zigbee starts every few seconds. I am using skyconnect and it has been working fine for a few months, and now since about 2 weeks, it needs restart every few hours. After restarting the addon everything works fine for next few hours.
[core_silabs_multiprotocol_2023-08-26T17-16-48.488Z.log](https://github.com/home-assistant/addons/files/12446171/core_silabs_multiprotocol_2023-08-26T17-16-48.488Z.log)

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Silicon Labs Multiprotocol

### What is the version of the add-on?

2.3.2

### Steps to reproduce the issue

1. Start home assistant
2. Wait few hours
3. Zigbee stops working
4. Restart Silicon Labs Multiprotocol addon
5. Everything works again
6. Move to step 2.

## System Information

version | core-2023.8.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | Europe/Warsaw
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4994
Installed Version | 1.32.1
Stage | running
Available Repositories | 1269
Downloaded Repositories | 3

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 26 sierpnia 2023 02:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | eu-central-1-6.ui.nabu.casa
certificate_status | ready
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.08.1
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 109.3 GB
disk_used | 33.5 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.2.1), File editor (5.6.0), TasmoAdmin (0.25.0), Google Assistant SDK (2.5.0), Advanced SSH & Web Terminal (15.0.7), AppDaemon (0.13.4), Grafana (9.0.3), InfluxDB (4.7.0), Home Assistant Google Drive Backup (0.111.1), Studio Code Server (5.10.1), Matter Server (4.9.0), Silicon Labs Multiprotocol (2.3.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 0
views | 8
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 16 sierpnia 2023 19:37
-- | --
current_recorder_run | 26 sierpnia 2023 15:59
estimated_db_size | 1035.96 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

<details><summary>Sonoff</summary>

version | 3.5.2 (2ad1cd7)
-- | --
cloud_online | 0 / 4
local_online | 0 / 0

</details>

### Anything in the add-on logs that might be useful for us?

```txt
[19:29:54] INFO: Starting zigbeed...
[19:29:54:419405] WARNING : In function 'property_get_single_endpoint_state_and_reply_to_pending_open_callback' in file /usr/src/cpc-daemon/server_core/system_endpoint/system_callbacks.c at line #176 : Property-get::PROP_ENDPOINT_STATE aborted
[19:29:54:419494] WARNING : In function 'property_get_single_endpoint_state_and_reply_to_pending_open_callback' in file /usr/src/cpc-daemon/server_core/system_endpoint/system_callbacks.c at line #210 : Could not read endpoint state on the secondary
[19:29:54:419531] WARNING : In function 'system_send_open_endpoint_ack' in file /usr/src/cpc-daemon/server_core/system_endpoint/system_callbacks.c at line #122 : Failed to acknowledge the open request for endpoint #12. Bad file descriptor
[19:29:55:531034] Info : New client connection using library v4.3.1.0
[19:29:56] INFO: Setup OTBR firewall...
WARNING in function 'property_get_single_endpoint_state_and_reply_to_pending_open_callback' in file /usr/src/cpc-daemon/server_core/system_endpoint/system_callbacks.c at line #176 : Property-get::PROP_ENDPOINT_STATE aborted
WARNING in function 'property_get_single_endpoint_state_and_reply_to_pending_open_callback' in file /usr/src/cpc-daemon/server_core/system_endpoint/system_callbacks.c at line #210 : Could not read endpoint state on the secondary
close cpc endpoint: No such file or directory
By using this software, you are agreeing to the Silicon Labs MSLA found at https://www.silabs.com/about-us/legal/master-software-license-agreement.
[19:29:56] INFO: Starting otbr-agent...
[19:29:56] INFO: zigbeed ended with exit code 1 (signal 0)...
otbr-agent[38199]: [NOTE]-AGENT---: Running 0.3.0
otbr-agent[38199]: [NOTE]-AGENT---: Thread version: 1.3.0
otbr-agent[38199]: [NOTE]-AGENT---: Thread interface: wpan0
otbr-agent[38199]: [NOTE]-AGENT---: Radio URL: spinel+cpc://cpcd_0?iid=2&iid-list=0
otbr-agent[38199]: [NOTE]-ILS-----: Infra link selected: wlan0
[19:29:56:419389] WARNING : In function 'property_get_single_endpoint_state_and_reply_to_pending_open_callback' in file /usr/src/cpc-daemon/server_core/system_endpoint/system_callbacks.c at line #176 : Property-get::PROP_ENDPOINT_STATE aborted
[19:29:56:419477] WARNING : In function 'property_get_single_endpoint_state_and_reply_to_pending_open_callback' in file /usr/src/cpc-daemon/server_core/system_endpoint/system_callbacks.c at line #210 : Could not read endpoint state on the secondary
[19:29:56:423960] Info : Client disconnected
[19:29:56:644815] Info : New client connection using library v4.3.1.0
[19:29:57] INFO: Starting zigbeed...
WARNING in function 'property_get_single_endpoint_state_and_reply_to_pending_open_callback' in file /usr/src/cpc-daemon/server_core/system_endpoint/system_callbacks.c at line #176 : Property-get::PROP_ENDPOINT_STATE aborted
WARNING in function 'property_get_single_endpoint_state_and_reply_to_pending_open_callback' in file /usr/src/cpc-daemon/server_core/system_endpoint/system_callbacks.c at line #210 : Could not read endpoint state on the secondary
otbr-agent[38199]: 50d.16:38:19.653 [C] Platform------: CPC endpoint open failed
otbr-agent[38199]: 50d.16:38:19.654 [C] Platform------: mCpcBusSpeed = 115200
otbr-agent[38199]: 50d.16:38:19.654 [C] Platform------: Init() at radio.cpp:121: Failure
close cpc endpoint: Success
[19:29:58] INFO: otbr-agent ended with exit code 1 (signal 0)...
OTBR_FORWARD_INGRESS  all opt    in * out wpan0  ::/0  -> ::/0  
Chain OTBR_FORWARD_INGRESS (0 references)
target     prot opt source               destination         
DROP       all      anywhere             anywhere             PKTTYPE = unicast
DROP       all      anywhere             anywhere             match-set otbr-ingress-deny-src src
ACCEPT     all      anywhere             anywhere             match-set otbr-ingress-allow-dst dst
DROP       all      anywhere             anywhere             PKTTYPE = unicast
ACCEPT     all      anywhere             anywhere            
otbr-ingress-deny-src
[19:29:58:419394] WARNING : In function 'property_get_single_endpoint_state_and_reply_to_pending_open_callback' in file /usr/src/cpc-daemon/server_core/system_endpoint/system_callbacks.c at line #176 : Property-get::PROP_ENDPOINT_STATE aborted
[19:29:58:419483] WARNING : In function 'property_get_single_endpoint_state_and_reply_to_pending_open_callback' in file /usr/src/cpc-daemon/server_core/system_endpoint/system_callbacks.c at line #210 : Could not read endpoint state on the secondary
[19:29:58:423988] Info : Client disconnected
otbr-ingress-deny-src-swap
otbr-ingress-allow-dst
otbr-ingress-allow-dst-swap
OTBR_FORWARD_EGRESS  all opt    in wpan0 out *  ::/0  -> ::/0  
Chain OTBR_FORWARD_EGRESS (0 references)
target     prot opt source               destination         
ACCEPT     all      anywhere             anywhere            
[19:29:59] INFO: OTBR firewall teardown completed.
[19:29:58:914444] Info : New client connection using library v4.3.1.0
WARNING in function 'property_get_single_endpoint_state_and_reply_to_pending_open_callback' in file /usr/src/cpc-daemon/server_core/system_endpoint/system_callbacks.c at line #176 : Property-get::PROP_ENDPOINT_STATE aborted
WARNING in function 'property_get_single_endpoint_state_and_reply_to_pending_open_callback' in file /usr/src/cpc-daemon/server_core/system_endpoint/system_callbacks.c at line #210 : Could not read endpoint state on the secondary
close cpc endpoint: No such file or directory
By using this software, you are agreeing to the Silicon Labs MSLA found at https://www.silabs.com/about-us/legal/master-software-license-agreement.
[19:30:00] INFO: zigbeed ended with exit code 1 (signal 0)...
[19:30:00:419410] WARNING : In function 'property_get_single_endpoint_state_and_reply_to_pending_open_callback' in file /usr/src/cpc-daemon/server_core/system_endpoint/system_callbacks.c at line #176 : Property-get::PROP_ENDPOINT_STATE aborted
[19:30:00:419784] WARNING : In function 'property_get_single_endpoint_state_and_reply_to_pending_open_callback' in file /usr/src/cpc-daemon/server_core/system_endpoint/system_callbacks.c at line #210 : Could not read endpoint state on the secondary
[19:30:00:423323] Info : Client disconnected
[19:30:02] INFO: Starting zigbeed...
```

**Comment by agners** [comment]
Do you have to remove/replug the SkyConnect? Or is just the restart of the Multiprotocol add-on enough?

**Comment by demono10000** [comment]
Restart of the add-on is enough. I have thread enabled and 3 border routers (home nest 2, homepod mini, skyconnect) and 2 smart sockets connected to them.

**Comment by agners** [comment]
@demono10000 can you maybe disable the Thread part for a while and see if that changes things?

Unfortunately, there is not much we can do about this directly, as this is all code from Silicon Labs.

**Comment by demono10000** [comment]
> @demono10000 can you maybe disable the Thread part for a while and see if that changes things?
> 
> Unfortunately, there is not much we can do about this directly, as this is all code from Silicon Labs.

Should I follow this guide or is there simpler way to disable it? https://skyconnect.home-assistant.io/procedures/disable-multiprotocol/

**Comment by agners** [comment]
> Should I follow this guide or is there simpler way to disable it? https://skyconnect.home-assistant.io/procedures/disable-multiprotocol/

You can disable just the OpenThread Border Router part in the Siliconlabs Multiprotocol add-on configuration.

![image](https://github.com/home-assistant/addons/assets/34061/f229f379-3784-4405-92df-ca960317ccbe)

You'll have to restart the add-on after that.

**Comment by demono10000** [comment]
> > Should I follow this guide or is there simpler way to disable it? https://skyconnect.home-assistant.io/procedures/disable-multiprotocol/
> 
> You can disable just the OpenThread Border Router part in the Siliconlabs Multiprotocol add-on configuration.
> 
> ![image](https://user-images.githubusercontent.com/34061/264983907-f229f379-3784-4405-92df-ca960317ccbe.png)
> 
> You'll have to restart the add-on after that.

Thanks, I will check if it helps.

**Comment by demono10000** [comment]
> > Should I follow this guide or is there simpler way to disable it? https://skyconnect.home-assistant.io/procedures/disable-multiprotocol/
> 
> You can disable just the OpenThread Border Router part in the Siliconlabs Multiprotocol add-on configuration.
> 
> ![image](https://user-images.githubusercontent.com/34061/264983907-f229f379-3784-4405-92df-ca960317ccbe.png)
> 
> You'll have to restart the add-on after that.

It didn't help. I had to restart the add-on four times since disabling Thread.

**Comment by agners** [comment]
Hm, I guess it is some lower level issue, e.g. your USB bus hangs or maybe a power supply issue. Do you see something in the Host logs?

What hardware are you using? Can you try changing things around USB, to see if that helps (replace USB hub if used, use a different USB plug)?

**Comment by demono10000** [comment]
> Hm, I guess it is some lower level issue, e.g. your USB bus hangs or maybe a power supply issue. Do you see something in the Host logs?
> 
> What hardware are you using? Can you try changing things around USB, to see if that helps (replace USB hub if used, use a different USB plug)?

I use Raspberry Pi 4 and I tried switching between USB 2 and USB 3 ports and it didn't help. I will try to replace the USB extension cable.

**Comment by demono10000** [comment]
> > Hm, I guess it is some lower level issue, e.g. your USB bus hangs or maybe a power supply issue. Do you see something in the Host logs?
> > What hardware are you using? Can you try changing things around USB, to see if that helps (replace USB hub if used, use a different USB plug)?
> 
> I use Raspberry Pi 4 and I tried switching between USB 2 and USB 3 ports and it didn't help. I will try to replace the USB extension cable.

Switching the USB extension cable didn't help. I may later try to switch the power supply.

**Comment by kylev** [comment]
I'm running roughly the same hardware (RP4, SkyConnect, 3.5A PS). It looks like the crash-loop goes in a couple of phases, with 10 minutes of internal `Property-get::PROP_ENDPOINT_STATE` attempts failing before fully crashing. Then something is internally restarting zigbeed and spamming the logs instead of letting the outer container crash.

Would it be possible to change s6 stuff to crash harder as mitigation? Restarting just `zigbeed` automatically is fast, but letting the failure bubble up would restart the container.

[skycon-loop.log](https://github.com/home-assistant/addons/files/12528342/skycon-loop.log)

**Comment by kylev** [comment]
Note: unlike @demono10000, I sometimes find that service restart isn't enough. During start-up, the SiLabs flasher fails to auto-negotiate with the SkyConnect, falls back to probing by baudrate, and exits.

I agree with @agners that this is likely because of buggy vendor'ed code from SiliconLabs via (their @aautotte bot?) or firmware. Can we get an "upstream" label and keep this bug open? It would help to maintain a Google result for other sufferers to monitor. Looks like there are already other duplicates...

Plus the community [share it to Silicon Labs](https://twitter.com/siliconlabs).

```logs
s6-rc: info: service banner successfully started
s6-rc: info: service universal-silabs-flasher: starting
[14:41:12] INFO: Checking /dev/ttyUSB0 identifying SkyConnect v1.0 from Nabu Casa.
[14:41:12] INFO: Starting universal-silabs-flasher with /dev/ttyUSB0
2023-09-05 14:41:14 homeassistant universal_silabs_flasher.flash[185] INFO Extracted GBL metadata: NabuCasaMetadata(metadata_version=1, sdk_version='4.3.1', ezsp_version=None, ot_rcp_version=None, fw_type=<FirmwareImageType.RCP_UART_802154: 'rcp-uart-802154'>, baudrate=460800)
2023-09-05 14:41:14 homeassistant universal_silabs_flasher.flasher[185] INFO Probing ApplicationType.GECKO_BOOTLOADER at 115200 baud
2023-09-05 14:41:16 homeassistant universal_silabs_flasher.flasher[185] INFO Probing ApplicationType.CPC at 460800 baud
2023-09-05 14:41:20 homeassistant universal_silabs_flasher.flasher[185] INFO Probing ApplicationType.CPC at 115200 baud
2023-09-05 14:41:24 homeassistant universal_silabs_flasher.flasher[185] INFO Probing ApplicationType.CPC at 230400 baud
2023-09-05 14:41:29 homeassistant universal_silabs_flasher.flasher[185] INFO Probing ApplicationType.EZSP at 115200 baud
2023-09-05 14:41:34 homeassistant `universal_silabs_flasher.flasher[185]` INFO Probing ApplicationType.SPINEL at 460800 baud
Error: Failed to probe running application type
s6-rc: warning: unable to start service universal-silabs-flasher: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service mdns: stopping
s6-rc: info: service banner: stopping Default: mDNSResponder (Engineering Build) (Aug 23 2023 18:31:24) stopping
s6-rc: info: service banner successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
[14:41:38] INFO: mDNS ended with exit code 4 (signal 0)...
s6-rc: info: service mdns successfully stopped
```

**Comment by demono10000** [comment]
I found a solution to my problem. I switched from ZHA to zigbee2mqtt and now my zigbee network works normally. I don't have to restart anything every few hours anymore.
