### ISSUE TITLE
Mosquitto broker Update 6.3.1

### ISSUE THREAD

**Issue by geidorei** [home-assistant/addons#3204]
### Describe the issue you are experiencing

Won't install - 6.3.0 to 6.3.1

Can't install homeassistant/aarch64-addon-mosquitto:6.3.1: 500 Server Error for http+docker://localhost/v1.42/images/create?tag=6.3.1&fromImage=homeassistant%2Faarch64-addon-mosquitto&platform=linux%2Farm64: Internal Server Error ("Get "https://registry-1.docker.io/v2/": context deadline exceeded")

Have restarted and also shutdown HA.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Almond

### What is the version of the add-on?

6.3.1

### Steps to reproduce the issue

Ran update and also from add-ons - failed on both occasions

## System Information

version | core-2023.8.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4997
Installed Version | 1.32.1
Stage | running
Available Repositories | 1349
Downloaded Repositories | 63
HACS Data | failed to load: unreachable

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | December 9, 2023 at 12:00 AM
relayer_connected | true
relayer_region | us-east-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
remote_server | eu-central-1-3.ui.nabu.casa
certificate_status | ready
can_reach_cert_server | failed to load: unreachable
can_reach_cloud_auth | failed to load: unreachable
can_reach_cloud | failed to load: unreachable

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.08.3
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 116.5 GB
disk_used | 56.3 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | failed to load: unreachable
installed_addons | File editor (5.6.0), Samba share (10.0.2), Log Viewer (0.15.1), CEC Scanner (3.0), Mosquitto broker (6.3.0), AppDaemon (0.13.4), Studio Code Server (5.10.1), Advanced SSH & Web Terminal (15.0.7), eWeLink Smart Home (1.4.3), Kasa Camera (2.2), Zigbee2MQTT (1.33.0-1), ESPHome (2022.3.1), InfluxDB (4.7.0), MariaDB (2.6.1), RTSP Simple Server Add-on (v0.17.6), motionEye (0.19.1), Z-Wave JS (0.1.89), Matter Server (4.9.0), eufy-security-ws (1.6.4), Silicon Labs Multiprotocol (2.3.2), Whisper (1.0.0), Piper (1.3.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 13
-- | --
resources | 33
views | 44
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | August 27, 2023 at 10:04 AM
-- | --
current_recorder_run | September 6, 2023 at 3:31 PM
database_engine | mysql
database_version | 10.6.12

</details>

### Anything in the Supervisor logs that might be useful for us?

```txt
Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:130
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 3:33:36 PM (4 occurrences)
Last logged: 3:50:52 PM

Failed to to call /store/addons/core_mosquitto/update - Can't install homeassistant/aarch64-addon-mosquitto:6.3.1: 500 Server Error for http+docker://localhost/v1.42/images/create?tag=6.3.1&fromImage=homeassistant%2Faarch64-addon-mosquitto&platform=linux%2Farm64: Internal Server Error ("Head "https://registry-1.docker.io/v2/homeassistant/aarch64-addon-mosquitto/manifests/6.3.1": Get "https://auth.docker.io/token?scope=repository%3Ahomeassistant%2Faarch64-addon-mosquitto%3Apull&service=registry.docker.io": context deadline exceeded")
Failed to to call /store/addons/core_mosquitto/update - Can't install homeassistant/aarch64-addon-mosquitto:6.3.1: 500 Server Error for http+docker://localhost/v1.42/images/create?tag=6.3.1&fromImage=homeassistant%2Faarch64-addon-mosquitto&platform=linux%2Farm64: Internal Server Error ("Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)")
Failed to to call /store/addons/core_mosquitto/update - Can't install homeassistant/aarch64-addon-mosquitto:6.3.1: 500 Server Error for http+docker://localhost/v1.42/images/create?tag=6.3.1&fromImage=homeassistant%2Faarch64-addon-mosquitto&platform=linux%2Farm64: Internal Server Error ("Get "https://registry-1.docker.io/v2/": context deadline exceeded")
```

### Anything in the add-on logs that might be useful for us?

```txt
Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:130
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 3:33:36 PM (4 occurrences)
Last logged: 3:50:52 PM

Failed to to call /store/addons/core_mosquitto/update - Can't install homeassistant/aarch64-addon-mosquitto:6.3.1: 500 Server Error for http+docker://localhost/v1.42/images/create?tag=6.3.1&fromImage=homeassistant%2Faarch64-addon-mosquitto&platform=linux%2Farm64: Internal Server Error ("Head "https://registry-1.docker.io/v2/homeassistant/aarch64-addon-mosquitto/manifests/6.3.1": Get "https://auth.docker.io/token?scope=repository%3Ahomeassistant%2Faarch64-addon-mosquitto%3Apull&service=registry.docker.io": context deadline exceeded")
Failed to to call /store/addons/core_mosquitto/update - Can't install homeassistant/aarch64-addon-mosquitto:6.3.1: 500 Server Error for http+docker://localhost/v1.42/images/create?tag=6.3.1&fromImage=homeassistant%2Faarch64-addon-mosquitto&platform=linux%2Farm64: Internal Server Error ("Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)")
Failed to to call /store/addons/core_mosquitto/update - Can't install homeassistant/aarch64-addon-mosquitto:6.3.1: 500 Server Error for http+docker://localhost/v1.42/images/create?tag=6.3.1&fromImage=homeassistant%2Faarch64-addon-mosquitto&platform=linux%2Farm64: Internal Server Error ("Get "https://registry-1.docker.io/v2/": context deadline exceeded")
```

**Comment by aIexus** [comment]
I had similar issue sime time ago, and it' was fixed after I changed the DNS servers from Google to Cloudflare on my home  router.

**Comment by geidorei** [comment]
Updated eventually.....
