### ISSUE TITLE
Mosquitto broker update to 6.3.1 resulted in multiple apps unable to connect

### ISSUE THREAD

**Issue by snigehere** [home-assistant/addons#3205]
### Describe the issue you are experiencing

Error from multiple addons using mqtt

Unable to connect to the MQTT broker: Connection Refused: not authorised.

Backed out to 6.3.0 and all working again

I didn't see any docs that said I needed to make changes 

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Mosquitto broker

### What is the version of the add-on?

6.3.1

### Steps to reproduce the issue

1. Install 6.3.1 and restarted HA
2. All integrations that run mqtt unable to connect to the broker
3. Restarted broker - didn't solve it
4. restarted HA - didnt solve it
5. restored 6.3.0 and all ok
...

### System Health information

<html>
<body>
<h2 id="title" class="mdc-dialog__title" style="-webkit-font-smoothing: antialiased; font-family: var(--mdc-typography-headline6-font-family,var(--mdc-typography-font-family,Roboto,sans-serif)); font-size: var(--mdc-typography-headline6-font-size,1.25rem); line-height: var(--mdc-typography-headline6-line-height,2rem); font-weight: var(--mdc-typography-headline6-font-weight,500); letter-spacing: var(--mdc-typography-headline6-letter-spacing,.0125em); text-decoration: var(--mdc-typography-headline6-text-decoration,inherit); text-transform: var(--mdc-typography-headline6-text-transform,inherit); display: block; position: relative; flex-shrink: 0; box-sizing: border-box; margin: 0px 0px 1px; padding: 24px 24px 0px; color: var(--mdc-dialog-heading-ink-color,rgba(0,0,0,.87));"><div class="header_title" style="margin-right: 32px; margin-inline-end: 32px; margin-inline-start: initial; direction: var(--direction);">System information</div><ha-icon-button dialogaction="close" class="header_button" style="display: inline-block; outline: 0px; position: absolute; right: 16px; top: 14px; text-decoration: none; color: inherit; inset-inline-start: initial; inset-inline-end: 16px; direction: var(--direction);"><mwc-icon-button title="Close" style="display: inline-block; outline: 0px; --mdc-ripple-color: currentcolor; -webkit-tap-highlight-color: transparent; vertical-align: top; --mdc-theme-on-primary: currentColor; --mdc-theme-text-disabled-on-light: var(--disabled-text-color);"><button class="mdc-icon-button mdc-icon-button--display-flex" aria-label="Close" style="font-size: 24px; width: var(--mdc-icon-button-size,48px); height: var(--mdc-icon-button-size,48px); padding: calc((var(--mdc-icon-button-size,48px) - var(--mdc-icon-size,24px))/ 2); display: inline-flex; position: relative; box-sizing: border-box; border: none; outline: 0px; background-color: transparent; fill: currentcolor; color: inherit; text-decoration: none; cursor: pointer; user-select: none; z-index: 0; overflow: visible; align-items: center; justify-content: center; vertical-align: top;"><span><slot><ha-svg-icon style="display: block; align-items: center; justify-content: center; position: relative; vertical-align: middle; fill: currentcolor; width: var(--mdc-icon-size,24px); height: var(--mdc-icon-size,24px);"><svg preserveAspectRatio="xMidYMid meet" focusable="false" role="img" aria-hidden="true" viewBox="0 0 24 24"><g><path d="M19,6.41L17.59,5L12,10.59L6.41,5L5,6.41L10.59,12L5,17.59L6.41,19L12,13.41L17.59,19L19,17.59L13.41,12L19,6.41Z"></path></g></svg></ha-svg-icon></slot></span></button></mwc-icon-button></ha-icon-button></h2><div id="content" class="mdc-dialog__content" style="-webkit-font-smoothing: antialiased; font-family: var(--mdc-typography-body1-font-family,var(--mdc-typography-font-family,Roboto,sans-serif)); font-size: 14px; line-height: var(--mdc-typography-body1-line-height,1.5rem); font-weight: 400; letter-spacing: var(--mdc-typography-body1-letter-spacing,.03125em); text-decoration-line: ; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; text-transform: none; flex-grow: 1; box-sizing: border-box; margin: 0px; overflow: auto; color: rgb(33, 33, 33); padding: var(--dialog-content-padding,24px); position: var(--dialog-content-position,relative); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal;"><slot id="contentSlot" style="margin-top: 0px; margin-bottom: 0px;"><div><div>

Version | core-2023.8.4
-- | --
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.11.4
Operating System Family | Linux
Operating System Version | 6.1.45
CPU Architecture | x86_64
Timezone | Europe/London
Configuration Directory | /config

</div><div><h3>Core Metrics</h3><ha-metric><ha-settings-row style="display: flex; padding: 0px; align-content: normal; align-self: auto; align-items: center; height: 54px; width: 535px;"><div class="prefix-wrap" style="display: var(--settings-row-prefix-display);"><slot name="prefix"></slot><div class="body" two-line="" style="padding: 8px 16px 8px 0px; overflow: hidden; display: var(--layout-vertical_-_display); flex-direction: var(--layout-vertical_-_flex-direction); justify-content: var(--layout-center-justified_-_justify-content); flex: 1 1 0%; min-height: calc(var(--paper-item-body-two-line-min-height,72px) - 16px);"><slot name="heading" style="overflow: hidden; text-overflow: ellipsis; white-space: nowrap;"><span slot="heading">Processor Usage</span></slot><div class="secondary" style="overflow: hidden; text-overflow: ellipsis; white-space: normal; display: block; padding-top: 4px; font-family: var(--mdc-typography-body2-font-family,var(--mdc-typography-font-family,Roboto,sans-serif)); -webkit-font-smoothing: antialiased; font-size: var(--mdc-typography-body2-font-size,.875rem); font-weight: var(--mdc-typography-body2-font-weight,400); line-height: normal; color: var(--secondary-text-color);"><slot name="description"><div slot="description" title="" style="white-space: normal; color: var(--secondary-text-color); display: flex; justify-content: space-between;"><span class="value" style="width: 48px; padding-right: 4px; flex-shrink: 0;">0.5<span> </span>%</span><ha-bar class="  " style="--ha-bar-primary-color: var(
          --metric-bar-ok-color,
          var(--success-color)
        );"><svg><g><rect></rect><rect width="0.5%"></rect></g></svg></ha-bar></div></slot></div></div></div><div class="content" style="display: var(--settings-row-content-display,flex); justify-content: flex-end; flex: 1 1 0%; padding: 16px 0px;"><slot></slot></div></ha-settings-row></ha-metric><ha-metric><ha-settings-row style="display: flex; padding: 0px; align-content: normal; align-self: auto; align-items: center; height: 54px; width: 535px;"><div class="prefix-wrap" style="display: var(--settings-row-prefix-display);"><slot name="prefix"></slot><div class="body" two-line="" style="padding: 8px 16px 8px 0px; overflow: hidden; display: var(--layout-vertical_-_display); flex-direction: var(--layout-vertical_-_flex-direction); justify-content: var(--layout-center-justified_-_justify-content); flex: 1 1 0%; min-height: calc(var(--paper-item-body-two-line-min-height,72px) - 16px);"><slot name="heading" style="overflow: hidden; text-overflow: ellipsis; white-space: nowrap;"><span slot="heading">Memory Usage</span></slot><div class="secondary" style="overflow: hidden; text-overflow: ellipsis; white-space: normal; display: block; padding-top: 4px; font-family: var(--mdc-typography-body2-font-family,var(--mdc-typography-font-family,Roboto,sans-serif)); -webkit-font-smoothing: antialiased; font-size: var(--mdc-typography-body2-font-size,.875rem); font-weight: var(--mdc-typography-body2-font-weight,400); line-height: normal; color: var(--secondary-text-color);"><slot name="description"><div slot="description" title="" style="white-space: normal; color: var(--secondary-text-color); display: flex; justify-content: space-between;"><span class="value" style="width: 48px; padding-right: 4px; flex-shrink: 0;">20.2<span> </span>%</span><ha-bar class="  " style="--ha-bar-primary-color: var(
          --metric-bar-ok-color,
          var(--success-color)
        );"><svg><g><rect></rect><rect width="20.2%"></rect></g></svg></ha-bar></div></slot></div></div></div><div class="content" style="display: var(--settings-row-content-display,flex); justify-content: flex-end; flex: 1 1 0%; padding: 16px 0px;"><slot></slot></div></ha-settings-row></ha-metric><h3>Supervisor Metrics</h3><ha-metric><ha-settings-row style="display: flex; padding: 0px; align-content: normal; align-self: auto; align-items: center; height: 54px; width: 535px;"><div class="prefix-wrap" style="display: var(--settings-row-prefix-display);"><slot name="prefix"></slot><div class="body" two-line="" style="padding: 8px 16px 8px 0px; overflow: hidden; display: var(--layout-vertical_-_display); flex-direction: var(--layout-vertical_-_flex-direction); justify-content: var(--layout-center-justified_-_justify-content); flex: 1 1 0%; min-height: calc(var(--paper-item-body-two-line-min-height,72px) - 16px);"><slot name="heading" style="overflow: hidden; text-overflow: ellipsis; white-space: nowrap;"><span slot="heading">Processor Usage</span></slot><div class="secondary" style="overflow: hidden; text-overflow: ellipsis; white-space: normal; display: block; padding-top: 4px; font-family: var(--mdc-typography-body2-font-family,var(--mdc-typography-font-family,Roboto,sans-serif)); -webkit-font-smoothing: antialiased; font-size: var(--mdc-typography-body2-font-size,.875rem); font-weight: var(--mdc-typography-body2-font-weight,400); line-height: normal; color: var(--secondary-text-color);"><slot name="description"><div slot="description" title="" style="white-space: normal; color: var(--secondary-text-color); display: flex; justify-content: space-between;"><span class="value" style="width: 48px; padding-right: 4px; flex-shrink: 0;">0<span> </span>%</span><ha-bar class="  " style="--ha-bar-primary-color: var(
          --metric-bar-ok-color,
          var(--success-color)
        );"><svg><g><rect></rect><rect width="0%"></rect></g></svg></ha-bar></div></slot></div></div></div><div class="content" style="display: var(--settings-row-content-display,flex); justify-content: flex-end; flex: 1 1 0%; padding: 16px 0px;"><slot></slot></div></ha-settings-row></ha-metric><ha-metric><ha-settings-row style="display: flex; padding: 0px; align-content: normal; align-self: auto; align-items: center; height: 54px; width: 535px;"><div class="prefix-wrap" style="display: var(--settings-row-prefix-display);"><slot name="prefix"></slot><div class="body" two-line="" style="padding: 8px 16px 8px 0px; overflow: hidden; display: var(--layout-vertical_-_display); flex-direction: var(--layout-vertical_-_flex-direction); justify-content: var(--layout-center-justified_-_justify-content); flex: 1 1 0%; min-height: calc(var(--paper-item-body-two-line-min-height,72px) - 16px);"><slot name="heading" style="overflow: hidden; text-overflow: ellipsis; white-space: nowrap;"><span slot="heading">Memory Usage</span></slot><div class="secondary" style="overflow: hidden; text-overflow: ellipsis; white-space: normal; display: block; padding-top: 4px; font-family: var(--mdc-typography-body2-font-family,var(--mdc-typography-font-family,Roboto,sans-serif)); -webkit-font-smoothing: antialiased; font-size: var(--mdc-typography-body2-font-size,.875rem); font-weight: var(--mdc-typography-body2-font-weight,400); line-height: normal; color: var(--secondary-text-color);"><slot name="description"><div slot="description" title="" style="white-space: normal; color: var(--secondary-text-color); display: flex; justify-content: space-between;"><span class="value" style="width: 48px; padding-right: 4px; flex-shrink: 0;">4.5<span> </span>%</span></div></slot></div></div></div></ha-settings-row></ha-metric></div></div></slot></div>
</body>
</html>System information
Version	core-2023.8.4
Installation Type	Home Assistant OS
Development	false
Supervisor	true
Docker	true
User	root
Virtual Environment	false
Python Version	3.11.4
Operating System Family	Linux
Operating System Version	6.1.45
CPU Architecture	x86_64
Timezone	Europe/London
Configuration Directory	/config
Home Assistant Community Store
GitHub API	ok
GitHub Content	ok
GitHub Web	ok
GitHub API Calls Remaining	4857
Installed Version	1.32.1
Stage	running
Available Repositories	1348
Downloaded Repositories	22
Home Assistant Cloud
Logged In	true
Subscription Expiration	12 September 2023 at 01:00
Relayer Connected	true
Relayer Region	eu-central-1
Remote Enabled	true
Remote Connected	true
Alexa Enabled	true
Google Enabled	false
Remote Server	eu-central-1-6.ui.nabu.casa
Certificate Status	ready
Reach Certificate Server	ok
Reach Authentication Server	ok
Reach Home Assistant Cloud	ok
Home Assistant Supervisor
Host Operating System	Home Assistant OS 10.5
Update Channel	stable
Supervisor Version	supervisor-2023.08.3
Agent Version	1.5.1
Docker Version	23.0.6
Disk Total	30.8 GB
Disk Used	11.8 GB
Healthy	true
Supported	true
Board	ova
Supervisor API	ok
Version API	ok
Installed Add-ons	Advanced SSH & Web Terminal (15.0.7), Samba share (10.0.2), Studio Code Server (5.10.1), Mosquitto broker (6.3.0), SQLite Web (3.9.2), Zigbee2MQTT (1.33.0-1), Ring-MQTT with Video Streaming (5.6.2), Terminal & SSH (9.7.1), OneDrive Backup (2.02), Hildebrand Glow To MQTT (1.3.0), Ginlong Solis Wi-Fi To MQTT (1.1.0)
Dashboards
Dashboards	20
Resources	11
Views	24
Mode	storage
Recorder
Oldest Run Start Time	31 August 2023 at 23:34
Current Run Start Time	6 September 2023 at 17:56
Estimated Database Size (MiB)	502.46 MiB
Database Engine	sqlite
Database Version	3.41.2
Solcast PV Forecast
Solcast server connection	ok
API requests remaining	10
Rooftop site count	2
Sonoff
Version	3.5.2 (2ad1cd7)
Cloud devices online	0 / 2
Local devices online	2 / 3
Debug page	– [more info](http://homeassistant.local:8123/api/sonoff/e0f4e16c-2979-4dac-af7a-b6d605436141)
Core Metrics
Processor Usage
0.5 %
Memory Usage
20.2 %
Supervisor Metrics
Processor Usage
0 %
Memory Usage
4.5 %

### Anything in the Supervisor logs that might be useful for us?

```txt
2023-09-06 17:57:00.005 ERROR (Thread-4 (_thread_main)) [homeassistant.components.mqtt.client] Unable to connect to the MQTT broker: Connection Refused: not authorised.
2023-09-06 17:57:00.126 WARNING (Thread-4 (_thread_main)) [homeassistant.components.mqtt.client] Disconnected from MQTT server core-mosquitto:1883 (5)
2023-09-06 17:57:01.129 ERROR (Thread-4 (_thread_main)) [homeassistant.components.mqtt.client] Unable to connect to the MQTT broker: Connection Refused: not authorised.
2023-09-06 17:57:01.131 WARNING (Thread-4 (_thread_main)) [homeassistant.components.mqtt.client] Disconnected from MQTT server core-mosquitto:1883 (5)
2023-09-06 17:57:03.084 INFO (MainThread) [custom_components.solis.sensor] Scheduling discovery
2023-09-06 17:57:03.084 DEBUG (MainThread) [custom_components.solis.service] Scheduling discovery in 1 seconds.
2023-09-06 17:57:03.134 ERROR (Thread-4 (_thread_main)) [homeassistant.components.mqtt.client] Unable to connect to the MQTT broker: Connection Refused: not authorised.
```

**Comment by rodrigocvv** [comment]
I am having the same issue here.

**Comment by franklinvv** [comment]
I have the same issue. I can't connect either, not even with a stand-alone MQTT client. When I rolled back to a backup for 6.3.0 things started working again.

**Comment by snigehere** [comment]
I did toggled it on and off and checked in the yaml it showed false but that didn't fix it

**Comment by snigehere** [comment]
Update
I have recently updated home assistant to a new release
<html>
<body>
<h2 id="title" class="mdc-dialog__title" style="-webkit-font-smoothing: antialiased; font-family: var(--mdc-typography-headline6-font-family,var(--mdc-typography-font-family,Roboto,sans-serif)); font-size: var(--mdc-typography-headline6-font-size,1.25rem); line-height: var(--mdc-typography-headline6-line-height,2rem); font-weight: var(--mdc-typography-headline6-font-weight,500); letter-spacing: var(--mdc-typography-headline6-letter-spacing,.0125em); text-decoration: var(--mdc-typography-headline6-text-decoration,inherit); text-transform: var(--mdc-typography-headline6-text-transform,inherit); display: block; position: relative; flex-shrink: 0; box-sizing: border-box; margin: 0px 0px 1px; padding: 24px 24px 0px; color: var(--mdc-dialog-heading-ink-color,rgba(0,0,0,.87));"><div class="header_title" style="margin-right: 32px; margin-inline-end: 32px; margin-inline-start: initial; direction: var(--direction);">System information</div><ha-icon-button dialogaction="close" class="header_button" style="display: inline-block; outline: 0px; position: absolute; right: 16px; top: 14px; text-decoration: none; color: inherit; inset-inline-start: initial; inset-inline-end: 16px; direction: var(--direction);"><mwc-icon-button title="Close" style="display: inline-block; outline: 0px; --mdc-ripple-color: currentcolor; -webkit-tap-highlight-color: transparent; vertical-align: top; --mdc-theme-on-primary: currentColor; --mdc-theme-text-disabled-on-light: var(--disabled-text-color);"><button class="mdc-icon-button mdc-icon-button--display-flex" aria-label="Close" style="font-size: 24px; width: var(--mdc-icon-button-size,48px); height: var(--mdc-icon-button-size,48px); padding: calc((var(--mdc-icon-button-size,48px) - var(--mdc-icon-size,24px))/ 2); display: inline-flex; position: relative; box-sizing: border-box; border: none; outline: 0px; background-color: transparent; fill: currentcolor; color: inherit; text-decoration: none; cursor: pointer; user-select: none; z-index: 0; overflow: visible; align-items: center; justify-content: center; vertical-align: top;"><mwc-ripple unbounded="" style="position: absolute; top: 0px; left: 0px; width: 48px; height: 48px; pointer-events: none; display: block;"><div class="mdc-ripple-surface mdc-ripple-upgraded mdc-ripple-upgraded--unbounded" style="--mdc-ripple-fg-size: 28px; --mdc-ripple-left: 10px; --mdc-ripple-top: 10px; --mdc-ripple-fg-scale: 1.7142857142857142; --mdc-ripple-fg-translate-end: 0; --mdc-ripple-fg-translate-start: 0; -webkit-tap-highlight-color: transparent; will-change: unset; position: absolute; outline: 0px; overflow: visible; --mdc-ripple-fg-opacity: var(--mdc-ripple-press-opacity, 0.12); top: 0px; left: 0px; width: 48px; height: 48px; pointer-events: none;"></div></mwc-ripple><span><slot><ha-svg-icon style="display: block; align-items: center; justify-content: center; position: relative; vertical-align: middle; fill: currentcolor; width: var(--mdc-icon-size,24px); height: var(--mdc-icon-size,24px);"><svg preserveAspectRatio="xMidYMid meet" focusable="false" role="img" aria-hidden="true" viewBox="0 0 24 24"><g><path d="M19,6.41L17.59,5L12,10.59L6.41,5L5,6.41L10.59,12L5,17.59L6.41,19L12,13.41L17.59,19L19,17.59L13.41,12L19,6.41Z"></path></g></svg></ha-svg-icon></slot></span></button></mwc-icon-button></ha-icon-button></h2><div id="content" class="mdc-dialog__content" style="-webkit-font-smoothing: antialiased; font-family: var(--mdc-typography-body1-font-family,var(--mdc-typography-font-family,Roboto,sans-serif)); font-size: 14px; line-height: var(--mdc-typography-body1-line-height,1.5rem); font-weight: 400; letter-spacing: var(--mdc-typography-body1-letter-spacing,.03125em); text-decoration-line: ; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; text-transform: none; flex-grow: 1; box-sizing: border-box; margin: 0px; overflow: auto; color: rgb(33, 33, 33); padding: var(--dialog-content-padding,24px); position: var(--dialog-content-position,relative); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal;"><slot id="contentSlot" style="margin-top: 0px; margin-bottom: 0px;"><div><div>

Version | core-2023.9.1
-- | --
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.11.5
Operating System Family | Linux
Operating System Version | 6.1.45
CPU Architecture | x86_64
Timezone | Europe/London
Configuration Directory | /config

</div></div></slot></div>
</body>
</html>

<html>
<body>
<div class="card-header" style="justify-content: space-between; display: flex; align-items: center; color: rgb(33, 33, 33); font-family: Roboto, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: 0.4375px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h3>Home Assistant Supervisor</h3></div>

Host Operating System | Home Assistant OS 10.5
-- | --
Update Channel | stable
Supervisor Version | supervisor-2023.08.3
Agent Version | 1.5.1
Docker Version | 23.0.6
Disk Total | 30.8 GB
Disk Used | 12.3 GB
Healthy | true
Supported | true
Board | ova
Supervisor API | ok
Version API | ok


</body>
</html>

So I thought I would again try the update of the addin to 6.3.1 to see if it still failed and, if so, try and collect more logs

I installed and all was ok... restarted HA and all was ok ... so it looks like it is ok this second time around ... I don't know if its connected to HA version or some issue during the first install but its now good for me.

I will not mark as closed for the moment as some others also reported the issue .. if they are also ok on a second go I will mark closed.

**Comment by mspiridakis** [comment]
Same here!

**Comment by snigehere** [comment]
closing
