### ISSUE TITLE
Piper will not start if selected voice has non-ascii characters in its name

### ISSUE THREAD

**Issue by AfmanS** [home-assistant/addons#3207]
### Describe the issue you are experiencing

With the 2023.09 update, a voice was added to Portuguese of Portugal called "Tugão". When it is selected, Piper will not start. The add-on log includes an error when encoding to ascii.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Piper

### What is the version of the add-on?

1.3.2

### Steps to reproduce the issue

1. Stop Piper
2. Select pt_PT-tugão-medium as the voice in the Configuration tab.
3. Start Piper

## System Information

version | core-2023.9.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.5
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | Europe/Lisbon
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4996
Installed Version | 1.32.1
Stage | running
Available Repositories | 1279
Downloaded Repositories | 5

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.08.3
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 113.6 GB
disk_used | 6.0 GB
healthy | true
supported | true
board | rpi3-64
supervisor_api | ok
version_api | ok
installed_addons | Home Assistant Google Drive Backup (0.111.1), Duck DNS (1.15.0), Studio Code Server (5.10.1), NGINX Home Assistant SSL proxy (3.5.0), Samba share (10.0.2), Terminal & SSH (9.7.1), Mosquitto broker (6.3.1), Piper (1.3.2)

</details>

<details><summary>Instituto Português do Mar e Atmosfera (IPMA)</summary>

api_endpoint_reachable | ok
-- | --

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 3
views | 2
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | August 30, 2023 at 07:58
-- | --
current_recorder_run | September 7, 2023 at 00:36
estimated_db_size | 30.21 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Anything in the Supervisor logs that might be useful for us?

```txt
23-09-07 19:33:58 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-piper with version 1.3.2
23-09-07 19:35:58 WARNING (MainThread) [supervisor.addons.addon] Timeout while waiting for addon Piper to start, took more then 120 seconds
```

### Anything in the add-on logs that might be useful for us?

```txt
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/dist-packages/wyoming_piper/__main__.py", line 193, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wyoming_piper/__main__.py", line 161, in main
    await process_manager.get_process()
  File "/usr/local/lib/python3.11/dist-packages/wyoming_piper/process.py", line 114, in get_process
    ensure_voice_exists(
  File "/usr/local/lib/python3.11/dist-packages/wyoming_piper/download.py", line 137, in ensure_voice_exists
    with urlopen(file_url) as response, open(
         ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.11/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1293, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/lib/python3.11/http/client.py", line 1131, in putrequest
    self._output(self._encode_request(request))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/http/client.py", line 1211, in _encode_request
    return request.encode('ascii')
           ^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'ascii' codec can't encode character '\xe3' in position 53: ordinal not in range(128)
[19:36:55] INFO: Service exited with code 1 (by signal 0)
```

**Comment by tiagobluiz** [comment]
It seems to me that the problem is with the usage of `ã` character in the title. Either HA is able to change the character encoding to support it, or alternatively, I would accept changing the name from `tugão` to `tuga`, as the voice provider for PT-pt I wouldn't mind.

**Comment by SoulOnFire** [comment]
I have the same issue if select that voice.

**Comment by zephirus** [comment]
Any way to solve this?

**Comment by gffa325** [comment]
I have the same issue with voice pt-PT selected.

**Comment by synesthesiam** [comment]
Please update to add-on version 1.4.0 and try again

**Comment by zephirus** [comment]
The error is gone but I can't get my voice to be detected. Don't know if it's just me but I press the mic, it's listening but nothing happens, ever

**Comment by AfmanS** [comment]
Using version 1.4.0, Piper starts successfully, but the Piper integration isn't automatically detecting the add-on.

**Comment by AfmanS** [comment]
After updating to 2023.10 the integration now detects Piper, maybe my system just needed a reboot. Either way Piper now works well with the tugão-medium voice.
