### ISSUE TITLE
Brand new SkyConnect v1.0 with stock firmware keeps looping between Failed setup, will retry and Initializing

### ISSUE THREAD

**Issue by jiriappl** [home-assistant/addons#3208]
### Describe the issue you are experiencing

Just got a new SkyConnect with stock firmware and connected it using the provided USB extension cable to my HA install.

Alas, SkyConnect under ZHA keeps looping between Failed setup, will retry and Initializing, and does not seem to complete the initial setup.

I have tried to reboot HA, use different USB port and different USB cable, no change.

HA config:
HAOS latest bits, running on Intel NUC.

HA Core logs report 
```
Logger: universal_silabs_flasher.cpc
Source: runner.py:186
First occurred: 3:21:11 PM (276 occurrences)
Last logged: 10:44:41 PM

Failed to parse buffer bytearray(b'\xf8'): ValueError('Invalid flag')
```

From Full log:
```
2023-09-09 22:36:36.113 WARNING (MainThread) [universal_silabs_flasher.cpc] Failed to parse buffer bytearray(b'\xf8'): ValueError('Invalid flag')
2023-09-09 22:38:13.312 WARNING (MainThread) [universal_silabs_flasher.cpc] Failed to parse buffer bytearray(b'\xf8'): ValueError('Invalid flag')
2023-09-09 22:39:50.724 WARNING (MainThread) [universal_silabs_flasher.cpc] Failed to parse buffer bytearray(b'\xf8'): ValueError('Invalid flag')
2023-09-09 22:41:27.624 WARNING (MainThread) [universal_silabs_flasher.cpc] Failed to parse buffer bytearray(b'\xf8'): ValueError('Invalid flag')
2023-09-09 22:43:04.725 WARNING (MainThread) [universal_silabs_flasher.cpc] Failed to parse buffer bytearray(b'\xf8'): ValueError('Invalid flag')
2023-09-09 22:44:41.584 WARNING (MainThread) [universal_silabs_flasher.cpc] Failed to parse buffer bytearray(b'\xf8'): ValueError('Invalid flag')
2023-09-09 22:46:18.423 WARNING (MainThread) [universal_silabs_flasher.cpc] Failed to parse buffer bytearray(b'\xf8'): ValueError('Invalid flag')
```

Enabling debug log: [excerpt](https://pastebin.com/wi6HYd0h).

Please advise on the next troubleshooting steps.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Almond

### What is the version of the add-on?

Included in the HAOS core, 2309.1.

### Steps to reproduce the issue

1. Plugin SkyConnect.
2. Observe it never completing Initializing successfully.

## System Information

version | core-2023.9.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.5
os_name | Linux
os_version | 6.1.45
arch | x86_64
timezone | America/Los_Angeles
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | December 27, 2023 at 4:00 PM
relayer_connected | true
relayer_region | us-east-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | us-east-1-9.ui.nabu.casa
certificate_status | ready
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.08.3
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 234.0 GB
disk_used | 11.4 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.6.0), Z-Wave JS (0.1.89), Terminal & SSH (9.7.1), Mosquitto broker (6.3.1), NGINX Home Assistant SSL proxy (3.5.0), Samba share (10.0.2), Advanced SSH & Web Terminal (15.0.7)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 0
views | 19
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | September 4, 2023 at 5:03 AM
-- | --
current_recorder_run | September 9, 2023 at 3:20 PM
estimated_db_size | 255.34 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Comment by darkxst** [comment]
This is an issue in HA core and not related to any addons, thus this is the wrong place to report this.

You should open an issue on the below repo instead:
https://github.com/home-assistant/core/issues

**Comment by jiriappl** [comment]
Thanks, created https://github.com/home-assistant/core/issues/100167, in case anybody comes here looking for the resolution of the same issue.
