### ISSUE TITLE
File Editor Stop to Work - 500 Internal Server Error Server got itself in trouble

### ISSUE THREAD

**Issue by giugit** [home-assistant/addons#3212]
### Describe the issue you are experiencing

File Editor not start with the error in the object

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Almond

### What is the version of the add-on?

Current version: 5.6.0

### Steps to reproduce the issue

1. Just click on the icon to open it
2.
3.
...

### System Health information

Nothing

**Comment by agners** [comment]
This is probably related to https://github.com/home-assistant/supervisor/issues/4547.

What Home Assistant Core version are you using?
