### ISSUE TITLE
[SSH Server] Listen only on specific interface

### ISSUE THREAD

**Issue by rwjack** [home-assistant/addons#3219]
### Describe the issue you are experiencing

There really should be an option to listen on a specific (management) interface, instead of listening on all, especially if additional IOT interfaces are configured.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

 SSH Server

### What is the version of the add-on?

9.7.1

### Steps to reproduce the issue

...

### System Health information

...

**Comment by FreelancerJay** [comment]
I would agree that an option to specify listening interfaces would add value to the addon...
Have you opened a "Feature Request" post on the community discourse? Might get a few more eyes on the idea and at least it won't completely disappear from the Stale bot...

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

**Comment by rwjack** [comment]
Leaving this here for future reference: https://community.home-assistant.io/t/ssh-server-listen-only-on-specific-interface/639623/3
