### ISSUE TITLE
XSS in File Editor

### ISSUE THREAD

**Issue by psenakv** [home-assistant/addons#3238]
### Describe the issue you are experiencing

If I have entity with name of <script>alert('XSS');</script> (it was not intentional, my phone is named like this, so it got into the entity name), the File Editor is unusable, because it will run the script and fire alerts indefinitely. It could also probably lead to some vulnerabilities.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

File editor

### What is the version of the add-on?

5.6.0

### Steps to reproduce the issue

1.
2.
3.
...

## System Information

version | core-2023.9.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.5
os_name | Linux
os_version | 6.1.45
arch | x86_64
timezone | Europe/Prague
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4998
Installed Version | 1.32.1
Stage | running
Available Repositories | 1293
Downloaded Repositories | 3

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.09.2
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 219.4 GB
disk_used | 10.9 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | ESPHome (2023.8.2), Studio Code Server (5.10.1), Advanced SSH & Web Terminal (15.0.7), Mosquitto broker (6.3.0), Node-RED (14.4.5), File editor (5.6.0), HassOS SSH port 22222 Configurator (0.9.3), NSPanel Manager (0.1.22)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 0
views | 10
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 22 September 2023 at 23:56
-- | --
current_recorder_run | 29 September 2023 at 20:24
estimated_db_size | 48.78 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

**Comment by adamjezek98** [comment]
It's not indefinitely, only 20-30 alerts pop out (I guess for every entity added by the mobile application). But the list of entities spills into the page, and the file editor can't load any files, so it's still unusable.

**Comment by ludeeus** [comment]
This has to be reported and adjusted in the [hass-configurator](https://github.com/danielperna84/hass-configurator) repository 👍
