### ISSUE TITLE
File Editor gives an error "401: Unauthorized"

### ISSUE THREAD

**Issue by MaxSychevskiy** [home-assistant/addons#3239]
### Describe the issue you are experiencing

Hi,

I was playing with Cloufflare add-on that did not want to work on my HA but at some point File Editor tat I used for YAML configuration code edit stopped working. It gives an error  "401: Unauthorized" and I don't know what to do.
I tried to uninstall the File Editor and Install it back without any effect.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Almond

### What is the version of the add-on?

Current version: 5.6.0

### Steps to reproduce the issue

1. Open the File editor Web UI
2.
3.
...

## System Information

version | core-2023.9.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.5
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.32.1
Stage | running
Available Repositories | 1359
Downloaded Repositories | 2

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.09.2
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 57.8 GB
disk_used | 3.9 GB
healthy | true
supported | true
board | rpi3-64
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.7.1), FTP (4.7.2), Mosquitto broker (6.3.1), Cloudflared (4.2.7), File editor (5.6.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 0
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 25 September 2023 at 10:57
-- | --
current_recorder_run | 30 September 2023 at 19:46
estimated_db_size | 4.46 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Anything in the Supervisor logs that might be useful for us?

```txt
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service configurator: starting
s6-rc: info: service configurator successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
INFO:2023-09-30 22:30:51,574:hass_configurator.configurator:Starting server
INFO:2023-09-30 22:30:51,577:hass_configurator.configurator:Listening on: http://0.0.0.0:8099
INFO:2023-09-30 22:31:14,395:hass_configurator.configurator:127.0.0.1 - "GET / HTTP/1.1" 200 -
INFO:2023-09-30 22:31:44,875:hass_configurator.configurator:127.0.0.1 - "GET / HTTP/1.1" 200 -
INFO:2023-09-30 22:32:15,385:hass_configurator.configurator:127.0.0.1 - "GET / HTTP/1.1" 200 -
INFO:2023-09-30 22:32:45,793:hass_configurator.configurator:127.0.0.1 - "GET / HTTP/1.1" 200 -
INFO:2023-09-30 22:33:16,193:hass_configurator.configurator:127.0.0.1 - "GET / HTTP/1.1" 200 -
INFO:2023-09-30 22:33:46,600:hass_configurator.configurator:127.0.0.1 - "GET / HTTP/1.1" 200 -
INFO:2023-09-30 22:34:17,011:hass_configurator.configurator:127.0.0.1 - "GET / HTTP/1.1" 200 -
INFO:2023-09-30 22:34:47,410:hass_configurator.configurator:127.0.0.1 - "GET / HTTP/1.1" 200 -
INFO:2023-09-30 22:35:17,803:hass_configurator.configurator:127.0.0.1 - "GET / HTTP/1.1" 200 -
INFO:2023-09-30 22:35:48,185:hass_configurator.configurator:127.0.0.1 - "GET / HTTP/1.1" 200 -
INFO:2023-09-30 22:36:18,600:hass_configurator.configurator:127.0.0.1 - "GET / HTTP/1.1" 200 -
INFO:2023-09-30 22:36:48,999:hass_configurator.configurator:127.0.0.1 - "GET / HTTP/1.1" 200 -
INFO:2023-09-30 22:37:19,407:hass_configurator.configurator:127.0.0.1 - "GET / HTTP/1.1" 200 -
INFO:2023-09-30 22:37:49,803:hass_configurator.configurator:127.0.0.1 - "GET / HTTP/1.1" 200 -
INFO:2023-09-30 22:38:20,194:hass_configurator.configurator:127.0.0.1 - "GET / HTTP/1.1" 200 -
INFO:2023-09-30 22:38:50,584:hass_configurator.configurator:127.0.0.1 - "GET / HTTP/1.1" 200 -
INFO:2023-09-30 22:39:20,983:hass_configurator.configurator:127.0.0.1 - "GET / HTTP/1.1" 200 -
```

**Comment by st-pavel** [comment]
I have same error.

**Comment by posinahual** [comment]
I have same error.

**Comment by Menz01** [comment]
i have the same issue as well

**Comment by Maxfactor13** [comment]
I have same error. Current version: 5.8.0

**Comment by Mikael2235** [comment]
Same error here !

**Comment by netzkopf** [comment]
Same problem here with version 5.8.0.
Not sure if it is a problem with the file editor though.
To me it also happens for zigbee2mqtt and the music assistant.

**Comment by ndrwrbgs** [comment]
I experienced an issue that appeared to match the description here.

This post seemed relevant, and the work around worked: https://community.home-assistant.io/t/file-configurator-401-unauthorized-error/194584/2
> @danielperna84 on May 11, 2020
> Can you try it with a different browser or in whatever private mode your browser has? The configurator memorizes the last location that it has accessed. If this location isn’t present anymore after your crash that could be a problem. Using a _fresh_ browser will result in accessing the base directory.


In Chrome Developer Tools, clearing various cookie values and Local storage did not seem to have any impact, but the option of `Application > Storage > Clear site data` **resolved the issue**.

<img width="600" height="250" alt="Image" src="https://github.com/user-attachments/assets/9474eb17-3c8d-4124-a552-305c17f0b724" />
