### ISSUE TITLE
Matter server compiled to armv7

### ISSUE THREAD

**Issue by RTodorov** [home-assistant/addons#3242]
### Describe the issue you are experiencing

Hello there, are there any plans to make the _matter_ server available for armv7 (for running on Raspberry PIs)?

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Almond

### What is the version of the add-on?

4.9.0

### Steps to reproduce the issue

1. Go to the add-on store
2. Search for matter
3. See that the install button is disabled. See only aarch64 and amd64 as supported platforms. See message "This add-on is not compatible with the processor of your device"

## System Information

version | core-2023.9.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.5
os_name | Linux
os_version | 6.1.21-v7
arch | armv7l
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | October 17, 2023 at 2:00 AM
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
remote_server | eu-central-1-5.ui.nabu.casa
certificate_status | ready
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.09.2
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 28.5 GB
disk_used | 4.8 GB
healthy | true
supported | true
board | rpi3
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.6.0), Terminal & SSH (9.7.1), Let's Encrypt (4.12.9)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 0
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | September 25, 2023 at 10:24 PM
-- | --
current_recorder_run | September 26, 2023 at 6:17 PM
estimated_db_size | 34.99 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

**Comment by ludeeus** [comment]
Please use the [forums](https://community.home-assistant.io/) for feature requests and general questions 👍
