### ISSUE TITLE
DHCP server addon NOT starting after upgrade to OS 11.0

### ISSUE THREAD

**Issue by github-1a** [home-assistant/addons#3262]
### Describe the issue you are experiencing

DHCP server addon NOT starting after upgrade to operating system 11.0, configuration was working previously, log follows:

[13:04:05] INFO: Creating DHCP configuration...
[13:04:10] INFO: Starting DHCP server...
Internet Systems Consortium DHCP Server 4.4.2-P1
Copyright 2004-2021 Internet Systems Consortium.
All rights reserved.
For info, please visit https://www.isc.org/software/dhcp/
Config file: /etc/dhcpd.conf
Database file: /data/dhcpd.lease
PID file: /run/dhcp/dhcpd.pid
Wrote 0 deleted host decls to leases file.
Wrote 0 new dynamic host decls to leases file.
Wrote 32 leases to leases file.
Multiple interfaces match the same shared network: eth0 end0
Failed to get interface index: No such device

If you think you have received this message due to a bug rather
than a configuration issue please read the section on submitting
bugs on either our web page at www.isc.org or in the README file
before submitting a bug.  These pages explain the proper
process and the information we find helpful for debugging.

exiting.
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Almond

### What is the version of the add-on?

1.3.0 /current/

### Steps to reproduce the issue

1. upgrade os to 11.0
2. DHCP sever NOT starting automatic as usually, manual start also ends with same error
3. 
...

### System Health information

No issues

**Comment by DimVKir** [comment]
Just replace in the config:
  interface: eth0
on
  interface: end0

**Comment by github-1a** [comment]
Right. This quite breaking change... Thank you.
