### ISSUE TITLE
Whisper accuracy, and ERROR:asyncio:Task exception was never retrieved

### ISSUE THREAD

**Issue by donburch888** [home-assistant/addons#3265]
### Describe the issue you are experiencing

A couple of minor issues:

1. I am trying to improve the STT accuracy.  I have swapped microphone and now the recorded audio ( using homeassistant-satellite on a RasPi 3B) is clear.  I run HAOS in a Proxmox VM on a Intel i5 PC with 2 cores and 8GB RAM.  Rhasspy runs on same hardware. 
With Whisper (HA add-on) set to default "tiny-int8" model, only about 1 in 3 commands to "Turn on study light" were recognized.  With Whisper set to “small” model, about 1 in 2 of my requests to turn the study light on or off were recognized:
```s6-rc: info: service discovery: starting
INFO:__main__:Ready
[12:48:58] INFO: Successfully send discovery information to Home Assistant.
s6-rc: info: service discovery successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
INFO:wyoming_faster_whisper.handler: Turn on the study light.
INFO:wyoming_faster_whisper.handler: Turn the studied light off.
INFO:wyoming_faster_whisper.handler: Turn the studied light off.
INFO:wyoming_faster_whisper.handler: Turn off the study light.
INFO:wyoming_faster_whisper.handler: Turn on study light.
INFO:wyoming_faster_whisper.handler: Turn off study light.
INFO:wyoming_faster_whisper.handler: Turn off the steady light.
INFO:wyoming_faster_whisper.handler: Turn the study light off.
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-113' coro=<AsyncEventHandler.run() done, defined at /usr/local/lib/python3.9/dist-packages/wyoming/server.py:28> exception=ConnectionResetError('Connection lost')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/wyoming/server.py", line 35, in run
    if not (await self.handle_event(event)):
  File "/usr/local/lib/python3.9/dist-packages/wyoming_faster_whisper/handler.py", line 45, in handle_event
    await self.write_event(self.wyoming_info_event)
  File "/usr/local/lib/python3.9/dist-packages/wyoming/server.py", line 26, in write_event
    await async_write_event(event, self.writer)
  File "/usr/local/lib/python3.9/dist-packages/wyoming/event.py", line 114, in async_write_event
    await writer.drain()
  File "/usr/lib/python3.9/asyncio/streams.py", line 387, in drain
    await self._protocol._drain_helper()
  File "/usr/lib/python3.9/asyncio/streams.py", line 190, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost
INFO:wyoming_faster_whisper.handler: Turn the static light on.
INFO:wyoming_faster_whisper.handler: Turn the studied light off.
```

2. With Whisper set to "medium-int8" model the accuracy is better (see log below) - but is the Medium (or a larger) model available or worthwhile ? 
hassio/addon/core_whisper/documentation documentation lists a `medium (3.1 GB)` option, but it is not in the list of available options.  I appreciate your focus on the RasPi 4 platform, where 3.1 GB may not be feasible - but I can allocate additional cores and RAM to my HA VM, or even run Whisper as a separate VM. 

4. VAD seems to be taking 15 seconds ... is there an option to reduce this ?

5. The `ERROR:asyncio:Task exception was never retrieved ... ConnectionResetError: Connection lost` appears multiple times (apparently at random) in the log - however it doesn't seem to affect operation. 

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Whisper

### What is the version of the add-on?

1.0.0

### Steps to reproduce the issue

1. Installed HA Voice Assist (Wyoming, Piper, Whisper, openWakeWord) on HAOS
2. Installed [homeassistant-satellite](https://github.com/synesthesiam/homeassistant-satellite) on a RasPi 3B with USB mic and headphones.  Tested sound quality using the "--debug-recording-dir <DIR>" option. 
3. run ...

## System Information

version | core-2023.10.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.5
os_name | Linux
os_version | 6.1.56
arch | x86_64
timezone | Australia/Sydney
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.33.0
Stage | running
Available Repositories | 1379
Downloaded Repositories | 13

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | November 3, 2023 at 11:00 AM
relayer_connected | true
relayer_region | ap-southeast-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
remote_server | ap-southeast-1-1.ui.nabu.casa
certificate_status | ready
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.0
-- | --
update_channel | stable
supervisor_version | supervisor-2023.10.0
agent_version | 1.6.0
docker_version | 24.0.6
disk_total | 30.8 GB
disk_used | 15.3 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.6.0), Samba share (10.0.2), Terminal & SSH (9.7.1), Mosquitto broker (6.3.1), Node-RED (14.6.2), Rhasspy Assistant (2.5.11), ESPHome (2023.9.3), openWakeWord (1.7.1), Whisper (1.0.0), Piper (1.4.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 8
views | 7
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | October 10, 2023 at 8:32 AM
-- | --
current_recorder_run | October 18, 2023 at 3:46 PM
estimated_db_size | 495.00 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Anything in the Supervisor logs that might be useful for us?

```txt
23-10-18 15:53:44 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session 990a35011220704664813792e1657819d71c79ea2d5aea8ebeb4f4b7f0b81e89a0bb44c868119465655a5dfad46324fa9feb7e2af3532a7e2886cd77b3fc4547
23-10-18 15:53:45 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session 990a35011220704664813792e1657819d71c79ea2d5aea8ebeb4f4b7f0b81e89a0bb44c868119465655a5dfad46324fa9feb7e2af3532a7e2886cd77b3fc4547
23-10-18 15:53:46 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session 990a35011220704664813792e1657819d71c79ea2d5aea8ebeb4f4b7f0b81e89a0bb44c868119465655a5dfad46324fa9feb7e2af3532a7e2886cd77b3fc4547
23-10-18 15:53:47 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session 990a35011220704664813792e1657819d71c79ea2d5aea8ebeb4f4b7f0b81e89a0bb44c868119465655a5dfad46324fa9feb7e2af3532a7e2886cd77b3fc4547
23-10-18 15:53:48 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session 990a35011220704664813792e1657819d71c79ea2d5aea8ebeb4f4b7f0b81e89a0bb44c868119465655a5dfad46324fa9feb7e2af3532a7e2886cd77b3fc4547
23-10-18 15:53:49 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session 990a35011220704664813792e1657819d71c79ea2d5aea8ebeb4f4b7f0b81e89a0bb44c868119465655a5dfad46324fa9feb7e2af3532a7e2886cd77b3fc4547
23-10-18 15:53:50 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session 990a35011220704664813792e1657819d71c79ea2d5aea8ebeb4f4b7f0b81e89a0bb44c868119465655a5dfad46324fa9feb7e2af3532a7e2886cd77b3fc4547
23-10-18 15:53:51 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session 990a35011220704664813792e1657819d71c79ea2d5aea8ebeb4f4b7f0b81e89a0bb44c868119465655a5dfad46324fa9feb7e2af3532a7e2886cd77b3fc4547
23-10-18 15:53:53 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session 990a35011220704664813792e1657819d71c79ea2d5aea8ebeb4f4b7f0b81e89a0bb44c868119465655a5dfad46324fa9feb7e2af3532a7e2886cd77b3fc4547
23-10-18 15:53:54 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session 990a35011220704664813792e1657819d71c79ea2d5aea8ebeb4f4b7f0b81e89a0bb44c868119465655a5dfad46324fa9feb7e2af3532a7e2886cd77b3fc4547
23-10-18 15:53:56 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session 990a35011220704664813792e1657819d71c79ea2d5aea8ebeb4f4b7f0b81e89a0bb44c868119465655a5dfad46324fa9feb7e2af3532a7e2886cd77b3fc4547
23-10-18 15:53:57 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session 990a35011220704664813792e1657819d71c79ea2d5aea8ebeb4f4b7f0b81e89a0bb44c868119465655a5dfad46324fa9feb7e2af3532a7e2886cd77b3fc4547
23-10-18 15:53:58 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session 990a35011220704664813792e1657819d71c79ea2d5aea8ebeb4f4b7f0b81e89a0bb44c868119465655a5dfad46324fa9feb7e2af3532a7e2886cd77b3fc4547
23-10-18 15:53:59 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session 990a35011220704664813792e1657819d71c79ea2d5aea8ebeb4f4b7f0b81e89a0bb44c868119465655a5dfad46324fa9feb7e2af3532a7e2886cd77b3fc4547
23-10-18 15:54:00 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session 990a35011220704664813792e1657819d71c79ea2d5aea8ebeb4f4b7f0b81e89a0bb44c868119465655a5dfad46324fa9feb7e2af3532a7e2886cd77b3fc4547
23-10-18 15:54:01 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session 990a35011220704664813792e1657819d71c79ea2d5aea8ebeb4f4b7f0b81e89a0bb44c868119465655a5dfad46324fa9feb7e2af3532a7e2886cd77b3fc4547
23-10-18 15:54:02 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session 990a35011220704664813792e1657819d71c79ea2d5aea8ebeb4f4b7f0b81e89a0bb44c868119465655a5dfad46324fa9feb7e2af3532a7e2886cd77b3fc4547
23-10-18 15:54:03 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session 990a35011220704664813792e1657819d71c79ea2d5aea8ebeb4f4b7f0b81e89a0bb44c868119465655a5dfad46324fa9feb7e2af3532a7e2886cd77b3fc4547
```

### Anything in the add-on logs that might be useful for us?

```txt
s6-rc: info: service whisper: starting
s6-rc: info: service whisper successfully started
s6-rc: info: service discovery: starting
WARNING:wyoming_faster_whisper.download:Model hashes do not match
WARNING:wyoming_faster_whisper.download:Expected: {'config.json': 'e5a2f85afc17f73960204cad2b002633', 'model.bin': '99b6aca05c475cbdcc182db2b2aed363', 'vocabulary.txt': 'c1120a13c94a8cbb132489655cdd1854'}
WARNING:wyoming_faster_whisper.download:Got: {'model.bin': '', 'config.json': '', 'vocabulary.txt': ''}
INFO:__main__:Downloading FasterWhisperModel.MEDIUM_INT8 to /data
INFO:__main__:Ready
[13:59:13] INFO: Successfully send discovery information to Home Assistant.
s6-rc: info: service discovery successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
INFO:wyoming_faster_whisper.handler: Turn on the study light.
INFO:wyoming_faster_whisper.handler: Turn off the study light.
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-287' coro=<AsyncEventHandler.run() done, defined at /usr/local/lib/python3.9/dist-packages/wyoming/server.py:28> exception=ConnectionResetError('Connection lost')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/wyoming/server.py", line 35, in run
    if not (await self.handle_event(event)):
  File "/usr/local/lib/python3.9/dist-packages/wyoming_faster_whisper/handler.py", line 45, in handle_event
    await self.write_event(self.wyoming_info_event)
  File "/usr/local/lib/python3.9/dist-packages/wyoming/server.py", line 26, in write_event
    await async_write_event(event, self.writer)
  File "/usr/local/lib/python3.9/dist-packages/wyoming/event.py", line 114, in async_write_event
    await writer.drain()
  File "/usr/lib/python3.9/asyncio/streams.py", line 387, in drain
    await self._protocol._drain_helper()
  File "/usr/lib/python3.9/asyncio/streams.py", line 190, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost
INFO:wyoming_faster_whisper.handler: Turn on study light.
INFO:wyoming_faster_whisper.handler: Turn off study light
INFO:wyoming_faster_whisper.handler: Turn living room lamp full.
INFO:wyoming_faster_whisper.handler: 10, living room light.
```

**Comment by jclsn** [comment]
Same here on tiny-int8 model. On all models basically. Since I tried the medium model once, this occurs every time. I tried reinstalling the addon completely, but no luck so far.

**Comment by HighWingy** [comment]
Just found this as I am getting a 404 error when trying to download the medium model as well. Though I'm running mine in a docker-compose container. 
Below is the error messages in my log:
```
WARNING:wyoming_faster_whisper.download:Model hashes do not match
WARNING:wyoming_faster_whisper.download:Expected: {'config.json': 'e5a2f85afc17f73960204cad2b002633', 'model.bin': '5f852c3335fbd24002ffbb965174e3d7', 'vocabulary.txt': 'c1120a13c94a8cbb132489655cdd1854'}
WARNING:wyoming_faster_whisper.download:Got: {'model.bin': '', 'config.json': '', 'vocabulary.txt': ''}
INFO:__main__:Downloading FasterWhisperModel.MEDIUM to /data
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/dist-packages/wyoming_faster_whisper/__main__.py", line 136, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/dist-packages/wyoming_faster_whisper/__main__.py", line 78, in main
    model_dir = download_model(model, args.download_dir)
  File "/usr/local/lib/python3.9/dist-packages/wyoming_faster_whisper/download.py", line 90, in download_model
    with urlopen(model_url) as response:
  File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by scaarup** [comment]
> Just found this as I am getting a 404 error when trying to download the medium model as well. Though I'm running mine in a docker-compose container. Below is the error messages in my log:
> 
> ```
> WARNING:wyoming_faster_whisper.download:Model hashes do not match
> WARNING:wyoming_faster_whisper.download:Expected: {'config.json': 'e5a2f85afc17f73960204cad2b002633', 'model.bin': '5f852c3335fbd24002ffbb965174e3d7', 'vocabulary.txt': 'c1120a13c94a8cbb132489655cdd1854'}
> WARNING:wyoming_faster_whisper.download:Got: {'model.bin': '', 'config.json': '', 'vocabulary.txt': ''}
> INFO:__main__:Downloading FasterWhisperModel.MEDIUM to /data
> Traceback (most recent call last):
>   File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/usr/local/lib/python3.9/dist-packages/wyoming_faster_whisper/__main__.py", line 136, in <module>
>     asyncio.run(main())
>   File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
>     return future.result()
>   File "/usr/local/lib/python3.9/dist-packages/wyoming_faster_whisper/__main__.py", line 78, in main
>     model_dir = download_model(model, args.download_dir)
>   File "/usr/local/lib/python3.9/dist-packages/wyoming_faster_whisper/download.py", line 90, in download_model
>     with urlopen(model_url) as response:
>   File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
>     return opener.open(url, data, timeout)
>   File "/usr/lib/python3.9/urllib/request.py", line 523, in open
>     response = meth(req, response)
>   File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
>     response = self.parent.error(
>   File "/usr/lib/python3.9/urllib/request.py", line 561, in error
>     return self._call_chain(*args)
>   File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
>     result = func(*args)
>   File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
>     raise HTTPError(req.full_url, code, msg, hdrs, fp)
> urllib.error.HTTPError: HTTP Error 404: Not Found
> ```

but why would you post that here? looks like a complete different issue.

**Comment by HighWingy** [comment]
> 
> but why would you post that here? looks like a complete different issue.

Admittedly there are multiple different things that OP asked/posted that are only loosely connected. And I'm responding to one of them

#2 on original post above says 
>".. but is the Medium (or a larger) model available or worthwhile ? hassio/addon/core_whisper/documentation documentation lists a medium (3.1 GB) option, but it is not in the list of available options..."

And my post is saying while medium appears to be a valid option, it does not appear to actually exist as I'm getting a 404 error when trying to download it.

**Comment by scaarup** [comment]
> > 
> 
> > but why would you post that here? looks like a complete different issue.
> 
> 
> 
> Admittedly there are multiple different things that OP asked/posted that are only loosely connected. And I'm responding to one of them
> 
> 
> 
> Number 2 on the original post above says:
> 
> >".. but is the Medium (or a larger) model available or worthwhile ? hassio/addon/core_whisper/documentation documentation lists a medium (3.1 GB) option, but it is not in the list of available options..."
> 
> 
> 
> And my post is saying while medium appears to be a valid option, it does not appear to actually exist as I'm getting a 404 error when trying to download it.
> 
> 
> 
> 
> 
> 

Okay but are you getting the error which is in the title of this issue?

**Comment by HighWingy** [comment]
> 
> Okay but are you getting the error which is in the title of this issue?

Potentially yes. 

If the error the OP is getting is from trying to use the Medium model, and I am getting an error saying that the Medium model does not appear exist, which answers a question OP asked. Then it seems reasonable to conclude that the source of OP's error could be the issue I found of not being able to download the Medium model.

To be more specific, I am proposing that OP is seeing that error message with the Medium model because it does not exist. And rather than report a 404 error, they got that message instead. 

Looking at my logs it's clear not everything gets logged there. OP can chime in here to confirm, but my theory here is that OP started the system with a different model loaded and confirmed it was working with some tests. They then tried to switch to the Medium model, and the system failed poorly because it could not download it. They then switched back to something other than Medium, and saw that things were working again. Concluding that there is something wrong with the Medium model. Which I now find is that the medium model is not downloadable at this time for some as yet to be found reason.

**Comment by donburch888** [comment]
> OP can chime in here to confirm, but my theory here is that OP started the system with a different model loaded and confirmed it was working with some tests. They then tried to switch to the Medium model, and the system failed poorly because it could not download it. 

Sorry guys, but that wasn't the case. I have sucessfully used the "tint-int8", "medium-int8" and "small" models; and since I am running HA on a machine with significantly more horesepower than a RasPi, I was hoping that running a larger model would improve accuracy of detected speech.  
However I do not feel competent to try compiling code myself - and so I was stuck at "Medium" model not appearing in the add-on's dropdown list. 

Ahh, I see that the documentation has been modified.  Pity, as Whisper just isn't up to WAF :-(

**Comment by ChR-iSz** [comment]
Any news? Same issue here on HP Server and M5 Atom echo...
