### ISSUE TITLE
openWakeWord: RPi3 support

### ISSUE THREAD

**Issue by 2m** [home-assistant/addons#3266]
### Describe the issue you are experiencing

Currently it is not possible to install `openwakeword` addon on RPi3. `armv7` is missing here:
https://github.com/home-assistant/addons/blob/master/openwakeword/config.yaml#L8-L9

However `openWakeWord` itself mentions that it is fast enough to run on RPi 3. https://github.com/dscripka/openwakeword#project-goals

Would it be possible to add RPi3 support for `openwakeword` addon?

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Almond

### What is the version of the add-on?

1.7.1

### Steps to reproduce the issue

1. Open `openWakeWord` addon in the Add-On store.
2. It shows that it is incompatible with the current hardware:

<img width="686" alt="image" src="https://github.com/home-assistant/addons/assets/422086/60eb3b3f-82a3-43ee-9487-74cae820d39b">

## System Information

version | core-2023.10.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.5
os_name | Linux
os_version | 6.1.21-v7
arch | armv7l
timezone | Europe/Vilnius
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.32.1
Stage | running
Available Repositories | 1311
Downloaded Repositories | 3

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | November 4, 2023 at 2:00 AM
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
remote_server | eu-central-1-12.ui.nabu.casa
certificate_status | ready
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.0
-- | --
update_channel | stable
supervisor_version | supervisor-2023.10.0
agent_version | 1.6.0
docker_version | 24.0.6
disk_total | 28.5 GB
disk_used | 9.2 GB
healthy | true
supported | true
board | rpi3
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.6.0), Advanced SSH & Web Terminal (15.1.0), Home Assistant Google Drive Backup (0.111.1), Let's Encrypt (4.12.9), Tailscale (0.12.0), ESPHome (2023.10.0), Grafana (9.1.0), Mosquitto broker (6.3.1), Victoria Metrics (1.8.21)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
views | 2
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | October 9, 2023 at 9:43 AM
-- | --
current_recorder_run | October 13, 2023 at 7:07 PM
estimated_db_size | 99.29 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

<details><summary>Xiaomi Miot Auto</summary>

component_version | 0.7.12
-- | --
can_reach_server | ok
can_reach_spec | ok
logged_accounts | 1
total_devices | 1

</details>

**Comment by synesthesiam** [comment]
Please try updating to version 1.8.0, which adds `armv7` support

**Comment by 2m** [comment]
I am getting the following error when trying to install: 

![Screenshot_20231025-093359.png](https://github.com/home-assistant/addons/assets/422086/ae77179f-4c6b-427a-a432-0972d9ad5e06)

**Comment by rp3tya** [comment]
I have 1.8.0 installed, cannot update to 1.8.1:
`
Error updating openWakeWord: Can't install homeassistant/armv7-addon-openwakeword:1.8.1: 404 Client Error for http+docker://localhost/v1.43/images/create?tag=1.8.1&fromImage=homeassistant%2Farmv7-addon-openwakeword&platform=linux%2Farm64: Not Found ("pull access denied for homeassistant/armv7-addon-openwakeword, repository does not exist or may require 'docker login': denied: requested access to the resource is denied")
`

**Comment by 2m** [comment]
Yea, it looks like there is no repository for the `armv7` https://registry.hub.docker.com/r/homeassistant/armv7-addon-openwakeword as opposed to the `aarch64` repo: https://registry.hub.docker.com/r/homeassistant/aarch64-addon-openwakeword

**Comment by synesthesiam** [comment]
I had the architecture in `config.yaml` but forgot to add it to `build.yaml`

**Comment by synesthesiam** [comment]
Please update to 1.8.2
