### ISSUE TITLE
Whisper exit code 4

### ISSUE THREAD

**Issue by kierenblack** [home-assistant/addons#3276]
### Describe the issue you are experiencing

I am trying to strart the Whisper addon but all i get in the logs is the following

`s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service whisper: starting
s6-rc: info: service whisper successfully started
s6-rc: info: service discovery: starting
[00:40:25] INFO: Service exited with code 256 (by signal 4)
[00:40:28] INFO: Service exited with code 256 (by signal 4)
[00:40:31] INFO: Service exited with code 256 (by signal 4)
[00:40:34] INFO: Service exited with code 256 (by signal 4)
[00:40:36] INFO: Service exited with code 256 (by signal 4)
[00:40:39] INFO: Service exited with code 256 (by signal 4)
[00:40:42] INFO: Service exited with code 256 (by signal 4)
[00:40:45] INFO: Service exited with code 256 (by signal 4)
[00:40:48] INFO: Service exited with code 256 (by signal 4)`

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Almond

### What is the version of the add-on?

1.0.0

### Steps to reproduce the issue

1.Start the addon
2.check the logs and the error is there
...

## System Information

version | core-2023.10.3
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.5
os_name | Linux
os_version | 5.10.0-26-amd64
arch | x86_64
timezone | Pacific/Auckland
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4882
Installed Version | 1.33.0
Stage | running
Available Repositories | 1317
Downloaded Repositories | 8

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 11 (bullseye)
-- | --
update_channel | stable
supervisor_version | supervisor-2023.10.0
agent_version | 1.6.0
docker_version | 24.0.6
disk_total | 215.5 GB
disk_used | 92.7 GB
healthy | failed to load: Unhealthy
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | Home Assistant Google Drive Backup (0.111.1), File editor (5.6.0), TasmoAdmin (0.25.1), Node-RED (14.6.3), Spotify Connect (0.12.6), Advanced SSH & Web Terminal (15.1.0), Log Viewer (0.16.0), Studio Code Server (5.13.0), ESPHome (2022.3.1), MariaDB (2.6.1), Samba share (10.0.2), Duck DNS (1.15.0), NGINX Home Assistant SSL proxy (3.5.0), InfluxDB (4.8.0), Mosquitto broker (6.3.1), Piper (1.4.0), Whisper (1.0.0), openWakeWord (1.8.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 1
views | 5
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | September 26, 2023 at 9:27 AM
-- | --
current_recorder_run | October 23, 2023 at 12:12 AM
estimated_db_size | 3254.44 MiB
database_engine | mysql
database_version | 10.6.12

</details>

<details><summary>Sonoff</summary>

version | 3.5.2 (2ad1cd7)
-- | --
cloud_online | 4 / 6
local_online | 4 / 11

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Anything in the add-on logs that might be useful for us?

```txt
see above
```

**Comment by synesthesiam** [comment]
Please see: https://github.com/home-assistant/addons/issues/3035

**Comment by ptaudio** [comment]
i'm using V1.0.0. Still same issue. #3035 does contribute to a solution. Please advice.

**Comment by mosaisi** [comment]
I have the same problem. I am running HA on Proxmox on a machine with an AMD chip. From responses to issue #3035 the issue is that the Whisper was not compiled to work with older AMD CPUs. I am looking to migrate to Intel CPU.

**Comment by proasnet** [comment]
I have the same problem. I am running HA on Acer machine with an Intel CPU. The virtualization in UEFI bios I tried on or off. Without any effect.
