### ISSUE TITLE
openwakeword exception after some run time

### ISSUE THREAD

**Issue by signaleleven** [home-assistant/addons#3277]
### Describe the issue you are experiencing

The openwakeword addon fails after a short time (it works fine until then, for seconds to minutes of time, until it fails) with the exception pasted in the log below. 
The container stays healthy, but non-functional, so the only way to restore wake-word functionality is to restart manually the addon.

I'm on a Yellow, if it helps

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

openwakeword

### What is the version of the add-on?

1.8.0

### Steps to reproduce the issue

1. run the addon with the default configuration
2. wait for the exception to pop up

## System Information

version | core-2023.10.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.5
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4999
Installed Version | 1.33.0
Stage | running
Available Repositories | 1316
Downloaded Repositories | 13

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.0
-- | --
update_channel | stable
supervisor_version | supervisor-2023.10.0
agent_version | 1.6.0
docker_version | 24.0.6
disk_total | 229.2 GB
disk_used | 19.2 GB
healthy | true
supported | true
board | yellow
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.3.1), TasmoAdmin (0.24.1), File editor (5.6.0), Duck DNS (1.15.0), Let's Encrypt (4.12.9), NGINX Home Assistant SSL proxy (3.5.0), AppDaemon (0.13.6), Spotify Connect (0.12.6), Tailscale (0.12.0), Studio Code Server (5.5.7), Terminal & SSH (9.7.1), JupyterLab (0.12.1), MPD (1.7.2), InfluxDB (4.8.0), Piper (1.4.0), ESPHome (2023.10.1), Home Assistant Git Exporter (1.16.0), Whisper (1.0.0), openWakeWord (1.8.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 7
views | 11
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | October 12, 2023 at 11:10 AM
-- | --
current_recorder_run | October 20, 2023 at 4:46 PM
estimated_db_size | 509.12 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Anything in the add-on logs that might be useful for us?

```txt
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service openwakeword: starting
s6-rc: info: service openwakeword successfully started
s6-rc: info: service discovery: starting
INFO:root:Ready
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
[15:55:12] INFO: Successfully sent discovery information to Home Assistant.
s6-rc: info: service discovery successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
ERROR:root:Unexpected error in wake word thread
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/wyoming_openwakeword/openwakeword.py", line 301, in ww_proc
    ww_model.allocate_tensors()
  File "/usr/local/lib/python3.11/dist-packages/tflite_runtime/interpreter.py", line 531, in allocate_tensors
    return self._interpreter.AllocateTensors()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: /tensorflow/tensorflow/lite/kernels/reshape.cc:92 num_input_elements != num_output_elements (2 != 1)Node number 24 (RESHAPE) failed to prepare.
```

### Additional information

The openwakeword addon is not present in the list of addons of the issue bug report form, so I selected `Whisper`, and then edited the issue to manually write "openwakeword"

**Comment by signaleleven** [comment]
It's the issue discussed here: https://github.com/rhasspy/wyoming-openwakeword/issues/1

**Comment by synesthesiam** [comment]
For now, try switching wake words. I have a TODO item to fix this.
