### ISSUE TITLE
Unable to shutdown over SSH due to line ending issue

### ISSUE THREAD

**Issue by h4ckninja** [home-assistant/addons#3278]
### Describe the issue you are experiencing

Like #2767, attempting to shutdown over SSH fails to do the following error:

```
[core-ssh ~]$ /usr/local/bin/shutdown
: No such file or directory bashio
```

This is on OS 11.0 and Core 10.5.3 (the most recent as of this writing). I was able to fix the reboot script by converting the file from DOS to Mac and then from Mac to Linux line endings. But this seems to be a wider issue.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Terminal & SSH

### What is the version of the add-on?

most recent

### Steps to reproduce the issue

1. Log in to SSH
2. Attempt to call `shutdown -h now`
3. Observe the error `: No such file or directory bashio`.

### System Health information

Already shutdown my home assistant to perform layer 1 maintenance.

### Anything in the Supervisor logs that might be useful for us?

```txt
Already shutdown my home assistant to perform layer 1 maintenance.
```

**Comment by bmccann16** [comment]
This is still broken in Home Assistant 11.1 running on an RPI-4.

**Comment by sonovice** [comment]
Still broken on newest HA.
