### ISSUE TITLE
Z-Wave Controller no longer starting with 0.2.0

### ISSUE THREAD

**Issue by bakgwailo** [home-assistant/addons#3280]
### Describe the issue you are experiencing

I've found my Z-Wave controller (Aeotec ZW090) no longer comes up with Z-Wave JS 0.2.0, and none of my Z-Wave controls work. Downgrading to 0.1.98, however, solves my problems and everything works OK. With 0.2.0, all of my switches/etc appear on the home page, but, attempted to toggle them results in nothing happening - and a fresh of of the page puts them back in their previous state.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Z-Wave JS

### What is the version of the add-on?

0.2.0

### Steps to reproduce the issue

1. Update to 0.2.0
2. See that Z-Wave switches/integrations no longer function

### System Health information

Version | core-2023.10.5
Installation Type | Home Assistant OS
Host Operating System | Home Assistant OS 11.0

Z-Wave JS Addon: 0.2.0 (0.1.98 works)

### Anything in the add-on logs that might be useful for us?

```txt
2023-10-24T00:31:52.176Z CNTRLR « [Node 020] ping successful
New client
New client
Client disconnected
Code 1000:
2023-10-24T00:32:26.687Z CNTRLR The controller is unresponsive
2023-10-24T00:32:26.692Z DRIVER Controller missed Send Data callback. Attempting to recover...
2023-10-24T00:32:26.712Z CNTRLR Performing soft reset...
2023-10-24T00:32:27.741Z CNTRLR Failed to execute controller command after 1/3 attempts. Scheduling next try i
n 100 ms.
2023-10-24T00:32:28.850Z CNTRLR Failed to execute controller command after 2/3 attempts. Scheduling next try i
n 1100 ms.
2023-10-24T00:32:30.964Z CNTRLR Soft reset failed: Timeout while waiting for an ACK from the controller (ZW020
0)
2023-10-24T00:32:30.965Z CNTRLR [Node 016] ping failed: Timeout while waiting for a callback from the controll
er (ZW0200)
Starting logging event forwarder at info level
Stopping logging event forwarder
Starting logging event forwarder at debug level
Stopping logging event forwarder
```

**Comment by jozg** [comment]
Hello,

The same here, 0.1.98 works and with the 0.2 version it stops reacting, so rollbacked for now,
Glad that i'm not the only one.

Regards

**Comment by jozg** [comment]
Ok, also with 0.2.1 the same problem for me, here is the log:

**Comment by hhamer78** [comment]
I have a comparable issue; with the upgrade to 0.2.0. Once or twice a day buttons (on user interface, app, webpage) don't react for ZWave devices. The devices are still alive; no complaints from HA. It also seems data is coming in fine (for example power metering). 

I investigated and can't find anything in the log files when this happends. I can't find any "button pushed" or whatever trigger. If I would find that and it would give some time-out I would understand it in a way .... but I even don't see anything triggering. Restarting the Zwave-JS add-on solves the issue.

**Comment by SergeyAnokhin** [comment]
Hello,

Same for me with EVERSPRING  Z-Wave (Z-Wave+). Rollbacked to 1.98
sensor.00_zwave_usb_stick_status -> 'unresponsive'

Thanks

**Comment by a-pir1** [comment]
I just recently had a similar issue.  Is your containers watchdog on?  I had to turn it off in mine and now it is working perfectly fine.

**Comment by edddeduck** [comment]
Similar issue seen on my setup - "UZB by Z-Wave.Me" I have Firmware: 5.2

```
2023-11-03T00:26:16.135Z CNTRLR   The controller is unresponsive
2023-11-03T00:26:16.136Z DRIVER   Controller missed Send Data callback. Attempting to recover...
2023-11-03T00:26:16.197Z CNTRLR   The controller does not support soft reset or the soft reset feature has been disabled with a config option or the ZWAVEJS_DISABLE_SOFT_RESET environment variable.
```

After that the plugin will shutdown more logs available if needed.

**Comment by jozg** [comment]
Ok, i updated my gen5 stick to the 1.02 firmware, and the problem is solved. I first make a backup with the backup tool, so i haven't had to pair again the devices. more info https://github.com/zwave-js/node-zwave-js/issues/6341
Update can be download at https://aeotec.freshdesk.com/support/solutions/articles/6000252294-z-stick-gen5-v1-02-firmware-update
And the backup tool https://aeotec.freshdesk.com/support/solutions/articles/6000108806-z-stick-gen5-backup-software

Regards,
