### ISSUE TITLE
Upgrade to 2023.10.5 causes zwave to fail

### ISSUE THREAD

**Issue by Villa-Buenavista** [home-assistant/addons#3288]
### Describe the issue you are experiencing

Please have a look at this issue raised with HA core. ZWave JS stopped working with HA Core 10.5. I downgraded to 10.3 and it works fine with JS 0.2.1.

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Z-Wave JS

### What is the version of the add-on?

Current version: 0.2.1 

### Steps to reproduce the issue

Any update of the Core System above 10.3 causes ZWave JS to fail. 

### System Health information

No repairs available: "Derzeit sind keine Reparaturen verfügbar"

I am running HA Blue hardware

 Home Assistant 2023.10.3 
Supervisor 2023.10.1 
Operating System 11.1 
Frontend 20231005.0 - latest 

### Anything in the Supervisor logs that might be useful for us?

```txt
I have downgraded to HA 10.3 for my network to work. Unfortunately I do not have logs...
```

### Additional information

This issue was also reported by someone else in the HA core thread.

https://github.com/home-assistant/core/issues/102619

**Comment by MartinHjelmare** [comment]
No need to open duplicate issues.
