### ISSUE TITLE
Cannot update or install Terminal & SSH addon

### ISSUE THREAD

**Issue by pstimpel** [home-assistant/addons#3308]
### Describe the issue you are experiencing

The plugin was installed for ages. Today I was asked to update it. Failed with

Error updating Terminal & SSH: Can't install homeassistant/amd64-addon-ssh:9.8.0: 500 Server Error for http+docker://localhost/v1.43/images/create?tag=9.8.0&fromImage=homeassistant%2Famd64-addon-ssh&platform=linux%2Famd64: Internal Server Error ("Get "https://registry-1.docker.io/v2/homeassistant/amd64-addon-ssh/manifests

So I uninstalled and installed it, failed as well

Failed to to call /addons/core_ssh/install - Can't install homeassistant/amd64-addon-ssh:9.8.0: 500 Server Error for http+docker://localhost/v1.43/images/create?tag=9.8.0&fromImage=homeassistant%2Famd64-addon-ssh&platform=linux%2Famd64: Internal Server Error ("Get "https://registry-1.docker.io/v2/": EOF")

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Terminal & SSH

### What is the version of the add-on?

was 9.7.1, tried tp update / install 9.8.0

### Steps to reproduce the issue

1. Just try to install or update

## System Information

version | core-2023.11.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.59
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.1
-- | --
update_channel | stable
supervisor_version | supervisor-2023.11.0
agent_version | 1.6.0
docker_version | 24.0.6
disk_total | 30.8 GB
disk_used | 15.1 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Node-RED (15.1.1), File editor (5.6.0), InfluxDB (4.8.0), SQLite Web (3.10.0), TasmoAdmin (0.26.0), Nextcloud Backup (0.17.7), ESPHome (2023.10.6)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
views | 17
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 3. November 2023 um 17:07
-- | --
current_recorder_run | 10. November 2023 um 16:45
estimated_db_size | 482.99 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Anything in the Supervisor logs that might be useful for us?

```txt
23-11-11 16:46:33 ERROR (MainThread) [supervisor.docker.interface] Can't install homeassistant/amd64-addon-ssh:9.8.0: 500 Server Error for http+docker://localhost/v1.43/images/create?tag=9.8.0&fromImage=homeassistant%2Famd64-addon-ssh&platform=linux%2Famd64: Internal Server Error ("Get "https://registry-1.docker.io/v2/homeassistant/amd64-addon-ssh/manifests/sha256:e49bac4a7b3c9631ef79655b8013908bbdd1fd03b9b0b127f15479132297312c": EOF")
```

**Comment by zimmra** [comment]
I am getting the error with matter-server

`Failed to install the Matter Server add-on: Can't install homeassistant/amd64-addon-matter-server:4.10.2: 500 Server Error for http+docker://localhost/v1.43/images/create?tag=4.10.2&fromImage=homeassistant%2Famd64-addon-matter-server&platform=linux%2Famd64: Internal Server Error ("Get "https://registry-1.docker.io/v2/": EOF")`

**Comment by zimmra** [comment]
It may be docker rate limiting

I went in to terminal within Home Assistant OS, and ran `docker login` and then logged in with my docker hub username/password. Then I was able to pull images without problem

**Comment by prohidium** [comment]
I cannot update zwave-js to 3.0 with similar error:

Can't install homeassistant/amd64-addon-zwave_js:0.3.0: 500 Server Error for http+docker://localhost/v1.43/images/create?tag=0.3.0&fromImage=homeassistant%2Famd64-addon-zwave_js&platform=linux%2Famd64: Internal Server Error ("Get "https://registry-1.docker.io/v2/homeassistant/amd64-addon-zwave_js/manifests/sha256:57a65d03b855e73a8cc2543b957e972adf6075fbcd16163dd2c9132f84ba32f2": EOF") 

Same happened with Terminal & SSH add-on but I was using the Advanced version so I uninstalled the standard version to get past the issue. 

I had just installed 2023.11.2 and two other plug in updates but the above 2 failed with similar errors. All else is running fine.

Core
2023.11.2
Supervisor
2023.11.0
Operating System
11.1
Frontend
20231030.2

**Comment by prohidium** [comment]
Could this be a 2023.11.2 new issue? I could roll back but I really don't want to do that if I can avoid it.

**Comment by TekFan** [comment]
I'm still on core 2023.10.3 and have the same error, so not related to latest 2023.11.2.
I wonder if it coud have something to do with the recent supervisor update.

**Comment by prohidium** [comment]
That info will certainly help. 

Based on the error message, my next guess is that it almost looks like HA is having an issue obtaining the update via "get". I think it is actually 2 errors. One error is the fail to download error and the other error is the fact that the downloaded file it expects to be there is not there so the update fails completely.

**Comment by pstimpel** [comment]
This is the log entry for the failed update

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:230
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 16:46:33 (3 occurrences)
Last logged: 16:49:40

    [139940593452480] Error updating Terminal & SSH: Can't install homeassistant/amd64-addon-ssh:9.8.0: 500 Server Error for http+docker://localhost/v1.43/images/create?tag=9.8.0&fromImage=homeassistant%2Famd64-addon-ssh&platform=linux%2Famd64: Internal Server Error ("Get "https://registry-1.docker.io/v2/homeassistant/amd64-addon-ssh/manifests/sha256:e49bac4a7b3c9631ef79655b8013908bbdd1fd03b9b0b127f15479132297312c": EOF")
    [139940593452480] Error updating Terminal & SSH: Can't install homeassistant/amd64-addon-ssh:9.8.0: 500 Server Error for http+docker://localhost/v1.43/images/create?tag=9.8.0&fromImage=homeassistant%2Famd64-addon-ssh&platform=linux%2Famd64: Internal Server Error ("Get "https://registry-1.docker.io/v2/": EOF")

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 167, in async_install
    await async_update_addon(self.hass, slug=self._addon_slug, backup=backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 53, in _wrapper
    raise HassioAPIError(data["message"])
homeassistant.components.hassio.handler.HassioAPIError: Can't install homeassistant/amd64-addon-ssh:9.8.0: 500 Server Error for http+docker://localhost/v1.43/images/create?tag=9.8.0&fromImage=homeassistant%2Famd64-addon-ssh&platform=linux%2Famd64: Internal Server Error ("Get "https://registry-1.docker.io/v2/homeassistant/amd64-addon-ssh/manifests/sha256:e49bac4a7b3c9631ef79655b8013908bbdd1fd03b9b0b127f15479132297312c": EOF")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 230, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2035, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2072, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 876, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 157, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 432, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 169, in async_install
    raise HomeAssistantError(f"Error updating {self.title}: {err}") from err
homeassistant.exceptions.HomeAssistantError: Error updating Terminal & SSH: Can't install homeassistant/amd64-addon-ssh:9.8.0: 500 Server Error for http+docker://localhost/v1.43/images/create?tag=9.8.0&fromImage=homeassistant%2Famd64-addon-ssh&platform=linux%2Famd64: Internal Server Error ("Get "https://registry-1.docker.io/v2/homeassistant/amd64-addon-ssh/manifests/sha256:e49bac4a7b3c9631ef79655b8013908bbdd1fd03b9b0b127f15479132297312c": EOF")

**Comment by pstimpel** [comment]
This is the log entry for the failed installation

Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:138
Integration: Home Assistant Supervisor ([documentation](https://www.home-assistant.io/integrations/hassio), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+hassio%22))
First occurred: 16:58:52 (1 occurrences)
Last logged: 16:58:52
Failed to to call /addons/core_ssh/install - Can't install homeassistant/amd64-addon-ssh:9.8.0: 500 Server Error for http+docker://localhost/v1.43/images/create?tag=9.8.0&fromImage=homeassistant%2Famd64-addon-ssh&platform=linux%2Famd64: Internal Server Error ("Get "https://registry-1.docker.io/v2/": EOF")

**Comment by TekFan** [comment]
Apparently, there was an issue on the registry server because it works now.
I just could update the 3 same previously failing addons without a hitch.

**Comment by pstimpel** [comment]
Yep, can confirm that. Installation went as expected

**Comment by The00Dustin** [comment]
FWIW, I had this issue after upgrading the supervisor to 2023.11.3 and it persisted until I rebooted my yellow.  A previous restart did not resolve the issue for me.

**Comment by BitionSong** [comment]
> 显然，注册表服务器出现了问题，因为它现在可以正常工作了。 我可以毫无障碍地更新之前失败的 3 个相同的插件。

请求协助解决，可以吗？谢谢

**Comment by mywalcoin-gif** [comment]
Same problem :(

`Регистратор: homeassistant.components.hassio
Источник: components/hassio/websocket_api.py:148
интеграция: Home Assistant Supervisor ([документация](https://www.home-assistant.io/integrations/hassio), [проблемы](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+hassio%22))
Зафиксировано первый раз: 15:32:23 (1 случай)
Зафиксировано последний раз: 15:32:23

Failed to to call /addons/core_ssh/options/validate -`

Is there any workaround?
