### ISSUE TITLE
v.11.0.0. SAMBA Add-on exposes unaccessible 'homeassistant' folder instead of 'config' folder

### ISSUE THREAD

**Issue by gribouk** [home-assistant/addons#3309]
### Describe the issue you are experiencing

Since v.11.0.0. SAMBA add on does not provide access to the config folder and exposes 'homeassistant' folder which is not possible to get access to. Reverting to 10.0.2 restores normal operation.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Almond

### What is the version of the add-on?

11.0.0.

### Steps to reproduce the issue

1. Install SAMBA add-on v 11.0.0.
2. Try to access 'homeassistant' folder
3. Recieve denial
...

## System Information

version | core-2023.11.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.39
arch | x86_64
timezone | Europe/
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4996
Installed Version | 1.33.0
Stage | running
Available Repositories | 1336
Downloaded Repositories | 83

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.4
-- | --
update_channel | beta
supervisor_version | supervisor-2023.11.2
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 457.7 GB
disk_used | 31.1 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (10.0.2), Check Home Assistant configuration (3.11.0), FTP (4.7.3), MQTT Server & Web client (1.2.0), Mosquitto broker (6.3.1), Terminal & SSH (9.7.1), DHCP server (1.3.0), Advanced SSH & Web Terminal (16.0.1), Portainer (1.5.1), Rhasspy Assistant (2.5.11), File editor (5.6.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 81
views | 15
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | November 1, 2023 at 11:10 AM
-- | --
current_recorder_run | November 11, 2023 at 6:55 PM
estimated_db_size | 1603.93 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

<details><summary>Sonoff</summary>

version | 3.5.3 (a8c6d45)
-- | --
cloud_online | 33 / 33
local_online | 29 / 29

</details>

**Comment by jocamane** [comment]
me too

**Comment by jocamane** [comment]
in my case I don't have anymore the config folder but i have the homeassistant folder. If i try open homeassistant folder it's ok, but i don't see config folder

**Comment by gribouk** [comment]
> in my case I don't have anymore the config folder but i have the homeassistant folder. If i try open homeassistant folder it's ok, but i don't see config folder

The idea is that instead of the 'config' folder you should have 'homeassistant' folder now. If it opens, you should be accessing same space as before. The problem is that it denies me opening it...

**Comment by twanjaarsveld** [comment]
i have the same problem, i can acces the config folder using the terminal so i know its still there but the Samba shows only shows
 `Processing section "[homeassistant]"
Processing section "[addons]"
Processing section "[addon_configs]"
Processing section "[ssl]"
Processing section "[share]"
Processing section "[backup]"
Processing section "[media]"`

i thought okay maybe its on the "[homeassistant]" folder but that simply wont open

**Comment by bschatzow** [comment]
Same issue, I tried to add 192.168.0.0/16 as allowed and it made no difference.  Can't open homeassistant folder.  Also do see why it was changed I had the different folders mapped in windows and now with the changes the maps will have to all be manually changed.

**Comment by Masteroshi430** [comment]
The 'config' folder is exposed as 'homeassistant' folder which breaks some non home assistant script trying to access the folder.

**Comment by bschatzow** [comment]
What HAOS are the people with working Samba 11 on? I am on HAOS 11.1 and it is broken for me.

**Comment by RienduPre** [comment]
Me too. I am on

Core 2023.11.2
Supervisor 2023.11.2
Operating System 11.1
Frontend 20231030.2
