### ISSUE TITLE
Latest update says: Use new location for accessing the Home Assistant configuration folder using /homeassistant ->but /config should stay???

### ISSUE THREAD

**Issue by canedje** [home-assistant/addons#3313]
### Describe the issue you are experiencing

The update information says: 
Use new location for accessing the Home Assistant configuration folder using /homeassistant.
But as I understand it should stay on /config?
Do I need to update now?

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Almond

### What is the version of the add-on?

now 5.6.0 update is 5.7.0

### Steps to reproduce the issue

1.
2.
3.
...
The update is showing up with above mentioned line in the update information

## System Information

version | core-2023.11.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.59
arch | x86_64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.33.0
Stage | running
Available Repositories | 1338
Downloaded Repositories | 41

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.1
-- | --
update_channel | stable
supervisor_version | supervisor-2023.11.3
agent_version | 1.6.0
docker_version | 24.0.6
disk_total | 48.5 GB
disk_used | 11.1 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.6.0), NGINX Home Assistant SSL proxy (3.5.0), Samba share (12.1.0), Terminal & SSH (9.8.1), Z-Wave JS (0.3.0), Samba Backup (5.2.0), Duck DNS (1.15.0), ESPHome (2023.11.0), Node-RED (16.0.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 28
views | 14
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 10 november 2023 om 14:49
-- | --
current_recorder_run | 11 november 2023 om 10:05
estimated_db_size | 1660.86 MiB
database_engine | mysql
database_version | 10.11.5

</details>

**Comment by frenck** [comment]
No, nothing to update, it is an internal change.

../Frenck
