### ISSUE TITLE
addon_configs folder not reachable

### ISSUE THREAD

**Issue by moustic999** [home-assistant/addons#3318]
### Describe the issue you are experiencing

Since the change to /homeassistant folder it is not possible anymore to access addon_configs folder and then edit config files for addons. This is espcially annoying for appdaemon.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Almond

### What is the version of the add-on?

5.7.0

### Steps to reproduce the issue

1.open file editor 
2. go  to parent folder of /homeassistant folder
you can't ....
...

## System Information

version | core-2023.11.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.59
arch | x86_64
timezone | Europe/Brussels
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4714
Installed Version | 1.33.0
Stage | running
Available Repositories | 1400
Downloaded Repositories | 13

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.1
-- | --
update_channel | stable
supervisor_version | supervisor-2023.11.3
agent_version | 1.6.0
docker_version | 24.0.6
disk_total | 30.8 GB
disk_used | 8.7 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.7.0), Terminal & SSH (9.8.1), Samba share (12.1.0), AppDaemon (0.15.2), Home Assistant Google Drive Backup (0.111.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 4
views | 8
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 6 novembre 2023 à 12:55
-- | --
current_recorder_run | 17 novembre 2023 à 16:49
estimated_db_size | 473.33 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

**Comment by randybb** [comment]
We need to do the same mapping as we have for the Studio Code Server, where we can change `config_path: /root` to get that access

**Comment by frenck** [comment]
The file editor can access other places, but you have to allow for that specifically.
By default, the file editor is locked in into the Home Assistant Core configuration folder.

See also the add-on documentation: <https://github.com/home-assistant/addons/blob/master/configurator/DOCS.md#option-enforce_basepath-required>
