### ISSUE TITLE
Error: '/root/firmware.gbl' does not appear to be a valid GBL image

### ISSUE THREAD

**Issue by gcracolici** [home-assistant/addons#3328]
### Describe the issue you are experiencing

I am trying to use the silicon labs flasher to flash the home assistant SkyConnect back to the latest EZSP firmware having previously enabled multiprotocol support. 

I am unable to use the web flashing tool as I do not have physical access to the system.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Silicon Labs Flasher

### What is the version of the add-on?

0.2.0

### Steps to reproduce the issue

1. Home assistant SkyConnect running multiprotocol firmware
2. Attempt Silicon labs addon uninstalled, OTBR and Thread integrations removed
3. Silicon Labs Flasher run with following settings:
Device:
/dev/serial/by-id/usb-Nabu_Casa_SkyConnect_v1.0_6aff09d25f43ed11899845ab2a61ed69-if00-port0
Bootloader Baudrate: 115200
Hardware flow control: On
Firmware URL : https://github.com/NabuCasa/silabs-firmware/blob/main/EmberZNet/NabuCasa_SkyConnect_EZSP_v7.1.1.0_ncp-uart-hw_115200.gbl
Verbose mode: On

...

## System Information

version | core-2023.11.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.59
arch | x86_64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4900
Installed Version | 1.33.0
Stage | running
Available Repositories | 1339
Downloaded Repositories | 14

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 13 January 2024 at 19:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
remote_server | eu-central-1-11.ui.nabu.casa
certificate_status | ready
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.1
-- | --
update_channel | stable
supervisor_version | supervisor-2023.11.3
agent_version | 1.6.0
docker_version | 24.0.6
disk_total | 234.0 GB
disk_used | 16.2 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.8.1), Node-RED (16.0.2), Mosquitto broker (6.4.0), Studio Code Server (5.14.2), room-assistant (2.20.0), Zigbee2MQTT (1.33.2-1), Home Assistant Google Drive Backup (0.111.1), Matter Server (4.10.2), eufy-security-ws (1.7.1), RTSP Simple Server Add-on (v0.17.6), Silicon Labs Flasher (0.2.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 3
views | 16
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 20 November 2023 at 12:26
-- | --
current_recorder_run | 23 November 2023 at 23:26
estimated_db_size | 871.79 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Anything in the Supervisor logs that might be useful for us?

```txt
Nothing relevant
```

### Anything in the add-on logs that might be useful for us?

```txt
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service banner: starting

-----------------------------------------------------------
 Add-on: Silicon Labs Flasher
 Silicon Labs firmware flasher add-on
-----------------------------------------------------------
 Add-on version: 0.2.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.1  (amd64 / generic-x86-64)
 Home Assistant Core: 2023.11.3
 Home Assistant Supervisor: 2023.11.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service banner successfully started
s6-rc: info: service universal-silabs-flasher: starting
[04:40:28] INFO: Starting universal-silabs-flasher with /dev/ttyUSB0 (bootloader baudrate 115200)
2023-11-24 04:40:28 core-silabs-flasher asyncio[149] DEBUG Using selector: EpollSelector
Error: '/root/firmware.gbl' does not appear to be a valid GBL image: ValidationError('Image is truncated: tag value is cut off')
[04:40:28] INFO: universal-silabs-flasher-up script exited with code 1
s6-rc: warning: unable to start service universal-silabs-flasher: command exited 1
s6-rc: info: service banner: stopping
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service banner successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by puddly** [comment]
The reason for your error is that you're providing a URL that does not point to a firmware image, but instead to the GitHub webpage previewing the file. The correct URL is `https://github.com/NabuCasa/silabs-firmware/raw/main/EmberZNet/beta/NabuCasa_SkyConnect_EZSP_v7.3.2.0_ncp-uart-hw_115200.gbl`.

Removing multiprotocol support is automated, it is much simpler to use the button from the hardware menu. It will migrate your Zigbee network as well: https://skyconnect.home-assistant.io/procedures/disable-multiprotocol/

**Comment by AJediIAm** [comment]
> The reason for your error is that you're providing a URL that does not point to a firmware image, but instead to the GitHub webpage previewing the file. The correct URL is `https://github.com/NabuCasa/silabs-firmware/raw/main/EmberZNet/beta/NabuCasa_SkyConnect_EZSP_v7.3.2.0_ncp-uart-hw_115200.gbl`.
> 
> Removing multiprotocol support is automated, it is much simpler to use the button from the hardware menu. It will migrate your Zigbee network as well: https://skyconnect.home-assistant.io/procedures/disable-multiprotocol/

This solved it for me. I'll make an attempt to update the documentation to clarify this.

**Comment by Stooovie** [comment]
Similar here, with proper URL. Slae.sh CC2652RB stick, with fw URL:

https://raw.githubusercontent.com/Koenkk/Z-Stack-firmware/Z-Stack_3.x.0_coordinator_20230507/coordinator/Z-Stack_3.x.0/bin/CC2652RB_coordinator_20230507.zip

```
[12:29:55] INFO: Starting universal-silabs-flasher with /dev/ttyUSB0 (bootloader baudrate 115200)
Error: '/root/firmware.gbl' does not appear to be a valid GBL image: ValidationError('Image is truncated: tag value is cut off')
```
