### ISSUE TITLE
Letsencrypt plugin network configuration for port not used in HTTP challenge

### ISSUE THREAD

**Issue by omgraae** [home-assistant/addons#3330]
### Describe the issue you are experiencing

Let's encrypt plugin cannot get certificate with custom challenge port.

### Configuration

I have configured the plugin to use tcp port 85 for challenges, as port 80 is used by another server on my home network.

### Result

Certificate is not issued, as http challenge fails  due to letsencrypt connecting to another server.

### Log

```log
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/file-structure.sh
cont-init: info: /etc/cont-init.d/file-structure.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun lets-encrypt (no readiness notification)
s6-rc: info: service legacy-services successfully started
[23:41:55] INFO: Selected http verification
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Requesting a certificate for hass.****************

Certbot failed to authenticate some domains (authenticator: standalone). The Certificate Authority reported these problems:
  Domain: hass.****************
  Type:   unauthorized
  Detail: xx.xx.xx.xx: Invalid response from http://hass.****************/.well-known/acme-challenge/gbxsxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxnb7h4iqs4: 404

Hint: The Certificate Authority failed to download the challenge files from the temporary standalone webserver started by Certbot on port 80. Ensure that the listed domains point to this machine and that it can accept inbound connections from the internet.

Some challenges have failed.
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Almond

### What is the version of the add-on?

4.12.9

### Steps to reproduce the issue

1. Configure Let's Encrypt plugin network port to something other than port 80
2. Configure Let's Encrypt plugin to do http challenges
3. Start plugin
...

### System Health information

There are currently no repairs available

### Anything in the Supervisor logs that might be useful for us?

```txt
Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:138
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 9:12:39 AM (1 occurrences)
Last logged: 9:12:39 AM

Failed to to call /addons/core_letsencrypt/stats - Container addon_core_letsencrypt is not running
```

### Anything in the add-on logs that might be useful for us?

```txt
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/file-structure.sh
cont-init: info: /etc/cont-init.d/file-structure.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun lets-encrypt (no readiness notification)
s6-rc: info: service legacy-services successfully started
[23:41:55] INFO: Selected http verification
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Requesting a certificate for hass.****************

Certbot failed to authenticate some domains (authenticator: standalone). The Certificate Authority reported these problems:
  Domain: hass.****************
  Type:   unauthorized
  Detail: xx.xx.xx.xx: Invalid response from http://hass.****************/.well-known/acme-challenge/gbxsxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxnb7h4iqs4: 404

Hint: The Certificate Authority failed to download the challenge files from the temporary standalone webserver started by Certbot on port 80. Ensure that the listed domains point to this machine and that it can accept inbound connections from the internet.

Some challenges have failed.
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by iranl** [comment]
A custom port can be used in production but you would have to set it up in conjunction with something like port forwarding or a HTTP proxy (optionally with the addition of domain and/or path based routing)

From https://letsencrypt.org/docs/challenge-types/:

> The HTTP-01 challenge can only be done on port 80. Allowing clients to specify arbitrary ports would make the challenge less secure, and so it is not allowed by the ACME standard.

Also see #2805 and https://community.letsencrypt.org/t/using-nat-and-changing-the-port/170176

**Comment by TheDiverM** [comment]
There has to be a way to fix this, since most home network has only 1 external IP and if you need a reverse proxy to get SSL to work it means you are going to need a lot of extra equipment, I have 5 Nas server the manage to get letsencrypt to work and none of them has port 80 available to them.

**Comment by iranl** [comment]
There isn't anything to fix. As stated the ACME standard disallows HTTP challenges on any port other than port 80. 
There is no way around this. 

The addon is only able to ask Let's encrypt to verify a HTTP challenge at a certain domain. Let's encrypt will try to verify this challenge at http://\<YOUR_DOMAIN>:80/.well-known/acme-challenge/\<TOKEN>/.

The addon can serve the challenge at a port other than 80, but it is up to the user to make sure http://<YOUR_DOMAIN>:80 is eventually routed to http://\<HASS INTERNAL IP>:\<CUSTOM ADDON PORT>. 
How this is achieved is beyond the scope or capability of the addon.

Personally I would just use a DNS challenge. You will be able to request (wildcard) certs without opening ports or having to setup any port forwarding/routing. The addon works with alot of (free) DNS providers through which you can accomplish this.
