### ISSUE TITLE
`Shift + insert` does not paste into `Terminal & SSH` add-on web-ui

### ISSUE THREAD

**Issue by bilogic** [home-assistant/addons#3333]
### Describe the issue you are experiencing

`Shift + insert` does not paste into Terminal add-on web-ui

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Terminal & SSH

### What is the version of the add-on?

9.8.1

### Steps to reproduce the issue

1. Copy text on my OS
2. Press shift + insert on the web UI, nothing happens

### System Health information

No repairs

### Anything in the Supervisor logs that might be useful for us?

```txt
Nothing related to terminal
```

### Anything in the add-on logs that might be useful for us?

```txt
Nothing related to terminal
```

**Comment by bilogic** [comment]
Windows 10 Chrome Version 119.0.6045.160 (Official Build) (64-bit)

**Comment by agners** [comment]
Did you make sure to focus the Web UI (as in, click with your left mouse button into the Web UI area?

**Comment by bilogic** [comment]
Yes I did. Are you using the Advanced Terminal or just Terminal?

**Comment by bilogic** [comment]
Which browser and OS are you using?

**Comment by bilogic** [comment]
Can't paste in MacOS Chrome also, no idea how to convert `Shift + Insert`
