### ISSUE TITLE
Conbee 3 not supported by DeCONZ addon

### ISSUE THREAD

**Issue by gorynychzmey** [home-assistant/addons#3334]
### Describe the issue you are experiencing

Seems to be Conbee 3 is not supported by addon. I suppose that adding of the environment variable DECONZ_BAUDRATE solves this problem. 

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Almond

### What is the version of the add-on?

6.22.0

### Steps to reproduce the issue

1. Install Conbee 3 as described in the documentation to addon and deCONZ.
2. Start the addon
3. Connect to Web-UI (Phoscon)
4. Go to "Settings->Gateway"
5. See the firmware is not recognised.

## System Information

version | core-2023.11.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.33.0
Stage | running
Available Repositories | 1341
Downloaded Repositories | 33

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.1
-- | --
update_channel | stable
supervisor_version | supervisor-2023.11.3
agent_version | 1.6.0
docker_version | 24.0.6
disk_total | 58.0 GB
disk_used | 12.4 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Studio Code Server (5.14.2), Mosquitto broker (6.4.0), ESPHome (2023.11.4), Advanced SSH & Web Terminal (16.0.1), AirCast (4.0.1), zabbix-agent2 (1.4), Frigate Proxy (1.3), deCONZ (6.22.0), Dnsmasq (1.6.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 22
views | 11
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 28 октября 2023 г. в 20:24
-- | --
current_recorder_run | 23 ноября 2023 г. в 02:04
estimated_db_size | 1113.23 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

**Comment by Sektor3** [comment]
With new Deconz-Addon-Version the Conbee 3 should be recognized again #3323
