### ISSUE TITLE
Ecowitt integration stop working in HA newer versions

### ISSUE THREAD

**Issue by machyaer** [home-assistant/addons#3337]
Hello,
I ran into a problem with this integration.

I found that with these settings:
![Ecowitt conf](https://github.com/home-assistant/core/assets/61188196/2f710c61-423e-409c-981b-0300d92b282a)

Every thing worked perfectly with an older version of HA (**i.e. 2023.6.1**):
![ecowitt old](https://github.com/home-assistant/addons/assets/61188196/2c6d070d-3211-4716-9f1f-50a369267277)

![Ecowitt HA old](https://github.com/home-assistant/core/assets/61188196/e906c8f8-4b73-4b1e-85d9-70b7b28bd191)

but not with the newer one (**i.e. 2023.11.3**):
![Ecowitt HA new](https://github.com/home-assistant/core/assets/61188196/b9f4bd61-3b61-41c7-b55b-3e0a64057728)

I also found that upgrading HA from release 2023.6.1 to 2023.11.3 the integration stopped working
![ecowitt HA upgrade](https://github.com/home-assistant/addons/assets/61188196/c719d746-ac1e-4ba4-8406-e38b7a026a44)
            
Can any of you who use it do a double check and/or can you tell me how to solve the problem?

Thank you

_Originally posted by @machyaer in https://github.com/home-assistant/core/issues/101669#issuecomment-1827631610_

**Comment by MakiSoftIT** [comment]
Same problem with last update of Home Assistant with ECOWITT.

**Comment by Coder84619** [comment]
Same problem.

**Comment by machyaer** [comment]
Strange behavior, I did the test on 2 different systems (rPi3 and rPi4) updated to the same version of HA and while on one everything worked correctly on the other there was no way to receive any data.

I therefore opted to install ecowitt2mqtt and solved the problem.

**Comment by Coder84619** [comment]
@machyaer Are you using HTTPS on HA? If so, check out this post: https://www.derekseaman.com/2023/12/home-assistant-ecowitt-weather-station-setup.html

**Comment by machyaer** [comment]
> @machyaer Are you using HTTPS on HA? If so, check out this post: https://www.derekseaman.com/2023/12/home-assistant-ecowitt-weather-station-setup.html

I have tried both https via the duckDNS (but without the https proxy addon) address and http via the internal network address, but on the rPi4 no results.

To make the system work correctly I used:
**[ecowitt2mqtt theaddon](https://github.com/bachya/home-assistant-addons/tree/main/ecowitt2mqtt)**

Now it's working great.

**Comment by Coder84619** [comment]
@machyaer If your HA instance is HTTPS, then you MUST use the HTTP Proxy method in my blog post, or as you found, the MQTT method. Ecowitt does NOT support HTTPS to custom servers. So using your DuckDNS address (which I assume is HTTPS) or HTTP to internal when using an SSL certificate on HA will NOT work. HA does NOT listen on HTTP if you have secured it with a SSL certificate.

**Comment by machyaer** [comment]
> @machyaer 
... or HTTP to internal when **using an SSL certificate on HA** will NOT work. HA does NOT listen on HTTP if you have secured it with a SSL certificate.

Got it!

This one it's the only difference between the rPi4 and rPi3 systems...
