### ISSUE TITLE
Preferred thread network still there after uninstalling OTBR Add-on

### ISSUE THREAD

**Issue by mpasdziernik** [home-assistant/addons#3343]
### Describe the issue you are experiencing

After uninstalling the OTBR add-on the created thread network "home assistant" is still the preferred network with reporting "no border routers found". 

I would expect that the network gets removed or that I am able to remove it via the gui. It is unclear to me if this preferred network without router will cause any problems.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

OpenThread Border Router

### What is the version of the add-on?

2.3.2

### Steps to reproduce the issue

1. Install add-on
2. Start with SkyConnect device
3. (optional) Delete corresponding integration
4. Uninstall add-on
...

## System Information

version | core-2023.11.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.63-haos
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4656
Installed Version | 1.33.0
Stage | running
Available Repositories | 1345
Downloaded Repositories | 13

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.2
-- | --
update_channel | stable
supervisor_version | supervisor-2023.11.6
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 30.8 GB
disk_used | 8.2 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.7.0), Advanced SSH & Web Terminal (16.0.2), Mosquitto broker (6.4.0), Zigbee2MQTT (1.34.0-1), NGINX Home Assistant SSL proxy (3.5.0), Cloudflared (4.2.11), Whisper (1.0.0), Piper (1.4.0), openWakeWord (1.8.2), Matter Server (4.10.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 9
views | 4
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | November 26, 2023 at 4:23 PM
-- | --
current_recorder_run | December 6, 2023 at 2:00 PM
estimated_db_size | 269.13 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Additional information

![Screenshot from 2023-12-06 09-28-55](https://github.com/home-assistant/addons/assets/7449605/4d10cd38-4e42-4d73-beee-29019dac085c)

**Comment by madmalkav** [comment]
Same here.

![imagen](https://github.com/home-assistant/addons/assets/11020793/344a326d-0037-4123-be43-8d5ccdd043fc)

**Comment by mpasdziernik** [comment]
It seems not to have any negative impact so far. New matter/thread devices can be added without problem and join the apple thread network "MyHome55". 

That is what I want but it is unclear why Home Assistant now chooses this network and why they ignore the nanoleaf network "NanoleafThread35".

**Comment by rd-michael-pasdziernik** [comment]
With the new version of the IOS companion app I was able to import the apple thread network credentials and choose the apple network as the preferred network. After this it was possible to delete the home assistant network.

**Comment by madmalkav** [comment]
I can´t do that, I get error 74.
