### ISSUE TITLE
Silicon Labs Flasher blocking NCP start then installed but **not** started

### ISSUE THREAD

**Issue by MattWestb** [home-assistant/addons#3347]
### Describe the issue you are experiencing

After updating my production system to HA 2023.12 ZHA is trying starting but is going offline and in portainer is the Silicon Labs Flasher porbing firmware after the NCP is initiated => ZHA is loosing the NCP and crashing and looping endless.

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### Which add-on are you reporting an issue with?

Silicon Labs Flasher

### What is the version of the add-on?

Current version: 0.2.0

### Steps to reproduce the issue

1.
2.
3.
...

## System Information

version | core-2023.12.0
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.21-v8+
arch | aarch64
timezone | Europe/Vienna
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 11 (bullseye)
-- | --
update_channel | stable
supervisor_version | supervisor-2023.11.6
agent_version | 1.4.1
docker_version | 24.0.7
disk_total | 58.3 GB
disk_used | 13.0 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | Custom deps deployment (1.3.4), Log Viewer (0.16.0), File editor (5.7.0), Matter Server (5.0.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 1
views | 6
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | November 30, 2023 at 16:17
-- | --
current_recorder_run | December 7, 2023 at 09:03
estimated_db_size | 575.76 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Anything in the Supervisor logs that might be useful for us?

```txt
Nothing here then the addon is uninstalled now for getting production system up and running
```

### Additional information

My 3 RCP system is not having this problem and was upgrade OK.
Also then having deleting the not started addon HA was trying starting it from cashed container with it and was needing one restart of the host system then it was away and ZHA is now starting OK.

Perhaps its somthing to do with ZHA is starting later now and the addon is not knowing ZHA is up and running on NCP coordinator (I think our **Puddly** is knowing how its working on the code level).
```[tasklist]
### Tasks
```

**Comment by puddly** [comment]
ZHA currently bundles [universal-silabs-flasher](https://github.com/NabuCasa/universal-silabs-flasher) and will try to probe firmware if setup fails to detect if RCP/Thread firmware is flashed by accident to a coordinator plugged straight into ZHA.

Is the flasher addon set to autostart on boot or does it have the watchdog setting enabled?
