### ISSUE TITLE
File Editor requires internet to be usable

### ISSUE THREAD

**Issue by starsoccer** [home-assistant/addons#3367]
### Describe the issue you are experiencing

I recently experienced an internet outage and was totally unable to use the file editor because it tries to load multiple files from cloudflare and other cdns. Ideally File editor should at bare minimum have local versions available to fall back to if they cant be loaded, or ideally be fully self contained and not require external resources.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

File editor

### What is the version of the add-on?

5.7.0

### Steps to reproduce the issue

1. Cut internet access from a device but allow local connection to HA only
2. Open file editor

### System Health information

N/A

**Comment by frenck** [comment]
Hi there @starsoccer 👋 

This is a duplicate of #2811

This is not a limitation of the add-on itself, but an limitation of the editor the add-on wraps. Track this upstream issue: 

<https://github.com/danielperna84/hass-configurator/issues/177>

Once upstream has addressed it, we can update the add-on.

../Frenck
