### ISSUE TITLE
Assist Microphone: end of speech detection is not working in a normal distance to a microphone

### ISSUE THREAD

**Issue by smoltron** [home-assistant/addons#3369]
### Describe the issue you are experiencing

My microphone is about 3 meters away in the living room. There is always a 15 second wait/timeout before the audio is sent further to the pipeline. When I speak from 5 cm distance of the microphone, the response is immediate, i.e. there is no wait. When I am 3 meters away, there is always the 15 second wait, even when the room is totally quiet. The sentences are in any case detected right.
I am using Jabra 410 hockey puck. It has a very sensitive microphone that can cover a large room easily. I think that the recording threshold must be set right and I have no idea where to start looking for the setting. Is it in local Assist Microphone or in wakeword detection?

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### Which add-on are you reporting an issue with?

Whisper

### What is the version of the add-on?

Assist Microphone was not in the list. I have the latest version.

### Steps to reproduce the issue

1. "alexa" -> chime
2. speak for 2 seconds
3.  wait for 13 seconds
4. chime
5. action

## System Information

version | core-2023.12.3
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 5.10.0-26-amd64
arch | x86_64
timezone | Europe/Helsinki
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.33.0
Stage | running
Available Repositories | 1426
Downloaded Repositories | 13
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | February 20, 2024 at 02:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | false
remote_server | eu-central-1-6.ui.nabu.casa
certificate_status | ready
instance_id | f22dcab6da364a768c5fa348f0378f99
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 11 (bullseye)
-- | --
update_channel | stable
supervisor_version | supervisor-2023.12.0
agent_version | 1.5.1
docker_version | 24.0.7
disk_total | 240.0 GB
disk_used | 59.9 GB
healthy | true
supported | true
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.8.1), deCONZ (6.22.0), Studio Code Server (5.14.2), MariaDB (2.6.1), Grafana (9.1.1), Matter Server (5.0.1), openWakeWord (1.8.2), Whisper (1.0.0), Piper (1.4.0), Assist Microphone (1.0.0), snowboy (1.0.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 10
views | 8
mode | storage

</details>

<details><summary>NextDNS</summary>

can_reach_server | ok
-- | --

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | December 14, 2023 at 05:42
-- | --
current_recorder_run | December 21, 2023 at 08:06
estimated_db_size | 211.59 MiB
database_engine | mysql
database_version | 10.6.12

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Comment by pako-github** [comment]
I do experience the same problem with the Anker Power Soundconf S330. In the raspberry version of this add-on one could select a folder under the debugging option such that the add-on puts there the sound files which it captured. I did have some succes with `ha audio volume input --index ... --volume XX` with another microphone. I still need to test this with the Anker. Maybe this helps as a workaround?

**Comment by bgoncal** [comment]
Same happens to me, although on iOS app or via browser silence is detected correctly
