### ISSUE TITLE
VLC Volume problem

### ISSUE THREAD

**Issue by yunusuztr** [home-assistant/addons#3375]
### Describe the issue you are experiencing

I’m having a problem with the VLC add-on. The volume setting always remains at 50%. I increase the volume but it still goes to 50%. Why does this happen? Do you have any solution suggestions?

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

VLC

### What is the version of the add-on?

0.3.0

### Steps to reproduce the issue

VLC volume yükselt
f5 refresh
tekrar volume %50

## System Information

version | core-2023.12.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.58-haos-raspi
arch | aarch64
timezone | Europe/Istanbul
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4976
Installed Version | 1.33.0
Stage | running
Available Repositories | 1359
Downloaded Repositories | 25

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 22

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 1 Ocak 2018 03:00
relayer_connected | false
relayer_region | null
remote_enabled | false
remote_connected | false
alexa_enabled | true
google_enabled | true
remote_server | null
certificate_status | null
instance_id | df56ed6e06b84d30996724500867f27d
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.2
-- | --
update_channel | stable
supervisor_version | supervisor-2023.12.0
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 457.7 GB
disk_used | 12.3 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.7.0), Terminal & SSH (9.8.1), Mosquitto broker (6.4.0), Studio Code Server (5.14.2), eWeLink Smart Home (1.4.3), Samba share (12.2.0), ESPHome (2023.12.5), Frigate (Full Access) (0.12.1), Node-RED (16.0.2), VLC (0.3.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 12
views | 7
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 17 Aralık 2023 19:57
-- | --
current_recorder_run | 27 Aralık 2023 19:15
estimated_db_size | 245.94 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

<details><summary>Sonoff</summary>

version | 3.5.3 (a8c6d45)
-- | --
cloud_online | 5 / 5
local_online | 5 / 5

</details>

**Comment by MartinHjelmare** [comment]
How are you changing the volume?

**Comment by yunusuztr** [comment]
![Ekran görüntüsü 2023-12-27 210556](https://github.com/home-assistant/addons/assets/129348788/b2b6863d-6c9f-4eb4-adc6-5cd7af75aa6a)
![Ekran görüntüsü 2023-12-27 210608](https://github.com/home-assistant/addons/assets/129348788/0f9949aa-633a-4201-bd55-780572180ebc)
 
The same result is obtained with these two different methods.

**Comment by MartinHjelmare** [comment]
Please activate debug logging for the integration and then change the volume of the entity in the Home Assistant GUI (the bottom one of your images). Attach the captured debug log to this issue as a txt file. Thanks!

**Comment by yunusuztr** [comment]
[Yeni Metin Belgesi.txt](https://github.com/home-assistant/addons/files/13780437/Yeni.Metin.Belgesi.txt)

for the log I restarted the plugin and then changed the audio and this is how the log turned out.

**Comment by MartinHjelmare** [comment]
That's the add-on log. I'd like the integration log.

**Comment by yunusuztr** [comment]
[log.txt](https://github.com/home-assistant/addons/files/13780479/log.txt)
I think that's true

**Comment by yunusuztr** [comment]
https://github.com/home-assistant/addons/assets/129348788/1944731f-919f-41b8-a1f6-519a4254120b
