### ISSUE TITLE
Samba Share 12.2.0 doesn't start

### ISSUE THREAD

**Issue by feron81** [home-assistant/addons#3393]
### Describe the issue you are experiencing

I have the problem that I'm not able to start Samba share on the newest Home Assistant update.

Now I have the problem that I'm not able to start Samba share. Do you know why?

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Almond

### What is the version of the add-on?

12.2.0

### Steps to reproduce the issue

1. I'm not able to start
2.
3.
...

### System Health information

No entires

**Comment by feron81** [comment]
The Log shows me following:
The log shows me following:
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-smbd: starting
[16:06:22] INFO: Hostname: homeassistant
[16:06:22] INFO: Interfaces: enp0s3
tdbsam_open: Converting version 0.0 database to version 4.0.
tdbsam_convert_backup: updated /var/lib/samba/private/passdb.tdb file.
Added user homeassistant.
s6-rc: info: service init-smbd successfully started
s6-rc: info: service smbd: starting
smbd version 4.18.8 started.
Copyright Andrew Tridgell and the Samba Team 1992-2023
INFO: Profiling support unavailable in this build.
s6-rc: info: service smbd successfully started
s6-rc: info: service nmbd: starting
nmbd version 4.18.8 started.
Copyright Andrew Tridgell and the Samba Team 1992-2023
s6-rc: info: service nmbd successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started

Samba name server HOMEASSISTANT is now a local master browser for workgroup WORKGROUP on subnet 192.168.1.6

idmap range not specified for domain ‘’
idmap range not specified for domain '’


And the app looks like that:
![Screenshot 2024-01-07 161743](https://github.com/home-assistant/addons/assets/84832617/5ef5b1b4-d2d3-46b2-8148-0646ae14d1f1)

**Comment by feron81** [comment]
Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:138
Integration: Home Assistant Supervisor ([documentation](https://www.home-assistant.io/integrations/hassio), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+hassio%22))
First occurred: 19:02:07 (2 occurrences)
Last logged: 19:02:22

Failed to to call /addons/core_samba/stats - 404 Client Error for http+docker://localhost/v1.43/containers/addon_core_samba/json: Not Found ("No such container: addon_core_samba")
Failed to to call /addons/core_samba/start - Another job is running for job group addon_core_samba

**Comment by Marcofant** [comment]
I have the same problem.
