### ISSUE TITLE
Silicon Labs Multiprotocol: OpenThread Border Router not working

### ISSUE THREAD

**Issue by merlinpimpim** [home-assistant/addons#3395]
### Describe the issue you are experiencing

I can't configure the OTBR integration with Silicon Labs Multiprotocol (SLM) 2.4.2:
![image](https://github.com/home-assistant/addons/assets/113300765/a6e46675-2933-472f-9f68-679dc76dc1ea)

In the SLM addon, with (firewall disabled):
![image](https://github.com/home-assistant/addons/assets/113300765/e38331fc-16b2-41df-892c-de61ebbc0451)

> [20:01:09] INFO: Successfully sent discovery information to Home Assistant.
s6-rc: info: service otbr-agent-rest-discovery successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
otbr-agent[308]: 00:00:26.334 [N] Mle-----------: RLOC16 b000 -> fffe
otbr-agent[308]: 00:00:27.072 [N] Mle-----------: Attach attempt 1, AnyPartition reattaching with Active Dataset
otbr-agent[308]: 00:00:33.575 [N] RouterTable---: Allocate router id 44
otbr-agent[308]: 00:00:33.576 [N] Mle-----------: RLOC16 fffe -> b000
otbr-agent[308]: 00:00:33.580 [N] Mle-----------: Role detached -> leader
otbr-agent[308]: 00:00:33.580 [N] Mle-----------: Partition ID 0x3a107857
ipset v7.10: Kernel error received: Invalid argument
otbr-agent[308]: 00:00:33.593 [W] Platform------: Failed to update ipsets: Failed
ipset v7.10: Kernel error received: Invalid argument
otbr-agent[308]: 00:00:34.043 [W] Platform------: Failed to update ipsets: Failed
otbr-agent[308]: 00:00:34.087 [C] Platform------: InitMulticastRouterSock() at multicast_routing.cpp:225: Protocol not available
[20:01:41] INFO: otbr-agent ended with exit code 5 (signal 0)...
[20:01:41] INFO: OTBR firewall teardown completed.
[20:01:41] WARNING: otbr-agent exited with code 5 (by signal 0).
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service otbr-agent-rest-discovery: stopping
s6-rc: info: service zigbeed: stopping
s6-rc: info: service mdns: stopping
s6-rc: info: service otbr-agent-rest-discovery successfully stopped
s6-rc: info: service otbr-agent: stopping
Default: mDNSResponder (Engineering Build) (Jan  5 2024 22:17:54) stopping
[20:01:41] INFO: zigbeed ended with exit code 256 (signal 15)...
[20:01:41] INFO: mDNS ended with exit code 4 (signal 0)...
s6-rc: info: service zigbeed successfully stopped
s6-rc: info: service mdns successfully stopped
[20:01:41] INFO: otbr-agent ended with exit code 256 (signal 15)...
[20:01:41] INFO: OTBR firewall teardown completed.
[20:01:41] WARNING: otbr-agent exited with code 143 (by signal 15).
s6-rc: info: service otbr-agent successfully stopped
s6-rc: info: service cpcd: stopping
[20:01:40:932727] Info : Endpoint socket #12: Client disconnected. 1 connections
[20:01:40:971659] Info : Client disconnected
[20:01:41:134108] Info : Endpoint socket #12: Client disconnected. 0 connections
[20:01:41:134365] Info : Client disconnected
[20:01:41:301302] Info : Server core cleanup
[20:01:41:301427] Info : Daemon exiting with status EXIT_SUCCESS
Logger buffer size = 28672, highwater mark = 2478 : 8.64%. Lost logs : 0
[20:01:41] INFO: CPC ended with exit code 0 (signal 0)...
s6-rc: info: service cpcd successfully stopped
s6-rc: info: service cpcd-config: stopping
s6-rc: info: service cpcd-config successfully stopped
s6-rc: info: service universal-silabs-flasher: stopping
s6-rc: info: service universal-silabs-flasher successfully stopped
s6-rc: info: service banner: stopping
s6-rc: info: service banner successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

--> The SLM addon crash :(

In the SLM addon, with (firewall enabled):
![image](https://github.com/home-assistant/addons/assets/113300765/8cf4afcb-68ba-4dfa-afac-c8158d8a22f1)

> [20:07:42] INFO: Starting zigbeed...
[20:07:43] INFO: Setup OTBR firewall...
ipset v7.10: Kernel error received: Invalid argument
[20:07:43] INFO: otbr-agent ended with exit code 1 (signal 0)...
[20:07:43] INFO: OTBR firewall teardown completed.
[20:07:43] WARNING: otbr-agent exited with code 1 (by signal 0).
[20:07:43:543206] Info : New client connection using library v4.3.1.0
[20:07:43:547710] Info : Opened connection socket for ep#12
[20:07:43:547878] Info : Endpoint socket #12: Client connected. 1 connections
[20:07:46] INFO: Setup OTBR firewall...
ipset v7.10: Kernel error received: Invalid argument
Listening on port 9999 for connection...
Accepting connection.
[20:07:46] INFO: otbr-agent ended with exit code 1 (signal 0)...
[20:07:46] INFO: OTBR firewall teardown completed.
[20:07:46] WARNING: otbr-agent exited with code 1 (by signal 0).
[20:07:49] INFO: Setup OTBR firewall...
ipset v7.10: Kernel error received: Invalid argument
[20:07:49] INFO: otbr-agent ended with exit code 1 (signal 0)...
[20:07:49] INFO: OTBR firewall teardown completed.
[20:07:49] WARNING: otbr-agent exited with code 1 (by signal 0).
[20:07:52] INFO: Setup OTBR firewall...
ipset v7.10: Kernel error received: Invalid argument
[20:07:52] INFO: otbr-agent ended with exit code 1 (signal 0)...
[20:07:52] INFO: OTBR firewall teardown completed.
[20:07:52] WARNING: otbr-agent exited with code 1 (by signal 0).

--> The SLM addon does NOT crash. But I still can't configure OTBR integration.

"**ipset v7.10: Kernel error received: Invalid argument**" seems to be the problem but I don't know how to solve it !

Note: with version 2.3.2 I could configure OTBR integration with the following configuration in SLM:
- OTBR enabled
- Firewall disabled.

The addon did not crash (but the ipset v7.10 error was already present).

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### Which add-on are you reporting an issue with?

Silicon Labs Multiprotocol

### What is the version of the add-on?

2.4.2

### Steps to reproduce the issue

1. Starting SLM 2.4.2
2. Read the logs
3.
...

## System Information

version | core-2024.1.2
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 5.4.180
arch | aarch64
timezone | Europe/Paris
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4935
Installed Version | 1.33.0
Stage | running
Available Repositories | 1368
Downloaded Repositories | 9

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 11 (bullseye)
-- | --
update_channel | stable
supervisor_version | supervisor-2023.12.0
agent_version | 1.5.1
docker_version | 24.0.7
disk_total | 14.4 GB
disk_used | 12.4 GB
healthy | true
supported | true
supervisor_api | ok
version_api | ok
installed_addons | deCONZ (6.22.0), File editor (5.7.0), Advanced SSH & Web Terminal (17.0.1), Zigbee2MQTT (1.35.0-1), Studio Code Server (5.14.2), Home Assistant Google Drive Backup (0.112.1), Log Viewer (0.16.0), Grafana (9.1.1), Mosquitto broker (6.4.0), Matter Server (5.0.2), Node-RED (16.0.2), Silicon Labs Multiprotocol (2.4.2), Silicon Labs Flasher (0.2.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 2
views | 3
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | December 28, 2023 at 01:03
-- | --
current_recorder_run | January 6, 2024 at 20:38
estimated_db_size | 805.91 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Additional information

HA supervised on a Khadas VIM1S (Fenix 1.5.1 Debian GNU/Linux 11 (bullseye) Linux 5.4.180).

**Comment by sblogoshs** [comment]
I also have this error that I posted on Core (now closed), because this error had clearly occurred with Core 2024.1.0b5 for the first time and is now still present with 2024.1.0.
The OTBR is started by Silicon Labs Multiprotocol and is also accessible via the web interface, but the OTBR device cannot be set up (error during setup).
- RPi4 and OS 11.3

**Comment by merlinpimpim** [comment]
Who can correct this error?

**Comment by merlinpimpim** [comment]
Hello,

Still no news?

How can I correct this issue on a supervised Home Assistant like mine, please?

```
INFO: Setup OTBR firewall...
ipset v7.10: Kernel error received: Invalid argument
```

**Comment by msevestre31** [comment]
Exactly same issue here with my SonOff ZBDongle-E flashed with multiprotocol.

With OTBR firewall disabled, I can quickly see the dongle Open Thread Border Router, until Silicon Labs Multiprotocol add-on stops by itself. Zigbe2MQTT is indeed not working (as SLM add on stops).

With With OTBR firewall enabled, the Silicon Labs Multiprotocol add-on continues to work (so Zigbe2MQTT can be used), but no Open Thread border router found anytime, and SLM add on logs loops with the following messages:
`[09:11:49] INFO: otbr-agent ended with exit code 1 (signal 0)...
[09:11:49] INFO: OTBR firewall teardown completed.
[09:11:49] WARNING: otbr-agent exited with code 1 (by signal 0).
[09:11:52] INFO: Setup OTBR firewall...
ipset v7.10: Kernel error received: Invalid argument`

**Comment by merlinpimpim** [comment]
I don't know who is capable of dealing with this issue, but no one has responded to our problems since the case was opened.

**Comment by msevestre31** [comment]
I found some discussions about updating dongle to firmware 4.4.0, which unfortunately is finally NOK as current SLM add on is working with 4.3.1 (actually, by two times, the add on had to be udpated to fit with 4.3.1 as 4.4.0 was not stable).

Let's wait for a later version with a stable 4.4.x firmware and related SLM add-on.

**Comment by merlinpimpim** [comment]
The issue seems to be more complex than that as I have the impression that it exists on the supervised versions of Home Assistant but not on the HassOS version.

**Comment by msevestre31** [comment]
I am on supervised as well. All this is fairly recent, thus let's be patient :)

**Comment by merlinpimpim** [comment]
up
Does anyone know how to fix this issue, please?

**Comment by merlinpimpim** [comment]
up

**Comment by merlinpimpim** [comment]
Still no answer, but I did find this:
https://github.com/home-assistant/addons/issues/3446

**Comment by merlinpimpim** [comment]
Does anyone have any information on this issue?

**Comment by afsy-d** [comment]
Hey, potential to reopen this? Having the same issue with a Home Assistant Yellow +  Silicon Labs Multiprotocol 2.4.5 + the OTBR addon.
