### ISSUE TITLE
Whisper crash after version 1.0.1.

### ISSUE THREAD

**Issue by andregoncalvespires** [home-assistant/addons#3403]
### Describe the issue you are experiencing

Use HASSOS on a proxmox virtual machine. After upgrading Whisper to version 1.0.1, the error "FATAL: Your CPU does not support the Advanced Vector Extensions required by Whisper." started to be displayed in the addon log.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Whisper

### What is the version of the add-on?

1.0.1

### Steps to reproduce the issue

1. Use HASSOS in VM proxmox
2. Instal or Update 1.0.1 whisper addon version
3. Start addon

## System Information

version | core-2024.1.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.70-haos
arch | x86_64
timezone | America/Sao_Paulo
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4481
Installed Version | 1.33.0
Stage | running
Available Repositories | 1381
Downloaded Repositories | 38

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.3
-- | --
update_channel | stable
supervisor_version | supervisor-2023.12.0
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 30.8 GB
disk_used | 17.6 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Advanced SSH & Web Terminal (17.0.2), ESPHome (2023.12.5), Grafana (9.1.2), Home Assistant Google Drive Backup (0.105.2), InfluxDB (5.0.0), MQTT Explorer (browser-1.0.1), Piper (1.4.0), Samba share (12.2.0), Studio Code Server (5.15.0), Zigbee2MQTT (1.35.1-1), openWakeWord (1.8.2), Matter Server (5.0.2), Mosquitto broker (6.4.0), Whisper (1.0.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 23
views | 38
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 30 de dezembro de 2023 às 03:46
-- | --
current_recorder_run | 8 de janeiro de 2024 às 20:44
estimated_db_size | 1404.08 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

<details><summary>Sonoff</summary>

version | 3.5.4 (a4a8c5f)
-- | --
cloud_online | 2 / 2
local_online | 2 / 2

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

```[tasklist]
### Tasks
```

**Comment by emwjacobson** [comment]
+1 for this. Whisper was running fine for me pre-update. Post update it won't start with the same "FATAL" error.

**Comment by Bredick** [comment]
I'm having the same problem, running haos vm on esxi on an atom c3758 CPU.

**Comment by cwquek** [comment]
+1  I am running on Proxmox, Whisper was running pre-update. After update to 1.0.1, it won't start with the same "FATAL" error.

**Comment by Goopdegooo** [comment]
Running fine with me on version 1.0.0, updated and 
[14:12:37] FATAL: Your CPU does not support the Advanced Vector Extensions required by Whisper.
[14:12:37] INFO: Service exited with code 1 (by signal 0)

Now will not start, CPU N5105.  No AVX support, but again was working fine on previous version 1.0.0.

**Comment by Scarriffle** [comment]
Same Problem since updating to version 1.0.1, CPU: Intel Pentium J5005

**Comment by 4thepayers** [comment]
Same error here, CPU: AMD Ryzen 5 PRO 3400G.
Worked fine till update 1.0.1

**Comment by zombie241088** [comment]
Same here 
CPU: Intel® Celeron® Processor N5095 on mini pc with Proxmox

**Comment by zeekens** [comment]
Same here, but @emwjacobson trick of setting the cpu type to "host" on Proxmox seem to have fixed it

**Comment by ninoger** [comment]
I confirm. Same "Your CPU does not support the Advanced Vector Extensions required by Whisper" error after 1.0.1 update. Up to version 1.0.0 everything is fine. Home assistant is on mini pc N5095, version 2024.1.2, supervisor 2023.12.0, OS 11.3

**Comment by frodo777** [comment]
Same Problem since updating to version 1.0.1. Proxmox intel i5 VM

**Comment by emwjacobson** [comment]
This change comes from commit 314ec9f54966ae14099bb874f1e5547b8cdd46fa introducing a new check for AVX instructions on the machine.

The program can obviously run without AVX, seeing as it has worked for users in the past without AVX-enabled CPUs.

Would it be possible to have it issue a Warning into the console that the CPU does not support AVX instructions, rather than outright exiting?

**Comment by holligram** [comment]
FATAL: Your CPU does not support the Advanced Vector Extensions required by Whisper.
Since version 1.0.1.
Proxmox VM running HAOS. Host CPU AMD Ryzen 7 5800U

**Comment by MatteoD77** [comment]
+ 1! same fatal error CPU not supported.

**Comment by holligram** [comment]
I fixed this by changing the Proxmox VM CPU type from default 'kvm64' to 'host'. That allows AVX cpu extensions to be used by the VM.

**Comment by agners** [comment]
Hm, I actually don't have an affected machine, this got implemented based on user feedback, specifically https://github.com/home-assistant/addons/issues/3035#issuecomment-1862765838 and #3355. 

Obviously, if it used to work on other machines without AVX, we should not exit then!

I wonder if those user were missing another instruction set as well, which lead to actual crashes (SIGILL). :thinking:

**Comment by holligram** [comment]
> Hm, I actually don't have an affected machine, this got implemented based on user feedback, specifically [#3035 (comment)](https://github.com/home-assistant/addons/issues/3035#issuecomment-1862765838) and #3355.
> 
> Obviously, if it used to work on other machines without AVX, we should not exit then!
> 
> I wonder if those user were missing another instruction set as well, which lead to actual crashes (SIGILL). 🤔

It works without AVX but it is very slow. The change made was exclude CPU's that don't support AVX extensions because of this slow response. There is a hotfix in the works to change the exclusion to a waring. However it will be much better to to fix the underlying problem and change the VM cpu to support AVX instructions as discussed in this post https://forum.proxmox.com/threads/cpu-type-host-vs-kvm64.111165/

**Comment by andregoncalvespires** [comment]
Version 1.0.2 is working for me. Tks
