### ISSUE TITLE
deCONZ version outdated

### ISSUE THREAD

**Issue by thexperiments** [home-assistant/addons#3413]
### Describe the issue you are experiencing

deCONZ version is outdated and thus doesn't have improvements made to several ZigBee device integrations and thus also is not able to find newer devices (In my case a recent Tuya radar human presence sensor)

https://github.com/home-assistant/addons/blob/2fb7dddbb0e6cbc0103eee3a8a1766e72f144f8a/deconz/build.yaml#L10

2.22 is from September and there currently is 2.24 as of two weeks ago.

Would be great to se this in the next update.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Almond

### What is the version of the add-on?

6.22.0

### Steps to reproduce the issue

Try to pair a device which support has been added for after 2.22 of deCONZ

## System Information

version | core-2024.1.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.71-haos
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4966
Installed Version | 1.33.0
Stage | running
Available Repositories | 1389
Downloaded Repositories | 20

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.4
-- | --
update_channel | stable
supervisor_version | supervisor-2023.12.0
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 30.8 GB
disk_used | 18.9 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Samba share (12.2.0), File editor (5.7.0), Portainer (1.5.1), RPC Shutdown (2.4), SQLite Web (4.1.0), Terminal & SSH (9.8.1), ikettle2mqtt (0.0.3), Studio Code Server (5.15.0), Z-Wave JS UI (3.1.0), Home Assistant Google Drive Backup (0.112.1), deCONZ (6.22.0), ESPHome (2023.12.5), WireGuard (0.10.2), openWakeWord (1.8.2), Whisper (1.0.2), Piper (1.4.0), Matter Server (5.0.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 11
views | 13
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 6. Januar 2024 um 14:49
-- | --
current_recorder_run | 13. Januar 2024 um 10:14
estimated_db_size | 939.10 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Comment by Rento25** [comment]
I also have the same issue with new Aqara T1 sensors. It works when I plug my conbee 2 in my PC, with the latest version.

Kind regards,

Rento Bijl

**Comment by Vitani** [comment]
2.24+ is needed to add support for the Conbee III stick - this was known back on November, so I don't know why it's not been updated.

**Comment by Tycho-S** [comment]
Actually if you're going for an update, 2.25 is almost out and it adds support for many interesting devices, IKEA VINDSTYRKA and Xiaomi LYWSD03MMC, so it would really be nice to get this soon <3

**Comment by derekcentrico** [comment]
Ah, didn't see addons repo.  Okay, so it looks like @francescopeloi is on this.  https://github.com/francescopeloi/addons/commits/master/deconz

@Tycho-S not sure about timelines for 2.25 and plans to get this moving forward sooner vs. later, but @francescopeloi repo shows 2.24.03 as current work going on.

**Comment by francescopeloi** [comment]
If you are waiting a new deconz version to get device support, there's ways to get the device support with your current deconz version. This works only if the new DDF is needed. I've never tried myself, you need to be docker savvy. Read [this](https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet) and [this](https://dresden-elektronik.github.io/deconz-dev-doc/modules/ddf/).

Not saying it's easy, but can be done.

**Comment by derekcentrico** [comment]
> If you are waiting a new deconz version to get device support, there's ways to get the device support with your current deconz version. This works only if the new DDF is needed. I've never tried myself, you need to be docker savvy. Read [this](https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet) and [this](https://dresden-elektronik.github.io/deconz-dev-doc/modules/ddf/).
> 
> Not saying it's easy, but can be done.

Thanks for jumping on the thread. I'll happily wait for your commits to make it to the master and send you a beer once there lol

**Comment by Tycho-S** [comment]
> If you are waiting a new deconz version to get device support, there's ways to get the device support with your current deconz version. This works only if the new DDF is needed. I've never tried myself, you need to be docker savvy. Read [this](https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet) and [this](https://dresden-elektronik.github.io/deconz-dev-doc/modules/ddf/).
> 
> Not saying it's easy, but can be done.

The problem is that you need a lot more than docker magic :) Because most of us run on Home Assistant OS and it doesn't allow any SSH logins to the core OS. You can install the terminal addon but it doesn't allow access to docker.

**Comment by francescopeloi** [comment]
You can enable ssh on the OS, I've done so. I'll find the reference when i get home, if you cannot find it earlier :)

**Comment by francescopeloi** [comment]
@Tycho-S here it is: https://developers.home-assistant.io/docs/operating-system/debugging/

**Comment by derekcentrico** [comment]
@francescopeloi any chance we'll see a commit of your updated deconz work in the near future?

**Comment by frenck** [comment]
Just released a new version of the add-on, containing the latest deconz.

../Frenck
