### ISSUE TITLE
Silicon Labs Multiprotocol + ZHA + Sonoff ZB Dongle E = Aqara door sensor not reporting correctly

### ISSUE THREAD

**Issue by GitWally** [home-assistant/addons#3417]
### Describe the issue you are experiencing

Hello,
the full history, to depict all details.

I decided to implement ZigBee in my HA environment, so I bought:

1. [Sonoff Zigbee USB 3.0 Dongle Plus](https://sonoff.tech/product/gateway-and-sensors/sonoff-zigbee-3-0-usb-dongle-plus-e/)
2. USB extension cable, to keep antenna far away from HA (which is wired) and Router
3. [Aqara Door & Window Sensor](https://zigbee.blakadder.com/Aqara_MCCGQ11LM.html)

Since I was starting from scratch I decided to go for Multiprotocol approach to benefit from Matter / Thread in the next future.

Before any other intervention I have fixed WiFi 2.4 GHz channels 1 (router) and 6 (Access Point), in order to use Channel 25 with Zigbee.

Then I flashed Sonoff with [web flasher from darkxst](https://github.com/darkxst/silabs-firmware-builder) using RCP Remote Co-Processor firmware (see zbdonglee/rcp-uart-802154-v4.3.2-zbdonglee-460800 > https://github.com/darkxst/silabs-firmware-builder/blob/main/firmware_builds/zbdonglee/). Flashing was pretty straight forward
 
Then I installed [Silicon Labs Multiprotocol](https://github.com/home-assistant/addons/tree/master/silabs-multiprotocol) 2.4.3 with given parameters (baudrate 460800, no hardware flow control, no automatically update firmware)

Initially I tried to install [Zigbee2MQTT v 1.35.1](https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/releases/tag/v1.35.1-1) but was not able to start, so gave up and went for ZHA

In ZHA i was able to pair Aqara sensor, but in a short it started to report wrongly almost randomly.

In the end I gave up the Multiprotocol approach (I don't need Matter as of today), flashed Sonoff with NCP Network Co-Processor firmware (7.3.1.0 build 176) and Aqara started working preciselly and very accurate! 
This last point confirms hardware is ok, no problem with interference or whatsoever 

Questions are:

a. has anybow reported this misbehaviour? 
b. may be, when Silicon Labs Multiprocol will exit "experimental" phase, this be fixed?

Many thanks for attention!

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### Which add-on are you reporting an issue with?

Silicon Labs Multiprotocol

### What is the version of the add-on?

2.4.3

### Steps to reproduce the issue

1. Flashed Sonoff with [web flasher from darkxst](https://github.com/darkxst/silabs-firmware-builder) using RCP Remote Co-Processor firmware (see zbdonglee/rcp-uart-802154-v4.3.2-zbdonglee-460800 > https://github.com/darkxst/silabs-firmware-builder/blob/main/firmware_builds/zbdonglee/)

2. Installed [Silicon Labs Multiprotocol](https://github.com/home-assistant/addons/tree/master/silabs-multiprotocol) 2.4.3 with given parameters (baudrate 460800, no hardware flow control, no automatically update firmware)

3. Using ZHA pair [Aqara Door & Window Sensor](https://zigbee.blakadder.com/Aqara_MCCGQ11LM.html)

4. Check sensor reliability ...

## System Information

version | core-2024.1.3
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 5.10.0-27-amd64
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.33.0
Stage | running
Available Repositories | 1450
Downloaded Repositories | 8
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 11 (bullseye)
-- | --
update_channel | stable
supervisor_version | supervisor-2023.12.1
agent_version | 1.5.1
docker_version | 24.0.7
disk_total | 232.2 GB
disk_used | 191.5 GB
healthy | true
supported | true
supervisor_api | ok
version_api | ok
installed_addons | Duck DNS (1.15.0), File editor (5.7.0), Home Assistant Google Drive Backup (0.112.1), Mosquitto broker (6.4.0), Glances (0.21.0), Frigate (Full Access) Beta (0.13.0) (0.13.0-rc1), Piper (1.4.0), Whisper (1.0.2), Google Assistant SDK (2.5.0), openWakeWord (1.8.2), Hikvision Doorbell (3.0.13), Silicon Labs Multiprotocol (2.4.3)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 3
views | 11
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 7 January 2024 at 07:30
-- | --
current_recorder_run | 15 January 2024 at 22:10
estimated_db_size | 180.90 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

**Comment by Towtoll** [comment]
I tried with nanoleaf product and I have the exact same problem when trying to pair

**Comment by puddly** [comment]
Are you using identical network settings in each test (i.e. channel 25)?

**Comment by GitWally** [comment]
> Are you using identical network settings in each test (i.e. channel 25)?

Yes, in both cases channel 25

**Comment by samoz83** [comment]
I had the same experience with Aqara door sensors and Hue motion sensors. Pretty much the same setup except using zigbee2mqtt.

Seems messages from a number of end devices were not being picked up or processed when using the multiprotocol setup.

Switched back to just NCP firmware and everything is working as expected. Device states updating immediately when changes happen.

**Comment by GitWally** [comment]
> Switched back to just NCP firmware and everything is working as expected. Device states updating immediately when changes happen.

I hope that's because Multiprotocol is experimental

**Comment by hensjl** [comment]
Same problem here. Devices that only push messages, like switches and motion sensors, have unstable connection. Before returning back to NCP firmware, this week I will test some of them with Tuya cloud.

**Comment by MattWestb** [comment]
Be sure having some good routers and adding end devices to roues and **no**t to the coordinator (then its also one router but its not 24/7 online then restarting  the system and all problem devices you have need 24/7 parent or they is getting problems).
Also after have adding one router (or more) disabling the coordinator having direct child's is recommended by adding it in the HA config and is getting more stable end devices in the network.

**Comment by GitWally** [comment]
> Be sure having some good routers and adding end devices to roues and **no**t to the coordinator (then its also one router but its not 24/7 online then restarting  the system and all problem devices you have need 24/7 parent or they is getting problems).
> 
> Also after have adding one router (or more) disabling the coordinator having direct child's is recommended by adding it in the HA config and is getting more stable end devices in the network.

In my case Aqara sensors are 3 mt away from the coordinator, less than 1,5 in straight line. Do you say also in this simple case I should put a router in the middle?
Thought it was needed in a larger mesh.
For the moment I will stay just with zigbee, since I heard a lot of issues with Silicon Lab Multiprocol versions.
Thanks

**Comment by hensjl** [comment]
> Same problem here. Devices that only push messages, like switches and motion sensors, have unstable connection. Before returning back to NCP firmware, this week I will test some of them with Tuya cloud.

GOOD NEWS

I have 5 motion sensors (2 tuya and 3 ikea), all had problem with RCP.
I never used NCP and had the problem  from the beginig, 2 or 3 months ago.  Flashed with darkxst web falsher from the begining.
/dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20231007154236-if00

I Disconnected the 2 tuya, to connect them to a little tuya hub. no more problem for them.
The 3 ikea sensors are set side by side to be activated together. About once in ten, the 3 sensors do not see me, always together.

Then, I decided to to fash back to NCP with the same tool from darkxst.
But I can't. Devide detected but not firmware and the flasher stop.
Having no time to investigate, I put the dongle back to my Pi4.

NOW IT WORK LIKE EXPECTED

What is changed ?
* in config:
 otbr_enable: from true to false
 otbr_log_level: form debug to info
* disabled "Open Thread Border Router" integration.
* last but probably nothing to do with
 HAcore from 2024.1.5 to 2024.1.6

If this can help someone...
