### ISSUE TITLE
LetsEncrypt addon: Add option to request secp384r1 certificate

### ISSUE THREAD

**Issue by DanAE111** [home-assistant/addons#3418]
### Describe the issue you are experiencing

I run a private CA with an internal ACME server when the addon requests an ecdsa certificate from my CA it is defaulting to a secp256r1 certificate. Would it be possible to add additional parameters for the elliptic curve type and key size so that they can be specified as part of advanced configuration?

My internal CA kicks back the cert request because the key size is below 384.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Let's Encrypt

### What is the version of the add-on?

5.0.9

### Steps to reproduce the issue

1. Have an ACME server that only accepts secp384r1 certificate requests.
2. Configure the addon to use said ACME server.
3. Request a certificate.
4. Certificate request is rejected because the key size requested is too small (secp256r1 instead of secp384r1).

## System Information

version | core-2023.12.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.63-haos
arch | x86_64
timezone | Australia/Sydney
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.33.0
Stage | running
Available Repositories | 1383
Downloaded Repositories | 22

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.2
-- | --
update_channel | stable
supervisor_version | supervisor-2023.12.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 30.8 GB
disk_used | 10.5 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.8.1), File editor (5.7.0), ESPHome (2023.12.7), NGINX Home Assistant SSL proxy (3.5.0), Samba share (12.2.0), TubesZB TI CC2652 FW Flasher (0.2.2), SQLite Web (4.0.0), Let's Encrypt (5.0.9)

</details>

<details><summary>Dashboards</summary>

dashboards | 6
-- | --
resources | 6
views | 7
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | December 25, 2023 at 10:34 PM
-- | --
current_recorder_run | December 26, 2023 at 9:34 AM
estimated_db_size | 103.56 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Anything in the add-on logs that might be useful for us?

```txt
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/file-structure.sh
cont-init: info: /etc/cont-init.d/file-structure.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun lets-encrypt (no readiness notification)
s6-rc: info: service legacy-services successfully started
[22:55:51] INFO: Selected http verification
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Account registered.
Requesting a certificate for homeassistant.mycooldomain.arpa
An unexpected error occurred:
acme.errors.IssuanceError
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### Additional information

![image](https://github.com/home-assistant/addons/assets/2210900/55874f7b-f878-4304-a7c2-913826f28cd4)

**Comment by WillCodeForCats** [comment]
I'd previously proposed an option for this, but I'll try getting it passed again in PR #3424.

**Comment by DanAE111** [comment]
Thanks. Happy to assist with testing if required.

**Comment by WillCodeForCats** [comment]
To use this set the following config:

```
key_type: 'ecdsa'
elliptic_curve: 'secp384r1'
```

**Comment by DanAE111** [comment]
Tested the updated addon and can confirm it allows me to request a ecdsa / secp384r1 certificate.

Thanks for implementing the required configuration parameters.

**Comment by GoetzGoerisch** [comment]
Fixed with https://github.com/home-assistant/addons/pull/3424
@DanAE111 if this can be closed, please do so?

**Comment by DanAE111** [comment]
> Fixed with https://github.com/home-assistant/addons/pull/3424
> @DanAE111 if this can be closed, please do so?

No worries. Done 😊
