### ISSUE TITLE
docker-ce 5.25 incompatible with MariaDb addon

### ISSUE THREAD

**Issue by smoltron** [home-assistant/addons#3425]
### Describe the issue you are experiencing

I did an update to docker-ce version 5.25.0.0 and found that it does not work with MariaDB container, at least in my setup. The container did not start with 5.25. The solution was to downgrade docker-ce to 5.24.0.7. Now it runs fine. This is Debian Bookworm amd64 and the package source is directly from Docker Bookworm stable repository.
The container did not start manually either.`

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### Which add-on are you reporting an issue with?

MariaDB

### What is the version of the add-on?

2.6.1

### Steps to reproduce the issue

1. Update docker-ce 5.25 from Docker Bookworm stable repository
2. MariaDb did not start
3. Downgrade docker-ce to 5.24
4. MariaDb starts normally

## System Information

version | core-2024.1.4
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.0-17-amd64
arch | x86_64
timezone | Europe/Helsinki
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.33.0
Stage | running
Available Repositories | 1450
Downloaded Repositories | 14
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | February 20, 2024 at 02:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | false
remote_server | eu-central-1-6.ui.nabu.casa
certificate_status | ready
instance_id | f22dcab6da364a768c5fa348f0378f99
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 12 (bookworm)
-- | --
update_channel | stable
supervisor_version | supervisor-2023.12.1
agent_version | 1.5.1
docker_version | 24.0.7
disk_total | 240.0 GB
disk_used | 48.5 GB
healthy | true
supported | true
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.8.1), Studio Code Server (5.15.0), MariaDB (2.6.1), Matter Server (5.0.4), deCONZ (6.22.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 10
views | 8
mode | storage

</details>

<details><summary>NextDNS</summary>

can_reach_server | ok
-- | --

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | January 13, 2024 at 09:40
-- | --
current_recorder_run | January 20, 2024 at 09:46
estimated_db_size | 564.31 MiB
database_engine | mysql
database_version | 10.6.12

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Comment by RC-Thoughts** [comment]
Can confirm.

**Comment by MattWestb** [comment]
Supervised is complete broken with docker 25.0 and they have fixing it in docker 26.0 and its being backported to 25.1 then its being released. Rolling back the latest working and waiting for docker being OK or if HA is fixing the static IP address issue that is making the problem (IP-address out of the containers configurated one).

**Comment by StephensGraeme** [comment]
Hi guys, I seem to have fallen in to this hole, I'm not the best with docker.
Any chance you could post a step by step on how to downgrade docker back to 5.24.0.7?

Thanks

**Comment by smoltron** [comment]
Instructions are here: https://community.home-assistant.io/t/home-assistant-supervisor-based-installations-fail-after-docker-upgrade/676477

**Comment by StephensGraeme** [comment]
Thanks, I'll give it a go

**Comment by MattWestb** [comment]
Supervised HA running ZHA is working OK with docker 25.01 that is released in Ubuntu and Debrian for most platforms so skip downgrading and update to the new release.

**Comment by smoltron** [comment]
It seems this is not yet over. InfluxDb export does not connect with 25.0.1. I downgraded again to 24.0.8 and now the data flows again. There is something about it here: https://github.com/home-assistant/core/issues/108810

**Comment by MattWestb** [comment]
I was getting the same problems with then installing 25.X of all my test and the production system and its need being fixed in HA side then its not allocating the network OK and 25.X is more strict with network recourse and we have putting one issue for it as you have seen.

**Comment by frenck** [comment]
This was an known issue in Docker upstream and has been corrected in the latest versions of Docker.

Closing this on our end, as it isn't an issue on this end.

..?Frenck
