### ISSUE TITLE
Broken Link in OpenThread Border Router Documentation - nRF52840

### ISSUE THREAD

**Issue by IIAIronWolf** [home-assistant/addons#3441]
### Describe the issue you are experiencing

There is a link "[This article](https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/matter/openthread_rcp_nrf_dongle.html) outlines..." that no longer exists on the nordic semi website. 
I just got an nRF52840 for use as a thread border router with the OpenThread Border Router add-on and cannot figure out how to get it working with this link missing. I used wayback machine to find what that link used to point to and nothing seems to work for flashing the device.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

CEC Scanner

### What is the version of the add-on?

2.4.4

### Steps to reproduce the issue

In Settings > Add-Ons > OpenThread Border Router > Documentation, click the link called 'This article' and see 'Page not found'

### System Health information

NA

### Anything in the Supervisor logs that might be useful for us?

```txt
NA
```

### Anything in the add-on logs that might be useful for us?

```txt
NA
```

**Comment by MattWestb** [comment]
I  have seen many example for Nordic setup on the open thread pages then its one reference design so shall being easy finding,
What is you missing is it the firmware build / flashing or the config for the host system ?
