### ISSUE TITLE
Activating OpenThread Border Router kills Sky Connect

### ISSUE THREAD

**Issue by PatrickSteiner** [home-assistant/addons#3445]
### Describe the issue you are experiencing

I have a working Zigbee2MQTT setup with the SkyConnect USB stick. When activating OpenThread Border Router, Zigbee2MQTT stops working with the following error

[07:23:14] INFO: Preparing to start...
[07:23:14] INFO: Socat not enabled
[07:23:16] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:info  2024-02-03 07:23:20: Logging to console and directory: '/config/zigbee2mqtt/log/2024-02-03.07-23-20' filename: log.txt
Zigbee2MQTT:info  2024-02-03 07:23:20: Starting Zigbee2MQTT version 1.35.2 (commit #unknown)
Zigbee2MQTT:info  2024-02-03 07:23:20: Starting zigbee-herdsman (0.33.5)
Zigbee2MQTT:error 2024-02-03 07:24:30: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2024-02-03 07:24:30: Failed to start zigbee
Zigbee2MQTT:error 2024-02-03 07:24:30: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2024-02-03 07:24:30: Exiting...
Zigbee2MQTT:error 2024-02-03 07:24:30: Error: Failure to connect
    at Ezsp.connect (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:364:19)
    at Driver.startup (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/driver.ts:158:13)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/app/lib/zigbee.ts:60:27)
    at Controller.start (/app/lib/controller.ts:106:27)
    at start (/app/index.js:107:5)

OpenThread Border Router Logs shows

s6-rc: info: service otbr-agent-configure successfully started
otbr-agent[183]: 00:00:00.704 [N] RoutingManager: Local on-link prefix: fdba:eca3:d0a1:ab53::/64
otbr-agent[183]: 00:00:00.718 [N] Mle-----------: Role disabled -> detached
otbr-agent[183]: 00:00:00.755 [N] Platform------: [netif] Changing interface state to up.
otbr-agent[183]: 00:00:00.767 [W] Platform------: [netif] ADD [U] fe80:0:0:0:4c81:e398:6c90:1a2e failed (InvalidArgs)
otbr-agent[183]: 00:00:00.767 [W] Platform------: [netif] Failed to process event, error:InvalidArgs
otbr-agent[183]: 00:00:00.770 [W] Platform------: [netif] ADD [U] fd82:4317:95bf:2a31:b03b:6e3d:7e0d:5804 failed (InvalidArgs)
otbr-agent[183]: 00:00:00.770 [W] Platform------: [netif] Failed to process event, error:InvalidArgs
otbr-agent[183]: 00:00:00.770 [W] Platform------: [netif] Failed to process request#5: No such process

Only manually flashing firmware `Zigbee (EZSP) 7.3.2.0 build 212 ` to replace the automatically flashed `OpenThread (RCP) SL-OPENTHREAD/2.4.0.0_GitHub-7074a43e4` get Zigbee2MQTT back up-and-running.

Is this something on my side, the Add-on defect or the firmware?

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

CEC Scanner

### What is the version of the add-on?

2.4.5

### Steps to reproduce the issue

see detailed description

### System Health information

no repaires

### Anything in the add-on logs that might be useful for us?

```txt
see detailed description
```

**Comment by MattWestb** [comment]
Is it RCP / Multi protocol or NCP / EZSP firmware you have flashing ?
If RCP M2Z shall not using  the comport  of the dongle instead the network port from the multi protocol or its blocking the comport  for the RCP and nothing its working.
If NCP firmware you shall not starting the thread addon then its cant talking to the firmware (wrong type) and blocking the comport but M2Z shall using the comport and it shall working OK on the hardware side.

**Comment by PatrickSteiner** [comment]
@MattWestb I'm not flashing a new firmware to enable Multi Protocoll, this seems to be done by the Add-On itself ( at least this is what the documentation tells me ). 
I only flash  to get back to a working state. The flashing tools then tells me that I have **OpenThread (RCP) SL-OPENTHREAD/2.4.0.0_GitHub-7074a43e4** installed and I'm manually reverting to **Zigbee (EZSP) 7.3.2.0 build 212**

What would be the naming convention for the multi protocol network that I need to configure in Z2M and the Border Router add on? ... just so I don't screw-up again ...

**Comment by MattWestb** [comment]
NCP / EZSP i only Zigbee and you cant / shall not using thread or multi protocol with  it only ZHA or Z2M that shall using the comport or you is getting problems.

So NCP / EZSP native firmware => ZHA / M2Z direct comport and not thread support.
RCP / Multi protocol firmware => Thread and Zigbee one network port (9999) with MP addon.
RCP / Open Thread Boarder Router firmware => Only thread and no Zigbee with OTBR addon.

**Comment by PatrickSteiner** [comment]
@MattWestb I must admint, that as someone who is not at all that deep into all those firmwares and versions, I'm lost.
Is there a documentation somewhere that explains how I can use my sky connect for Z2M and Open Thread Border for my Matter/Thread Devices?

**Comment by MattWestb** [comment]
The Sky Connect guide for Multi protocol is the was getting both Thread and Zigbee for ZHA and M2Z all others you is only getting one of them from the dongle

**Comment by marcelveldt** [comment]
> @MattWestb I must admint, that as someone who is not at all that deep into all those firmwares and versions, I'm lost. Is there a documentation somewhere that explains how I can use my sky connect for Z2M and Open Thread Border for my Matter/Thread Devices?

Yes, you need a second skyconnect (or other zigbee dongle) in that case.
