### ISSUE TITLE
File Editor - Themes not working

### ISSUE THREAD

**Issue by bearhntr** [home-assistant/addons#3449]
### Describe the issue you are experiencing

I have made multiple attempts to change the 'theme' of the File Editor add-on.  None of them seem to make any difference.  I am trying to get one of the 'Dark' themes to work as the default white is quite harsh on my eyes.  So far every thing in my HA installation is in 'Dark Mode' except this add-on.  
 

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

CEC Scanner

### What is the version of the add-on?

Current version: 5.7.0

### Steps to reproduce the issue

1.  Open File Editor from sidebar
2.  Choose 'gear' icon in upper-right and choose 'Editor Settings'
3.  Scroll down to 'Theme' and locate the 'Dark' themes - choose one and SAVE
4.  The editor window will sometimes take the update, but the area around it never changes (see image)

![image](https://github.com/home-assistant/addons/assets/100164602/e053ea34-52b3-4c68-8ff1-783ee6d3439d)

...

## System Information

version | core-2024.1.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.74-haos
arch | x86_64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.5
-- | --
update_channel | stable
supervisor_version | supervisor-2024.01.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 93.8 GB
disk_used | 5.9 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Studio Code Server (5.15.0), Advanced SSH & Web Terminal (17.1.0), Log Viewer (0.17.0), File editor (5.7.0), Samba share (12.2.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | January 29, 2024 at 9:12 PM
-- | --
current_recorder_run | February 7, 2024 at 8:10 AM
estimated_db_size | 3.50 MiB
database_engine | mysql
database_version | 11.2.2

</details>

**Comment by frenck** [comment]
Themes and add-ons are not related to each other. Add-ons run other software packages inside Home Assistant, but they are not Home Assistant.

In this case, the software ran inside the File editor add-on is: hass-configurator.

You could try to request themable options with the upstream project. Once they release new versions, we will update the add-on as well.

../Frenck
