### ISSUE TITLE
No hardware menu to change channel when using non-Yellow/SkyConnect with Silicon Labs Multiprotocol enabled

### ISSUE THREAD

**Issue by mp15** [home-assistant/addons#3451]
### Describe the issue you are experiencing

There's a small oversight in channel configuration. When Silicon Labs Multiprotocol is enabled and you attempt to change the channel in ZHA or Threads integration you are told to change the channel in System->Hardware. Unfortunately if you are not using Home Assistant Yellow or SkyConnect, e.g. you are using ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2 with the correct firmware there is no option to change the channel in the Hardware menu. This leaves you in a rather sticky situation where if the ZHA and Threads integrations have disagreeing channels, you cannot change the channel to repair this.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Silicon Labs Multiprotocol

### What is the version of the add-on?

2.4.4

### Steps to reproduce the issue

1. Attempt to change channel in ZHA
2. Get told to change the channel in System -> Hardware
3. Go to System -> Hardware, find no option to change channel

## System Information

version | core-2024.2.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.1
os_name | Linux
os_version | 6.1.63-haos-raspi
arch | aarch64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1459
Downloaded Repositories | 2
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.5
-- | --
update_channel | beta
supervisor_version | supervisor-2024.01.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 233.8 GB
disk_used | 6.0 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Matter Server (5.0.4), Let's Encrypt (5.0.15), Terminal & SSH (9.8.1), Silicon Labs Multiprotocol (2.4.4)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
mode | auto-gen

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 1 February 2024 at 23:16
-- | --
current_recorder_run | 7 February 2024 at 20:03
estimated_db_size | 11.40 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

**Comment by mp15** [comment]
Closing as duplicate of #3124

**Comment by sywzy** [comment]
sorry https://github.com/home-assistant/addons/issues/3124 is not found
