### ISSUE TITLE
Deconz 6.23.0 fails to start with 'deconz: warning: unable to spawn ./run (waiting 60 seconds): Exec format error'

### ISSUE THREAD

**Issue by rexbron** [home-assistant/addons#3470]
### Describe the issue you are experiencing

After upgrading to Deconz add on 6.23.0, the add on fails to start.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

deCONZ

### What is the version of the add-on?

6.23.0

### Steps to reproduce the issue

1. Upgrade to Deconz 6.23.0
2. Attempt to start and fail. 
3. Note loading the webUI throws a 502 Bad Gateway message. 

Downgrading to 6.20.0 resolves the issue. 

## System Information

version | core-2024.2.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.1
os_name | Linux
os_version | 6.1.63-haos-raspi
arch | aarch64
timezone | America/Toronto
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.32.1
Stage | running
Available Repositories | 1391
Downloaded Repositories | 5

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.5
-- | --
update_channel | stable
supervisor_version | supervisor-2024.01.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 28.6 GB
disk_used | 11.3 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | deCONZ (6.20.0), Terminal & SSH (9.9.0), UniFi Network Application (3.0.3), Nextcloud Backup (0.17.7), ESPHome (2023.12.9)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 2
views | 3
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | February 14, 2024 at 4:26 PM
-- | --
current_recorder_run | February 16, 2024 at 9:51 AM
estimated_db_size | 190.77 MiB
database_engine | mysql
database_version | 10.5.23

</details>

### Anything in the add-on logs that might be useful for us?

```txt
deconz: warning: unable to spawn ./run (waiting 60 seconds): Exec format error
```

**Comment by dimab0** [comment]
Hmm, I have the same issue. Seems HA auto-updated something, and I can no longer access UI or port 8123. I do see supervisor log at 4357 logging the following, the last 4 lines repeating endlessly. But...I don't know what is nor do I have 'deconz'. I don't have that addon...

Were you able to resolve?

`s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/udev.sh
cont-init: info: /etc/cont-init.d/udev.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun supervisor (no readiness notification)
services-up: info: copying legacy longrun watchdog (no readiness notification)
s6-supervise watchdog: warning: unable to spawn ./run (waiting 60 seconds): Exec format error
s6-supervise supervisor: warning: unable to spawn ./run (waiting 60 seconds): Exec format error
s6-supervise watchdog: warning: unable to spawn ./run (waiting 60 seconds): Exec format error
s6-supervise supervisor: warning: unable to spawn ./run (waiting 60 seconds): Exec format error`

**Comment by rexbron** [comment]
Hi @dimab0,

I rolled back to the previous functioning add on version. No resolution yet. 
What hardware are you running?

**Comment by dimab0** [comment]
I am running HA on a RaspberryPi. I’m unable to connect to the device at
all so also unable to rollback. It’s refusing any connections.
Waiting to connect it to monitor to see if it will be responsive at all.

~Dimitry Braznichenko

**Comment by dimab0** [comment]
Raspberry SC15184 Pi 4 Model B 2019 Quad Core 64 Bit WiFi Bluetooth (2GB)

https://a.co/d/5EKiaIU


~Dimitry Braznichenko

**Comment by rexbron** [comment]
Not stale, still an issue.
