### ISSUE TITLE
IPv6 ULA RA sent by Silicon Multiprotocol's otbr-agent

### ISSUE THREAD

**Issue by meiser79** [home-assistant/addons#3473]
### Describe the issue you are experiencing

Hello,

The Matter Server addon sends IPv6 ULA RAs into my network so that all my LAN clients get an IPv6 ULA assigned. This introduced some IPv6 routing issues in my network.

Thanks a lot.
Regards,
meiser

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Debian

### Which add-on are you reporting an issue with?

Silicon Labs Multiprotocol

### What is the version of the add-on?

2.4.4

### Steps to reproduce the issue

Install the mentioned addons and check if your LAN clients receive a IPv6 ULA RA. It should come from the HA system.

## System Information

version | core-2024.2.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.1
os_name | Linux
os_version | 6.1.74-haos
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1393
Downloaded Repositories | 6

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.5
-- | --
update_channel | stable
supervisor_version | supervisor-2024.01.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 30.8 GB
disk_used | 7.8 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.4.0), Samba share (12.3.0), Matter Server (5.1.2), Silicon Labs Multiprotocol (2.4.4), Multipan Flasher (0.2.1), Zigbee2MQTT (1.35.3-1), NGINX Home Assistant SSL proxy (3.8.0), Terminal & SSH (9.9.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 1
views | 3
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 8. Februar 2024 um 06:14
-- | --
current_recorder_run | 16. Februar 2024 um 20:25
estimated_db_size | 47.99 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Additional information

I captured this with tcpdump on one of my systems:

18:31:09.980538 enp6s18 M   IP6 (flowlabel 0xba966, hlim 255, next-header ICMPv6 (58) payload length: 64) fe80::5054:ff:fe21:d987 > ff02::1: [icmp6 sum ok] ICMP6, router advertisement, length 64
        hop limit 0, Flags [none], pref medium, router lifetime 0s, reachable time 0ms, retrans timer 0ms
          prefix info option (3), length 32 (4): fd50:e100:5ba7:a155::/64, Flags [onlink, auto], valid time 1800s, pref. time 1800s
          route info option (24), length 16 (2):  fda3:cc59:d6e8:1::/64, pref=medium, lifetime=1800s
18:31:10.299604 enp6s18 Out IP6 (hlim 255, next-header ICMPv6 (58) payload length: 32) :: > ff02::1:ff21:d983: [icmp6 sum ok] ICMP6, neighbor solicitation, length 32, who has fd50:e100:5ba7:a155:5054:ff:fe21:d983
          unknown option (14), length 8 (1): 
          0x0000:  f146 8ee1 ec6d

**Comment by meiser79** [comment]
Reading https://community.home-assistant.io/t/the-state-of-matter/679508, I guess that it's your Matter concept to assign IPv6 ULA.

> Enable IPv6 on your home router and Home Assistant Operating System. You don’t need to get IPv6 from your internet provider, as the Matter devices operate locally. But you do need to make sure it’s enabled on your home network.


Would it be possible to have an option to disable IPv6 ULA if the network interface has a valid IPv6 GUA? As this means that there is a working IPv6 network environment.

**Comment by meiser79** [comment]
It's the otbr-agent of the Silicon Multiprotocol addon.

`otbr-agent[308]: 00:00:00.051 [N] RoutingManager: Local on-link prefix: fd50:e100:5ba7:a155::/64`

**Comment by agners** [comment]
@meiser79 this is the default behavior we inherit from the OpenThread border router we deploy in the Silicon Labs Multiprotocol add-on.

I do have a GUA available in my network too, but I haven't noticed problems so far. I do use the vanilla OpenThread Border Router add-n though.

I do have a similar announcement from the routing manager:

```
otbr-agent[185]: 00:00:00.035 [N] RoutingManager: Local on-link prefix: fd2f:7fe0:dc78:8e15::/64
```

However, it seems that the prefix is not active, it does not get announced on my network. Jumping inside the OTBR add-on container `docker exec -it addon_core_openthread_border_router /bin/bash` also confirms this:

```
root@ha-shelf2-yellow:/usr/src# ot-ctl br onlinkprefix
Local: fd2f:7fe0:dc78:8e15::/64
Favored: 2a02:abc:abc::/64
```

Btw, because we continue to have stability problems with the Multiprotocol approach we halted development of this add-on. I'd recommend using the dedicated Thread variant if you are still interested in Thread (the OpenThread Border Router add-on, see also the new [Enable Thread support](https://skyconnect.home-assistant.io/procedures/enable-thread/) documentation). The OpenThread Border Router shipped with that add-on is newer.

Can you check if this is reproducible with the OpenThread Border Router add-on? If so, can you check the output of the `ot-ctl br onlinkprefix` command?

**Comment by meiser79** [comment]
@agners Thanks a lot for the explanation! As I just wanted to be ready for Thread/Matter, but my current environment is Zigbee-based, I cannot switch to the Thread-only firmware on my Sonoff dongle.
As soon as I have my first Thread device, I'll check again.
