### ISSUE TITLE
Duck DNS IP not updating on change

### ISSUE THREAD

**Issue by L0bit0** [home-assistant/addons#3474]
### Describe the issue you are experiencing

Hi

I im using DUCK DNS for months, and realize IP is not updated on DuckDNS settings, so every time my External IP Change, i can not enter outside of my network, and had to manually update IP on Duck DNS

this is my configuration

> ![image](https://github.com/home-assistant/addons/assets/10359623/c64f0a80-cad3-404d-810f-fccd929cb62a)

and this is wht logs have
```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
# INFO: Using main config file /data/workdir/config
+ Account already registered!
[12:31:39] WARNING: 
[12:31:39] INFO: Renew certificate for domains: l0bit0ha.duckdns.org and aliases: 
# INFO: Using main config file /data/workdir/config
Processing l0bit0ha.duckdns.org
 + Signing domains...
 + Generating private key...
 + Generating signing request...
 + Requesting new certificate order from CA...
 + Received 1 authorizations URLs from the CA
 + Handling authorization for l0bit0ha.duckdns.org
 + 1 pending challenge(s)
 + Deploying challenge tokens...
ERROR: deploy_challenge hook returned with non-zero exit code
```

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### Which add-on are you reporting an issue with?

Duck DNS

### What is the version of the add-on?

1.15.0

### Steps to reproduce the issue

1.
2.
3.
...

## System Information

version | core-2024.2.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.1
os_name | Linux
os_version | 6.1.63-haos-raspi
arch | aarch64
timezone | Europe/Madrid
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1394
Downloaded Repositories | 42

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.5
-- | --
update_channel | stable
supervisor_version | supervisor-2024.01.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 439.4 GB
disk_used | 55.1 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Node-RED (17.0.7), Duck DNS (1.15.0), Terminal & SSH (9.9.0), Grafana (9.1.3), Studio Code Server (5.15.0), DHCP server (1.3.1), MariaDB (2.6.1), InfluxDB (5.0.0), Home Assistant Google Drive Backup (0.112.1), phpMyAdmin (0.9.1), ESPHome (2023.12.9), Z-Wave JS (0.4.4), Samba share (12.3.0), Log Viewer (0.17.0), Z-Wave JS UI (3.3.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 9
-- | --
resources | 32
views | 59
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | January 27, 2023 at 7:17 PM
-- | --
current_recorder_run | February 12, 2024 at 11:03 AM
estimated_db_size | 6096.00 MiB
database_engine | mysql
database_version | 10.6.12

</details>

<details><summary>Sonoff</summary>

version | 3.5.4 (a4a8c5f)
-- | --
cloud_online | 3 / 3
local_online | 3 / 3

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Anything in the Supervisor logs that might be useful for us?

```txt
this is all about Duck DNS on the log

24-02-17 12:20:45 INFO (SyncWorker_1) [supervisor.docker.manager] Stopping addon_core_duckdns application
24-02-17 12:20:50 INFO (SyncWorker_1) [supervisor.docker.manager] Cleaning addon_core_duckdns application
24-02-17 12:20:51 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-duckdns with version 1.15.0
24-02-17 12:31:30 INFO (SyncWorker_6) [supervisor.docker.manager] Stopping addon_core_duckdns application
24-02-17 12:31:35 INFO (SyncWorker_6) [supervisor.docker.manager] Cleaning addon_core_duckdns application
24-02-17 12:31:36 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-duckdns with version 1.15.0
```

### Anything in the add-on logs that might be useful for us?

```txt
Duck DNS
[12:31:39] INFO: Renew certificate for domains: l0bit0ha.duckdns.org and aliases: 
Processing l0bit0ha.duckdns.org
 + Handling authorization for l0bit0ha.duckdns.org
```

**Comment by hunhejj** [comment]
Same here. What I find strange is this line in the duckdns logs:
```
[12:31:39] WARNING: 
```

I also see that in my logs.

**Comment by L0bit0** [comment]
Anyone else with the same issue?

For people, it is working, can you share how do you have configured?

Any alternative to DuckDNS?

thanks

**Comment by TheAnT1979** [comment]
i have the same issue

`# INFO: Using main config file /data/workdir/config
Processing vdba-ha.duckdns.org
 + Signing domains...
 + Generating private key...
 + Generating signing request...
 + Requesting new certificate order from CA...
 + Received 1 authorizations URLs from the CA
 + Handling authorization for vdba-ha.duckdns.org
 + 1 pending challenge(s)
 + Deploying challenge tokens...
ERROR: deploy_challenge hook returned with non-zero exit code`

**Comment by L0bit0** [comment]
Hi

Anyone can help wit this or let us know any other door we can call?
Anyone knows an alternate system

Thanks in advance

**Comment by Haary3** [comment]
Same Problem here, just an empty Warning

**Comment by johnterickson** [comment]
On the add-on's Configuration page, do the three dots in the upper right and select `Edit in YAML`.  My token had an extra space in it.

**Comment by L0bit0** [comment]
same to me!  crazy...

I will try to reset my router and force external IP change to confirm.

**Comment by Hellchampion** [comment]
Same issue

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service duckdns: starting
s6-rc: info: service duckdns successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
# INFO: Using main config file /data/workdir/config
+ Generating account key...
+ Registering account key with ACME server...
+ Fetching account URL...
+ Done!
[10:59:49] INFO: Starting DuckDNS...
[10:59:49] WARNING: 
[10:59:49] INFO: Renew certificate for domains: hellchampion.duckdns.org and aliases: 
# INFO: Using main config file /data/workdir/config
 + Creating chain cache directory /data/workdir/chains
Processing hellchampion.duckdns.org
 + Creating new directory /data/letsencrypt/hellchampion.duckdns.org ...
 + Signing domains...
 + Generating private key...
 + Generating signing request...
 + Requesting new certificate order from CA...
 + Received 1 authorizations URLs from the CA
 + Handling authorization for hellchampion.duckdns.org
 + 1 pending challenge(s)
 + Deploying challenge tokens...
ERROR: deploy_challenge hook returned with non-zero exit code
[11:04:59] WARNING:

**Comment by systemacasale** [comment]
> On the add-on's Configuration page, do the three dots in the upper right and select `Edit in YAML`. My token had an extra space in it.

Thank you, I was going crazy :-)
