### ISSUE TITLE
change log level

### ISSUE THREAD

**Issue by nicolasimeoni** [home-assistant/addons#3478]
### Describe the issue you are experiencing

I have set the log level of Home Assistant to "ERROR" but the file editor addon fills up my linux log of this type of entries
INFO:2024-02-21 00:26:45,853:hass_configurator.configurator:127.0.0.1 - "GET / HTTP/1.1" 200 Is it possible to change the log level of the addon?

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### Which add-on are you reporting an issue with?

File editor

### What is the version of the add-on?

5.8.0

### Steps to reproduce the issue

1. Activate the addon
2. wait some minutes
3. see the system log
...

## System Information

version | core-2024.2.2
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.1
os_name | Linux
os_version | 6.6.16-current-sunxi64
arch | aarch64
timezone | Europe/Rome
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 12 (bookworm)
-- | --
update_channel | stable
supervisor_version | supervisor-2024.01.1
agent_version | 1.5.1
docker_version | 25.0.3
disk_total | 14.0 GB
disk_used | 6.8 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | ESPHome (2023.12.9), File editor (5.8.0), Glances (0.21.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 0
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 10 febbraio 2024 alle ore 18:19
-- | --
current_recorder_run | 20 febbraio 2024 alle ore 01:07
estimated_db_size | 10.58 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

**Comment by avandorp** [comment]
We probably should figure out what part of the system is accessing the file editor every half a minute.

**Comment by LupinIII** [comment]
Any idea what is causing this? It's still happening.
(Home Assistant OS, Core 2025.11.3)
