### ISSUE TITLE
Piper: missing en_US-hfc_female-medium

### ISSUE THREAD

**Issue by thatso** [home-assistant/addons#3480]
### Describe the issue you are experiencing

The voice model `en_US-hfc_female-medium` is not selectable in the Piper UI.
Trying to add it in YAML mode results in this error message which confirms that it is not an option:

> Failed to save add-on configuration, value must be one of ['ar_JO-kareem-medium', 'ca-upc_ona-x-low', 'ca-upc_pau-x-low', 'ca_ES-upc_ona-medium', 'ca_ES-upc_ona-x_low', 'ca_ES-upc_pau-x_low', 'cs_CZ-jirka-low', 'cs_CZ-jirka-medium', 'da-nst_talesyntese-medium', 'da_DK-talesyntese-medium', 'de-eva_k-x-low', 'de-karlsson-low', 'de-kerstin-low', 'de-pavoque-low', 'de-ramona-low', 'de-thorsten-low', 'de_DE-eva_k-x_low', 'de_DE-karlsson-low', 'de_DE-kerstin-low', 'de_DE-pavoque-low', 'de_DE-ramona-low', 'de_DE-thorsten-high', 'de_DE-thorsten-low', 'de_DE-thorsten-medium', 'de_DE-thorsten_emotional-medium', 'el-gr-rapunzelina-low', 'el_GR-rapunzelina-low', 'en-gb-alan-low', 'en-gb-southern_english_female-low', 'en-us-amy-low', 'en-us-danny-low', 'en-us-kathleen-low', 'en-us-lessac-low', 'en-us-lessac-medium', 'en-us-libritts-high', 'en-us-ryan-high', 'en-us-ryan-low', 'en-us-ryan-medium', 'en_GB-alan-low', 'en_GB-alan-medium', 'en_GB-alba-medium', 'en_GB-aru-medium', 'en_GB-jenny_dioco-medium', 'en_GB-northern_english_male-medium', 'en_GB-semaine-medium', 'en_GB-southern_english_female-low', 'en_GB-vctk-medium', 'en_US-amy-low', 'en_US-amy-medium', 'en_US-arctic-medium', 'en_US-danny-low', '**en_US-hfc_male-medium**', 'en_US-joe-medium', 'en_US-kathleen-low', 'en_US-kusal-medium', 'en_US-l2arctic-medium', 'en_US-lessac-high', 'en_US-lessac-low', 'en_US-lessac-medium', 'en_US-libritts-high', 'en_US-libritts_r-medium', 'en_US-ryan-high', 'en_US-ryan-low', 'en_US-ryan-medium', 'es-carlfm-x-low', 'es-mls_10246-low', 'es-mls_9972-low', 'es_ES-carlfm-x_low', 'es_ES-davefx-medium', 'es_ES-mls_10246-low', 'es_ES-mls_9972-low', 'es_ES-sharvard-medium', 'es_MX-ald-medium', 'fi-harri-low', 'fi_FI-harri-low', 'fi_FI-harri-medium', 'fr-gilles-low', 'fr-mls_1840-low', 'fr-siwis-low', 'fr-siwis-medium', 'fr_FR-gilles-low', 'fr_FR-mls_1840-low', 'fr_FR-siwis-low', 'fr_FR-siwis-medium', 'fr_FR-upmc-medium', 'hu_HU-anna-medium', 'hu_HU-berta-medium', 'hu_HU-imre-medium', 'is-bui-medium', 'is-salka-medium', 'is-steinn-medium', 'is-ugla-medium', 'is_IS-bui-medium', 'is_IS-salka-medium', 'is_IS-steinn-medium', 'is_IS-ugla-medium', 'it-riccardo_fasol-x-low', 'it_IT-riccardo-x_low', 'ka_GE-natia-medium', 'kk-iseke-x-low', 'kk-issai-high', 'kk-raya-x-low', 'kk_KZ-iseke-x_low', 'kk_KZ-issai-high', 'kk_KZ-raya-x_low', 'lb_LU-marylux-medium', 'ne-google-medium', 'ne-google-x-low', 'ne_NP-google-medium', 'ne_NP-google-x_low', 'nl-mls_5809-low', 'nl-mls_7432-low', 'nl-nathalie-x-low', 'nl-rdh-medium', 'nl-rdh-x-low', 'nl_BE-nathalie-medium', 'nl_BE-nathalie-x_low', 'nl_BE-rdh-medium', 'nl_BE-rdh-x_low', 'nl_NL-mls_5809-low', 'nl_NL-mls_7432-low', 'no-talesyntese-medium', 'no_NO-talesyntese-medium', 'pl-mls_6892-low', 'pl_PL-darkman-medium', 'pl_PL-gosia-medium', 'pl_PL-mc_speech-medium', 'pl_PL-mls_6892-low', 'pt-br-edresson-low', 'pt_BR-edresson-low', 'pt_BR-faber-medium', 'pt_PT-tugão-medium', 'ro_RO-mihai-medium', 'ru-irinia-medium', 'ru_RU-denis-medium', 'ru_RU-dmitri-medium', 'ru_RU-irina-medium', 'ru_RU-ruslan-medium', 'sk_SK-lili-medium', 'sr_RS-serbski_institut-medium', 'sv_SE-nst-medium', 'sw_CD-lanfrica-medium', 'tr_TR-dfki-medium', 'tr_TR-fahrettin-medium', 'uk-lada-x-low', 'uk_UA-lada-x_low', 'uk_UA-ukrainian_tts-medium', 'vi-25hours-single-low', 'vi-vivos-x-low', 'vi_VN-25hours_single-low', 'vi_VN-vais1000-medium', 'vi_VN-vivos-x_low', 'zh-cn-huayan-x-low', 'zh_CN-huayan-medium', 'zh_CN-huayan-x_low']. **Got {'voice': 'en_US-hfc_female-medium'**, 'speaker': 0, 'length_scale': 1, 'noise_scale': 0.667, 'noise_w': 0.333, 'max_piper_procs': 1, 'debug_logging': False, 'update_voices': True}

According to [piper-voices](https://huggingface.co/rhasspy/piper-voices/tree/v1.0.0/en/en_US/hfc_female/medium) it was added 4 months ago.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Piper

### What is the version of the add-on?

1.4.0

### Steps to reproduce the issue

1. open Add-ons > Piper > Configuration
2. try to select the voice model `en_US-hfc_female-medium`

### System Health information

There are currently no repairs available

### Anything in the Supervisor logs that might be useful for us?

```txt
(nothing related)
```

**Comment by DrTechdom** [comment]
I also have the same issue even after reloading the add-on and the integration. Hfc_female shows available in the assistant settings but not under the Piper add-on.
![Screenshot_20240225-185935](https://github.com/home-assistant/addons/assets/32243922/027b2cdc-76e4-414e-9b59-39de561ac79e)


![Screenshot_20240225-190015](https://github.com/home-assistant/addons/assets/32243922/e97fd155-173e-4d6c-a7eb-888820ac2270)

**Comment by MJHeijster** [comment]
For me it wasn't working in the beginning, after a "Reboot system", it was all available and working for me.

**Comment by DrTechdom** [comment]
Piper update 1.5.0 seems to have fixed it

**Comment by thatso** [comment]
Yes, with the latest Piper 1.5.0 its available.
