### ISSUE TITLE
MariaDB jemalloc issue on Raspberry Pi 5

### ISSUE THREAD

**Issue by errrrata** [home-assistant/addons#3503]
### Describe the issue you are experiencing

When running on Raspberry Pi 5, MariaDB addon refuses to start with the following errors in the log:

```
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
sh: out of memory
```

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### Which add-on are you reporting an issue with?

MariaDB

### What is the version of the add-on?

2.6.1

### Steps to reproduce the issue

1. install 'MariaDB' addon
2. attempt to start 'MariaDB' addon

## System Information

version | core-2024.3.0
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.1.0-rpi7-rpi-2712
arch | aarch64
timezone | Europe/Gibraltar
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4643
Installed Version | 1.33.0
Stage | running
Available Repositories | 1405
Downloaded Repositories | 54

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | March 19, 2024 at 01:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | false
remote_connected | false
alexa_enabled | false
google_enabled | true
remote_server | eu-central-1-2.ui.nabu.casa
certificate_status | ready
instance_id | d92a00abff4846a485bab0d746345f46
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 12 (bookworm)
-- | --
update_channel | stable
supervisor_version | supervisor-2024.02.1
agent_version | 1.6.0
docker_version | 25.0.3
disk_total | 468.9 GB
disk_used | 60.0 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | Google Assistant Webserver (0.0.4), ESPHome (2024.2.2), eWeLink Smart Home (1.4.3), Volvo2Mqtt (1.8.27), Zigbee2MQTT Proxy (0.2.0), Mosquitto broker (6.4.0), Matter Server (5.4.1), Zigbee2MQTT (1.36.0-1), Advanced SSH & Web Terminal (17.1.1), Whisper (1.0.2), Terminal & SSH (9.9.0), Studio Code Server (5.15.0), Piper (1.5.0), openWakeWord (1.10.0), OpenThread Border Router (2.5.0), Nginx Proxy Manager (1.0.1), Network UPS Tools (0.13.0), MariaDB (2.6.1), Let's Encrypt (5.0.15), chrony (3.0.1), Duck DNS (1.15.0), Grocy (0.21.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 6
-- | --
resources | 19
views | 9
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | March 6, 2024 at 22:16
-- | --
current_recorder_run | March 7, 2024 at 10:34
estimated_db_size | 2744.11 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Anything in the add-on logs that might be useful for us?

```txt
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
sh: out of memory
```

**Comment by b1ngfun** [comment]
Same issue.

**Comment by systempal** [comment]
`kernel=kernel8.img` at the end of /boot/firmware/config.txt

**Comment by b1ngfun** [comment]
> `kernel=kernel8.img` at the end of /boot/firmware/config.txt

Can I use this on raspberry os as well?

**Comment by systempal** [comment]
> > `kernel=kernel8.img` at the end of /boot/firmware/config.txt
> 
> Can I use this on raspberry os as well?

It works for me on a Raspberry 5 with Raspberry OS and Home Assistant supervised.

**Comment by RogerSelwyn** [comment]
Also me

**Comment by b1ngfun** [comment]
> > > `kernel=kernel8.img` at the end of /boot/firmware/config.txt
> 
> > 
> 
> > Can I use this on raspberry os as well?
> 
> 
> 
> It works for me on a Raspberry Pi 5 with Raspberry Pi OS and Home Assistant supervised.

Thanks, I have a same setup with you and it works!

**Comment by systempal** [comment]
With Addon Version 2.7.1 i'm able to remove the line
`kernel=kernel8.img`
from my config.txt and MariaDB starts correctly.

Any comment from developers ?

**Comment by RogerSelwyn** [comment]
> With Addon Version 2.7.1 i'm able to remove the line `kernel=kernel8.img` from my config.txt and MariaDB starts correctly.
> 
> Any comment from developers ?

This is true for me as well
