### ISSUE TITLE
External network access Let's Encrypt certificate not applied until reboot

### ISSUE THREAD

**Issue by jacobsvante** [home-assistant/addons#3512]
### Describe the issue you are experiencing

When using external network access with a TLS certificate provided by the Let's Encrypt add-on, renewed certificate doesn't get applied until after reboot.

Restarting Home Assistant isn't enough.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Let's Encrypt

### What is the version of the add-on?

5.0.15

### Steps to reproduce the issue

1. Set up external network access and point it to a domain that you own
2. Set up Let's Encrypt add-on to create certificates for this domain
3. Wait for several weeks until Let's Encrypt e-mails you about certificate renewal for this domain
4. Start Let's Encrypt add-on so that it renews the domain
5. Notice how the Expires At of the domain doesn't change

## System Information

version | core-2024.3.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.1.73-haos-raspi
arch | aarch64
timezone | Europe/Stockholm
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1400
Downloaded Repositories | 6

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.0
-- | --
update_channel | stable
supervisor_version | supervisor-2024.03.0
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 458.4 GB
disk_used | 22.0 GB
healthy | true
supported | true
board | yellow
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.4.0), Terminal & SSH (9.10.0), Let's Encrypt (5.0.15)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 1
views | 3
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | December 6, 2023 at 6:56 PM
-- | --
current_recorder_run | March 13, 2024 at 11:50 AM
estimated_db_size | 3293.54 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Comment by joeduvall4** [comment]
I encountered the same issue recently. I'm also running Home Assistant OS, in my case on Yellow hardware. 

I wonder if this is potentially an issue with certificate handling in Home Assistant OS or the frontend application, and if so, would opening an issue there would get more eyes on it? (I didn't look closely enough at the issue before I rebooted to fix it.)
