### ISSUE TITLE
Unable to log into Samba share

### ISSUE THREAD

**Issue by wolverdude** [home-assistant/addons#3518]
### Describe the issue you are experiencing

Until a couple days ago, I was able to access my Home Assistant files through Samba just fine, but then it stopped accepting my credentials. I checked that the username & password match exactly, but my Samba client (MacOS Finder) keeps saying that my credentials are being rejected.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Samba share

### What is the version of the add-on?

12.3.1

### Steps to reproduce the issue

I'm using the default username of `homeassistant`. I can share my password directly if needed.

I tried restarting the addon. I even tried uninstalling and reinstalling, but the issue persisted.

### System Health information

There are currently no repairs available

### Anything in the Supervisor logs that might be useful for us?

```txt
No
```

### Anything in the add-on logs that might be useful for us?

```txt
No
```

### Additional information

All my Samba addon settings are default except for Allowed Hosts, which I have configured for my local subnet/mask. I do not have any other Samba servers on my network that I'm aware of.

**Comment by Mediacj** [comment]
I have the same problem after a reinstall of my Macbook M1, account and password are right but login is rejected.

I use the notation smb://ipadres_ha in remote server as worked before.

**Comment by GenMurdock** [comment]
For me the issues is the same. I can reach by manually adding http://ipadress_ha to access servers, but via given "network" in Finder is states no connection possible.

**Comment by wolverdude** [comment]
Thanks for the pointers. It worked fine after I set up access through "network" first. This tip should probably be added to [the docs](https://github.com/home-assistant/addons/blob/d03fc1b/samba/DOCS.md). I'll put up a PR if I get around to it, anyone else should feel free to do it if I don't get to it first.
