### ISSUE TITLE
Cannot select es_MX-claude-high voice

### ISSUE THREAD

**Issue by dbustosrc** [home-assistant/addons#3534]
### Describe the issue you are experiencing

I want to select es_MX-claude-high voice in my addon configuration, but it doesn't appear as an option, I also tried to put the model name manually in YAML config but with this error:
`Failed to save add-on configuration, value must be one of ['ar_JO-kareem-low', 'ar_JO-kareem-medium', 'ca-upc_ona-x-low', 'ca-upc_pau-x-low', 'ca_ES-upc_ona-medium', 'ca_ES-upc_ona-x_low', 'ca_ES-upc_pau-x_low', 'cs_CZ-jirka-low', 'cs_CZ-jirka-medium', 'da-nst_talesyntese-medium', 'da_DK-talesyntese-medium', 'de-eva_k-x-low', 'de-karlsson-low', 'de-kerstin-low', 'de-pavoque-low', 'de-ramona-low', 'de-thorsten-low', 'de_DE-eva_k-x_low', 'de_DE-karlsson-low', 'de_DE-kerstin-low', 'de_DE-mls-medium', 'de_DE-pavoque-low', 'de_DE-ramona-low', 'de_DE-thorsten-high', 'de_DE-thorsten-low', 'de_DE-thorsten-medium', 'de_DE-thorsten_emotional-medium', 'el-gr-rapunzelina-low', 'el_GR-rapunzelina-low', 'en-gb-alan-low', 'en-gb-southern_english_female-low', 'en-us-amy-low', 'en-us-danny-low', 'en-us-kathleen-low', 'en-us-lessac-low', 'en-us-lessac-medium', 'en-us-libritts-high', 'en-us-ryan-high', 'en-us-ryan-low', 'en-us-ryan-medium', 'en_GB-alan-low', 'en_GB-alan-medium', 'en_GB-alba-medium', 'en_GB-aru-medium', 'en_GB-jenny_dioco-medium', 'en_GB-northern_english_male-medium', 'en_GB-semaine-medium', 'en_GB-southern_english_female-low', 'en_GB-vctk-medium', 'en_US-amy-low', 'en_US-amy-medium', 'en_US-arctic-medium', 'en_US-danny-low', 'en_US-hfc_female-medium', 'en_US-hfc_male-medium', 'en_US-joe-medium', 'en_US-kathleen-low', 'en_US-kusal-medium', 'en_US-l2arctic-medium', 'en_US-lessac-high', 'en_US-lessac-low', 'en_US-lessac-medium', 'en_US-libritts-high', 'en_US-libritts_r-medium', 'en_US-ryan-high', 'en_US-ryan-low', 'en_US-ryan-medium', 'es-carlfm-x-low', 'es-mls_10246-low', 'es-mls_9972-low', 'es_ES-carlfm-x_low', 'es_ES-davefx-medium', 'es_ES-mls_10246-low', 'es_ES-mls_9972-low', 'es_ES-sharvard-medium', 'es_MX-ald-medium', 'fa_IR-amir-medium', 'fa_IR-gyro-medium', 'fi-harri-low', 'fi_FI-harri-low', 'fi_FI-harri-medium', 'fr-gilles-low', 'fr-mls_1840-low', 'fr-siwis-low', 'fr-siwis-medium', 'fr_FR-gilles-low', 'fr_FR-mls-medium', 'fr_FR-mls_1840-low', 'fr_FR-siwis-low', 'fr_FR-siwis-medium', 'fr_FR-tom-medium', 'fr_FR-upmc-medium', 'hu_HU-anna-medium', 'hu_HU-berta-medium', 'hu_HU-imre-medium', 'is-bui-medium', 'is-salka-medium', 'is-steinn-medium', 'is-ugla-medium', 'is_IS-bui-medium', 'is_IS-salka-medium', 'is_IS-steinn-medium', 'is_IS-ugla-medium', 'it-riccardo_fasol-x-low', 'it_IT-riccardo-x_low', 'ka_GE-natia-medium', 'kk-iseke-x-low', 'kk-issai-high', 'kk-raya-x-low', 'kk_KZ-iseke-x_low', 'kk_KZ-issai-high', 'kk_KZ-raya-x_low', 'lb_LU-marylux-medium', 'ne-google-medium', 'ne-google-x-low', 'ne_NP-google-medium', 'ne_NP-google-x_low', 'nl-mls_5809-low', 'nl-mls_7432-low', 'nl-nathalie-x-low', 'nl-rdh-medium', 'nl-rdh-x-low', 'nl_BE-nathalie-medium', 'nl_BE-nathalie-x_low', 'nl_BE-rdh-medium', 'nl_BE-rdh-x_low', 'nl_NL-mls-medium', 'nl_NL-mls_5809-low', 'nl_NL-mls_7432-low', 'no-talesyntese-medium', 'no_NO-talesyntese-medium', 'pl-mls_6892-low', 'pl_PL-darkman-medium', 'pl_PL-gosia-medium', 'pl_PL-mc_speech-medium', 'pl_PL-mls_6892-low', 'pt-br-edresson-low', 'pt_BR-edresson-low', 'pt_BR-faber-medium', 'pt_PT-tugão-medium', 'ro_RO-mihai-medium', 'ru-irinia-medium', 'ru_RU-denis-medium', 'ru_RU-dmitri-medium', 'ru_RU-irina-medium', 'ru_RU-ruslan-medium', 'sk_SK-lili-medium', 'sl_SI-artur-medium', 'sr_RS-serbski_institut-medium', 'sv_SE-nst-medium', 'sw_CD-lanfrica-medium', 'tr_TR-dfki-medium', 'tr_TR-fahrettin-medium', 'tr_TR-fettah-medium', 'uk-lada-x-low', 'uk_UA-lada-x_low', 'uk_UA-ukrainian_tts-medium', 'vi-25hours-single-low', 'vi-vivos-x-low', 'vi_VN-25hours_single-low', 'vi_VN-vais1000-medium', 'vi_VN-vivos-x_low', 'zh-cn-huayan-x-low', 'zh_CN-huayan-medium', 'zh_CN-huayan-x_low']. Got {'voice': 'es_MX-claude-high', 'speaker': 0, 'length_scale': 1, 'noise_scale': 0.667, 'noise_w': 0.333, 'max_piper_procs': 4, 'debug_logging': False, 'update_voices': True}`

I've checked the voices.json file into the docker addon, and the option is in there.
```
"es_MX-claude-high": {
        "key": "es_MX-claude-high",
        "name": "claude",
        "language": {
            "code": "es_MX",
            "family": "es",
            "region": "MX",
            "name_native": "Español",
            "name_english": "Spanish",
            "country_english": "Mexico"
        },
        "quality": "high",
        "num_speakers": 1,
        "speaker_id_map": {},
        "files": {
            "es/es_MX/claude/high/es_MX-claude-high.onnx": {
                "size_bytes": 63122309,
                "md5_digest": "cb1966e0ff20ca3aa010f6c9a0ce296a"
            },
            "es/es_MX/claude/high/es_MX-claude-high.onnx.json": {
                "size_bytes": 4963,
                "md5_digest": "36882201922fabb409f18d284af3eddd"
            },
            "es/es_MX/claude/high/MODEL_CARD": {
                "size_bytes": 247,
                "md5_digest": "bca99dc9b9a6c8f2f8563d73d52c4a3b"
            }
        },
        "aliases": []
    },
```

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Piper

### What is the version of the add-on?

1.5

### Steps to reproduce the issue

1. Go to Addons in Home Assistant
2. Go to Piper addon
3. Open Configuration tab
4. Open Voice options

## System Information

version | core-2024.3.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.20-haos
arch | x86_64
timezone | America/Guayaquil
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4683
Installed Version | 1.34.0
Stage | running
Available Repositories | 1483
Downloaded Repositories | 58

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 15

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.1
-- | --
update_channel | stable
supervisor_version | supervisor-2024.03.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 30.8 GB
disk_used | 18.0 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Advanced SSH & Web Terminal (17.2.0), Studio Code Server (5.15.0), Mosquitto broker (6.4.0), Matter Server (5.4.1), Home Assistant Google Drive Backup (0.112.1), Whisper (2.0.0), openWakeWord (1.10.0), File editor (5.8.0), Network UPS Tools (0.13.0), Piper (1.5.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 36
views | 23
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | March 22, 2024 at 01:19
-- | --
current_recorder_run | March 30, 2024 at 14:25
estimated_db_size | 785.32 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Comment by lupa18** [comment]
Same here: 
`wyoming_piper.download.VoiceNotFoundError: es_MX-claude-high`
