### ISSUE TITLE
matter_server error message unclear to add device

### ISSUE THREAD

**Issue by barrelful** [home-assistant/addons#3535]
### Describe the issue you are experiencing

When an user tries to "Add Matter Device" from a MINIMAL version (from F-Droid for example) of the companion app on Android mobile phone it shows:

`You need to use the Home Assistant Companion app on your mobile phone to commission Matter devices`

Actually, the message does not especify it needs to be a FULL version from the companion app. It would be nice that the app shows it is a MINIMAL version and FULL is required in the message.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Matter Server

### What is the version of the add-on?

5.4.1

### Steps to reproduce the issue

1. Install the addon.
2. Install the companion app from F-Droid on an Android device.
3. Try to "Add Matter Device"

### System Health information

Irrelevant.

### Anything in the Supervisor logs that might be useful for us?

```txt
Irrelevant.
```

### Anything in the add-on logs that might be useful for us?

```txt
Irrelevant.
```

**Comment by p-brt** [comment]
Same probleme here. It was unclear to me whether it was a bug or not until I saw this issue.

**Comment by PureTryOut** [comment]
I don't usually have a device around with Google Services or the Play Store and I didn't even know there was a "minimal" and a "full" version of the app, so this message was _very_ confusing! This should really be clarified with a more obvious message.

And to be honest, I don't understand why this is a thing anyway. Do we really need a phone with Google Services installed (a company I'm actively trying to get rid of!) to setup Matter devices?!
