### ISSUE TITLE
New deCONZ version v2.26.3

### ISSUE THREAD

**Issue by dutch-erik** [home-assistant/addons#3540]
### Describe the issue you are experiencing

deCONZ version is outdated and thus doesn't have improvements made to several ZigBee device integrations, etc.

[https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/v2.26.3](url)

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

deCONZ

### What is the version of the add-on?

2.25.3

### Steps to reproduce the issue

Try to pair a device which support has been added for after 2.25.3

## System Information

version | core-2024.3.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.1.73-haos-raspi
arch | aarch64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1483
Downloaded Repositories | 58
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.1
-- | --
update_channel | stable
supervisor_version | supervisor-2024.03.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 116.5 GB
disk_used | 7.5 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (12.3.1), Samba Backup (5.2.0), File editor (5.8.0), Cloudflared (5.1.7), Spotify Connect (0.13.0), Terminal & SSH (9.10.0), deCONZ (6.23.0), AppDaemon (0.16.4)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 40
views | 27
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 21 March 2024 at 14:55
-- | --
current_recorder_run | 2 April 2024 at 16:55
estimated_db_size | 1311.05 MiB
database_engine | mysql
database_version | 10.11.2

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Comment by frenck** [comment]
This is an open source project, feel free to jump in and contribute an update.

(Technically, this is not an issue but a feature request for which we don't use or issue tracker).

../Frenck

**Comment by yan14** [comment]
Well, I created a pull request. https://github.com/home-assistant/addons/pull/3542

**Comment by dutch-erik** [comment]
@yan14 Thank you very much.
Hopefully this the PR will be picked up soon so new sensors can be added.

**Comment by woytekbode** [comment]
@yan14 Could you redo the pull request for Deconz v2.27.6?

See https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/v2.27.6. New release since last week. Hopefully we can now finally go to a new version and fix some of the Hue issues.

**Comment by yan14** [comment]
There is already a new one: https://github.com/home-assistant/addons/pull/3708

**Comment by woytekbode** [comment]
> There is already a new one: #3708

Cheers! Have not found that one. Can't wait!
