### ISSUE TITLE
File Editor search/replace unusable on Android due to field capture

### ISSUE THREAD

**Issue by TheWebMachine** [home-assistant/addons#3546]
### Describe the issue you are experiencing

When trying to use the Search/Replace modal on Android, either in Companion app or direct browser, every time you try to tap on the search controls, the search text field gets re-selected, the keyboard is raised, and the button action is ignored, making the function entirely unusable.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Debian

### Which add-on are you reporting an issue with?

File editor

### What is the version of the add-on?

5.8.0

### Steps to reproduce the issue

1. Open File Editor
2. Open any file
3. Choose search icon
4. type text and attempt to search multiple results with the buttons
...

## System Information

version | core-2024.4.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.20-haos
arch | x86_64
timezone | America/Chicago
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1471
Downloaded Repositories | 30
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | January 8, 2025 at 6:00 PM
relayer_connected | true
relayer_region | us-east-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | us-east-1-4.ui.nabu.casa
certificate_status | ready
instance_id | (redacted)
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.1
-- | --
update_channel | stable
supervisor_version | supervisor-2024.03.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 30.8 GB
disk_used | 19.1 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.8.0), Samba share (12.3.1), Advanced SSH & Web Terminal (17.2.0), ESPHome (2024.3.1), eWeLink Smart Home (1.4.3), Music Assistant BETA (2.0.0b130)

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 11
views | 22
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | March 30, 2024 at 9:12 AM
-- | --
current_recorder_run | April 3, 2024 at 8:07 PM
estimated_db_size | 779.83 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

<details><summary>Sonoff</summary>

version | 3.6.0 (8dd8af9)
-- | --
cloud_online | 4 / 4
local_online | 4 / 4

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Comment by TheWebMachine** [comment]
Anyone!?

**Comment by frenck** [comment]
Hi there @TheWebMachine 👋 

It seems like you want to report an issue with the software running inside the add-on, and not the add-on itself. Add-ons wrap existing software in an installable way, but do not maintain or develop the software inside of it.

In this case, that is hass-configurator. Please report this issue upstream with that project:

<https://github.com/danielperna84/hass-configurator>

Thanks! 👍 

../Frenck
