### ISSUE TITLE
Git Pull is returning 401 while trying to check Home-Assistant config

### ISSUE THREAD

**Issue by tcarrondo** [home-assistant/addons#3587]
### Describe the issue you are experiencing

Git pull addon is unable to check configuration and because of that unable to restart after config changes being fetched.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Git pull

### What is the version of the add-on?

7.14.1

### Steps to reproduce the issue

1. push some changes to config repo
2. wait for add-on Git pull to fetch those changes

### System Health information

There are currently no repairs available

### Anything in the add-on logs that might be useful for us?

```txt
(...)
[Info] Checking if something has changed...
[Info] Something has changed, checking Home-Assistant config...
time="2024-05-02T19:01:11Z" level=error msg="Unexpected server response. Status code: 401"
Unexpected server response. Status code: 401
[Error] Configuration updated but it does not pass the config check. Do not restart until this is fixed!
(...)
```

### Additional information

Going to: Developer tools > Check and restart
Configuration is valid, and restarting HA works as expected with the changes pushed to repo.

**Comment by andarotajo** [comment]
I'm experiencing the same issue. Not sure since when this has been happening though

**Comment by AleksejsC** [comment]
I have same issue. In supervisor logs:
`WARNING (MainThread) [supervisor.api.middleware.security] No API token provided for /core/check`

**Comment by norbertohenriques** [comment]
Any clues about what's causing this? I have my Home Assistant updated to the last version, and the error still remains there.
