### ISSUE TITLE
Issue with Letsencrypt and Gandi DNS

### ISSUE THREAD

**Issue by gtubhi** [home-assistant/addons#3590]
### Describe the issue you are experiencing

I have the latest Letsencrypt Addons (5.0.18), and I am getting the following error when trying to renew the certificate.
[06:28:45] INFO: Selected DNS Provider: dns-gandi
[06:28:45] INFO: Use propagation seconds: 60
[06:28:45] INFO: Use Gandi gandi_api_key
[06:28:45] INFO: Detecting existing certificate type for ha.5jcs.com
Saving debug log to /var/log/letsencrypt/letsencrypt.log
[06:28:48] INFO: Existing certificate using 'rsa' key type.
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Renewing an existing certificate for xx.xx.com
Error parsing credentials configuration '/data/dnsapikey': Duplicate keyword name at line 60.
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Let's Encrypt

### What is the version of the add-on?

5.0.18

### Steps to reproduce the issue

1.I click on "Start" to start the addon.
2.
3.
...

## System Information

version | core-2024.5.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.1.73-haos-raspi
arch | aarch64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4884
Installed Version | 1.34.0
Stage | running
Available Repositories | 1410
Downloaded Repositories | 13

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.04.4
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 116.8 GB
disk_used | 24.2 GB
healthy | true
supported | true
board | rpi5-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (12.3.1), Terminal & SSH (9.13.0), File editor (5.8.0), Let's Encrypt (5.0.18), UniFi Network Application (3.0.4), ESPHome (2024.4.2), Hey Ada! (1.2.0), Whisper (2.0.0), Piper (1.5.0), chrony (3.0.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 21
-- | --
resources | 5
views | 18
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | May 1, 2024 at 8:18 PM
-- | --
current_recorder_run | May 7, 2024 at 5:50 AM
estimated_db_size | 754.99 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

**Comment by evilny0** [comment]
I had the same issue, I fixed it by using a gandi "personal access token" instead of the deprecated api key.

**Comment by MiAutomations** [comment]
> 

Hello I'm also facing a similar issue, can you please give more details about how to fixe this ? 

Thank you

**Comment by gtubhi** [comment]
That worked. I also had to change gandi_api_key: to gandi_token: in the configuration. Thanks!
