### ISSUE TITLE
No longer able to retrieve password in HA

### ISSUE THREAD

**Issue by SB0519** [home-assistant/addons#3603]
### Describe the issue you are experiencing

There is now no way to retrieve password in HA to configure devices to connect to mqtt it is mentioned in this post.
https://community.home-assistant.io/t/lost-my-user-name-and-password-for-mosquitto-server/645913

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Mosquitto broker

### What is the version of the add-on?

6.4.0

### Steps to reproduce the issue

1. Settings>Devices and settings>MQTT
2. Configure
3. Re-configure MQTT
4. Show Password
5. Shows only "__**password_not_changed**__"
...

### System Health information

na

### Anything in the Supervisor logs that might be useful for us?

```txt
na
```

### Anything in the add-on logs that might be useful for us?

```txt
na
```

### Additional information

na

**Comment by mathieucarbou** [comment]
Use the Vs code plugin to open `/config/.storage/core.config_entries`
you should see an entry similar to this one

![image](https://github.com/home-assistant/addons/assets/61346/f323f31b-17b1-4b64-8645-029c59800aa2)
