### ISSUE TITLE
Add-on Dnsmasq fails to start after update to 1.8.0

### ISSUE THREAD

**Issue by koenraadhaedens** [home-assistant/addons#3609]
### Describe the issue you are experiencing

after update from 1.7.0 to 1.8.0 i got this error. Restoring backup to 1.7.0 makes it working again.

dnsmasq: bad option at line 10 of /etc/dnsmasq.conf
[13:25:45] WARNING: Halt add-on
s6-rc: info: service legacy-services successfully started
s6-rc: info: service legacy-services: stopping
[13:25:46] INFO: Service restart after closing
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Dnsmasq

### What is the version of the add-on?

1.8.0

### Steps to reproduce the issue

after update from 1.7.0 to 1.8.0 i got this error

### System Health information

N/A

### Anything in the Supervisor logs that might be useful for us?

```txt
N/a
```

### Anything in the add-on logs that might be useful for us?

```txt
dnsmasq: bad option at line 10 of /etc/dnsmasq.conf
[13:25:45] WARNING: Halt add-on
s6-rc: info: service legacy-services successfully started
s6-rc: info: service legacy-services: stopping
[13:25:46] INFO: Service restart after closing
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### Additional information

n/a

**Comment by antro31** [comment]
Same issue on my side. Reverted back to previous version.

**Comment by ScottG489** [comment]
Do we not even just spin up these add-ons once as part of our testing process?

**Comment by AquaMorph** [comment]
This issue seems bad because it seems like there is zero testing before pushing out to production. I created a new config from the documentation and also hit this error. Maybe this is something that can be improved for future releases.

**Comment by MKtuzi** [comment]
Hello. Is the problem fixed? Can someone please explain the solution? Thank you.

**Comment by cannondale0815** [comment]
Yes, seems fixed. Just update to latest version.

**Comment by MKtuzi** [comment]
Thank you. Sorry, I can't.. : 'AddonManager.install' blocked from execution, no host internet connection
I haven't seen any serious discussion about the problem, which is probably not just me. Something happened after upgrading dnsmasq to 1.8.0.... After restarting.... only NabuCasa, same error.. No Up or Dn grades.
I'll sort it out somehow.. Thanks.

**Comment by embed-3d** [comment]
> Thank you. Sorry, I can't.. : 'AddonManager.install' blocked from execution, no host internet connection I haven't seen any serious discussion about the problem, which is probably not just me. Something happened after upgrading dnsmasq to 1.8.0.... After restarting.... only NabuCasa, same error.. No Up or Dn grades. I'll sort it out somehow.. Thanks.

I had the same issues, after I updated to version 1.8.0 since my network relies on the dnsmasq service.

I basically reconfigured my network to not use dnsmasq as dns server and rebooted my homeassistant server (disconnect and reconnect the ethernet port should be also sufficient). Now an update to version 1.8.1 should be possible.
Afterwards I reconfigured my network again to use dnsmasq as dns server and everything worked again as expected.

**Comment by sairon** [comment]
Sorry everyone, this is completely my fault. While it would be nice to have a way to catch errors like this in CI before add-ons are pushed to production (which happens automatically on PR merge), I believe it wouldn't happen if someone else were reviewing the PR. I missed the wrong config entry name in the config and as I thought it's in overall a simple change, I just carelessly merged it. Next time I will make sure to test every change before merging add-on PRs.

**Comment by koenraadhaedens** [comment]
No worries! We appreciate all the hard work you put in. Mistakes happen, and it's all part of the learning process.
Your dedication and commitment are valued. Thank you for taking responsibility and for your continued efforts.
Keep up the great work!

**Comment by ScottG489** [comment]
Yeah absolutely no blame on anyone in particular. These things happen, so we should at least have some kind of sanity check testing as part of CI.
