### ISSUE TITLE
Zooz 800 Z-Wave-USB-Stick not working after update to V1.30

### ISSUE THREAD

**Issue by AuPaGri** [home-assistant/addons#3612]
### Describe the issue you are experiencing

Hi,
yesterday I updated my Zooz 800 Z-Wave USB-Stick (European version) from V1.20 to 1.30. Since than Z-Wave is working for some minutes after starting HA, than it stops and in the "800 Series USB controller status" I get lots of error messages, it changes from "switched to ready" to "switched to unresponsive" like every 10 seconds.
I downgraded to 1.20 and everything is working fine. Don't know, if this is a problem of the Z-Wave stick, Home Assistant OS or Z-Wave JS (0.5.0).

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Z-Wave JS

### What is the version of the add-on?

Z-Wave JS (0.5.0)

### Steps to reproduce the issue

1. Update Zooz 800 Z-Wave-USB-Stick to V1.30
2. Switch on HA
3. Wait and see
...

## System Information

version | core-2024.5.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.28-haos-raspi
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.3
-- | --
update_channel | stable
supervisor_version | supervisor-2024.05.1
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 28.5 GB
disk_used | 8.1 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.4.0), Terminal & SSH (9.14.0), Advanced SSH & Web Terminal (18.0.0), Z-Wave JS (0.5.0), File editor (5.8.0), VLC (0.3.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 0
views | 17
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 17. Mai 2024 um 15:16
-- | --
current_recorder_run | 25. Mai 2024 um 13:38
estimated_db_size | 703.14 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

**Comment by brenter** [comment]
Same issue here. Downgrade fixed it. Have no logs to share unfortunately.

**Comment by abominab** [comment]
You're lucky you were able to downgrade. Mine just got bricked trying to upgrade. Modal just closed around 3% and went dark after that. Quick 30 bucks down the drain.

**Comment by hey8you** [comment]
I have the same issue after updating to 1.30(US version). Im on the fence if I should try to downgrade it or not, lol. Mine has been going unresponsive after about 9+ hours.
