### ISSUE TITLE
Matter server: Primary interface CLI option not honored

### ISSUE THREAD

**Issue by thardie** [home-assistant/addons#3619]
### Describe the issue you are experiencing

Even when passing a network interface of "end0.9" via `--primary-interface`, the logs report 
```
[1717142348.044766][126:126] CHIP:DL: Got Ethernet interface: end0
[1717142348.045812][126:126] CHIP:DL: Found the primary Ethernet interface:end0
```
At the start of the logs, the container shows:

```
[00:58:49] INFO: Starting Matter Server...
[00:58:55] INFO: Using 'end0.9' as primary network interface.
```

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Matter Server

### What is the version of the add-on?

6.0.0

### Steps to reproduce the issue

1. Get an interface other than end0 to be default
2. Verify Default network under System->Settings->Network (in my case end0.9)
3. Start/restart addon_core_matter_server
4. Check the logs showing disagreeing network adapter names
...

## System Information

version | core-2024.5.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.1.73-haos-raspi
arch | aarch64
timezone | America/Los_Angeles
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4929
Installed Version | 1.32.1
Stage | running
Available Repositories | 1407
Downloaded Repositories | 10

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.05.1
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 916.8 GB
disk_used | 29.0 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.14.0), Studio Code Server (5.15.0), Home Assistant Google Drive Backup (0.112.1), Node-RED (17.0.12), Z-Wave JS UI (3.6.0), RTSPtoWeb - WebRTC (1.4.0), Mosquitto broker (6.4.1), Zigbee2MQTT (1.37.1-1), Matter Server (6.0.0), ESPHome (2023.12.9), Frigate (Full Access) (0.13.2), Silicon Labs Multiprotocol (2.4.5), Let's Encrypt (5.0.18), NGINX Home Assistant SSL proxy (3.9.0), Tesla HTTP Proxy (2.2.6)

</details>

<details><summary>Dashboards</summary>

dashboards | 6
-- | --
resources | 7
views | 8
mode | storage

</details>

<details><summary>Recorder</summary>

error | failed to load: unknown
-- | --

</details>

**Comment by mwolter805** [comment]
Hello,
I am having this issue too where the matter server is not honoring the "--primary-interface enp0s31f6.21" extra Matter Server argument. .21 is the vlan I would like the matter server to use as it's primary interface. 
 
The hub I wish to connect to via Matter is not trusted and therefore placed on a vlan isolated from the internet and also isolated other vlans. I have added a vlan to HA for the same vlan as the untrusted hub. I can ping the untrusted hub on its IPv6 link-local address, so I know HA has connectivity to it through this vlan. However when attempting to add the hub to the matter server it cannot connect. Reviewing the matter server logs I see the following
```
[17:13:25] INFO: Using 'enp0s31f6' as primary network interface.
```
and not enp0s31f6.21

**Comment by thardie** [comment]
> Hello, I am having this issue too where the matter server is not honoring the "--primary-interface enp0s31f6.21" extra Matter Server argument. .21 is the vlan I would like the matter server to use as it's primary interface.
> 
> The hub I wish to connect to via Matter is not trusted and therefore placed on a vlan isolated from the internet and also isolated other vlans. I have added a vlan to HA for the same vlan as the untrusted hub. I can ping the untrusted hub on its IPv6 link-local address, so I know HA has connectivity to it through this vlan. However when attempting to add the hub to the matter server it cannot connect. Reviewing the matter server logs I see the following
> 
> ```
> [17:13:25] INFO: Using 'enp0s31f6' as primary network interface.
> ```
> 
> and not enp0s31f6.21

I opened a PR to fix this and it was rejected with "We don't want to support complex networking situations". I ended up restructuring my network to accommodate this limitation. I still think it's very short-sighted.

**Comment by kingp0dd** [comment]
> > Hello, I am having this issue too where the matter server is not honoring the "--primary-interface enp0s31f6.21" extra Matter Server argument. .21 is the vlan I would like the matter server to use as it's primary interface.
> > The hub I wish to connect to via Matter is not trusted and therefore placed on a vlan isolated from the internet and also isolated other vlans. I have added a vlan to HA for the same vlan as the untrusted hub. I can ping the untrusted hub on its IPv6 link-local address, so I know HA has connectivity to it through this vlan. However when attempting to add the hub to the matter server it cannot connect. Reviewing the matter server logs I see the following
> > ```
> > [17:13:25] INFO: Using 'enp0s31f6' as primary network interface.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and not enp0s31f6.21
> 
> I opened a PR to fix this and it was rejected with "We don't want to support complex networking situations". I ended up restructuring my network to accommodate this limitation. I still think it's very short-sighted. I also won't ever open another PR to this project for that reason.

How did you restructure your network? Did you put HASS on IoT VLAN instead?

**Comment by KagoSergal** [comment]
> > I opened a PR to fix this and it was rejected with "We don't want to support complex networking situations". I ended up restructuring my network to accommodate this limitation. I still think it's very short-sighted. I also won't ever open another PR to this project for that reason.
> 
> How did you restructure your network? Did you put HASS on IoT VLAN instead?

I switched the primary untagged interface to be the IoT network, and then made a tagged VLAN for the regular network. This meant HASS then defaulted to the IoT network and works fine now.

**Comment by thardie** [comment]
> > I opened a PR to fix this and it was rejected with "We don't want to support complex networking situations". I ended up restructuring my network to accommodate this limitation. I still think it's very short-sighted. I also won't ever open another PR to this project for that reason.
> 
> How did you restructure your network? Did you put HASS on IoT VLAN instead?

I switched the primary untagged interface to be the IoT network, and then made a tagged VLAN for the regular network. This meant HASS then defaulted to the IoT network and works fine now.
