### ISSUE TITLE
OpenThread Border Router Network device only configuration could not be saved

### ISSUE THREAD

**Issue by drstil** [home-assistant/addons#3620]
### Describe the issue you are experiencing

I want to create a OpenThread Border Router with a Smlight SLZB-06M stick via ethernet on a Raspberry Pi 3B+. I have no serial device attached, so in the configuration of the Add-On nothing is shown under `Device`. But I set the connection as a `Network Device`. When I want to save the settings I got the following error message:

```
Fehler beim Speichern der Add-on Konfiguration, Missing required option 'device' in OpenThread Border Router (core_openthread_border_router). Got {'device': None, 'baudrate': '460800', 'flow_control': False, 'autoflash_firmware': False, 'otbr_log_level': 'notice', 'firewall': True, 'nat64': False, 'network_device': '192.168.1.107:6638'}
```

This is the configuration I want to save in YAML.
```
device: null
baudrate: "460800"
flow_control: false
autoflash_firmware: false
otbr_log_level: notice
firewall: true
nat64: false
network_device: 192.168.1.107:6638
``` 

How could I use this Add-On with an only ethernet bound device?

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

OpenThread Border Router

### What is the version of the add-on?

2.6.0

### Steps to reproduce the issue

1. Do. not attach any serial device to your HA Hardware. 
2. Configure OpenThread Border Router with network device.
3. Save the configuration.

## System Information

version | core-2024.5.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.28-haos-raspi
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | failed to load: timeout
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1396
Downloaded Repositories | 2
HACS Data | failed to load: timeout

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | failed to load: timeout
can_reach_cloud_auth | failed to load: timeout
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.3
-- | --
update_channel | stable
supervisor_version | supervisor-2024.05.1
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 469.3 GB
disk_used | 16.3 GB
healthy | true
supported | true
board | rpi3-64
supervisor_api | ok
version_api | failed to load: timeout
installed_addons | WireGuard (0.10.2), Advanced SSH & Web Terminal (18.0.0), Studio Code Server (5.15.0), Matter Server (6.0.0), Node-RED (17.0.12), Mosquitto broker (6.4.1), Increase Swap (1.1.3), NGINX Home Assistant SSL proxy (3.9.0), Samba share (12.3.1), OpenThread Border Router (2.6.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 0
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 28. Mai 2024 um 17:01
-- | --
current_recorder_run | 31. Mai 2024 um 13:38
estimated_db_size | 51.91 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

**Comment by Sam01101101** [comment]
Also interested in this, I dont believe this is possible yet. 

The OTB add on in HA is the rest API, the SLZB-06M is a coordinator which is required by the add on.

**Comment by tl-sl** [comment]
The addon works with SLZB-06M connected over network. However documentation was only just updated recently
https://github.com/home-assistant/addons/blob/master/openthread_border_router/DOCS.md

For it to work:
- You need to select a dummy device from the list of serial ports (doesnt matter which as this setting gets overwritten at runtime, with the network settings)
- You need to make sure to set baudrate to `460800` on the ZHA/Z2M page of slzb-06m SMLIGHT web ui

**Comment by drstil** [comment]
> The addon works with SLZB-06M connected over network. However documentation was only just updated recently https://github.com/home-assistant/addons/blob/master/openthread_border_router/DOCS.md
> 
> For it to work:
> 
> * You need to select a dummy device from the list of serial ports (doesnt matter which as this setting gets overwritten at runtime, with the network settings)
> * You need to make sure to set baudrate to `460800` on the ZHA/Z2M page of slzb-06m SMLIGHT web ui

I have no other real/dummy device than only this stick. And it works correctly over ethernet, if the stick is still attached to my hardware by USB/Serial. But I have to detach it to have it at another location, but then there is no device anymore. 
Is there a way to somehow simulate a serial device for this case?

**Comment by tl-sl** [comment]
How do you run HA? On both HAOS and Supervised, you should have a bunch of ports like `/dev/ttyS1`?

**Comment by drstil** [comment]
> How do you run HA? On both HAOS and Supervised, you should have a bunch of ports like `/dev/ttyS1`?

Only HAOS on Raspberry Pi 3+. Here is my device list:

![HomeAssistantOpenThreadBorderRouterDevices](https://github.com/home-assistant/addons/assets/34704471/1fb3b684-b913-4353-b514-a5a85f303fe3)

When I go into the HA Docker container, I got a lot more (but not in the device list of the thread router):

![Bildschirmfoto 2024-07-01 um 12 05 12](https://github.com/home-assistant/addons/assets/34704471/ece10d89-6fba-4ee5-bee7-eab4da45887c)

**Comment by tl-sl** [comment]
Not reaally sure about this, but do you have advanced mode enabled under your user settings? perhaps that is hiding them in the UI?

**Comment by drstil** [comment]
> Not reaally sure about this, but do you have advanced mode enabled under your user settings? perhaps that is hiding them in the UI?

Yes, I have enabled the advanced mode:
![Bildschirmfoto 2024-07-01 um 13 20 26](https://github.com/home-assistant/addons/assets/34704471/0df4ab9b-201e-4e76-bef9-ead28fb2915f)

**Comment by tl-sl** [comment]
Not sure then, why they are not showing.

**Comment by Sam01101101** [comment]
> > The addon works with SLZB-06M connected over network. However documentation was only just updated recently https://github.com/home-assistant/addons/blob/master/openthread_border_router/DOCS.md
> > For it to work:
> > 
> > * You need to select a dummy device from the list of serial ports (doesnt matter which as this setting gets overwritten at runtime, with the network settings)
> > * You need to make sure to set baudrate to `460800` on the ZHA/Z2M page of slzb-06m SMLIGHT web ui
> 
> I have no other real/dummy device than only this stick. And it works correctly over ethernet, if the stick is still attached to my hardware by USB/Serial. But I have to detach it to have it at another location, but then there is no device anymore. Is there a way to somehow simulate a serial device for this case?

Thanks for sharing, what port is your SLZB-06M operating on?

**Comment by drstil** [comment]
Do you know how the addon is getting the device list? With which code, so that we could check if there is maybe some kind of setting/restriction?

**Comment by tl-sl** [comment]
not exactly, it would be handled via the supervisor API I guess:

https://github.com/home-assistant/addons/blob/fd927750b334dcc957081bfee9cd7b2a0ae28b42/openthread_border_router/config.yaml#L40

From a quick look there is an example of device filtering in the Supervisor tests:

https://github.com/home-assistant/supervisor/blob/130efd340c312657c699e3bdcd66a55eb51a0db6/tests/hardware/test_module.py#L127

**Comment by tl-sl** [comment]
no its not possible to disable the device check, due to the hack used to make the device setting visible even when it is unused.

**Comment by manueldziuba** [comment]
@drstil : you seem to be a German user, like me 😉. Please let us stay in contact, keeping us updated with our achievements ☺️

**Comment by Brettk80** [comment]
Same issue running this on PI4, with Core
2024.12.0
Supervisor
2024.11.4
Operating System
14.0
Frontend
20241127.4

I cannot see a border controller, cannot connect device over ethernet on a dummy port, cant see a list of ports, cant use device as described.  Junk.

**Comment by yboujraf** [comment]
I am using Proxmox with HAOS (no raspberry pi) and the "OpenThread Border Router" can't access to network instead of USB ?

And if I follow the tuto [here](https://smlight.tech/manual/slzb-06/guide/thread-matter/), I see it is possible to assign network ?
![image](https://github.com/user-attachments/assets/65303068-1ef5-446c-b4d4-85b6ad7855f0)

on HAOS,

<img width="635" alt="image" src="https://github.com/user-attachments/assets/638f1165-a0e4-4b55-8721-5522e6109567" />

Any idea ?

Best Regards

**Comment by maltejahn** [comment]
@yboujraf I Have the same exact issue that i cant select any "network device". Do you had any luck installing the SLTB.06M Device?

I also run HAOS inside Proxmox -the only differenceis that i use a N100 Mainboard wich shouldnt make any difference with this error:

> 
> Core 2025.2.5
> Supervisor 2025.03.0
> Operating System 14.2
> Frontend 20250221.0

**Comment by yboujraf** [comment]
Dear @maltejahn 

Not yet fixed.

BR

**Comment by darkxst** [comment]
IF there are no ttyS1 like devices displayed to select (which afaik should only affect HAOS on rasp pi ). The easiest fix is to buy a cheap USB Serial adapter and use this as a physical "dummy" device.

**Comment by maltejahn** [comment]
![Image](https://github.com/user-attachments/assets/1e8cb026-aa68-4dc7-a581-df03387294ae)

**Comment by jcmk06270** [comment]
Exactly the same problem, unable to get the addon working with PI4 and a SLZB-MR1 that has Thread support. Real pity there is no way to override the serial port device issue because nowdays more and more users will be using network connected adapters. How can we get this issue opened again?

**Comment by MiAutomations** [comment]
I'm also facing this issue, I'm not able to save the configuration


![Image](https://github.com/user-attachments/assets/dc60b7d7-b476-451b-adad-55a5cf859820)

Is there any workarround to fix this? 

Thank you in advance

**Comment by tl-sl** [comment]
> Is there any workarround to fix this?

Just select one of the /dev/ttyS2 devices (this selection will get overriden by network settings)

**Comment by tl-sl** [comment]
> unable to get the addon working with PI4

On PI4, the uarts are not enabled by default, so you wont see the /dev/ttySx ports to select as dummy port. The easiest option here is to buy a cheap USB-UART adapter and use this for the dummy port selection. Otherwise you need to install dtbo to activate uarts.

**Comment by guppiy** [comment]
Hi All,

I have the problem that there isn't shown any device at all. Please help! Thank you

<img width="1063" height="1016" alt="Image" src="https://github.com/user-attachments/assets/185d4599-df20-478f-8692-3a6b899b3b06" />

**Comment by jbbandos** [comment]
> Hi All,
> 
> I have the problem that there isn't shown any device at all. Please help! Thank you
> <img alt="Image" width="1063" height="1016" src="https://private-user-images.githubusercontent.com/220498240/465623290-185d4599-df20-478f-8692-3a6b899b3b06.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTkzMTc2NDIsIm5iZiI6MTc1OTMxNzM0MiwicGF0aCI6Ii8yMjA0OTgyNDAvNDY1NjIzMjkwLTE4NWQ0NTk5LWRmMjAtNDc4Zi04NjkyLTNhNmI4OTliM2IwNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTAwMVQxMTE1NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYmFmNzNjMGZhNWQ0ZjdiMjRhY2YxOTEyNTkxODlkN2MwODczMzJkZTZmOWU0YzM5NzAxNWM0YjlkNmY5ZDY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.i5qGzR9GwlKvxKdprkyIc7T4EHsyWB-b5qUW4ER4A9Q">

Same issue, seems like a new one. Did you try editing the yaml and adding a "network_device: xxx.xxx.xxx.xxx:6638" line?
After I add it, I have the network device entry in the UI available again.

**Comment by D3strukt0r** [comment]
I also have a Raspberry Pi 4, and the following allows me to show the dummy devices
 
1. Open the `boot` partition of the SD card on your computer.
2. Open the `config.txt` file in a text editor.
3. Add the following line at the end of the file to enable UART:
   ```
   enable_uart=1
   ```

Before:

<img width="1124" height="768" alt="Image" src="https://github.com/user-attachments/assets/e090ddd2-f4c3-42f5-94c5-2e62ee1f1afb" />

After:

<img width="1045" height="795" alt="Image" src="https://github.com/user-attachments/assets/e6b994f4-d401-4d22-a354-c373a6a47102" />

Just remember there is this warning here https://github.com/home-assistant/addons/blob/master/openthread_border_router/DOCS.md about using Matter over IP instead of a direct USB connection

> [!WARNING]
> The OTBR expects the RCP connected radio to be on a reliable link such as
> UART or SPI. Using TCP/IP to reach a remote RCP radio breaks this assumption.
> If the TCP/IP connection fails, the OTBR will not shutdown cleanly and leave
> stale routes in your network. This will lead to Thread devices to be
> potentially unreachable for up to 30 minutes (route lifetime) even when other
> routers are available.
>
> The RCP protocol is not designed to be transferred over an IP network: It is
> a timing-sensitive protocol. You might experience Thread issues if your
> network link has excessive latencies. As Thread is networking capable,
> running a Thread border router on the system the RCP radio is plugged in is
> recommended.

**Comment by drstil** [comment]
```
enable_uart=1
```

Was for me only necessary on Raspberry Pi 3B+, on Raspberry Pi `/dev/ttyAMA10` already existed from default enabled built-in Bluetooth.

**Comment by MickM57** [comment]
Raspberry Pi4 using SLZB-MR1u.
Latest version of HA and SLZB-MR1 fully updated to latest stable as of 24th March 2026.
Adding enable_uart+1 to the boot partition config.txt showed and allowed me to select /dev/ttyS0 in the device tab
Which allowed me to save the Ip Address of the SLZB adaptor and enable thread.

Thanks to all the above for your help, it was driving me to distraction!
