### ISSUE TITLE
Add-ons silabs-multiprotocol cant‘ be pulled

### ISSUE THREAD

**Issue by DanielFujiwara** [home-assistant/addons#3646]
### Describe the issue you are experiencing

The silabs-multiprotocol component cannot be installed in add-ons，docker homeassistant/aarch64-addon-silabs-multiprotocol Each version cannot be pulled

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### Which add-on are you reporting an issue with?

CEC Scanner

### What is the version of the add-on?

latest

### Steps to reproduce the issue

1.intall Silicon Labs Multiprotocol
2.failed
3.docker pull homeassistant/aarch64-addon-silabs-multiprotocol:2.4.5 failed
...

### System Health information

Nothing

**Comment by DanielFujiwara** [comment]
![Uploading 截屏2024-06-17 14.56.09.png…]()

**Comment by DanielFujiwara** [comment]
![截屏2024-06-17 14 56 09](https://github.com/home-assistant/addons/assets/63831213/e21c227c-9b7e-4f69-9e2c-f0b74e132d39)

**Comment by ywj410** [comment]
have same problem

**Comment by vistalba** [comment]
Same problem with Let‘s Encrypt and EVCC addons.
