### ISSUE TITLE
Let’s encrypt update fails

### ISSUE THREAD

**Issue by vincedh** [home-assistant/addons#3655]
### Describe the issue you are experiencing

When running update from version 5.0.18 -> 5.0.19:

Can't install homeassistant/aarch64-addon-letsencrypt:5.0.19: 404 Client Error for http+docker://localhost/v1.45/images/create?tag=5.0.19&fromImage=homeassistant%2Faarch64-addon-letsencrypt&platform=linux%2Farm64: Not Found ("manifest for homeassistant/aarch64-addon-letsencrypt:5.0.19 not found: manifest unknown: manifest unknown")

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Let's Encrypt

### What is the version of the add-on?

5.0.18

### Steps to reproduce the issue

1. Click update
2. Error shows: Can't install homeassistant/aarch64-addon-letsencrypt:5.0.19: 404 Client Error for http+docker://localhost/v1.45/images/create?tag=5.0.19&fromImage=homeassistant%2Faarch64-addon-letsencrypt&platform=linux%2Farm64: Not Found ("manifest for homeassistant/aarch64-addon-letsencrypt:5.0.19 not found: manifest unknown: manifest unknown")

## System Information

version | core-2024.6.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.33-haos
arch | aarch64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4972
Installed Version | 1.34.0
Stage | running
Available Repositories | 1388
Downloaded Repositories | 4

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.4
-- | --
update_channel | stable
supervisor_version | supervisor-2024.06.0
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 27.2 GB
disk_used | 6.7 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | odroid-n2
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.8.0), Node-RED (17.0.13), Z-Wave JS (0.6.0), Terminal & SSH (9.14.0), Home Assistant Google Drive Backup (0.112.1), Let's Encrypt (5.0.18), Advanced SSH & Web Terminal (18.0.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 1
views | 16
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 11 juni 2024 om 13:49
-- | --
current_recorder_run | 21 juni 2024 om 15:42
estimated_db_size | 195.95 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

**Comment by caraar12345** [comment]
I was just having the same, then it updated to 5.0.21 which is working 🙌

**Comment by frenck** [comment]
As per above, please check for updates and next install/update to 5.0.21, which resolved the issue.

../Frenck
