### ISSUE TITLE
Open Thread Border Router - failing to load after upgrade to 2.8.0

### ISSUE THREAD

**Issue by clefus** [home-assistant/addons#3667]
### Describe the issue you are experiencing

Thread devices are all offline.  Checked Addon in HomeAssistant, it was not running.  When you try to start it, it eventually shuts back off.  Restarting system and/or addon etc. does not resolve.  The below cycles a few times before it gives up/times out.

Logs below.

Thanks in advance.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

OpenThread Border Router

### What is the version of the add-on?

2.8.0

### Steps to reproduce the issue

1. Upgrade Open Thread Border Router to 2.8.0.
2. I did not notice it at first, but then noticed all thread devices were offline - would go in and restart the addon - did not realize at first that the addon was not staying up and that the devices were not coming back up.
3. I tried downgrading back to Open Thread Border Router 2.7.0.  But I saw in 2.8.0 where it may have upgraded the Silicon Labs Multiprotocol.  It has the same log and is no longer running.  silicon labs flasher Addon is in a similar boat.
...

## System Information

version | core-2024.6.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.33-haos
arch | x86_64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4814
Installed Version | 1.34.0
Stage | running
Available Repositories | 1385
Downloaded Repositories | 16

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | July 18, 2024 at 8:00 PM
relayer_connected | true
relayer_region | us-east-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | false
remote_server | us-east-1-3.ui.nabu.casa
certificate_status | ready
instance_id | <>
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.4
-- | --
update_channel | stable
supervisor_version | supervisor-2024.06.2
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 234.0 GB
disk_used | 9.9 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.14.0), Matter Server (6.1.2), OpenThread Border Router (2.8.0), Home Assistant Google Drive Backup (0.112.1), Network UPS Tools (0.13.0), File editor (5.8.0), ESPHome (2024.6.3), openWakeWord (1.10.0), Advanced SSH & Web Terminal (18.0.0), Silicon Labs Multiprotocol (2.4.5), Silicon Labs Flasher (0.2.3)

</details>

<details><summary>Dashboards</summary>

dashboards | 9
-- | --
resources | 10
views | 15
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | June 17, 2024 at 1:23 AM
-- | --
current_recorder_run | June 27, 2024 at 2:51 AM
estimated_db_size | 165.61 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Anything in the Supervisor logs that might be useful for us?

```txt
2024-06-27 02:54:19.846 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-otbr with version 2.8.0
2024-06-27 02:54:26.473 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Silicon Labs Multiprotocol is failed, restarting...
2024-06-27 02:54:26.480 INFO (SyncWorker_2) [supervisor.docker.manager] Cleaning addon_core_silabs_multiprotocol application
2024-06-27 02:54:26.735 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-silabs-multiprotocol with version 2.4.5
2024-06-27 02:54:48.445 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-11067' coro=<Addon.watchdog_container() done, defined at /usr/src/supervisor/supervisor/addons/addon.py:1429> exception=AddonsJobError('Rate limit exceeded, more than 10 calls in 0:30:00')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 1443, in watchdog_container
    await self._restart_after_problem(event.state)
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 290, in wrapper
    raise on_condition(
supervisor.exceptions.AddonsJobError: Rate limit exceeded, more than 10 calls in 0:30:00
2024-06-27 02:54:55.458 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Silicon Labs Multiprotocol is failed, restarting...
2024-06-27 02:54:55.463 INFO (SyncWorker_3) [supervisor.docker.manager] Cleaning addon_core_silabs_multiprotocol application
2024-06-27 02:54:55.654 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-silabs-multiprotocol with version 2.4.5
2024-06-27 02:55:24.404 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Silicon Labs Multiprotocol is failed, restarting...
2024-06-27 02:55:24.410 INFO (SyncWorker_6) [supervisor.docker.manager] Cleaning addon_core_silabs_multiprotocol application
2024-06-27 02:55:24.643 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-silabs-multiprotocol with version 2.4.5
2024-06-27 02:55:53.332 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-11392' coro=<Addon.watchdog_container() done, defined at /usr/src/supervisor/supervisor/addons/addon.py:1429> exception=AddonsJobError('Rate limit exceeded, more than 10 calls in 0:30:00')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 1443, in watchdog_container
    await self._restart_after_problem(event.state)
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 290, in wrapper
    raise on_condition(
supervisor.exceptions.AddonsJobError: Rate limit exceeded, more than 10 calls in 0:30:00
```

### Anything in the add-on logs that might be useful for us?

```txt
-----------------------------------------------------------
 Add-on: OpenThread Border Router
 OpenThread Border Router add-on
-----------------------------------------------------------
 Add-on version: 2.8.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 12.4  (amd64 / generic-x86-64)
 Home Assistant Core: 2024.6.4
 Home Assistant Supervisor: 2024.06.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service banner successfully started
s6-rc: info: service universal-silabs-flasher: starting
[02:57:34] INFO: Checking /dev/ttyUSB0 identifying SkyConnect v1.0 from Nabu Casa.
[02:57:34] INFO: Starting universal-silabs-flasher with /dev/ttyUSB0
2024-06-27 02:57:34.623 homeassistant universal_silabs_flasher.flash INFO Extracted GBL metadata: NabuCasaMetadata(metadata_version=1, sdk_version='4.4.0', ezsp_version=None, ot_rcp_version='SL-OPENTHREAD/2.4.0.0_GitHub-7074a43e4' (2.4.0.0), cpc_version=None, fw_type=<FirmwareImageType.OT_RCP: 'ot-rcp'>, baudrate=460800)
2024-06-27 02:57:34.623 homeassistant universal_silabs_flasher.flasher INFO Probing ApplicationType.GECKO_BOOTLOADER at 115200 baud
2024-06-27 02:57:36.630 homeassistant universal_silabs_flasher.flasher INFO Probing ApplicationType.SPINEL at 460800 baud
2024-06-27 02:57:40.945 homeassistant universal_silabs_flasher.flasher INFO Probing ApplicationType.CPC at 460800 baud
2024-06-27 02:57:45.259 homeassistant universal_silabs_flasher.flasher INFO Probing ApplicationType.CPC at 115200 baud
2024-06-27 02:57:49.574 homeassistant universal_silabs_flasher.flasher INFO Probing ApplicationType.CPC at 230400 baud
2024-06-27 02:57:53.889 homeassistant universal_silabs_flasher.flasher INFO Probing ApplicationType.EZSP at 115200 baud
Error: Failed to probe running application type
s6-rc: warning: unable to start service universal-silabs-flasher: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service banner: stopping
s6-rc: info: service mdns: stopping
s6-rc: info: service banner successfully stopped
Default: mDNSResponder (Engineering Build) (Jun 25 2024 11:10:05) stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
[02:57:58] INFO: mDNS ended with exit code 4 (signal 0)...
s6-rc: info: service mdns successfully stopped
```

**Comment by clefus** [comment]
Anything else I can provide on this?  Thanks in advance.

**Comment by LunaMistcaller** [comment]
Hiya! I had this same issue and was able to resolve it by going into the configuration for open thread and turning off the auto update firmware option. 

Hope this helps!

**Comment by clefus** [comment]
Thanks @LunaMistcaller - I have tried toggling the following (below) settings one at at a time.  Has made no difference in the logs or results.  I have also tried different baud rates.  Still nada.

Hardware Flow Control
Automatically Flash Firmware
OTBR Firewall
NAT64

I think it is a bug in HAOS update or bad Open Thread Border Router version....maybe it cause some mismatch flash?

**Comment by clefus** [comment]
In case I failed to mention above - this is with the nabu casa skyconnect device.  Thanks in advance.

**Comment by LunaMistcaller** [comment]
@clefus I sort of wonder if the firmware that auto installed was bad or it might not have permissions to update the firmware within HA itself, though I didn't see anyway to give it permissions to update if that was the case. I ended up flashing it outside of HA. 

I've summarized what steps I took below after the trial and error period: 

1. Uninstalled Open Thread addon
2. Disconnected my skyconnect from my VM to my host PC
3. Installed the Silicon Labs CP2102 driver to allow it to flash. That can be found here: https://www.silabs.com/developers/usb-to-uart-bridge-vcp-drivers?tab=downloads
4. Updated my skyconnect's firmware using the link here: https://connectzbt1.home-assistant.io/firmware-update/ I picked the open thread firmware option. 
5. Restarted Home Assistant 
6. Re-installed Open Thread addon 
7. turned off the firmware update 
8. started the addon 


My settings are: 

Baudrate: 460800
Hadware flow control: On
Automatically flash firmware: Off
OTBR Firewall: On
NAT64: Off

Hope this gets it going for you!

**Comment by clefus** [comment]
Thanks @LunaMistcaller really appreciate your help.  I tried the steps you outlined - it did flash a new firmware version....but it still does not work.  It did change the logs though.

-----------------------------------------------------------

 Add-on: OpenThread Border Router
 OpenThread Border Router add-on
-----------------------------------------------------------
 Add-on version: 2.8.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 12.4  (amd64 / generic-x86-64)
 Home Assistant Core: 2024.6.4
 Home Assistant Supervisor: 2024.06.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service banner successfully started
s6-rc: info: service universal-silabs-flasher: starting
[01:20:16] INFO: Flashing firmware is disabled
s6-rc: info: service universal-silabs-flasher successfully started
s6-rc: info: service otbr-agent: starting
[01:20:16] INFO: Setup OTBR firewall...
[01:20:16] INFO: Starting otbr-agent...
[NOTE]-AGENT---: Running 0.3.0-41474ce-dirty
[NOTE]-AGENT---: Thread version: 1.3.0
[NOTE]-AGENT---: Thread interface: wpan0
[NOTE]-AGENT---: Radio URL: spinel+hdlc+uart:///dev/ttyUSB0?uart-baudrate=460800&uart-flow-control
[NOTE]-AGENT---: Radio URL: trel://eno1
[NOTE]-ILS-----: Infra link selected: eno1
49d.17:08:32.309 [W] P-SpinelDrive-: Wait for response timeout
49d.17:08:34.309 [W] P-SpinelDrive-: Wait for response timeout
49d.17:08:36.310 [W] P-SpinelDrive-: Wait for response timeout
49d.17:08:36.311 [C] Platform------: Init() at spinel_driver.cpp:82: Failure
49d.17:08:38.312 [W] P-SpinelDrive-: Wait for response timeout
[01:20:24] WARNING: otbr-agent exited with code 1 (by signal 0).
Chain OTBR_FORWARD_INGRESS (0 references)
target     prot opt source               destination         
DROP       all  --  anywhere             anywhere             PKTTYPE = unicast
DROP       all  --  anywhere             anywhere             match-set otbr-ingress-deny-src src
ACCEPT     all  --  anywhere             anywhere             match-set otbr-ingress-allow-dst dst
DROP       all  --  anywhere             anywhere             PKTTYPE = unicast
ACCEPT     all  --  anywhere             anywhere            
otbr-ingress-deny-src
otbr-ingress-deny-src-swap
otbr-ingress-allow-dst
otbr-ingress-allow-dst-swap
Chain OTBR_FORWARD_EGRESS (0 references)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             anywhere            
[01:20:24] INFO: OTBR firewall teardown completed.
s6-svlisten1: fatal: /run/s6-rc/servicedirs/otbr-agent failed permanently or its supervisor died
s6-rc: warning: unable to start service otbr-agent: command exited 1
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service universal-silabs-flasher: stopping
s6-rc: info: service mdns: stopping
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
Default: mDNSResponder (Engineering Build) (Jun 25 2024 11:10:05) stopping
s6-rc: info: service universal-silabs-flasher successfully stopped
s6-rc: info: service banner: stopping
s6-rc: info: service banner successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
[01:20:25] INFO: mDNS ended with exit code 4 (signal 0)...
s6-rc: info: service mdns successfully stopped

Thanks in advance to whoever solves!

**Comment by darkxst** [comment]
> ```
> 2024-06-27 02:54:19.846 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-otbr with version 2.8.0
> 2024-06-27 02:54:26.473 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon Silicon Labs Multiprotocol is failed, restarting...
> 2024-06-27 02:54:26.480 INFO (SyncWorker_2) [supervisor.docker.manager] Cleaning addon_core_silabs_multiprotocol application
> 2024-06-27 02:54:26.735 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-silabs-multiprotocol with version 2.4.5
> ```

You can't run Multiprotocol and OTBR addons at the same time (on the same device atleast). Try removing multiprotocol addon from the mix!

**Comment by clefus** [comment]
Thanks @darkxst.  I was able to get it working again tonight.  I again uninstalled the Open Thread Border router integrations and addons.  I first tried removing the integrations and adding them back, that did not work.  I then removed both the openthread border router and the multi-protocol addon and then added only the open thread border router addon back.  The integrations for Thread and Open Border Router were auto added and it is now working.

I think this issue needs to remain open.  While I am now working again, I do have flash firmware disabled and this should be enabled and functioning to get the latest from homeassistant/nabu.

**Comment by darkxst** [comment]
@clefus what happens when you enable auto flash firmware? can you post logs of this failing?

**Comment by clefus** [comment]
Actually - seems to be working now - at least Open Thread Border Router...not sure about the firmware flash....here is the log.  I also turned off and on a device after enabling / restarting addon.

-----------------------------------------------------------

 Add-on: OpenThread Border Router
 OpenThread Border Router add-on
-----------------------------------------------------------
 Add-on version: 2.8.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 12.4  (amd64 / generic-x86-64)
 Home Assistant Core: 2024.6.4
 Home Assistant Supervisor: 2024.06.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service banner successfully started
s6-rc: info: service universal-silabs-flasher: starting
[18:04:52] INFO: Checking /dev/ttyUSB0 identifying SkyConnect v1.0 from Nabu Casa.
[18:04:52] INFO: Starting universal-silabs-flasher with /dev/ttyUSB0
2024-07-01 18:04:52.694 homeassistant universal_silabs_flasher.flash INFO Extracted GBL metadata: NabuCasaMetadata(metadata_version=1, sdk_version='4.4.0', ezsp_version=None, ot_rcp_version='SL-OPENTHREAD/2.4.0.0_GitHub-7074a43e4' (2.4.0.0), cpc_version=None, fw_type=<FirmwareImageType.OT_RCP: 'ot-rcp'>, baudrate=460800)
2024-07-01 18:04:52.694 homeassistant universal_silabs_flasher.flasher INFO Probing ApplicationType.GECKO_BOOTLOADER at 115200 baud
2024-07-01 18:04:54.702 homeassistant universal_silabs_flasher.flasher INFO Probing ApplicationType.SPINEL at 460800 baud
2024-07-01 18:04:55.817 homeassistant universal_silabs_flasher.flasher INFO Detected ApplicationType.SPINEL, version 'SL-OPENTHREAD/2.4.0.0_GitHub-7074a43e4' (2.4.0.0) at 460800 baudrate (bootloader baudrate None)
2024-07-01 18:04:55.817 homeassistant universal_silabs_flasher.flash INFO Firmware version 'SL-OPENTHREAD/2.4.0.0_GitHub-7074a43e4' (2.4.0.0) is flashed, not re-installing
s6-rc: info: service universal-silabs-flasher successfully started
s6-rc: info: service otbr-agent: starting
[18:04:56] INFO: Setup OTBR firewall...
[18:04:56] INFO: Starting otbr-agent...
s6-rc: info: service otbr-agent successfully started
s6-rc: info: service otbr-agent-rest-discovery: starting
s6-rc: info: service otbr-agent-configure: starting
Done
s6-rc: info: service otbr-agent-configure successfully started
[18:04:56] INFO: Successfully sent discovery information to Home Assistant.
s6-rc: info: service otbr-agent-rest-discovery successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[NOTE]-AGENT---: Running 0.3.0-41474ce-dirty
[NOTE]-AGENT---: Thread version: 1.3.0
[NOTE]-AGENT---: Thread interface: wpan0
[NOTE]-AGENT---: Radio URL: spinel+hdlc+uart:///dev/ttyUSB0?uart-baudrate=460800&uart-flow-control
[NOTE]-AGENT---: Radio URL: trel://eno1
[NOTE]-ILS-----: Infra link selected: eno1
51d.09:53:10.696 [C] P-SpinelDrive-: Software reset co-processor successfully
00:00:00.055 [N] RoutingManager: BR ULA prefix: fd2b:9d4c:9f0b::/48 (loaded)
00:00:00.055 [N] RoutingManager: Local on-link prefix: fdbb:b08e:f06f:aa61::/64
00:00:00.082 [N] Mle-----------: Role disabled -> detached
00:00:00.092 [N] P-Netif-------: Changing interface state to up.
00:00:00.103 [W] P-Netif-------: Failed to process request#2: No such process
00:00:00.103 [W] P-Netif-------: Failed to process request#6: No such process
00:00:00.160 [N] Mle-----------: Role detached -> router
00:00:00.160 [N] Mle-----------: Partition ID 0x26a0ecdb
[NOTE]-BBA-----: BackboneAgent: Backbone Router becomes Primary!
00:00:03.363 [N] MeshForwarder-: Dropping rx frag frame, error:Drop, len:32, src:a2a35d3103fb84dd, dst:0xffff, tag:64257, offset:128, dglen:160, sec:yes
00:00:03.665 [W] DuaManager----: Failed to perform next registration: NotFound
00:00:15.667 [N] MeshForwarder-: Dropping (reassembly queue) IPv6 UDP msg, len:1074, chksum:74b8, ecn:no, sec:yes, error:ReassemblyTimeout, prio:normal, rss:-85.0, radio:15.4
00:00:15.667 [N] MeshForwarder-:     src:[fd2b:9d4c:9f0b:1:b079:2974:ed98:fa47]:5540
00:00:15.667 [N] MeshForwarder-:     dst:[fd2b:9d4c:9f0b:1:4fa5:684c:be03:4d0e]:54656
00:00:16.668 [N] MeshForwarder-: Dropping (reassembly queue) IPv6 UDP msg, len:1074, chksum:09a2, ecn:no, sec:yes, error:ReassemblyTimeout, prio:normal, rss:-88.25, radio:15.4
00:00:16.668 [N] MeshForwarder-:     src:[fd2b:9d4c:9f0b:1:2e77:6bb3:5b79:eed3]:5540
00:00:16.668 [N] MeshForwarder-:     dst:[fd2b:9d4c:9f0b:1:4fa5:684c:be03:4d0e]:54656
00:00:16.668 [N] MeshForwarder-: Dropping (reassembly queue) IPv6 UDP msg, len:1074, chksum:74b8, ecn:no, sec:yes, error:ReassemblyTimeout, prio:normal, rss:-84.5, radio:15.4
00:00:16.668 [N] MeshForwarder-:     src:[fd2b:9d4c:9f0b:1:b079:2974:ed98:fa47]:5540
00:00:16.668 [N] MeshForwarder-:     dst:[fd2b:9d4c:9f0b:1:4fa5:684c:be03:4d0e]:54656
00:00:17.672 [N] MeshForwarder-: Dropping (reassembly queue) IPv6 UDP msg, len:1074, chksum:09a2, ecn:no, sec:yes, error:ReassemblyTimeout, prio:normal, rss:-89.75, radio:15.4
00:00:17.672 [N] MeshForwarder-:     src:[fd2b:9d4c:9f0b:1:2e77:6bb3:5b79:eed3]:5540
00:00:17.672 [N] MeshForwarder-:     dst:[fd2b:9d4c:9f0b:1:4fa5:684c:be03:4d0e]:54656
00:00:17.672 [N] MeshForwarder-: Dropping (reassembly queue) IPv6 UDP msg, len:1078, chksum:8fcb, ecn:no, sec:yes, error:ReassemblyTimeout, prio:normal, rss:-84.75, radio:15.4
00:00:17.672 [N] MeshForwarder-:     src:[fd2b:9d4c:9f0b:1:b7a7:c5b5:89ba:fad9]:5540
00:00:17.672 [N] MeshForwarder-:     dst:[fd2b:9d4c:9f0b:1:4fa5:684c:be03:4d0e]:54656
00:00:17.672 [N] MeshForwarder-: Dropping (reassembly queue) IPv6 UDP msg, len:1074, chksum:09a2, ecn:no, sec:yes, error:ReassemblyTimeout, prio:normal, rss:-88.625, radio:15.4
00:00:17.672 [N] MeshForwarder-:     src:[fd2b:9d4c:9f0b:1:2e77:6bb3:5b79:eed3]:5540
00:00:17.672 [N] MeshForwarder-:     dst:[fd2b:9d4c:9f0b:1:4fa5:684c:be03:4d0e]:54656
00:00:17.672 [N] MeshForwarder-: Dropping (reassembly queue) IPv6 UDP msg, len:1074, chksum:74b8, ecn:no, sec:yes, error:ReassemblyTimeout, prio:normal, rss:-84.625, radio:15.4
00:00:17.672 [N] MeshForwarder-:     src:[fd2b:9d4c:9f0b:1:b079:2974:ed98:fa47]:5540
00:00:17.672 [N] MeshForwarder-:     dst:[fd2b:9d4c:9f0b:1:4fa5:684c:be03:4d0e]:54656
00:00:18.675 [N] MeshForwarder-: Dropping (reassembly queue) IPv6 UDP msg, len:1074, chksum:09a2, ecn:no, sec:yes, error:ReassemblyTimeout, prio:normal, rss:-89.0, radio:15.4
00:00:18.675 [N] MeshForwarder-:     src:[fd2b:9d4c:9f0b:1:2e77:6bb3:5b79:eed3]:5540
00:00:18.675 [N] MeshForwarder-:     dst:[fd2b:9d4c:9f0b:1:4fa5:684c:be03:4d0e]:54656

**Comment by darkxst** [comment]
> OPENTHREAD/2.4.0.0_GitHub-7074a43e4' (2.4.0.0) is flashed, not re-installing
> s6-rc: info: service universal-silabs-flasher successfully started

That looks good. Probably before the two addons were fighting with each other over which firmware should be installed.

**Comment by darkxst** [comment]
> .how can I tell which firmware it is running

it was in the logs, per the line I quoted.



> I wanted to be able to run thread and zigbee.

Its really not recommended to run Multiprotocol anymore due to ongoing stability issues in firmware and stack, it is best to run 2 separate sticks, one for Zigbee and one for Thread

**Comment by agners** [comment]
Closing this, as the problem OP had is fixed.

In general, make sure to not have both, the Silicon Labs Multiprotocol and the OpenThread Border Router installed, and in particular not running at the same time! Each one of them expects exclusive access to the SkyConnect/Connect ZBT-1. If both access the radio at the same time, things are bound to fail.

The dedicated Thread setup is recommended. Check the SkyConnect docs on how to [properly disable the multiprotocol feature](https://connectzbt1.home-assistant.io/procedures/disable-multiprotocol/#from-skyconnect).
