### ISSUE TITLE
Duck DNS - ERROR: Challenge is invalid! (returned: invalid) (result: ["type"]	"dns-01"

### ISSUE THREAD

**Issue by KitHubek** [home-assistant/addons#3678]
### Describe the issue you are experiencing

Just see this error at log. Official HA addon Duck DNS
All working ok, but recent see this error at log

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Duck DNS

### What is the version of the add-on?

1.17.0

### Steps to reproduce the issue

1. Install DuckDns addon
2. fill config file
3. run addon
4. see errors at log 

## System Information

version | core-2024.6.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.33-haos
arch | x86_64
timezone | Europe/Warsaw
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1384
Downloaded Repositories | 9

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 33

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>GIOŚ</summary>

can_reach_server | ok
-- | --

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.4
-- | --
update_channel | stable
supervisor_version | supervisor-2024.06.2
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 234.0 GB
disk_used | 31.2 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Studio Code Server (5.15.0), Mosquitto broker (6.4.1), Samba share (12.3.1), Duck DNS (1.17.0), NGINX Home Assistant SSL proxy (3.9.0), Zigbee2MQTT (1.38.0-1), ESPHome (2024.6.4), MariaDB (2.7.1), Advanced SSH & Web Terminal (18.0.0), phpMyAdmin (0.9.1), Node-RED (18.0.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 8
-- | --
resources | 5
views | 33
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 3 maja 2024 17:04
-- | --
current_recorder_run | 30 czerwca 2024 00:07
estimated_db_size | 4754.19 MiB
database_engine | mysql
database_version | 10.11.6

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

<details><summary>Xiaomi Miot Auto</summary>

component_version | 0.7.18
-- | --
can_reach_server | ok
can_reach_spec | ok
logged_accounts | 1
total_devices | 15

</details>

### Anything in the add-on logs that might be useful for us?

```txt
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
# INFO: Using main config file /data/workdir/config
+ Account already registered!
[19:05:32] INFO: Renew certificate for domains: mydns.duckdns.org and aliases: 
# INFO: Using main config file /data/workdir/config
Processing mydns.duckdns.org
 + Checking domain name(s) of existing cert... unchanged.
 + Checking expire date of existing cert...
 + Valid till Jul 30 18:23:23 2024 GMT (Less than 30 days). Renewing!
 + Signing domains...
 + Generating private key...
 + Generating signing request...
 + Requesting new certificate order from CA...
 + Received 1 authorizations URLs from the CA
 + Handling authorization for mydns.duckdns.org
 + 1 pending challenge(s)
 + Deploying challenge tokens...
OK + Responding to challenge for mydns.duckdns.org authorization...
 + Cleaning challenge tokens...
OK + Challenge validation has failed :(
ERROR: Challenge is invalid! (returned: invalid) (result: ["type"]	"dns-01"
["url"]	"https://acme-v02.api.letsencrypt.org/acme/chall-v3/hiddennumbers"
["status"]	"invalid"
["validated"]	"2024-07-01T17:05:38Z"
["error","type"]	"urn:ietf:params:acme:error:dns"
["error","detail"]	"DNS problem: SERVFAIL looking up TXT for _acme-challenge.mydns.duckdns.org - the domain's nameservers may be malfunctioning"
["error","status"]	400
["error"]	{"type":"urn:ietf:params:acme:error:dns","detail":"DNS problem: SERVFAIL looking up TXT for _acme-challenge.mydns.duckdns.org - the domain's nameservers may be malfunctioning","status":400}
["token"]	"hiddentoken")
```

### Additional information

my addon config:

domains:
  - mydns.duckdns.org
token: mytoken
aliases: []
lets_encrypt:
  accept_terms: true
  algo: secp384r1
  certfile: fullchain.pem
  keyfile: privkey.pem
seconds: 300

at main HA config file:

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

**Comment by dkliban** [comment]
I am experiencing the exact same problem. i updated to 1.18.0 and that didn't help.

**Comment by gffa325** [comment]
Same here!

DuckDNS Addon version 1.18.0

**Comment by ruicarvalho-winsig** [comment]
Same Here with 1.18.0.

**Comment by ncp1113** [comment]
The UI configuration is incorrect for duckdns. There are actually 2 errors. Edit in YAML. (click on 3 dots)
 It should be:
domains:
  - *****.duckdns.org
email: *****
keyfile: privkey.pem
certfile: fullchain.pem
challenge: dns
dns:
  provider: dns-duckdns
  duckdns_token: *****

Thank you to Bruno at https://www.derekseaman.com/2023/06/home-assistant-auto-renewing-lets-encrypt-ssl.html
and [Marie-Luise Orland](https://community.home-assistant.io/u/CaptainMalu)

**Comment by Kammiiz** [comment]
> The UI configuration is incorrect for duckdns. There are actually 2 errors. Edit in YAML. (click on 3 dots) It should be:
> 
> ```
> domains:`
>   - *****.duckdns.org
> email: *****
> keyfile: privkey.pem
> certfile: fullchain.pem
> challenge: dns
> dns:
>   provider: dns-duckdns
>   duckdns_token: *****
> ```
> 
> Thank you to Bruno at https://www.derekseaman.com/2023/06/home-assistant-auto-renewing-lets-encrypt-ssl.html and [Marie-Luise Orland](https://community.home-assistant.io/u/CaptainMalu)

Thanks a lot ! Worked for me

**Comment by PinkFloyd1213** [comment]
> The UI configuration is incorrect for duckdns. There are actually 2 errors. Edit in YAML. (click on 3 dots) It should be:
> 
> ```
> domains:`
>   - *****.duckdns.org
> email: *****
> keyfile: privkey.pem
> certfile: fullchain.pem
> challenge: dns
> dns:
>   provider: dns-duckdns
>   duckdns_token: *****
> ```
> 
> Thank you to Bruno at https://www.derekseaman.com/2023/06/home-assistant-auto-renewing-lets-encrypt-ssl.html and [Marie-Luise Orland](https://community.home-assistant.io/u/CaptainMalu)

This configuration is for the DuckDNS addon or for the Let's Encrypt addon ? Cause if I set this up like that in the DuckDNS addons, I got an error: 

 ```
Failed to save add-on configuration, Missing option 'lets_encrypt' in root in Duck DNS (core_duckdns). Got {'domains': ['***.duckdns.org'], 'email': '***', 'keyfile': 'privkey.pem', 'certfile': 'fullchain.pem', 'challenge': 'dns', 'seconds': 300, 'dns': {'provider': 'dns-duckdns', 'duckdns_token': '***''}} 
 ```

**Comment by ncp1113** [comment]
In the DuckDNS add-on, click on the three dots to get to "Edit in YAML". That is where you put your code. You need to register your domain with DuckDNS and copy DuckDNS token at the top of the page.

**Comment by Tiktack** [comment]
> The UI configuration is incorrect for duckdns. There are actually 2 errors. Edit in YAML. (click on 3 dots) It should be:
> 
> ```
> domains:`
>   - *****.duckdns.org
> email: *****
> keyfile: privkey.pem
> certfile: fullchain.pem
> challenge: dns
> dns:
>   provider: dns-duckdns
>   duckdns_token: *****
> ```
> 
> Thank you to Bruno at https://www.derekseaman.com/2023/06/home-assistant-auto-renewing-lets-encrypt-ssl.html and [Marie-Luise Orland](https://community.home-assistant.io/u/CaptainMalu)
> 
> EDIT: I had to reinstall everything with an upgraded OS. The above did not work with Hass OS 2024.8.3. This is what worked with in the new install:
> 
> ```
> domains:
>   - ****.duckdns.org
> token: **** 
> aliases: []
> lets_encrypt:
>   accept_terms: true
>   algo: secp384r1
>   certfile: /ssl/fullchain.pem
>   keyfile: /ssl/privkey.pem
> seconds: 300
> challenge: dns
> dns:
>   provider: dns-duckdns
> ```

This still doesn't work. The error stays the same.

**Comment by graysham** [comment]
Anyone figure this out? My install was working, Hit certificate expiry date and it hadnt auto renewed correctly. So I started seeing issues as see in OP. When i use the changes suggest by @ncp1113 on their Aug 4th edit, I get a 503 error rather than a 403 with the original setup but it still fails basically.

**Comment by Tiktack** [comment]
For me it just started to work in 2 days. Nothing changed, default config with true for agreement + token + 1 domain from duckdns

**Comment by dpiessens** [comment]
Mine is failing the DNS challenge as well, it seems that DuckDNS is either having issues with latency on populating the txt records or overall domain lookup. Either way, for an existing domain I either get 400 not found or a 403 and your TXT record is expired.

**Comment by Tiktack** [comment]
> @Tiktack Was it a new duckdns domain? I am wondering if a new domain can take time to show up in the DNS universe.

I had one domain for 2 years. But I reinstalled my HA and couldn't setup duckDNS with the error mentioned in this issue. Also, I created another one to check, but it didn't help, same error. In a day or something like that both domains started to work. 

So, I guess duck dns having some issues on their side and I can suggest just to try in a day or two...
Nothing else helped..

**Comment by Marco1971Repo** [comment]
> challenge: dns
> dns:
>   provider: dns-duckdns

this do thing work to me.
Big Thanks!!!!!

**Comment by ML-GeekHub** [comment]
I had a similar problem. Last thing I tried is dpiessens answer 17 Dec 2024 (edit as yaml text) and it worked for me. However, after full HA reboot, when I come back to duckdns configuration ( edit as yaml ), I found the following text:

```
domains:
  - ***.duckdns.org
token: ***
aliases: []
lets_encrypt:
  accept_terms: true
  algo: secp384r1
  certfile: fullchain.pem
  keyfile: privkey.pem
seconds: 300
```

**Comment by ML-GeekHub** [comment]
Nevertheless, it seems that all is working now. Thank's !!
