### ISSUE TITLE
Everspring thermometers dropped values by bout 30 C after installing the Z-wave JS 3.9.0 update

### ISSUE THREAD

**Issue by ArLo69** [home-assistant/addons#3693]
### Describe the issue you are experiencing

Immediately the air temperature reported by my two Everspring thermometers droppen from around 23 C tot around -5 C. And they do give new value changes after the update.
Newer Aeotec thermometers and a Secure Meters SES302 still show correct values, but appear to give no new values at all. Not even after forced updates and tamering with the temperature. They are stuck at the last value before the update for quite some time now.  Soft reset of Z-wave, unplugging the Aeotec 700 stick and restarting HA did not help. Other devices like switches, power meters and door sensors are working just fine. 

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Z-Wave JS

### What is the version of the add-on?

3.9.0

### Steps to reproduce the issue

1. Update to 3.9.0 
2. Check the air temverature of any Everspring ST814 
3. Check values of any thermometer preferable through a graph.
4.  Check HA log, you will see device updates showing they do report in at interval or by forced update.
...

## System Information

version | core-2024.7.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.33-haos
arch | x86_64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1388
Downloaded Repositories | 28

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.4
-- | --
update_channel | stable
supervisor_version | supervisor-2024.06.2
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 116.7 GB
disk_used | 24.9 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Advanced SSH & Web Terminal (18.0.0), Duck DNS (1.18.0), Studio Code Server (5.15.0), Z-Wave JS UI (3.9.0), SQLite Web (4.1.2), Samba share (12.3.1), MariaDB (2.7.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 18
views | 13
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 10 juli 2024 om 11:58
-- | --
current_recorder_run | 17 juli 2024 om 11:45
estimated_db_size | 898.73 MiB
database_engine | mysql
database_version | 10.11.6

</details>

**Comment by MartinHjelmare** [comment]
This issue tracker doesn't track issues with the Z-Wave JS UI add-on that you're running.

Since the problem is device specific, I recommend capturing Z-Wave JS driver debug logs and opening an issue with the driver project.

https://github.com/zwave-js/node-zwave-js/issues
