### ISSUE TITLE
Whisper not working: Service exited with code 256 (by signal 4)

### ISSUE THREAD

**Issue by maciek1992** [home-assistant/addons#3695]
### Describe the issue you are experiencing

I have a HomeAssistant on VM with Proxmox installed on Dell Wyse 7010 and can not run Whisper at all, the processor in Proxmox is set to host. (AMD G-T56N Processor)

Strangely, HA is showing that this addon is working, but Wyoming protocol can not find it.

I know this processor doesn't have AVX instructions but it should work, just slower.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Whisper

### What is the version of the add-on?

2.1.2

### Steps to reproduce the issue

1. Install Whisper
2. Try to run it
3. Check Logs
...

## System Information

version | core-2024.7.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.33-haos
arch | x86_64
timezone | Europe/Warsaw
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4962
Installed Version | 1.34.0
Stage | running
Available Repositories | 1384
Downloaded Repositories | 6

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 1 stycznia 2018 o 01:00
relayer_connected | false
relayer_region | null
remote_enabled | false
remote_connected | false
alexa_enabled | false
google_enabled | true
remote_server | null
certificate_status | null
instance_id | bc13030b39ee405dad975ee1ac1993dc
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.4
-- | --
update_channel | stable
supervisor_version | supervisor-2024.06.2
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 30.8 GB
disk_used | 10.6 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | kvm
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.14.0), Studio Code Server (5.15.0), Duck DNS (1.18.0), NGINX Home Assistant SSL proxy (3.9.0), UniFi Network Application (3.2.0), Piper (1.5.1), Whisper (2.1.2), openWakeWord (1.10.0), Samba share (12.3.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 1
views | 2
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 20 lipca 2024 o 11:25
-- | --
current_recorder_run | 22 lipca 2024 o 18:51
estimated_db_size | 278.48 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Anything in the Supervisor logs that might be useful for us?

```txt
2024-07-22 18:54:04.887 WARNING (MainThread) [supervisor.addons.addon] Timeout while waiting for addon Whisper to start, took more than 120 seconds

--
```

### Anything in the add-on logs that might be useful for us?

```txt
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service whisper: starting
s6-rc: info: service whisper successfully started
s6-rc: info: service discovery: starting
[18:52:07] WARNING: Your CPU does not support Advanced Vector Extensions (AVX). Whisper will run slower than normal.
[18:52:26] INFO: Service exited with code 256 (by signal 4)
[18:52:28] WARNING: Your CPU does not support Advanced Vector Extensions (AVX). Whisper will run slower than normal.
[18:52:38] INFO: Service exited with code 256 (by signal 4)
[18:52:39] WARNING: Your CPU does not support Advanced Vector Extensions (AVX). Whisper will run slower than normal.
[18:52:48] INFO: Service exited with code 256 (by signal 4)
[18:52:49] WARNING: Your CPU does not support Advanced Vector Extensions (AVX). Whisper will run slower than normal.
[18:52:57] INFO: Service exited with code 256 (by signal 4)
[18:52:59] WARNING: Your CPU does not support Advanced Vector Extensions (AVX). Whisper will run slower than normal.
```

**Comment by Maxmills82** [comment]
I'm in the same boat did u ever fix it

**Comment by Maxmills82** [comment]
I'm in the same boat didbu ever fix it

**Comment by jli113** [comment]
Same

**Comment by skom27** [comment]
I have the same thing:
[13:20:54] WARNING: Your CPU does not support Advanced Vector Extensions (AVX). Whisper will run slower than normal.
[13:20:56] INFO: Service exited with code 256 (by signal 4)
[13:20:57] WARNING: Your CPU does not support Advanced Vector Extensions (AVX). Whisper will run slower than normal.

**Comment by JugglerLKR** [comment]
Same here, not matter which model I choose

**Comment by Bob-Technicien-pro** [comment]
To solve missing AVX issue I have set the CPU type to "**host**" in Proxmox for the Home Assistant VM @walnuss0815 THX!!
