### ISSUE TITLE
NGINX Home Assistant SSL proxy update prevents addon start

### ISSUE THREAD

**Issue by mmarc** [home-assistant/addons#3726]
### Describe the issue you are experiencing

Update to 3.10.0 adds optional `real_ip_from` config item but won't start if no `real_ip_from` is provided.
So plugin won't restart after update.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

NGINX Home Assistant SSL proxy

### What is the version of the add-on?

3.10.0

### Steps to reproduce the issue

Just update from a previous version to 3.10.0

**Comment by DocBrownInSpace** [comment]
Is there a workaround?  I’m not sure what to set “real_ip_from” to.

**Comment by imnotnotdavid** [comment]
Same issue here!

**Comment by ibatten** [comment]
I've hit this.  If you use the UI configurator, it correctly puts in real_ip_from: [ ], which is required.  The example configuration in the documentation is wrong, because it shows real_ip_from: (end of line at the colon),which will not save.  Without real_ip_from: [ ], a working 3.9.0 configuration will not start.

**Comment by mvkGH** [comment]
> Is there a workaround? I’m not sure what to set “real_ip_from” to.

You can just leave it emtpy and click on save

In yaml:
```
certfile: cert.pem
keyfile: key.pem
cloudflare: false
real_ip_from: []
```

**Comment by imnotnotdavid** [comment]
![IMG_0570](https://github.com/user-attachments/assets/a8e6f561-0c4e-4d93-87ee-d0e520098951)

added the brackets but add on crashes when it tries to start. Assuming I did it wrong?

**Comment by mvkGH** [comment]
> ![IMG_0570](https://private-user-images.githubusercontent.com/98236245/357867854-a8e6f561-0c4e-4d93-87ee-d0e520098951.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NDY1OTksIm5iZiI6MTcyMzY0NjI5OSwicGF0aCI6Ii85ODIzNjI0NS8zNTc4Njc4NTQtYThlNmY1NjEtMGM0ZS00ZDkzLTg3ZWUtZDBlNTIwMDk4OTUxLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNFQxNDM4MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZWM3NDExNzFiNDE4MTE4NTBkMmRjZDQyNmY5ZGUxMTY3YjlmZDMzNzRiZWU2NWY0NDU0NmM0OGU1YTU2ZTQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5JJBlTNf3mjBmXJ9Hxhul16_yy5ojmoUNvP1HAPsiK8)
> 
> added the brackets but add on crashes when it tries to start. Assuming I did it wrong?

Don't add the brackets manually. Just leave the value empty and hit save.

**Comment by imnotnotdavid** [comment]
Bingo! Removed the brackets, hit save and now it started up!

**Comment by mtoftum** [comment]
Adding real_ip_from: [] to configuration.yaml seems to fix the issue with starting nginx, but seems to bring back an old issue where I had to add trusted_proxies: entries to configuration.yaml to fix a 400 bad request error. I've updated to add current ip, but it still results in 400 errors.
