### ISSUE TITLE
3.10.0 - Requires  'real_ip_from' in configuration

### ISSUE THREAD

**Issue by chicagoandy** [home-assistant/addons#3729]
### Describe the issue you are experiencing

After upgrading to 3.10.0, I am unable to start nginx_proxy.

Starting the add-on gives the error:    Missing option 'real_ip_from' in root in NGINX Home Assistant SSL proxy (core_nginx_proxy).

Documentation states that the field "real_ip_from" is optional.
![image](https://github.com/user-attachments/assets/d213ab99-63b6-4fe6-a893-7f13fea4afc3)

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

NGINX Home Assistant SSL proxy

### What is the version of the add-on?

3.10.0

### Steps to reproduce the issue

1. Inplace Upgrade to 3.10.0
2. Navagate to Add-On page for NGINX Proxy
3. Click 'Start'.
4. Startup fails with error that :real_ip_from is required.
...

## System Information

version | core-2024.7.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.33-haos
arch | x86_64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1389
Downloaded Repositories | 37

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 12

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.4
-- | --
update_channel | stable
supervisor_version | supervisor-2024.08.0
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 93.8 GB
disk_used | 52.0 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | kvm
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Studio Code Server (5.15.0), Duck DNS (1.18.0), Samba share (12.3.2), Home Assistant Google Drive Backup (0.112.1), NGINX Home Assistant SSL proxy (3.10.0), Advanced SSH & Web Terminal (18.0.0), Mosquitto broker (6.4.1), TeslaMate (0.22.0), Grafana (10.0.0), SQLite Web (4.2.0), ESPHome (2024.7.3), Firefox (Edge) (1.2.0), InfluxDB (5.0.0), MQTT Explorer (browser-1.0.3)

</details>

<details><summary>Dashboards</summary>

dashboards | 8
-- | --
resources | 20
views | 40
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | August 7, 2024 at 1:54 PM
-- | --
current_recorder_run | August 12, 2024 at 4:46 PM
estimated_db_size | 1317.66 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

<details><summary>Solcast PV Forecast</summary>

can_reach_server | ok
-- | --
used_requests | 2
rooftop_site_count | 2

</details>

<details><summary>Sonoff</summary>

version | 3.7.3 (e240aaf)
-- | --
cloud_online | 1 / 1
local_online | 1 / 1
debug | failed to load: 

</details>

### Anything in the Supervisor logs that might be useful for us?

```txt
2024-08-14 11:53:33.369 ERROR (MainThread) [supervisor.addons.addon] Add-on core_nginx_proxy has invalid options: Missing option 'real_ip_from' in root in NGINX Home Assistant SSL proxy (core_nginx_proxy). Got {'domain': 'andyland.duckdns.org', 'hsts': 'max-age=31536000; includeSubDomains', 'certfile': 'fullchain.pem', 'keyfile': 'privkey.pem', 'cloudflare': False, 'customize': {'active': True, 'default': 'nginx_proxy_default*.conf', 'servers': 'nginx_proxy/*.conf'}}
```

### Anything in the add-on logs that might be useful for us?

```txt
None generated.
```

**Comment by chicagoandy** [comment]
I've just noticed this is a dupe of  https://github.com/home-assistant/addons/issues/3726, you may want to leave the bug 'open' and visible until the fix is pushed.

**Comment by paultimms** [comment]
Same issue here. I read #3726 but I wasn't able to resolve it, so I restored the backup to revert to 3.9.0 and it's working fine. I won't update it until I can see it's been fixed.

**Comment by mkosmo** [comment]
I just reinstalled it again, got 3.10.1, and it automatically added the new line.

**Comment by domoticz-italia** [comment]
> Same issue here. I read #3726 but I wasn't able to resolve it, so I restored the backup to revert to 3.9.0 and it's working fine. I won't update it until I can see it's been fixed.

Hi. same iusse here. Can you explain me how to revert to 3.9.0?
try to reinstall lot of time but I can see only 3.10.0 version, not 3.10.1.
Thank so much

**Comment by davidrapan** [comment]
@domoticz-italia, you can only really revert using restore of the backup. Backing up before the upgrade should be opt-out. So you should have the backup there.

**Comment by domoticz-italia** [comment]
I have it:
addon_core_nginx_proxy_3.9.0.tar
but if i click on "restore" nothing happen.
May be I can do that manually?

**Comment by domoticz-italia** [comment]
> @domoticz-italia, you can only really revert using restore of the backup. Backing up before the upgrade should be opt-out. So you should have the backup there.

did it trough: setting, sistem, backup
now it works again.
Thanks so much

**Comment by chicagoandy** [comment]
I've noticed they've now made 3.10.1, and the only change in that version is to set the default value in the config file as:
real_ip_from: []

Adding that to your config file should resolve the issue.
Or pulling 3.10.1 should also fix the issue.

**Comment by paultimms** [comment]
Updated from 3.9.0 to 3.10.1 and all is working fine.

**Comment by chicagoandy** [comment]
Closing the issue.
