### ISSUE TITLE
VLC open file

### ISSUE THREAD

**Issue by alcatrazcj** [home-assistant/addons#3739]
### Describe the issue you are experiencing

In VLC integration, the “open media” button no longer works. I can't open M3U file
![image](https://github.com/user-attachments/assets/81018519-5864-4ef0-ba6c-70d763a2e578)

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

VLC

### What is the version of the add-on?

0.3.0

### Steps to reproduce the issue

1.“open media” button no longer works.

## System Information

version | core-2024.8.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.46-haos
arch | x86_64
timezone | Europe/Bucharest
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.1
-- | --
update_channel | stable
supervisor_version | supervisor-2024.08.0
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 116.7 GB
disk_used | 7.7 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.8.0), RPC Shutdown (2.5), Terminal & SSH (9.14.0), MPD (1.7.2), eWeLink Smart Home (1.4.3), Filebrowser (2.23.0_14), AdGuard Home (5.1.1), Mosquitto broker (6.4.1), VLC (0.3.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 1
views | 4
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 21 august 2024 la 19:13
-- | --
current_recorder_run | 25 august 2024 la 18:48
estimated_db_size | 166.39 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

**Comment by alcatrazcj** [comment]
no one does anything?!

**Comment by alcatrazcj** [comment]
?????

**Comment by DeclanE47** [comment]
Hey @alcatrazcj I will take a look at this tomorrow 👍

**Comment by alcatrazcj** [comment]
technical support is disappointing
