### ISSUE TITLE
Aqara Smart Plug (lumi.plug.maeu01) measurements not syncing to HA

### ISSUE THREAD

**Issue by Floris-88** [home-assistant/addons#3741]
### Describe the issue you are experiencing

I have a couple of the Aqara Smart Plug (lumi.plug.maeu01).
I know there are some issues with them and I found a lot of topics, but nothing covers my issue.

So I add the plugs to deCONZ. The power reading in deCONZ itself is perfectly fine and updates rather quickly (about 10 to 30 seconds max, which is fine):
![deCONZ Aqara plug](https://github.com/user-attachments/assets/01e7e0ed-542f-4a91-8c2c-816a1b65b97b)

However, the Phoscon app and Home Assistant itself are not or very slowly updated. It usually takes like 10 minutes for the value to get updated in Phoscon and HA. Whenever they update, it is at the same time though (Phoscon and HA).
![Phoscon Aqara Plug](https://github.com/user-attachments/assets/cac2ad51-a289-41be-a5fa-79f0332bd4e0)
![Home Assistant Aqara plug](https://github.com/user-attachments/assets/50e021f1-5834-4f47-938c-e37ce0911fb5)

I also tried to update the firmware according this topic: https://github.com/Koenkk/zigbee2mqtt/issues/13903#issuecomment-1822255030

Also tried deleting the device and re-pairing a couple of times, but always the same results.

Anyone have any insight in what might cause this and how to fix this?

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

deCONZ

### What is the version of the add-on?

7.0.0

### Steps to reproduce the issue

1. Pair device in deCONZ
2. Check power reading in deCONZ vs HA / Phoscon

### System Health information

Nothing

### Anything in the Supervisor logs that might be useful for us?

```txt
Nothing related to Aqara plugs
```

### Anything in the add-on logs that might be useful for us?

```txt
Doesn't show any errors that I can see
```

### Additional information

HA running on Pi4 with ConBee II stick (on USB extension cord) using deCONZ addon.
Everything else in deCONZ works perfectly fine (lights, sensors, other philips plugs).
Core 2024.8.3
Supervisor 2024.08.0
Operating System 13.1
Frontend 20240809.0

Updated deCONZ to 7.0.0 yesterday but issue was already present in previous versions.

**Comment by frijnhart** [comment]
I connected a second plug which is on a different firmware (0.0.0_0041 or just v41 I guess).
It updates a bit quicker in Phoscon and HA, but there is still a big lag from deCONZ. In deCONZ they both update just fine...

deCONZ:
![image](https://github.com/user-attachments/assets/1011f23e-dd1b-424c-86b2-6f7e38edc348)

Phoscon:
![image](https://github.com/user-attachments/assets/9968e8bd-b01f-4378-b81c-f9e792b9eeea)

HA:
![image](https://github.com/user-attachments/assets/2f928bb5-e249-468d-9059-750d9d752518)
