### ISSUE TITLE
Google DNS challenge method no longer works after the business was sold to Squarespace

### ISSUE THREAD

**Issue by Joshbloam** [home-assistant/addons#3742]
### Describe the issue you are experiencing

Google DNS challenge method does not work anymore. Google sold their domains business to Squarespace last year and my domain name is fully moved over to Squarespace now. Wildcards are no longer an option. Would be awesome to get the DNS challenge working again! Thanks!

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Let's Encrypt

### What is the version of the add-on?

5.1.3

### Steps to reproduce the issue

1. challenge: dns
2.dns:
  provider: dns-google-domains
  google_domains_access_token: XXXX
  google_domains_zone: mydomainname
3.
...

### System Health information

There are currently no repairs available

### Additional information

No Squarespace documentation found.

**Comment by agners** [comment]
Hm, Squarespace is not in the list of supported providers for DNS validation:
https://community.letsencrypt.org/t/dns-providers-who-easily-integrate-with-lets-encrypt-dns-validation/86438

Also according to this comment it indeed seems that Squarespace does not support the necessary ACME TLS/SSL certificates:
https://github.com/aaomidi/certbot-dns-google-domains/issues/41#issuecomment-2259399955

I'll remove Google DNS as it seems to really not work anymore. It seems you have to find a different solution :cry:
