### ISSUE TITLE
Letsencrypt: GoDaddy wildcard certificate error

### ISSUE THREAD

**Issue by rupert12pl** [home-assistant/addons#3746]
### Describe the issue you are experiencing

The wildcard certificate does not work for letsencrypt.
For full-name domains, the certificate is generated correctly.

Logs:
```
s6-rc: info: service legacy-services successfully started
21:26:51] INFO: Selected DNS Provider: dns-godaddy
[21:26:51] INFO: Use propagation seconds: 60
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Renewing an existing certificate for xxx and 2 more domains
Error determining zone identifier for rob-m.de: 401 Client Error: Unauthorized for url: https://api.godaddy.com/v1/domains/xxx
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
```

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Let's Encrypt

### What is the version of the add-on?

5.1.3

### Steps to reproduce the issue

1. domains: *.domain.com
2.![image](https://github.com/user-attachments/assets/6557866c-b434-4fc6-b886-9a86aa818778)
3. Authentication credentials

For full-name domains, the certificate is generated correctly.

### System Health information

Nothing to repair

**Comment by agners** [comment]
@dim-0 do you have thoughts on this issue?

**Comment by agners** [comment]
> I should probably add a note to the documentation to warn other users about this caveat.

Or could we maybe even detect such a setting and error out ahead of calling the API? :thinking:  But then, they might fix the API. We probably could just add a warning and let code continue, just in case this gets fixed API side :thinking:
