### ISSUE TITLE
DuckDNS 502 Bad Gateway - Causes softlock and prevents external connections

### ISSUE THREAD

**Issue by gergy008** [home-assistant/addons#3748]
### Describe the issue you are experiencing

It appears either DuckDNS had a blip today at around 15:15:32 BST because all of a sudden, I was no longer able to access my Home Assistant environment externally. When I got home, external connections were still down, but the internal local IP access was still up.

When I got home from work, I checked the home assistant log:

```
logger: homeassistant.components.duckdnsSource: components/duckdns/__init__.py:114integration: Duck DNS (documentation, issues)
First occurred: 3 September 2024 at 14:16:22 (2 occurrences)
Last logged: 17:15:44
Updating DuckDNS domain failed: redacted.duckdns.org
```

Then I checked the DuckDNS log and saw that it was stuck at:
```html
[15:15:32] INFO: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
</body>
</html>
```

After restarting DuckDNS, I was able to access remotely.

Log:
[duckdns.log](https://github.com/user-attachments/files/16880232/duckdns.log)

Config:
[duckdns.conf.log](https://github.com/user-attachments/files/16880256/duckdns.conf.log)

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Duck DNS

### What is the version of the add-on?

1.18.0

### Steps to reproduce the issue

This was a random occurrence, possibly related to some kind of outage - if it happens again it will lock me out externally again.

## System Information

version | core-2024.8.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.31-haos-raspi
arch | aarch64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.0
Stage | running
Available Repositories | 1393
Downloaded Repositories | 3

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.1
-- | --
update_channel | stable
supervisor_version | supervisor-2024.08.0
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 234.3 GB
disk_used | 5.6 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.8.0), Duck DNS (1.18.0), Terminal & SSH (9.14.0), Node-RED (18.0.5), NGINX Home Assistant SSL proxy (3.10.1), Samba NAS (12.2.0-nas2), Mosquitto broker (6.4.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 0
views | 6
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 25 August 2024 at 14:48
-- | --
current_recorder_run | 2 September 2024 at 00:16
estimated_db_size | 33.97 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Anything in the Supervisor logs that might be useful for us?

```txt
Nope sorry it has been overwritten and no idea where it could be in the file editor
```

### Anything in the add-on logs that might be useful for us?

```txt
DuckDNS Logs attached, along with config.

Home assistant log:


logger: homeassistant.components.duckdnsSource: components/duckdns/__init__.py:114integration: Duck DNS (documentation, issues)
First occurred: 3 September 2024 at 14:16:22 (2 occurrences)
Last logged: 17:15:44
Updating DuckDNS domain failed: redacted.duckdns.org
```
```


### Additional information

_No response_

**Comment by ge33ek** [comment]
+1 for a fix/adjustment 

but if we’re in the business for tweaking or better reporting this, having DuckDNS surface entities like “cert expiry date” “cert renew failed” and other relevant common errors - automations could then be triggered.
