### ISSUE TITLE
File editor does not default syntax highlighting to python for jinja extension.

### ISSUE THREAD

**Issue by DaveOzzie** [home-assistant/addons#3752]
### Describe the issue you are experiencing

File editor does not default syntax highlighting to python for jinja extension.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

File editor

### What is the version of the add-on?

5.8.0 

### Steps to reproduce the issue

1. Open a file with the extension jinja
2. No syntax highlighting. 
3. Go to editor settings, change mode to python
4. Syntax highlighting now works

### System Health information

There are currently no repairs available

### Anything in the Supervisor logs that might be useful for us?

```txt
Nope
```

### Anything in the add-on logs that might be useful for us?

```txt
Nope
```

**Comment by DaveOzzie** [comment]
No maintainer for this addon? 
I would use the vscode addon if my pi had more ram.

**Comment by DaveOzzie** [comment]
Ping

**Comment by frenck** [comment]
Hi there @DaveOzzie 👋 

Thanks for opening up an issue with our project. Unfortunately, this is not something we can address.

Add-ons wrap existing pieces of software for easy distribution and installation, but the software isn't created or maintained by us. In this case, it is the hass-configurator project/software we install for the file editor.

Please report your issue/wish with the upstream hass-configurator project. Once they have added/adjusted their project, we will be happy to update the add-on to include that update.

../Frenck

**Comment by DaveOzzie** [comment]
Thanks for the information I was unaware how Addons work. I have raised an issue with the hass-configurator project (I think). I did not find it easy to find the correct upstream project as there are 8 repositories with the same name.
