### ISSUE TITLE
File editor error with ESPHome secrets: "cannot merge mappings; the provided source object is unacceptable"

### ISSUE THREAD

**Issue by 7wells** [home-assistant/addons#3779]
### The problem

Hello!

I enter in file `/homeassistant/esphome/secrets.yaml` the following (and only) line:

`<<: !include ../secrets.yaml`

The File editor then complains with a red exclamation mark symbol and the following error:
```
cannot merge mappings; the provided source object is unacceptable (1:29)

 1 | <<: .include ../secrets.yaml
---------------------------------^
```
Nevertheless, an ESPHome node correctly gets the secrets from one level above, i.e. from `/homeassistant/secrets.yaml`.

Is this problem related to the File editor addon or rather to ESPHome? For the latter case, I have opened an issue there: https://github.com/esphome/issues/issues/6288

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

File editor

### What is the version of the add-on?

5.8.0

### Steps to reproduce the issue

1. Enter in file `/homeassistant/secrets.yaml` the following line (example):
`wifi_password: "blablabla"`

2. Enter in file `/homeassistant/esphome/secrets.yaml` the following (and only) line:
`<<: !include ../secrets.yaml`

3. Observe the File editor error message:
```
cannot merge mappings; the provided source object is unacceptable (1:29)

 1 | <<: .include ../secrets.yaml
---------------------------------^
```

**Comment by frenck** [comment]
Oh hi there @7wells 👋 

Add-ons wrap existing software, in this case, hass-configurator is used in this add-on.
Thes specific issue you report is an issue with hass-configurator and not directly with the add-on itself.

Therefore, please report this issue with the hass-configurator project. Once they have addressed this issue, we can update the add-on to include the upstream fix.

../Frenck
