### ISSUE TITLE
Missing few translation from one settings page "A file containing the..." 

### ISSUE THREAD

**Issue by misa1515** [home-assistant/addons#3785]
### Describe the issue you are experiencing

Found missing translation in lokalise.

Link in source code
https://github.com/home-assistant/addons/blob/6658d1bd1f2b6c48be43cda184a009602e59d857/mosquitto/translations/en.yaml#L30

![MosquittoTranslation](https://github.com/user-attachments/assets/c37961cb-a814-4401-9057-3c80287533ae)

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Mosquitto broker

### What is the version of the add-on?

not relevant

### System Health information

ok

**Comment by frenck** [comment]
These translations are not provided by addons; closing this issue for that reason.
