### ISSUE TITLE
Unable to scroll in "File editor" when using macOS Home Assistant "Companion App"

### ISSUE THREAD

**Issue by pweibelanykey** [home-assistant/addons#3788]
### Describe the issue you are experiencing

Scrolling is not possible/enabled within the macOS Home Assistant "Companion App"
https://apps.apple.com/ch/app/home-assistant/id1099568401
Only occurs in "File Editor", all other Add-ons or other areas which have scrolling work just fine. 

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

File editor

### What is the version of the add-on?

5.8.0

### Steps to reproduce the issue

1. Use macOS Companion App
2. Open File Editor
3. Open any File larger than Screen allows to show entirely
4. Try to scroll down
...

## System Information

version | core-2024.10.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.46-haos
arch | x86_64
timezone | Europe/Zurich
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4996
Installed Version | 2.0.1
Stage | running
Available Repositories | 1428
Downloaded Repositories | 2

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.1
-- | --
update_channel | stable
supervisor_version | supervisor-2024.09.1
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 30.8 GB
disk_used | 9.6 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | oracle
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Advanced SSH & Web Terminal (19.0.0), AppDaemon (0.16.6), File editor (5.8.0), ESPHome (2024.9.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 0
views | 6
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | October 1, 2024 at 1:58 PM
-- | --
current_recorder_run | October 6, 2024 at 1:34 PM
estimated_db_size | 1679.50 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

**Comment by muratcorlu** [comment]
This problem occurs also on Terminal and Visual Studio Code Server addons.
