### ISSUE TITLE
the "listen ... http2" directive is deprecated

### ISSUE THREAD

**Issue by Pastaloverzzz** [home-assistant/addons#3791]
### Describe the issue you are experiencing

Hi, in the system logs i'm getting the following depreciation messages for listen ... http2:

`[01:01:31] INFO: Running nginx...
nginx: [warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead in /etc/nginx.conf:30
nginx: [warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead in /etc/nginx.conf:54`

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

NGINX Home Assistant SSL Proxy

### What is the version of the add-on?

3.11.0

### Steps to reproduce the issue

1

### System Health information

/

**Comment by RonnieDilli** [comment]
I just submitted the #3804 pull request that aims to fix this particular issue.
