### ISSUE TITLE
Let’s Encrypt add-on version mismatch

### ISSUE THREAD

**Issue by gunverth** [home-assistant/addons#3846]
### Describe the issue you are experiencing

Changelog says 5.2.6 as latest.
Home Assistant says 5.2.5. as latest

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Let's Encrypt

### What is the version of the add-on?

5.2.5

### Steps to reproduce the issue

-

### System Health information

-

### Additional information

You cannot update to the latest version 5.2.6
New HAOS installations also gets version 5.2.5 addon.

**Comment by agners** [comment]
Hm, I see PR #3838 missed bumping the version.

I am about to merge #3749, then things should be fine again.
