### ISSUE TITLE
openwakeword.wav file in backup almost 2 gigs

### ISSUE THREAD

**Issue by dovy6** [home-assistant/addons#3858]
### Describe the issue you are experiencing

I've noticed my HA backups ballooned in size and I'm finally taking the time to troubleshoot it. I downloaded the most recent backup file, which has several sub-backup files. Most of them are reasonable in size, a few kilobytes to several megabytes in size. One, though, is over a gigabyte. It's title is "share.tar.gz," and it consists of three folders, and a 2 kb text file named check_config.txt

1 folder is empty, one folder contains a few json files and a log file, and the last is named assist_pipeline, contains a folder that's a string of hex, and in that folder is another called Home Assistant, followed by a folder with a string of numbers. Inside of that, though, is a file named 00_wake-wake_word.openwakeword.wav
This file is 1.78 gigabytes large! 

Is this expected behavior? Why is openwakeword saving such a large wav file, and why is it being backed up??

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Whisper

### What is the version of the add-on?

openWakeWord Current version: 1.10.0

### Steps to reproduce the issue

Not sure why openWakeWord isn't an option to select in the drop down. It is an official add on, right?

1. Install openwakeword, and configure and start the add on
2. Wait an unknown amount of time
3. Check your backups as they get larger and larger, and wonder what's making them so large
4. Finally download one of the backups and check for what file is so huge.
...

## System Information

version | core-2024.12.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.13.0
os_name | Linux
os_version | 6.6.63-haos
arch | x86_64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.1
Stage | running
Available Repositories | 1547
Downloaded Repositories | 23

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 14.0
-- | --
update_channel | stable
supervisor_version | supervisor-2024.11.4
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 57.7 GB
disk_used | 32.9 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Cloudflared (5.2.2), File editor (5.8.0), Home Assistant Google Drive Backup (0.112.1), Log Viewer (0.17.1), Mosquitto broker (6.4.1), Node-RED (18.1.1), Piper (1.5.2), Samba share (12.3.2), Simple Scheduler (2.5), Tailscale (0.24.0), Zigbee2MQTT (1.42.0-1), openWakeWord (1.10.0), Advanced SSH & Web Terminal (19.0.0), Whisper (2.2.0), Glances (0.21.1), Music Assistant Server (beta) (2.4.0b7), Studio Code Server (5.17.3)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 12
views | 20
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | November 27, 2024 at 3:18 PM
-- | --
current_recorder_run | December 9, 2024 at 4:01 PM
estimated_db_size | 717.08 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Anything in the add-on logs that might be useful for us?

```txt
DEBUG:wyoming_openwakeword.handler:Client connected: 406674355432070
DEBUG:wyoming_openwakeword.handler:Sent info to client: 406674355432070
DEBUG:wyoming_openwakeword.handler:Client disconnected: 406674355432070
DEBUG:wyoming_openwakeword.handler:Client connected: 406706403273569
DEBUG:wyoming_openwakeword.handler:Sent info to client: 406706403273569
DEBUG:wyoming_openwakeword.handler:Client disconnected: 406706403273569
DEBUG:wyoming_openwakeword.handler:Client connected: 406738445691681

This is repeated with different numbers but again and again and again
```

### Additional information

![image](https://github.com/user-attachments/assets/8240b538-41be-423e-9978-dd3614fdba48)

**Comment by synesthesiam** [comment]
Did you turn on debug recording in assist pipeline and leave it running?

**Comment by agners** [comment]
> Is this expected behavior? Why is openwakeword saving such a large wav file, and why is it being backed up??

The `/share` directory is backed up by default in a full backup. If you create a partial backup, you can de-select that folder.

**Comment by dovy6** [comment]
assist pipline debugging didn't work the way I envisioned, so I disabled it. Seems I'd left behind that wav file. 

I imagined the debug would work that by saving recordings of OWW being triggered, perhaps also with some recordings of when it thinks it hears something but cancels due to not recognizing the wake word. Instead, it seems, it just records a continuous wav file for as long as there is space on the devices. Am I wrong about how it works?

**Comment by synesthesiam** [comment]
This isn't the expected behavior. It usually times out the recording with enough silence, so something else must have happened that I'll need to investigate.
With streaming wake word, it's more difficult to get it right, unfortunately :/

**Comment by dovy6** [comment]
@synesthesiam well, seems like the reason for my initial issue is solved, leftovers from the assist pipeline debugging I attempted. Have any interest in attempting to determine what happened there, or should I just close this issue?

**Comment by synesthesiam** [comment]
Let's close the issue. While I agree that the large file is a problem, I think (1) this is a feature that should be temporarily enabled, and (2) on-device wake word is making this less of a potential problem.

What do you think?

**Comment by dovy6** [comment]
1) debugging was only enabled for a short time, but because for whatever reason it just recorded everything, I guess, it dropped this giant file
2) Is on-device wake word making it's way to android any time soon?
3) yeah I'm going to close this, because the actual issue is in fact resolved...
