### ISSUE TITLE
Samba Share - Access to /config denied, other Shares work

### ISSUE THREAD

**Issue by dafunkydan** [home-assistant/addons#3873]
### Describe the issue you are experiencing

The Share /config can't be access when using Windows 11 Pro 24H2 (Clean Install).
The other Shares (e.g. /backup or /ssl) can be accessed successfully. That goes for both connect to the IP and the UNC Name (homeassistant).
The Error when trying to access /config is (translated) "Probably not the Rights to access this Ressource. Server couldn't process the requested Action".

I didn't find a way to get Debug Level Logs for the Addon. To rule out Errors i tried with SambaNAS as well, and there a Debug Level log could get set.
This Log indicates that the Problem is related to SID or NTLM, falling back to anonymous user when accessing /config. However, i don't get why i can access the other Shares, though. The content of /config gets pulled as well, if i interprete the Log correctly.

With other Machines, e.g. Cx File Explorer under Android, or Windows 10 Home 22H2, i can access /config. As the Problem experienced is with a Clean Install of the most recent Windows Version, the Problem will presumable pop up for a growing Amount of Users.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Samba share

### What is the version of the add-on?

12.3.2

### Steps to reproduce the issue

1. Start Samba share on Homeassistant
2. Do a Clean Install of Windows 11 Pro and Update to current Version 24H2
3. Navigate with Explorer to Homeassistants Samba Adress, e.g. 192.168.128.81 
4. Log in using the configured Credentials
5. Open a Share like /backup with success
6. Try to access the Share /config, it gets denied

## System Information

version | core-2024.12.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.13.0
os_name | Linux
os_version | 6.6.62-haos-raspi
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.1
Stage | running
Available Repositories | 1565
Downloaded Repositories | 38

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 40

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 14.1
-- | --
update_channel | stable
supervisor_version | supervisor-2024.12.0
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 219.4 GB
disk_used | 89.4 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | AdGuard Home (5.2.1), Samba share (12.3.2), Grafana (10.2.2), Mosquitto broker (6.4.1), Terminal & SSH (9.16.0), InfluxDB (5.0.1), TasmoAdmin (0.31.2), SQLite Web (4.3.0), Advanced SSH & Web Terminal (19.0.0), Studio Code Server (5.18.0), ESPHome Device Builder (2024.12.2), Glances (0.21.1), Zigbee2MQTT (1.41.0-1), Zigbee2MQTT Edge (edge), TubesZB Zigpy-CLI Tools (0.3.1.0), Filebrowser (2.23.0_14), MariaDB (2.7.1), Let's Encrypt (5.2.10), Nextcloud (30.0.4), Samba NAS (12.3.2-nas), WireGuard (0.10.2), Vaultwarden (Bitwarden) (0.23.7), Portainer (2.25.1), ESPHome 2023.12 (2023.12.9), Rclone Backup (3.3.3)

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 20
views | 71
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | December 16, 2024 at 09:54
-- | --
current_recorder_run | December 27, 2024 at 09:32
estimated_db_size | 1204.65 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Anything in the add-on logs that might be useful for us?

```txt
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-smbd: starting
[10:33:33] INFO: Hostname: homeassistant
[10:33:33] INFO: Interfaces: wlan0 end0 
tdbsam_open: Converting version 0.0 database to version 4.0.
tdbsam_convert_backup: updated /var/lib/samba/private/passdb.tdb file.
Added user adminha.
s6-rc: info: service init-smbd successfully started
s6-rc: info: service smbd: starting
s6-rc: info: service smbd successfully started
s6-rc: info: service nmbd: starting
s6-rc: info: service nmbd successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
nmbd version 4.18.9 started.
smbd version 4.18.9 started.
Copyright Andrew Tridgell and the Samba Team 1992-2023
Copyright Andrew Tridgell and the Samba Team 1992-2023
INFO: Profiling support unavailable in this build.
*****
Samba name server HOMEASSISTANT is now a local master browser for workgroup WORKGROUP on subnet 192.168.128.81
*****
```

### Additional information

What i already tried.

- Use UNC Path "homeassistant" or direct IP `\\192.168.128.81`
- Browse it with Powershell (e.g. dir in /ssl gets listed, dir in /config results in:
```
    + CategoryInfo          : ReadError: (\\192.168.128.81\config:String) [Get-ChildItem], IOException
    + FullyQualifiedErrorId : DirIOError,Microsoft.PowerShell.Commands.GetChildItemCommand
```
- Map the Server as Network Drive, assign a Letter
- In the Addon, Setting Compatibility Mode (and allowing SMBv1 in Windows)
- Set Maximum SMB Version to 2.0
- Clearing all network connections with net use * /delete
- Group Policy -> Computer Configuration -> Windows Settings -> Security Settings -> Local Policies -> Security Options -> Network security ->
  - Restrict NTLM: Add remote server exceptions for NTLM authentication -> Homeassistants IP
  - Restrict NTLM: Outgoing NTLM traffic to remote Servers: Allow all
  - Restrict NTLM: Incoming NTLM traffic: Allow all

- Group Policy: Disable the SMB client signing requirement and Disable the guest fallback protection 
(according to https://techcommunity.microsoft.com/blog/filecab/accessing-a-third-party-nas-with-smb-in-windows-11-24h2-may-fail/415430

Log of alternative SambaNAS attached:
[sambanas_log.txt](https://github.com/user-attachments/files/18259438/sambanas_log.txt)

**Comment by dafunkydan** [comment]
Solved.
When setting up a File Notification, the file got called `/config/test.txt` (including the Slash).
This threw an Error when accessing the Share/Folder.
Will make the Suggestion to check File Notify for allowed Chars.

**Comment by olivayfuente** [comment]
Hello @dafunkydan. Can you describe how you solved it? I don't quite understand the example you gave of test.txt. I have exactly the same problem as you.
Thanks.

**Comment by dafunkydan** [comment]
Sure, let's see if you really have the same problem 😄
I had one file (created by file notification), that was not called text.txt, but /config/test.txt.
The actual filename started with "/conf....."
This seems to be fine for creating, but threw the Error when trying to access with samba.

Look with Ssh, another file explorer on Homeassistant itself, through the share you wanna map for any irregular filename.

In my case, the culprit was a file in "/config" NAMED “/config/text.txt".
I deleted it (renaming would have probably done the job as well), and everything was fine again.

Hope your problem is similar, so you can apply the solution as well 🍀

**Comment by olivayfuente** [comment]
That's exactly what happened to me, instead of a file in a folder. Fixed it, I deleted it with mobaxtrem. Many many thanks. Greetings.
