### ISSUE TITLE
Mosquitto Broker not allowing me to use additional ports in Hass.io

### ISSUE THREAD

**Issue by cdk222** [home-assistant/addons#707]
I have tried to load additional listener ports (1885, 1886) for Mosquitto MQTT in Hass.io with no luck. In the addon Config page I have set the following correctly:

  "customize": {
    "active": true,
    "folder": "mosquitto"

I have correctly setup the acl.conf and accesscontrollist in /share/mosquitto/ and they are found by the addon.

To then get the additional ports I have configured an additional mosquitto.conf file in the /share/Mosquitto and it only contains 4 lines: 

listener 1885
protocol mqtt
listener 1886
protocol mqtt

The Mosquitto logs indicate that it has seen the additional ports and have loaded correctly (as seen below); however when i then attempt to connect to the broker on either 1885 or 1886 it simply wont connect. 1883 is fine and works and I have also successfully testing all my user/password combos on 1883 and they work too. Just have no idea what the issue is

[01:28:58] INFO: Setup mosquitto configuration
[01:28:58] WARNING: SSL not enabled - No valid certs found!
[01:28:58] INFO: Found local users inside config
[01:28:58] INFO: Initialize Hass.io Add-on services
[01:28:58] INFO: Initialize Home Assistant discovery
[01:28:58] INFO: Start Mosquitto daemon
1569086938: Loading config file /share/mosquitto/acl.conf
1569086938: Loading config file /share/mosquitto/mosquitto.conf
1569086938: mosquitto version 1.6.3 starting
1569086938: Config loaded from /etc/mosquitto.conf.
1569086938: Loading plugin: /usr/share/mosquitto/auth-plug.so
1569086938: |-- *** auth-plug: startup
1569086938:  ├── Username/password checking enabled.
1569086938:  ├── TLS-PSK checking enabled.
1569086938:  └── Extended authentication not enabled.
1569086938: Opening ipv4 listen socket on port 1885.
1569086938: Opening ipv6 listen socket on port 1885.
1569086938: Opening ipv4 listen socket on port 1886.
1569086938: Opening ipv6 listen socket on port 1886.
1569086938: Opening ipv4 listen socket on port 1883.
1569086938: Opening ipv6 listen socket on port 1883.
1569086938: Opening websockets listen socket on port 1884.

**Comment by cdk222** [comment]
I should add that if I go inside the Mosquitto Docker container and edit the mosquitto.conf file then 1885 and 1886 work fine. Problem is as soon a the container restarts then the config is lost. I dont want to create a volume because as soon as there is an Addon-update then those changes will be lost again.

Is is possible to have a volume/mount created in the next version of the addon so that the mosquitto.conf file can be persistent.....able to be manipulated from the host?

**Comment by frenck** [comment]
I've looked at this for the current refactoring of the mosquito add-on, but we can't/should not add this. It requires to drop the add-on to host networking level, which is really unneeded.

If you are desperately in need for a solution like this, the add-on might not be the best option for you.
